const {chromium}=require('playwright-core'),fs=require('node:fs/promises'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
(async()=>{
 const manifest=JSON.parse(await fs.readFile(process.env.RELEASE_ARTIFACTS||'/tmp/zoi-organizer-navigation-production.json'));
 const evidence={commit:manifest.commit,deployment:manifest.deployment,artifacts:[],entry:[],canonical:[]};
 for(const item of manifest.artifacts){const source=execFileSync('git',['show',manifest.commit+':'+item.file]);assert.equal(crypto.createHash('sha256').update(source).digest('hex'),item.sha256);const r=await fetch('https://www.zoi.city/'+item.file,{signal:AbortSignal.timeout(15000)});assert.equal(r.status,200,item.file);assert.equal(crypto.createHash('sha256').update(Buffer.from(await r.arrayBuffer())).digest('hex'),item.sha256,item.file);evidence.artifacts.push({...item,exactMainBytes:true});}
 const browser=await chromium.launch({executablePath:'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});
 try{for(const width of[390,1440]){
  const p=await browser.newPage({viewport:{width,height:900},serviceWorkers:'block'}),errors=[],privateRequests=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(r.method()!=='GET'||/\/rest\/v1\/|\/auth\/v1\/|\/functions\/v1\/|\/api\//.test(u.pathname)){privateRequests.push(u.pathname);return route.abort();}return route.continue();});
  await p.goto('https://www.zoi.city/tickets/hosts/?event=11111111-1111-4111-8111-111111111111',{waitUntil:'networkidle'});await p.getByRole('heading',{name:'Sign in',exact:true}).waitFor();assert.equal(await p.locator('[data-organizer-setup],[data-form=grant],[data-roster]').count(),0);assert.deepEqual(errors,[]);assert.deepEqual(privateRequests,[]);evidence.entry.push({width,signedOut:true,privateSurfaceAbsent:true,pageErrors:[]});await p.close();
  for(const reducedMotion of['no-preference','reduce'])for(const dest of['/business/signatureproductions-6aa61d','/business/ke-nairobi-yamas-greek-restaurant']){
   const page=await browser.newPage({viewport:{width,height:900},reducedMotion,serviceWorkers:'block'}),pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));await page.addInitScript(()=>addEventListener('pagereveal',e=>{if(!location.pathname.startsWith('/business/'))return;window.navigationProbe={transition:!!e.viewTransition};if(e.viewTransition){e.viewTransition.ready.then(()=>navigationProbe.ready=true);e.viewTransition.finished.then(()=>navigationProbe.finished=true);}}));
   await page.goto('https://www.zoi.city/',{waitUntil:'domcontentloaded'});await page.evaluate(path=>{const a=document.createElement('a');a.href=path+'?navigation-check=kept#contact';a.id='navigation-review-link';a.textContent='Open reviewed home';document.body.prepend(a);},dest);await page.locator('#navigation-review-link').click();await page.waitForURL('**'+dest+'?navigation-check=kept#contact');await page.locator('h1').first().waitFor();await page.waitForFunction(()=>!!window.navigationProbe);assert.equal(await page.locator('[data-zoi-navigation]').count(),1);assert.equal(await page.evaluate(()=>navigationProbe.transition),reducedMotion==='no-preference');if(reducedMotion==='no-preference')await page.waitForFunction(()=>navigationProbe.ready&&navigationProbe.finished);assert.deepEqual(pageErrors,[]);evidence.canonical.push({width,reducedMotion,path:dest,transitionFinished:reducedMotion==='no-preference',pageErrors:[]});await page.close();
  }
 }}finally{await browser.close();}
 await fs.mkdir('docs/audits/evidence',{recursive:true});await fs.writeFile('docs/audits/evidence/organizer-navigation-production-2026-10-02.json',JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence));
})().catch(e=>{console.error(e);process.exitCode=1;});
