const {chromium}=require('playwright-core'),assert=require('node:assert/strict');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),actor=id(1),ws=id(9),other=id(10);
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});try{for(const width of[390,1440])for(const role of['owner','editor','viewer']){
 const p=await browser.newPage({viewport:{width,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{sessionStorage.setItem('zoi.mobile.refresh.v1',JSON.stringify({refresh_token:'fixture'}));window.open=url=>{window.openedUrl=url;return null;};});
 await p.route('https://csebihpaychdkanjjsmz.supabase.co/**',async r=>{const u=new URL(r.request().url());let body=[];if(u.pathname==='/auth/v1/token')body={access_token:'fixture',refresh_token:'fixture',expires_at:Math.floor(Date.now()/1000)+3600,user:{id:actor,email:'qa@example.invalid'}};else if(u.pathname.endsWith('/zoi_me'))body={authenticated:true,workspaces:[{id:ws,name:'Event team',role},{id:other,name:'Other team',role}]};await r.fulfill({contentType:'application/json',body:JSON.stringify(body)});});
 await p.goto(process.env.EXPO_ORIGIN||'http://127.0.0.1:8359');await p.getByRole('tab',{name:/Grow/}).click();const menu=p.getByRole('button',{name:'Menu & event service on web ↗',exact:true}),queue=p.getByRole('button',{name:'Kitchen & bar queue on web ↗',exact:true});
 await p.getByRole('radio',{name:/Event team/}).waitFor();if(role==='viewer'){assert.equal(await menu.count(),0);assert.equal(await queue.count(),0);}else{await menu.click();assert.equal(await p.evaluate(()=>window.openedUrl),'https://www.zoi.city/social/service-menu?workspace='+ws);await queue.click();assert.equal(await p.evaluate(()=>window.openedUrl),'https://www.zoi.city/social/service-queue?workspace='+ws);await p.getByRole('radio',{name:/Other team/}).click();await menu.click();assert.equal(await p.evaluate(()=>window.openedUrl),'https://www.zoi.city/social/service-menu?workspace='+other);}
 assert.equal(await p.locator('body').evaluate(e=>e.scrollWidth<=innerWidth),true);await p.screenshot({path:'/tmp/zoi-service-native-'+width+'-'+role+'.png',fullPage:true});await p.getByRole('button',{name:'Sign out',exact:true}).click();await p.getByRole('button',{name:'Sign in',exact:true}).waitFor();assert.equal(await menu.count(),0);assert.equal(await queue.count(),0);assert.deepEqual(errors,[]);console.log('PASS actual compiled Account service handoff',width,role,'current workspace/no token/role/signout');await p.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
