const{chromium}=require('playwright-core'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');const root=path.resolve(__dirname,'../../..'),server=http.createServer(async(req,res)=>{try{const p=new URL(req.url,'http://local').pathname,f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',p.endsWith('.html')?'text/html':'text/javascript');res.end(await fs.readFile(f));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const origin='http://127.0.0.1:'+server.address().port;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});for(const width of[390,1440]){const p=await browser.newPage({viewport:{width,height:1000}});await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await p.goto(origin+'/tests/browser/service-queue/fixture.html');await p.getByRole('button',{name:'Start preparing',exact:true}).waitFor();await p.locator('.zservice-queue').screenshot({path:'/tmp/zoi-service-queue-'+width+'.png'});await p.getByRole('button',{name:'Start preparing',exact:true}).click();await p.getByRole('button',{name:'Mark ready',exact:true}).waitFor();assert.equal(await p.evaluate(()=>qa.row.revision),2);
await p.evaluate(()=>qa.mode='lost');await p.getByRole('button',{name:'Mark ready',exact:true}).click();await p.getByRole('button',{name:'Check update result'}).waitFor();await p.evaluate(()=>{qa.mode='ok';qa.mount();});await p.getByRole('button',{name:'Check update result'}).click();await p.getByRole('button',{name:'Mark delivered',exact:true}).waitFor();assert.equal(await p.evaluate(()=>qa.row.revision),3);assert.equal(await p.evaluate(()=>qa.handle.hasUnsavedChanges()),false);
await p.evaluate(()=>qa.mode='notsent');await p.getByRole('button',{name:'Mark delivered',exact:true}).click();await p.getByRole('button',{name:'Cancel unconfirmed update'}).click();await p.getByText('Unconfirmed update cancelled. The order was not cancelled.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>qa.row.fulfillment_status),'ready');await p.evaluate(()=>qa.mode='ok');await p.getByRole('button',{name:'Mark delivered',exact:true}).click();await p.getByText('No active orders for this station.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>qa.row.revision),4);
await p.evaluate(()=>{qa.mode='ok';qa.row.fulfillment_status='received';qa.mount();});await p.getByRole('button',{name:'Start preparing',exact:true}).waitFor();await p.evaluate(()=>qa.mode='wrongscope');await p.getByRole('button',{name:'Refresh queue',exact:true}).click();await p.getByText('The queue response could not be verified.',{exact:true}).waitFor();assert.equal(await p.getByText('Alex',{exact:false}).count(),0);
await p.evaluate(()=>{qa.mode='ok';qa.mount();});await p.getByRole('button',{name:'Start preparing',exact:true}).waitFor();await p.evaluate(()=>qa.mode='denied');await p.getByRole('button',{name:'Refresh queue',exact:true}).click();await p.getByText('Request failed',{exact:true}).waitFor();assert.equal(await p.getByText('Alex',{exact:false}).count(),0);
await p.evaluate(()=>{qa.mode='ok';qa.mount();});await p.getByRole('button',{name:'Start preparing',exact:true}).waitFor();await p.evaluate(()=>{qa.holdRefresh=true;qa.before=qa.calls.length;});await p.getByRole('button',{name:'Refresh queue',exact:true}).click();await p.waitForFunction(()=>typeof qa.releaseRefresh==='function');await p.evaluate(()=>{qa.actor='00000000-0000-4000-8000-000000000099';qa.releaseRefresh();});await p.waitForTimeout(60);assert.equal(await p.evaluate(()=>qa.calls.length-qa.before),0);assert.equal(await p.getByText('Alex',{exact:false}).count(),0);
await p.evaluate(()=>{qa.actor='00000000-0000-4000-8000-000000000002';qa.holdRefresh=false;qa.mode='ok';qa.mount();});await p.getByRole('button',{name:'Start preparing',exact:true}).waitFor();await p.evaluate(()=>{qa.refreshOk=false;qa.before=qa.calls.length;});await p.getByRole('button',{name:'Refresh queue',exact:true}).click();await p.getByText('Your session could not be refreshed. Sign in again.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>qa.calls.length-qa.before),0);assert.equal(await p.getByText('Alex',{exact:false}).count(),0);
assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);console.log('PASS service queue',width,'forward lifecycle, lost receipt, cancel-update distinction, private denial/scope clear, refresh account fencing');await p.close();}}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
