const{chromium}=require('playwright-core'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'../../..'),id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),ws=id(100),owner=id(1),recipient=id(2);
const html=`<!doctype html><meta name="viewport" content="width=device-width"><style>:root{--line:#456;--tx:#eef;--mut:#abc;--bg2:#10283f;--bg3:#071729;--acc:#91ddf3}*{box-sizing:border-box}body{background:#081725;color:#eef;font:16px system-ui;margin:20px}main{max-width:800px;margin:auto}button,input,select{font:inherit;padding:12px;max-width:100%;margin:4px}label{display:block}.zs-actions{display:flex;flex-wrap:wrap}</style><main id="app"></main><script src="/assets/zoi-core.js"></script><script src="/assets/suite/settings.js"></script><script>window.mount=()=>ZoiSuite.modules.find(m=>m.id==='settings').mount(document.getElementById('app'),{C:ZoiCore,ws:'${ws}',toast:()=>{}});mount();</script>`;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost'),p=u.pathname;res.setHeader('Content-Type',p.endsWith('.mjs')||p.endsWith('.js')?'text/javascript':p.endsWith('.png')?'image/png':'text/html');res.end(p==='/owner'?html:await fs.readFile(path.join(base,p.endsWith('/')?p+'index.html':p)));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;let browser;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});for(const width of[390,1440]){let invitation=null,secret='',receipts={},mode='ok',previewFail=false,member=false,calls=[];const context=await browser.newContext({viewport:{width,height:900}}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(({owner})=>{if(!localStorage.getItem('zoi_auth'))localStorage.setItem('zoi_auth',JSON.stringify({user_id:owner,access_token:'test',expires_at:Math.floor(Date.now()/1000)+3600}));},{owner});
 await context.route('https://csebihpaychdkanjjsmz.supabase.co/**',async route=>{const req=route.request(),fn=req.url().split('/').at(-1),a=req.postDataJSON()||{};calls.push({fn,a});let r,status=200;
 if(fn==='workspace_settings_get')r={ok:true,workspace_id:ws,role:'owner',identity:{name:'Signature team',version:id(31)},voice:{version:id(32),business_name:'Signature',about:'',tone:'Professional',languages:'English',sample:''}};else if(fn==='workspace_team_get')r={ok:true,workspace_id:ws,role:'owner',actor_profile_id:owner,members:[{id:id(11),profile_id:owner,name:'Owner',role:'owner',revision:id(21),protected:true}]};else if(fn==='workspace_invitation_list'){if(mode==='listfail'){status=503;r={message:'offline'};}else r={ok:true,workspace_id:ws,role:'owner',invitations:invitation?[invitation]:[]};}
 else if(fn==='workspace_invitation_create'){secret=a.p_token;invitation={id:a.p_id,workspace_id:ws,recipient_email:a.p_email,role:a.p_role,state:'pending',revision:id(20),expires_at:a.p_expires_at};r={ok:true,workspace_id:ws,request_id:a.p_request,operation:'create',invitation};receipts[a.p_request]=r;if(mode==='lost'){return route.abort();}}
 else if(fn==='workspace_invitation_preview'){if(previewFail){status=403;r={message:'invitation_unavailable'};}else r={ok:true,id:invitation.id,workspace_id:ws,workspace_name:'Signature production team',role:invitation.role,state:invitation.state,revision:invitation.revision,expires_at:invitation.expires_at,auth_user_id:recipient,actor_profile_id:member?id(88):null,current_member:member,current_role:member?'editor':null};}
 else if(fn==='workspace_invitation_accept'){r={ok:true,workspace_id:ws,request_id:a.p_request,operation:'accept',member_id:id(80),profile_id:id(88),invitation_id:invitation.id};if(mode==='unknown')return route.abort();if(mode==='conflict')r={ok:false,error:'invitation_conflict',workspace_id:ws,request_id:a.p_request,operation:'accept'};else{member=true;invitation.state='accepted';}receipts[a.p_request]=r;if(mode==='acceptlost')return route.abort();if(mode==='acceptreadfail')previewFail=true;}
 else if(fn==='workspace_invitation_request'){if(a.p_cancel_if_missing&&!receipts[a.p_request])receipts[a.p_request]={ok:false,cancelled:true,workspace_id:ws,request_id:a.p_request,operation:a.p_operation};r={ok:true,workspace_id:ws,request_id:a.p_request,operation:a.p_operation,found:!!receipts[a.p_request],result:receipts[a.p_request]};}
 else if(fn==='workspace_invitation_revoke'){invitation.state='revoked';invitation.revision=id(22);r={ok:true,workspace_id:ws,request_id:a.p_request,operation:'revoke',invitation};receipts[a.p_request]=r;}
 else throw Error('Unexpected network '+fn);await route.fulfill({status,contentType:'application/json',body:JSON.stringify(r)});});
 await p.goto(origin+'/owner');await p.getByLabel('Colleague email').fill('recipient@example.test');mode='lost';await p.getByRole('button',{name:'Create invitation link',exact:true}).click();await p.getByRole('button',{name:'Check invitation change',exact:true}).waitFor();await p.reload();await p.getByRole('button',{name:'Check invitation change',exact:true}).click();await p.getByRole('button',{name:'Copy invitation link',exact:true}).waitFor();assert.match(secret,/^[a-f0-9]{64}$/);assert.equal(calls.filter(c=>c.fn==='workspace_invitation_create').length,1);await p.screenshot({path:'/tmp/workspace-invite-owner-'+width+'.png',fullPage:true});assert.equal(await p.locator('body').evaluate(e=>e.scrollWidth<=innerWidth),true);
 await p.evaluate(recipient=>ZoiCore.auth.save({user_id:recipient,access_token:'test2',expires_at:Math.floor(Date.now()/1000)+3600}),recipient);mode='conflict';await p.goto(origin+'/workspace/join/#token='+secret);await p.getByRole('button',{name:'Join organization',exact:true}).waitFor();assert.equal(new URL(p.url()).hash,'');assert.equal(calls.some(c=>c.fn==='workspace_invitation_accept'),false);await p.screenshot({path:'/tmp/workspace-invite-recipient-'+width+'.png',fullPage:true});await p.getByRole('button',{name:'Join organization',exact:true}).click();await p.getByRole('button',{name:'Check join request',exact:true}).waitFor();await p.getByRole('button',{name:'Check join request',exact:true}).click();await p.getByRole('button',{name:'Join organization',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Check join request',exact:true}).count(),0);
 mode='unknown';await p.getByRole('button',{name:'Join organization',exact:true}).click();await p.getByRole('button',{name:'Check join request',exact:true}).waitFor();previewFail=true;await p.getByRole('button',{name:'Cancel unconfirmed join request',exact:true}).click();await p.getByText(/Unconfirmed join request cancelled/).waitFor();await p.getByRole('button',{name:'Check join request',exact:true}).waitFor({state:'detached'});assert.equal(await p.getByRole('button',{name:'Check join request',exact:true}).count(),0);
 previewFail=false;mode='acceptreadfail';await p.getByRole('button',{name:'Check invitation again',exact:true}).click();await p.getByRole('button',{name:'Join organization',exact:true}).click();await p.getByText(/Invitation acceptance confirmed/).waitFor();await p.getByRole('button',{name:'Check join request',exact:true}).waitFor({state:'detached'});assert.equal(await p.getByRole('button',{name:'Check join request',exact:true}).count(),0);previewFail=false;await p.getByRole('button',{name:'Check invitation again',exact:true}).click();await p.getByRole('link',{name:'Open your workspace',exact:true}).waitFor();assert.equal(await p.locator('body').evaluate(e=>e.scrollWidth<=innerWidth),true);await p.evaluate(owner=>{ZoiCore.auth.save({user_id:owner,access_token:'owner',expires_at:Math.floor(Date.now()/1000)+3600});dispatchEvent(new Event('focus'));},owner);await p.getByText(/Invitation response could not be verified/).waitFor();assert.equal(await p.getByRole('button',{name:'Join organization',exact:true}).count(),0);assert.equal(await p.getByRole('link',{name:'Open your workspace',exact:true}).count(),0);assert.equal(await p.getByRole('heading',{name:'Signature production team',exact:true}).count(),0);assert.equal(calls.some(c=>c.fn.includes('otp')),false);assert.deepEqual(errors,[]);console.log('PASS invitation',width,'actual ZoiCore transport, owner lost-response recovery, recipient fragment privacy, conflict recovery, cancellation with revoked preview, accepted response with failed refresh');await context.close();}}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
