import test from 'node:test';import assert from 'node:assert/strict';
import {SessionClient}from'../src/session.ts';import{ownerAccessRefused}from'../src/businessOwner.ts';
const codes=['suite_session_unavailable','invitation_unavailable','verified_account_required','not_authorized','no_access_to_listing','no_access_to_workspace','not_signed_in'];
const paths=['home_content_get','home_content_save','bizpage_status'];
const client=(message,status=400)=>new SessionClient({read:async()=>null,write:async()=>{},clear:async()=>{}},async()=>new Response(JSON.stringify({message,code:'42501',details:'private owner@example.invalid',hint:'private-provider-token'}),{status,headers:{'Content-Type':'application/json'}}));
test('actual owner authority HTTP400 preserves exact safe code and proves private state refusal',async()=>{for(const name of paths)for(const code of codes){await assert.rejects(client(code).request('/rest/v1/rpc/'+name,{}),error=>{assert.equal(error.status,400);assert.equal(error.code,code);assert.equal(ownerAccessRefused(error),true);assert(!error.message.includes(code));assert(!JSON.stringify(error).includes('owner@example'));assert(!JSON.stringify(error).includes('private-provider'));return true;});}});
test('generic HTTP400 and transient failures stay uncertain; no broad payload or code disclosure',async()=>{for(const message of ['unknown application error','suite_session_unavailable: private detail','version_conflict'])await assert.rejects(client(message).request('/rest/v1/rpc/home_content_save',{}),error=>{assert.equal(error.code,undefined);assert.equal(ownerAccessRefused(error),false);assert(!error.message.includes('private detail'));return true;});await assert.rejects(client('suite_session_unavailable',503).request('/rest/v1/rpc/home_content_get',{}),error=>{assert.equal(error.code,undefined);assert.equal(ownerAccessRefused(error),false);return true;});});
test('bounded code retention does not alter other suites/auth/provider error handling',async()=>{for(const path of ['/rest/v1/rpc/ops_record_save','/rest/v1/rpc/community_feed','/auth/v1/token'])await assert.rejects(client('suite_session_unavailable').request(path,{}),error=>{assert.equal(error.code,undefined);return true;});});

const operatorPaths=['ops_records_list','ops_audit_list','ops_mutation_execute','ops_request_status','documents_list','document_history','document_archive'];
test('exact existing Company and document authority RPCs preserve safe codes and actual status only',async()=>{for(const name of operatorPaths)for(const code of [...codes,'company_permission_denied',...(name.startsWith('ops_')?['ops_permission_denied','insufficient_permission']:['document_permission_denied'])])for(const status of [400,401,403]){await assert.rejects(client(code,status).request('/rest/v1/rpc/'+name,{}),error=>{assert.equal(error.status,status);assert.equal(error.code,code);assert(!error.message.includes(code));assert(!JSON.stringify(error).includes('owner@example'));assert(!JSON.stringify(error).includes('private-provider'));return true;});}});
test('operator code recognition remains bounded to exact path, exact message and authority status',async()=>{for(const path of ['/rest/v1/rpc/community_feed','/auth/v1/token','/rest/v1/rpc/ops_records_list?extra=1','/rest/v1/rpc/ops_record_save'])for(const code of ['company_permission_denied','ops_permission_denied','document_permission_denied'])await assert.rejects(client(code).request(path,{}),error=>{assert.equal(error.code,undefined);return true;});for(const name of operatorPaths)for(const [code,status]of [['suite_session_unavailable: private detail',400],['version_conflict',400],['unknown application error',400],['suite_session_unavailable',503]])await assert.rejects(client(code,status).request('/rest/v1/rpc/'+name,{}),error=>{assert.equal(error.code,undefined);return true;});for(const name of paths)for(const code of ['company_permission_denied','ops_permission_denied','document_permission_denied'])await assert.rejects(client(code).request('/rest/v1/rpc/'+name,{}),error=>{assert.equal(error.code,undefined);return true;});});
