import test from 'node:test';import assert from 'node:assert/strict';import {CreatorRecovery,creatorActions} from '../src/creatorRecovery.ts';
const actor='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',request='33333333-3333-4333-8333-333333333333';
function fixture(){let stored=null,active=true,calls=[],handler=async()=>{throw Error('lost')};const store={load:async()=>structuredClone(stored),save:async(_,v)=>{stored=structuredClone(v)},clear:async()=>stored=null};const make=()=>new CreatorRecovery(store,actor,()=>active,async(n,p)=>{calls.push([n,structuredClone(p)]);return handler(n,p)},()=>request);return {store,make,calls,get stored(){return stored},set stored(v){stored=v},set handler(v){handler=v},set active(v){active=v}};}
const saved=action=>({ok:true,state:'saved',request_id:request,action,campaign_id:id,entity_id:id});
test('all seven actions execute through durable nonce-only wrapper and validate receipt',async()=>{for(const action of creatorActions){const f=fixture(),r=f.make();await r.load();f.handler=async(n,p)=>{assert.equal(n,'creator_mutation_execute');assert.deepEqual(Object.keys(f.stored).sort(),['action','actor','request']);assert.equal(JSON.stringify(f.stored).includes('PRIVATE'),false);assert.equal(p.p_args.p_request,undefined);return saved(action);};await r.send(action,{p_campaign:id,p_data:{summary:'PRIVATE'},p_request:'old'});assert.equal(f.stored,null);}});
test('lost response blocks replacement, exact retry retains immutable memory payload',async()=>{const f=fixture(),r=f.make();await r.load();const args={p_campaign:id,p_data:{summary:'PRIVATE'}};await assert.rejects(r.send('creator_draft_save',args));args.p_data.summary='CHANGED';await assert.rejects(r.send('creator_draft_save',args));f.handler=async()=>saved('creator_draft_save');await r.recover('retry');assert.deepEqual(f.calls[0],f.calls[1]);assert.equal(f.stored,null);});
test('reload has no payload, missing receipt retains fence, cancellation requires exact proof',async()=>{const f=fixture(),r=f.make();await r.load();await assert.rejects(r.send('creator_draft_save',{p_campaign:id}));const next=f.make();await next.load();assert.equal(next.payload,null);await assert.rejects(next.recover('retry'));f.handler=async()=>({ok:true,state:'missing',request_id:request});await next.recover('check');assert.ok(next.marker);f.handler=async()=>({ok:true,state:'cancelled',request_id:id});await assert.rejects(next.recover('cancel'));assert.ok(next.marker);f.handler=async()=>({ok:true,state:'cancelled',request_id:request});await next.recover('cancel');assert.equal(f.stored,null);});
test('permission denial drops private payload without deleting recovery reference',async()=>{const f=fixture(),r=f.make();await r.load();await assert.rejects(r.send('creator_draft_save',{p_campaign:id,p_data:{summary:'PRIVATE'}}));r.dropPayload();assert.equal(r.payload,null);assert.ok(f.stored);f.handler=async()=>{throw Object.assign(Error('creator_permission_denied'),{status:403})};await assert.rejects(r.recover('check'));assert.ok(f.stored);});
test('storage failure, corrupt marker and late account change cannot permit dispatch or acknowledgement',async()=>{const f=fixture();f.store.save=async()=>{throw Error('storage')};const r=f.make();await r.load();await assert.rejects(r.send('creator_convert',{}));assert.equal(f.calls.length,0);assert.equal(r.ready,false);f.stored={actor,request,action:'creator_convert',private:'forbidden'};await assert.rejects(f.make().load());const g=fixture(),next=g.make();await next.load();g.handler=async()=>{g.active=false;return saved('creator_convert')};await assert.rejects(next.send('creator_convert',{}));assert.ok(g.stored);});
test('mismatched saved entity does not discard recovery reference',async()=>{const f=fixture(),r=f.make();await r.load();f.handler=async()=>({...saved('creator_deliverable_save'),entity_id:request});await assert.rejects(r.send('creator_deliverable_save',{p_campaign:id,p_id:id}));assert.ok(f.stored);});
test('account switch during persisted readback prevents dispatch',async()=>{const f=fixture(),r=f.make();await r.load();const original=f.store.load;f.store.load=async()=>{const result=await original();f.active=false;return result;};await assert.rejects(r.send('creator_convert',{}));assert.equal(f.calls.length,0);assert.ok(f.stored);});
