import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{stripTypeScriptTypes}from'node:module';
const source=fs.readFileSync(new URL('../src/eventHostLink.ts',import.meta.url),'utf8');const{guestEventHostLink,organiserEventHostLink}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
const event='40000000-0000-4000-8000-000000000001',workspace='30000000-0000-4000-8000-000000000001',actor='10000000-0000-4000-8000-000000000001',profile='20000000-0000-4000-8000-000000000001';
function fixture(){const f={active:true,role:'admin',calls:[],me:{profile:{id:profile},workspaces:[{id:workspace,role:'admin'}]},inventory:{ok:true,event_id:event,version:1,tables:[]}};f.args={event,workspace,actor,current:()=>f.active,rpc:async(n,p)=>{f.calls.push({n,p});return n==='zoi_me'?f.me:f.inventory;}};return f;}
test('guest link carries only canonical selected event, never credentials',()=>{assert.equal(guestEventHostLink(event.toUpperCase()),'https://www.zoi.city/tickets/hosts/?event='+event);for(const value of['',event+'&token=secret','https://evil.test'])assert.throws(()=>guestEventHostLink(value));});
test('organiser handoff validates exact selected workspace and event with fresh authority',async()=>{const f=fixture();f.me.workspaces.unshift({id:profile,role:'owner'});assert.equal(await organiserEventHostLink(f.args),'https://www.zoi.city/tickets/hosts/?event='+event+'&workspace='+workspace);assert.deepEqual(f.calls[1],{n:'table_inventory_operator',p:{p_workspace:workspace,p_event:event}});});
test('viewer, missing, duplicate and malformed memberships cannot produce operator link',async()=>{for(const workspaces of[[{id:workspace,role:'viewer'}],[],[{id:workspace,role:'admin'},{id:workspace,role:'owner'}],null]){const f=fixture();f.me.workspaces=workspaces;await assert.rejects(organiserEventHostLink(f.args));assert.equal(f.calls.length,1);}});
test('selected workspace never falls back to first membership',async()=>{const f=fixture();f.args.workspace='';await assert.rejects(organiserEventHostLink(f.args));assert.equal(f.calls.length,0);});
test('wrong event and denied operator proof cannot open a link',async()=>{const f=fixture();f.inventory.event_id=profile;await assert.rejects(organiserEventHostLink(f.args));f.args.rpc=async()=>{throw Error('not_authorized');};await assert.rejects(organiserEventHostLink(f.args));});
test('late account/workspace switches fence membership and operator responses',async()=>{for(const held of['zoi_me','table_inventory_operator']){const f=fixture();let release;f.args.rpc=async n=>{if(n===held)await new Promise(r=>release=r);return n==='zoi_me'?f.me:f.inventory;};const job=organiserEventHostLink(f.args);while(!release)await new Promise(r=>setImmediate(r));f.active=false;release();await assert.rejects(job,/changed/);}});
