import test from'node:test';import assert from'node:assert/strict';import{GeneralReservationGuard}from'../src/generalReservation.ts';
const attempt={actor:'actor-a',event:'event-a',tier:'1',id:'request-a',created_at:'2026-09-30T12:00:00Z'},receipt={ok:true,code:'real',qty:2,amount_cents:0,paid:false};
const store=()=>{const m=new Map();return{getItem:async k=>m.get(k)||null,setItem:async(k,v)=>{m.set(k,v)},removeItem:async k=>{m.delete(k)}}};
test('interrupted reservation remains blocked after remount and across tier changes, scoped to actor and event',async()=>{const s=store(),g=new GeneralReservationGuard(s);await g.begin(attempt,()=>true);const again=new GeneralReservationGuard(s);assert.deepEqual(await again.read('actor-a','event-a'),attempt);await assert.rejects(again.begin({...attempt,id:'second',tier:'2'},()=>true));assert.equal(await again.read('actor-b','event-a'),null);assert.equal(await again.read('actor-a','event-b'),null);});
test('only exact confirmed free receipt clears original attempt; malformed and stale confirmations preserve warning',async()=>{const g=new GeneralReservationGuard(store());await g.begin(attempt,()=>true);for(const r of[{...receipt,paid:true},{...receipt,qty:3},{...receipt,code:''}])await assert.rejects(g.confirmed(attempt,r,2));await assert.rejects(g.confirmed({...attempt,id:'other'},receipt,2));assert.ok(await g.read('actor-a','event-a'));await g.confirmed(attempt,receipt,2);assert.equal(await g.read('actor-a','event-a'),null);});
test('storage failure and account change stop request preparation before network action',async()=>{const g=new GeneralReservationGuard({getItem:async()=>null,setItem:async()=>{throw Error('storage unavailable')},removeItem:async()=>{}});await assert.rejects(g.begin(attempt,()=>true));await assert.rejects(g.begin(attempt,()=>false));});

test('new request recovery accepts only exact nonce/event/tier/quantity receipt, with no contact storage',async()=>{const {generalReceipt,generalRecovery,generalSubmission}=await import('../src/generalReservation.ts');const a={...attempt,protocol:'once',qty:2},r={...receipt,currency:'EUR',request_id:a.id,event_id:a.event,ticket_type_id:a.tier};const storage=store(),g=new GeneralReservationGuard(storage);await g.begin(a,()=>true);const revived=await new GeneralReservationGuard(storage).read(a.actor,a.event);assert.equal(generalRecovery({ok:true,found:false},revived),null);assert.ok(await g.read(a.actor,a.event));assert.equal(generalRecovery({ok:true,found:true,receipt:r,current_status:'reserved',checked_in:false,event_available:true},revived).receipt.code,'real');for(const patch of[{request_id:'other'},{event_id:'other'},{ticket_type_id:1},{qty:3},{paid:true}])assert.throws(()=>generalReceipt({...r,...patch},a));const args=generalSubmission(revived,' Guest ',' GUEST@example.com ');assert.equal(args.p_request,a.id);assert.equal(args.p_email,'guest@example.com');assert.equal(args.p_qty,2);assert.equal('p_name' in revived,false);assert.equal('p_email' in revived,false);await g.confirmed(a,r,2);assert.equal(await g.read(a.actor,a.event),null);});
test('legacy saved requests cannot be upgraded to once protocol, and malformed recovery never clears warning',async()=>{const {generalRecovery,generalSubmission}=await import('../src/generalReservation.ts');assert.throws(()=>generalSubmission(attempt,'Guest','guest@example.com'));const a={...attempt,protocol:'once',qty:2};for(const response of[null,{ok:false,found:false},{ok:true,found:'false'},{ok:true,found:true,receipt}])assert.throws(()=>generalRecovery(response,a));});

test('recovered creation receipt cannot imply active ticket after cancellation or closed event',async()=>{const {generalRecovery}=await import('../src/generalReservation.ts');const a={...attempt,protocol:'once',qty:2},r={...receipt,currency:'EUR',request_id:a.id,event_id:a.event,ticket_type_id:a.tier};assert.throws(()=>generalRecovery({ok:true,found:true,receipt:r},a));const v=generalRecovery({ok:true,found:true,receipt:r,current_status:'cancelled',checked_in:false,event_available:false},a);assert.equal(v.status,'cancelled');assert.equal(v.eventAvailable,false);assert.equal(v.receipt.code,'real');});
