import test from'node:test';import assert from'node:assert/strict';import{PrivateRequestStore}from'../src/privateRequests.ts';import{InquiryRecovery,inquiryMarker,inquiryRecoveryResult}from'../src/inquiryRecovery.ts';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',R='33333333-3333-4333-8333-333333333333',T='44444444-4444-4444-8444-444444444444',marker={user:A,kind:'start',request:R,target:T};
function setup(){const rows=new Map();let user=A,fail=false;const store=new PrivateRequestStore({getItem:async k=>rows.get(k)??null,setItem:async(k,v)=>{if(fail)throw Error('storage unavailable');rows.set(k,v)},removeItem:async k=>rows.delete(k)},()=>user,'zoi.inquiry-request.');return{rows,store,c:new InquiryRecovery(store,A),switch:v=>user=v,fail:()=>fail=true};}
test('restart restores nonce-only metadata and prevents replacement',async()=>{const f=setup();await f.c.begin(marker);assert.deepEqual(await new InquiryRecovery(f.store,A).load(),marker);assert.throws(()=>inquiryMarker({...marker,body:'private'},A));await assert.rejects(f.c.begin({...marker,request:B}),/earlier/);assert.ok([...f.rows.values()].every(v=>!v.includes('body')));});
test('A to B to A protects and preserves original marker',async()=>{const f=setup();await f.c.begin(marker);f.switch(B);assert.equal(await f.c.load(),null);await assert.rejects(f.c.begin(marker));f.switch(A);assert.deepEqual(await f.c.load(),marker);});
test('SecureStore failure and silent adapter failure prevent dispatch',async()=>{const f=setup();f.fail();await assert.rejects(f.c.begin(marker));let sent=false;const c=new InquiryRecovery(new PrivateRequestStore({getItem:async()=>null,setItem:async()=>{},removeItem:async()=>{}},()=>A,'zoi.inquiry-request.'),A);await assert.rejects(async()=>{await c.begin(marker);sent=true},/could not be saved/);assert.equal(sent,false);});
test('receipt requires exact nonce kind and target; notfound is not cancellation',()=>{const receipt={request_id:R,kind:'start',listing_id:T,thread_id:B};assert.deepEqual(inquiryRecoveryResult({ok:true,found:true,receipt},marker),{thread:B,cancelled:false});for(const patch of[{request_id:A},{kind:'reply'},{listing_id:B},{thread_id:'bad'}])assert.throws(()=>inquiryRecoveryResult({ok:true,found:true,receipt:{...receipt,...patch}},marker));assert.equal(inquiryRecoveryResult({ok:true,found:false,cancelled:false,request_id:R},marker),null);assert.deepEqual(inquiryRecoveryResult({ok:true,cancelled:true,request_id:R},marker),{thread:null,cancelled:true});assert.throws(()=>inquiryRecoveryResult({ok:true,cancelled:true,request_id:A},marker));});
test('failed recovery keeps marker until confirmed cancellation acknowledgement',async()=>{const f=setup();await f.c.begin(marker);assert.throws(()=>inquiryRecoveryResult({ok:false},marker));assert.deepEqual(await f.c.load(),marker);inquiryRecoveryResult({ok:true,cancelled:true,request_id:R},marker);await f.c.clear();assert.equal(await f.c.load(),null);});

test('corrupt active null prevents a replacement inquiry nonce',async()=>{const f=setup();await f.c.begin(marker);const key='zoi.inquiry-request.'+A;const manifest=JSON.parse(f.rows.get(key));f.rows.set(key+'.'+manifest.active.slot+'.0','null');await assert.rejects(f.c.begin({...marker,request:B}),/could not be verified/);assert.equal(f.rows.get(key+'.'+manifest.active.slot+'.0'),'null');});
