import test from 'node:test';import assert from 'node:assert/strict';import { assertOpsReceipt, canWrite, recordPayload, toForm } from '../src/operations.ts';
const workspace='00000000-0000-4000-8000-000000000001';const record={id:'00000000-0000-4000-8000-000000000002',workspace_id:workspace,kind:'task',project_id:'00000000-0000-4000-8000-000000000003',title:'Prepare event',data:{notes:'Bring forms',custom:'preserved'},status:'open',version:1};
test('save receipts require correct workspace, identity and incremented version',()=>{assert.throws(()=>assertOpsReceipt({},workspace,'task'));assert.throws(()=>assertOpsReceipt({ok:true,record:{...record,workspace_id:'different'}},workspace,'task'));assert.throws(()=>assertOpsReceipt({ok:true,record},workspace,'task',record));assert.equal(assertOpsReceipt({ok:true,record:{...record,version:2}},workspace,'task',record).version,2);});
test('editor can edit contacts/projects/tasks but not company records; viewers cannot write',()=>{assert.equal(canWrite('editor','task'),true);assert.equal(canWrite('editor','company'),false);assert.equal(canWrite('viewer','project'),false);assert.equal(canWrite('owner','company'),true);});
test('full-form edits preserve custom existing data and explicitly clear relations',()=>{const payload=recordPayload({...toForm(record),title:'Updated',company_id:'',due_at:'2026-10-05'},record);assert.equal(payload.custom,'preserved');assert.equal(payload.notes,'Bring forms');assert.equal(payload.company_id,null);assert.equal(payload.due_at,'2026-10-05T23:59:59Z');});
test('invalid deadline and blank title fail before sending',()=>{assert.throws(()=>recordPayload({...toForm(),title:' ',due_at:''}));assert.throws(()=>recordPayload({...toForm(),title:'Title',due_at:'2026-02-31'}));});

test('projects require company and tasks require project before sending',()=>{assert.throws(()=>recordPayload({...toForm(),title:'Matter'},undefined,'project'),/company/);assert.throws(()=>recordPayload({...toForm(),title:'Follow up'},undefined,'task'),/project/);});
test('unicode payload byte limit is enforced before sending',()=>{assert.throws(()=>recordPayload({...toForm(),title:'Contact',notes:'字'.repeat(11000)},undefined,'contact'),/too large/);});

test('unmodified deadline preserves its exact timestamp',()=>{const existing={...record,due_at:'2026-10-05T10:30:00Z'};assert.equal(recordPayload(toForm(existing),existing).due_at,existing.due_at);});
test('new company has valid default sector and cannot submit blank sector',()=>{assert.equal(recordPayload({...toForm(),title:'Company'},undefined,'company').sector,'business');assert.throws(()=>recordPayload({...toForm(),title:'Company',sector:''},undefined,'company'),/sector/);});
