import test from 'node:test';import assert from 'node:assert/strict';import {PrivateRequestStore} from '../src/privateRequests.ts';
const U='11111111-1111-4111-8111-111111111111',V='22222222-2222-4222-8222-222222222222';
function fixture(){const rows=new Map();let user=U;return {rows,setUser:v=>user=v,store:new PrivateRequestStore({getItem:async k=>rows.get(k)??null,setItem:async(k,v)=>rows.set(k,v),removeItem:async k=>rows.delete(k)},()=>user)};}
test('private recovery stores exact Unicode across bounded secure chunks',async()=>{const f=fixture(),v={request:'same',notes:'Ελληνικά 🇬🇷'.repeat(400)};await f.store.save(U,v);assert.deepEqual(await f.store.load(U),v);for(const [k,s]of f.rows)if(/\.\d\.\d+$/.test(k))assert.ok(Buffer.byteLength(s)<=1600);await f.store.clear(U);assert.equal(f.rows.size,0);});
test('account switch cannot read or save another account’s private request',async()=>{const f=fixture();await f.store.save(U,{request:'one'});f.setUser(V);assert.equal(await f.store.load(U),null);await assert.rejects(f.store.save(U,{request:'two'}));f.setUser(U);assert.deepEqual(await f.store.load(U),{request:'one'});});
test('sign-out cleanup runs after queued writes and removes every chunk',async()=>{const f=fixture();const saving=f.store.save(U,{notes:'a'.repeat(10000)}),clear=f.store.clear(U);await Promise.all([saving,clear]);assert.equal(f.rows.size,0);});
test('incomplete persistence is never mistaken for a retryable request',async()=>{const f=fixture();f.rows.set('zoi.private-request.'+U,JSON.stringify({active:null,pending:{slot:0,count:2}}));await assert.rejects(f.store.load(U),/interrupted/);await f.store.clear(U);assert.equal(f.rows.size,0);});

test('cleanup failure cannot roll back a committed recovery request',async()=>{const rows=new Map();let fail=false;const store=new PrivateRequestStore({getItem:async k=>rows.get(k)??null,setItem:async(k,v)=>rows.set(k,v),removeItem:async k=>{if(fail)throw Error('locked');rows.delete(k)}},()=>U);await store.save(U,{request:'old'});fail=true;await store.save(U,{request:'new'});assert.deepEqual(await store.load(U),{request:'new'});fail=false;await store.clear(U);assert.equal(rows.size,0);});
test('separate workflows keep distinct encrypted recovery namespaces',async()=>{const rows=new Map(),storage={getItem:async k=>rows.get(k)??null,setItem:async(k,v)=>rows.set(k,v),removeItem:async k=>rows.delete(k)};const event=new PrivateRequestStore(storage,()=>U),community=new PrivateRequestStore(storage,()=>U,'zoi.community-request.');await event.save(U,{kind:'confirm'});await community.save(U,{kind:'publish'});await community.clear(U);assert.deepEqual(await event.load(U),{kind:'confirm'});assert.equal(await community.load(U),null);});
test('failed storage cleanup retains a discoverable manifest until explicit cleanup succeeds',async()=>{const rows=new Map();let fail=true;const store=new PrivateRequestStore({getItem:async k=>rows.get(k)??null,setItem:async(k,v)=>{if(fail&&/\.0\.1$/.test(k))throw Error('full');rows.set(k,v)},removeItem:async k=>{if(fail)throw Error('locked');rows.delete(k)}},()=>U);await assert.rejects(store.save(U,{notes:'x'.repeat(1000)}));await assert.rejects(store.load(U),/interrupted/);fail=false;await store.clear(U);assert.equal(rows.size,0);});

test('non-null malformed manifests never masquerade as no pending request',async()=>{for(const value of [true,[],{},null,{active:false},{active:{slot:0,count:1,other:1}},{active:null,pending:null},{active:null,unknown:true}]){const f=fixture();f.rows.set('zoi.private-request.'+U,JSON.stringify(value));await assert.rejects(f.store.load(U),/could not be verified/);await assert.rejects(f.store.save(U,{request:'replacement'}),/could not be verified/);}});
test('valid active-null pending manifest remains interrupted, not empty',async()=>{const f=fixture();f.rows.set('zoi.private-request.'+U,JSON.stringify({active:null,pending:{slot:0,count:1}}));await assert.rejects(f.store.load(U),/interrupted/);});

test('an active null payload is corruption rather than no pending request',async()=>{const f=fixture();await f.store.save(U,{request:'original'});const key='zoi.private-request.'+U;const manifest=JSON.parse(f.rows.get(key));f.rows.set(key+'.'+manifest.active.slot+'.0','null');await assert.rejects(f.store.load(U),/could not be verified/);assert.ok(f.rows.has(key),'the recovery marker is retained');});
