import test from 'node:test';import assert from 'node:assert/strict';import { normalizeProfile, publicURL } from '../src/profile.ts';
test('profile gives owner fields priority, merges actual socials and labels enrichment',()=>{const p=normalizeProfile({name:'Business',profile:{about:'Owner description',social:{instagram:'https://instagram.com/owner'},_enrich:{about:'Scraped',phone:'+301234567',social:{instagram:'https://instagram.com/scraped'}}},social_links:{facebook:'https://facebook.com/owner'}});assert.equal(p.description,'Owner description');assert.equal(p.phone,'+301234567');assert.deepEqual(p.socials.map(x=>x.url),['https://instagram.com/owner','https://facebook.com/owner']);assert.ok(p.enrichmentNote);});
test('profile never fabricates verification or ratings from owner data',()=>{const p=normalizeProfile({name:'Business',profile:{verified:true,rating:5,reviews:['fake']},verification_status:'unverified'});assert.equal(p.verified,false);assert.equal(p.profile.rating,undefined);assert.equal(p.profile.reviews,undefined);assert.equal(p.socials.length,0);});
test('profile rejects unsafe external schemes and credentials',()=>{for(const url of ['javascript:alert(1)','file:///etc/passwd','https://user:pass@example.com','https://127.0.0.1/a','//example.com'])assert.equal(publicURL(url),'');assert.equal(publicURL('https://example.com/a'),'https://example.com/a');});
test('missing entity is absent, not invented profile',()=>{assert.equal(normalizeProfile(null),null);assert.equal(normalizeProfile([]),null);assert.equal(normalizeProfile({error:'timeout'}),null);});

test('profile actions require exact server routes and matching booking listing',()=>{const id='053a5656-b19b-48a4-8721-65c4674f647c';const p=normalizeProfile({id,name:'Place',booking_url:'/book/?listing='+id,volunteer_url:'/volunteer/?workspace='+id});assert.equal(p.bookingListing,id);assert.equal(p.volunteerWorkspace,id);for(const url of ['https://evil.test/book/?listing='+id,'//evil.test/book/?listing='+id,'/book/?listing='+id+'&other=yes','/book/?listing=invalid'])assert.equal(normalizeProfile({id,name:'Place',booking_url:url}).bookingListing,'');assert.equal(normalizeProfile({id:'different',name:'Place',booking_url:'/book/?listing='+id}).bookingListing,'');assert.equal(normalizeProfile({id,name:'Place'}).bookingListing,'');});

test('private enquiry entry requires server invitation for this same listing',()=>{const id='053a5656-b19b-48a4-8721-65c4674f647c';assert.equal(normalizeProfile({id,name:'Place',inquiry_url:'/inquiries/?listing='+id}).inquiryListing,id);assert.equal(normalizeProfile({id:'other',name:'Place',inquiry_url:'/inquiries/?listing='+id}).inquiryListing,'');assert.equal(normalizeProfile({id,name:'Place',inquiry_url:'https://evil.test/inquiries/?listing='+id}).inquiryListing,'');});
