import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{stripTypeScriptTypes}from'node:module';
const source=fs.readFileSync(new URL('../src/workspaceTeam.ts',import.meta.url),'utf8');const{createTeamController,teamRoles}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
function fixture(){let stored=null,current=true,mode='ok',writes=0,reads=0;const receipts={};let snapshot={ok:true,workspace_id:id(9),actor_profile_id:id(1),role:'owner',members:[{id:id(11),profile_id:id(1),revision:id(21),name:'Owner',role:'owner',protected:true},{id:id(12),profile_id:id(2),revision:id(22),name:'Member',role:'editor',protected:false}]};const deps={workspace:id(9),current:()=>current,nonce:()=>id(100+writes),changed:()=>{},storage:{load:async()=>stored,save:async v=>{if(mode==='storage')throw Error('Storage failed');stored=v;},clear:async()=>{stored=null;}},rpc:async(n,a)=>{if(mode==='denied')throw Object.assign(Error('not_authorized'),{status:403});if(n==='workspace_team_get'){reads++;return structuredClone(snapshot);}if(n==='workspace_team_save'){writes++;if(mode==='unknown')throw Error('Network');let r={ok:true,workspace_id:id(9),request_id:a.p_request,member_id:a.p_member,profile_id:a.p_profile};if(mode==='conflict')r={...r,ok:false,error:'membership_conflict'};else{snapshot.members[1].role=a.p_role;snapshot.members[1].revision=id(200+writes);}receipts[a.p_request]=r;if(mode==='lost')throw Error('Network');return r;}if(a.p_cancel_if_missing&&!receipts[a.p_request])receipts[a.p_request]={ok:false,cancelled:true,workspace_id:id(9),request_id:a.p_request};return{ok:true,workspace_id:id(9),request_id:a.p_request,found:!!receipts[a.p_request],result:receipts[a.p_request]};}};return {controller:()=>createTeamController(deps),mode:v=>mode=v,stop:()=>current=false,stored:()=>stored,writes:()=>writes,reads:()=>reads,snapshot};}
test('roles protect owner/self and admin peer escalation',()=>{const f=fixture(),s=f.snapshot;assert.deepEqual(teamRoles(s,s.members[0]),[]);assert.deepEqual(teamRoles(s,s.members[1]),['admin','editor','viewer']);s.role='admin';assert.deepEqual(teamRoles(s,s.members[1]),['editor','viewer']);s.members[1].role='admin';assert.deepEqual(teamRoles(s,s.members[1]),[]);s.role='viewer';assert.deepEqual(teamRoles(s,s.members[1]),[]);});
test('real controller confirms save only after current roster read',async()=>{const f=fixture(),c=f.controller();await c.load();await c.change(c.state().snapshot.members[1],'role','viewer');assert.equal(f.writes(),1);assert.equal(f.reads(),2);assert.equal(c.state().snapshot.members[1].role,'viewer');assert.equal(f.stored(),null);assert.equal(c.state().message,'Team change confirmed.');});
test('lost response survives remount; receipt check does not resend',async()=>{const f=fixture(),c=f.controller();await c.load();f.mode('lost');await c.change(c.state().snapshot.members[1],'role','viewer');assert.ok(c.state().pending);assert.deepEqual(Object.keys(f.stored()),['request']);const remount=f.controller();await remount.load();await remount.recover();assert.equal(f.writes(),1);assert.equal(remount.state().pending,null);assert.equal(remount.state().message,'Team change confirmed.');});
test('unknown request blocks new write and safely cancels',async()=>{const f=fixture(),c=f.controller();await c.load();const m=c.state().snapshot.members[1];f.mode('unknown');await c.change(m,'role','viewer');await c.change(m,'role','admin');assert.equal(f.writes(),1);await c.recover();assert.ok(c.state().pending);await c.recover(true);assert.equal(c.state().pending,null);assert.equal(c.state().snapshot.members[1].role,'editor');});
test('conflict refreshes membership; storage failure prevents submission',async()=>{const f=fixture(),c=f.controller();await c.load();f.mode('conflict');await c.change(c.state().snapshot.members[1],'role','viewer');assert.equal(c.state().pending,null);assert.match(c.state().message,/changed elsewhere/);f.mode('storage');await c.change(c.state().snapshot.members[1],'role','viewer');assert.equal(f.writes(),1);});
test('authority loss clears private roster and account change fences calls',async()=>{const f=fixture(),c=f.controller();await c.load();f.mode('denied');await c.change(c.state().snapshot.members[1],'role','viewer');assert.equal(c.state().snapshot,null);assert.equal(c.state().loaded,false);f.stop();await c.recover();assert.equal(f.writes(),0);c.drop();assert.equal(c.state().pending,null);});
