import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {renderMusicHome} from '../../../api/_music-home.js';
const root=resolve(import.meta.dirname,'../../..');
const entity={id:'11111111-1111-4111-8111-111111111111',name:'Independent Artist',slug:'independent-artist',entity_type:'artist',website:'https://artist.example.org/',profile:{_enrich:{source_url:'https://artist.example.org/',listen:{youtube:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',spotify:'https://open.spotify.com/artist/0VuyN0xzSqykiDB2MxihTe'}}}};
const core=`window.ZoiCore={auth:{load:()=>null,token:()=>null,ensureFresh:async()=>false},keys:{auth:'test_auth'},api:{rpc:async()=>({ok:true,available:false,shows:[]})}};`;
const cachedModel=process.env.CACHED_MODEL_PATH?await readFile(process.env.CACHED_MODEL_PATH):null;
const server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/'){res.setHeader('Content-Type','text/html');res.end(renderMusicHome(entity,{template:u.searchParams.get('template')}));return;}if(cachedModel&&u.pathname==='/assets/homes/templates/music/model.mjs'){res.setHeader('Content-Type','text/javascript');res.end(cachedModel);return;}if(u.pathname==='/assets/zoi-core.js'){res.setHeader('Content-Type','text/javascript');res.end(core);return;}if(process.env.PRODUCTION_ASSETS==='1'&&u.pathname.startsWith('/assets/')){const upstream=await fetch('https://zoi.city'+u.pathname+u.search);res.statusCode=upstream.status;res.setHeader('Content-Type',upstream.headers.get('content-type')||'application/octet-stream');res.end(Buffer.from(await upstream.arrayBuffer()));return;}const p=resolve(root,'.'+u.pathname);if(!p.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[extname(p)]||'application/octet-stream');res.end(await readFile(p));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox'],headless:true});const results=[];
try{for(const width of[390,1440])for(const template of['atelier','concierge','table','parea']){const page=await browser.newPage({viewport:{width,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>route.request().url().startsWith(origin)?route.continue():route.abort());await page.goto(origin+'/?template='+template);const trigger=page.locator('[data-video]');await trigger.waitFor();await page.waitForFunction(()=>document.querySelector('[data-video]')&&window.ZoiCore);await trigger.click();const dialog=page.locator('dialog.music-dialog');await assert.doesNotReject(()=>dialog.waitFor({state:'visible'}));assert.equal(await dialog.locator('iframe').getAttribute('src'),'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ');assert.equal(await dialog.locator('iframe').getAttribute('title'),'Independent Artist video');assert.equal(await dialog.locator('a').getAttribute('href'),entity.profile._enrich.listen.youtube);assert(await page.evaluate(()=>document.querySelector('dialog.music-dialog').contains(document.activeElement)));await page.screenshot({path:`/tmp/artist-${process.env.PRODUCTION_ASSETS==='1'?'production':'source'}-video-${template}-${width}.png`});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await dialog.locator('[data-close]').click();assert.equal(await dialog.locator('iframe').count(),0);assert(await trigger.evaluate(el=>document.activeElement===el));await trigger.click();await page.keyboard.press('Escape');assert.equal(await dialog.locator('iframe').count(),0);assert.equal(await dialog.evaluate(el=>el.open),false);assert(await trigger.evaluate(el=>document.activeElement===el));assert.deepEqual(errors,[]);results.push({width,template,openCloseEscapeFocusUnload:true});await page.close();}console.log(JSON.stringify({results,providerPlayback:'not exercised: external requests blocked'},null,2));}finally{await browser.close();await new Promise(r=>server.close(r));}
