import fs from'node:fs/promises';import path from'node:path';import crypto from'node:crypto';import{credentialFindings}from'../../../scripts/check-source-credentials.mjs';
const base=process.cwd(),destination=process.env.HOST_FREEZE_DIR||'/workspaces/zoi-city/.recovery/event-host-controls-final-freeze-20261003',receipt='docs/audits/evidence/event-host-controls-2026-10-03/manifest-final.json';
await fs.mkdir(destination,{recursive:false});
const runtime=['assets/events/host-controls.mjs','assets/events/host-controls.css','assets/events/signature/customer-a.mjs','assets/events/signature/customer-a.css','assets/events/signature/experience.mjs','tickets/hosts/index.html'];
const files=new Set(runtime),queue=[...runtime,'tests/unit/event-host-controls.test.mjs','tests/unit/event-publicity.test.mjs','tests/unit/event-publicity-view.test.mjs','tests/unit/event-payment-policy.test.mjs','tests/unit/table-inventory-operator.test.mjs','tests/unit/signature-startup.test.mjs','tests/unit/signature-experience.test.mjs','tests/unit/signature-planning.test.mjs','tests/unit/signature-table-choice.test.mjs','scripts/check-source-credentials.mjs','api/_event-home.js','assets/homes/templates/events/generic.mjs','assets/homes/templates/events/client.mjs','assets/homes/templates/events/style.css','assets/tickets/event-payment-policy.mjs','assets/tickets/organizer-setup.mjs','assets/tickets/host-allocations.mjs','assets/zoi-theme.css','assets/tickets/host-allocations.css','events/giannis-ploutarchos-andromache-toronto-2027/index.html','docs/specialists/zoi-delivery/SKILL.md','docs/specialists/zoi-delivery/references/roles.md','docs/recovery-scope.json','assets/tickets/event-payment-policy-contract.md','assets/tickets/event-host-allocation-contract.md','supabase/migrations/20260930075049_owner_content_versioned_save.sql','supabase/migrations/20260930184500_event_publicity_owner_content.sql','supabase/migrations/20261001171500_event_payment_response_deadline.sql','supabase/migrations/20261003023304_event_table_current_session.sql','supabase/migrations/20260930125216_versioned_event_table_holds.sql','package.json','package-lock.json','docs/audits/event-host-controls-2026-10-03.md'];
async function walk(dir){for(const f of await fs.readdir(dir,{withFileTypes:true})){const p=path.posix.join(dir,f.name);if(f.isDirectory())await walk(p);else if(p!==receipt)queue.push(p);}}await walk('tests/browser/event-host-controls');await walk('docs/audits/evidence/event-host-controls-2026-10-03');
const visited=new Set(),missing=[];while(queue.length){const name=queue.shift();if(visited.has(name))continue;visited.add(name);let bytes;try{bytes=await fs.readFile(path.join(base,name));}catch{missing.push(name);continue;}files.add(name);if(!/\.(mjs|cjs|js|html|css)$/.test(name))continue;const text=bytes.toString();for(const match of text.matchAll(/(?:from\s*|import\s*\(\s*|import\s*)['"]([^'"]+)['"]|(?:href|src)=["']([^"']+)["']|url\(["']?([^)'"\s]+)|['"](\/assets\/[^'"\s]+)['"]/g)){const ref=(match[1]||match[2]||match[3]||match[4]).split('?')[0].split('#')[0];if(!ref||ref.includes('${')||/^(?:https?:|data:)/.test(ref)||!ref.startsWith('.')&&!ref.startsWith('/'))continue;const file=ref.startsWith('/')?ref.slice(1):path.posix.normalize(path.posix.join(path.posix.dirname(name),ref));if(file.startsWith('assets/')||file.startsWith('api/')||file.startsWith('tests/')){try{const st=await fs.stat(path.join(base,file));if(st.isFile())queue.push(file);}catch{}}}}
const entries=[];let findings=0;for(const name of [...files].sort()){const bytes=await fs.readFile(path.join(base,name));if(/\.(?:mjs|cjs|js|json|md|sql|html|css|log)$/.test(name))findings+=credentialFindings(bytes.toString()).length;const target=path.join(destination,name);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,bytes);entries.push({path:name,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length});}if(findings)throw Error('Credential findings: '+findings);if(missing.length)throw Error('Missing explicit dependency files: '+missing.join(', '));
const manifest={base_commit:'95d63fd15b18d3d73d91bb2a5e40ae54313e8a39',isolated_checkout:base,snapshot:destination,production:false,no_live_writes:true,runtime_paths:runtime,credential_findings:findings,entries};const bytes=JSON.stringify(manifest,null,2)+'\n';await fs.writeFile(receipt,bytes);await fs.mkdir(path.dirname(path.join(destination,receipt)),{recursive:true});await fs.writeFile(path.join(destination,receipt),bytes);console.log(JSON.stringify({entries:entries.length,runtime:runtime.length,manifest_sha256:crypto.createHash('sha256').update(bytes).digest('hex'),snapshot:destination}));
