const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const base=path.resolve(__dirname,'../../..'),out=process.env.QA_OUTPUT_DIR||path.join(base,'docs/audits/evidence/event-host-controls-2026-10-03/controlled');
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local'),file=path.resolve(base,'.'+url.pathname);if(!file.startsWith(base+path.sep)||!['/assets/','/tests/browser/event-host-controls/'].some(x=>url.pathname.startsWith(x)))throw Error();res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8');res.end(await fs.readFile(file));}catch{res.statusCode=404;res.end();}});
(async()=>{await fs.mkdir(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,report={controlled:true,production:false,no_live_writes:true,cases:[]};let browser;
try{browser=await chromium.launch({executablePath:'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});
 for(const width of[390,1440])for(const kind of['toronto','montreal','sparse']){
  const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+'/tests/browser/event-host-controls/fixture.html');await page.evaluate(kind=>{qa.kind=kind;return qa.mount();},kind);
  const owner=page.getByRole('region',{name:'Event organiser controls'});await owner.getByRole('button',{name:'Save event announcements',exact:true}).waitFor();await owner.getByLabel('Show a dated ticket-sales report').check();await owner.getByLabel('Tickets sold (whole tickets)').fill('317');await owner.getByLabel('Reported at (UTC)').fill(new Date(Date.now()-3600000).toISOString().slice(0,16));await owner.getByLabel('Hide after (UTC, within 31 days)').fill(new Date(Date.now()+86400000).toISOString().slice(0,16));await owner.getByLabel('Organiser announcement link').fill('https://official.example/reported');await owner.getByRole('button',{name:'Preview announcements',exact:true}).click();await owner.getByText(/317 Tickets sold/).waitFor();await owner.screenshot({path:path.join(out,`${kind}-${width}-review.png`)});
  const before=await page.evaluate(()=>structuredClone({base:qa.base,starts:qa.profile.starts,lineup:qa.profile.lineup,tickets:qa.profile.tickets_url}));await owner.getByRole('button',{name:'Save event announcements',exact:true}).click();await owner.getByText('Event announcements saved. Open the guest page to see the published update.',{exact:true}).waitFor();await page.getByRole('button',{name:'Refresh published guest view'}).click();await page.locator('#guest-output').getByText('317 tickets sold',{exact:true}).waitFor();const payload=await page.evaluate(()=>qa.calls.find(x=>x.name==='home_content_save').p);assert.deepEqual(payload.p_base,{});assert.deepEqual(Object.keys(payload.p_profile),['event_publicity']);assert.deepEqual(await page.evaluate(()=>({base:qa.base,starts:qa.profile.starts,lineup:qa.profile.lineup,tickets:qa.profile.tickets_url})),before);await owner.screenshot({path:path.join(out,`${kind}-${width}-saved.png`)});await page.locator('#guest').screenshot({path:path.join(out,`${kind}-${width}-guest.png`)});
  await owner.getByRole('button',{name:'Allowed payment arrangements',exact:true}).click();await page.getByLabel('Allowed guest payment option').selectOption('true');await page.getByLabel('Response deadline (UTC, optional)').fill('2027-03-01T12:00');await page.getByRole('button',{name:'Save event payment policy',exact:true}).click();await page.getByText('Event payment options saved.',{exact:true}).waitFor();const policy=await page.evaluate(()=>qa.calls.find(x=>x.name==='event_payment_policy_configure').p);assert.equal(policy.p_allow_pay_at_door,true);assert.equal(policy.p_allow_pay_online,false);assert.equal(policy.p_response_deadline,'2027-03-01T12:00:00.000Z');await page.locator('#payment').screenshot({path:path.join(out,`${kind}-${width}-payment.png`)});
  await owner.getByText('Edit ticket-sales announcement & event posts',{exact:true}).click();await owner.getByRole('button',{name:'Remove event announcements',exact:true}).click();await owner.getByRole('button',{name:'Save event announcements',exact:true}).click();await owner.getByText('Event announcements saved. Open the guest page to see the published update.',{exact:true}).waitFor();await page.getByRole('button',{name:'Refresh published guest view'}).click();await page.getByText('No current organiser ticket-sales report.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>qa.profile.event_publicity),null);
  await owner.getByRole('button',{name:'Booking options & table setup',exact:true}).click();await page.getByText('Prepare this event for your parea',{exact:true}).waitFor();await page.getByText('Table inventory',{exact:true}).waitFor();const setup=page.locator('#setup');await setup.getByLabel('Enable public timed holds after saving').waitFor();await setup.getByLabel('Event start, including UTC offset').fill('2027-03-26T22:00:00-04:00');await setup.getByLabel('Enable public timed holds after saving').check();await setup.locator('[data-field=selected]').check();await setup.getByLabel('Source table label').fill(kind==='montreal'?'10A':'9');await setup.getByLabel('Capacity',{exact:true}).fill('10');await setup.getByLabel('Minimum party').fill('1');await setup.getByLabel('Price per guest').fill('125');await setup.getByLabel('Currency').selectOption('CAD');await setup.getByLabel('This price includes all applicable taxes and fees').check();await setup.getByRole('button',{name:'Review changes',exact:true}).click();await setup.getByText('Public timed holds will be enabled if the event is eligible. Start: 2027-03-26T22:00:00-04:00',{exact:true}).waitFor();await setup.getByRole('button',{name:'Save these settings',exact:true}).click();await setup.getByText('Current settings loaded.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>qa.inventory.enabled),true);await page.evaluate(()=>qa.mountGuestAvailability());await page.locator('#guest-availability').getByText('Choose a table',{exact:true}).waitFor().catch(async error=>{await fs.writeFile(path.join(out,'inventory-guest-failure.json'),JSON.stringify(await page.evaluate(()=>({inventory:qa.inventory,html:document.getElementById('guest-availability').innerHTML})),null,2));throw error;});await setup.getByLabel('Enable public timed holds after saving').uncheck();await setup.getByRole('button',{name:'Review changes',exact:true}).click();await setup.getByRole('button',{name:'Save these settings',exact:true}).click();await setup.getByText('Current settings loaded.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>qa.inventory.enabled),false);await page.evaluate(()=>qa.mountGuestAvailability());await page.locator('#guest-availability').getByText('Table reservations on Zoi are not configured for this event. Use the organiser’s published contact or ticket options.',{exact:true}).waitFor();await page.locator('#setup').screenshot({path:path.join(out,`${kind}-${width}-booking.png`)});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);assert.deepEqual(errors,[]);report.cases.push({width,kind,update_guest_clear:true,payment_door_unpaid:true,existing_inventory_handoff:true,payload,errors});await page.close();
 }
 for(const width of[390,1440])for(const mode of['lost','conflict','denied','editor','viewer','account']){
  const page=await browser.newPage({viewport:{width,height:1000}});await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+'/tests/browser/event-host-controls/fixture.html');const owner=page.getByRole('region',{name:'Event organiser controls'});await owner.getByRole('button',{name:'Save event announcements',exact:true}).waitFor();
  if(mode==='viewer'){await page.evaluate(()=>{qa.role='viewer';return qa.mount();});await owner.getByText('Only a currently authorized owner, administrator or editor can publish this event’s announcements.',{exact:true}).waitFor();assert.equal(await owner.getByLabel('Tickets sold (whole tickets)').count(),0);}
  else if(mode==='account'){await owner.getByLabel('Tickets sold (whole tickets)').fill('444');await page.evaluate(()=>{qa.actor=null;dispatchEvent(new Event('zoi:auth-change'));});await owner.getByText('Sign in to manage your own event announcements and permitted arrangements.',{exact:true}).waitFor();assert.equal(await owner.getByLabel('Tickets sold (whole tickets)').count(),0);assert.equal(await page.evaluate(()=>qa.calls.filter(x=>x.name==='home_content_save').length),0);}
  else {if(mode==='editor'){await page.evaluate(()=>{qa.role='editor';return qa.mount();});await owner.getByRole('button',{name:'Save event announcements',exact:true}).waitFor();}await owner.getByRole('button',{name:'Remove event announcements',exact:true}).click();if(mode!=='editor')await page.evaluate(mode=>qa.mode=mode,mode);await owner.getByRole('button',{name:'Save event announcements',exact:true}).click();
   if(mode==='lost'){await owner.getByRole('button',{name:'Retry and confirm the same announcement',exact:true}).waitFor();assert(await owner.getByLabel('Tickets sold (whole tickets)').isDisabled());await page.evaluate(()=>qa.mount());await owner.getByRole('button',{name:'Retry and confirm the same announcement',exact:true}).click();await owner.getByText('Announcement save confirmed.',{exact:true}).waitFor();const writes=await page.evaluate(()=>qa.calls.filter(x=>x.name==='home_content_save'));assert.deepEqual(writes[0].p,writes[1].p);}
   else if(mode==='conflict')await owner.getByText('The event changed elsewhere. Reload current details before editing again.',{exact:true}).waitFor();else if(mode==='denied')await owner.getByText('Only a currently authorized owner, administrator or editor can publish this event’s announcements.',{exact:true}).waitFor();else {await owner.getByText('Event announcements saved. Open the guest page to see the published update.',{exact:true}).waitFor();assert.equal(await page.getByLabel('Allowed guest payment option').count(),0);await owner.getByRole('button',{name:'Booking options & table setup',exact:true}).click();await owner.getByText(/editorial access alone does not grant inventory access/).waitFor();}}
  report.cases.push({width,mode,passed:true});await page.close();
 }
 report.status='passed';
}catch(error){report.status='failed';report.failure=error.message;throw error;}finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');await browser?.close();await new Promise(r=>server.close(r));}console.log(JSON.stringify({status:report.status,cases:report.cases.length}));})().catch(e=>{console.error(e);process.exitCode=1;});
