const{chromium}=require('playwright-core'),assert=require('node:assert/strict');
const actor='11111111-1111-4111-8111-111111111111',ws='22222222-2222-4222-8222-222222222222',company='33333333-3333-4333-8333-333333333333',member='44444444-4444-4444-8444-444444444444',other='55555555-5555-4555-8555-555555555555';
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});try{for(const width of[390,1440]){
let role='owner',lose=false,hold=false,release,deny=false;const records=[{id:company,workspace_id:ws,kind:'company',title:'Arts Society',data:{legal_name:'Arts Society Incorporated'},version:1,status:'open'}],receipts={},calls=[];
const p=await browser.newPage({viewport:{width,height:1000}});await p.addInitScript(()=>{sessionStorage.setItem('zoi.mobile.refresh.v1',JSON.stringify({refresh_token:'fixture'}));window.open=url=>{window.openedUrl=url;return null;};});
await p.route('https://csebihpaychdkanjjsmz.supabase.co/**',async r=>{const url=r.request().url(),name=url.split('/').pop(),a=r.request().postDataJSON();calls.push({name,a});let body=[];
if(url.includes('/auth/v1/token'))body={access_token:'fixture',refresh_token:'fixture',expires_at:Math.floor(Date.now()/1000)+3600,user:{id:actor,email:'qa@example.invalid'}};
if(name==='zoi_me')body={authenticated:true,profile:{id:member},workspaces:[{id:ws,name:'Arts Society',role},{id:other,name:'Other organization',role:'owner'}]};
if(name==='ops_records_list'){if(deny)return r.fulfill({status:401,contentType:'application/json',body:JSON.stringify({message:'expired'})});if(hold){hold=false;await new Promise(r=>release=r);}body={ok:true,role,records,members:[{profile_id:member,display_name:'Maria'}]};}
if(name==='ops_mutation_execute'){assert.notEqual(role,'viewer');const x=a.p_args,id=x.p_id||crypto.randomUUID(),before=records.find(r=>r.id===id);assert.equal(x.p_expected_version,before?.version||0);const row={...x.p_data,id,workspace_id:ws,kind:x.p_kind,version:(before?.version||0)+1,data:x.p_data};if(before)records.splice(records.indexOf(before),1,row);else records.push(row);body=receipts[a.p_request]={ok:true,state:'saved',workspace_id:ws,request_id:a.p_request,action:a.p_action,record_id:id,kind:x.p_kind,version:row.version};if(lose){lose=false;return r.abort('failed');}}
if(name==='ops_request_status')body=receipts[a.p_request];
await r.fulfill({contentType:'application/json',body:JSON.stringify(body)});});
const button=name=>p.getByRole('button',{name,exact:true});const enter=async()=>{await p.getByRole('tab',{name:/Grow/}).click();await p.getByRole('radio',{name:/Arts Society/}).click();await button('Open Business operations').click();};const companyOpen=async()=>{await button('● Company').waitFor();await p.getByRole('button',{name:/Arts Society.*version/}).click();await button('Start company project').waitFor();};
await p.goto(process.env.EXPO_ORIGIN||'http://localhost:8197');await enter();await companyOpen();await button('Company details & settings').click();await p.getByLabel('Legal name',{exact:true}).fill('Arts Society of Ontario');assert.equal(await button('Start company project').isDisabled(),true);await p.getByLabel('Legal name',{exact:true}).scrollIntoViewIfNeeded();await p.screenshot({path:'/tmp/native-company-form-'+width+'.png',fullPage:true});await button('Save record').click();await p.getByRole('button',{name:/Arts Society.*version 2/}).click();assert.equal(records[0].data.legal_name,'Arts Society of Ontario');
await button('Start company project').click();await p.getByLabel('Title',{exact:true}).fill('Annual programme');await button('Save record').click();const project=records.find(r=>r.kind==='project');assert.equal(project.company_id,company);await p.getByRole('button',{name:/Annual programme.*version 1/}).click();await button('Add follow-up task').click();await p.getByLabel('Title',{exact:true}).fill('Confirm programme budget');await button('Maria').click();lose=true;await button('Save record').click();await button('Check saved Operations receipt').waitFor();await p.getByRole('button',{name:'← All workspace tools',exact:true}).click();await button('Open Business operations').click();await button('Check saved Operations receipt').click();await p.getByText(/Change saved. Reference/).waitFor();assert.equal(records.filter(r=>r.kind==='task').length,1);const task=records.find(r=>r.kind==='task');assert.equal(task.assignee_profile_id,member);assert.notEqual(member,actor);assert.equal(task.project_id,project.id);assert.equal(task.due_at,null);
await companyOpen();await button('Open company task · Confirm programme budget').click();await button('completed').click();assert.equal(await button('Back to company workspace').isDisabled(),true);lose=true;await button('Save record').click();await button('Check saved Operations receipt').waitFor();assert.equal(await button('Back to company workspace').isDisabled(),true);await button('Check saved Operations receipt').scrollIntoViewIfNeeded();await p.screenshot({path:'/tmp/native-company-pending-'+width+'.png',fullPage:true});await button('Check saved Operations receipt').click();await p.getByRole('button',{name:/Confirm programme budget.*version 2/}).click();await button('Back to company workspace').click();await p.getByText('1 projects · 0 open tasks · 0 work contacts',{exact:true}).waitFor();await p.getByText('Confirm programme budget · completed · Maria · No deadline',{exact:true}).waitFor();await button('Project files on website · Annual programme').click();await p.waitForFunction(()=>window.openedUrl);assert.equal(await p.evaluate(()=>window.openedUrl),`https://www.zoi.city/social?workspace=${ws}#documents/project/${project.id}`);await button('Start company project').scrollIntoViewIfNeeded();await p.screenshot({path:'/tmp/native-company-'+width+'.png',fullPage:true});
await p.reload();await enter();await companyOpen();await p.getByText('1 projects · 0 open tasks · 0 work contacts',{exact:true}).waitFor();
role='editor';await button('Reload records').click();await button('Company details & settings').click();assert.equal(await p.getByLabel('Legal name',{exact:true}).isEditable(),false);assert.equal(await button('Save record').count(),0);assert.equal(await button('Start company project').isEnabled(),true);await button('Hide company details').click();
role='viewer';await button('Reload records').click();await p.getByText('Private files require an authorized editor or owner.',{exact:true}).waitFor();assert.equal(await button('Start company project').count(),0);assert.equal(await button('Project files on website · Annual programme').count(),0);await button('Open company task · Confirm programme budget').click();assert.equal(await button('Save record').count(),0);await button('Back to company workspace').click();
role='owner';await button('Reload records').click();await button('Start company project').waitFor();await p.evaluate(()=>window.openedUrl=null);hold=true;await button('Project files on website · Annual programme').click();for(let n=0;!release&&n<100;n++)await new Promise(r=>setTimeout(r,10));assert(release);await button('← All workspace tools').click();await p.getByRole('radio',{name:/Other organization/}).click();release();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>window.openedUrl),null);
await p.getByRole('radio',{name:/Arts Society/}).click();await button('Open Business operations').click();await companyOpen();deny=true;await button('Project files on website · Annual programme').click();await p.getByText('Sign in to continue.',{exact:true}).waitFor();assert.equal(await button('Start company project').count(),0);assert.equal(await button('Company details & settings').count(),0);assert.equal(calls.filter(c=>c.name==='ops_mutation_execute').length,4);console.log('PASS native Company full journey',width);await p.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
