const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor=id(90),ws=id(1),other=id(99),member=id(20),origin=process.env.EXPO_ORIGIN||'http://localhost:8209',evidence=process.env.COMPANY_CONSOLE_EVIDENCE||path.resolve('docs/audits/evidence/native-company-console-producer-2026-10-03');fs.mkdirSync(evidence,{recursive:true});
const row=(n,kind,x={})=>({id:id(n),workspace_id:ws,kind,title:kind+n,version:1,status:'open',data:{},...x});
function records(){return[row(2,'company',{title:'Alpha Arts',data:{legal_name:null,jurisdiction:'Ontario'}}),row(3,'company',{title:'Beta Food'}),row(4,'project',{company_id:id(2),title:'Festival planning'}),row(5,'project',{company_id:id(3),title:'Supply contract'}),row(6,'task',{project_id:id(4),title:'Overdue budget',due_at:'2026-01-01T23:59:59Z',assignee_profile_id:member}),row(7,'task',{project_id:id(5),title:'Blocked supplier',status:'blocked'}),row(8,'task',{project_id:id(4),title:'Next venue deadline',due_at:new Date(Date.now()+86400000).toISOString(),assignee_profile_id:id(21)}),row(9,'task',{project_id:id(4),title:'Completed permit',status:'completed'}),row(10,'contact',{company_id:id(2),title:'Maria contact',data:{email:'private-alpha@example.invalid'}}),row(11,'contact',{company_id:id(3),title:'Foreign contact',data:{email:'private-beta@example.invalid'}})];}
async function fixture(browser,width){const p=await browser.newPage({viewport:{width,height:1000}});let data=records(),role='owner',deny=false,hold=false,release,ops=0;const calls=[],downloads=[],errors=[];
 p.on('download',x=>downloads.push(x));p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>sessionStorage.setItem('zoi.mobile.refresh.v1',JSON.stringify({refresh_token:'fixture'})));
 await p.route('https://csebihpaychdkanjjsmz.supabase.co/**',async route=>{const url=route.request().url(),name=url.split('/').pop(),args=route.request().postDataJSON();calls.push({name,args});let body=[];
 if(url.includes('/auth/v1/token'))body={access_token:'fixture',refresh_token:'fixture',expires_at:Math.floor(Date.now()/1000)+3600,user:{id:actor,email:'qa@example.invalid'}};
 if(name==='zoi_me')body={authenticated:true,profile:{id:member},workspaces:[{id:ws,name:'Arts workspace',role},{id:other,name:'Other workspace',role:'owner'}]};
 if(name==='ops_records_list'){ops++;if(hold){hold=false;await new Promise(r=>release=r);}if(deny)return route.fulfill({status:403,contentType:'application/json',body:JSON.stringify({message:'not_authorized'})});body={ok:true,role,records:data,members:[{profile_id:member,display_name:'Maria'},{profile_id:id(21),display_name:'Nikos'}]};}
 if(name==='documents_list')body={ok:true,role,projects:data.filter(r=>r.kind==='project'),documents:[{id:id(30),workspace_id:ws,project_id:id(4),title:'Programme budget',current_version:2},{id:id(31),workspace_id:ws,project_id:id(5),title:'Supplier private budget',current_version:1}]};
 await route.fulfill({contentType:'application/json',body:JSON.stringify(body)});});
 const button=label=>p.getByRole('button',{name:label,exact:true});await p.goto(origin);await p.getByRole('tab',{name:/Grow/}).click();await p.getByRole('radio',{name:/Arts workspace/}).click();await button('Open Business operations').click();await button('Open company workspace · Alpha Arts').waitFor();
 return{p,button,calls,downloads,errors,get data(){return data;},set data(value){data=value;},setRole(value){role=value;},setDeny(){deny=true;},held(){hold=true;},async waitHeld(){for(let n=0;!release&&n<200;n++)await new Promise(r=>setTimeout(r,10));assert(release);},release(){release();},get ops(){return ops;}};
}
async function downloadJSON(f){const pending=f.p.waitForEvent('download');await f.button('Export reviewed company records').click();const dl=await pending;assert.equal(dl.suggestedFilename(),'zoi-company-'+id(2)+'.json');return JSON.parse(fs.readFileSync(await dl.path(),'utf8'));}
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});let count=0;try{for(const width of[390,1440]){
 const f=await fixture(browser,width),{p,button}=f;
 await button('Open work task · Blocked supplier').waitFor();await button('Open work task · Overdue budget').waitFor();assert.equal(await button('Open work task · Next venue deadline').count(),0);
 await button('Next 7 days').click();await button('Open work task · Next venue deadline').waitFor();assert.equal(await button('Open work task · Blocked supplier').count(),0);
 await button('All work').click();await button('Filter assignee · Maria').click();await button('Open work task · Overdue budget').waitFor();assert.equal(await button('Open work task · Blocked supplier').count(),0);await button('Everyone').click();
 await p.getByLabel('Search saved company work',{exact:true}).fill('Supply contract');await button('Open work task · Blocked supplier').waitFor();assert.equal(await button('Open work task · Overdue budget').count(),0);await p.getByLabel('Search saved company work',{exact:true}).fill('');
 await button('All work').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(evidence,'queue-'+width+'.png'),fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await button('Open company workspace · Alpha Arts').click();await button('Open company task · Overdue budget').waitFor();assert.equal(await button('Open company task · Blocked supplier').count(),0);await button('Completed').click();await button('Open company task · Completed permit').waitFor();assert.equal(await button('Open company task · Overdue budget').count(),0);await button('All work').click();
 await button('Review company handover').click();await button('Export reviewed company records').waitFor();await p.screenshot({path:path.join(evidence,'handover-'+width+'.png'),fullPage:true});let packet=await downloadJSON(f);assert.equal(packet.company.data.legal_name,null);assert.equal(packet.company.id,id(2));assert.equal(packet.contacts.length,1);assert.equal(packet.contacts[0].data.email,'private-alpha@example.invalid');assert.equal(packet.document_records,null);assert.ok(!JSON.stringify(packet).includes('private-beta'));assert.ok(!f.calls.some(c=>c.name==='documents_list'));
 await button('Include authorized document records').click();await button('Review company handover').click();await button('Export reviewed company records').waitFor();packet=await downloadJSON(f);assert.equal(packet.document_records.length,1);assert.equal(packet.document_records[0].current_version,2);assert.ok(!JSON.stringify(packet).includes('Supplier private budget'));
 await button('Review company handover').click();await button('Export reviewed company records').waitFor();f.data[0]={...f.data[0],version:2,data:{legal_name:'Updated owner record'}};await button('Export reviewed company records').click();await p.getByText('Company records or access changed. Review the current records before sharing.',{exact:true}).waitFor();assert.equal(f.downloads.length,2);assert.equal(await button('Export reviewed company records').count(),0);
 await button('Review company handover').click();await button('Export reviewed company records').waitFor();await button('Discard handover review').click();assert.equal(await button('Export reviewed company records').count(),0);
 assert.deepEqual(f.errors,[]);assert.equal(f.calls.filter(c=>/mutation|archive|upload/.test(c.name)).length,0);await p.close();console.log('PASS native Company console full filters + reviewed current export',width);count++;
 for(const mode of ['viewer','downgraded-review','expired','foreign-record','account','workspace','unmount']){
  const f=await fixture(browser,width),{p,button}=f;await button('Open company workspace · Alpha Arts').click();
  if(['account','workspace','unmount'].includes(mode)){f.held();await button('Review company handover').click();await f.waitHeld();await button('← All workspace tools').click();if(mode==='account')await button('Sign out').click();else if(mode==='workspace')await p.getByRole('radio',{name:/Other workspace/}).click();else await p.getByRole('tab',{name:/Home/}).click();f.release();await p.waitForTimeout(150);assert.equal(await button('Export reviewed company records').count(),0);assert.equal(await p.getByText('Company record handover',{exact:true}).count(),0);
  }else if(mode==='downgraded-review'){await button('Include authorized document records').click();await button('Review company handover').click();await button('Export reviewed company records').waitFor();f.setRole('viewer');await button('Reload records').click();await p.getByText('Private files require an authorized editor or owner.',{exact:true}).waitFor();assert.equal(await button('Export reviewed company records').count(),0);assert.equal(await button('Include authorized document records').count(),0);assert.equal(f.downloads.length,0);
  }else if(mode==='viewer'){f.setRole('viewer');await button('Reload records').click();await button('Review company handover').waitFor();assert.equal(await button('Include authorized document records').count(),0);await button('Review company handover').click();await button('Export reviewed company records').waitFor();const packet=await downloadJSON(f);assert.equal(packet.document_records,null);assert.equal(await button('Start company project').count(),0);assert.ok(!f.calls.some(c=>c.name==='documents_list'));
  }else{await button('Review company handover').click();await button('Export reviewed company records').waitFor();if(mode==='expired')f.setDeny();else f.data[1].workspace_id=other;await button('Export reviewed company records').click();await p.getByRole('alert').first().waitFor();assert.equal(f.downloads.length,0);assert.equal(await button('Export reviewed company records').count(),0);}
  assert.deepEqual(f.errors,[]);assert.equal(f.calls.filter(c=>/mutation|archive|upload/.test(c.name)).length,0);assert.ok(!Object.values(await p.evaluate(()=>({...sessionStorage,...localStorage}))).some(v=>String(v).includes('private-alpha')));await p.close();console.log('PASS native Company handover',width,mode);count++;
 }
 const sparse=await fixture(browser,width);sparse.data=[row(2,'company',{title:'Alpha Arts'})];await sparse.button('Reload records').click();await sparse.p.getByText('Start a company project, then add an assigned task and deadline.',{exact:true}).waitFor();await sparse.button('Open company workspace · Alpha Arts').click();await sparse.button('Review company handover').click();await sparse.button('Export reviewed company records').waitFor();const empty=await downloadJSON(sparse);assert.equal(empty.tasks.length,0);assert.equal(empty.contacts.length,0);await sparse.p.screenshot({path:path.join(evidence,'sparse-'+width+'.png'),fullPage:true});await sparse.p.close();console.log('PASS native sparse Company review',width);count++;
 }fs.writeFileSync(path.join(evidence,'browser-results.json'),JSON.stringify({status:'passed',journeys:count,widths:[390,1440],boundary:'Actual compiled Expo native App on web; all Supabase calls controlled, no live writes. Physical iOS/Android OS share remains open.'},null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
