const {chromium}=require('playwright-core'),fs=require('node:fs/promises'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const root=process.env.CANDIDATE_ROOT||path.resolve(__dirname,'../../..'),out=process.env.EVIDENCE_DIR;if(!out)throw Error('EVIDENCE_DIR required');
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local');let p=u.pathname;if(p.startsWith('/business/')){res.writeHead(302,{Location:'https://www.zoi.city'+p});return res.end();}if(p.endsWith('/'))p+='index.html';const file=path.resolve(root,'.'+p);if(!file.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':p.endsWith('.json')?'application/json':'text/javascript');res.end(await fs.readFile(file));}catch{res.statusCode=404;res.end();}});
(async()=>{await fs.mkdir(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const report={candidate_root:root,controlled_rpc:false,source:'actual anonymous production readers',canonical:'actual ordinary production pages',cases:[]};try{
for(const width of[390,1440])for(const item of[{q:'OPA',name:'OPA Productions',more:true},{q:'SIGNAT',name:'Signature Productions'},{q:'Yamas',name:'Yamas Greek Restaurant'},{q:'Yamas',name:'Yamas Greek Restaurant',country:'Kenya',city:'Nairobi'},{q:'SIGNAT',name:'Signature Productions',country:'Canada',city:'North York'},{q:'Yamas',name:'Yamas Greek Restaurant',country:'Kenya',city:'Nairobi',initial:true},{q:'SIGNAT',name:'Signature Productions',country:'Canada',city:'North York',initial:true},{q:'zzzxqvNoGreekListing987654',empty:true}]){
 const context=await browser.newContext({viewport:{width,height:1000},isMobile:width===390,hasTouch:width===390,serviceWorkers:'block'}),page=await context.newPage(),errors=[],calls=[],blocked=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/rest/v1/rpc/'))calls.push({fn:r.url().split('/').pop(),args:r.postDataJSON()});});await page.route('**/*',r=>{const fn=new URL(r.request().url()).pathname.split('/').pop();if(r.request().url().includes('/rest/v1/rpc/')&&/(save|write|update|send|create|delete|reserve|publish|checkout|claim|commit|insert|configure)/i.test(fn)){blocked.push(fn);return r.abort();}return r.continue();});const result={width,...item,calls,errors,blocked};report.cases.push(result);
 try{await page.goto(origin+'/explore/'+(item.initial?'?city='+encodeURIComponent(item.city)+'&country='+encodeURIComponent(item.country):''));await page.waitForFunction(()=>document.querySelector('#q')?.getAttribute('role')==='combobox');
 if(item.initial){assert.equal(await page.locator('#city-sel').inputValue(),item.city);assert.equal(await page.locator('#country-sel').inputValue(),item.country);}
 if(item.city&&!item.initial){await page.getByRole('button',{name:'Find a city',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('combobox',{name:'Country for city search'}).locator('option[value="'+item.country+'"]').waitFor({state:'attached'});await dialog.getByRole('combobox',{name:'Country for city search'}).selectOption(item.country);const city=dialog.getByRole('combobox',{name:'Find a city'});await city.waitFor();await page.waitForFunction(()=>!document.querySelector('[data-query]').disabled);await city.fill(item.city);await dialog.getByRole('option',{name:item.city,exact:true}).waitFor();await page.screenshot({path:path.join(out,`${width}-${item.city}-picker.png`)});if(width===390)await dialog.getByRole('option',{name:item.city,exact:true}).tap();else{await city.press('ArrowDown');await city.press('Enter');}await dialog.waitFor({state:'hidden'});assert.equal(await page.locator('#city-sel').inputValue(),item.city);assert.equal(new URL(page.url()).searchParams.get('city'),item.city);assert.equal(new URL(page.url()).searchParams.get('country'),item.country);}
 const input=page.locator('#q'),box=page.locator('.discovery-suggestions').first();const started=Date.now();await input.fill(item.q);await box.waitFor({state:'visible'});await page.waitForFunction(()=>{const x=document.querySelector('.discovery-suggestions');return x&&!x.hidden&&!x.textContent.includes('Finding matches');},{},{timeout:15000});result.suggestion_ms=Date.now()-started;assert(!(await box.innerText()).includes('Suggestions could not load'));
 if(item.empty){assert.match(await box.innerText(),/No matching pages/);}else{if(item.more){assert.equal(await box.getByRole('option').count(),6);assert(await box.getByRole('button',{name:/Show more matches/}).isVisible());}
 if(width===390){for(let i=0;i<6&&!await box.getByRole('option').filter({has:page.locator('strong',{hasText:new RegExp('^'+item.name+'$')})}).count();i++)await box.getByRole('button',{name:/Show more matches/}).tap();const target=box.getByRole('option').filter({has:page.locator('strong',{hasText:new RegExp('^'+item.name+'$')})});assert.equal(await target.count(),1);await target.scrollIntoViewIfNeeded();if(item.more)await page.screenshot({path:path.join(out,width+'-OPA-expanded.png')});await target.tap();}else{let found=false;for(let i=0;i<32;i++){await input.press('ArrowDown');const active=await input.getAttribute('aria-activedescendant');const text=await page.locator('#'+active+' strong').innerText();if(text===item.name){found=true;break;}}assert(found);if(item.more)await page.screenshot({path:path.join(out,width+'-OPA-expanded.png')});await input.press('Enter');}
 await page.waitForURL(u=>u.hostname==='www.zoi.city'&&u.pathname.startsWith('/business/'),{timeout:20000});await page.getByRole('heading',{level:1}).waitFor();assert((await page.locator('body').innerText()).toLowerCase().includes(item.name.toLowerCase()));result.canonical=page.url();}
 assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));result.passed=true;await page.screenshot({path:path.join(out,`${width}-${item.q}-${item.city||'global'}${item.initial?'-initial':''}-result.png`)});
 }catch(e){result.passed=false;result.failure=e.message;await page.screenshot({path:path.join(out,`${width}-${item.q}-${item.city||'global'}-failure.png`)}).catch(()=>{});}finally{await context.close();}console.log(JSON.stringify({width,q:item.q,city:item.city,passed:result.passed,ms:result.suggestion_ms,failure:result.failure}));
}
}finally{await browser.close();await new Promise(r=>server.close(r));report.passed=report.cases.every(x=>x.passed)&&report.cases.length===16;await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');if(!report.passed)process.exitCode=1;}})().catch(e=>{console.error(e);process.exitCode=1;});
