const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const base=path.resolve(__dirname,'../../..'),out=process.env.QA_OUTPUT_DIR||path.join(base,'docs/audits/evidence/source-authority-producer-2026-10-03');
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local'),file=path.resolve(base,'.'+url.pathname);if(!file.startsWith(base+path.sep)||!(url.pathname.startsWith('/assets/')||url.pathname.startsWith('/tests/browser/source-authority/')))throw Error();res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8');res.end(await fs.readFile(file));}catch{res.statusCode=404;res.end();}});
const retired='Your current access could not be confirmed. Sign in and reopen Business home before editing.';
(async()=>{await fs.mkdir(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,report={controlled:true,production:false,no_live_writes:true,cases:[]};let browser;
try{browser=await chromium.launch({executablePath:'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});
for(const width of[390,1440])for(const scenario of['open','foreground-page','foreground-status','save','expired-local-session','revoked-listing','uncertain-read','uncertain-save','version-change','authorized-focus']){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+'/tests/browser/source-authority/fixture.html');
 const panel=page.getByRole('region',{name:'Website and source review'}),input=page.getByLabel('Official website address');await panel.waitFor();await input.fill('https://private-unsaved.example/');
 if(scenario==='open'){await page.evaluate(()=>{qa.failure='suite_session_unavailable';qa.failureFn='home_content_get';return qa.mount();});}
 if(scenario==='foreground-page'||scenario==='foreground-status'){await page.evaluate(fn=>{qa.failure='suite_session_unavailable';qa.failureFn=fn;window.dispatchEvent(new Event('focus'));},scenario==='foreground-page'?'home_content_get':'bizpage_status');}
 if(scenario==='save'){await page.evaluate(()=>{qa.failure='invitation_unavailable';qa.failureFn='home_content_save';});await page.getByRole('button',{name:'Save page',exact:true}).click();}
 if(scenario==='expired-local-session'){await page.evaluate(()=>{qa.fresh=false;window.dispatchEvent(new Event('focus'));});}
 if(scenario==='revoked-listing'){await page.evaluate(()=>{qa.statusRevoked=true;window.dispatchEvent(new Event('focus'));});}
 if(['open','foreground-page','foreground-status','save','expired-local-session','revoked-listing'].includes(scenario)){await page.getByText(retired,{exact:true}).waitFor();assert.equal(await panel.count(),0);assert.equal(await page.locator('input,textarea').count(),0);assert(!await page.locator('#root').textContent().then(t=>t.includes('private-unsaved')));await page.screenshot({path:path.join(out,`${scenario}-${width}.png`)});}
 if(scenario==='uncertain-read'){await page.evaluate(()=>{qa.failure='unclassified_server_failure';qa.failureFn='home_content_get';window.dispatchEvent(new Event('focus'));});await page.waitForFunction(()=>qa.readCalls.filter(n=>n==='home_content_get').length>=2);assert.equal(await input.inputValue(),'https://private-unsaved.example/');assert(!await input.isDisabled());assert.equal(await page.evaluate(()=>qa.writes.length),0);}
 if(scenario==='uncertain-save'){await page.evaluate(()=>{qa.failure='unclassified_server_failure';qa.failureFn='home_content_save';});await page.getByRole('button',{name:'Save page',exact:true}).click();await page.getByRole('button',{name:'Retry this save',exact:true}).waitFor();assert.equal(await input.inputValue(),'https://private-unsaved.example/');assert(await input.isDisabled());await page.evaluate(()=>{qa.failure=null;});await page.getByRole('button',{name:'Retry this save',exact:true}).click();await page.getByText('Saved. Your page details and menu are updated.',{exact:true}).waitFor();assert.deepEqual(...await page.evaluate(()=>qa.rpcCalls.filter(c=>c.name==='home_content_save').map(c=>c.args)));}
 if(scenario==='version-change'){await page.evaluate(()=>{qa.version='c'.repeat(32);window.dispatchEvent(new Event('focus'));});await page.getByText('This page changed elsewhere. Your unsaved text is still here. Reload the saved details before publishing.',{exact:true}).waitFor();assert.equal(await input.inputValue(),'https://private-unsaved.example/');await page.getByRole('button',{name:'Save page',exact:true}).click();await page.getByText('Reload your page before saving so existing changes stay safe.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>qa.writes.length),0);}
 if(scenario==='authorized-focus'){await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForFunction(()=>qa.readCalls.filter(n=>n==='home_content_get').length>=2);assert.equal(await input.inputValue(),'https://private-unsaved.example/');await page.getByRole('button',{name:'Save page',exact:true}).click();await page.getByText('Saved. Your page details and menu are updated.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>qa.owner_content.website),'https://private-unsaved.example/');}
 assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);report.cases.push({width,scenario,passed:true});await page.close();
}report.status='passed';
}catch(error){report.status='failed';report.failure=error.message;throw error;}finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');await browser?.close();await new Promise(r=>server.close(r));}console.log(JSON.stringify({status:report.status,cases:report.cases.length}));})().catch(e=>{console.error(e);process.exitCode=1;});
