const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const root=path.resolve(__dirname,'../../..'),id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const server=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://local').pathname,file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+'/'))throw Error();let body=await fs.readFile(file);if(pathname.endsWith('/fixture.html')){let s=body.toString();for(const [n,a]of[['name','args'],['n','p']])s=s.replace(`rpc:async(${n},${a})=>{`,`rpc:async(${n},${a})=>{window.serviceCalls.push({name:${n},args:${a}});if(${n}==='event_service_capabilities'&&window.capabilityMode==='absent')return null;if(${n}==='event_service_capabilities'&&window.capabilityMode==='malformed')return{ok:true,version:'1'};`);body=s;}res.setHeader('Content-Type',pathname.endsWith('.html')?'text/html':'text/javascript');res.end(body);}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;let browser;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});for(const width of[390,1440])for(const tool of['menu','queue','setup','operator','guest']){
 const actor=tool==='menu'?'11111111-1111-4111-8111-111111111111':id(tool==='setup'?6:2),ws=tool==='menu'?'22222222-2222-4222-8222-222222222222':id(1),event=id(tool==='setup'?2:3),request=id(901);
 let key,marker;if(tool==='menu'){key=`zoi:service-menu:v1:${actor}:${ws}`;marker={actor,workspace:ws,request,item:null,expected:0};}else if(tool==='queue'){key=`zoi:service-queue:${actor}:${ws}`;marker={actor,workspace:ws,request,order:id(3),expected:1,next:'preparing'};}else if(tool==='setup'){key=`zoi:event-service-setup:${actor}:${ws}`;marker={actor,workspace:ws,request,event,venue:id(3),expected:0};}else{const context=tool==='guest'?event:ws;key=`zoi:event-service:${actor}:${context}`;marker={actor,context,request,kind:tool==='guest'?'order':'start',scope:tool==='guest'?id(5):id(4),table:id(6),event};}
 const p=await browser.newPage({viewport:{width,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await p.addInitScript(({key,marker})=>{window.serviceCalls=[];window.capabilityMode='absent';sessionStorage.setItem(key,JSON.stringify(marker));},{key,marker});
 const folder={menu:'service-menu',queue:'service-queue',setup:'event-service-setup',operator:'event-service-lifecycle',guest:'event-service-lifecycle'}[tool];await p.goto(origin+`/tests/browser/${folder}/fixture.html`);if(tool==='setup')await p.getByRole('button',{name:'Set up event service',exact:true}).click();if(tool==='guest')await p.evaluate(()=>qa.mount('guest'));
 await p.getByText(/This service tool is not available/).last().waitFor();await fs.mkdir('/tmp/service-capabilities-candidate',{recursive:true});await p.screenshot({path:`/tmp/service-capabilities-candidate/${tool}-${width}.png`});const check={menu:'Check result',queue:'Check update result',setup:'Check setup result',operator:'Check result',guest:'Check result'}[tool],reload={menu:'Refresh catalogue',queue:'Refresh queue',setup:'Reload service setup (discard draft)',operator:'Reload service details',guest:'Refresh service'}[tool];assert.equal(await p.getByRole('button',{name:check,exact:true}).isDisabled(),true);assert.equal(await p.evaluate(key=>sessionStorage.getItem(key),key),JSON.stringify(marker));assert.ok((await p.evaluate(()=>serviceCalls)).every(c=>c.name==='event_service_capabilities'));
 await p.evaluate(()=>capabilityMode='malformed');await p.getByRole('button',{name:reload,exact:true}).click();await p.waitForTimeout(30);assert.equal(await p.getByRole('button',{name:check,exact:true}).isDisabled(),true);assert.ok((await p.evaluate(()=>serviceCalls)).every(c=>c.name==='event_service_capabilities'));
 await p.evaluate(()=>capabilityMode='installed');await p.getByRole('button',{name:reload,exact:true}).click();await p.waitForFunction(label=>[...document.querySelectorAll('button')].some(b=>b.textContent===label&&!b.disabled),check);
 const cancel={menu:'Cancel if not saved',queue:'Cancel unconfirmed update',setup:'Cancel if not saved',operator:'Cancel if not submitted',guest:'Cancel if not submitted'}[tool];await p.getByRole('button',{name:cancel,exact:true}).click();await p.waitForFunction(key=>sessionStorage.getItem(key)===null,key);
 const calls=await p.evaluate(()=>serviceCalls);assert.equal(calls.filter(c=>c.name.endsWith('_request')).length,1);assert.equal(calls.some(c=>/_save|_once|event_service_order$|event_service_start$/.test(c.name)),false);assert.deepEqual(errors,[]);assert.equal(await p.locator('body').evaluate(e=>e.scrollWidth<=innerWidth),true);console.log('PASS',width,tool,'absent/malformed startup zero private dispatch, marker retained, explicit availability then scoped cancellation');await p.close();
 }}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
