import {readFile,unlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {routeFor} from './evidence.mjs';
const execute=promisify(execFile);
export async function browserEvidence(row,{origin='https://www.zoi.city',command=process.env.AGENT_BROWSER_BIN||'agent-browser',run=execute}={}){
 const base=new URL(origin);if(base.origin!==origin||!['https:','http:'].includes(base.protocol))throw Error('invalid_browser_origin');
 const session='quality-'+row.listing_id,call=async args=>{const {stdout}=await run(command,['--session',session,...args,'--json'],{timeout:30000,maxBuffer:1500000,env:Object.fromEntries(['PATH','HOME','TMPDIR','XDG_RUNTIME_DIR','DISPLAY','NODE_EXTRA_CA_CERTS'].filter(k=>process.env[k]).map(k=>[k,process.env[k]]))});let r;try{r=JSON.parse(stdout)}catch{throw Error('browser_output_unconfirmed')}if(!r.success)throw Error('browser_action_failed');return r.data?.result??r.data};
 const screens=[];let control={passed:false,kind:'none'};
 try{
  await call(['open',origin+routeFor(row)]);
  await call(['eval','Promise.race([Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.addEventListener("load",resolve,{once:true});img.addEventListener("error",resolve,{once:true})}))),new Promise(resolve=>setTimeout(resolve,4000))]).then(()=>true)']);
  for(const width of [390,1440]){await call(['set','viewport',String(width),'1000']);const s=await call(['eval','('+function(name,origin){const visible=n=>{const r=n.getBoundingClientRect();return r.width>0&&r.height>0&&getComputedStyle(n).visibility!=='hidden'};const norm=s=>String(s||'').normalize('NFKC').toLocaleLowerCase('en').replace(/\([^)]*\)/g,' ').replace(/[\p{P}\p{S}\s]+/gu,' ').trim();const body=document.body.innerText;const links=[...document.querySelectorAll('main a[href]')].filter(visible),buttons=[...document.querySelectorAll('main button')].filter(visible);const controls=[...links,...buttons];const primary=controls.filter(n=>n.matches('.primary,.btn-primary,[data-primary],.hero button,.hero a'));const supported=n=>n.matches('[data-prepare],[data-home-photo],[data-vcard]')||n.tagName==='A'&&/^(#|tel:|mailto:|https:\/\/)/.test(n.getAttribute('href')||'');return{width:innerWidth,identityPresent:norm(body).includes(norm(name)),overflow:document.documentElement.scrollWidth>innerWidth+1,brokenImages:[...document.querySelectorAll('main img')].filter(n=>visible(n)&&(!n.complete||!n.naturalWidth)).length,emptyControls:controls.filter(n=>!n.innerText.trim()&&!n.getAttribute('aria-label')&&!n.querySelector('img[alt]')).length,unsafeLinks:links.filter(n=>!/^(https?:|mailto:|tel:|\/|#)/.test(n.getAttribute('href')||'')).length,deadAnchors:links.filter(n=>{const href=n.getAttribute('href');if(!href?.startsWith('#'))return false;return href==='#'||!document.getElementById(decodeURIComponent(href.slice(1)))}).length,httpOriginMismatch:location.origin!==origin,untestedPrimary:primary.filter(n=>!supported(n)).length,vcard:!!document.querySelector('main [data-vcard]'),localDialog:!!document.querySelector('main [data-prepare]'),gallery:!!document.querySelector('main [data-home-photo]'),details:!!document.querySelector('main details>summary')};}.toString()+')('+JSON.stringify(row.name)+','+JSON.stringify(origin)+')']);screens.push(s)}
  const last=screens.at(-1);
  if(last.localDialog){await call(['eval','document.querySelector("main [data-prepare]").setAttribute("data-quality-target","prepare")']);await call(['click','[data-quality-target="prepare"]']);const opened=await call(['eval','!!document.querySelector("dialog[open]")']);await call(['press','Escape']);const closed=await call(['eval','!document.querySelector("dialog[open]")']);control={passed:opened&&closed,kind:'contact_checklist_open_escape'};}
  else if(last.gallery){await call(['eval','document.querySelector("main [data-home-photo]").setAttribute("data-quality-target","gallery")']);await call(['click','[data-quality-target="gallery"]']);const opened=await call(['eval','!!document.querySelector("dialog[open] img")']);await call(['press','Escape']);const closed=await call(['eval','!document.querySelector("dialog[open]")']);control={passed:opened&&closed,kind:'source_gallery_open_escape'};}
  else if(last.details){await call(['eval','document.querySelector("main details>summary").setAttribute("data-quality-target","details")']);await call(['click','[data-quality-target="details"]']);const opened=await call(['eval','!!document.querySelector("main details[open]")']);await call(['eval','document.querySelector("main details>summary").setAttribute("data-quality-target","details")']);await call(['click','[data-quality-target="details"]']);const closed=await call(['eval','!document.querySelector("main details[open]")']);control={passed:opened&&closed,kind:'details_expand_collapse'};}
  if(last.vcard){const target=path.join(tmpdir(),'zoi-quality-'+row.listing_id+'.vcf');try{await call(['eval','document.querySelector("main [data-vcard]").setAttribute("data-quality-target","vcard")']);await call(['download','[data-quality-target="vcard"]',target]);const card=await readFile(target,'utf8'),normalize=v=>v.normalize('NFKC').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[\p{P}\p{S}\s]+/gu,' ').trim();const fn=card.match(/^FN:(.*)$/m)?.[1]||'';const passed=card.length<16000&&card.includes('BEGIN:VCARD')&&card.includes('END:VCARD')&&normalize(fn)===normalize(row.name);control={...control,passed:control.passed&&passed,vcard_checked:passed};}finally{await unlink(target).catch(()=>{})}}
  return{screens,control};
 }finally{try{await call(['close'])}catch{}}
}
