const {chromium}=require('playwright-core'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'../../..'),ws='10000000-0000-4000-8000-000000000001';
const html=`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>:root{--tx:#f4f8ff;--mut:#afc4d9;--bg2:#132a40;--bg3:#0b1b2c;--line:#40576d;--acc:#166bd6;--green:#8be3ab}body{margin:18px;background:#081725;color:var(--tx);font:14px system-ui}main{max-width:900px;margin:auto}button,select{min-height:44px}</style><main id="app"></main><script>
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');window.qa={actor:id(1),role:'owner',mode:'ok',calls:[],receipts:{},members:[{id:id(11),profile_id:id(1),name:'Owner',role:'owner',revision:id(21),protected:true},{id:id(12),profile_id:id(2),name:'Alex Pappas',role:'editor',revision:id(22),protected:false},{id:id(13),profile_id:id(3),name:'Administrator',role:'admin',revision:id(23),protected:false}]};
window.C={auth:{load:()=>({user_id:qa.actor})},api:{rpc:async(n,a)=>{qa.calls.push({n,a});if(qa.mode==='denied')throw Object.assign(Error('not_authorized'),{status:403});if(n==='workspace_settings_get')return {ok:true,workspace_id:'${ws}',role:qa.role,identity:{name:'Signature team',version:id(31)},voice:{version:id(32),business_name:'Signature',about:'',tone:'Professional',languages:'English',sample:''}};if(n==='workspace_team_get'){if(qa.mode==='readfail')throw Error('Offline');return{ok:true,workspace_id:'${ws}',role:qa.role,actor_profile_id:id(1),members:qa.members};}if(n==='workspace_team_request'){if(a.p_cancel_if_missing&&!qa.receipts[a.p_request])qa.receipts[a.p_request]={ok:false,cancelled:true,workspace_id:'${ws}',request_id:a.p_request};return{ok:true,workspace_id:'${ws}',request_id:a.p_request,found:!!qa.receipts[a.p_request],result:qa.receipts[a.p_request]};}if(n==='workspace_team_save'){if(qa.mode==='unknown')throw Error('Network lost');let r={ok:true,workspace_id:'${ws}',request_id:a.p_request,member_id:a.p_member,profile_id:a.p_profile};if(qa.mode==='conflict')r={...r,ok:false,error:'membership_conflict'};else{const m=qa.members.find(x=>x.id===a.p_member);if(a.p_action==='remove')qa.members=qa.members.filter(x=>x!==m);else{m.role=a.p_role;m.revision=crypto.randomUUID();}}qa.receipts[a.p_request]=r;if(qa.mode==='lost')throw Error('Response lost');return r;}throw Error('Unexpected '+n);}}};window.ctx={C,ws:'${ws}',toast:()=>{}};
</script><script src="/assets/suite/settings.js"></script><script>window.mount=()=>ZoiSuite.modules.find(m=>m.id==='settings').mount(document.getElementById('app'),ctx);mount();</script>`;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');res.setHeader('content-type',u.pathname.startsWith('/assets/')?'text/javascript':'text/html');res.end(u.pathname.startsWith('/assets/')?await fs.readFile(path.join(base,u.pathname)):html);}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});for(const width of[390,1440]){const p=await browser.newPage({viewport:{width,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const origin='http://127.0.0.1:'+server.address().port;await p.goto(origin);const team=()=>p.locator('section').filter({has:p.getByRole('heading',{name:'Your team',exact:true})});const member=()=>p.getByRole('region',{name:'Team member Alex Pappas'});await member().waitFor();assert.equal(await p.getByRole('region',{name:'Team member Owner'}).getByRole('button').count(),0);
await member().getByRole('combobox').selectOption('viewer');await member().getByRole('button',{name:'Save role'}).click();await p.getByText('Team change confirmed.',{exact:true}).waitFor();assert.equal(await member().getByRole('combobox').inputValue(),'viewer');
await p.evaluate(()=>qa.mode='lost');await member().getByRole('combobox').selectOption('editor');await member().getByRole('button',{name:'Save role'}).click();await p.getByRole('button',{name:'Check team change'}).waitFor();await p.evaluate(()=>mount());await p.getByRole('button',{name:'Check team change'}).click();await p.getByText('Team change confirmed.',{exact:true}).waitFor();assert.equal(await member().getByRole('combobox').inputValue(),'editor');
await p.evaluate(()=>qa.mode='unknown');await member().getByRole('combobox').selectOption('viewer');await member().getByRole('button',{name:'Save role'}).click();await p.getByRole('button',{name:'Check team change'}).click();await p.getByText('No completed change was found. Check again or safely cancel it.',{exact:true}).waitFor();await p.getByRole('button',{name:'Cancel unconfirmed change'}).click();await p.getByText('Unconfirmed change cancelled.',{exact:true}).waitFor();
await p.evaluate(()=>qa.mode='conflict');await member().getByRole('combobox').selectOption('viewer');await member().getByRole('button',{name:'Save role'}).click();await p.getByText('This membership changed elsewhere. Review the refreshed team before trying again.',{exact:true}).waitFor();
await p.evaluate(()=>{qa.mode='ok';qa.role='admin';});await p.getByRole('button',{name:'Refresh team'}).click();assert.equal(await p.getByRole('region',{name:'Team member Administrator'}).getByRole('button').count(),0);assert.equal(await member().getByRole('combobox').locator('option[value=admin]').count(),0);
await member().getByRole('button',{name:'Remove member',exact:true}).click();await p.getByRole('button',{name:'Keep member'}).click();assert.equal(await member().count(),1);await member().getByRole('button',{name:'Remove member',exact:true}).click();await p.screenshot({path:'/tmp/workspace-team-'+width+'.png',fullPage:true});await p.getByRole('button',{name:'Confirm removal'}).click();await member().waitFor({state:'detached'});
await p.evaluate(()=>qa.role='viewer');await p.getByRole('button',{name:'Refresh team'}).click();assert.equal(await team().getByRole('combobox').count(),0);
await p.evaluate(()=>qa.mode='readfail');await p.getByRole('button',{name:'Refresh team'}).click();await p.getByRole('button',{name:'Retry loading team'}).waitFor();await p.evaluate(()=>qa.mode='ok');await p.getByRole('button',{name:'Retry loading team'}).click();await p.getByRole('button',{name:'Refresh team'}).waitFor();
await p.evaluate(()=>{qa.actor='00000000-0000-4000-8000-000000000099';dispatchEvent(new Event('focus'));});await p.getByText('Your account or workspace changed. Reopen Settings to continue.',{exact:true}).waitFor();assert.equal(await p.getByText('Alex Pappas',{exact:true}).count(),0);assert.equal(await p.locator('body').evaluate(el=>el.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS workspace team',width,'mounted Settings, role save, owner/admin/viewer, lost response/remount, unknown cancellation, stale conflict, removal confirmation, failure retry, account clear');await p.close();}}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
