const {chromium}=require('playwright-core');const assert=require('node:assert/strict');const http=require('node:http');const fs=require('node:fs/promises');const path=require('node:path');const base=path.resolve(__dirname,'../../..');
const sourceOrigin=process.env.WORKSPACE_SOURCE_ORIGIN||'',sourceCache=new Map();async function source(name){if(!sourceOrigin)return fs.readFile(path.join(base,name));if(!sourceCache.has(name)){const response=await fetch(new URL('/'+name,sourceOrigin));if(!response.ok)throw Error('Source fetch '+name+' '+response.status);sourceCache.set(name,Buffer.from(await response.arrayBuffer()));}return sourceCache.get(name);}
const actor='11111111-1111-4111-8111-111111111111',old='22222222-2222-4222-8222-222222222222',fresh='55555555-5555-4555-8555-555555555555',listing='33333333-3333-4333-8333-333333333333',missing='44444444-4444-4444-8444-444444444444';
const other='77777777-7777-4777-8777-777777777777';
const stub=`<script>window.qa={actor:'${actor}',writes:0,reads:[],mode:'ok',workspaces:[{id:'${old}',name:'Old business',kind:'business',role:'owner'},{id:'${other}',name:'Other business',kind:'business',role:'owner'}]};if(new URL(location.href).searchParams.has('qa-empty'))qa.workspaces=[];window.ZoiCore={BASE:location.origin,KEY:'fixture',esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),theme:{init:()=>{}},auth:{load:()=>({user_id:qa.actor}),token:()=>qa.actor,ensureFresh:async()=>true,clear:()=>{},signOut:async()=>{}},api:{rpc:async(n,a)=>{if(n==='zoi_me'){qa.meCalls=(qa.meCalls||0)+1;const snapshot=structuredClone(qa.workspaces);if(qa.holdMe)await new Promise(r=>(qa.releases||(qa.releases=[])).push(r));return{authenticated:true,workspaces:snapshot};}if(n==='suite_config')return{};if(n==='social_channels_list')return[];if(n==='zoi_create_workspace'){qa.writes++;await new Promise(r=>setTimeout(r,100));qa.workspaces.push({id:'${fresh}',name:a.p_name,kind:a.p_kind,role:'owner'});if(qa.mode==='lost')throw Error('Response lost');return{ok:true,workspace_id:'${fresh}',name:a.p_name,kind:a.p_kind};}if(n==='bizpage_status'&&new URL(location.href).searchParams.has('qa-claims'))return{ok:true,workspace_id:a.p_workspace,claims:[{listing_id:'${listing}',name:'Parea Arts Society',slug:'parea-arts',status:'claim_pending',submitted_at:'2026-10-01T08:00:00Z'},{listing_id:'${missing}',name:'Previously managed business',slug:'previously-managed',status:'claimed',submitted_at:'2026-09-30T08:00:00Z'}],owned:[]};if(n==='bizpage_status')return{ok:true,workspace_id:a.p_workspace,claims:[],owned:[{id:'${listing}',name:'First business',slug:'first',claimed:true}]};if(n==='home_content_get'){qa.reads.push(a.p_listing);return{ok:true,workspace_id:'${old}',listing_id:a.p_listing,version:'a'.repeat(32),entity_type:'business',category_slug:'shops',base:{description:'PRIVATE PROFILE'},profile:{},owner_content:{}};}throw Error('Unexpected RPC '+n);}}};window.ZoiSuite={modules:[{id:'priorities',label:'Overview',mount:(el,ctx)=>{qa.ctx=ctx;(qa.contexts||(qa.contexts=[])).push(ctx.ws);el.textContent='Overview '+ctx.ws;return{hasUnsavedChanges:()=>!!qa.dirty};}}]};</script>`;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/functions/v1/social-config'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({platforms:[],services:{}}));}let file;if(u.pathname.startsWith('/social')){let html=(await source('social/index.html')).toString('utf8');html=html.replace(/<script\b[^>]*src="([^"]+)"[^>]*><\/script>/g,(all,src)=>src.startsWith('/assets/suite/bizpage.js')?all:'').replace("<script>window.ZoiSuite",stub+'<script>window.ZoiSuite').replace(/<script>if\('serviceWorker'[\s\S]*?<\/script>/,'');res.setHeader('Content-Type','text/html');return res.end(html);}if(!u.pathname.startsWith('/assets/'))throw Error();file=path.resolve(base,'.'+u.pathname);if(!file.startsWith(base+path.sep))throw Error();res.setHeader('Content-Type',file.endsWith('.css')?'text/css':'text/javascript');res.end(await source(path.relative(base,file)));}catch{res.statusCode=404;res.end();}});
(async()=>{let browser;await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});for(const width of[390,1440]){const p=await browser.newPage({viewport:{width,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());async function home(){await p.goto(origin+'/social?workspace='+old);await p.locator('#workspace-context-name').waitFor();}async function create(){if(width<860)await p.locator('#hamb').click();await p.locator('#wsbtn').click();await p.locator('#ws-new').click();await p.waitForFunction(()=>!document.querySelector('#c-go').disabled);}
// Account transition while malformed history intent must not expose the old roster.
for(const signal of ['storage','focus','zoi:auth-change']){
 await home();
 await p.evaluate(signal=>{qa.actor='99999999-9999-4999-8999-999999999999';qa.workspaces=[];history.pushState(null,'','/social?workspace=bad');window.dispatchEvent(new Event(signal));},signal);
 await p.getByRole('heading',{name:'Choose your workspace'}).waitFor();
 assert.doesNotMatch(await p.locator('#root').innerText(),/Old business|Other business/);
 assert.equal(await p.locator('#mount').count(),0);
 assert.equal(await p.locator('#workspace-recovery option').count(),1);
 // Returning to the original account must obtain fresh authority, not resurrect cached state.
 await p.evaluate(({actor,old})=>{qa.actor=actor;qa.workspaces=[{id:old,name:'Returned workspace',kind:'business',role:'viewer'}];history.pushState(null,'','/social?workspace='+old);window.dispatchEvent(new Event('storage'));},{actor,old});
 await p.waitForFunction(()=>document.getElementById('workspace-context-name')?.textContent==='Returned workspace');
 assert.equal(await p.evaluate(()=>qa.ctx.role),'viewer');
}
// An old membership response must not overwrite a new account, including an invalid route.
await home();
await p.evaluate(id=>{qa.holdMe=true;qa.releases=[];history.pushState(null,'','/social?workspace='+id);window.dispatchEvent(new PopStateEvent('popstate'));},other);
await p.waitForFunction(()=>qa.releases.length===1);
await p.evaluate(()=>{qa.actor='99999999-9999-4999-8999-999999999999';qa.workspaces=[];history.pushState(null,'','/social?workspace=bad');window.dispatchEvent(new Event('storage'));qa.holdMe=false;qa.releases[0]();});
await p.getByRole('heading',{name:'Choose your workspace'}).waitFor();
await p.waitForTimeout(300);
assert.doesNotMatch(await p.locator('#root').innerText(),/Old business|Other business/);
assert.equal(await p.locator('#mount').count(),0);
assert.equal(await p.evaluate(()=>qa.meCalls),2);
assert.deepEqual(errors,[]);
console.log('PASS independent history',width,'account transition with invalid route, empty roster, returning authority and held prior-account response');
await p.close();}}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
