import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {spawn} from 'node:child_process';import {planAvailability} from '../../assets/bookings/planner.mjs';
const container=process.env.ZOI_TEST_POSTGRES_CONTAINER;let db='postgres';
function sql(q){return new Promise((resolve,reject)=>{const p=spawn('docker',['exec','-i',container,'psql','-U','postgres','-d',db,'-X','-qAt','-v','ON_ERROR_STOP=1']);let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('close',n=>n?reject(Error(err)):resolve(out.trim().split('\n').at(-1)));p.stdin.end(q);});}
const actor='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',viewer='00000000-0000-4000-8000-000000000003',ws='10000000-0000-4000-8000-000000000001',listing='20000000-0000-4000-8000-000000000001',quote=x=>"'"+String(x).replaceAll("'","''")+"'";
const as=(q,user=actor)=>sql(`set role authenticated;select set_config('request.jwt.claim.sub','${user}',false);${q}`);
const call=(name,args,user=actor)=>as(`select public.${name}(${args});`,user).then(JSON.parse);
const file=p=>readFileSync(new URL(p,import.meta.url),'utf8');
test('recurring booking plans enforce actor/version/expiry, atomic conflicts, retry and race safety with real PostgreSQL',{skip:!container},async t=>{
 const name='booking_planner_'+process.pid;await sql('create database '+name);db=name;t.after(async()=>{db='postgres';await sql('drop database '+name);});
 await sql(file('../database/venue-fixture.sql').replace('create role anon;create role authenticated;',''));await sql(file('../../supabase/migrations/20260930001839_venue_plans_and_atomic_seat_holds.sql'));await sql("alter table zoi.listings add column name text default 'QA business';create table public.menu_items(id uuid,workspace_id uuid,name text,description text,price_cents integer,currency text,station text,is_available boolean,sort_order integer);");await sql(file('../../supabase/migrations/20260930004059_booking_services_resources_and_reservations.sql'));await sql(file('../../supabase/migrations/20260930011100_booking_recurring_availability.sql'));
 await call('booking_settings_save',`'${ws}',0,'${listing}','Europe/Athens','EUR',false`);
 const service=(await call('booking_item_save',`'${ws}','service',null,0,'{"name":"Haircut","duration_minutes":60,"buffer_minutes":15,"price_cents":3500,"active":true}'`)).item;
 const resource=(await call('booking_item_save',`'${ws}','resource',null,0,'{"name":"Stylist","kind":"staff","capacity":1,"active":true}'`)).item;
 const date=new Date(Date.now()+3*86400000).toISOString().slice(0,10),pattern={dateFrom:date,dateTo:date,weekdays:[new Date(date+'T12:00Z').getUTCDay()],opens:'09:00',closes:'12:00'};
 const preview=(pat=pattern,user=actor)=>call('booking_plan_preview',`'${ws}','${service.id}','${resource.id}',${quote(JSON.stringify(pat))}`,user);
 const save=(p,id='70000000-0000-4000-8000-000000000001',user=actor)=>call('booking_plan_save',`'${ws}','${p.plan_id}','${id}'`,user);
 await t.test('preview matches pure planner and is private to owner/admin',async()=>{await assert.rejects(preview(pattern,viewer),/workspace_permission_denied/);await assert.rejects(preview(pattern,other),/workspace_permission_denied/);await assert.rejects(sql(`set role anon;select public.booking_plan_history('${ws}');`),/permission denied/);await assert.rejects(as('select * from zoi.booking_availability_plans;'),/permission denied/);
  const p=await preview(),expected=planAvailability({...pattern,timezone:'Europe/Athens',durationMinutes:60,bufferMinutes:15});assert.deepEqual(p.slots.map(x=>Date.parse(x.starts_at)),expected.map(x=>Date.parse(x.starts_at)));assert.equal(p.slots.length,2);assert.ok(p.slots.every(x=>x.conflicts.length===0));
 });
 await t.test('timezone resolver rejects DST gap/fold and roundtrips normal times',async()=>{for(const wall of ['2027-03-28 03:30','2026-10-25 03:30'])await assert.rejects(sql(`select zoi.booking_wall_instant('${wall}','Europe/Athens');`),/booking_dst_wall_time/);assert.equal(await sql("select zoi.booking_wall_instant('2026-10-26 09:00','Europe/Athens')=timestamptz '2026-10-26 07:00Z';"),'t');});
 await t.test('server weekly previews reject future DST transitions and elapsed-time crossing',async()=>{
  for(const month of [2,9]){let year=new Date().getUTCFullYear(),d;do{d=new Date(Date.UTC(year,month+1,0));d.setUTCDate(d.getUTCDate()-d.getUTCDay());if(d.getTime()>Date.now())break;year++;}while(true);const day=d.toISOString().slice(0,10);await assert.rejects(preview({dateFrom:day,dateTo:day,weekdays:[0],opens:'03:00',closes:'05:00'}),/booking_dst_wall_time/);}
  let year=new Date().getUTCFullYear(),d=new Date(Date.UTC(year,10,0));d.setUTCDate(d.getUTCDate()-d.getUTCDay());if(d.getTime()<Date.now()){d=new Date(Date.UTC(year+1,10,0));d.setUTCDate(d.getUTCDate()-d.getUTCDay());}const day=d.toISOString().slice(0,10);
  await sql(`update zoi.booking_services set duration_minutes=180,buffer_minutes=0,version=version+1 where id='${service.id}';`);
  await assert.rejects(preview({dateFrom:day,dateTo:day,weekdays:[0],opens:'02:00',closes:'05:00'}),/booking_dst_crossing/);
  await sql(`update zoi.booking_services set duration_minutes=60,buffer_minutes=15,version=version+1 where id='${service.id}';`);
 });
 await t.test('invalid patterns and foreign actor tokens rejected; stale versions and expiry fail',async()=>{await assert.rejects(preview({...pattern,weekdays:[1,1]}),/invalid_booking_pattern/);await assert.rejects(preview({...pattern,dateFrom:'infinity'}),/invalid_booking_pattern/);let p=await preview();await sql(`insert into zoi.workspace_members values('${ws}','${other}','admin');`);await assert.rejects(save(p,undefined,other),/booking_plan_unavailable/);await sql(`update zoi.booking_services set version=version+1 where id='${service.id}';`);await assert.rejects(save(p),/version_conflict/);p=await preview();await sql(`update zoi.booking_availability_plans set expires_at=now()-interval '1 minute' where id='${p.plan_id}';`);await assert.rejects(save(p),/booking_plan_expired/);});
 await t.test('two racing plans yield one atomic winner; retries keep exact receipt and audit',async()=>{const a=await preview(),b=await preview(),out=await Promise.allSettled([save(a),save(b,'70000000-0000-4000-8000-000000000002')]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.match(out.find(x=>x.status==='rejected').reason.message,/availability_overlap/);const winner=out[0].status==='fulfilled'?a:b,id=out[0].status==='fulfilled'?'70000000-0000-4000-8000-000000000001':'70000000-0000-4000-8000-000000000002';const receipt=out.find(x=>x.status==='fulfilled').value;assert.equal(receipt.slots.length,2);assert.deepEqual(await save(winner,id),receipt);assert.equal(await sql(`select count(*) from zoi.booking_slots where workspace_id='${ws}';`),'2');assert.equal((await call('booking_plan_history',`'${ws}'`)).batches.length,1);await assert.rejects(save(winner,'70000000-0000-4000-8000-000000000003'),/request_id_conflict/);});
 await t.test('conflict preview is explicit and save rollback leaves existing slots unchanged',async()=>{const p=await preview();assert.ok(p.slots.every(x=>x.conflicts.length===1));const before=await sql('select jsonb_agg(to_jsonb(s) order by id) from zoi.booking_slots s;');await assert.rejects(save(p,'70000000-0000-4000-8000-000000000004'),/availability_overlap/);assert.equal(await sql('select jsonb_agg(to_jsonb(s) order by id) from zoi.booking_slots s;'),before);
  const occupied=(await sql('select id from zoi.booking_slots order by starts_at limit 1;'));
  await sql(`insert into zoi.bookings(workspace_id,slot_id,profile_id,request_id,customer_name,customer_email,party_size) values('${ws}','${occupied}','${other}',gen_random_uuid(),'Local QA','local@example.invalid',1);`);
  await assert.rejects(save(p,'70000000-0000-4000-8000-000000000006'),/availability_overlap/);assert.equal(await sql(`select status||':'||version from zoi.bookings where slot_id='${occupied}';`),'confirmed:1');
  // First proposed slot is free, second overlaps: ensure earlier insert rolls back too.
  const partial=await preview({...pattern,opens:'07:45',closes:'10:15'});assert.equal(partial.slots[0].conflicts.length,0);assert.equal(partial.slots[1].conflicts.length,1);await assert.rejects(save(partial,'70000000-0000-4000-8000-000000000005'),/availability_overlap/);assert.equal(await sql('select count(*) from zoi.booking_slots;'),'2');
 });
 await t.test('private production fixture scripts refuse existing state and clean only their scoped rows',async()=>{
  const qa='053a5656-b19b-48a4-8721-65c4674f647c',qaAuth='2ba5b8e3-4fe9-4ec7-a3bf-7f616fcf07fd';
  await sql(`create table zoi.categories(id bigint primary key);insert into zoi.categories values(1);alter table zoi.listings add column primary_category_id bigint,add column city text,add column country text,add column address text,add column website text,add column slug text;insert into zoi.workspaces values('${qa}');insert into zoi.user_profiles values('21a04e78-e3b1-448e-8517-47aad25dd5da','${qaAuth}');insert into zoi.workspace_members values('${qa}','21a04e78-e3b1-448e-8517-47aad25dd5da','owner');`);
  const setup=file('../../ops/qa-booking-planner-setup.sql'),cleanup=file('../../ops/qa-booking-planner-cleanup.sql');
  const fixture=JSON.parse(await sql(setup));assert.equal(fixture.published,false);assert.equal(fixture.booking_enabled,false);await assert.rejects(sql(setup),/qa_existing_setup_do_not_modify/);
  const p=await call('booking_plan_preview',`'${qa}','${fixture.service_id}','${fixture.resource_id}',${quote(JSON.stringify(pattern))}`,qaAuth);await call('booking_plan_save',`'${qa}','${p.plan_id}',gen_random_uuid()`,qaAuth);
  assert.equal((await call('booking_catalog',`'${fixture.listing_id}',now(),now()+interval '7 days'`,qaAuth)).available,false);
  await sql(`update zoi.booking_settings set enabled=true where workspace_id='${qa}';`);await assert.rejects(sql(cleanup),/qa_fixture_changed_do_not_delete/);await sql(`update zoi.booking_settings set enabled=false where workspace_id='${qa}';`);
  const receipt=JSON.parse(await sql(cleanup));assert.equal(receipt.slots_deleted,2);assert.equal(receipt.plans_deleted,1);assert.equal(await sql(`select count(*) from zoi.listings where owner_workspace_id='${qa}';`),'0');assert.equal(await sql(`select count(*) from zoi.booking_slots where workspace_id='${ws}';`),'2');
 });

});
