import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{spawn}from'node:child_process';
const container=process.env.ZOI_TEST_POSTGRES_CONTAINER;let db='postgres';function sql(q){return new Promise((resolve,reject)=>{const p=spawn('docker',['exec','-i',container,'psql','-U','postgres','-d',db,'-X','-qAt','-v','ON_ERROR_STOP=1']);let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('close',n=>n?reject(Error(err)):resolve(out.trim().split('\n').at(-1)));p.stdin.end(q);});}
const owner='00000000-0000-4000-8000-000000000001',customer='00000000-0000-4000-8000-000000000002',viewer='00000000-0000-4000-8000-000000000003',ws='10000000-0000-4000-8000-000000000001',listing='20000000-0000-4000-8000-000000000001',quote=x=>"'"+String(x).replaceAll("'","''")+"'";
const as=(q,user=owner)=>sql(`set role authenticated;select set_config('request.jwt.claim.sub','${user}',false);${q}`),call=(name,args,user=owner)=>as(`select public.${name}(${args});`,user).then(JSON.parse),file=p=>readFileSync(new URL(p,import.meta.url),'utf8');
test('atomic rescheduling preserves confirmed inventory, scope, price review, audit and retries under real races',{skip:!container},async t=>{
 const name='booking_reschedule_'+process.pid;await sql('create database '+name);db=name;t.after(async()=>{db='postgres';await sql('drop database '+name);});
 await sql(file('../database/venue-fixture.sql').replace('create role anon;create role authenticated;',''));await sql(file('../../supabase/migrations/20260930001839_venue_plans_and_atomic_seat_holds.sql'));await sql("alter table zoi.listings add column name text default 'QA business';create table public.menu_items(id uuid,workspace_id uuid,name text,description text,price_cents integer,currency text,station text,is_available boolean,sort_order integer);");await sql(file('../../supabase/migrations/20260930004059_booking_services_resources_and_reservations.sql'));await sql(file('../../supabase/migrations/20260930021400_booking_atomic_rescheduling.sql'));
 await call('booking_settings_save',`'${ws}',0,'${listing}','Europe/Athens','EUR',true`);
 const service=(await call('booking_item_save',`'${ws}','service',null,0,'{"name":"Table booking","duration_minutes":60,"buffer_minutes":15,"price_cents":3500,"active":true}'`)).item;
 const otherService=(await call('booking_item_save',`'${ws}','service',null,0,'{"name":"Other service","duration_minutes":60,"buffer_minutes":0,"price_cents":0,"active":true}'`)).item;
 const resources=[];for(let i=0;i<4;i++)resources.push((await call('booking_item_save',`'${ws}','resource',null,0,'{"name":"Table ${i}","kind":"table","capacity":${i===3?1:4},"active":true}'`)).item);
 const day=n=>new Date(Date.now()+n*86400000).toISOString();
 const slot=async(r,d,svc=service)=>(await call('booking_slot_save',`'${ws}',null,0,'${svc.id}','${r.id}','${day(d)}',true`)).slot;
 const sourceA=await slot(resources[0],2),sourceB=await slot(resources[1],2),target=await slot(resources[2],3),small=await slot(resources[3],3),wrong=await slot(resources[0],4,otherService);
 const book=async(s,user=owner)=>(await call('booking_create',`'${s.id}',gen_random_uuid(),'Local QA','qa@example.invalid',2,1`,user)).booking;
 const a=await book(sourceA),b=await book(sourceB,customer);
 const opts=(booking,user=owner)=>call('booking_reschedule_options',`'${booking.id}','${day(1)}','${day(7)}'`,user);
 const move=(booking,destination,id,user=owner,version=1,price=destination.price_cents,slotVersion=destination.version)=>call('booking_reschedule',`'${booking.id}',${version===null?'null':version},'${destination.id}',${slotVersion===null?'null':slotVersion},'${id}',${price===null?'null':price},'${destination.currency}'`,user);
 const key=n=>'70000000-0000-4000-8000-'+String(n).padStart(12,'0');
 await t.test('only customer/owner/admin can view replacements and audit; wrong service and capacity omitted',async()=>{const result=await opts(a);assert.equal(result.original.id,sourceA.id);assert.deepEqual(result.slots.map(x=>x.id),[target.id]);await assert.rejects(opts(a,customer),/booking_not_owned/);await assert.rejects(opts(a,viewer),/booking_not_owned/);await assert.rejects(opts(a,'00000000-0000-4000-8000-000000000099'),/sign_in_required/);await assert.rejects(call('booking_reschedule_history',`'${a.id}'`,customer),/booking_not_owned/);await assert.rejects(as('select * from zoi.booking_reschedules;'),/permission denied/);await assert.rejects(sql(`set role anon;select public.booking_reschedule_history('${a.id}');`),/permission denied/);});
 await t.test('failed stale/price/capacity/scope attempts leave original confirmed and target unoccupied',async()=>{await assert.rejects(move(a,target,key(1),owner,null),/version_conflict/);await assert.rejects(move(a,target,key(2),owner,1,target.price_cents,null),/slot_version_conflict/);await assert.rejects(move(a,target,key(3),owner,1,null),/booking_price_changed/);await assert.rejects(move(a,small,key(4)),/party_exceeds_capacity/);await assert.rejects(move(a,wrong,key(5)),/invalid_reschedule_target/);await assert.rejects(move(a,target,key(6),customer),/booking_not_owned/);
  await sql(`insert into zoi.booking_slots(workspace_id,service_id,resource_id,starts_at,ends_at,blocked_until,service_name,resource_name,capacity,price_cents,currency) select '10000000-0000-4000-8000-000000000002',service_id,resource_id,starts_at+interval '1 day',ends_at+interval '1 day',blocked_until+interval '1 day',service_name,resource_name,capacity,price_cents,currency from zoi.booking_slots where id='${target.id}';`);const foreign=JSON.parse(await sql("select to_jsonb(s) from zoi.booking_slots s where workspace_id='10000000-0000-4000-8000-000000000002';"));await assert.rejects(move(a,foreign,key(7)),/invalid_reschedule_target/);
  assert.equal(await sql(`select slot_id::text||':'||version||':'||status from zoi.bookings where id='${a.id}';`),sourceA.id+':1:confirmed');assert.equal(await sql(`select count(*) from zoi.bookings where slot_id='${target.id}';`),'0');
 });
 let winner,winningBooking,winningUser,winningKey,losingBooking;
 await t.test('competing replacements have exactly one winner; loser retains original and retry returns same receipt',async()=>{const results=await Promise.allSettled([move(a,target,key(10)),move(b,target,key(11),customer)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.match(results.find(r=>r.status==='rejected').reason.message,/slot_unavailable/);const win=results[0].status==='fulfilled'?0:1;winner=results[win].value;winningBooking=win?b:a;losingBooking=win?a:b;winningUser=win?customer:owner;winningKey=key(win?11:10);assert.equal(winner.booking.id,winningBooking.id);assert.equal(winner.booking.version,2);assert.equal(winner.payment_collected,false);assert.deepEqual(await move(winningBooking,target,winningKey,winningUser),winner);assert.equal(await sql(`select slot_id from zoi.bookings where id='${losingBooking.id}';`),win?sourceA.id:sourceB.id);assert.equal(await sql('select count(*) from zoi.booking_reschedules;'),'1');await assert.rejects(move(winningBooking,small,winningKey,winningUser),/request_id_conflict/);});
 await t.test('old inventory is released, new inventory occupied, immutable audit retains price/time and same reference',async()=>{const catalog=await call('booking_catalog',`'${listing}','${day(1)}','${day(7)}'`);assert.ok(catalog.slots.some(s=>s.id===winner.from_slot_id));assert.ok(!catalog.slots.some(s=>s.id===target.id));const history=await call('booking_reschedule_history',`'${winningBooking.id}'`,winningUser);assert.equal(history.changes.length,1);const change=history.changes[0];assert.equal(change.before_version,1);assert.equal(change.after_version,2);assert.equal(change.old_slot.price_cents,3500);assert.equal(change.new_slot.id,target.id);assert.equal(change.actor_profile_id,winningUser);assert.ok(change.created_at);});
 await t.test('explicitly reviewed changed price persists without charging, with same-request simultaneous retry',async()=>{const next=await slot(resources[0],5);await sql(`update zoi.booking_slots set price_cents=4200,version=2 where id='${next.id}';`);next.price_cents=4200;next.version=2;await assert.rejects(move(winningBooking,next,key(20),winningUser,2,3500),/booking_price_changed/);const results=await Promise.all([move(winningBooking,next,key(21),winningUser,2),move(winningBooking,next,key(21),winningUser,2)]);assert.deepEqual(results[0],results[1]);assert.equal(results[0].booking.version,3);assert.equal(results[0].new_slot.price_cents,4200);assert.equal(results[0].payment_collected,false);assert.equal(await sql('select count(*) from zoi.booking_reschedules;'),'2');});
 await t.test('opposing resource moves use stable locks and an operator preserves customer ownership',async()=>{
  const source1=await slot(resources[0],7),source2=await slot(resources[1],7),destination1=await slot(resources[1],8),destination2=await slot(resources[0],8),one=await book(source1),two=await book(source2,customer);
  const results=await Promise.all([move(one,destination1,key(40)),move(two,destination2,key(41))]);assert.equal(results[0].booking.id,one.id);assert.equal(results[1].booking.id,two.id);assert.equal(results[1].booking.profile_id,customer);assert.equal(results[1].booking.customer_email,'qa@example.invalid');
 });
 await t.test('started and cancelled bookings cannot move; existing cancellation still works',async()=>{await call('booking_status_set',`'${winningBooking.id}',3,'cancelled'`,winningUser);const next=await slot(resources[1],6);await assert.rejects(move(winningBooking,next,key(30),winningUser,4),/booking_not_reschedulable/);await sql(`update zoi.booking_slots set starts_at=now()-interval '1 hour',ends_at=now()+interval '1 hour',blocked_until=now()+interval '2 hours' where id=(select slot_id from zoi.bookings where id='${losingBooking.id}');`);await assert.rejects(opts(losingBooking),/booking_not_reschedulable/);});
 await t.test('production rollback verification runs as anon/authenticated and leaves no fixture',async()=>{
  await sql(`create table zoi.categories(id bigint primary key);insert into zoi.categories values(1);alter table zoi.listings add column primary_category_id bigint,add column city text,add column country text,add column address text,add column website text,add column slug text;insert into zoi.workspaces values('053a5656-b19b-48a4-8721-65c4674f647c');insert into zoi.user_profiles values('21a04e78-e3b1-448e-8517-47aad25dd5da','2ba5b8e3-4fe9-4ec7-a3bf-7f616fcf07fd');insert into zoi.workspace_members values('053a5656-b19b-48a4-8721-65c4674f647c','21a04e78-e3b1-448e-8517-47aad25dd5da','owner');`);
  assert.equal(await sql(file('../../ops/qa-booking-reschedule-rollback.sql')),'t|0|0');
 });

});
