import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{spawn}from'node:child_process';
const container=process.env.ZOI_TEST_POSTGRES_CONTAINER;let db='postgres';function sql(q){return new Promise((resolve,reject)=>{const p=spawn('docker',['exec','-i',container,'psql','-U','postgres','-d',db,'-X','-qAt','-v','ON_ERROR_STOP=1']);let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('close',n=>n?reject(Error(err)):resolve(out.trim().split('\n').at(-1)));p.stdin.end(q);});}
const owner='00000000-0000-4000-8000-000000000001',customer='00000000-0000-4000-8000-000000000002',viewer='00000000-0000-4000-8000-000000000003',ws='10000000-0000-4000-8000-000000000001',listing='20000000-0000-4000-8000-000000000001',quote=x=>"'"+String(x).replaceAll("'","''")+"'";
const as=(q,user=owner)=>sql(`set role authenticated;select set_config('request.jwt.claim.sub','${user}',false);${q}`),call=(name,args,user=owner)=>as(`select public.${name}(${args});`,user).then(JSON.parse),file=p=>readFileSync(new URL(p,import.meta.url),'utf8');
test('connected event plans reserve every provider atomically with private context',{skip:!container},async t=>{
 const name='event_plan_'+process.pid;await sql('create database '+name);db=name;t.after(async()=>{db='postgres';await sql('drop database '+name);});
 await sql(file('../database/venue-fixture.sql').replace('create role anon;create role authenticated;',''));await sql(file('../../supabase/migrations/20260930001839_venue_plans_and_atomic_seat_holds.sql'));await sql("alter table zoi.listings add column name text default 'QA business';create table public.menu_items(id uuid,workspace_id uuid,name text,description text,price_cents integer,currency text,station text,is_available boolean,sort_order integer);");await sql(file('../../supabase/migrations/20260930004059_booking_services_resources_and_reservations.sql'));await sql(file('../../supabase/migrations/20260930021400_booking_atomic_rescheduling.sql'));
 await sql(file('../../supabase/migrations/20260930043125_connected_event_plans.sql'));

 const key=n=>'70000000-0000-4000-8000-'+String(n).padStart(12,'0'),ws2='10000000-0000-4000-8000-000000000002',listing2='20000000-0000-4000-8000-000000000002';
 await sql(`INSERT INTO zoi.workspace_members VALUES('${ws2}','${customer}','owner');INSERT INTO zoi.listings(id,owner_workspace_id,entity_type,publish_status,marketplace_status,name) VALUES('${listing2}','${ws2}','artist','published','','Band');`);
 await call('booking_settings_save',`'${ws}',0,'${listing}','Europe/Athens','EUR',true`);await call('booking_settings_save',`'${ws2}',0,'${listing2}','Europe/Athens','EUR',true`,customer);
 const item=(workspace,kind,data,user=owner,id=null,version=0)=>call('booking_item_save',`'${workspace}','${kind}',${id?quote(id):'null'},${version},${quote(JSON.stringify(data))}`,user).then(r=>r.item);
 const svcData={name:'Event service',duration_minutes:120,buffer_minutes:30,price_cents:10000,active:true};const svc=await item(ws,'service',svcData),svc2=await item(ws2,'service',svcData,customer);
 const hall=await item(ws,'resource',{name:'Hall',kind:'venue',capacity:250,active:true}),band=await item(ws2,'resource',{name:'Band',kind:'performer',capacity:1,active:true},customer);
 const day=n=>new Date(Date.now()+n*86400000).toISOString();const slot=async(w,s,r,d,user=owner)=>(await call('booking_slot_save',`'${w}',null,0,'${s.id}','${r.id}','${day(d)}',true`,user)).slot;
 const hallSlot=await slot(ws,svc,hall,2),bandSlot=await slot(ws2,svc2,band,2,customer);
 const selection=(s,l,kind,role)=>({slot_id:s.id,listing_id:l,workspace_id:s.workspace_id,slot_version:s.version,settings_version:1,party_size:kind==='venue'?200:1,price_cents:s.price_cents,currency:s.currency,resource_kind:kind,role,shared_context:'Only this provider may see '+role});
 const choices=[selection(hallSlot,listing,'venue','Reception hall'),selection(bandSlot,listing2,'performer','Live music')],data=(selections=choices)=>({title:'Private family gathering',kind:'wedding',timezone:'Europe/Athens',private_notes:'PRIVATE FAMILY NOTES',customer_name:'Local QA',customer_email:'qa@example.invalid',selections});
 const save=(value,user=viewer,request=key(1),plan=null,version=0)=>call('event_plan_save',`${plan?quote(plan):'null'},${version},'${request}',${quote(JSON.stringify(value))}`,user);
 const confirm=(plan,user=viewer,request=key(2),version=1)=>call('event_plan_confirm',`'${plan}',${version},'${request}'`,user);let p;
 await t.test('resource types obey unit semantics and catalog retains accepted slot pricing',async()=>{await assert.rejects(item(ws,'resource',{name:'Invalid staff',kind:'staff',capacity:2,active:true}),/booking_resources_capacity_semantics/);await assert.rejects(item(ws,'resource',{name:'Invalid table',kind:'table',capacity:51,active:true}),/booking_resources_capacity_semantics/);await assert.rejects(item(ws,'resource',{name:'Hall',kind:'equipment',capacity:250,active:true},owner,hall.id,1),/resource_kind_has_history/);await item(ws,'service',{...svcData,price_cents:25000},owner,svc.id,1);const catalog=await call('event_plan_catalog',`'${listing}','${day(1)}','${day(7)}'`,viewer);assert.equal(catalog.slots[0].price_cents,10000);assert.equal(catalog.slots[0].resource_kind,'venue');assert.equal(catalog.slots[0].capacity,250);});
 await t.test('private plan persists with exact retries and rejects other customer access',async()=>{const result=await save(data());p=result.plan;assert.deepEqual(await save(data()),result);await assert.rejects(call('event_plan_get',`'${p.id}'`,owner),/event_plan_not_owned/);await assert.rejects(sql(`set role anon;select * from zoi.event_plans;`),/permission denied/);await assert.rejects(save({...data(),title:'Changed'}),/request_id_conflict/);});
 await t.test('one conflicting provider makes whole confirmation fail without other reservations',async()=>{const held=(await call('booking_create',`'${bandSlot.id}','${key(10)}','Provider test','provider@example.invalid',1,1`,customer)).booking;await assert.rejects(confirm(p.id),/slot_unavailable/);assert.equal(await sql(`select count(*) from zoi.bookings where slot_id='${hallSlot.id}';`),'0');assert.equal(await sql(`select status from zoi.event_plans where id='${p.id}';`),'draft');await call('booking_status_set',`'${held.id}',1,'cancelled'`,customer);});
 await t.test('failure after first booking insertion still rolls back every selected booking',async()=>{await sql(`CREATE FUNCTION zoi.qa_reject_second() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.workspace_id='${ws2}' AND NEW.customer_name='Local QA' THEN RAISE EXCEPTION 'qa_forced_second_insert_failure';END IF;RETURN NEW;END$$;CREATE TRIGGER qa_reject_second BEFORE INSERT ON zoi.bookings FOR EACH ROW EXECUTE FUNCTION zoi.qa_reject_second();`);await assert.rejects(confirm(p.id),/qa_forced_second_insert_failure/);assert.equal(await sql(`select count(*) from zoi.bookings where slot_id='${hallSlot.id}';`),'0');assert.equal(await sql(`select count(*) from zoi.event_plan_bookings where plan_id='${p.id}';`),'0');await sql('DROP TRIGGER qa_reject_second ON zoi.bookings;DROP FUNCTION zoi.qa_reject_second();');});
 let receipt;
 await t.test('atomic confirmation creates both bookings; same request returns immutable receipt',async()=>{const results=await Promise.all([confirm(p.id),confirm(p.id)]);assert.deepEqual(results[0],results[1]);receipt=results[0];assert.equal(receipt.bookings.length,2);assert.equal(receipt.payment_collected,false);assert.equal(receipt.version,2);assert.equal(await sql(`select count(*) from zoi.event_plan_bookings where plan_id='${p.id}';`),'2');});
 await t.test('provider sees only their explicit context, no private notes or other vendors',async()=>{const a=receipt.bookings.find(x=>x.booking.workspace_id===ws),b=receipt.bookings.find(x=>x.booking.workspace_id===ws2);const context=await call('event_plan_provider_context',`'${a.booking.id}'`,owner);assert.equal(context.context.role,'Reception hall');assert.ok(!JSON.stringify(context).includes('PRIVATE'));assert.ok(!JSON.stringify(context).includes('Live music'));assert.ok(!JSON.stringify(context).includes(p.id));await assert.rejects(call('event_plan_provider_context',`'${b.booking.id}'`,owner),/workspace_permission_denied/);await assert.rejects(call('event_plan_provider_context',`'${a.booking.id}'`,viewer),/workspace_permission_denied/);});
 await t.test('current plan rereads ordinary cancellation rather than claiming old receipt current',async()=>{const b=receipt.bookings[0].booking;await call('booking_status_set',`'${b.id}',1,'cancelled'`,viewer);const current=await call('event_plan_get',`'${p.id}'`,viewer);assert.equal(current.bookings.find(x=>x.booking.id===b.id).booking.status,'cancelled');assert.deepEqual(await confirm(p.id),receipt);});
 await t.test('individual reschedule retains provider context and plan rereads new time',async()=>{const b=receipt.bookings.find(x=>x.booking.workspace_id===ws2).booking,target=await slot(ws2,svc2,band,3,customer);await call('booking_reschedule',`'${b.id}',1,'${target.id}',1,'${key(15)}',${target.price_cents},'${target.currency}'`,viewer);const current=await call('event_plan_get',`'${p.id}'`,viewer);assert.equal(current.bookings.find(x=>x.booking.id===b.id).slot.id,target.id);assert.equal((await call('event_plan_provider_context',`'${b.id}'`,customer)).context.role,'Live music');});
 await t.test('rescheduling cannot reinterpret a performer act as equipment units',async()=>{const resource=await item(ws2,'resource',{name:'Sound bundle',kind:'equipment',capacity:8,active:true},customer),target=await slot(ws2,svc2,resource,5,customer),b=receipt.bookings.find(x=>x.booking.workspace_id===ws2).booking;await assert.rejects(call('booking_reschedule',`'${b.id}',2,'${target.id}',1,'${key(16)}',${target.price_cents},'${target.currency}'`,viewer),/invalid_reschedule_target/);const options=await call('booking_reschedule_options',`'${b.id}','${day(1)}','${day(7)}'`,viewer);assert.ok(!options.slots.some(x=>x.id===target.id));});
 await t.test('opposing customers confirming reverse provider order cannot double-book or deadlock',async()=>{const a=await slot(ws,svc,hall,4),b=await slot(ws2,svc2,band,4,customer);const selections=[selection(a,listing,'venue','Hall'),selection(b,listing2,'performer','Band')];const first=(await save(data(selections),viewer,key(20))).plan,second=(await save(data([...selections].reverse()),owner,key(21))).plan;const outcomes=await Promise.allSettled([confirm(first.id,viewer,key(22)),confirm(second.id,owner,key(23))]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.match(outcomes.find(x=>x.status==='rejected').reason.message,/slot_unavailable/);assert.equal(await sql(`select count(*) from zoi.bookings where slot_id in('${a.id}','${b.id}') and status='confirmed';`),'2');});
 await t.test('changed reviewed price, ownership and settings reject with no partial state',async()=>{const a=await slot(ws,svc,hall,6),b=await slot(ws2,svc2,band,6,customer),v=data([selection(a,listing,'venue','Hall'),selection(b,listing2,'performer','Band')]);v.selections[1].price_cents++;const plan=(await save(v,viewer,key(30))).plan;await assert.rejects(confirm(plan.id,viewer,key(31)),/booking_price_changed/);assert.equal(await sql(`select count(*) from zoi.bookings where slot_id in('${a.id}','${b.id}');`),'0');v.selections[1].price_cents--;const next=(await save(v,viewer,key(32))).plan;await sql(`update zoi.listings set owner_workspace_id='${ws}' where id='${listing2}';`);await assert.rejects(confirm(next.id,viewer,key(33)),/booking_unavailable/);await sql(`update zoi.listings set owner_workspace_id='${ws2}' where id='${listing2}';update zoi.booking_settings set version=2 where workspace_id='${ws2}';`);await assert.rejects(confirm(next.id,viewer,key(34)),/booking_unavailable/);});
 await t.test('bounded search, duplicate selection and maximum eight slots are enforced server-side',async()=>{await assert.rejects(call('event_plan_catalog',`'${listing}','${day(1)}','${day(33)}'`,viewer),/invalid_date_range/);await assert.rejects(call('event_plan_catalog',`'${listing}','now','infinity'`,viewer),/invalid_date_range/);await assert.rejects(save(data([...choices,...choices]),viewer,key(40)),/duplicate_event_slot/);await assert.rejects(save(data(Array.from({length:9},(_,i)=>({...choices[0],slot_id:key(100+i)}))),viewer,key(41)),/invalid_event_plan/);});
 await t.test('exact production rollback proof leaves no fixture or booking settings',async()=>{await sql(`CREATE TABLE zoi.categories(id bigint PRIMARY KEY);INSERT INTO zoi.categories VALUES(1);ALTER TABLE zoi.listings ADD COLUMN primary_category_id bigint,ADD COLUMN city text,ADD COLUMN country text,ADD COLUMN address text,ADD COLUMN website text,ADD COLUMN slug text;INSERT INTO zoi.workspaces VALUES('053a5656-b19b-48a4-8721-65c4674f647c');INSERT INTO zoi.user_profiles VALUES('21a04e78-e3b1-448e-8517-47aad25dd5da','2ba5b8e3-4fe9-4ec7-a3bf-7f616fcf07fd');INSERT INTO zoi.workspace_members VALUES('053a5656-b19b-48a4-8721-65c4674f647c','21a04e78-e3b1-448e-8517-47aad25dd5da','owner');`);assert.equal(await sql(file('../../ops/qa-connected-event-plan-rollback.sql')),'t|0|0');});
});
