import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{spawn}from'node:child_process';
const container=process.env.ZOI_TEST_POSTGRES_CONTAINER;let db='postgres';
function sql(q){return new Promise((resolve,reject)=>{const c=spawn('docker',['exec','-i',container,'psql','-U','postgres','-d',db,'-X','-q','-At','-v','ON_ERROR_STOP=1']);let out='',err='';c.stdout.on('data',d=>out+=d);c.stderr.on('data',d=>err+=d);c.on('close',code=>code?reject(Error(err)):resolve(out.trim()));c.stdin.end(q);});}
const uuid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');const ws=uuid(1),owner=uuid(11),viewer=uuid(12),a=uuid(13),b=uuid(14);
const as=(id,q)=>`SET ROLE authenticated;SET request.jwt.claim.sub='${id}';${q}`;let program,shift;
const saveShift=(id=null,version=0,capacity=1,status='scheduled',start="now()+interval '2 days'",end="now()+interval '2 days 2 hours'")=>`SELECT public.org_shift_save('${ws}','${program}','Community kitchen','Parish hall',${start},${end},'Europe/Athens',${capacity},'${status}',${id?"'"+id+"'":'NULL'},${version});`;
test('organization volunteer scheduling against PostgreSQL',{skip:!container},async t=>{const name='org_test_'+process.pid;await sql('CREATE DATABASE '+name);db=name;t.after(async()=>{db='postgres';await sql('DROP DATABASE '+name);});await sql(`CREATE SCHEMA auth;CREATE SCHEMA zoi;GRANT USAGE ON SCHEMA auth,zoi TO authenticated,anon;CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid $$;CREATE TABLE zoi.workspaces(id uuid PRIMARY KEY,name text);CREATE TABLE zoi.user_profiles(id uuid PRIMARY KEY,auth_user_id uuid,display_name text);CREATE TABLE zoi.workspace_members(workspace_id uuid,profile_id uuid,role text);INSERT INTO zoi.workspaces VALUES('${ws}','QA Parish');INSERT INTO zoi.user_profiles SELECT id,id,'Fixture volunteer' FROM unnest(ARRAY['${owner}'::uuid,'${viewer}'::uuid,'${a}'::uuid,'${b}'::uuid])id;INSERT INTO zoi.workspace_members VALUES('${ws}','${owner}','owner'),('${ws}','${viewer}','viewer');`);await sql(readFileSync(new URL('../../supabase/migrations/20260930004540_organization_volunteer_scheduling.sql',import.meta.url),'utf8'));
await t.test('owner publishes program and future shift; viewer cannot manage',async()=>{const q=`SELECT public.org_program_save('${ws}','Community meals','Volunteer service','published');`;await assert.rejects(sql(as(viewer,q)),/not_authorized/);program=JSON.parse(await sql(as(owner,q))).program.id;shift=JSON.parse(await sql(as(owner,saveShift()))).shift;assert.equal(shift.version,1);});
await t.test('public schedule excludes roster and private workspace details',async()=>{const result=JSON.parse(await sql(`SET ROLE anon;SELECT public.org_opportunities('${ws}');`));assert.equal(result.shifts[0].available,1);assert.equal(JSON.stringify(result).includes('profile_id'),false);await assert.rejects(sql(`SET ROLE anon;SELECT * FROM zoi.org_registrations;`),/permission denied/);});
await t.test('concurrent final-place signups have exactly one winner and retry is idempotent',async()=>{const results=await Promise.allSettled([sql(as(a,`SELECT public.org_signup('${shift.id}');`)),sql(as(b,`SELECT public.org_signup('${shift.id}');`))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const winner=results[0].status==='fulfilled'?a:b;const r=JSON.parse(await sql(as(winner,`SELECT public.org_signup('${shift.id}');`)));assert.equal(r.registration.status,'active');assert.equal(await sql(`SELECT count(*) FROM zoi.org_registrations WHERE status='active';`),'1');});
await t.test('roster is restricted; active shifts cannot disappear or change times',async()=>{await assert.rejects(sql(as(viewer,`SELECT public.org_roster('${ws}','${shift.id}');`)),/not_authorized/);await assert.rejects(sql(as(a,`SELECT public.org_roster('${ws}','${shift.id}');`)),/not_authorized/);await assert.rejects(sql(as(owner,`SELECT public.org_program_save('${ws}','Meals','','draft','${program}',1);`)),/cancel_registered_shifts_first/);await assert.rejects(sql(as(owner,saveShift(shift.id,1,1))),/registered_shift_times_locked/);const result=JSON.parse(await sql(as(owner,`SELECT public.org_roster('${ws}','${shift.id}');`)));assert.equal(result.registrations.length,1);assert.ok(!JSON.stringify(result).includes('email'));});
await t.test('capacity reductions and cross-workspace writes are rejected',async()=>{await assert.rejects(sql(as(owner,saveShift(shift.id,1,0,'scheduled',"'"+shift.starts_at+"'","'"+shift.ends_at+"'"))),/capacity_below_registrations/);await assert.rejects(sql(as(owner,saveShift().replace(ws,uuid(999)))),/not_authorized/);await assert.rejects(sql(`SET ROLE anon;SELECT public.org_signup('${shift.id}');`),/permission denied/);});
await t.test('volunteer cancel retries are idempotent and free the place',async()=>{const profile=await sql(`SELECT profile_id FROM zoi.org_registrations WHERE shift_id='${shift.id}';`);const q=as(profile,`SELECT public.org_signup_cancel('${shift.id}');`);const first=await sql(q);assert.equal(await sql(q),first);assert.equal(JSON.parse(await sql(`SELECT public.org_opportunities('${ws}');`)).shifts[0].available,1);});
await t.test('overlapping commitments blocked; cancellation and audit persist',async()=>{await sql(as(a,`SELECT public.org_signup('${shift.id}');`));const other=JSON.parse(await sql(as(owner,saveShift(null,0,2)))).shift;await assert.rejects(sql(as(a,`SELECT public.org_signup('${other.id}');`)),/overlapping_shift/);const update=saveShift(shift.id,1,1,'cancelled',"'"+shift.starts_at+"'","'"+shift.ends_at+"'");const receipt=JSON.parse(await sql(as(owner,update)));assert.equal(receipt.shift.version,2);const ownHistory=JSON.parse(await sql(as(a,`SELECT public.org_opportunities('${ws}');`)));assert.equal(ownHistory.shifts.find(s=>s.id===shift.id).registration_status,'cancelled');const publicSchedule=JSON.parse(await sql(`SET ROLE anon;SELECT public.org_opportunities('${ws}');`));assert.equal(publicSchedule.shifts.some(s=>s.id===shift.id),false);assert.equal(await sql(`SELECT DISTINCT status FROM zoi.org_registrations WHERE shift_id='${shift.id}';`),'cancelled');assert.ok(Number(await sql('SELECT count(*) FROM zoi.org_audit;'))>=6);await assert.rejects(sql(as(owner,update)),/version_conflict/);});
await t.test('started shifts reject volunteer cancellation but operator can cancel',async()=>{const last=JSON.parse(await sql(as(owner,saveShift(null,0,2,"scheduled","now()+interval '5 days'","now()+interval '5 days 2 hours'")))).shift;await sql(as(b,`SELECT public.org_signup('${last.id}');`));await sql(`UPDATE zoi.org_shifts SET starts_at=now()-interval '1 minute',ends_at=now()+interval '1 hour' WHERE id='${last.id}';`);await assert.rejects(sql(as(b,`SELECT public.org_signup_cancel('${last.id}');`)),/started_shift_contact_organizer/);const row=JSON.parse(await sql(`SELECT row_to_json(s) FROM zoi.org_shifts s WHERE id='${last.id}';`));const cancelled=JSON.parse(await sql(as(owner,saveShift(row.id,1,2,'cancelled',"'"+row.starts_at+"'","'"+row.ends_at+"'"))));assert.equal(cancelled.shift.status,'cancelled');});
await t.test('null versions cannot bypass optimistic concurrency and nonfinite/past times are rejected',async()=>{
 await assert.rejects(sql(as(owner,`SELECT public.org_program_save('${ws}','Title','','published','${program}',NULL);`)),/version_conflict/);
 await assert.rejects(sql(as(owner,`SELECT public.org_program_save('${ws}','Title','','published',NULL,NULL);`)),/version_conflict/);
 await assert.rejects(sql(as(owner,saveShift(null,null))),/version_conflict/);
 await assert.rejects(sql(as(owner,saveShift(null,0,1,'scheduled',"'infinity'","'infinity'"))),/invalid_shift_times/);
 const created=JSON.parse(await sql(as(owner,saveShift(null,0,1,'scheduled',"now()+interval '8 days'","now()+interval '8 days 1 hour'")))).shift;
 await assert.rejects(sql(as(owner,saveShift(created.id,null,1,'scheduled',"'"+created.starts_at+"'","'"+created.ends_at+"'"))),/version_conflict/);
 await assert.rejects(sql(as(owner,saveShift(created.id,1,1,'scheduled',"now()-interval '1 hour'","now()+interval '1 hour'"))),/start_must_be_future/);
});
await t.test('former registrants see only public snapshots after a program becomes private',async()=>{
 const created=JSON.parse(await sql(as(owner,saveShift(null,0,1,'scheduled',"now()+interval '7 days'","now()+interval '7 days 1 hour'")))).shift;
 await sql(as(a,`SELECT public.org_signup('${created.id}');SELECT public.org_signup_cancel('${created.id}');`));
 await sql(as(owner,`SELECT public.org_program_save('${ws}','PRIVATE TITLE','PRIVATE DESCRIPTION','draft','${program}',1);`));
 await sql(as(owner,saveShift(created.id,1,1,'scheduled',"'"+created.starts_at+"'","'"+created.ends_at+"'").replace('Community kitchen','PRIVATE SHIFT').replace('Parish hall','PRIVATE LOCATION')));
 const result=JSON.parse(await sql(as(a,`SELECT public.org_opportunities('${ws}');`)));assert.ok(!JSON.stringify(result).includes('PRIVATE'));
 const history=result.shifts.find(s=>s.id===created.id);assert.equal(history.title,'Community kitchen');assert.equal(history.location,'Parish hall');assert.equal(history.registration_status,'cancelled');assert.equal(history.unavailable,true);
 const anon=JSON.parse(await sql(`SET ROLE anon;SELECT public.org_opportunities('${ws}');`));assert.equal(anon.shifts.length,0);assert.equal(anon.programs.length,0);
});

});
