import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{spawn}from'node:child_process';
const container=process.env.ZOI_TEST_POSTGRES_CONTAINER;let db='postgres';
function sql(q){return new Promise((resolve,reject)=>{const c=spawn('docker',['exec','-i',container,'psql','-U','postgres','-d',db,'-X','-q','-At','-v','ON_ERROR_STOP=1']);let out='',err='';c.stdout.on('data',d=>out+=d);c.stderr.on('data',d=>err+=d);c.on('close',code=>code?reject(Error(err)):resolve(out.trim()));c.stdin.end(q);});}

const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');const ws=id(1),owner=id(11),viewer=id(12),guest=id(13),listing=id(20);const as=(actor,q)=>`SET ROLE authenticated;SET request.jwt.claim.sub='${actor}';${q}`;const json=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
test('organization calendar actual PostgreSQL journey',{skip:!container},async t=>{const name='calendar_test_'+process.pid;await sql('CREATE DATABASE '+name);db=name;t.after(async()=>{db='postgres';await sql('DROP DATABASE '+name);});
await sql(`CREATE SCHEMA auth;CREATE SCHEMA zoi;GRANT USAGE ON SCHEMA auth,zoi TO authenticated,anon;CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid $$;CREATE TABLE zoi.workspaces(id uuid PRIMARY KEY,name text);CREATE TABLE zoi.user_profiles(id uuid PRIMARY KEY,auth_user_id uuid,display_name text);CREATE TABLE zoi.workspace_members(workspace_id uuid,profile_id uuid,role text);CREATE TABLE zoi.listings(id uuid PRIMARY KEY,owner_workspace_id uuid,name text,publish_status text,marketplace_status text);INSERT INTO zoi.workspaces VALUES('${ws}','QA Parish');INSERT INTO zoi.user_profiles SELECT id,id,'Fixture' FROM unnest(ARRAY['${owner}'::uuid,'${viewer}'::uuid,'${guest}'::uuid])id;INSERT INTO zoi.workspace_members VALUES('${ws}','${owner}','owner'),('${ws}','${viewer}','viewer');INSERT INTO zoi.listings VALUES('${listing}','${ws}','QA Parish','published','visible');`);
await sql(readFileSync(new URL('../../supabase/migrations/20260930004540_organization_volunteer_scheduling.sql',import.meta.url),'utf8'));
const planner=readFileSync(new URL('../../supabase/migrations/20260930013518_booking_recurring_availability.sql',import.meta.url),'utf8');await sql(planner.slice(planner.indexOf('create function zoi.booking_wall_instant'),planner.indexOf('create function public.booking_plan_preview')));
await sql(readFileSync(new URL('../../supabase/migrations/20260930015911_parish_service_calendar.sql',import.meta.url),'utf8'));
const program=JSON.parse(await sql(as(owner,`SELECT public.org_program_save('${ws}','Hospitality','Welcome team','published');`))).program;
const date=await sql("SELECT (current_date+14)::text;");const weekday=Number(await sql("SELECT extract(dow from current_date+14);"));
const data={listing_id:listing,kind:'rehearsal',title:'Weekly dance rehearsal',description:'Public details',location:'Hall',timezone:'Europe/Athens',status:'published',program_id:program.id,program_version:program.version,volunteer_title:'Welcome team',capacity:2,pattern:{dateFrom:date,dateTo:date,weekdays:[weekday],opens:'10:00',closes:'11:00'}};
const preview=()=>`SELECT public.org_calendar_preview('${ws}',${json(data)});`;let expected,receipt;
await t.test('viewer and outsider cannot preview; anonymous cannot read private records',async()=>{await assert.rejects(sql(as(viewer,preview())),/not_authorized/);await assert.rejects(sql(as(guest,preview())),/not_authorized/);await assert.rejects(sql('SET ROLE anon;SELECT * FROM zoi.org_calendar_events;'),/permission denied/);expected=JSON.parse(await sql(as(owner,preview()))).occurrences.map(({starts_at,ends_at})=>({starts_at,ends_at}));});
const save=(request=id(31),values=data,times=expected)=>`SELECT public.org_calendar_batch_save('${ws}','${request}',${json(values)},${json(times)});`;
await t.test('tampered preview is rejected without records; atomic creation and retry',async()=>{await assert.rejects(sql(as(owner,save(id(30),data,[{...expected[0],ends_at:expected[0].starts_at}]))),/calendar_preview_changed/);assert.equal(await sql('SELECT count(*) FROM zoi.org_calendar_events;'),'0');receipt=JSON.parse(await sql(as(owner,save())));assert.equal(receipt.events.length,1);assert.equal(receipt.events[0].version,2);assert.ok(receipt.events[0].shift_id);assert.deepEqual(JSON.parse(await sql(as(owner,save()))),receipt);await assert.rejects(sql(as(owner,save(id(31),{...data,title:'Changed'}))),/request_id_conflict/);await assert.rejects(sql(as(owner,save(id(32)))),/calendar_occurrence_exists/);});
const publicRead=()=>`SET ROLE anon;SELECT public.org_calendar_public('${listing}',now(),now()+interval '90 days');`;
await t.test('published dates expose only approved data and usable volunteer link',async()=>{const result=JSON.parse(await sql(publicRead()));assert.equal(result.events[0].volunteer_shift_id,receipt.events[0].shift_id);assert.ok(!JSON.stringify(result).includes('actor_profile_id'));await sql(as(guest,`SELECT public.org_signup('${receipt.events[0].shift_id}');`));});
await t.test('cancellation atomically cancels volunteer commitments, null versions denied',async()=>{const e=receipt.events[0];await assert.rejects(sql(as(owner,`SELECT public.org_calendar_event_set('${ws}','${e.id}',NULL,'cancelled');`)),/version_conflict/);const q=`SELECT public.org_calendar_event_set('${ws}','${e.id}',2,'cancelled');`;const result=JSON.parse(await sql(as(owner,q)));assert.equal(result.event.version,3);assert.deepEqual(JSON.parse(await sql(as(owner,q))),result);assert.equal(await sql(`SELECT status FROM zoi.org_registrations WHERE shift_id='${e.shift_id}';`),'cancelled');const result2=JSON.parse(await sql(publicRead()));assert.equal(result2.events[0].status,'cancelled');assert.equal(result2.events[0].volunteer_shift_id,null);});
await t.test('draft privacy, hidden listing and ownership transfer suppress public calendar',async()=>{await sql(as(owner,save(id(33),{...data,title:'Private draft',status:'draft'})));assert.equal(JSON.parse(await sql(publicRead())).events.length,1);await sql(`UPDATE zoi.listings SET marketplace_status='hidden';`);assert.equal(JSON.parse(await sql(publicRead())).available,false);await sql(`UPDATE zoi.listings SET marketplace_status='visible',owner_workspace_id='${id(99)}';`);assert.equal(JSON.parse(await sql(publicRead())).events.length,0);await sql(`UPDATE zoi.listings SET owner_workspace_id='${ws}';`);});
await t.test('concurrent duplicate saves create exactly one event; concurrent cancellation is idempotent',async()=>{const changed={...data,title:'Race rehearsal',program_id:null,status:'draft'};const results=await Promise.allSettled([sql(as(owner,save(id(40),changed))),sql(as(owner,save(id(41),changed)))]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);const e=JSON.parse(results.find(x=>x.status==='fulfilled').value).events[0];const q=as(owner,`SELECT public.org_calendar_event_set('${ws}','${e.id}',1,'cancelled');`);const cancelled=await Promise.all([sql(q),sql(q)]);assert.equal(cancelled[0],cancelled[1]);assert.equal(await sql(`SELECT count(*) FROM zoi.org_audit WHERE entity_id='${e.id}' AND action='calendar_cancelled';`),'1');});
await t.test('DST missing and repeated local times rejected by actual shared conversion',async()=>{await assert.rejects(sql("SELECT zoi.booking_wall_instant('2027-03-28 03:30','Europe/Athens');"),/booking_dst_wall_time/);await assert.rejects(sql("SELECT zoi.booking_wall_instant('2026-10-25 03:30','Europe/Athens');"),/booking_dst_wall_time/);});
});
