import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{spawn}from'node:child_process';const container=process.env.ZOI_TEST_POSTGRES_CONTAINER;let database='postgres';
function sql(q){return new Promise((resolve,reject)=>{const c=spawn('docker',['exec','-i',container,'psql','-U','postgres','-d',database,'-X','-q','-At','-v','ON_ERROR_STOP=1']);let out='',err='';c.stdout.on('data',d=>out+=d);c.stderr.on('data',d=>err+=d);c.on('close',code=>code?reject(Error(err)):resolve(out.trim()));c.stdin.end(q);});}
const ws='00000000-0000-0000-0000-000000000001',user='00000000-0000-0000-0000-000000000011';
test('social stats requires workspace membership and preserves authorized counts',{skip:!container},async t=>{const name='social_stats_'+process.pid;await sql('CREATE DATABASE '+name);database=name;t.after(async()=>{database='postgres';await sql('DROP DATABASE '+name);});await sql(`CREATE SCHEMA auth;CREATE SCHEMA zoi;CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid $$;CREATE FUNCTION zoi.is_ws_member(p_workspace uuid) RETURNS boolean LANGUAGE sql AS $$ SELECT p_workspace='${ws}'::uuid AND auth.uid()='${user}'::uuid $$;CREATE TABLE zoi.social_posts(workspace_id uuid,status text);CREATE TABLE zoi.social_channels(workspace_id uuid,connected boolean);INSERT INTO zoi.social_posts VALUES('${ws}','draft'),('${ws}','scheduled'),('${ws}','published');INSERT INTO zoi.social_channels VALUES('${ws}',true),('${ws}',false),('${ws}',null);`);await sql(readFileSync(new URL('../../supabase/migrations/20260930005338_social_stats_workspace_authorization.sql',import.meta.url),'utf8'));
await assert.rejects(sql(`SET ROLE anon;SELECT public.social_stats('${ws}');`),/permission denied/);
await assert.rejects(sql(`SET ROLE authenticated;SELECT public.social_stats('${ws}');`),/not_authorized/);
await assert.rejects(sql(`SET ROLE authenticated;SET request.jwt.claim.sub='00000000-0000-0000-0000-000000000099';SELECT public.social_stats('${ws}');`),/not_authorized/);
const result=JSON.parse(await sql(`SET ROLE authenticated;SET request.jwt.claim.sub='${user}';SELECT public.social_stats('${ws}');`));assert.deepEqual(result,{drafts:1,channels:1,published:1,scheduled:1,channels_pending:2});
});
