import{createLayout,seatRows,validateLayout}from'../../assets/tickets/venue-model.mjs';
import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{spawn}from'node:child_process';
const container=process.env.ZOI_TEST_POSTGRES_CONTAINER;let db='postgres';function sql(q){return new Promise((resolve,reject)=>{const p=spawn('docker',['exec','-i',container,'psql','-U','postgres','-d',db,'-X','-qAt','-v','ON_ERROR_STOP=1']);let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('close',n=>n?reject(Error(err)):resolve(out.trim().split('\n').at(-1)));p.stdin.end(q);});}
const owner='00000000-0000-4000-8000-000000000001',customer='00000000-0000-4000-8000-000000000002',viewer='00000000-0000-4000-8000-000000000003',ws='10000000-0000-4000-8000-000000000001',listing='20000000-0000-4000-8000-000000000001',quote=x=>"'"+String(x).replaceAll("'","''")+"'";
const as=(q,user=owner)=>sql(`set role authenticated;select set_config('request.jwt.claim.sub','${user}',false);${q}`),call=(name,args,user=owner)=>as(`select public.${name}(${args});`,user).then(JSON.parse),file=p=>readFileSync(new URL(p,import.meta.url),'utf8');

test('venue measured references persist safely through revisions and publication',{skip:!container},async t=>{const name='venue_reference_'+process.pid;await sql('create database '+name);db=name;t.after(async()=>{db='postgres';await sql('drop database '+name);});await sql(file('../database/venue-fixture.sql').replace('create role anon;create role authenticated;',''));await sql(file('../../supabase/migrations/20260930001839_venue_plans_and_atomic_seat_holds.sql'));await sql(file('../../supabase/migrations/20260930043130_venue_reference_calibration_and_views.sql'));
const image={url:'https://images.example.com/venue.jpg',caption:'Organizer view from this seat'},reference={...image,pixel_width:1000,pixel_height:750,calibration:{x1:0,y1:0,x2:1000,y2:0,distance_m:20}},raw=seatRows(createLayout());raw.reference=reference;raw.sections=[{id:'left',label:'Left section',view_image:image}];raw.objects[0].section_id='left';raw.objects[1].view_image=image;const layout=validateLayout(raw),save=(l,plan=null,revision=0,user=owner)=>call('venue_plan_save',`'${ws}',${plan?quote(plan):'null'},${revision},${quote(JSON.stringify(l))}`,user);let result;
await t.test('organizer calibration, section and seat photos survive SQL normalization exactly',async()=>{result=await save(layout);assert.deepEqual(result.layout,layout);assert.equal((await call('venue_reference_capabilities',`'${ws}'`)).version,1);await assert.rejects(save(layout,null,0,viewer),/workspace_permission_denied/);await assert.rejects(call('venue_plan_get',`'${ws}','${result.plan_id}'`,customer),/workspace_permission_denied/);});
await t.test('unsafe images and malformed geometry are rejected before persistence',async()=>{for(const url of['javascript:alert(1)','http://example.com/a.jpg','https://127.0.0.1/a.jpg','https://example.local/a.jpg','https://example.com/a.svg','https://u:p@example.com/a.jpg','https://example.com/a.jpg?x="y','https://example.com/a.jpg?x=%0a'])await assert.rejects(save({...layout,reference:{...reference,url}}),/unsafe_venue_image_url/);await assert.rejects(save({...layout,reference:{...reference,calibration:{...reference.calibration,x2:0}}}),/invalid_reference_calibration/);await assert.rejects(save({...layout,reference:{...reference,calibration:{...reference.calibration,distance_m:80}}}),/reference_outside_room/);await assert.rejects(save({...layout,sections:[]}),/venue_section_not_found/);assert.equal(await sql('select count(*) from zoi.venue_plans;'),'1');});
await t.test('revision checks and immutable published geometry preserve documentary references',async()=>{await sql('update zoi.seating_runtime set enabled=true;');await call('venue_plan_publish',`'${ws}','${result.plan_id}',1,'${listing}',1`);const published=await call('tickets_seat_map',`'${listing}'`);assert.deepEqual(published.layout,layout);const edited={...layout,reference:{...reference,caption:'Updated organizer reference'}};const saved=await save(edited,result.plan_id,1);assert.equal(saved.revision,2);assert.equal((await call('tickets_seat_map',`'${listing}'`)).layout.reference.caption,reference.caption);await assert.rejects(save(edited,result.plan_id,1),/revision_conflict/);});
await t.test('production rollback script preserves zero fixture plans',async()=>{await sql(`INSERT INTO zoi.workspaces VALUES('053a5656-b19b-48a4-8721-65c4674f647c');INSERT INTO zoi.user_profiles VALUES('21a04e78-e3b1-448e-8517-47aad25dd5da','2ba5b8e3-4fe9-4ec7-a3bf-7f616fcf07fd');INSERT INTO zoi.workspace_members VALUES('053a5656-b19b-48a4-8721-65c4674f647c','21a04e78-e3b1-448e-8517-47aad25dd5da','owner');`);assert.equal(await sql(file('../../ops/qa-venue-reference-rollback.sql')),'t|0');});
});
