const{chromium}=require('playwright-core'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{createHash}=require('node:crypto'),{execFileSync}=require('node:child_process');
const out=process.env.EVIDENCE_DIR,origin=process.env.PRODUCTION_ORIGIN||'https://www.zoi.city',commit=process.env.RELEASE_COMMIT,deployment=process.env.DEPLOYMENT_ID,repo=process.env.RELEASE_REPO||path.resolve(__dirname,'../../..');
if(!out||!commit||!/^[0-9a-f]{40}$/.test(commit)||!deployment||!['https://www.zoi.city','https://zoi.city'].includes(origin))throw Error('Exact RELEASE_COMMIT, DEPLOYMENT_ID, EVIDENCE_DIR and approved production origin required');
const sha=b=>createHash('sha256').update(b).digest('hex');
(async()=>{await fs.mkdir(out,{recursive:true});const assets=[];for(const [file,url] of [['explore/index.html',origin+'/explore/'],['assets/discovery/autocomplete.mjs',origin+'/assets/discovery/autocomplete.mjs'],['assets/discovery/city-picker.mjs',origin+'/assets/discovery/city-picker.mjs']]){const expected=execFileSync('git',['show',commit+':'+file],{cwd:repo,maxBuffer:16*1024*1024}),response=await fetch(url,{headers:{'Cache-Control':'no-cache'}}),actual=Buffer.from(await response.arrayBuffer()),entry={file,url,status:response.status,expected_sha256:sha(expected),served_sha256:sha(actual)};assets.push(entry);await fs.writeFile(path.join(out,'asset-binding.json'),JSON.stringify({release_commit:commit,deployment_id:deployment,assets},null,2)+'\n');assert.equal(entry.status,200);assert.equal(entry.served_sha256,entry.expected_sha256);}const expectedHtml=execFileSync('git',['show',commit+':explore/index.html'],{cwd:repo,encoding:'utf8'}),versions={};for(const name of ['autocomplete','city-picker']){const match=expectedHtml.match(new RegExp('/assets/discovery/'+name+'[.]mjs[?]v=([A-Za-z0-9_-]+)'));assert(match,'Release must version '+name);versions[name]=match[0];}const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const report={release_commit:commit,deployment_id:deployment,origin,controlled_rpc:false,local_server:false,assets,expected_versioned_modules:versions,source:'actual anonymous production readers',canonical:'actual ordinary production pages',cases:[]};try{
for(const width of[390,1440])for(const item of[{q:'OPA',name:'OPA Productions',more:true},{q:'SIGNAT',name:'Signature Productions'},{q:'Yamas',name:'Yamas Greek Restaurant'},{q:'Yamas',name:'Yamas Greek Restaurant',country:'Kenya',city:'Nairobi'},{q:'SIGNAT',name:'Signature Productions',country:'Canada',city:'North York'},{q:'Yamas',name:'Yamas Greek Restaurant',country:'Kenya',city:'Nairobi',initial:true},{q:'SIGNAT',name:'Signature Productions',country:'Canada',city:'North York',initial:true},{q:'zzzxqvNoGreekListing987654',empty:true}]){
 const context=await browser.newContext({viewport:{width,height:1000},isMobile:width===390,hasTouch:width===390,serviceWorkers:'block'}),page=await context.newPage(),errors=[],calls=[],blocked=[],moduleRequests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/assets/discovery/autocomplete.mjs')||r.url().includes('/assets/discovery/city-picker.mjs'))moduleRequests.push(r.url());if(r.url().includes('/rest/v1/rpc/'))calls.push({fn:r.url().split('/').pop(),args:r.postDataJSON()});});await page.route('**/*',r=>{const fn=new URL(r.request().url()).pathname.split('/').pop();if(r.request().url().includes('/rest/v1/rpc/')&&/(save|write|update|send|create|delete|reserve|publish|checkout|claim|commit|insert|configure)/i.test(fn)){blocked.push(fn);return r.abort();}return r.continue();});const result={width,...item,calls,errors,blocked,moduleRequests};report.cases.push(result);
 try{await page.goto(origin+'/explore/'+(item.initial?'?city='+encodeURIComponent(item.city)+'&country='+encodeURIComponent(item.country):''));await page.waitForFunction(()=>document.querySelector('#q')?.getAttribute('role')==='combobox');
 if(item.initial){assert.equal(await page.locator('#city-sel').inputValue(),item.city);assert.equal(await page.locator('#country-sel').inputValue(),item.country);}
 if(item.city&&!item.initial){await page.getByRole('button',{name:'Find a city',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('combobox',{name:'Country for city search'}).locator('option[value="'+item.country+'"]').waitFor({state:'attached'});await dialog.getByRole('combobox',{name:'Country for city search'}).selectOption(item.country);const city=dialog.getByRole('combobox',{name:'Find a city'});await city.waitFor();await page.waitForFunction(()=>!document.querySelector('[data-query]').disabled);await city.fill(item.city);await dialog.getByRole('option',{name:item.city,exact:true}).waitFor();await page.screenshot({path:path.join(out,`${width}-${item.city}-picker.png`)});if(width===390)await dialog.getByRole('option',{name:item.city,exact:true}).tap();else{await city.press('ArrowDown');await city.press('Enter');}await dialog.waitFor({state:'hidden'});assert.equal(await page.locator('#city-sel').inputValue(),item.city);assert.equal(new URL(page.url()).searchParams.get('city'),item.city);assert.equal(new URL(page.url()).searchParams.get('country'),item.country);}
 const input=page.locator('#q'),box=page.locator('.discovery-suggestions').first();const started=Date.now();await input.fill(item.q);await box.waitFor({state:'visible'});await page.waitForFunction(()=>{const x=document.querySelector('.discovery-suggestions');return x&&!x.hidden&&!x.textContent.includes('Finding matches');},{},{timeout:15000});result.suggestion_ms=Date.now()-started;assert(!(await box.innerText()).includes('Suggestions could not load'));
 if(item.empty){assert.match(await box.innerText(),/No matching pages/);}else{if(item.more){assert.equal(await box.getByRole('option').count(),6);assert(await box.getByRole('button',{name:/Show more matches/}).isVisible());}
 if(width===390){for(let i=0;i<6&&!await box.getByRole('option').filter({has:page.locator('strong',{hasText:new RegExp('^'+item.name+'$')})}).count();i++)await box.getByRole('button',{name:/Show more matches/}).tap();const target=box.getByRole('option').filter({has:page.locator('strong',{hasText:new RegExp('^'+item.name+'$')})});assert.equal(await target.count(),1);await target.scrollIntoViewIfNeeded();if(item.more)await page.screenshot({path:path.join(out,width+'-OPA-expanded.png')});await target.tap();}else{let found=false;for(let i=0;i<32;i++){await input.press('ArrowDown');const active=await input.getAttribute('aria-activedescendant');const text=await page.locator('#'+active+' strong').innerText();if(text===item.name){found=true;break;}}assert(found);if(item.more)await page.screenshot({path:path.join(out,width+'-OPA-expanded.png')});await input.press('Enter');}
 await page.waitForURL(u=>u.hostname==='www.zoi.city'&&u.pathname.startsWith('/business/'),{timeout:20000});await page.getByRole('heading',{level:1}).waitFor();assert((await page.locator('body').innerText()).toLowerCase().includes(item.name.toLowerCase()));result.canonical=page.url();}
 for(const name of ['autocomplete','city-picker'])assert(moduleRequests.some(u=>new URL(u).pathname+new URL(u).search===versions[name]),'Actual page requested released '+name+' import');assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));result.passed=true;await page.screenshot({path:path.join(out,`${width}-${item.q}-${item.city||'global'}${item.initial?'-initial':''}-result.png`)});
 }catch(e){result.passed=false;result.failure=e.message;await page.screenshot({path:path.join(out,`${width}-${item.q}-${item.city||'global'}-failure.png`)}).catch(()=>{});}finally{await context.close();}console.log(JSON.stringify({width,q:item.q,city:item.city,passed:result.passed,ms:result.suggestion_ms,failure:result.failure}));
}
}finally{await browser.close();report.passed=report.cases.every(x=>x.passed)&&report.cases.length===16;await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');if(!report.passed)process.exitCode=1;}})().catch(e=>{console.error(e);process.exitCode=1;});
