import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from './Auth';
import { businessPayload, editableBusinesses } from './businessEdit';
function Action({label,run,disabled=false}:{label:string;run:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={run} style={[s.action,disabled&&{opacity:.5}]}><Text style={s.link}>{label}</Text></Pressable>;}
export function BusinessEditor(){const {session,workspaceId}=useAuth();return session&&workspaceId?<Editor key={session.user.id+':'+workspaceId}/>:null;}
function Editor(){const {client,session,workspaceId}=useAuth();const userId=session!.user.id;const [open,setOpen]=useState(false),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState(''),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);const alive=useRef(true),working=useRef(false);const current=()=>alive.current&&client.session?.user.id===userId;useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
const run=async(work:()=>Promise<void>)=>{if(working.current)return;working.current=true;setBusy(true);setError('');try{await work();}catch(e){if(current())setError(e instanceof Error?e.message:'The request could not be confirmed.');}finally{working.current=false;if(current())setBusy(false);}};
const load=()=>run(async()=>{const value=await client.rpc('bizpage_status',{p_workspace:workspaceId});if(!value||!Array.isArray(value.owned)||!Array.isArray(value.claims))throw new Error('Business ownership could not be verified.');if(current()){setRows(editableBusinesses(value));setLoaded(true);}});
const choose=(id:string)=>run(async()=>{const value=await client.rpc('bizpage_get',{p_workspace:workspaceId,p_listing:id});if(!value||value.id!==id)throw new Error('This business profile could not be verified.');if(current()){setSelected(id);setDraft({...value,social_links:value.social_links||{}});setNotice('');}});
const update=(key:string,value:any)=>{setDraft((previous:any)=>({...previous,[key]:value}));setNotice('Unsaved changes');};
const save=()=>run(async()=>{const payload=businessPayload(workspaceId,selected,draft);const result=await client.rpc('bizpage_save',payload);if(result!==true)throw new Error('The business update was not confirmed. Your draft is preserved.');if(current())setNotice('Your business details are saved.');});
const socials=draft?.social_links&&typeof draft.social_links==='object'&&!Array.isArray(draft.social_links)?draft.social_links:null;
return <View style={s.panel}><Text style={s.title}>Your business profile</Text><Text style={s.body}>Update the details on businesses your workspace owns or has an approved claim to.</Text><Action label={open?'Hide editor':'Manage business details'} disabled={busy} run={()=>{setOpen(v=>!v);if(!open&&!loaded)load();}}/>{open?<>{busy?<ActivityIndicator/>:null}{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{notice?<Text accessibilityLiveRegion="polite" style={s.body}>{notice}</Text>:null}{!loaded?<Action label="Load businesses" disabled={busy} run={load}/>:!rows.length?<Text style={s.body}>No owned or approved business claims were returned for this workspace. Pending claims do not grant editing access.</Text>:null}{rows.map(row=><Action key={row.id} label={(selected===row.id?'● ':'')+row.name} disabled={busy||!!draft} run={()=>choose(row.id)}/>)}{draft?<><Text style={s.title}>{draft.name}</Text>{[['description','Description'],['phone','Phone'],['email','Contact email'],['website','Website'],['hours','Opening hours'],['price_range','Price range'],['photo_url','Photo URL']].map(([key,label])=><View key={key} style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={'Business '+label} value={typeof draft[key]==='string'?draft[key]:''} onChangeText={value=>update(key,value)} editable={!busy} multiline={key==='description'||key==='hours'} style={s.input} autoCapitalize={['website','email','photo_url'].includes(key)?'none':'sentences'}/></View>)}<Text style={s.label}>Social links</Text>{socials?[...new Set([...Object.keys(socials),'instagram','facebook','tiktok','youtube','linkedin'])].map(platform=><View key={platform} style={s.field}><Text style={s.label}>{platform}</Text><TextInput accessibilityLabel={platform+' business URL'} value={typeof socials[platform]==='string'?socials[platform]:''} editable={!busy} autoCapitalize="none" style={s.input} onChangeText={value=>{const links={...socials};if(value)links[platform]=value;else delete links[platform];update('social_links',links);}}/></View>):<Text style={s.error}>The stored social-link format cannot be safely edited here. Use the website to review it.</Text>}<Action label="Save business details" disabled={busy||!socials} run={save}/><Action label="Close this draft" disabled={busy} run={()=>{setDraft(null);setSelected('');setNotice('');}}/><Text style={s.body}>Closing the draft or switching workspace discards unsaved changes. Detailed industry fields and media uploads remain on the website.</Text></>:null}</>:null}</View>;
}
const s=StyleSheet.create({panel:{padding:22,gap:14,borderWidth:1,borderColor:'#DFE6EB',backgroundColor:'#fff',borderRadius:18},title:{fontSize:22,fontWeight:'700',color:'#132F46'},body:{fontSize:14,lineHeight:22,color:'#60717E'},label:{fontSize:13,color:'#132F46',fontWeight:'700'},field:{gap:6},input:{minHeight:46,padding:12,borderWidth:1,borderColor:'#CAD7E0',borderRadius:10,color:'#132F46'},action:{minHeight:44,padding:12,backgroundColor:'#EAF4FB',borderRadius:10,justifyContent:'center'},link:{color:'#116CBA',fontWeight:'700'},error:{color:'#963624'}});
