import{LIGHT}from'./brand';
import {useEffect,useRef,useState} from 'react';
import {Image,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {useAuth} from './Auth';
import {communityError} from './community';
import {communityMediaURL} from './communityMedia';
export function SocialAction({label,run,disabled=false,selected=false}:{label:string;run:()=>void;disabled?:boolean;selected?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} accessibilityState={{disabled,selected}} onPress={run} style={[socialStyle.action,selected&&socialStyle.selected,disabled&&{opacity:.45}]}><Text style={[socialStyle.link,selected&&{color:LIGHT.onButton}]}>{label}</Text></Pressable>;}
export function SocialField({label,value,set,max=500,multiline=false,disabled=false}:{label:string;value:string;set:(v:string)=>void;max?:number;multiline?:boolean;disabled?:boolean}){return <View style={{gap:7}}><Text style={socialStyle.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={set} editable={!disabled} maxLength={max} multiline={multiline} style={[socialStyle.input,multiline&&{minHeight:110,textAlignVertical:'top'}]}/></View>;}
export function SocialAvatar({profile,size=42}:{profile:any;size?:number}){const [failed,setFailed]=useState(false),url=communityMediaURL(profile?.avatar_url);useEffect(()=>setFailed(false),[url]);return url&&!failed?<Image accessibilityLabel={profile.display_name+' profile photo'} source={{uri:url}} onError={()=>setFailed(true)} style={{width:size,height:size,borderRadius:size/2}}/>:<View style={[socialStyle.avatar,{width:size,height:size,borderRadius:size/2}]}><Text style={{fontSize:size*.38,color:LIGHT.accent,fontWeight:'700'}}>{(profile?.display_name||'Z').slice(0,1).toUpperCase()}</Text></View>;}
export function useSocialScope(){const {client,session}=useAuth(),user=session?.user.id,alive=useRef(true),working=useRef(false);const [busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);const current=()=>alive.current&&client.session?.user.id===user;const read=(name:string,args:any)=>session?client.rpc(name,args):client.request('/rest/v1/rpc/'+name,args);const run=async(fn:()=>Promise<void>)=>{if(working.current)return;working.current=true;setBusy(true);setError('');try{await fn();}catch(e){if(current())setError(communityError(e));}finally{working.current=false;if(current())setBusy(false);}};return {client,session,current,read,run,busy,error,setError};}
export const socialStyle=StyleSheet.create({content:{padding:20,gap:18,paddingBottom:34},panel:{padding:19,gap:14,backgroundColor:LIGHT.surface,borderWidth:1,borderColor:LIGHT.line,borderRadius:24},title:{fontSize:30,fontWeight:'700',color:LIGHT.ink,letterSpacing:-.8},heading:{fontSize:19,fontWeight:'700',color:LIGHT.ink},body:{fontSize:15,lineHeight:24,color:LIGHT.muted},small:{fontSize:12,lineHeight:19,color:LIGHT.dim},label:{fontSize:13,fontWeight:'700',color:LIGHT.ink},input:{minHeight:48,padding:14,borderWidth:1,borderColor:LIGHT.line,borderRadius:15,color:LIGHT.ink,fontSize:16},action:{minHeight:44,paddingHorizontal:16,paddingVertical:11,backgroundColor:LIGHT.surfaceRaised,borderRadius:24,justifyContent:'center'},selected:{backgroundColor:LIGHT.ink},link:{color:LIGHT.accent,fontWeight:'700',fontSize:13},error:{color:LIGHT.error,fontSize:14,lineHeight:22},row:{flexDirection:'row',flexWrap:'wrap',gap:9,alignItems:'center'},avatar:{alignItems:'center',justifyContent:'center',backgroundColor:LIGHT.surfaceRaised},divider:{height:1,backgroundColor:LIGHT.line},image:{width:'100%',height:340,borderRadius:20,backgroundColor:LIGHT.surfaceRaised},eyebrow:{fontSize:10,fontWeight:'700',letterSpacing:2,color:LIGHT.gold}});
