import {totals,receipt,addLine,productLink,initialVariant,singleDefaultVariant,variantLabel} from '../../assets/commerce/model.mjs';
export const COMMERCE='https://www.zoi.city/api/commerce';
const ID=/^\d{8,20}$/,HANDLE=/^[-a-zA-Z0-9]{1,200}$/;
export type BasketItem={single_default_variant?:boolean;id:string;quantity:number;title:string;product_title:string;handle:string;price:string;currency:string;image:string|null};
export function commerceImage(value:unknown){try{const u=new URL(String(value));return u.protocol==='https:'&&['cdn.shopify.com','buygreek.shop'].includes(u.hostname)&&!u.username&&!u.password&&!u.port?u.href:null;}catch{return null;}}
export function commercePrice(value:unknown){if(typeof value!=='string'||!/^\d{1,9}(?:\.\d{1,6})?$/.test(value))throw Error('This product price could not be verified.');return value;}
export function commerceVariant(v:any){if(!v||!ID.test(v.id||'')||typeof v.available!=='boolean'||!/^[A-Z]{3}$/.test(v.currency||'')||typeof v.title!=='string')throw Error('This product option could not be verified.');return {...v,price:commercePrice(v.price),image:commerceImage(v.image)};}
export function commerceProduct(p:any){if(!p||!HANDLE.test(p.handle||'')||typeof p.title!=='string'||typeof p.description!=='string'||!Array.isArray(p.variants)||!Array.isArray(p.images)||typeof p.more_variants!=='boolean'||typeof p.available!=='boolean'||p.url!=='https://buygreek.shop/products/'+p.handle)throw Error('This BuyGreek product could not be verified.');return {...p,image:commerceImage(p.image),images:p.images.map((i:any)=>({...i,url:commerceImage(i.url)})).filter((i:any)=>i.url),variants:p.variants.map(commerceVariant)};}
export function basketRead(value:unknown):BasketItem[]{if(!Array.isArray(value)||value.length>30)throw Error('This saved basket could not be restored.');const seen=new Set();return value.map(r=>{if(!r||!ID.test(r.id||'')||seen.has(r.id)||!Number.isInteger(r.quantity)||r.quantity<1||r.quantity>20||!HANDLE.test(r.handle||'')||!/^[A-Z]{3}$/.test(r.currency||'')||typeof r.title!=='string'||typeof r.product_title!=='string')throw Error('This saved basket could not be restored.');seen.add(r.id);return {...r,single_default_variant:r.single_default_variant===true&&r.title==='Default Title',price:commercePrice(r.price),image:commerceImage(r.image)};});}
const sharedBasket=(rows:BasketItem[])=>rows.map(r=>({...r,title:r.product_title,variant:r.title}));
export function basketAdd(basket:BasketItem[],product:any,variant:any,quantity:number){commerceVariant(variant);return basketRead(addLine(sharedBasket(basket),product,variant,quantity).map((r:any)=>({...r,product_title:r.title,title:r.variant})));}
export function basketTotals(rows:BasketItem[]){return totals(rows).map((r:any)=>({...r,amount:r.amount.split('.')[0]+'.'+r.amount.split('.')[1].replace(/0+$/,'').padEnd(2,'0')}));}
export {productLink,initialVariant,singleDefaultVariant,variantLabel};
export function commerceReceipt(value:any,basket:BasketItem[]){if(value?.ok!==true||value.payment_collected!==false||!Array.isArray(value.lines)||value.lines.length!==basket.length||typeof value.pricing_note!=='string')throw Error('Checkout review could not be verified.');const rows=value.lines.map((v:any)=>{commerceVariant(v);const requested=basket.find(r=>r.id===v.id);if(!requested||requested.quantity!==v.quantity||!v.available||!HANDLE.test(v.handle||'')||typeof v.product_title!=='string')throw Error('Checkout quantities or availability changed. Review the basket again.');return v;});if(new Set(rows.map((r:any)=>r.id)).size!==basket.length)throw Error('Checkout items could not be verified.');receipt(value,sharedBasket(basket));const expected='https://buygreek.shop/cart/'+basket.map(r=>r.id+':'+r.quantity).join(',');if(value.checkout_url!==expected)throw Error('The checkout address did not match your basket.');return {...value,lines:rows};}
export function shopLink(value:string){try{const u=new URL(value,'https://www.zoi.city');const product=u.searchParams.get('product')||'',variant=u.searchParams.get('variant')||'';return {product:HANDLE.test(product)?product:'',variant:ID.test(variant)?variant:variant?'unavailable-shared-option':''};}catch{return {product:'',variant:''};}}
