import {inquiryId} from './inquiries.ts';
import {communityMediaURL} from './communityMedia.ts';
export const communityTopics=['food','travel','business','careers','culture','language','music','faith','sport','family','local','community'];
export const communityModes=[['for_you','For you'],['following','Following'],['watch','Watch'],['questions','Ask Greeks'],['near_me','Near me'],['latest','Latest'],['saved','Saved']] as const;
const count=(n:any)=>Number.isInteger(n)&&n>=0;
export function communityProfile(v:any){if(!v||!inquiryId(v.id)||typeof v.display_name!=='string'||typeof v.bio!=='string'||!Array.isArray(v.interests)||!Number.isInteger(v.version)||v.version<0||!['following_count','follower_count','post_count'].every(k=>count(v[k])))throw Error('This public profile could not be verified.');return {...v,avatar_url:communityMediaURL(v.avatar_url)};}
export function communityPost(v:any){if(!inquiryId(v?.id)||!inquiryId(v.author?.id)||typeof v.author.display_name!=='string'||typeof v.body!=='string'||!Array.isArray(v.media)||!Array.isArray(v.topics)||!Array.isArray(v.ranking_reasons)||!count(v.likes)||!count(v.comments)||!Number.isFinite(Date.parse(v.created_at)))throw Error('A community post could not be verified.');return {...v,author:{...v.author,avatar_url:communityMediaURL(v.author.avatar_url)},media:v.media.map((m:any)=>{if(!['image','video'].includes(m.type)||!communityMediaURL(m.url))throw Error('A community media attachment could not be verified.');return {...m,url:communityMediaURL(m.url),poster_url:communityMediaURL(m.poster_url)};})};}
export function communityFeed(v:any,mode:string){if(v?.ok!==true||v.mode!==mode||!Number.isFinite(Date.parse(v.as_of))||!Array.isArray(v.posts)||!Array.isArray(v.ranking_rules)||v.next_offset!==null&&(!Number.isInteger(v.next_offset)||v.next_offset<1))throw Error('The community feed could not be verified.');return {...v,posts:v.posts.map(communityPost)};}
export function communityComments(v:any,post:string){if(v?.ok!==true||!Array.isArray(v.comments)||v.comments.some((c:any)=>!inquiryId(c.id)||c.post_id!==post||!inquiryId(c.author?.id)||typeof c.body!=='string')||v.next_offset!==null&&!Number.isInteger(v.next_offset))throw Error('The conversation could not be verified.');return v;}
export function communityCommentReceipt(v:any,post:string,profile:string){const c=v?.comment;if(v?.ok!==true||!inquiryId(c?.id)||c.post_id!==post||c.author?.id!==profile||c.mine!==true)throw Error('Your reply has not been confirmed. Retry the same request.');return c;}
export function communityFlag(v:any,id:string,flag:string,desired:boolean){if(v?.ok!==true||(v.post_id||v.profile_id)!==id||v[flag]!==desired||(flag==='liked'&&!count(v.likes))||(flag==='following'&&!count(v.follower_count)))throw Error('This change could not be verified. Refresh before trying again.');return v;}
export function communityProfileData(form:any){const handle=String(form.handle||'').trim().toLowerCase(),display_name=String(form.display_name||'').trim(),bio=String(form.bio||''),city=String(form.city||'').trim(),country=String(form.country||'').trim();if(!/^[a-z0-9_]{3,30}$/.test(handle)||!display_name||display_name.length>80||bio.length>400||city.length>120||country.length>120||!Array.isArray(form.interests)||form.interests.length>8||form.interests.some((t:string)=>!communityTopics.includes(t)))throw Error('Review your public handle, name, bio and up to eight interests.');return {handle,display_name,bio,city,country,interests:form.interests,avatar_media_id:form.avatar_media_id||null};}
export function communityError(error:any){const text=String(error?.message||error);return /blocked|not_visible/.test(text)?'This content is unavailable to this account.':/handle.*taken|unique/.test(text)?'That public handle is already in use.':/version_conflict/.test(text)?'This changed in another session. Refresh before editing again.':text;}

export function communityPublicationRequest(v:any,profile:string){if(v?.version!==1||v.profile!==profile||!inquiryId(v.args?.p_request)||typeof v.args.p_body!=='string'||!v.args.p_body.trim()||v.args.p_body.trim().length>1000||!Array.isArray(v.args.p_media)||v.args.p_media.length>4||v.args.p_media.some((id:any)=>!inquiryId(id))||new Set(v.args.p_media).size!==v.args.p_media.length||!['moment','question','recommendation','event'].includes(v.args.p_context?.intent)||!Array.isArray(v.args.p_context?.topics)||v.args.p_context.topics.length>5||v.args.p_context.topics.some((t:string)=>!communityTopics.includes(t)))throw Error('This publication recovery record cannot be safely retried. Review your posts before discarding it.');return v;}
export function communityPublicationReceipt(v:any,request:string){if(v?.ok!==true||!inquiryId(v.id)||v.request_id!==request)throw Error('Publication is not yet confirmed. Retry the same saved request.');return v;}
