import {Pressable,StyleSheet,Text,View} from 'react-native';
import {companyJourney} from '../../assets/operations/company-journey.mjs';
import {canWrite,type OpsRecord} from './operations';
import type {nativeCompanyWork} from './companyWorkspace';
import {CompanyConsole} from './CompanyConsole';
import {CompanyHandover} from './CompanyHandover';
function Action({label,disabled,onPress}:{label:string;disabled:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[s.action,disabled&&{opacity:.5}]}><Text style={s.actionText}>{label}</Text></Pressable>;}
export function CompanyWorkspace({model,role,members,disabled,onOpen,onStart,onFiles,details,onDetails,records,current,read}:{records:OpsRecord[];current:()=>boolean;read:(name:string,args:Record<string,unknown>)=>Promise<any>;model:ReturnType<typeof nativeCompanyWork>;role:string;members:{profile_id:string;display_name?:string}[];disabled:boolean;onOpen:(row:OpsRecord)=>void;onStart:(row:OpsRecord)=>void;onFiles:(row:OpsRecord)=>void;details:boolean;onDetails:()=>void}){
 const journey=companyJourney(model),write=canWrite(role,'project'),next=journey.next;
 return <View style={s.panel}><Text style={s.kicker}>YOUR COMPANY WORKSPACE</Text><Text style={s.title}>{model.company.title}</Text><Text style={s.body}>Company administration · projects, assigned work and files</Text>
 <View style={s.metrics}>{[[model.projects.length,'Projects'],[journey.counts.completed+'/'+journey.counts.total,'Tasks completed'],[journey.counts.overdue,'Overdue'],[journey.counts.blocked,'Blocked']].map(([value,label])=><View key={String(label)} style={s.metric}><Text style={s.value}>{value}</Text><Text style={s.small}>{label}</Text></View>)}</View><Text style={s.small}>{model.projects.length} projects · {model.tasks.filter(t=>t.status!=='completed').length} open tasks · {model.contacts.length} work contacts</Text><Text style={s.small}>{journey.counts.unassigned} unassigned tasks</Text>
 <View style={s.next}><Text style={s.heading}>Your next step</Text><Text style={s.body}>{next.detail}</Text>{write||!['create_project','create_task'].includes(next.action)?<Action label={next.label} disabled={disabled} onPress={()=>next.action==='create_project'||next.action==='create_task'?onStart(next.record):onOpen(next.record)}/>:<Text style={s.small}>An authorized editor or owner can start linked work.</Text>}</View>
 {write?<Action label="Start company project" disabled={disabled} onPress={()=>onStart(model.company)}/>:null}
 {journey.projects.map((item:any)=><View key={item.project.id} style={s.project}><Text style={s.heading}>{item.project.title}</Text><Text style={s.small}>{item.project.status.replaceAll('_',' ')} · {item.completed} of {item.tasks.length} tasks completed</Text>{item.percent!==null?<View accessibilityLabel={item.project.title+' task completion: '+item.percent+' percent'} style={s.track}><View style={[s.fill,{width:(item.percent+'%') as `${number}%`}]}/></View>:null}<Action label={'Open company project · '+item.project.title} disabled={disabled} onPress={()=>onOpen(item.project)}/>{write?<><Action label={'Add task · '+item.project.title} disabled={disabled} onPress={()=>onStart(item.project)}/><Action label={'Project files · '+item.project.title} disabled={disabled} onPress={()=>onFiles(item.project)}/></>:null}</View>)}
 <CompanyConsole key={model.company.id} records={records} workspace={model.company.workspace_id} companyId={model.company.id} members={members} disabled={disabled} onOpen={onOpen}/>
 <CompanyHandover key={model.company.id+':handover'} workspace={model.company.workspace_id} companyId={model.company.id} role={role} disabled={disabled} current={current} read={read}/>
 <Text style={s.small}>{write?'Private project documents open here in the app. Files remain in your authorized workspace.':'Private files require an authorized editor or owner.'}</Text><Action label={details?'Hide company details':'Company details & settings'} disabled={disabled} onPress={onDetails}/></View>;
}
const s=StyleSheet.create({panel:{gap:14,padding:16,borderWidth:1,borderColor:'#DFE6EB',borderRadius:18},kicker:{fontSize:10,letterSpacing:1.5,color:'#60717E',fontWeight:'700'},title:{fontSize:24,fontWeight:'700',color:'#132F46'},heading:{fontSize:17,fontWeight:'700',color:'#132F46'},body:{fontSize:14,lineHeight:22,color:'#60717E'},small:{fontSize:12,lineHeight:19,color:'#60717E'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{flexGrow:1,flexBasis:'40%',padding:12,backgroundColor:'#F1F7FB',borderRadius:12},value:{fontSize:24,fontWeight:'700',color:'#132F46'},next:{padding:16,gap:10,borderWidth:1,borderColor:'#CAD7E0',borderLeftWidth:3,borderLeftColor:'#116CBA',borderRadius:12,backgroundColor:'#F1F7FB'},project:{padding:14,gap:12,borderWidth:1,borderColor:'#DFE6EB',borderRadius:14},task:{paddingTop:12,gap:8,borderTopWidth:1,borderColor:'#DFE6EB'},track:{height:6,borderRadius:3,backgroundColor:'#DFE6EB',overflow:'hidden'},fill:{height:6,backgroundColor:'#116CBA'},action:{minHeight:44,padding:12,backgroundColor:'#EAF4FB',borderRadius:10,justifyContent:'center'},actionText:{fontSize:12,fontWeight:'700',color:'#116CBA'}});
