import {localInput,zonedToInstant} from '../../assets/bookings/model.mjs';
import {publicURL} from './profile.ts';
export const creatorChannels=['instagram','tiktok','youtube','podcast','blog','live','other'];
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const string=(v:unknown,max:number,required=false)=>{const text=String(v??'').trim();if((required&&!text)||text.length>max)throw Error(`Use ${required?'1':'0'}–${max} characters.`);return text;};
export const deviceZone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
export const creatorLocal=(value:string|null)=>value?localInput(value,deviceZone()):'';
function instant(value:string){return value?zonedToInstant(value,deviceZone()):null;}
export function creatorDraftForm(draft:any){return {...draft,fee:((draft.planned_fee_cents||0)/100).toFixed(2),channels:draft.channels||[],event_at:creatorLocal(draft.event_at),duration_minutes:String(draft.duration_minutes||0)};}
export function creatorDraftData(form:any,kind:string){if(!/^\d+(?:\.\d{1,2})?$/.test(form.fee||'')||Number(form.fee)>1000000)throw Error('Use a planned fee from 0 to 1,000,000 with up to two decimal places.');const currency=String(form.currency||'').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(currency))throw Error('Use a three-letter currency, such as EUR.');const base={title:string(form.title,200,true),summary:string(form.summary,4000),planned_fee_cents:Math.round(Number(form.fee)*100),currency};if(kind==='sponsorship'){if(!Array.isArray(form.channels)||form.channels.some((c:string)=>!creatorChannels.includes(c)||c==='live')||new Set(form.channels).size!==form.channels.length)throw Error('Choose supported sponsorship channels.');return {...base,channels:form.channels,usage_terms:string(form.usage_terms,2000),disclosure_notes:string(form.disclosure_notes,1000)};}if(kind!=='performance')throw Error('This campaign type is unavailable.');const duration=Number(form.duration_minutes);if(!Number.isInteger(duration)||duration<0||duration>1440)throw Error('Use a duration from 0 to 1,440 minutes.');return {...base,venue:string(form.venue,300),event_at:instant(form.event_at),duration_minutes:duration,technical_requirements:string(form.technical_requirements,3000)};}
export function creatorDeliverableData(form:any){if(!creatorChannels.includes(form.channel))throw Error('Choose a deliverable channel.');return {title:string(form.title,200,true),description:string(form.description,2000),channel:form.channel,due_at:instant(form.due_at)};}
export function creatorProof(value:string){const text=value.trim(),url=publicURL(text);if(!url.startsWith('https://')||text.length>2000||/\s/.test(text))throw Error('Use a complete public HTTPS proof link without credentials or spaces.');return url;}
export function creatorRecord(value:any,key:string,id?:string){const record=value?.[key];if(value?.ok!==true||!record||!uuid.test(record.id||'')||(id&&record.id!==id))throw Error('This change was not confirmed. Keep the request and refresh before retrying.');return record;}
export function creatorCampaign(value:any,workspace:string,id?:string){const row=creatorRecord(value,'campaign',id);if(row.workspace_id!==workspace||!Number.isInteger(row.version)||row.version<1||!['sponsorship','performance'].includes(row.kind)||!uuid.test(row.project_id||''))throw Error('This campaign receipt did not match the workspace.');return row;}
export function creatorSharedDetail(value:any,id:string,workspace?:string){if(value?.ok!==true||value.campaign?.id!==id||typeof value.operator!=='boolean'||typeof value.can_write!=='boolean'||!['briefs','deliverables','submissions','audit'].every(k=>Array.isArray(value[k])))throw Error('This private campaign could not be verified.');if(workspace&&(!value.operator||value.campaign.workspace_id!==workspace))throw Error('This campaign belongs to another workspace.');if(!value.operator&&(['draft','project_id','company_id','customer_id'].some(k=>k in value.campaign)||value.audit.length))throw Error('The customer response contained private workspace fields.');if(value.briefs.some((b:any)=>!uuid.test(b.id||'')||b.campaign_id!==id||!['shared','accepted','changes_requested'].includes(b.status)||!b.payload?.brief||!Array.isArray(b.payload.deliverables))||value.submissions.some((s:any)=>!uuid.test(s.id||'')||s.campaign_id!==id||!['submitted','accepted','changes_requested'].includes(s.status)))throw Error('Shared campaign history could not be verified.');return value;}
export function creatorDecisionReceipt(value:any,key:'brief'|'submission',id:string,request:string,decision:string,note:string){const row=creatorRecord(value,key,id);if(row.status!==decision||row.decision_request!==request||row.decision_note!==note)throw Error('The decision receipt did not match this request.');return row;}

export function creatorShareCheck(draft:any,kind:string,count:number){if(!draft.summary?.trim())throw Error('Add a clear brief summary before sharing.');if(count<1||count>30)throw Error('Add between 1 and 30 deliverables before sharing.');if(kind==='sponsorship'&&(!draft.channels?.length||!draft.disclosure_notes?.trim()))throw Error('Choose sponsorship channels and add disclosure notes before sharing.');if(kind==='performance'&&(!draft.venue?.trim()||!draft.event_at||draft.duration_minutes<1))throw Error('Add a venue, event time and duration before sharing.');}
export function creatorError(error:unknown){const message=error instanceof Error?error.message:String(error);const known:Record<string,string>={creator_no_changes_to_share:'This saved version is already shared. Save a changed brief or deliverable before sharing another version.',creator_permission_denied:'Your account cannot access this private collaboration.',creator_version_conflict:'This draft changed. Refresh and review the latest saved version.',creator_business_changed:'The original business changed ownership or visibility. Existing shared work is read-only.',creator_project_archived:'The linked Operations project is archived. This collaboration is read-only.',creator_brief_superseded:'A newer brief was shared. Review that version before responding.',creator_decision_already_recorded:'A decision is already recorded. Refresh to see it.',creator_delivery_already_submitted:'This deliverable already has a pending or accepted submission.',creator_request_conflict:'This request reference was used with different content. Review the saved history before starting another request.',creator_delivery_task_unavailable:'The linked task was moved or archived. The business team must review it in Operations.'};return known[message]||(/^(creator_|invalid_creator_)/.test(message)?'The change could not be confirmed. Review the saved records and try again.':message);}
