import {inquiryId} from './inquiries.ts';
export const creatorActions=['creator_convert','creator_draft_save','creator_deliverable_save','creator_brief_share','creator_submission_send','creator_brief_decide','creator_submission_decide'];
type Marker={actor:string;request:string;action:string};
type Store={load(user:string):Promise<unknown>;save(user:string,value:unknown):Promise<void>;clear(user:string):Promise<void>};
export class CreatorRecovery {
 marker:Marker|null=null;payload:any=null;ready=false;busy=false;
 private store:Store;private actor:string;private current:()=>boolean;private call:(name:string,args:any)=>Promise<any>;private nonce:()=>string;private changed:()=>void;
 constructor(store:Store,actor:string,current:()=>boolean,call:(name:string,args:any)=>Promise<any>,nonce:()=>string,changed:()=>void=()=>{}){this.store=store;this.actor=actor;this.current=current;this.call=call;this.nonce=nonce;this.changed=changed;}
 private assert(){if(!this.current())throw Error('Your account or workspace changed.');}
 private validate(value:any):Marker|null{if(value===null)return null;if(!value||value.actor!==this.actor||!inquiryId(value.request)||!creatorActions.includes(value.action)||Object.keys(value).some(k=>!['actor','request','action'].includes(k)))throw Error('Creator recovery cannot be verified. Do not start a replacement change.');return value;}
 async load(){this.assert();this.ready=false;this.marker=this.validate(await this.store.load(this.actor));this.assert();this.ready=true;this.changed();}
 dropPayload(){this.payload=null;this.changed();}
 get blocked(){return !this.ready||!!this.marker||this.busy;}
 private result(value:any){const m=this.marker;if(!m||value?.ok!==true||value.request_id!==m.request||!['saved','missing','cancelled'].includes(value.state)||(value.state==='saved'&&(value.action!==m.action||!inquiryId(value.campaign_id)||!inquiryId(value.entity_id))))throw Error('The creator receipt did not match this request.');if(value.state==='saved'&&this.payload){const p=this.payload.p_args;if(p.p_campaign&&value.campaign_id!==p.p_campaign)throw Error('The creator campaign receipt did not match.');const id=p.p_id||p.p_brief||p.p_submission;if(id&&value.entity_id!==id)throw Error('The creator item receipt did not match.');}return value;}
 private async finish(value:any){this.assert();const result=this.result(value);if(result.state!=='missing'){await this.store.clear(this.actor);this.assert();const remaining=await this.store.load(this.actor);this.assert();if(remaining!==null)throw Error('Creator recovery could not be cleared.');this.marker=null;this.payload=null;}this.changed();return result;}
 private async run(work:()=>Promise<any>){this.assert();if(this.busy)throw Error('Wait for the previous creator request.');this.busy=true;this.changed();try{return await work();}finally{this.busy=false;this.changed();}}
 async send(action:string,args:any){return this.run(async()=>{if(!this.ready||this.marker)throw Error('Check the previous creator change before saving another.');if(!creatorActions.includes(action))throw Error('Invalid creator action.');const data=JSON.parse(JSON.stringify(args));delete data.p_request;const marker={actor:this.actor,request:this.nonce(),action};this.validate(marker);try{await this.store.save(this.actor,marker);this.assert();const readback=await this.store.load(this.actor);this.assert();this.marker=this.validate(readback);if(!this.marker||this.marker.request!==marker.request||this.marker.action!==action)throw Error('Creator recovery was not saved. Nothing was sent.');}catch(error){this.ready=false;throw error;}this.payload={p_request:marker.request,p_action:action,p_args:data};this.changed();this.assert();const result=await this.call('creator_mutation_execute',this.payload);if(result?.state!=='saved')throw Error('The change was not confirmed saved. Check its receipt.');return this.finish(result);});}
 async recover(mode:'check'|'retry'|'cancel'){return this.run(async()=>{if(!this.ready||!this.marker)throw Error('No verified recovery reference is available.');this.assert();const value=mode==='retry'?await this.retry():await this.call('creator_request_status',{p_request:this.marker.request,p_cancel_if_missing:mode==='cancel'});return this.finish(value);});}
 private retry(){if(!this.payload)throw Error('The private payload is no longer on this device. Check the receipt or cancel if unsaved.');this.assert();return this.call('creator_mutation_execute',this.payload);}
}
