import { validateFileMetadata } from '../../assets/documents/file-rules.mjs';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export { validateFileMetadata };
export function documentReceipt(value:any,workspace:string,expected:number,document?:string){if(value?.ok!==true||!value.document||value.document.workspace_id!==workspace||!uuid.test(value.document.id||'')||(document&&value.document.id!==document)||!uuid.test(value.version?.id||'')||value.version?.state!=='ready'||value.document.current_version!==value.version.version||value.version.version<=expected)throw new Error('The upload was not confirmed. Keep this request and refresh document history before retrying.');return value;}
export async function privateDocumentBody(response:Response,metadata:{filename:string;mime_type:string;size_bytes:number}) {
 validateFileMetadata({name:metadata.filename,type:metadata.mime_type,size:metadata.size_bytes});
 if(!response.ok||!/(?:^|,)\s*no-store(?:,|$)/i.test(response.headers.get('cache-control')||'')||!/^attachment(?:;|$)/i.test(response.headers.get('content-disposition')||'')||response.headers.get('content-type')?.split(';')[0]!==metadata.mime_type)throw new Error('The private attachment response could not be verified.');
 const reader=response.body?.getReader?.();let bytes:Uint8Array;
 if(reader){const chunks:Uint8Array[]=[];let total=0;try{for(;;){const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>10485760||total>metadata.size_bytes){await reader.cancel();throw new Error('The download exceeded its verified size.');}chunks.push(part.value);}bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}}finally{reader.releaseLock();}}
 else bytes=new Uint8Array(await response.arrayBuffer());
 if(bytes.byteLength!==metadata.size_bytes)throw new Error('The downloaded file size did not match its record.');return bytes;
}
export function documentError(error:unknown){const message=error instanceof Error?error.message:String(error);const pairs:[RegExp,string][]=[[/unsupported_document_type|filename_type_mismatch/,'Choose PDF, plain text, PNG or JPEG with a matching filename.'],[/invalid_document_size|request_too_large/,'Choose a non-empty file no larger than 10 MiB.'],[/invalid_filename/,'Use a filename up to 180 characters without slashes or control characters.'],[/document_permission_denied/,'Only workspace owners, admins and editors can access these private documents.'],[/version_conflict|upload_state_conflict/,'This document changed. Refresh its history before selecting a new version.'],[/document_signature_mismatch|invalid_text_document/,'The file contents do not match an accepted document type.'],[/active_project_required/,'Choose an active project or matter in this workspace.'],[/cleanup_not_allowed/,'Only incomplete uploads older than 15 minutes can be cleaned up.']];return pairs.find(([pattern])=>pattern.test(message))?.[1]||message;}
