import {zonedToInstant,localInput} from '../../assets/bookings/model.mjs';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export const festivalCategories=['food','crafts','books','community','sponsor','other'];
export const festivalStatuses=['submitted','approved','declined','withdrawn','cancelled'];
const text=(v:unknown,max:number,required=false)=>{const s=String(v??'').trim();if((required&&!s)||s.length>max)throw Error(`Use ${required?'1':'0'}–${max} characters.`);return s;};
export function festivalApplication(form:any){const units=Number(form.units),email=text(form.contact_email,160,true);if(!Number.isInteger(units)||units<1||units>10)throw Error('Request between 1 and 10 units.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a valid contact email.');if(!festivalCategories.includes(form.category))throw Error('Choose an application category.');return {organisation:text(form.organisation,160,true),contact_name:text(form.contact_name,120,true),contact_email:email,category:form.category,units,notes:text(form.notes,2500)};}
export function festivalPackage(form:any){if(!uuid.test(form.event_id||'')||!['booth','sponsor'].includes(form.kind))throw Error('Choose an owned host and offer type.');if(!/^\d+(?:\.\d{1,2})?$/.test(form.price||'')||Number(form.price)>1000000)throw Error('Use a quote from 0 to 1,000,000 currency units with up to two decimal places.');const capacity=Number(form.capacity),currency=text(form.currency,3,true).toUpperCase(),benefits=String(form.benefits||'').split('\n').map((x:string)=>x.trim()).filter(Boolean);if(!Number.isInteger(capacity)||capacity<1||capacity>5000||!/^[A-Z]{3}$/.test(currency)||benefits.length>20||benefits.some((b:string)=>b.length>200))throw Error('Check capacity, three-letter currency, and up to 20 benefits of 200 characters each.');return {event_id:form.event_id,kind:form.kind,name:text(form.name,160,true),description:text(form.description,3000),benefits,price_cents:Math.round(Number(form.price)*100),currency,capacity,closes_at:zonedToInstant(form.closes_at,form.timezone),timezone:form.timezone,active:form.active===true};}
export function festivalPackageForm(row:any){return {...row,price:(row.price_cents/100).toFixed(2),capacity:String(row.capacity),benefits:row.benefits.join('\n'),closes_at:localInput(row.closes_at,row.timezone)};}
export function festivalRecord(value:any,key:string,{id,workspace,profile,version,status}:any={}){const row=value?.[key];if(value?.ok!==true||!uuid.test(row?.id||'')||(id&&row.id!==id)||(workspace&&row.workspace_id!==workspace)||(profile&&row.profile_id!==profile)||!Number.isInteger(row.version)||row.version<1||(version!==undefined&&row.version!==version)||(status&&row.status!==status))throw Error('This festival change was not confirmed. Review saved records before trying another request.');if(key==='application'&&(!uuid.test(row.inquiry_id||'')||!festivalStatuses.includes(row.status)||!row.terms||!Number.isInteger(row.total_cents)))throw Error('The application receipt is incomplete.');return row;}
export function festivalPage(value:any,key:string,workspace?:string,profile?:string){if(value?.ok!==true||!Array.isArray(value[key])||(value.next_offset!==null&&(!Number.isInteger(value.next_offset)||value.next_offset<0))||value[key].some((r:any)=>(workspace&&r.workspace_id!==workspace)||(profile&&r.profile_id!==profile)))throw Error('Private festival records could not be verified.');return value;}
export function festivalError(error:unknown){const code=error instanceof Error?error.message:String(error),map:Record<string,string>={festival_offer_changed:'The offer changed. Refresh and review its current quote before applying.',festival_offer_full:'There are not enough units available. Pending applications do not reserve capacity.',festival_version_conflict:'This record changed. Refresh and review its current version.',festival_offer_unavailable:'This offer is paused, closed or unavailable.',festival_application_exists:'You already have a pending or approved application for this offer.',festival_capacity_below_allocations:'Capacity cannot be lower than approved units.',festival_package_has_applications:'An offer with application history cannot change its host or type.',festival_permission_denied:'Your account cannot access these private offers or applications.',festival_application_locked:'Only pending applications can be edited.',festival_event_unavailable:'The host must be a published visible page owned by this workspace.'};return map[code]||(/^festival_|^invalid_festival_/.test(code)?'This change could not be confirmed. Check your details and refresh the saved state.':code);}
