type Storage={getItem:(key:string)=>Promise<string|null>;setItem:(key:string,value:string)=>Promise<void>;removeItem:(key:string)=>Promise<void>};
export type GeneralAttempt={actor:string;event:string;tier:string;id:string;created_at:string;protocol?:'once';qty?:number};
export function generalReceipt(value:any,attempt:GeneralAttempt){if(attempt.protocol!=='once'||!Number.isInteger(attempt.qty)||value?.ok!==true||typeof value.code!=='string'||!value.code.trim()||value.qty!==attempt.qty||value.amount_cents!==0||value.paid!==false||typeof value.currency!=='string'||value.request_id!==attempt.id||value.event_id!==attempt.event||value.ticket_type_id!==attempt.tier)throw Error('The reservation receipt did not match this saved request.');return value;}
export function generalRecovery(value:any,attempt:GeneralAttempt){if(value?.ok!==true||typeof value.found!=='boolean')throw Error('The saved reservation could not be checked.');if(!value.found)return null;if(!['reserved','confirmed','cancelled'].includes(value.current_status)||typeof value.checked_in!=='boolean'||typeof value.event_available!=='boolean')throw Error('The current reservation status could not be verified.');return{receipt:generalReceipt(value.receipt,attempt),status:value.current_status as string,checkedIn:value.checked_in as boolean,eventAvailable:value.event_available as boolean};}
export function generalSubmission(attempt:GeneralAttempt,name:string,email:string){if(attempt.protocol!=='once'||!Number.isInteger(attempt.qty)||attempt.qty!<1||attempt.qty!>10)throw Error('This older request must be reviewed with the organizer.');name=name.trim();email=email.trim().toLowerCase();if(!name||name.length>120||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>160)throw Error('Re-enter the original name and email.');return{p_request:attempt.id,p_event:attempt.event,p_type:attempt.tier,p_name:name,p_email:email,p_qty:attempt.qty};}
export class GeneralReservationGuard{
 private storage:Storage;
 constructor(storage:Storage){this.storage=storage;}
 private key(actor:string,event:string){if(!actor||!event)throw Error('Reservation scope is missing.');return 'zoi.ticket.uncertain.v1.'+encodeURIComponent(actor)+'.'+encodeURIComponent(event);}
 async read(actor:string,event:string):Promise<GeneralAttempt|null>{const raw=await this.storage.getItem(this.key(actor,event));if(!raw)return null;let value;try{value=JSON.parse(raw);}catch{throw Error('The saved reservation warning could not be read. Contact the organizer before booking again.');}if(value.actor!==actor||value.event!==event||typeof value.tier!=='string'||typeof value.id!=='string'||!Number.isFinite(Date.parse(value.created_at)))throw Error('The saved reservation warning could not be verified. Contact the organizer before booking again.');if(value.protocol!==undefined&&(value.protocol!=='once'||!Number.isInteger(value.qty)||value.qty<1||value.qty>10))throw Error('The saved request metadata could not be verified.');return value;}
 async references(actor:string,event:string):Promise<GeneralAttempt[]>{
  const raw=await this.storage.getItem(this.key(actor,event).replace('uncertain','references'));if(!raw)return [];
  let rows;try{rows=JSON.parse(raw);}catch{throw Error('Saved ticket references could not be read.');}
  if(!Array.isArray(rows)||rows.length>5)throw Error('Saved ticket references could not be verified.');
  const now=Date.now();const fresh=rows.filter((r:any)=>{if(r.actor!==actor||r.event!==event||r.protocol!=='once'||typeof r.id!=='string'||typeof r.tier!=='string'||!Number.isInteger(r.qty)||r.qty<1||r.qty>10||!Number.isFinite(Date.parse(r.created_at)))throw Error('Saved ticket references do not match this account.');return now-Date.parse(r.created_at)<=365*86400000&&Date.parse(r.created_at)<=now+60000;});
  if(fresh.length!==rows.length){const key=this.key(actor,event).replace('uncertain','references');if(fresh.length)await this.storage.setItem(key,JSON.stringify(fresh));else await this.storage.removeItem(key);}
  return fresh;
 }
 private async remember(attempt:GeneralAttempt){
  const rows=await this.references(attempt.actor,attempt.event);
  const {actor,event,tier,id,created_at,protocol,qty}=attempt;
  const value=JSON.stringify([{actor,event,tier,id,created_at,protocol,qty},...rows.filter(r=>r.id!==id)].slice(0,5));
  const key=this.key(actor,event).replace('uncertain','references');await this.storage.setItem(key,value);
  if(await this.storage.getItem(key)!==value)throw Error('Your confirmed ticket reference could not be saved. Keep your confirmation code.');
 }
 async hasGuestPending(actor:string,event:string){return actor!=='guest'&&!!await this.read('guest',event);}
 async begin(attempt:GeneralAttempt,current:()=>boolean){if(!current())throw Error('Your account changed.');if(await this.hasGuestPending(attempt.actor,attempt.event))throw Error('Recover the earlier guest request while signed out before starting another reservation.');if(await this.read(attempt.actor,attempt.event))throw Error('An earlier reservation may have completed. Review it with the organizer before booking again.');if(!current())throw Error('Your account changed.');const key=this.key(attempt.actor,attempt.event),value=JSON.stringify(attempt);await this.storage.setItem(key,value);if(await this.storage.getItem(key)!==value)throw Error('This device could not preserve the reservation warning. No request was sent.');if(!current())throw Error('Your account changed. No request was sent.');}
 async confirmed(attempt:GeneralAttempt,receipt:{ok?:boolean;code?:string;qty?:number;amount_cents?:number;paid?:boolean},quantity:number){if(receipt.ok!==true||!receipt.code?.trim()||receipt.qty!==quantity||receipt.amount_cents!==0||receipt.paid!==false)throw Error('Reservation confirmation could not be verified.');if(attempt.protocol==='once')generalReceipt(receipt,attempt);const stored=await this.read(attempt.actor,attempt.event);if(!stored||stored.id!==attempt.id||stored.tier!==attempt.tier)throw Error('The saved reservation warning changed.');if(attempt.protocol==='once')await this.remember(attempt);await this.storage.removeItem(this.key(attempt.actor,attempt.event));}
}
