import {useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {useAuth} from './Auth';
import {inquiryDetail,inquiryError,inquiryId,inquiryReplyReceipt,inquiryStartReceipt,inquiryText,inquiryThread} from './inquiries';
function Action({label,run,disabled=false}:{label:string;run:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} accessibilityState={{disabled}} onPress={run} style={[s.action,disabled&&{opacity:.5}]}><Text style={s.link}>{label}</Text></Pressable>;}
function useScope(){const {client,session}=useAuth(),user=session?.user.id;const alive=useRef(true),working=useRef(false);const [busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);const current=()=>alive.current&&client.session?.user.id===user;const run=async(fn:()=>Promise<void>)=>{if(working.current)return;working.current=true;setBusy(true);setError('');try{await fn();}catch(e){if(current())setError(inquiryError(e));}finally{working.current=false;if(current())setBusy(false);}};return {client,session,current,run,busy,error};}
async function actor(client:any){const me=await client.rpc('zoi_me',{});const id=inquiryId(me?.profile?.id);if(!id)throw Error('Your account profile could not be verified. Refresh your account before sending.');return id;}
function Conversation({id,workspace,back,onThread,status}:{id:string;workspace?:string;back:()=>void;onThread?:(thread:any)=>void;status?:string}){
 const {client,session,current,run,busy,error}=useScope();const [detail,setDetail]=useState<any>(null),[body,setBody]=useState(''),[notice,setNotice]=useState('');const pending=useRef<any>(null);
 const load=async(older=false)=>{const value=inquiryDetail(await client.rpc('inquiry_thread',{p_thread:id,p_before:older?detail?.older_cursor:null}),id,workspace);if(current()){setDetail((old:any)=>older&&old?{...value,messages:[...value.messages,...old.messages.filter((m:any)=>!value.messages.some((n:any)=>n.id===m.id))]}:value);onThread?.(value.thread);}};
 useEffect(()=>{run(()=>load());},[id]);
 const send=()=>run(async()=>{const author=await actor(client);if(!current())return;pending.current||={thread:id,author,request:randomUUID(),body:inquiryText(body,4000)};const p=pending.current;const result=inquiryReplyReceipt(await client.rpc('inquiry_reply',{p_thread:p.thread,p_body:p.body,p_request:p.request}),p);if(!current())return;pending.current=null;setBody('');setDetail((old:any)=>({...old,thread:result.thread,messages:old.messages.some((m:any)=>m.id===result.message.id)?old.messages:[...old.messages,result.message]}));setNotice('Reply sent.');await load().catch(()=>{if(current())setNotice('Reply confirmed. Refresh to load any newer messages.');});});
 return <View style={s.panel}><Action label="Back to enquiries" disabled={busy} run={back}/>{busy?<ActivityIndicator/>:null}{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{notice?<Text accessibilityLiveRegion="polite" style={s.body}>{notice}</Text>:null}<Action label="Refresh conversation" disabled={busy} run={()=>run(()=>load())}/>{detail?<><Text style={s.title}>{detail.thread.subject}</Text><Text style={s.body}>{status||detail.thread.status} · {new Date(detail.thread.updated_at).toLocaleString()}</Text>{detail.older_cursor?<Action label="Load earlier messages" disabled={busy} run={()=>run(()=>load(true))}/>:null}{detail.messages.map((m:any)=><View key={m.id} style={s.message}><Text style={s.label}>{m.author_side==='business'?'Business team':'Customer'} · {new Date(m.created_at).toLocaleString()}</Text><Text selectable style={s.body}>{m.body}</Text></View>)}{detail.can_reply||pending.current?<><TextInput accessibilityLabel="Enquiry reply" value={body} onChangeText={setBody} editable={!busy&&!pending.current} maxLength={4000} multiline style={[s.input,{minHeight:110}]}/><Action label={pending.current?'Retry same reply':'Send reply'} disabled={busy||!body.trim()} run={send}/>{pending.current?<Text style={s.body}>This message may already have been sent. Retrying uses the same request. Refresh the conversation before discarding it.</Text>:null}{pending.current?<Action label="Discard pending reply after review" disabled={busy} run={()=>{pending.current=null;setBody('');setNotice('Local pending reply discarded. Server messages remain in the conversation.');}}/>:null}</>:<Text style={s.body}>Replies are unavailable because the business page is no longer available to this team.</Text>}{detail.operator?<><Text style={s.title}>Activity</Text>{detail.audit.map((a:any)=><Text key={a.id} style={s.small}>{a.action.replaceAll('_',' ')} · {new Date(a.created_at).toLocaleString()} · {a.actor_id}</Text>)}</>:null}</>:null}</View>;
}
export function InquiriesScreen({listing='',thread='',back,signIn}:{listing?:string;thread?:string;back:()=>void;signIn:()=>void}){const {session}=useAuth();return <Customer key={(session?.user.id||'anon')+':'+listing+':'+thread} listing={listing} thread={thread} back={back} signIn={signIn}/>;}
function Customer({listing,thread,back,signIn}:{listing:string;thread:string;back:()=>void;signIn:()=>void}){
 const {client,session,current,run,busy,error}=useScope();const [selected,setSelected]=useState(thread),[availability,setAvailability]=useState<any>(null),[threads,setThreads]=useState<any[]>([]),[loaded,setLoaded]=useState(false),[next,setNext]=useState<number|null>(null),[subject,setSubject]=useState(''),[body,setBody]=useState('');const pending=useRef<any>(null);
 const load=async(offset=0)=>{if(listing&&!inquiryId(listing))throw Error('This business enquiry link is invalid.');if(listing){const value=await client.request('/rest/v1/rpc/inquiry_availability',{p_listing:listing});if(value?.ok!==true||typeof value.available!=='boolean')throw Error('Enquiry availability could not be verified.');if(current())setAvailability(value);}if(session){const value=await client.rpc('inquiry_mine',{p_offset:offset});if(value?.ok!==true||!Array.isArray(value.threads)||(value.next_offset!==null&&!Number.isInteger(value.next_offset)))throw Error('Your enquiries could not be verified.');value.threads.forEach((t:any)=>inquiryThread(t));if(current()){setThreads(old=>offset?[...old,...value.threads.filter((t:any)=>!old.some(v=>v.id===t.id))]:value.threads);setNext(value.next_offset);setLoaded(true);}}};
 useEffect(()=>{run(()=>load());},[]);
 const start=()=>run(async()=>{const customer=await actor(client);if(!current())return;pending.current||={listing,customer,request:randomUUID(),subject:inquiryText(subject,120),body:inquiryText(body,4000)};const p=pending.current;const value=inquiryStartReceipt(await client.rpc('inquiry_start',{p_listing:p.listing,p_subject:p.subject,p_body:p.body,p_request:p.request}),p);if(current()){pending.current=null;setSubject('');setBody('');setSelected(value.id);}});
 return <ScrollView contentContainerStyle={s.content}><Action label="← Back" run={back}/><Text style={s.heading}>Your enquiries</Text><Text style={s.body}>Private conversations with businesses on Zoi. Check here for replies; email and push notifications are not sent.</Text>{selected&&session?<Conversation key={session.user.id+':'+selected} id={selected} back={()=>setSelected('')}/>:<>{busy?<ActivityIndicator/>:null}{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{!session?<Action label="Sign in to send and read enquiries" run={signIn}/>:null}<Action label="Refresh enquiries" disabled={busy} run={()=>run(()=>load())}/>{listing&&availability?<View style={s.panel}><Text style={s.title}>{availability.name||'Contact this business'}</Text>{availability.available&&session?<><TextInput accessibilityLabel="Enquiry subject" placeholder="Subject" value={subject} onChangeText={setSubject} maxLength={120} editable={!busy&&!pending.current} style={s.input}/><TextInput accessibilityLabel="New enquiry message" placeholder="How can the team help?" value={body} onChangeText={setBody} maxLength={4000} multiline editable={!busy&&!pending.current} style={[s.input,{minHeight:110}]}/><Action label={pending.current?'Retry same enquiry':'Send private enquiry'} disabled={busy||!subject.trim()||!body.trim()} run={start}/>{pending.current?<Text style={s.body}>An interrupted send may already have completed. Retry this same request to retrieve its receipt.</Text>:null}</>:!availability.available?<Text style={s.body}>This business has not enabled new enquiries. Existing conversations remain below.</Text>:null}</View>:null}{threads.map(t=><Action key={t.id} label={`${t.listing_name||'Business'} · ${t.subject} · ${t.status}`} run={()=>setSelected(t.id)}/>)}{session&&loaded&&!busy&&!error&&!threads.length?<Text style={s.body}>No enquiries yet.</Text>:null}{next!==null?<Action label="Load more enquiries" disabled={busy} run={()=>run(()=>load(next))}/>:null}</>}</ScrollView>;
}
export function InquiryInbox(){const {session,workspaceId}=useAuth();return session&&workspaceId?<Inbox key={session.user.id+':'+workspaceId} workspace={workspaceId}/>:null;}
function Inbox({workspace}:{workspace:string}){
 const {client,current,run,busy,error}=useScope();const [open,setOpen]=useState(false),[data,setData]=useState<any>(null),[filter,setFilter]=useState<string|null>(null),[selected,setSelected]=useState<any>(null),[status,setStatus]=useState('open'),[assignee,setAssignee]=useState<string|null>(null),[notice,setNotice]=useState('');
 const load=async(offset=0,nextFilter=filter)=>{const value=await client.rpc('inquiry_inbox',{p_workspace:workspace,p_status:nextFilter,p_offset:offset});if(value?.ok!==true||!['owner','admin','editor'].includes(value.role)||!['threads','listings','members'].every(k=>Array.isArray(value[k]))||(value.next_offset!==null&&!Number.isInteger(value.next_offset)))throw Error('Only workspace owners, admins and editors can access the enquiry inbox.');value.threads.forEach((t:any)=>inquiryThread(t,{workspace}));if(current())setData((old:any)=>offset&&old?{...value,threads:[...old.threads,...value.threads.filter((t:any)=>!old.threads.some((v:any)=>v.id===t.id))]}:value);};
 const settings=(row:any)=>run(async()=>{const value=await client.rpc('inquiry_settings_save',{p_workspace:workspace,p_listing:row.id,p_enabled:!row.enabled,p_expected_version:row.version||0});const result=value?.settings;if(value?.ok!==true||result?.workspace_id!==workspace||result.listing_id!==row.id||result.enabled!==!row.enabled||result.version!==(row.version||0)+1)throw Error('The enquiry setting was not confirmed. Refresh before retrying.');if(current())setNotice(result.enabled?'New customer enquiries enabled.':'New customer enquiries disabled.');await load();});
 const update=()=>run(async()=>{const value=await client.rpc('inquiry_update',{p_workspace:workspace,p_thread:selected.id,p_expected_version:selected.version,p_status:status,p_assignee:assignee});if(value?.ok!==true)throw Error('The inbox update was not confirmed.');const row=inquiryThread(value.thread,{id:selected.id,workspace});if(row.version!==selected.version+1||row.status!==status||row.assignee_id!==assignee)throw Error('The update receipt did not match your changes.');if(current()){setSelected(row);setNotice('Enquiry status and assignment saved.');}await load();});
 return <View style={s.panel}><Text style={s.title}>Customer enquiry inbox</Text><Text style={s.body}>Receive private enquiries, reply as your business team and track responsibility.</Text><Action label={open?'Hide enquiry inbox':'Open enquiry inbox'} disabled={busy} run={()=>{setOpen(v=>!v);if(!open&&!data)run(()=>load());}}/>{open?<>{busy?<ActivityIndicator/>:null}{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{notice?<Text accessibilityLiveRegion="polite" style={s.body}>{notice}</Text>:null}{data?<><Action label="Refresh inbox" disabled={busy} run={()=>run(()=>load())}/>{['owner','admin'].includes(data.role)?<><Text style={s.title}>Business contact settings</Text>{data.listings.map((row:any)=><Action key={row.id} label={(row.enabled?'Disable':'Enable')+' enquiries · '+row.name} disabled={busy} run={()=>settings(row)}/>)}</>:null}<View style={s.row}>{[null,'open','waiting','resolved'].map(value=><Action key={value||'all'} label={(filter===value?'● ':'')+(value||'All enquiries')} disabled={busy} run={()=>{setFilter(value);run(()=>load(0,value));}}/>)}</View>{data.threads.map((row:any)=><Action key={row.id} label={`${row.subject} · ${row.status}`} disabled={busy} run={()=>{setSelected(row);setStatus(row.status);setAssignee(row.assignee_id);}}/>)}{data.next_offset!==null?<Action label="Load more inbox enquiries" disabled={busy} run={()=>run(()=>load(data.next_offset))}/>:null}{selected?<><Text style={s.title}>Status & assignment</Text><View style={s.row}>{['open','waiting','resolved'].map(value=><Action key={value} label={(status===value?'● ':'')+value} disabled={busy} run={()=>setStatus(value)}/>)}</View><Action label={(assignee===null?'● ':'')+'Unassigned'} disabled={busy} run={()=>setAssignee(null)}/>{data.members.map((m:any)=><Action key={m.profile_id} label={(assignee===m.profile_id?'● ':'')+(m.display_name||m.profile_id)} disabled={busy} run={()=>setAssignee(m.profile_id)}/>)}<Action label="Save status and assignment" disabled={busy} run={update}/><Conversation key={selected.id} id={selected.id} workspace={workspace} status={selected.status} onThread={row=>{setSelected(row);setStatus(row.status);setAssignee(row.assignee_id);}} back={()=>setSelected(null)}/></>:null}{!data.threads.length?<Text style={s.body}>No enquiries match this filter.</Text>:null}</>:null}</>:null}</View>;
}
const s=StyleSheet.create({content:{padding:22,gap:16,paddingBottom:36},panel:{padding:18,gap:12,borderWidth:1,borderColor:'#DFE6EB',backgroundColor:'#fff',borderRadius:16},heading:{fontSize:30,fontWeight:'700',color:'#132F46'},title:{fontSize:20,fontWeight:'700',color:'#132F46'},label:{fontSize:13,fontWeight:'700',color:'#132F46'},body:{fontSize:14,lineHeight:22,color:'#60717E'},small:{fontSize:12,lineHeight:19,color:'#60717E'},input:{minHeight:46,padding:12,borderWidth:1,borderColor:'#CAD7E0',borderRadius:10,color:'#132F46'},action:{minHeight:44,padding:12,backgroundColor:'#EAF4FB',borderRadius:10,justifyContent:'center'},link:{color:'#116CBA',fontWeight:'700'},error:{color:'#963624'},row:{flexDirection:'row',flexWrap:'wrap',gap:8},message:{padding:12,gap:8,borderLeftWidth:3,borderLeftColor:'#D9B26A',backgroundColor:'#F7F9FA'}});
