import {useEffect,useRef,useState} from 'react';
import {Linking,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {useAuth} from './Auth';
import {currentPareaGroup,currentInvitationPreview,guestEventHostLink,ownPareaGroups,privateEventInvitation,scopedEventHostRpc} from './eventHostLink';
const money=(cents:number,currency:string)=>new Intl.NumberFormat('en',{style:'currency',currency,currencyDisplay:'code'}).format(cents/100);
export function NativePareaHandoff({eventId}:{eventId:string}){
 const {client,session,workspaceId}=useAuth();const actor=session?.user.id||'',scope=useRef({actor,eventId,workspaceId});scope.current={actor,eventId,workspaceId};
 const captured=useRef({actor,eventId,workspaceId}).current,alive=useRef(true),working=useRef(false);
 const [groups,setGroups]=useState<Awaited<ReturnType<typeof ownPareaGroups>>|null>(null),[link,setLink]=useState(''),[preview,setPreview]=useState<ReturnType<typeof currentInvitationPreview>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{alive.current=false;},[]);
 const current=()=>alive.current&&scope.current.actor===captured.actor&&scope.current.eventId===captured.eventId&&scope.current.workspaceId===captured.workspaceId&&client.session?.user.id===captured.actor;
 const check=()=>{if(!current())throw Error('The account or event view changed.');};
 const rpc=(name:string,args:Record<string,unknown>)=>scopedEventHostRpc(client,captured.actor,current,name,args);
 const act=async(fn:()=>Promise<void>)=>{if(working.current||!current())return;working.current=true;setBusy(true);setError('');try{await fn();}catch{if(current()){setGroups(null);setPreview(null);setLink('');setError('This group or invitation could not be verified. Refresh your account and check the selected event.');}}finally{working.current=false;if(current())setBusy(false);}};
 const load=()=>act(async()=>{setGroups(null);const rows=await ownPareaGroups(eventId,rpc);check();setGroups(rows);});
 const inspect=()=>act(async()=>{setPreview(null);const parsed=privateEventInvitation(link,eventId),value=await rpc('event_host_claim_preview',{p_token:parsed.token});check();setPreview(currentInvitationPreview(value,eventId));});
 const openInvitation=()=>act(async()=>{const parsed=privateEventInvitation(link,eventId);const fresh=currentInvitationPreview(await rpc('event_host_claim_preview',{p_token:parsed.token}),eventId);check();if(!preview||JSON.stringify(fresh)!==JSON.stringify(preview))throw Error('Invitation details changed. Review again.');setLink('');setPreview(null);await Linking.openURL(parsed.url);});
 const openGroup=(id:string)=>act(async()=>{const me=await rpc('zoi_me',{}),value=await rpc('event_host_get',{p_allocation:id});check();const fresh=currentPareaGroup(value,eventId,me?.profile?.id||'');if(fresh.id!==id||!fresh.active)throw Error('Allocation unavailable');check();await Linking.openURL(guestEventHostLink(eventId));});
 const button=(label:string,run:()=>void,disabled=false)=><Pressable accessibilityRole="button" accessibilityState={{disabled:busy||disabled}} disabled={busy||disabled} onPress={run} style={[s.button,(busy||disabled)&&s.disabled]}><Text style={s.action}>{label}</Text></Pressable>;
 return <View style={s.card}><Text style={s.title}>Get your parea ready</Text><Text style={s.text}>Review your current group quantities, or check a private invitation before opening it in your browser.</Text>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{button(busy?'Checking current details…':'Refresh my parea allocations',load)}{groups?.length===0?<Text style={s.text}>No host allocations were returned for this account and event. A personal invitation can still be reviewed below.</Text>:null}{groups?.map(g=><View key={g.id} style={s.group}><Text style={s.heading}>{g.label}</Text><Text style={s.text}>{g.quota} allocated · {g.accepted} accepted · {g.waiting} awaiting acceptance · {g.unassigned} unassigned</Text><Text style={s.text}>{money(g.unitPrice,g.currency)} per guest · expires {new Date(g.expires).toLocaleString()}</Text><Text style={s.text}>{g.active?'These are invitation quantities, not paid tickets.':'This allocation is no longer active.'}</Text>{g.active?button('Open this event’s host tools in browser ↗',()=>openGroup(g.id)):null}</View>)}<Text style={s.heading}>Received a private invitation?</Text><TextInput accessibilityLabel="Private Zoi invitation link" value={link} onChangeText={value=>{setLink(value);setPreview(null);setError('');}} editable={!busy} autoCapitalize="none" autoCorrect={false} textContentType="none" secureTextEntry style={s.input} placeholder="Paste your private invitation"/>{button('Check this invitation',inspect,!link.trim())}{preview?<View style={s.group}><Text style={s.heading}>{preview.event} · {preview.table}</Text><Text style={s.text}>{preview.quantity} tickets · {money(preview.quantity*preview.unitPrice,preview.currency)} allocation amount</Text><Text style={s.text}>Expires {new Date(preview.expires).toLocaleString()}. {preview.status==='accepted'?'Already accepted by this account.':'Review and accept in the browser.'}</Text><Text style={s.text}>No payment collected or admission issued. The browser shows only payment arrangements currently enabled by the organiser.</Text>{button('Open my private invitation in browser ↗',openInvitation)}</View>:null}<Text style={s.small}>Browser sign-in is separate. Host tools open this event; select your group there. No native editing, sending or payment happens here. Private links are kept only in this open view and cleared after handoff.</Text></View>;
}
const s=StyleSheet.create({card:{padding:20,borderRadius:18,borderWidth:1,borderColor:'#D6E3ED',backgroundColor:'#F3F9FD',gap:14},title:{fontSize:23,fontWeight:'700',color:'#132F46'},heading:{fontSize:17,fontWeight:'700',color:'#132F46'},text:{fontSize:14,lineHeight:22,color:'#425A6D'},small:{fontSize:12,lineHeight:19,color:'#526A7B'},group:{padding:14,borderRadius:14,backgroundColor:'#fff',gap:10},button:{minHeight:44,padding:12,borderRadius:10,backgroundColor:'#E1EFF9',justifyContent:'center'},action:{fontSize:14,fontWeight:'700',color:'#116CBA'},disabled:{opacity:.5},input:{minHeight:48,padding:12,borderRadius:10,borderWidth:1,borderColor:'#9DB8CB',backgroundColor:'#fff',color:'#132F46'},error:{fontSize:14,lineHeight:22,color:'#963624'}});
