import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth, operationsRequestStore } from './Auth';
import {randomUUID} from 'expo-crypto';
import {createOperationsRecovery,operationsDenied} from '../../assets/operations/recovery.mjs';
import { canWrite, linkedWorkForm, isOpsRecord, recordPayload, toForm, type OpsRecord, type RecordKind } from './operations';
import {organizationRpc,projectDocumentsLink} from './organizationWorkflow';
const sections: [RecordKind, string][] = [['company', 'Company'], ['contact', 'Contacts'], ['project', 'Projects & matters'], ['task', 'Tasks']];
function Action({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={[s.action, disabled && { opacity: 0.5 }]}><Text style={s.actionText}>{label}</Text></Pressable>; }
export function OperationsPanel({ requestedRecordId }: { requestedRecordId?: string } = {}) {
  const { session, workspaceId } = useAuth();
  if (!session || !workspaceId) return null;
  return <WorkspaceOperations key={session.user.id + ':' + workspaceId} workspace={workspaceId} userId={session.user.id} requestedRecordId={requestedRecordId} />;
}
function WorkspaceOperations({ workspace, userId, requestedRecordId }: { workspace: string; userId: string; requestedRecordId?: string }) {
  const { client, workspaceId } = useAuth();
  const [records, setRecords] = useState<OpsRecord[]>([]); const [members, setMembers] = useState<{profile_id: string; display_name?: string; role?: string}[]>([]); const [role, setRole] = useState('viewer'); const [kind, setKind] = useState<RecordKind>('company'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [reload, setReload] = useState(0);
  const [editing, setEditing] = useState<OpsRecord | null | undefined>(undefined); const [form, setForm] = useState<Record<string, string>>(() => toForm()); const [saving, setSaving] = useState(false); const [confirmArchive, setConfirmArchive] = useState(''); const [audit, setAudit] = useState<{ id: string; action: string; version: number; created_at: string }[]>([]); const [auditLoading, setAuditLoading] = useState(false);
  const editingRef = useRef(editing?.id); editingRef.current = editing?.id;
  const alive = useRef(true); const busy = useRef(false); const workspaceRef = useRef(workspaceId); workspaceRef.current = workspaceId;
  const current = () => alive.current && client.session?.user.id === userId && workspaceRef.current === workspace;
  const [,rerender]=useState(0);const recoveryRef=useRef<ReturnType<typeof createOperationsRecovery>|null>(null);
  function clearPrivate(){setRecords([]);setMembers([]);setRole('viewer');setEditing(undefined);setForm(toForm());setAudit([]);setConfirmArchive('');setNotice('');recoveryRef.current?.dropPayload();}
  async function rpc(name:string,args:any){if(!current())throw Error('Operations account or workspace changed.');try{const value=await organizationRpc(client,userId,current,name,args);if(!current())throw Error('Operations account or workspace changed.');return value;}catch(e){if(current()&&operationsDenied(e))clearPrivate();throw e;}}
  if(!recoveryRef.current){const store=operationsRequestStore(workspace);recoveryRef.current=createOperationsRecovery({actor:userId,workspace,current,call:rpc,nonce:randomUUID,changed:()=>{if(current())rerender(n=>n+1);},storage:{load:()=>store.load(userId),save:(value:unknown)=>store.save(userId,value),clear:()=>store.clear(userId)}});}
  const recovery=recoveryRef.current;
  useEffect(()=>{recovery.load().catch((e:Error)=>{if(current())setError(e.message);});return()=>{alive.current=false;recovery.dropPayload();};},[]);
  const recovered=async(value:any)=>{if(!current())return;if(value.state==='missing'){setError('No saved receipt yet. Retry the exact change or cancel if unsaved before starting another.');return;}setEditing(undefined);setForm(toForm());setNotice(value.state==='saved'?'Change saved. Reference '+value.record_id+'.':'Unsaved change cancelled. A delayed request cannot save it.');setReload(n=>n+1);};
  const check=async(mode:string)=>{if(busy.current)return;busy.current=true;setSaving(true);setError('');try{if(mode==='load')await recovery.load();else await recovered(await recovery.recover(mode));}catch(e){if(current())setError(e instanceof Error?e.message:'Recovery could not be confirmed.');}finally{busy.current=false;if(current())setSaving(false);}};
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  useEffect(() => { let active = true; setLoading(true); setError(''); rpc('ops_records_list', { p_workspace: workspace, p_kind: null, p_include_archived: false }).then(result => {
    if (!result || result.ok !== true || !Array.isArray(result.records) || !result.records.every((row: unknown) => isOpsRecord(row, workspace))) throw new Error('Invalid records response');
    if (active && current()) { setRecords(result.records); setMembers(Array.isArray(result.members) ? result.members.filter((member: any) => typeof member.profile_id === 'string') : []); setRole(typeof result.role === 'string' ? result.role : 'viewer'); }
  }).catch(() => { if (active && current()) setError('Your operations workspace could not be loaded. No records have been changed.'); }).finally(() => { if (active && current()) setLoading(false); }); return () => { active = false; }; }, [workspace, reload, client]);
  const edit = (row?: OpsRecord) => { setEditing(row || null); setForm(toForm(row)); setAudit([]); setConfirmArchive(''); setError(''); setNotice(''); };
  const handledRequest = useRef('');
  useEffect(() => { if (!requestedRecordId || handledRequest.current === requestedRecordId || loading || saving) return; const row = records.find(record => record.id === requestedRecordId); handledRequest.current = requestedRecordId; if (row) { setKind(row.kind); edit(row); } else setError('The priority record is no longer in your active workspace records.'); }, [requestedRecordId, records, loading, saving]);
  const save = async () => {
    if (busy.current || recovery.state().blocked || !canWrite(role, kind) || editing === undefined) return;
    let payload; try { payload = recordPayload(form, editing || undefined, kind); } catch (e) { setError(e instanceof Error ? e.message : 'Check the form.'); return; }
    busy.current = true; setSaving(true); setError(''); setNotice('');
    try {await recovered(await recovery.send('save',{p_kind:kind,p_data:payload,p_id:editing?.id||null,p_expected_version:editing?.version||0}));}
    catch (e) { if (current()) setError(e instanceof Error ? e.message + ' Check the previous request before saving another.' : 'Save could not be confirmed. Your form is preserved.'); }
    finally { busy.current = false; if (current()) setSaving(false); }
  };
  const archive = async (row: OpsRecord) => {
    if (busy.current || recovery.state().blocked || !['owner', 'admin'].includes(role)) return;
    if (confirmArchive !== row.id) { setConfirmArchive(row.id); return; }
    busy.current = true; setSaving(true); setError('');
    try {await recovered(await recovery.send('archive',{p_id:row.id,p_expected_version:row.version}));}
    catch (e) { if (current()) setError(e instanceof Error ? e.message : 'Archive could not be confirmed.'); }
    finally { busy.current = false; if (current()) setSaving(false); }
  };
  const history = async (row: OpsRecord) => { if (auditLoading) return; setAuditLoading(true); setError(''); try { const result = await rpc('ops_audit_list', { p_workspace: workspace, p_record: row.id, p_limit: 20 }); if (!result?.ok || !Array.isArray(result.events) || !result.events.every((event: any) => event.workspace_id === workspace && event.record_id === row.id)) throw new Error(); if (current() && editingRef.current === row.id) setAudit(result.events); } catch { if (current()) setError('Change history could not be loaded.'); } finally { if (current()) setAuditLoading(false); } };
  const startLinked = (row:OpsRecord) => {if(!current()||saving||recovery.state().blocked)return;try{const next=linkedWorkForm(row,workspace);if(!canWrite(role,next.kind))return;setKind(next.kind);setEditing(null);setForm(next.form);setAudit([]);setNotice('Linked to '+row.title+'. Review and save the new record.');setError('');}catch(e){setError(e instanceof Error?e.message:'Linked work is unavailable.');}};
  const openProjectDocuments=async(row:OpsRecord)=>{if(busy.current||!current())return;busy.current=true;setSaving(true);setError('');try{const url=await projectDocumentsLink({workspace,project:row.id,current,rpc});if(!current())return;await Linking.openURL(url);if(current())setNotice('Opened this project’s documents on the website. Sign in there with an authorized account; this app did not share your session.');}catch(e){if(current())setError(e instanceof Error?e.message:'Project documents could not open.');}finally{busy.current=false;if(current())setSaving(false);}};
  const fields: [string, string][] = [['title', kind === 'company' ? 'Company display name' : kind === 'contact' ? 'Contact name' : 'Title'], ...(kind === 'company' ? [['legal_name', 'Legal name'], ['jurisdiction', 'Jurisdiction'], ['registration_number', 'Registration number']] as [string, string][] : []), ...(kind === 'company' || kind === 'contact' ? [['website', 'Website'], ['email', 'Email'], ['phone', 'Phone']] as [string, string][] : []), ['notes', 'Notes'], ['due_at', 'Due date · YYYY-MM-DD (UTC)']];
  const editable = canWrite(role, kind)&&!recovery.state().blocked;
  return <View style={s.panel}><Text style={s.kicker}>YOUR BUSINESS, ORGANISED</Text><Text style={s.title}>Operations workspace</Text><Text style={s.body}>Company records, contacts, projects and tasks for your selected workspace.</Text><Text style={s.small}>Company records help you stay organised; saving a record does not register a business or submit a filing.</Text>
    {!recovery.state().ready?<Action label="Load Operations recovery reference" disabled={saving} onPress={()=>{void check('load');}}/>:null}{recovery.state().marker?<View style={s.form}><Text style={s.body}>Check your previous change before saving another. Private record content is not stored on this device.</Text><Action label="Check saved Operations receipt" disabled={saving} onPress={()=>{void check('check');}}/>{recovery.state().payload?<Action label="Retry exact Operations change" disabled={saving} onPress={()=>{void check('retry');}}/>:null}<Action label="Cancel Operations change if not saved" disabled={saving} onPress={()=>{void check('cancel');}}/></View>:null}
    <View style={s.row}>{sections.map(([value, label]) => <Action key={value} disabled={saving} label={(kind === value ? '● ' : '') + label} onPress={() => { setKind(value); setEditing(undefined); setAudit([]); setConfirmArchive(''); }} />)}</View>
    {loading ? <ActivityIndicator color="#116CBA" /> : null}{error ? <Text style={s.error} accessibilityRole="alert">{error}</Text> : null}{notice ? <Text style={s.body} accessibilityLiveRegion="polite">{notice}</Text> : null}
    <View style={s.row}><Action label="Reload records" disabled={saving || loading} onPress={() => setReload(v => v + 1)} />{editable ? <Action label="New record" disabled={saving || loading} onPress={() => edit()} /> : <Text style={s.small}>{canWrite(role,kind)?'Resolve the previous change or load its recovery reference before editing.':'Your role has read-only access to this section.'}</Text>}</View>
    {!loading && !records.filter(row => row.kind === kind).length && !error ? <Text style={s.body}>No {sections.find(([id]) => id === kind)?.[1].toLowerCase()} records yet.</Text> : null}
    {records.filter(row => row.kind === kind).map(row => <Pressable key={row.id} accessibilityRole="button" disabled={saving} onPress={() => edit(row)} style={[s.record, editing?.id === row.id && s.recordSelected]}><Text style={s.heading}>{row.title}</Text><Text style={s.small}>{row.status.replaceAll('_', ' ')} · version {row.version}{row.due_at ? ' · due ' + row.due_at.slice(0, 10) : ''}</Text></Pressable>)}
    {editing !== undefined ? <View style={s.form}><Text style={s.heading}>{editing ? 'Record details' : 'New record'}</Text>{fields.map(([key, label]) => <View key={key} style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={form[key] || ''} onChangeText={value => setForm(previous => ({ ...previous, [key]: value }))} editable={editable && !saving} multiline={key === 'notes'} maxLength={key === 'notes' ? 20000 : key === 'title' ? 200 : 500} autoCapitalize={['email', 'website'].includes(key) ? 'none' : 'sentences'} style={[s.input, key === 'notes' && { minHeight: 100, textAlignVertical: 'top' }]} /></View>)}
      {kind === 'company' ? <><Text style={s.label}>Sector</Text><View style={s.row}>{['business','lawyer','church','restaurant','stylist','creator'].map(sector => <Action key={sector} disabled={!editable || saving} label={(form.sector === sector ? '● ' : '') + sector} onPress={() => setForm(previous => ({...previous,sector}))} />)}</View></> : null}
      <Text style={s.label}>Status</Text><View style={s.row}>{['open', 'in_progress', 'blocked', 'completed'].map(status => <Action key={status} disabled={!editable || saving} label={(form.status === status ? '● ' : '') + status.replaceAll('_', ' ')} onPress={() => setForm(previous => ({ ...previous, status }))} />)}</View>
      {(['company', 'project', 'contact'] as RecordKind[]).filter(relation => relation !== kind && !(kind === 'task' && relation === 'company')).map(relation => <View key={relation} style={s.field}><Text style={s.label}>Linked {relation}{(kind === 'project' && relation === 'company') || (kind === 'task' && relation === 'project') ? ' · required' : ''}</Text><View style={s.row}><Action disabled={!editable || saving} label={!form[relation + '_id'] ? '● None' : 'None'} onPress={() => setForm(previous => ({ ...previous, [relation + '_id']: '' }))} />{records.filter(row => row.kind === relation).map(row => <Action key={row.id} disabled={!editable || saving} label={(form[relation + '_id'] === row.id ? '● ' : '') + row.title} onPress={() => setForm(previous => ({ ...previous, [relation + '_id']: row.id }))} />)}</View></View>)}
      {kind === 'task' && members.length ? <View style={s.field}><Text style={s.label}>Assigned to</Text><View style={s.row}><Action disabled={!editable || saving} label={!form.assignee_profile_id ? '● Unassigned' : 'Unassigned'} onPress={() => setForm(previous => ({...previous,assignee_profile_id:''}))} />{members.map(member => <Action key={member.profile_id} disabled={!editable || saving} label={(form.assignee_profile_id === member.profile_id ? '● ' : '') + (member.display_name || 'Workspace member')} onPress={() => setForm(previous => ({...previous,assignee_profile_id:member.profile_id}))} />)}</View></View> : null}
      <View style={s.row}>{editable ? <Action label={saving ? 'Saving…' : 'Save record'} disabled={saving} onPress={save} /> : null}<Action label="Close details" disabled={saving} onPress={() => { setEditing(undefined); setConfirmArchive(''); }} />{editing ? <Action label={auditLoading ? 'Loading history…' : 'View change history'} disabled={auditLoading || saving} onPress={() => history(editing)} /> : null}{editing && ['owner', 'admin'].includes(role) ? <Action label={confirmArchive === editing.id ? 'Confirm archive' : 'Archive record'} disabled={saving||recovery.state().blocked} onPress={() => archive(editing)} /> : null}</View>
      {editing&&!editing.archived_at&&['contact','project'].includes(editing.kind)?<View style={s.record}><Text style={s.heading}>Continue this work</Text>{canWrite(role,editing.kind==='contact'?'project':'task')?<Action label={editing.kind==='contact'?'Start linked project':'Add follow-up task'} disabled={saving||recovery.state().blocked||JSON.stringify(form)!==JSON.stringify(toForm(editing))} onPress={()=>startLinked(editing)}/>:null}{editing.kind==='project'&&['owner','admin','editor'].includes(role)?<><Text style={s.small}>Project documents open on the website with this workspace and project. Browser sign-in is required. Save or discard edits before continuing.</Text><Action label="Open project documents on website" disabled={saving||recovery.state().blocked||JSON.stringify(form)!==JSON.stringify(toForm(editing))} onPress={()=>{void openProjectDocuments(editing);}}/></>:null}{records.filter(row=>!row.archived_at&&(editing.kind==='contact'?row.contact_id===editing.id:row.project_id===editing.id)).map(row=><Action key={row.id} label={'Open linked '+row.kind+' · '+row.title} disabled={saving||JSON.stringify(form)!==JSON.stringify(toForm(editing))} onPress={()=>{setKind(row.kind);edit(row);}}/>)}</View>:null}
      {audit.map(event => <View key={event.id} style={s.record}><Text style={s.body}>{event.action} · version {event.version}</Text><Text style={s.small}>{new Date(event.created_at).toLocaleString()}</Text></View>)}
    </View> : null}
  </View>;
}
const s = StyleSheet.create({ panel: { padding: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: '#DFE6EB', borderRadius: 18, gap: 16 }, kicker: { color: '#A77B32', fontSize: 10, letterSpacing: 2, fontWeight: '700' }, title: { color: '#132F46', fontSize: 25, fontWeight: '700' }, heading: { color: '#132F46', fontSize: 17, fontWeight: '700' }, body: { color: '#60717E', fontSize: 14, lineHeight: 23 }, small: { color: '#60717E', fontSize: 12, lineHeight: 19 }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, action: { backgroundColor: '#EAF4FB', padding: 12, minHeight: 44, borderRadius: 9, justifyContent: 'center' }, actionText: { color: '#116CBA', fontWeight: '600', fontSize: 12 }, record: { padding: 14, borderWidth: 1, borderColor: '#DFE6EB', borderRadius: 10, gap: 5 }, recordSelected: { borderColor: '#116CBA', backgroundColor: '#F1F7FB' }, field: { gap: 8 }, label: { color: '#132F46', fontWeight: '600', fontSize: 13 }, input: { minHeight: 46, borderWidth: 1, borderColor: '#CAD7E0', borderRadius: 10, padding: 12, color: '#132F46', fontSize: 15 }, form: { gap: 18, paddingTop: 12 }, error: { color: '#963624', fontSize: 14, lineHeight: 23 } });
