import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from './Auth';
import { assertOpsReceipt, canWrite, isOpsRecord, recordPayload, toForm, type OpsRecord, type RecordKind } from './operations';
const sections: [RecordKind, string][] = [['company', 'Company'], ['contact', 'Contacts'], ['project', 'Projects & matters'], ['task', 'Tasks']];
function Action({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={[s.action, disabled && { opacity: 0.5 }]}><Text style={s.actionText}>{label}</Text></Pressable>; }
export function OperationsPanel({ requestedRecordId }: { requestedRecordId?: string } = {}) {
  const { session, workspaceId } = useAuth();
  if (!session || !workspaceId) return null;
  return <WorkspaceOperations key={session.user.id + ':' + workspaceId} workspace={workspaceId} userId={session.user.id} requestedRecordId={requestedRecordId} />;
}
function WorkspaceOperations({ workspace, userId, requestedRecordId }: { workspace: string; userId: string; requestedRecordId?: string }) {
  const { client, workspaceId } = useAuth();
  const [records, setRecords] = useState<OpsRecord[]>([]); const [members, setMembers] = useState<{profile_id: string; display_name?: string; role?: string}[]>([]); const [role, setRole] = useState('viewer'); const [kind, setKind] = useState<RecordKind>('company'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [reload, setReload] = useState(0);
  const [editing, setEditing] = useState<OpsRecord | null | undefined>(undefined); const [form, setForm] = useState<Record<string, string>>(() => toForm()); const [saving, setSaving] = useState(false); const [confirmArchive, setConfirmArchive] = useState(''); const [audit, setAudit] = useState<{ id: string; action: string; version: number; created_at: string }[]>([]); const [auditLoading, setAuditLoading] = useState(false);
  const editingRef = useRef(editing?.id); editingRef.current = editing?.id;
  const alive = useRef(true); const busy = useRef(false); const workspaceRef = useRef(workspaceId); workspaceRef.current = workspaceId;
  const current = () => alive.current && client.session?.user.id === userId && workspaceRef.current === workspace;
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  useEffect(() => { let active = true; setLoading(true); setError(''); client.rpc('ops_records_list', { p_workspace: workspace, p_kind: null, p_include_archived: false }).then(result => {
    if (!result || result.ok !== true || !Array.isArray(result.records) || !result.records.every((row: unknown) => isOpsRecord(row, workspace))) throw new Error('Invalid records response');
    if (active && current()) { setRecords(result.records); setMembers(Array.isArray(result.members) ? result.members.filter((member: any) => typeof member.profile_id === 'string') : []); setRole(typeof result.role === 'string' ? result.role : 'viewer'); }
  }).catch(() => { if (active && current()) setError('Your operations workspace could not be loaded. No records have been changed.'); }).finally(() => { if (active && current()) setLoading(false); }); return () => { active = false; }; }, [workspace, reload, client]);
  const edit = (row?: OpsRecord) => { setEditing(row || null); setForm(toForm(row)); setAudit([]); setConfirmArchive(''); setError(''); setNotice(''); };
  const handledRequest = useRef('');
  useEffect(() => { if (!requestedRecordId || handledRequest.current === requestedRecordId || loading || saving) return; const row = records.find(record => record.id === requestedRecordId); handledRequest.current = requestedRecordId; if (row) { setKind(row.kind); edit(row); } else setError('The priority record is no longer in your active workspace records.'); }, [requestedRecordId, records, loading, saving]);
  const save = async () => {
    if (busy.current || !canWrite(role, kind) || editing === undefined) return;
    let payload; try { payload = recordPayload(form, editing || undefined, kind); } catch (e) { setError(e instanceof Error ? e.message : 'Check the form.'); return; }
    busy.current = true; setSaving(true); setError(''); setNotice('');
    try { const result = await client.rpc('ops_record_save', { p_workspace: workspace, p_kind: kind, p_data: payload, p_id: editing?.id || null, p_expected_version: editing?.version || 0 }); const saved = assertOpsReceipt(result, workspace, kind, editing || undefined); if (!current()) return; setRecords(rows => [saved, ...rows.filter(row => row.id !== saved.id)]); setEditing(saved); setForm(toForm(saved)); setNotice('Record saved. Version ' + saved.version + '.'); }
    catch (e) { if (current()) setError(e instanceof Error ? e.message + ' Your form is preserved. Reload records and reopen the record before retrying an uncertain save.' : 'Save could not be confirmed. Your form is preserved.'); }
    finally { busy.current = false; if (current()) setSaving(false); }
  };
  const archive = async (row: OpsRecord) => {
    if (busy.current || !['owner', 'admin'].includes(role)) return;
    if (confirmArchive !== row.id) { setConfirmArchive(row.id); return; }
    busy.current = true; setSaving(true); setError('');
    try { const result = await client.rpc('ops_record_archive', { p_workspace: workspace, p_id: row.id, p_expected_version: row.version }); const saved = assertOpsReceipt(result, workspace, row.kind, row); if (!saved.archived_at) throw new Error('Archive was not confirmed.'); if (!current()) return; setRecords(rows => rows.filter(item => item.id !== row.id)); setEditing(undefined); setConfirmArchive(''); setNotice('Record archived.'); }
    catch (e) { if (current()) setError(e instanceof Error ? e.message : 'Archive could not be confirmed.'); }
    finally { busy.current = false; if (current()) setSaving(false); }
  };
  const history = async (row: OpsRecord) => { if (auditLoading) return; setAuditLoading(true); setError(''); try { const result = await client.rpc('ops_audit_list', { p_workspace: workspace, p_record: row.id, p_limit: 20 }); if (!result?.ok || !Array.isArray(result.events) || !result.events.every((event: any) => event.workspace_id === workspace && event.record_id === row.id)) throw new Error(); if (current() && editingRef.current === row.id) setAudit(result.events); } catch { if (current()) setError('Change history could not be loaded.'); } finally { if (current()) setAuditLoading(false); } };
  const fields: [string, string][] = [['title', kind === 'company' ? 'Company display name' : kind === 'contact' ? 'Contact name' : 'Title'], ...(kind === 'company' ? [['legal_name', 'Legal name'], ['jurisdiction', 'Jurisdiction'], ['registration_number', 'Registration number']] as [string, string][] : []), ...(kind === 'company' || kind === 'contact' ? [['website', 'Website'], ['email', 'Email'], ['phone', 'Phone']] as [string, string][] : []), ['notes', 'Notes'], ['due_at', 'Due date · YYYY-MM-DD (UTC)']];
  const editable = canWrite(role, kind);
  return <View style={s.panel}><Text style={s.kicker}>YOUR BUSINESS, ORGANISED</Text><Text style={s.title}>Operations workspace</Text><Text style={s.body}>Company records, contacts, projects and tasks for your selected workspace.</Text><Text style={s.small}>Company records help you stay organised; saving a record does not register a business or submit a filing.</Text>
    <View style={s.row}>{sections.map(([value, label]) => <Action key={value} disabled={saving} label={(kind === value ? '● ' : '') + label} onPress={() => { setKind(value); setEditing(undefined); setAudit([]); setConfirmArchive(''); }} />)}</View>
    {loading ? <ActivityIndicator color="#116CBA" /> : null}{error ? <Text style={s.error} accessibilityRole="alert">{error}</Text> : null}{notice ? <Text style={s.body} accessibilityLiveRegion="polite">{notice}</Text> : null}
    <View style={s.row}><Action label="Reload records" disabled={saving || loading} onPress={() => setReload(v => v + 1)} />{editable ? <Action label="New record" disabled={saving || loading} onPress={() => edit()} /> : <Text style={s.small}>Your role has read-only access to this section.</Text>}</View>
    {!loading && !records.filter(row => row.kind === kind).length && !error ? <Text style={s.body}>No {sections.find(([id]) => id === kind)?.[1].toLowerCase()} records yet.</Text> : null}
    {records.filter(row => row.kind === kind).map(row => <Pressable key={row.id} accessibilityRole="button" disabled={saving} onPress={() => edit(row)} style={[s.record, editing?.id === row.id && s.recordSelected]}><Text style={s.heading}>{row.title}</Text><Text style={s.small}>{row.status.replaceAll('_', ' ')} · version {row.version}{row.due_at ? ' · due ' + row.due_at.slice(0, 10) : ''}</Text></Pressable>)}
    {editing !== undefined ? <View style={s.form}><Text style={s.heading}>{editing ? 'Record details' : 'New record'}</Text>{fields.map(([key, label]) => <View key={key} style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={form[key] || ''} onChangeText={value => setForm(previous => ({ ...previous, [key]: value }))} editable={editable && !saving} multiline={key === 'notes'} maxLength={key === 'notes' ? 20000 : key === 'title' ? 200 : 500} autoCapitalize={['email', 'website'].includes(key) ? 'none' : 'sentences'} style={[s.input, key === 'notes' && { minHeight: 100, textAlignVertical: 'top' }]} /></View>)}
      {kind === 'company' ? <><Text style={s.label}>Sector</Text><View style={s.row}>{['business','lawyer','church','restaurant','stylist','creator'].map(sector => <Action key={sector} disabled={!editable || saving} label={(form.sector === sector ? '● ' : '') + sector} onPress={() => setForm(previous => ({...previous,sector}))} />)}</View></> : null}
      <Text style={s.label}>Status</Text><View style={s.row}>{['open', 'in_progress', 'blocked', 'completed'].map(status => <Action key={status} disabled={!editable || saving} label={(form.status === status ? '● ' : '') + status.replaceAll('_', ' ')} onPress={() => setForm(previous => ({ ...previous, status }))} />)}</View>
      {(['company', 'project', 'contact'] as RecordKind[]).filter(relation => relation !== kind && !(kind === 'task' && relation === 'company')).map(relation => <View key={relation} style={s.field}><Text style={s.label}>Linked {relation}{(kind === 'project' && relation === 'company') || (kind === 'task' && relation === 'project') ? ' · required' : ''}</Text><View style={s.row}><Action disabled={!editable || saving} label={!form[relation + '_id'] ? '● None' : 'None'} onPress={() => setForm(previous => ({ ...previous, [relation + '_id']: '' }))} />{records.filter(row => row.kind === relation).map(row => <Action key={row.id} disabled={!editable || saving} label={(form[relation + '_id'] === row.id ? '● ' : '') + row.title} onPress={() => setForm(previous => ({ ...previous, [relation + '_id']: row.id }))} />)}</View></View>)}
      {kind === 'task' && members.length ? <View style={s.field}><Text style={s.label}>Assigned to</Text><View style={s.row}><Action disabled={!editable || saving} label={!form.assignee_profile_id ? '● Unassigned' : 'Unassigned'} onPress={() => setForm(previous => ({...previous,assignee_profile_id:''}))} />{members.map(member => <Action key={member.profile_id} disabled={!editable || saving} label={(form.assignee_profile_id === member.profile_id ? '● ' : '') + (member.display_name || 'Workspace member')} onPress={() => setForm(previous => ({...previous,assignee_profile_id:member.profile_id}))} />)}</View></View> : null}
      <View style={s.row}>{editable ? <Action label={saving ? 'Saving…' : 'Save record'} disabled={saving} onPress={save} /> : null}<Action label="Close details" disabled={saving} onPress={() => { setEditing(undefined); setConfirmArchive(''); }} />{editing ? <Action label={auditLoading ? 'Loading history…' : 'View change history'} disabled={auditLoading || saving} onPress={() => history(editing)} /> : null}{editing && ['owner', 'admin'].includes(role) ? <Action label={confirmArchive === editing.id ? 'Confirm archive' : 'Archive record'} disabled={saving} onPress={() => archive(editing)} /> : null}</View>
      {audit.map(event => <View key={event.id} style={s.record}><Text style={s.body}>{event.action} · version {event.version}</Text><Text style={s.small}>{new Date(event.created_at).toLocaleString()}</Text></View>)}
    </View> : null}
  </View>;
}
const s = StyleSheet.create({ panel: { padding: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: '#DFE6EB', borderRadius: 18, gap: 16 }, kicker: { color: '#A77B32', fontSize: 10, letterSpacing: 2, fontWeight: '700' }, title: { color: '#132F46', fontSize: 25, fontWeight: '700' }, heading: { color: '#132F46', fontSize: 17, fontWeight: '700' }, body: { color: '#60717E', fontSize: 14, lineHeight: 23 }, small: { color: '#60717E', fontSize: 12, lineHeight: 19 }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, action: { backgroundColor: '#EAF4FB', padding: 12, minHeight: 44, borderRadius: 9, justifyContent: 'center' }, actionText: { color: '#116CBA', fontWeight: '600', fontSize: 12 }, record: { padding: 14, borderWidth: 1, borderColor: '#DFE6EB', borderRadius: 10, gap: 5 }, recordSelected: { borderColor: '#116CBA', backgroundColor: '#F1F7FB' }, field: { gap: 8 }, label: { color: '#132F46', fontWeight: '600', fontSize: 13 }, input: { minHeight: 46, borderWidth: 1, borderColor: '#CAD7E0', borderRadius: 10, padding: 12, color: '#132F46', fontSize: 15 }, form: { gap: 18, paddingTop: 12 }, error: { color: '#963624', fontSize: 14, lineHeight: 23 } });
