import{LIGHT}from'./brand';
import {type ReactNode,useEffect,useRef,useState} from 'react';
import {AccessibilityInfo,Animated,Platform,StyleSheet,View} from 'react-native';
import {BlurTargetView,BlurView} from 'expo-blur';
import {LinearGradient} from 'expo-linear-gradient';
import * as Battery from 'expo-battery';
export function usePresentationPreferences(){const [reduceMotion,setMotion]=useState(true),[reduceTransparency,setTransparency]=useState(true),[lowPower,setLowPower]=useState(true);useEffect(()=>{let alive=true;AccessibilityInfo.isReduceMotionEnabled().then(v=>{if(alive)setMotion(v);}).catch(()=>{});const media=Platform.OS==='web'&&typeof matchMedia==='function'?matchMedia('(prefers-reduced-transparency: reduce)'):null;const transparencyChanged=()=>setTransparency(media?.matches||false);if(Platform.OS==='web'){transparencyChanged();media?.addEventListener('change',transparencyChanged);}else AccessibilityInfo.isReduceTransparencyEnabled?.().then(v=>{if(alive)setTransparency(v);}).catch(()=>{});if(Platform.OS==='web'){setLowPower(!!(globalThis.navigator as any)?.connection?.saveData);}else Battery.getPowerStateAsync().then(v=>{if(alive)setLowPower(v.lowPowerMode);}).catch(()=>{});const motion=AccessibilityInfo.addEventListener('reduceMotionChanged',setMotion),transparency=AccessibilityInfo.addEventListener('reduceTransparencyChanged',setTransparency),power=Platform.OS==='web'?null:Battery.addLowPowerModeListener(v=>setLowPower(v.lowPowerMode));return()=>{alive=false;motion?.remove();transparency?.remove();media?.removeEventListener('change',transparencyChanged);power?.remove();};},[]);return {motion:!reduceMotion&&!lowPower,glass:!reduceTransparency&&!lowPower};}
export function GlassHero({children}:{children:ReactNode}){const target=useRef<View|null>(null),preferences=usePresentationPreferences();return <View style={s.hero}><BlurTargetView ref={target} style={StyleSheet.absoluteFill}><LinearGradient colors={[LIGHT.background,LIGHT.surface,LIGHT.surfaceRaised]} start={{x:0,y:0}} end={{x:1,y:1}} style={StyleSheet.absoluteFill}/><View style={s.orbitOne}/><View style={s.orbitTwo}/><View style={s.goldLine}/></BlurTargetView><View pointerEvents="none" style={StyleSheet.absoluteFill}>{preferences.glass?<BlurView blurTarget={target} blurMethod="dimezisBlurViewSdk31Plus" intensity={18} tint="light" style={StyleSheet.absoluteFill}/>:null}</View><View style={s.heroContent}>{children}</View><View pointerEvents="none" style={s.glassEdge}>{preferences.glass?<BlurView blurTarget={target} blurMethod="dimezisBlurViewSdk31Plus" intensity={30} tint="light" style={StyleSheet.absoluteFill}/>:<View style={[StyleSheet.absoluteFill,{backgroundColor:LIGHT.surfaceRaised}]}/>}</View></View>;}
export function Reveal({children,trigger}:{children:ReactNode;trigger:string}){const {motion}=usePresentationPreferences(),progress=useRef(new Animated.Value(1)).current,previous=useRef(trigger);useEffect(()=>{const changed=previous.current!==trigger;previous.current=trigger;if(!motion||!changed){progress.setValue(1);return;}progress.setValue(0);const animation=Animated.timing(progress,{toValue:1,duration:220,useNativeDriver:Platform.OS!=='web'});animation.start();return()=>animation.stop();},[trigger,motion]);return <Animated.View style={{flex:1,opacity:progress,transform:[{translateY:progress.interpolate({inputRange:[0,1],outputRange:[6,0]})}]}}>{children}</Animated.View>;}
const s=StyleSheet.create({hero:{borderRadius:28,overflow:'hidden',borderWidth:1,borderColor:LIGHT.surface,backgroundColor:LIGHT.surfaceRaised,boxShadow:'0 14px 35px rgba(38,49,43,0.07)'},heroContent:{padding:28,paddingBottom:36,gap:22},orbitOne:{position:'absolute',width:210,height:210,borderRadius:110,borderWidth:1,borderColor:LIGHT.line,right:-95,top:70},orbitTwo:{position:'absolute',width:280,height:280,borderRadius:150,borderWidth:1,borderColor:LIGHT.line,right:-130,top:35},goldLine:{position:'absolute',width:180,height:2,backgroundColor:LIGHT.gold,right:-25,bottom:58,transform:[{rotate:'-35deg'}]},glassEdge:{height:12,position:'absolute',bottom:0,left:0,right:0,overflow:'hidden',borderTopWidth:1,borderTopColor:'#FFFFFFAA'}});
