import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { useAuth } from './Auth';
import { prioritize } from '../../assets/priorities/engine.mjs';
import { loadSources } from '../../assets/priorities/sources.mjs';
import { OperationsPanel } from './Operations';
import { BookingOperator } from './BookingOperator';
function Action({label,run,disabled=false}:{label:string;run:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={run} style={[s.action,disabled&&{opacity:.5}]}><Text style={s.link}>{label}</Text></Pressable>;}
export function PrioritiesPanel(){const {session,workspaceId}=useAuth();return session&&workspaceId?<EvidencePriorities key={session.user.id+':'+workspaceId}/>:null;}
function EvidencePriorities(){const {client,session,workspaceId}=useAuth();const user=session!.user.id;const [sources,setSources]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[clock,setClock]=useState(Date.now()),[details,setDetails]=useState(''),[review,setReview]=useState<any>(null);const alive=useRef(true),working=useRef(false);const current=()=>alive.current&&client.session?.user.id===user;useEffect(()=>{alive.current=true;const timer=setInterval(()=>setClock(Date.now()),60000);return()=>{alive.current=false;clearInterval(timer);};},[]);const report=sources?prioritize({workspace:workspaceId,now:clock,sources}):null;
const refresh=async()=>{if(working.current)return;working.current=true;setBusy(true);setError('');try{const value=await loadSources({api:{rpc:(name:string,args:any)=>client.rpc(name,args)}},workspaceId);if(current()){setSources(value);setClock(Date.now());}}catch(e){if(current())setError(e instanceof Error?e.message:'Workspace records could not be checked.');}finally{working.current=false;if(current())setBusy(false);}};
return <View style={s.panel}><Text style={s.title}>What needs attention</Text><Text style={s.body}>Priorities from saved task deadlines, publishing states and confirmed bookings.</Text><Action label={busy?'Checking records…':'Check workspace priorities'} disabled={busy} run={refresh}/>{busy?<ActivityIndicator/>:null}{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{report?<><Text style={s.body}>{report.issues.length} actions · {report.coverage.filter((row:any)=>row.available).length}/{report.coverage.length} sources verified</Text>{report.coverage.map((row:any)=><View key={row.name} style={s.source}><Text style={s.label}>{row.name}</Text><Text style={s.body}>{row.available?'Loaded saved records':row.reason}</Text></View>)}{!report.complete?<Text style={s.error}>Coverage is incomplete. Unavailable sources are not counted as zero problems.</Text>:null}<Text style={s.small}>Publishing: previous 30 days through next 7. Bookings: previous and next 7 days. Records older than 5 minutes are excluded until refreshed.</Text><Action label={details==='formula'?'Hide ranking explanation':'How priorities are ranked'} run={()=>setDetails(value=>value==='formula'?'':'formula')}/>{details==='formula'?<Text style={s.body}>{report.formula} Scores use recorded severity, deadline urgency and coordination needs. No follower counts, engagement estimates or revenue forecasts are used.</Text>:null}{!report.issues.length?<Text style={s.body}>No matching actions in the verified records and inspected date windows. This is not a complete business health assessment.</Text>:null}{report.issues.map((issue:any)=><View key={issue.key} style={s.card}><Text style={s.score}>Priority {issue.score}/100</Text><Text style={s.heading}>{issue.action}</Text><Text style={s.body}>{issue.title}</Text>{issue.facts.map((fact:string,index:number)=><Text key={index} style={s.body}>• {fact}</Text>)}<Action label={details===issue.key?'Hide evidence':'View evidence and score'} run={()=>setDetails(value=>value===issue.key?'':issue.key)}/>{details===issue.key?<><Text style={s.small}>Severity {issue.components.severity} + urgency {issue.components.urgency} + coordination {issue.components.coordination}</Text><Text style={s.small}>{issue.confidence} · fetched {new Date(issue.fetchedAt).toLocaleString()}</Text><Text selectable style={s.small}>Record {issue.recordId}</Text></>:null}<Action label={issue.source==='publishing'?'Review publication on website ↗':'Review '+issue.source+' here'} run={()=>issue.source==='publishing'?Linking.openURL('https://www.zoi.city/social/composer').catch(()=>setError('The publishing workspace could not be opened.')):setReview(issue)}/></View>)}{review?<View style={s.card}><Action label="Close priority review" run={()=>setReview(null)}/>{review.source==='operations'?<OperationsPanel requestedRecordId={review.recordId}/>:<BookingOperator initiallyOpen/>}</View>:null}</>:null}</View>;
}
const s=StyleSheet.create({panel:{padding:22,gap:14,backgroundColor:'#fff',borderWidth:1,borderColor:'#DFE6EB',borderRadius:18},title:{fontSize:22,fontWeight:'700',color:'#132F46'},heading:{fontSize:18,fontWeight:'700',color:'#132F46'},body:{fontSize:14,lineHeight:22,color:'#60717E'},small:{fontSize:12,lineHeight:19,color:'#60717E'},label:{fontSize:13,fontWeight:'700',color:'#132F46'},source:{gap:4,paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#DFE6EB'},card:{padding:16,gap:12,borderWidth:1,borderColor:'#DFE6EB',borderRadius:12},score:{fontSize:13,fontWeight:'700',color:'#A77B32'},action:{minHeight:44,padding:12,backgroundColor:'#EAF4FB',borderRadius:10,justifyContent:'center'},link:{color:'#116CBA',fontWeight:'700'},error:{color:'#963624'}});
