import type {DraftStorage} from './drafts.ts';
type Part={slot:number;count:number};type Manifest={active:Part|null;pending?:Part};
/** One encrypted, account-scoped uncertain request. Never replayed automatically. */
export class PrivateRequestStore{
 private tails=new Map<string,Promise<unknown>>();
 private prefix:string; private storage:DraftStorage; private currentUser:()=>string|undefined;
 constructor(storage:DraftStorage,currentUser:()=>string|undefined,prefix='zoi.private-request.'){if(!/^[a-z.-]+$/.test(prefix))throw Error('Invalid storage namespace.');this.storage=storage;this.currentUser=currentUser;this.prefix=prefix;}
 private key(user:string){if(!/^[0-9a-f-]{36}$/i.test(user))throw Error('Invalid account reference.');return this.prefix+user;}
 private serial<T>(user:string,fn:()=>Promise<T>):Promise<T>{const next=(this.tails.get(user)||Promise.resolve()).catch(()=>{}).then(fn);this.tails.set(user,next);return next;}
 private async manifest(key:string):Promise<Manifest|null>{const raw=await this.storage.getItem(key);if(!raw)return null;const m=JSON.parse(raw);if(!m||typeof m!=='object'||Array.isArray(m)||!Object.hasOwn(m,'active')||Object.keys(m).some(k=>!['active','pending'].includes(k)))throw Error('The saved private request could not be verified.');for(const [key,p] of Object.entries(m)){if(key==='active'&&p===null)continue;if(!p||typeof p!=='object'||Array.isArray(p)||Object.keys(p).length!==2||!Object.hasOwn(p,'slot')||!Object.hasOwn(p,'count')||![0,1].includes((p as Part).slot)||!Number.isInteger((p as Part).count)||(p as Part).count<1||(p as Part).count>150)throw Error('The saved private request could not be verified.');}return m;}
 private async removeParts(key:string,part?:Part|null){if(part)for(let i=0;i<part.count;i++)await this.storage.removeItem(key+'.'+part.slot+'.'+i);}
 load(user:string){return this.serial(user,async()=>{if(this.currentUser()!==user)return null;const key=this.key(user),m=await this.manifest(key);if(!m)return null;if(m.pending)throw Error('A private request was interrupted while being saved. Refresh server records before discarding this local recovery record.');if(!m.active)return null;let value='';for(let i=0;i<m.active.count;i++){const part=await this.storage.getItem(key+'.'+m.active.slot+'.'+i);if(part===null)throw Error('The private recovery record is incomplete. Refresh server records before discarding it.');value+=part;}if(this.currentUser()!==user)return null;const parsed=JSON.parse(value);if(parsed===null)throw Error('The saved private request could not be verified.');return parsed;});}
 save(user:string,value:unknown){return this.serial(user,async()=>{if(this.currentUser()!==user)throw Error('The account changed.');const key=this.key(user),serialized=JSON.stringify(value);if(serialized.length>50000)throw Error('This private request is too large to save safely. Shorten its notes.');const chars=Array.from(serialized),parts:string[]=[];for(let i=0;i<chars.length;i+=400)parts.push(chars.slice(i,i+400).join(''));const old=await this.manifest(key);if(old?.pending)throw Error('Review the interrupted private request before starting another.');const next={slot:old?.active?.slot===0?1:0,count:parts.length};await this.storage.setItem(key,JSON.stringify({active:old?.active||null,pending:next}));try{for(let i=0;i<parts.length;i++){if(this.currentUser()!==user)throw Error('The account changed.');await this.storage.setItem(key+'.'+next.slot+'.'+i,parts[i]);}if(this.currentUser()!==user)throw Error('The account changed.');await this.storage.setItem(key,JSON.stringify({active:next}));}catch(error){let removed=true;try{await this.removeParts(key,next);}catch{removed=false;}if(removed){if(old?.active)await this.storage.setItem(key,JSON.stringify(old)).catch(()=>{});else await this.storage.removeItem(key).catch(()=>{});}throw error;}/* The committed slot remains authoritative even if stale-slot cleanup fails. */ await this.removeParts(key,old?.active).catch(()=>{});});}
 clear(user:string){return this.serial(user,async()=>{const key=this.key(user),m=await this.manifest(key);if(!m)return;await this.removeParts(key,m?.active);await this.removeParts(key,m?.pending);/* Sweep bounded inactive chunks left by interrupted cleanup. */ for(let slot=0;slot<2;slot++)for(let i=0;i<150;i++)await this.storage.removeItem(key+'.'+slot+'.'+i);await this.storage.removeItem(key);});}
}
