import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useAuth } from './Auth';
import { normalizeProfile, publicURL, plain, profileImageMode } from './profile';
import { musicDraft, musicFields } from './music';
import { BookingPanel } from './Bookings';
export function BusinessProfile({ slug, back, signIn, volunteer, enquiry }: { slug: string; back: () => void; signIn: () => void; volunteer: (workspace: string) => void; enquiry: (listing: string) => void }) {
  const { client } = useAuth(); const [profile, setProfile] = useState<ReturnType<typeof normalizeProfile>>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [retry, setRetry] = useState(0); const [imageFailed, setImageFailed] = useState(false);const [imageFit,setImageFit]=useState<'center'|'cover'>('center');
  useEffect(() => { let active = true; setLoading(true); setProfile(null); setError(''); setImageFailed(false);setImageFit('center'); client.request('/rest/v1/rpc/seo_entity', { p_slug: slug }).then(data => { if (active) setProfile(normalizeProfile(data)); }).catch(() => { if (active) setError('This profile could not be loaded. Please try again.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [slug, retry, client]);
  const open = async (url: string) => { try { await Linking.openURL(url); } catch { setError('Your device could not open this link. Please try another contact option.'); } };
  const music = profile && ['artist','musician'].includes(profile.type) ? musicDraft(profile.profile) : null;
  const action = (label: string, url: string) => <Pressable key={label} accessibilityRole="link" accessibilityLabel={label} onPress={() => open(url)} style={s.action}><Text style={s.link}>{label} ↗</Text></Pressable>;
  return <ScrollView contentContainerStyle={s.content}><Pressable accessibilityRole="button" onPress={back} style={s.action}><Text style={s.link}>← Back</Text></Pressable>{loading ? <ActivityIndicator color="#116CBA" /> : null}{error ? <View accessibilityRole="alert" style={s.panel}><Text style={s.body}>{error}</Text><Pressable accessibilityRole="button" onPress={() => setRetry(v => v + 1)} style={s.action}><Text style={s.link}>Try again</Text></Pressable></View> : null}{!loading && !error && !profile ? <Text style={s.body}>This listing is not available. It may have been moved or unpublished.</Text> : null}{profile ? <>
    {profile.photo && !imageFailed ? <Image source={{ uri: profile.photo }} resizeMode={imageFit} onLoad={event=>setImageFit(profileImageMode(event.nativeEvent.source.width,event.nativeEvent.source.height))} accessibilityLabel={profile.name} style={s.photo} onError={() => setImageFailed(true)} /> : <View style={s.initial}><Text style={s.monogram}>{profile.name.slice(0, 1).toUpperCase()}</Text></View>}
    <Text style={s.eyebrow}>{profile.type || 'The Greek world'}</Text><Text style={s.title}>{profile.name}</Text>{profile.verified ? <Text style={s.verified}>Verified listing</Text> : null}{profile.location ? <Text style={s.body}>{profile.location}</Text> : null}
    <View style={s.row}>{profile.website ? action('Website', profile.website) : null}{profile.phone && /[0-9]{3}/.test(profile.phone) ? action('Call ' + profile.phone, 'tel:' + profile.phone.replace(/[^0-9+]/g, '')) : null}{/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(profile.email) ? action('Email', 'mailto:' + encodeURIComponent(profile.email)) : null}{profile.address ? action('Directions', 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(profile.address + ' ' + profile.location)) : null}</View>
    {profile.description ? <View style={s.panel}><Text style={s.heading}>About</Text><Text style={s.body}>{profile.description}</Text></View> : null}
    {profile.address ? <View style={s.panel}><Text style={s.heading}>Visit</Text><Text selectable style={s.body}>{profile.address}</Text></View> : null}
    {profile.services.length ? <View style={s.panel}><Text style={s.heading}>Services</Text>{profile.services.map((service, index) => <Text key={index} style={s.body}>• {service}</Text>)}</View> : null}
    {profile.socials.length ? <View style={s.panel}><Text style={s.heading}>Follow their story</Text><View style={s.row}>{profile.socials.map(social => action(social.label, social.url))}</View></View> : null}
    {music ? <View style={s.panel}><Text style={s.heading}>Music & bookings</Text>{music.press ? <Text style={s.body}>{plain(music.press)}</Text> : null}<View style={s.row}>{musicFields.filter(([key]) => key.endsWith('_url') || key === 'merch').map(([key,label]) => publicURL(music[key]) ? action(label,publicURL(music[key])) : null)}</View>{/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(music.booking_email) ? action('Booking contact' + (music.booking_name ? ': ' + plain(music.booking_name) : ''),'mailto:' + encodeURIComponent(music.booking_email)) : null}{[['embeds','Featured music'],['releases','Releases'],['tour','Shows & tour dates']].map(([key,label]) => music[key].length ? <View key={key}><Text style={s.heading}>{label}</Text>{music[key].map((row:any,index:number) => publicURL(row.url) ? <View key={index}>{action(plain(row.title) || label,publicURL(row.url))}{row.date ? <Text style={s.small}>{plain(row.date)}</Text> : null}</View> : null)}</View> : null)}</View> : null}
    {profile.inquiryListing ? <Pressable accessibilityRole="button" style={s.action} onPress={() => enquiry(profile.inquiryListing)}><Text style={s.link}>Send a private enquiry →</Text></Pressable> : null}
    {profile.bookingListing ? <BookingPanel listingId={profile.bookingListing} signIn={signIn} /> : null}
    {profile.volunteerWorkspace ? <View style={s.panel}><Text style={s.heading}>Give your time</Text><Text style={s.body}>Explore this organization’s published volunteer opportunities.</Text><Pressable accessibilityRole="button" style={s.action} onPress={() => volunteer(profile.volunteerWorkspace)}><Text style={s.link}>Volunteer with this community →</Text></Pressable></View> : null}
    {profile.enrichmentNote ? <Text style={s.small}>{profile.enrichmentNote}</Text> : null}{action('Open canonical Zoi profile', 'https://www.zoi.city/p/' + encodeURIComponent(profile.slug || slug))}
  </> : null}</ScrollView>;
}
const s = StyleSheet.create({ content: { padding: 22, gap: 18, paddingBottom: 36 }, panel: { backgroundColor: '#fff', borderRadius: 18, padding: 20, gap: 12, borderWidth: 1, borderColor: '#DFE6EB' }, title: { fontSize: 32, lineHeight: 39, fontWeight: '700', color: '#132F46' }, heading: { fontSize: 20, color: '#132F46', fontWeight: '700' }, eyebrow: { textTransform: 'uppercase', fontSize: 10, letterSpacing: 2, color: '#A77B32' }, body: { color: '#60717E', fontSize: 15, lineHeight: 25 }, small: { color: '#60717E', fontSize: 12, lineHeight: 19 }, verified: { color: '#21714A', fontWeight: '600' }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, action: { paddingHorizontal: 15, paddingVertical: 13, minHeight: 46, backgroundColor: '#EAF4FB', borderRadius: 11, justifyContent: 'center' }, link: { color: '#116CBA', fontSize: 14, fontWeight: '700' }, photo: { width: '100%', height: 240, borderRadius: 18 }, initial: { height: 180, borderRadius: 18, backgroundColor: '#E6EFF0', justifyContent: 'center', alignItems: 'center' }, monogram: { fontSize: 72, color: '#416D7D' } });
