import {NativePareaHandoff} from './NativePareaHandoff';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { GeneralReservationGuard, generalReceipt, generalRecovery, generalSubmission, type GeneralAttempt } from './generalReservation';
const generalGuard = new GeneralReservationGuard(AsyncStorage);
import {guestEventHostLink, organiserEventHostLink, scopedEventHostRpc} from './eventHostLink';
import {EventSeatMap} from './EventSeatMap';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, AppState, Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { randomUUID } from 'expo-crypto';
import { useAuth } from './Auth';
import { plain } from './profile';
import { freeReceipt, holdReceipt, remainingSeconds, seatMap, statusResponse, validEventId, type Hold, type Receipt } from './seating';
function Action({ label, run, disabled = false }: { label: string; run: () => void; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={run} style={[s.action, disabled && s.disabled]}><Text style={s.link}>{label}</Text></Pressable>; }
export function TicketsScreen({ eventId, chooseEvent, signIn }: { eventId: string | null; chooseEvent: (id: string | null) => void; signIn: () => void }) {
  const { session } = useAuth();
  return eventId ? <EventTickets key={eventId + ':' + (session?.user.id || 'guest')} eventId={eventId} back={() => chooseEvent(null)} signIn={signIn} /> : <EventsList choose={chooseEvent} />;
}
function EventsList({ choose }: { choose: (id: string) => void }) {
  const { client } = useAuth(); const [events, setEvents] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [reload, setReload] = useState(0); const [eventCode, setEventCode] = useState('');
  useEffect(() => { let active = true; setLoading(true); setError(''); client.request('/rest/v1/rpc/explore_search', { p_q: '', p_type: 'event', p_limit: 24 }).then(result => { if (!Array.isArray(result)) throw new Error(); if (active) setEvents(result.filter(event => validEventId(event.id))); }).catch(() => { if (active) setError('Events could not be loaded. Please try again.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [reload, client]);
  return <ScrollView contentContainerStyle={s.content}><Text style={s.kicker}>MAKE A MEMORY TOGETHER</Text><Text style={s.title}>Your next gathering.</Text><Text style={s.body}>Discover events and check tickets directly with Zoi.</Text><View style={s.panel}><Text style={s.heading}>Your table and your group</Text><Text style={s.body}>Open an event below to organise whole ticket quantities, share personal invitations and review current payment arrangements in the app. Organiser allocation settings are available on the website. An allocation is not an admission ticket.</Text><Action label="Manage group allocations in browser ↗" run={() => { void Linking.openURL('https://www.zoi.city/tickets/hosts/').catch(() => setError('We could not open group allocations. Try again, or visit www.zoi.city/tickets/hosts/ in your browser.')); }} /></View>{loading ? <ActivityIndicator color="#116CBA" /> : null}{error ? <Text style={s.error}>{error}</Text> : null}<Action label="Refresh events" disabled={loading} run={() => setReload(v => v + 1)} />{events.map(event => <Pressable accessibilityRole="button" key={event.id} onPress={() => choose(event.id)} style={s.panel}><Text style={s.heading}>{plain(event.name)}</Text><Text style={s.body}>{[event.city,event.country].map(plain).filter(Boolean).join(' · ')}</Text>{event.description ? <Text numberOfLines={3} style={s.body}>{plain(event.description)}</Text> : null}<Text style={s.link}>View event and tickets →</Text></Pressable>)}{!loading && !error && !events.length ? <Text style={s.body}>No published events were returned.</Text> : null}<View style={s.panel}><Text style={s.heading}>Have an event link?</Text><TextInput accessibilityLabel="Zoi event link or ID" style={s.input} value={eventCode} onChangeText={setEventCode} placeholder="Paste the event link or ID" autoCapitalize="none" /><Action label="Open event" run={() => { let id = eventCode.trim(); try { id = new URL(id).searchParams.get('e') || id; } catch {} if (validEventId(id)) choose(id); else setError('Enter a Zoi event link with ?e= or a valid event ID.'); }} /></View></ScrollView>;
}
function EventTickets({ eventId, back, signIn }: { eventId: string; back: () => void; signIn: () => void }) {
  const { client, session, workspaceId } = useAuth(); const userId = session?.user.id;
  const selectedWorkspace = useRef(workspaceId); selectedWorkspace.current = workspaceId;
  const [event, setEvent] = useState<any>(null); const [tiers, setTiers] = useState<any[]>([]); const [map, setMap] = useState<ReturnType<typeof seatMap>>(null); const [mapNotice, setMapNotice] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [hold, setHold] = useState<Hold | null>(null); const [reservations, setReservations] = useState<{status: string; receipt: Receipt}[]>([]); const [receipt, setReceipt] = useState<Receipt | null>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [name, setName] = useState(''); const [email, setEmail] = useState(session?.user.email || ''); const [quantity, setQuantity] = useState(1); const [tierId, setTierId] = useState(''); const [now, setNow] = useState(Date.now()); const [offset, setOffset] = useState(0); const [cancelId, setCancelId] = useState(''); const [statusReady, setStatusReady] = useState(false); const [generalUncertain, setGeneralUncertain] = useState(false); const [generalReady,setGeneralReady]=useState(false); const [guestPending,setGuestPending]=useState(false); const [generalHistory,setGeneralHistory]=useState<any[]>([]); const [generalAttempt,setGeneralAttempt]=useState<GeneralAttempt|null>(null); const [generalLifecycle,setGeneralLifecycle]=useState<{status:string;checkedIn:boolean;eventAvailable:boolean|null}|null>(null);
  const readEpoch = useRef(0); const alive = useRef(true); const working = useRef(false); const request = useRef<{ id: string; seats: string[] } | null>(null); const holdRef = useRef(hold); holdRef.current = hold; const expiredRead = useRef(''); const current = () => alive.current && client.session?.user.id === userId;
  const publicCall = (fn: string, body: unknown) => client.request('/rest/v1/rpc/' + fn, body);
  const generalCall=(fn:string,body:unknown)=>{if(!current())throw Error('Your account changed.');return userId?client.rpc(fn,body):publicCall(fn,body);};
  const recoverGeneral=async(attempt:GeneralAttempt)=>{if(attempt.protocol!=='once')return;const response=await generalCall('tickets_reserve_receipt',{p_request:attempt.id,p_event:attempt.event,p_type:attempt.tier});const saved=generalRecovery(response,attempt);if(!current())return;if(saved){setReceipt({...saved.receipt,cancelled:saved.status==='cancelled'});setGeneralLifecycle(saved);await generalGuard.confirmed(attempt,saved.receipt,attempt.qty!);if(!current())return;setGeneralAttempt(null);setGeneralUncertain(false);setNotice(saved.status==='cancelled'?'This reservation was cancelled. The original code is shown for your records.':'Your recorded reservation was recovered. Review its current status below.');}else setNotice('This request has no confirmed receipt yet. Re-enter the original details to retry the same request; no new request will be created.');};
  const loadMap = async () => { const epoch = readEpoch.current; try { const value = seatMap(await publicCall('tickets_seat_map', { p_event: eventId })); if (!current() || epoch !== readEpoch.current) return; setMap(value); setMapNotice(value ? 'Seat availability is from the server. Select up to 10 seats, then request a hold.' : 'This event does not have a published seating plan.'); if (!holdRef.current) setSelected(ids => ids.filter(id => value?.seats.some(seat => seat.id === id && seat.state === 'available'))); } catch (e) { if (current() && epoch === readEpoch.current) { setMap(null); setMapNotice(e instanceof Error ? e.message : 'Seat selection is unavailable.'); } } };
  const loadStatus = async () => { const epoch = readEpoch.current; if (!userId) return; const value = statusResponse(await client.rpc('tickets_seat_status', { p_event: eventId })); if (!current() || epoch !== readEpoch.current) return; setStatusReady(true); setHold(value.active_hold); setReservations(value.reservations); setOffset(Date.parse(value.server_time) - Date.now()); if (value.active_hold) setSelected(value.active_hold.seat_ids); };
  const refresh = async () => { if (working.current) return; working.current = true; setLoading(true); setStatusReady(false); setError('');setGeneralHistory([]);if(generalLifecycle){setReceipt(null);setGeneralLifecycle(null);} try { setGeneralReady(false); const pendingGeneral=await generalGuard.read(userId||'guest',eventId); if(!current())return;setGeneralAttempt(pendingGeneral);setGeneralUncertain(!!pendingGeneral);const unresolvedGuest=await generalGuard.hasGuestPending(userId||'guest',eventId);if(!current())return;setGuestPending(unresolvedGuest);setGeneralReady(true);if(pendingGeneral)await recoverGeneral(pendingGeneral).catch(e=>{if(current())setNotice(e instanceof Error?e.message:'Reservation recovery is unavailable. Your saved request is preserved.');});if(!current())return;
      const refs=await generalGuard.references(userId||'guest',eventId);if(!current())return;
      const history=await Promise.all(refs.filter(ref=>ref.id!==pendingGeneral?.id).map(async ref=>{
       try{const value=generalRecovery(await generalCall('tickets_reserve_receipt',{p_request:ref.id,p_event:ref.event,p_type:ref.tier}),ref);return {id:ref.id,...(value||{}),unavailable:!value};}
       catch{return {id:ref.id,unavailable:true};}
      }));if(!current())return;setGeneralHistory(history);
      const [ev,types] = await Promise.all([publicCall('tickets_event_public', { p_event: eventId }), publicCall('tickets_types_list', { p_event: eventId })]); if (!ev || !plain(ev.name) || !Array.isArray(types)) throw new Error('This event is unavailable or unpublished.'); if (!current()) return; setEvent(ev); setTiers(types.filter(type => /^\d+$/.test(String(type.id)) && !(typeof type.id === 'number' && !Number.isSafeInteger(type.id)))); await loadMap(); if (userId) await loadStatus().catch(() => { if (current()) setNotice('Your saved seat holds could not be checked. Refresh reservations before making another hold.'); }); } catch (e) { if (current()) setError(e instanceof Error ? e.message : 'The event could not be loaded.'); } finally { working.current = false; if (current()) setLoading(false); } };
  useEffect(() => { alive.current = true; refresh(); const subscription = AppState.addEventListener('change', state => { if (state === 'active') refresh(); }); const timer = setInterval(() => setNow(Date.now()), 1000); return () => { alive.current = false; subscription.remove(); clearInterval(timer); }; }, [eventId, userId]);
  const seconds = remainingSeconds(hold, now, offset);
  useEffect(() => { if (!working.current && hold && seconds === 0 && expiredRead.current !== hold.hold_id) { expiredRead.current = hold.hold_id; setNotice('The hold time has elapsed. Checking its current status…'); loadStatus().catch(() => { if (current()) setNotice('The hold time elapsed. Refresh reservations to verify its status.'); }); loadMap(); } }, [hold?.hold_id, seconds]);
  const action = async (run: () => Promise<void>) => { if (working.current) return; working.current = true; readEpoch.current += 1; setBusy(true); setError(''); setNotice(''); try { await run(); } catch (e) { if (current()) setError(e instanceof Error ? e.message : 'This action could not be confirmed. Refresh before retrying.'); } finally { working.current = false; if (current()) setBusy(false); } };
  const openHostTools = (organiser = false) => action(async () => {
    const workspace = workspaceId;
    const stillCurrent = () => current() && (!organiser || selectedWorkspace.current === workspace);
    if (!stillCurrent()) throw Error('Your account or selected workspace changed.');
    const url = organiser ? await organiserEventHostLink({event:eventId,workspace,actor:userId || '',current:stillCurrent,rpc:(name,args)=>scopedEventHostRpc(client,userId || '',stillCurrent,name,args)}) : guestEventHostLink(eventId);
    if (!stillCurrent()) return;
    await Linking.openURL(url);
  });
  const toggle = useCallback((id: string) => { if (hold || busy || !map?.seats.some(seat => seat.id === id && seat.state === 'available')) return; setSelected(ids => ids.includes(id) ? ids.filter(value => value !== id) : ids.length < 10 ? [...ids,id] : ids); request.current = null; },[hold,busy,map]);
  const reserveSeats = () => action(async () => { if (!hold || seconds <= 0) throw new Error('Refresh your hold before confirming.'); if (!name.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) throw new Error('Enter your name and a valid email.'); const saved = freeReceipt(await client.rpc('tickets_seat_reserve', { p_hold_id: hold.hold_id, p_name: name.trim(), p_email: email.trim() }), hold.seat_ids.length, hold); if (!current()) return; setReceipt(saved); setGeneralLifecycle(null); setHold(null); setSelected([]); request.current = null; setNotice('Your free reservation is confirmed.'); await loadStatus().catch(() => { if (current()) { setStatusReady(false); setNotice('The action is confirmed. Refresh to update your reservation list.'); } }); await loadMap(); });
  const holdSeats = () => action(async () => { if (!session) throw new Error('Sign in before holding seats.'); if (!statusReady) throw new Error('Refresh your reservations before requesting another hold.'); if (!selected.length || hold) return; request.current ||= { id: randomUUID(), seats: [...selected] }; const result = holdReceipt(await client.rpc('tickets_seat_hold', { p_event: eventId, p_seat_ids: request.current.seats, p_request_id: request.current.id }), request.current.seats); if (!current()) return; setHold(result); setNotice('Your seats are held until the server expiry time. Confirm below.'); });
  const release = () => action(async () => { if (!hold) return; const result = await client.rpc('tickets_seat_release', { p_hold_id: hold.hold_id }); if (result?.ok !== true) throw new Error('Release was not confirmed. Refresh your reservations.'); if (!current()) return; setHold(null); setSelected([]); request.current = null; setNotice('Your seat hold was released.'); await loadMap(); });
  const cancel = (saved: Receipt) => { if (!saved.hold_id) return; if (cancelId !== saved.hold_id) { setCancelId(saved.hold_id); return; } action(async () => { const result = freeReceipt(await client.rpc('tickets_seat_cancel', { p_hold_id: saved.hold_id }), saved.qty, { hold_id: saved.hold_id!, seat_ids: saved.seat_ids || [], expires_at: '' }); if (result.cancelled !== true) throw new Error('Cancellation was not confirmed.'); if (!current()) return; setReceipt(previous => previous?.hold_id === saved.hold_id ? result : previous); setCancelId(''); setNotice('Your reservation was cancelled.'); await loadStatus().catch(() => { if (current()) { setStatusReady(false); setNotice('The action is confirmed. Refresh to update your reservation list.'); } }); await loadMap(); }); };
  const reserveGeneral = () => action(async () => {
    if(!generalReady)throw Error('Refresh reservations before continuing.');
    if(await generalGuard.hasGuestPending(userId||'guest',eventId))throw Error('A guest reservation on this device still needs review. Sign out and reopen this event to recover it before starting another request.');
    if(!current())return;
    let attempt=generalAttempt;
    if(attempt&&attempt.protocol!=='once')throw Error('This older reservation request must be reviewed with the organizer.');
    if(!attempt){const tier=tiers.find(item=>String(item.id)===tierId);if(!tier||tier.price_cents!==0||map?.ticket_type_id===tierId)throw Error('Choose an available free ticket type.');attempt={actor:userId||'guest',event:eventId,tier:String(tier.id),id:randomUUID(),created_at:new Date().toISOString(),protocol:'once',qty:quantity};}
    const args=generalSubmission(attempt,name,email);
    if(!generalAttempt){await generalGuard.begin(attempt,current);if(!current())return;setGeneralAttempt(attempt);setGeneralUncertain(true);}else if(attempt.actor!==(userId||'guest')||attempt.event!==eventId)throw Error('Your reservation account changed.');
    const saved=generalReceipt(await generalCall('tickets_reserve_once',args),attempt);if(!current())return;setReceipt(saved);setGeneralLifecycle({status:'Current status not yet checked',checkedIn:false,eventAvailable:null});await recoverGeneral(attempt);if(!current())return;setTierId('');
  });
  return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}><Action label="← All events" run={back} /><Text style={s.kicker}>GATHER WITH YOUR PEOPLE</Text><Text style={s.title}>{plain(event?.name) || 'Event tickets'}</Text>{event?.event_at && Number.isFinite(Date.parse(event.event_at)) ? <Text style={s.body}>{new Date(event.event_at).toLocaleString()}</Text> : null}<Text style={s.body}>{[event?.city,event?.country].map(plain).filter(Boolean).join(' · ')}</Text>{event?.description ? <Text style={s.body}>{plain(event.description)}</Text> : null}
    {loading ? <ActivityIndicator color="#116CBA" /> : null}{error ? <Text accessibilityRole="alert" style={s.error}>{error}</Text> : null}{notice ? <Text accessibilityLiveRegion="polite" style={s.body}>{notice}</Text> : null}<Action label="Refresh event and reservations" disabled={busy || loading} run={refresh} />
    {event ? <View style={s.panel}><Text style={s.heading}>Your table and your group</Text><Text style={s.body}>Organise your parea below. The website also has group tools and organiser allocation settings; browser sign-in is separate.</Text><Action label="This event’s group arrangements on web ↗" disabled={busy || loading} run={() => openHostTools()} />{userId && workspaceId ? <><Text style={s.small}>Organiser access is checked against the workspace selected in Grow and this event.</Text><Action label="Check organiser access and open web tools ↗" disabled={busy || loading} run={() => openHostTools(true)} /></> : null}</View> : null}
    {event && userId ? <NativePareaHandoff key={eventId+':'+userId+':'+(workspaceId||'')} eventId={eventId}/> : null}
    {tiers.map(tier => { const price = Number.isInteger(tier.price_cents) && tier.price_cents >= 0 ? tier.price_cents : null; const named = map?.ticket_type_id === String(tier.id); return <View key={String(tier.id)} style={s.panel}><Text style={s.heading}>{plain(tier.name) || 'Ticket'}</Text><Text style={s.body}>{price === 0 ? 'Free reservation' : price !== null ? (price / 100).toFixed(2) + ' ' + plain(tier.currency) : 'Price unavailable'}</Text>{tier.description ? <Text style={s.body}>{plain(tier.description)}</Text> : null}{typeof tier.capacity === 'number' && typeof tier.reserved === 'number' ? <Text style={s.small}>{Math.max(0,tier.capacity-tier.reserved)} capacity remaining before active seat holds · availability rechecked at confirmation</Text> : null}{named ? <Text style={s.link}>Choose named seats below</Text> : price === 0 ? <Action label={tierId === String(tier.id) ? 'Selected' : 'Choose free ticket'} disabled={busy || loading || !!hold || generalUncertain || guestPending || !generalReady} run={() => { setTierId(String(tier.id)); setReceipt(null); }} /> : price !== null ? <Action label="View ticket options on website ↗" run={() => Linking.openURL('https://www.zoi.city/tickets?e=' + encodeURIComponent(eventId)).catch(() => setError('The website could not be opened.'))} /> : null}</View>; })}
    {mapNotice ? <Text style={s.small}>{mapNotice}</Text> : null}{map ? <View style={s.panel}><Text style={s.heading}>Choose your seats</Text><EventSeatMap layout={map.layout} seats={map.seats} selected={selected} toggle={toggle}/><Text style={s.small}>Blue: available · Gold: selected · Grey: held or reserved</Text><View style={s.row}>{map.seats.map(seat => <Action key={seat.id} label={(selected.includes(seat.id) ? '● ' : '') + seat.label + (seat.accessible ? ' · accessible' : '') + ' · ' + seat.state} disabled={!!hold || busy || seat.state !== 'available'} run={() => toggle(seat.id)} />)}</View>{!session ? <Action label="Sign in to hold seats" run={signIn} /> : !hold ? <Action label={`Hold ${selected.length || ''} selected seats`} disabled={busy || !selected.length || loading || !statusReady} run={holdSeats} /> : <><Text accessibilityLiveRegion="polite" style={s.heading}>{seconds > 0 ? `Hold expires in ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}` : 'Hold time elapsed — refresh status'}</Text><Action label="Release my hold" disabled={busy} run={release} /></>}</View> : null}
    {(hold && seconds > 0) || tierId ? <View style={s.panel}><Text style={s.heading}>Reservation details</Text><TextInput accessibilityLabel="Guest name" style={s.input} placeholder="Your name" value={name} onChangeText={setName} maxLength={120} editable={!busy} /><TextInput accessibilityLabel="Confirmation email" style={s.input} placeholder="Email address" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" maxLength={160} editable={!busy} />{!hold ? <View style={s.row}><Action label="−" disabled={busy || quantity <= 1} run={() => setQuantity(value => value - 1)} /><Text style={s.body}>{quantity} tickets</Text><Action label="+" disabled={busy || quantity >= 10} run={() => setQuantity(value => value + 1)} /></View> : null}<Action label={busy ? 'Confirming…' : 'Confirm free reservation'} disabled={busy || loading || (!hold && (generalUncertain || guestPending || !generalReady))} run={hold ? reserveSeats : reserveGeneral} /><Text style={s.small}>A reservation is confirmed only when the server returns a confirmation code. An interrupted request may still complete: refresh before retrying.</Text></View> : null}
    {guestPending?<View style={s.panel}><Text style={s.heading}>Review your earlier guest request</Text><Text style={s.body}>A guest reservation on this device may have completed. Sign out in Grow, then reopen this event to check it before starting another reservation. The guest request is never sent using your signed-in account.</Text><Action label="Open account settings" run={signIn}/></View>:null}
    {generalUncertain ? <View style={s.panel}>{generalAttempt?.protocol==='once'?<><Text style={s.heading}>Recover your general-admission request</Text><Text style={s.body}>{generalAttempt.qty} tickets · request saved on this device. Re-enter the same name and email; changed details are rejected by the server.</Text><TextInput accessibilityLabel="Original reservation name" value={name} onChangeText={setName} editable={!busy} maxLength={120} style={s.input}/><TextInput accessibilityLabel="Original reservation email" value={email} onChangeText={setEmail} editable={!busy} maxLength={160} autoCapitalize="none" keyboardType="email-address" style={s.input}/><Action label="Check saved reservation receipt" disabled={busy||loading} run={()=>action(()=>recoverGeneral(generalAttempt))}/><Action label="Retry this same reservation request" disabled={busy||loading||!name.trim()||!email.trim()} run={reserveGeneral}/></>:null}<Text style={s.error}>This general-admission request may have completed. The warning remains on this device after reopening this event. Use the recovery controls when available, or contact the organizer before starting another reservation.</Text><Action label="Review event and contact options on website ↗" run={()=>Linking.openURL('https://www.zoi.city/tickets?e='+encodeURIComponent(eventId)).catch(()=>setError('The website could not be opened.'))}/><Text style={s.small}>Opening the website does not resolve or clear this warning. No automatic retry is sent.</Text></View> : null}
    {generalHistory.length?<View style={s.panel}><Text style={s.heading}>Tickets saved on this device</Text>{generalHistory.map(row=><View key={row.id} style={s.panel}>{row.unavailable?<Text style={s.body}>The current status of a saved ticket could not be verified. Refresh to check again.</Text>:<><Text style={s.heading}>{row.status==='cancelled'?'Reservation cancelled':'Reservation recorded'}</Text><Text selectable style={s.code}>{row.receipt.code}</Text><Text style={s.body}>Status: {row.status}{row.checkedIn?' · Checked in':''}{row.eventAvailable===false?' · Current event or ticket offering is unavailable':''}</Text><Text style={s.body}>{row.receipt.qty} tickets · Free</Text></>}</View>)}<Text style={s.small}>Up to five recent references per event are kept on this device for one year. Their current status is checked with Zoi; this is not a cross-device ticket wallet.</Text></View>:null}
    {receipt ? <View style={s.receipt}><Text style={s.heading}>{receipt.cancelled ? 'Reservation cancelled' : generalLifecycle?'Reservation recorded':'Reservation confirmed'}</Text><Text selectable style={s.code}>{receipt.code}</Text>{generalLifecycle?<Text style={s.body}>Status: {generalLifecycle.status}{generalLifecycle.checkedIn?' · Checked in':''}{generalLifecycle.eventAvailable===false?' · Current event or ticket offering is unavailable':''}</Text>:null}<Text style={s.body}>{receipt.qty} tickets · Free{receipt.seat_ids ? ' · Seats: ' + receipt.seat_ids.join(', ') : ''}</Text></View> : null}
    {session ? <View style={s.panel}><Text style={s.heading}>Your named-seat reservations</Text>{reservations.length ? reservations.map(row => <View key={row.receipt.hold_id} style={s.saved}><Text selectable style={s.heading}>{row.receipt.code}</Text><Text style={s.body}>{row.receipt.qty} seats · {row.status}</Text>{row.status === 'reserved' ? <Action label={cancelId === row.receipt.hold_id ? 'Confirm cancellation' : 'Cancel reservation'} disabled={busy} run={() => cancel(row.receipt)} /> : null}</View>) : <Text style={s.small}>Refresh to check your reservations. General-admission confirmation codes are shown immediately after booking.</Text>}</View> : null}
  </ScrollView>;
}
const s = StyleSheet.create({ content: { padding: 22, gap: 18, paddingBottom: 36 }, panel: { padding: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: '#DFE6EB', borderRadius: 18, gap: 14 }, title: { fontSize: 32, lineHeight: 39, fontWeight: '700', color: '#132F46' }, heading: { fontSize: 18, color: '#132F46', fontWeight: '700' }, kicker: { fontSize: 10, letterSpacing: 2, color: '#A77B32', fontWeight: '700' }, body: { fontSize: 14, lineHeight: 23, color: '#60717E' }, small: { fontSize: 12, lineHeight: 19, color: '#60717E' }, action: { minHeight: 44, padding: 12, borderRadius: 10, backgroundColor: '#EAF4FB', justifyContent: 'center' }, disabled: { opacity: 0.5 }, link: { fontSize: 13, color: '#116CBA', fontWeight: '700' }, error: { color: '#963624', fontSize: 14, lineHeight: 23 }, input: { minHeight: 48, borderColor: '#CAD7E0', borderWidth: 1, borderRadius: 10, padding: 12, color: '#132F46' }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' }, receipt: { backgroundColor: '#E8F3EB', borderRadius: 18, padding: 22, gap: 12 }, code: { fontSize: 23, fontWeight: '700', color: '#132F46', letterSpacing: 2 }, saved: { borderTopColor: '#DFE6EB', borderTopWidth: 1, paddingTop: 12, gap: 10 } });
