import { Fragment, useEffect, useRef, useState } from 'react';
import { Pressable, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import Svg, { Polygon, Rect, Text as SvgText } from 'react-native-svg';
import { AsyncStorage, useAuth } from './Auth';
import { createLayout, validateLayout, seatRows, updateObjects, summarize, parseLayout, projectPoint } from '../../assets/tickets/venue-model.mjs';
type Item = { id: string; kind: 'seat' | 'table' | 'stage'; label: string; x: number; y: number; width: number; depth: number; height: number; accessible: boolean; excluded: boolean };
type Layout = { version: number; name: string; width: number; depth: number; objects: Item[] };
const palette = { seat: '#116CBA', table: '#A77B32', stage: '#132F46' };
function Control({ label, run }: { label: string; run: () => void }) { return <Pressable accessibilityRole="button" onPress={run} style={st.control}><Text style={st.controlText}>{label}</Text></Pressable>; }
export function VenueStudio() {
  const { session } = useAuth();
  const [layout, setLayout] = useState<Layout>(() => createLayout('My venue', 20, 15));
  const [selected, setSelected] = useState(''); const [is3d, set3d] = useState(false); const [yaw, setYaw] = useState(0.6); const [notice, setNotice] = useState(''); const [json, setJson] = useState('');
  const item = layout.objects.find(object => object.id === selected); const counts = summarize(layout);
  const key = 'zoi.venue.' + (session?.user.id || 'guest');
  const activeKey = useRef(key); activeKey.current = key;
  useEffect(() => { setLayout(createLayout('My venue', 20, 15)); setSelected(''); setJson(''); setNotice(''); }, [key]);
  const change = (fn: () => Layout) => { try { setLayout(validateLayout(fn())); setNotice('Unsaved changes'); } catch (error) { setNotice(error instanceof Error ? error.message : 'This layout change could not be applied.'); } };
  const move = (dx: number, dy: number) => { if (item) change(() => updateObjects(layout, [item.id], { x: item.x + dx, y: item.y + dy })); };
  const corners = (object: Item, z: number) => [[object.x, object.y], [object.x + object.width, object.y], [object.x + object.width, object.y + object.depth], [object.x, object.y + object.depth]].map(([x, y]) => projectPoint(x, y, z, layout, yaw));
  const points = (vertices: { x: number; y: number }[]) => vertices.map(v => `${v.x},${v.y}`).join(' ');
  const shapeColor = (object: Item) => object.id === selected ? '#D98619' : object.excluded ? '#AAB3BA' : object.accessible ? '#218367' : palette[object.kind];
  const objects = is3d ? [...layout.objects].sort((a, b) => projectPoint(b.x, b.y, 0, layout, yaw).depth - projectPoint(a.x, a.y, 0, layout, yaw).depth) : layout.objects;
  const save = async () => { try { await AsyncStorage.setItem(key, JSON.stringify(validateLayout(layout))); if (activeKey.current === key) setNotice('Layout saved on this device.'); } catch { setNotice('Your layout could not be saved. Export a copy before leaving.'); } };
  const load = async () => { try { const value = await AsyncStorage.getItem(key); if (activeKey.current !== key) return; if (!value) { setNotice('No saved layout on this device.'); return; } setLayout(parseLayout(value)); setSelected(''); setNotice('Saved layout loaded.'); } catch { setNotice('The saved layout could not be loaded.'); } };
  return <View style={st.panel}><Text style={st.kicker}>VENUE STUDIO</Text><Text style={st.title}>Shape the gathering.</Text><Text style={st.body}>Create a venue plan, explore its geometry in 3D, and select individual seats. This is your layout draft; selections do not reserve tickets.</Text>
    <TextInput accessibilityLabel="Venue name" value={layout.name} onChangeText={name => setLayout({ ...layout, name })} style={st.input} maxLength={100} />
    <View style={st.row}><Control label={is3d ? 'Floor plan' : '3D view'} run={() => set3d(!is3d)} /><Control label="Rotate left" run={() => setYaw(yaw - 0.3)} /><Control label="Rotate right" run={() => setYaw(yaw + 0.3)} /></View>
    <View style={st.canvas}><Svg width="100%" height={260} viewBox={is3d ? '0 0 800 440' : `-1 -1 ${layout.width + 2} ${layout.depth + 2}`} accessibilityLabel={is3d ? 'Three dimensional venue preview' : 'Venue floor plan'}>
      {is3d ? <Polygon points={points(corners({ x: 0, y: 0, width: layout.width, depth: layout.depth } as Item, 0))} fill="#E8EEF0" stroke="#B6C8D0" strokeWidth={2} /> : <Rect x={0} y={0} width={layout.width} height={layout.depth} fill="#E8EEF0" stroke="#B6C8D0" strokeWidth={0.08} />}
      {objects.map(object => {
        if (!is3d) return <Rect key={object.id} x={object.x} y={object.y} width={object.width} height={object.depth} rx={object.kind === 'seat' ? 0.12 : 0.05} fill={shapeColor(object)} stroke={selected === object.id ? '#132F46' : '#fff'} strokeWidth={0.06} onPress={() => setSelected(object.id)} />;
        const top = corners(object, object.height), bottom = corners(object, 0);
        return <Fragment key={object.id}><Polygon points={points([top[1], top[2], bottom[2], bottom[1]])} fill={shapeColor(object)} opacity={0.65} stroke="#fff" strokeWidth={0.6} onPress={() => setSelected(object.id)} /><Polygon points={points([top[2], top[3], bottom[3], bottom[2]])} fill={shapeColor(object)} opacity={0.8} stroke="#fff" strokeWidth={0.6} onPress={() => setSelected(object.id)} /><Polygon points={points(top)} fill={shapeColor(object)} stroke="#fff" strokeWidth={0.8} onPress={() => setSelected(object.id)} /></Fragment>;
      })}
      {!is3d && objects.length === 0 ? <SvgText x={layout.width / 2} y={layout.depth / 2} fontSize={0.65} textAnchor="middle" fill="#60717E">Add seats to start your plan</SvgText> : null}
    </Svg></View>
    <Text style={st.body}>{counts.seats} seats · {counts.accessible} accessible · {counts.excluded} excluded · {layout.width} × {layout.depth} m</Text>
    <View style={st.row}><Control label="Add 3 rows of seats" run={() => change(() => seatRows(layout, { rows: 3, seats: 8, prefix: String.fromCharCode(65 + new Set(layout.objects.filter(o => o.kind === 'seat').map(o => o.label.charAt(0))).size), y: Math.max(2.65, ...layout.objects.filter(o => o.kind === 'seat').map(o => o.y)) + 1.35, idPrefix: 'seats-' + Date.now().toString(36) }))} /><Control label="Add stage" run={() => change(() => ({ ...layout, objects: [...layout.objects, { id: 'stage-' + Date.now().toString(36), kind: 'stage', label: 'Stage', x: 6, y: 1, width: 8, depth: 2, height: 1, accessible: false, excluded: false }] }))} /></View>
    <View style={st.row}><Control label="Add table" run={() => change(() => ({ ...layout, objects: [...layout.objects, { id: 'table-' + Date.now().toString(36), kind: 'table', label: 'Table ' + (layout.objects.filter(o => o.kind === 'table').length + 1), x: 1, y: 1, width: 2, depth: 2, height: 0.75, accessible: false, excluded: false }] }))} /><Control label="Widen room 2 m" run={() => change(() => ({ ...layout, width: layout.width + 2 }))} /><Control label="Deepen room 2 m" run={() => change(() => ({ ...layout, depth: layout.depth + 2 }))} /></View>
    <Text style={st.heading}>{item ? `Selected: ${item.label}` : 'Select an object to edit'}</Text>
    <View style={st.row}>{layout.objects.map(object => <Pressable accessibilityRole="button" aria-pressed={selected === object.id} accessibilityState={{ selected: selected === object.id }} key={object.id} onPress={() => setSelected(object.id)} style={[st.seat, selected === object.id && st.selected]}><Text style={st.controlText}>{object.label}</Text></Pressable>)}</View>
    {item ? <><View style={st.row}><Control label="← 0.25 m" run={() => move(-0.25, 0)} /><Control label="→ 0.25 m" run={() => move(0.25, 0)} /><Control label="↑ 0.25 m" run={() => move(0, -0.25)} /><Control label="↓ 0.25 m" run={() => move(0, 0.25)} /></View>{item.kind === 'seat' ? <View style={st.row}><Control label={item.accessible ? 'Remove accessibility mark' : 'Mark accessible'} run={() => change(() => updateObjects(layout, [item.id], { accessible: !item.accessible }))} /><Control label={item.excluded ? 'Include seat' : 'Exclude seat'} run={() => change(() => updateObjects(layout, [item.id], { excluded: !item.excluded }))} /></View> : null}<Control label="Remove selected object" run={() => { change(() => ({ ...layout, objects: layout.objects.filter(object => object.id !== item.id) })); setSelected(''); }} /></> : null}
    {notice ? <Text accessibilityLiveRegion="polite" style={st.notice}>{notice}</Text> : null}
    <View style={st.row}><Control label="Save draft" run={save} /><Control label="Load draft" run={load} /><Control label="Export JSON" run={() => { try { const text = JSON.stringify(validateLayout(layout), null, 2); setJson(text); Share.share({ message: text, title: layout.name }).catch(() => setNotice('Copy the JSON below to export your layout.')); } catch (error) { setNotice(error instanceof Error ? error.message : 'Check your layout.'); } }} /></View>
    <TextInput accessibilityLabel="Venue layout JSON import or export" multiline placeholder="Paste a venue JSON file to import, or export to see it here" value={json} onChangeText={setJson} style={[st.input, { minHeight: 100, textAlignVertical: 'top' }]} maxLength={250000} /><Control label="Import layout JSON" run={() => { try { setLayout(parseLayout(json)); setSelected(''); setNotice('Layout imported. Save a draft to keep it.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Invalid layout.'); } }} />
  </View>;
}
const st = StyleSheet.create({ panel: { backgroundColor: '#fff', padding: 20, borderRadius: 18, borderWidth: 1, borderColor: '#DFE6EB', gap: 16 }, kicker: { fontSize: 10, letterSpacing: 2, color: '#A77B32', fontWeight: '700' }, title: { fontSize: 26, color: '#132F46', fontWeight: '700' }, body: { color: '#60717E', fontSize: 14, lineHeight: 23 }, heading: { color: '#132F46', fontSize: 17, fontWeight: '700' }, input: { borderWidth: 1, borderColor: '#CAD7E0', borderRadius: 10, padding: 12, minHeight: 48, color: '#132F46' }, row: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' }, control: { backgroundColor: '#EAF4FB', padding: 12, minHeight: 44, justifyContent: 'center', borderRadius: 9 }, controlText: { color: '#116CBA', fontWeight: '600', fontSize: 12 }, canvas: { backgroundColor: '#F6F8F9', borderRadius: 12, overflow: 'hidden' }, seat: { minWidth: 44, minHeight: 44, borderWidth: 1, borderColor: '#DFE6EB', borderRadius: 8, alignItems: 'center', justifyContent: 'center', padding: 8 }, selected: { borderColor: '#116CBA', backgroundColor: '#EAF4FB' }, notice: { color: '#132F46', fontSize: 14, lineHeight: 22 } });
