import {useEffect,useRef,useState} from 'react';
import {Platform,Pressable,StyleSheet,Text,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {randomUUID} from 'expo-crypto';
import {useAuth} from './Auth';
import {PrivateRequestStore} from './privateRequests';
import {createTeamController,teamRoles,type TeamMember} from './workspaceTeam';
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[s.button,disabled&&{opacity:.5}]}><Text style={s.buttonText}>{label}</Text></Pressable>;}
export function WorkspaceTeamPanel(){const {session,workspaceId}=useAuth();if(!session||!workspaceId)return null;return <Team key={session.user.id+':'+workspaceId} actor={session.user.id} workspace={workspaceId}/>;}
function Team({actor,workspace}:{actor:string;workspace:string}){
 const {client,workspaceId}=useAuth(),alive=useRef(true),scope=useRef(workspaceId);scope.current=workspaceId;
 const [,render]=useState(0),[confirm,setConfirm]=useState(''),[choices,setChoices]=useState<Record<string,string>>({});
 const current=()=>alive.current&&client.session?.user.id===actor&&scope.current===workspace;
 const controller=useRef<ReturnType<typeof createTeamController>|null>(null);
 if(!controller.current){const namespace=workspace.toLowerCase().replace(/[0-9]/g,d=>String.fromCharCode(103+Number(d)));const store=new PrivateRequestStore({getItem:async key=>Platform.OS==='web'?globalThis.sessionStorage.getItem(key):SecureStore.getItemAsync(key),setItem:async(key,value)=>{if(Platform.OS==='web')globalThis.sessionStorage.setItem(key,value);else await SecureStore.setItemAsync(key,value,{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY});},removeItem:async key=>{if(Platform.OS==='web')globalThis.sessionStorage.removeItem(key);else await SecureStore.deleteItemAsync(key);}},()=>client.session?.user.id,'zoi.team-request.'+namespace+'.');controller.current=createTeamController({workspace,current,rpc:(name,args)=>client.rpc(name,args),storage:{load:()=>store.load(actor),save:value=>store.save(actor,value),clear:()=>store.clear(actor)},nonce:randomUUID,changed:()=>{if(current())render(n=>n+1);}});}
 const team=controller.current;
 useEffect(()=>{alive.current=true;void team.load();return()=>{alive.current=false;team.drop();};},[team]);
 const state=team.state();
 function change(m:TeamMember,action:'role'|'remove',role:string|null){setConfirm('');void team.change(m,action,role);}
 return <View style={s.panel}><Text style={s.title}>Your organization team</Text><Text style={s.body}>Manage existing members. Ownership stays protected; administrators can manage editors and viewers.</Text>{state.message?<Text accessibilityRole="alert" style={s.body}>{state.message}</Text>:null}{state.busy?<Text style={s.body}>Checking your team…</Text>:null}{state.pending?<View style={s.row}><Text style={s.body}>A team change needs confirmation before another can be made.</Text><Action label="Check team change" disabled={state.busy} onPress={()=>void team.recover()}/><Action label="Cancel unconfirmed change" disabled={state.busy} onPress={()=>void team.recover(true)}/></View>:state.snapshot?state.snapshot.members.map(m=>{const allowed=teamRoles(state.snapshot!,m);return <View key={m.id} style={s.row}><Text style={s.name}>{m.name}{m.profile_id===state.snapshot?.actor_profile_id?' · You':''}</Text><Text style={s.body}>{m.role}</Text>{allowed.length?<><View style={s.choices}>{allowed.map(role=><Pressable key={role} accessibilityRole="radio" accessibilityLabel={`${role} role for ${m.name}`} accessibilityState={{checked:(choices[m.id]||m.role)===role,disabled:state.busy}} disabled={state.busy} onPress={()=>setChoices(v=>({...v,[m.id]:role}))} style={[s.choice,(choices[m.id]||m.role)===role&&s.chosen]}><Text style={s.buttonText}>{role}</Text></Pressable>)}</View><View style={s.choices}><Action label={`Save role for ${m.name}`} disabled={state.busy} onPress={()=>change(m,'role',choices[m.id]||m.role)}/><Action label={`Remove ${m.name}`} disabled={state.busy} onPress={()=>setConfirm(m.id)}/></View>{confirm===m.id?<View style={s.confirm}><Text style={s.body}>Remove {m.name}? They will lose access to this organization.</Text><Action label="Keep member" disabled={state.busy} onPress={()=>setConfirm('')}/><Action label="Confirm removal" disabled={state.busy} onPress={()=>change(m,'remove',null)}/></View>:null}</>:null}</View>;}):null}<Action label={state.loaded?'Refresh team':'Load team'} disabled={state.busy||!!state.pending} onPress={()=>{setChoices({});setConfirm('');void team.load();}}/></View>;
}
const s=StyleSheet.create({panel:{padding:16,borderRadius:16,borderWidth:1,borderColor:'#C8D9E8',backgroundColor:'#F5FAFF',gap:12},title:{fontSize:19,fontWeight:'700',color:'#132F46'},name:{fontSize:16,fontWeight:'700',color:'#132F46'},body:{fontSize:14,lineHeight:21,color:'#435E72'},row:{borderTopWidth:1,borderTopColor:'#C8D9E8',paddingTop:14,gap:10},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{padding:12,borderRadius:10,borderWidth:1,borderColor:'#A8C1D8'},chosen:{backgroundColor:'#D8ECFF',borderColor:'#116CBA'},button:{padding:12,minHeight:44,borderRadius:10,borderWidth:1,borderColor:'#A8C1D8',alignSelf:'flex-start'},buttonText:{fontSize:14,fontWeight:'600',color:'#125888'},confirm:{padding:12,borderRadius:12,backgroundColor:'#E5F0FA',gap:10}});
