export type TeamMember={id:string;profile_id:string;name:string;role:string;revision:string;protected:boolean};
export type TeamSnapshot={ok:true;workspace_id:string;actor_profile_id:string;role:string;members:TeamMember[]};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const roles=['owner','admin','editor','viewer'];
export function teamSnapshot(value:any,workspace:string):value is TeamSnapshot{return value?.ok===true&&value.workspace_id===workspace&&uuid.test(value.actor_profile_id)&&roles.includes(value.role)&&Array.isArray(value.members)&&value.members.every((m:any)=>uuid.test(m.id)&&uuid.test(m.profile_id)&&uuid.test(m.revision)&&typeof m.name==='string'&&roles.includes(m.role)&&typeof m.protected==='boolean');}
export function teamRoles(snapshot:TeamSnapshot,member:TeamMember){if(member.protected||member.profile_id===snapshot.actor_profile_id||member.role==='owner')return [];if(snapshot.role==='owner')return ['admin','editor','viewer'];if(snapshot.role==='admin'&&member.role!=='admin')return ['editor','viewer'];return [];}
export function teamDenied(e:any){return [401,403].includes(Number(e?.status||e?.statusCode))||/42501|not_authorized/.test(`${e?.code} ${e?.message}`);}
type Deps={workspace:string;current:()=>boolean;rpc:(name:string,args:any)=>Promise<any>;storage:{load:()=>Promise<any>;save:(value:any)=>Promise<void>;clear:()=>Promise<void>};nonce:()=>string;changed:()=>void};
export function createTeamController(d:Deps){
 let snapshot:TeamSnapshot|null=null,pending:{request:string}|null=null,busy=false,loaded=false,message='';
 const check=()=>{if(!d.current())throw Error('Your account or workspace changed.');};
 async function rpc(name:string,args:any){check();const result=await d.rpc(name,args);check();return result;}
 async function read(){const value=await rpc('workspace_team_get',{p_workspace:d.workspace});if(!teamSnapshot(value,d.workspace))throw Error('Team response could not be verified.');snapshot=value;}
 async function settle(value:any){if(value?.workspace_id!==d.workspace||value.request_id!==pending?.request)throw Error('Team result could not be verified.');let text='';if(value.ok===true&&uuid.test(value.member_id)&&uuid.test(value.profile_id))text='Team change confirmed.';else if(value.cancelled===true)text='Unconfirmed change cancelled.';else if(['membership_conflict','member_missing'].includes(value.error))text='This membership changed elsewhere. Review the current team.';else throw Error('Team change is not confirmed.');await read();await d.storage.clear();check();pending=null;message=text;}
 async function run(fn:()=>Promise<void>){if(busy||!d.current())return;busy=true;d.changed();try{await fn();}catch(e:any){if(d.current()){if(teamDenied(e)){snapshot=null;loaded=false;}message=e?.message||'Team action could not finish.';}}finally{busy=false;if(d.current())d.changed();}}
 return {state:()=>({snapshot,pending,busy,loaded,message}),drop:()=>{snapshot=null;pending=null;loaded=false;message='';},
 load:()=>run(async()=>{loaded=false;snapshot=null;const value=await d.storage.load();check();if(value){if(!uuid.test(value.request)||Object.keys(value).length!==1)throw Error('Recovery reference could not be read.');pending=value;}await read();loaded=true;message='';}),
 change:(member:TeamMember,action:'role'|'remove',role:string|null)=>run(async()=>{if(!loaded||pending||!snapshot)throw Error('Confirm the outstanding change before continuing.');const allowed=teamRoles(snapshot,member);if(!allowed.length||action==='role'&&!allowed.includes(role||''))throw Error('Your role cannot make this change.');if(action==='role'&&role===member.role){message='This role is already saved.';return;}const request={request:d.nonce()};await d.storage.save(request);check();pending=request;try{await settle(await rpc('workspace_team_save',{p_workspace:d.workspace,p_request:request.request,p_profile:member.profile_id,p_member:member.id,p_revision:member.revision,p_action:action,p_role:role}));}catch(e:any){if(teamDenied(e))throw e;if(/team_request_limit|team_receipt_capacity|invalid_team_request|owner_membership_protected|self_membership_protected|owner_required|bad_role/.test(String(e?.message||''))){await d.storage.clear();check();pending=null;throw Error('No change was made. Refresh the team; if the limit persists, contact support.');}throw Error('The team change is not confirmed. Check its result before making another change.');}}),
 recover:(cancel=false)=>run(async()=>{if(!pending)throw Error('No pending request.');const r=await rpc('workspace_team_request',{p_workspace:d.workspace,p_request:pending.request,p_cancel_if_missing:cancel});if(r?.ok!==true||r.workspace_id!==d.workspace||r.request_id!==pending.request)throw Error('Recovery response could not be verified.');if(r.found){await settle(r.result);loaded=true;}else message='No completed change found. Check again or safely cancel it.';})
 };
}
