const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const base=path.resolve(__dirname,'../../..'),out=process.env.QA_OUTPUT_DIR||path.join(base,'docs/audits/evidence/parea-shared-frontdoor-2026-10-03/browser');
const id=n=>'82000000-0000-4000-8000-'+String(n).padStart(12,'0');
const targets={toronto:{id:'4546481e-8995-482a-a0af-f0017613f187',name:'Giannis Ploutarchos & Andromache',starts:'20 March 2027',venue:'Parkview Manor',family:'event'},montreal:{id:'9b241a00-f0c9-5748-8e22-79e2e0b57f79',name:'Giannis Ploutarchos & Andromache · Montréal',starts:'26 March 2027',venue:'Palace Convention Centre',family:'event',slug:'giannis-ploutarchos-andromache-montreal-2027',floor_plan_url:'/assets/events/opa/montreal-2027-floor-plan.jpg'},sparse:{id:id(300),name:'Sparse event acceptance fixture',slug:'sparse-event-fixture',family:'event',starts:null,venue:null}};
const fixture=kind=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Parea candidate · ${kind}</title><link rel="stylesheet" href="/assets/events/signature/customer-a.css"><style>body{margin:0;background:#081322;color:#fff;font:16px system-ui}main{max-width:1250px;margin:auto}#fixture{min-width:0}</style></head><body><main id="fixture"></main><script type="module">
import {mountSignatureCustomer,pareaEventContext} from '/assets/events/signature/customer-a.mjs';
import {eventTablePreference} from '/assets/events/room-plans.mjs';
window.state={actor:'${id(1)}',calls:[],writes:[],failInventory:false,configured:false};const state=window.state;
const members=[['Alex',3],['Maria',1],['Niko',5]].map(([first_name,ticket_quantity],i)=>({id:'${id(10)}'.slice(0,-2)+String(i+10),first_name,ticket_quantity}));
window.ZoiCore={BASE:location.origin,KEY:'fixture-public-key',auth:{isSignedIn:()=>!!state.actor,load:()=>state.actor?{user_id:state.actor,access_token:'x.'+btoa(JSON.stringify({sub:state.actor}))+'.x'}:null},api:{rpc:async(name,args)=>{state.calls.push({name,args});if(name==='saved_guest_group_list')return{ok:true,groups:[{id:'${id(50)}',version:1,archived:false,data:{label:'Our usual parea',arrangement:'together',members}}]};state.writes.push({name,args});throw Error('unexpected_write');}}};
const entity=${JSON.stringify(targets[kind])},context=pareaEventContext({...entity,public_url:'https://www.zoi.city/event/'+entity.slug});context.validateTables=ids=>ids.map(id=>eventTablePreference(entity,id)?.id).filter(Boolean);
window.planner=mountSignatureCustomer({root:document.querySelector('#fixture'),C:ZoiCore,...(${JSON.stringify(kind)}==='toronto'?{}:{context})});if(${JSON.stringify(kind)}==='toronto'){planner.setTableSelection(['9']);planner.setEventId(entity.id);}if(${JSON.stringify(kind)}==='montreal')planner.setTableSelection(['10A']);
</script></body></html>`;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/fixture/')){res.setHeader('Content-Type','text/html');return res.end(fixture(u.pathname.split('/').pop()));}if(u.pathname==='/rest/v1/rpc/table_inventory_map'){res.setHeader('Content-Type','application/json');let body='';for await(const x of req)body+=x;const data=JSON.parse(body);return res.end(JSON.stringify({ok:true,event_id:data.p_event,configured:false,tables:[]}));}const file=path.resolve(base,'.'+u.pathname);if(!file.startsWith(base+path.sep)||!u.pathname.startsWith('/assets/'))throw Error();res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.jpg')?'image/jpeg':file.endsWith('.png')?'image/png':'text/javascript');res.end(await fs.readFile(file));}catch{res.statusCode=404;res.end();}});
(async()=>{await fs.mkdir(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const report={captured_at:new Date().toISOString(),controlled_local_candidate:true,no_live_writes:true,cases:[]};try{for(const width of[390,1440])for(const kind of Object.keys(targets)){
const page=await browser.newPage({viewport:{width,height:1000}}),r={kind,width,errors:[],screenshots:[],checks:[]};report.cases.push(r);page.on('pageerror',e=>r.errors.push(e.message));await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());await page.goto(origin+'/fixture/'+kind);await page.locator('[data-count]').waitFor();
const capture=async phase=>{await page.locator('.sig-a-work').evaluate(el=>el.scrollIntoView({block:'start'}));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,kind+'-'+width+'-'+phase+'.png')});if(phase==='group-3-1-5'||phase==='review-share')await page.locator('.sig-a-work').screenshot({path:path.join(out,kind+'-'+width+'-'+phase+'-full.png')});r.screenshots.push(phase);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);};
await page.locator('[data-count]').fill('9');await page.locator('[data-next]').click();for(let i=0;i<3;i++){if(i)await page.locator('[data-add-recipient]').click();await page.locator('[data-recipient-name]').nth(i).fill(['Alex','Maria','Niko'][i]);await page.locator('[data-ticket-quantity]').nth(i).fill(String([3,1,5][i]));}await page.locator('.sig-a-recipient-contacts summary').first().click();await page.locator('[data-recipient-email]').first().fill('alex@example.org');await page.locator('[data-recipient-tel]').first().fill('+1 416 555 1234');assert.match(await page.locator('[data-allocation-status]').innerText(),/9 of 9/);await capture('group-3-1-5');
await page.locator('[data-pick-contact]').nth(1).click();await page.locator('dialog[open] [name=name]').fill('Maria');await page.locator('dialog[open] [name=email]').fill('maria@example.org');await page.locator('dialog[open] [name=tel]').fill('+1 514 555 5678');await capture('contact-open');await page.locator('dialog[open]').getByRole('button',{name:'Use these details',exact:true}).click();assert.equal(await page.locator('[data-recipient-email]').nth(1).inputValue(),'maria@example.org');await page.locator('[data-next]').click();await page.locator('[data-review-message]').first().click();const msg=await page.locator('[data-person-message]').first().inputValue();assert.match(msg,/Alex: 3 tickets in our group of 9/);assert.match(msg,/not a booking/);assert(!msg.includes('maria@example.org'));const links=await page.locator('[data-person-channels]').first().locator('a').evaluateAll(es=>es.map(e=>e.href));assert.equal(links.length,2);assert.equal(decodeURIComponent(links[0].split('body=')[1]),msg);assert.equal(new URL(links[1]).searchParams.get('body'),msg);await capture('review-share');if(kind==='montreal'){assert.match(msg,/table preference: 10A/);assert.match(await page.locator('.sig-a-choice').innerText(),/Table 10A/);}if(kind==='toronto')assert.match(await page.locator('.sig-a-allocation-total').innerText(),/1,800\.00/);else assert.match(await page.locator('.sig-a-allocation-total').innerText(),/To confirm/);
await page.locator('[data-check-ticket-setup]').click();await page.getByText('Ticket inventory is not configured on Zoi for this event.',{exact:false}).waitFor();const host=await page.locator('.sig-a-host-handoff a').getAttribute('href');assert.equal(host,'/tickets/hosts/?event='+targets[kind].id);r.host_handoff=host;r.message=msg;r.composers=links;await capture('host-unconfigured');
await page.route('**/rest/v1/rpc/table_inventory_map',route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'fixture_error'})}));await page.locator('[data-check-ticket-setup]').click();await page.getByText('Ticket setup could not be checked.',{exact:false}).waitFor();assert.equal(await page.locator('[data-check-ticket-setup]').isEnabled(),true);await page.unroute('**/rest/v1/rpc/table_inventory_map');await page.locator('[data-check-ticket-setup]').click();await page.getByText('Ticket inventory is not configured on Zoi for this event.',{exact:false}).waitFor();r.checks.push('inventory error preserves draft and explicit retry succeeds');

await page.locator('[data-usual-group] summary').click();await page.getByRole('button',{name:'Our usual parea · 9 tickets',exact:true}).click();await page.getByRole('button',{name:'Use this group',exact:true}).click();assert.equal(await page.locator('[data-recipient-name]').count(),3);assert.deepEqual(await page.locator('[data-ticket-quantity]').evaluateAll(es=>es.map(e=>Number(e.value))),[3,1,5]);assert.deepEqual(await page.locator('[data-recipient-email]').evaluateAll(es=>es.map(e=>e.value)),['','','']);r.checks.push('saved crew 3/1/5 without contacts');await capture('saved-crew-reuse');await page.locator('[data-ticket-quantity]').first().fill('10');await page.locator('[data-next]').click();assert.equal(await page.locator('[data-review-message]').count(),0);assert.match(await page.locator('.sig-a-status').innerText(),/too many/);r.checks.push('over-allocation blocked');await page.evaluate(()=>{state.actor='${id(2)}';dispatchEvent(new Event('zoi:auth-change'));});assert.equal(await page.locator('[data-count]').inputValue(),'2');assert.equal(await page.locator('[data-recipient-name]').count(),0);assert.equal(await page.evaluate(()=>state.writes.length),0);r.checks.push('account change clears contacts/group; zero writes');assert.deepEqual(r.errors,[]);await page.close();
} }finally{await browser.close();await new Promise(r=>server.close(r));const bytes=JSON.stringify(report,null,2)+'\n';const {credentialFindings}=await import('../../../scripts/check-source-credentials.mjs');if(credentialFindings(bytes).length)throw Error('credential_in_report');await fs.writeFile(path.join(out,'report.json'),bytes);}console.log(JSON.stringify({cases:report.cases.length,checks:report.cases.map(r=>({kind:r.kind,width:r.width,checks:r.checks,errors:r.errors}))}));})().catch(e=>{console.error(e);process.exitCode=1;});
