const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const assert=require('node:assert/strict');
const {chromium}=require('playwright-core');
const base=path.resolve(process.env.ARRIVAL_BASE||process.cwd());
const out=path.resolve(process.env.ARRIVAL_EVIDENCE||'docs/audits/evidence/public-arrival-producer-2026-10-03/browser');
fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{let target=path.join(base,decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,'index.html');if(!target.startsWith(base)||!fs.existsSync(target)){res.writeHead(404);res.end('Missing');return;}res.writeHead(200,{'Content-Type':mime[path.extname(target)]||'application/octet-stream'});fs.createReadStream(target).pipe(res);});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({executablePath:'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const report={basis:'Full candidate index and unchanged repo assets. Controlled remote read transport only; no account or writes.',cases:[]};try{
for(const width of [390,1440])for(const theme of ['light','dark']){
 const context=await browser.newContext({viewport:{width,height:960},isMobile:width===390,hasTouch:width===390,serviceWorkers:'block',reducedMotion:'reduce'});await context.addInitScript(t=>localStorage.setItem('zoi_theme',t),theme);const page=await context.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));let outage=true;
 await page.route('https://**/*',async route=>{const url=route.request().url();if(url.includes('/rest/v1/rpc/')){const name=url.split('/').pop();requests.push({name,method:route.request().method(),body:route.request().postData()});assert(!['waitlist_join'].includes(name),'No public write');await new Promise(r=>setTimeout(r,outage?1500:0));await route.fulfill({status:outage?503:200,contentType:'application/json',body:JSON.stringify(outage?{code:'PGRST002'}:name==='home_stats'?{listings:1,cities:1,countries:1}:name==='zoi_namedays_today'?{names:[]}:[])});}else if(url.includes('fonts.googleapis')||url.includes('fonts.gstatic'))await route.continue();else await route.fulfill({status:503,body:'Unavailable'});});
 await page.goto(origin,{waitUntil:'domcontentloaded'});await page.locator('.za-photo img').evaluate(img=>img.decode());await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(300);assert.equal(await page.locator('#zoiCta').innerText(),'Join Zoi');assert.equal(requests.length,0,'No arrival RPC before guest expands live content');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);assert.equal(await page.locator('.za-photo img').evaluate(img=>img.naturalWidth),3000);assert.equal(await page.locator('.za-frontdoors a').count(),4);assert(await page.locator('#za-business').isHidden());await page.screenshot({path:path.join(out,`${width}-${theme}-arrival.png`)});
 await page.locator('[data-za-path="business"]').click();assert(await page.locator('#za-people').isHidden());await page.locator('#za-business summary').click();assert(await page.locator('#za-business details').getAttribute('open')!==null);assert.equal(await page.locator('#za-business a').last().getAttribute('href'),'/social/bizpage');await page.screenshot({path:path.join(out,`${width}-${theme}-business.png`)});
 await page.locator('[data-za-path="people"]').click();await page.locator('#za-people summary').click();assert(await page.locator('#za-people details').innerText().then(t=>t.includes('Public browsing stays open')));await page.screenshot({path:path.join(out,`${width}-${theme}-people.png`)});
 const rail=page.locator('.za-rail');await rail.focus();await page.keyboard.press('End');await page.waitForTimeout(100);const end=await rail.evaluate(e=>e.scrollLeft);assert(end>100);await page.keyboard.press('Home');await page.waitForTimeout(100);assert(await rail.evaluate(e=>e.scrollLeft)<3);await page.locator('[data-za-scroll="1"]').click();await page.waitForTimeout(100);assert(await rail.evaluate(e=>e.scrollLeft)>100);
 await page.locator('#za-daily > summary').click();await page.locator('.za-pulse-retry').first().waitFor({timeout:10000});assert.equal(await page.locator('.za-pulse-retry').count(),3);assert(!(await page.locator('#community-pulse').innerText()).includes('No namedays today'),'503 must not be empty');assert.equal(await page.locator('#za-daily').evaluate(e=>e.open),true);await page.screenshot({path:path.join(out,`${width}-${theme}-unavailable.png`)});outage=false;await page.locator('.za-pulse-retry').first().click();await page.locator('#community-pulse').getByText('No namedays today',{exact:true}).waitFor();assert.equal(await page.locator('.za-pulse-retry').count(),0);assert.equal(requests.filter(r=>r.name==='feed_list').length,2);await page.screenshot({path:path.join(out,`${width}-${theme}-recovered-empty.png`)});
 await page.locator('#arrival-query').fill('SIGNAT & Montréal');await page.locator('.za-search button').click();await page.waitForURL('**/explore/?q=**');assert.equal(new URL(page.url()).searchParams.get('q'),'SIGNAT & Montréal');assert.equal(errors.length,0,JSON.stringify(errors));report.cases.push({width,theme,reducedMotion:true,heroOriginal:[3000,1996],overflow:false,requests,errors,searchQuery:new URL(page.url()).searchParams.get('q'),passed:true});await context.close();
}
fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.cases.length,out}));}catch(error){report.failure=error.stack;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));throw error;}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
