const{chromium}=require('playwright-core'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');const base=path.resolve(__dirname,'../../..'),out=process.env.OUTPUT_DIR||'/tmp/suite-authority-specialist';
const server=http.createServer(async(req,res)=>{try{const f=path.resolve(base,'.'+new URL(req.url,'http://local').pathname);if(!f.startsWith(base+'/'))throw Error();let body=await fs.readFile(f);if(f.endsWith('fixture.html')){const shell=await fs.readFile(path.join(base,'social/index.html'),'utf8');body=body.toString().replace('</head>','<link rel="stylesheet" href="/assets/zoi-theme.css">'+shell.match(/<style>[\s\S]*?<\/style>/)[0]+'</head>');}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'text/javascript');res.end(body);}catch{res.statusCode=404;res.end();}});
(async()=>{await fs.mkdir(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const origin='http://127.0.0.1:'+server.address().port;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const findings=[];for(const width of[390,1440])for(const module of['audience','email','bio','settings']){const p=await browser.newPage({viewport:{width,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await p.goto(origin+'/tests/browser/suite-authority/fixture.html?module='+module);await p.waitForFunction(()=>document.querySelectorAll('#root input').length>0||document.querySelector('[data-z=new]')||document.querySelector('[data-z=add]'));
if(module==='audience'){await p.getByRole('button',{name:'+ Add contact',exact:true}).click();await p.locator('[data-z=f_name]').fill('Private contact');await p.locator('[data-z=f_email]').fill('qa@example.invalid');await p.locator('[data-z=f_save]').click();await p.getByText('Contact added.',{exact:true}).waitFor();await p.getByRole('button',{name:'Edit',exact:true}).click();await p.evaluate(()=>qa.session=false);await p.locator('[data-z=f_save]').click();await p.getByText('suite_session_unavailable',{exact:true}).waitFor();assert.equal(await p.locator('[data-z=f_name]').count(),0);assert.equal(await p.getByText('Private contact',{exact:true}).count(),0);findings.push({width,module,sessionExpiredFormVisible:0});}
if(module==='email'){await p.locator('[data-z=subject]').fill('Private campaign');await p.locator('[data-z=body]').fill('Private campaign body');await p.locator('[data-z=save]').click();await p.getByText('Draft saved.',{exact:true}).waitFor();await p.locator('[data-z=sched_toggle]').click();await p.locator('[data-z=sched_at]').fill('2028-10-01T20:00');await p.locator('[data-z=sched_go]').click();await p.waitForFunction(()=>qa.campaigns[0]?.status==='scheduled');await p.locator('[data-z=unsched]').waitFor();await p.screenshot({path:path.join(out,module+'-owner-'+width+'.png')});await p.locator('[data-z=unsched]').click();await p.waitForFunction(()=>qa.campaigns[0]?.status==='draft');await p.evaluate(()=>{qa.actor='99999999-9999-4999-8999-999999999999';window.dispatchEvent(new Event('zoi:auth-change'));});assert.equal(await p.locator('#root').innerText(),'');findings.push({width,module,afterAccountChangeText:''});}
if(module==='bio'){await p.getByPlaceholder('e.g. Maria’s Bakery').fill('Private client bio');await p.getByRole('button',{name:'Save draft',exact:true}).click();await p.getByText('Saved as draft.',{exact:true}).waitFor();await p.getByRole('switch').click();await p.getByRole('button',{name:'Save & publish',exact:true}).click();await p.getByText('Saved & published.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>qa.bio.published),true);await p.screenshot({path:path.join(out,module+'-owner-'+width+'.png')});await p.evaluate(()=>{qa.actor='99999999-9999-4999-8999-999999999999';window.dispatchEvent(new Event('zoi:auth-change'));});assert.equal(await p.locator('#root').innerText(),'');findings.push({width,module,afterAccountChangeText:''});}
if(module==='settings'){await p.getByLabel('Workspace name').fill('Updated workspace');await p.getByRole('button',{name:'Save name',exact:true}).click();await p.getByText('Settings saved and confirmed.',{exact:true}).waitFor();await p.evaluate(()=>qa.session=false);await p.getByLabel('Workspace name').fill('No longer allowed');await p.getByRole('button',{name:'Save name',exact:true}).click();await p.waitForFunction(()=>document.querySelectorAll('#root input').length===0);findings.push({width,module,remainingInputs:0});}
await p.screenshot({path:path.join(out,module+'-'+width+'.png')});assert.deepEqual(errors,[]);
if(['email','bio'].includes(module)){
 const ready=async()=>{await p.goto(origin+'/tests/browser/suite-authority/fixture.html?module='+module);await p.locator(module==='email'?'[data-z=subject]':'input[placeholder="e.g. Maria’s Bakery"]').waitFor();};
 const fill=async()=>{if(module==='email'){await p.locator('[data-z=subject]').fill('Private queued campaign');await p.locator('[data-z=body]').fill('Private queued body');}else await p.getByPlaceholder('e.g. Maria’s Bakery').fill('Private queued bio');};
 const save=()=>module==='email'?p.locator('[data-z=save]').click():p.getByRole('button',{name:'Save draft',exact:true}).click();
 await ready();await fill();await p.evaluate(()=>qa.role='viewer');await save();await p.getByText(/Your workspace access changed/).waitFor();assert.equal(await p.locator('#root input').count(),0);assert.equal(await p.evaluate(()=>qa.writes.length),0);
 await ready();await fill();await p.evaluate(()=>qa.mode='held-write');await save();await p.waitForFunction(()=>typeof qa.release==='function');await p.evaluate(()=>{qa.actor='99999999-9999-4999-8999-999999999999';window.dispatchEvent(new Event('zoi:auth-change'));qa.release();});await p.waitForTimeout(50);assert.equal(await p.locator('#root').innerText(),'');assert.equal(await p.locator('#status').innerText(),'');assert.equal(await p.evaluate(()=>qa.writes.length),1);
 await ready();await p.evaluate(()=>{qa.mode='held';qa.mount();});await p.waitForFunction(()=>typeof qa.release==='function');await p.evaluate(()=>{qa.ctx.ws='88888888-8888-4888-8888-888888888888';document.querySelector('#root').textContent='New workspace';qa.release();});await p.waitForTimeout(50);assert.equal(await p.locator('#root').innerText(),'New workspace');
 await ready();await fill();await p.evaluate(()=>qa.ctx.ws='88888888-8888-4888-8888-888888888888');await save();assert.equal(await p.evaluate(()=>qa.writes.length),0);assert.equal(await p.locator('#root').innerText(),'');assert.deepEqual(errors,[]);
 findings.push({width,module,roleDenialClear:true,delayedWriteIgnored:true,delayedWorkspaceReadIgnored:true,newWriteAfterScopeChange:false});
}
await p.close();}await fs.writeFile(path.join(out,'findings.json'),JSON.stringify(findings,null,2));console.log(JSON.stringify(findings));}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
