import vm from'node:vm';import{readFile,writeFile}from'node:fs/promises';import assert from'node:assert/strict';
const source=await readFile(new URL('../../../assets/zoi-core.js',import.meta.url),'utf8');const A='10000000-0000-4000-8000-000000000001',B='10000000-0000-4000-8000-000000000002';const session=(id,token=id,seconds=3600)=>({user_id:id,access_token:token,refresh_token:'fixture-refresh',expires_at:Date.now()/1000+seconds});const response=data=>new Response(JSON.stringify(data),{status:200});
function setup(fetch){const store=new Map(),context={fetch,AbortController,Promise,Date,setTimeout,clearTimeout,atob,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)}};vm.createContext(context);vm.runInContext(source,context);return{C:context.ZoiCore,store}}
let results=[];
for(const mode of['require','prefer']){let headers=[];const{C}=setup(async(url,o)=>{headers.push(o.headers.Authorization);return response({private:'A'})});C.auth.save(session(A,'A-token'));const pending=C.api.rpc('private_write',{draft:'A'},{auth:mode}).then(()=>true,()=>false);C.auth.save(session(B,'B-token'));const accepted=await pending;results.push({case:mode+'-switch-before-send',sends:headers.length,usedActor:headers[0]?.includes('B-token')?'B':headers[0]?'A':null,accepted});}
{let sends=0;const{C}=setup(async()=>{sends++;return response({ok:true})});C.auth.save(session(A));const p=C.api.rpc('private_write',{}, {auth:'require'}).then(()=>true,()=>false);C.auth.clear();C.auth.save(session(A,'A-new-login'));results.push({case:'same-actor-logout-relogin-before-send',accepted:await p,sends});}
{let finish;const{C,store}=setup(()=>new Promise(r=>finish=r));C.auth.save(session(A));const p=C.api.rpc('private_read',{}, {auth:'require'}).then(()=>true,()=>false);await new Promise(r=>setTimeout(r,0));store.set('zoi_auth',JSON.stringify(session(B)));C.auth.load();finish(response({private:'A'}));results.push({case:'cross-tab-load-during-read',accepted:await p});}
{let finish;const{C}=setup((url)=>url.includes('/auth/')?Promise.resolve(response({access_token:'A-refreshed',refresh_token:'rotated',expires_in:3600,user:{id:A}})):new Promise(r=>finish=r));C.auth.save(session(A,'A-old',25));const p=C.api.rpc('private_read',{}, {auth:'prefer'}).then(()=>true,()=>false);await new Promise(r=>setTimeout(r,0));assert.equal(await C.auth.ensureFresh(),true);finish(response({private:'A'}));results.push({case:'same-actor-refresh-during-read',accepted:await p});}
console.log(JSON.stringify(results,null,2));await writeFile(process.env.OUTPUT||'/tmp/core-session-transition-audit.json',JSON.stringify(results,null,2));if(process.env.EXPECT_FIXED==='1'){assert(results.slice(0,3).every(r=>r.sends===0&&!r.accepted));assert.equal(results[3].accepted,false);assert.equal(results[4].accepted,true)}
