import vm from'node:vm';import{readFile,writeFile}from'node:fs/promises';import assert from'node:assert/strict';
const source=await readFile(new URL('../../../assets/zoi-core.js',import.meta.url),'utf8'),A='10000000-0000-4000-8000-000000000001',B='10000000-0000-4000-8000-000000000002',S='20000000-0000-4000-8000-000000000001',T='20000000-0000-4000-8000-000000000002';const jwt=(id,sid,revision=1)=>'e30.'+Buffer.from(JSON.stringify({sub:id,session_id:sid,iat:revision})).toString('base64url')+'.sig',session=(id=A,sid=S)=>({user_id:id,access_token:jwt(id,sid),refresh_token:'fixture',expires_at:Date.now()/1000+20});const response=j=>new Response(JSON.stringify(j));
function setup(fetch){const store=new Map(),events=new EventTarget(),c={fetch,AbortController,Promise,Date,setTimeout,clearTimeout,atob,CustomEvent,dispatchEvent:e=>events.dispatchEvent(e),addEventListener:(...a)=>events.addEventListener(...a),localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)}};vm.createContext(c);vm.runInContext(source,c);return{C:c.ZoiCore,events,store}}
const results=[];
for(const [name,id,sid,user,expected]of[['same-session',A,S,A,true],['wrong-actor',B,S,B,false],['wrong-session',A,T,A,false],['conflicting-metadata',B,S,A,false]]){let sends=0;const{C}=setup(async url=>url.includes('/auth/')?response({access_token:jwt(id,sid,2),expires_in:3600,user:{id:user}}):(sends++,response({ok:true})));C.auth.save(session());const ok=await C.api.rpc('private',{}, {auth:'require'}).then(()=>true,()=>false);results.push({name,accepted:ok,sends,storedActor:C.auth.load()?.user_id,storedTokenUnchanged:C.auth.load()?.access_token===jwt(A,S)});assert.equal(ok,expected);assert.equal(sends,expected?1:0);if(!expected)assert.equal(C.auth.load()?.access_token,jwt(A,S))}
{let finish;const{C}=setup(async()=>({ok:true,status:200,text:()=>new Promise(r=>finish=r)}));C.auth.save({...session(),expires_at:Date.now()/1000+3600});const p=C.api.rpc('private',{}, {auth:'require'}).then(()=>true,()=>false);await new Promise(r=>setTimeout(r,0));C.auth.save({...session(B,T),expires_at:Date.now()/1000+3600});finish('{"ok":true}');const accepted=await p;assert.equal(accepted,false);results.push({name:'body-held-switch',accepted})}
for(const mode of['anon','prefer']){let bearer;const{C}=setup(async(u,o)=>{bearer=o.headers.Authorization;return response({ok:true})});const p=C.api.rpc('public',{}, {auth:mode});C.auth.save({...session(),expires_at:Date.now()/1000+3600});await p;assert.equal(bearer,'Bearer '+C.KEY);results.push({name:mode+'-anonymous-start-stays-anonymous',pass:true})}
for(const kind of['refresh','verify']){let finish;const{C,store}=setup(()=>new Promise(r=>finish=r));C.auth.save(session());const pending=(kind==='refresh'?C.auth.ensureFresh():C.otp.verify('fixture@example.invalid','123456')).then(x=>!!x,()=>false);store.set('zoi_auth',JSON.stringify({...session(B,T),expires_at:Date.now()/1000+3600}));finish(response({access_token:jwt(A,S,2),expires_in:3600,user:{id:A}}));const accepted=await pending,storedActor=C.auth.load()?.user_id;results.push({name:'unobserved-storage-before-'+kind+'-commit',accepted,storedActor});assert.equal(accepted,false);assert.equal(storedActor,B)}
console.log(JSON.stringify(results,null,2));await writeFile('/tmp/core-session-transition-extended.json',JSON.stringify(results,null,2));
