// One real deployed, signed-out acceptance batch. No route fixtures or account/write actions.
const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const origin='https://www.zoi.city',commit=process.env.GUEST_EXPECTED_COMMIT,assetBase=process.env.GUEST_ASSET_BASE,out=process.env.QA_OUTPUT_DIR,hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const targets=[{kind:'toronto',url:'/events/giannis-ploutarchos-andromache-toronto-2027/',id:'4546481e-8995-482a-a0af-f0017613f187',slug:'giannis-ploutarchos-andromache-toronto-2027'},{kind:'montreal',url:'/event/giannis-ploutarchos-andromache-montreal-2027',id:'9b241a00-f0c9-5748-8e22-79e2e0b57f79',slug:'giannis-ploutarchos-andromache-montreal-2027'}];
const assets=new Set(['/assets/events/guest-planning.mjs','/assets/events/signature/private-plan.mjs','/assets/events/signature/customer-a.mjs','/assets/events/signature/customer-a.css','/assets/events/signature/experience.mjs','/assets/homes/templates/events/client.mjs']);
const privateRPC=/^(?:event_plan_|home_content_|table_(?:inventory_configure|reservation_)|event_payment_policy_configure|ops_mutation_|invitation_(?:issue|send)|zoi_me)/;
const publicRead=new Set(['home_entity','table_inventory_map','event_placements_public','event_artists','event_service_menu_public','inquiry_availability','social_public_feed','home_social_feed']);
const safeURL=value=>{const u=new URL(value);return u.origin+u.pathname+(['v','slug'].filter(k=>u.searchParams.has(k)).map((k,i)=>(i?'&':'?')+k+'='+encodeURIComponent(u.searchParams.get(k))).join(''));};
const settle=async tasks=>{for(let n=0;n<3;n++){const snapshot=[...tasks];await Promise.allSettled(snapshot);if(snapshot.length===tasks.length)return;}};
(async()=>{
 assert.match(commit||'',/^[a-f0-9]{40}$/);assert.equal(process.env.GUEST_DEPLOY_READY,commit,'Root exact commit READY is required before any request');assert(assetBase&&out,'Exact release stage and new evidence output are required');
 await fs.mkdir(out,{recursive:true});assert.equal(await fs.stat(path.join(out,'report.json')).then(()=>true,()=>false),false,'Never overwrite a retained production run');
 const report={started_at:new Date().toISOString(),expected_ready_commit:commit,actual_production:true,no_routes_or_fixtures:true,no_account:true,no_writes:true,no_messages_or_composers:true,scope:'Exactly two widths for Toronto and canonical Montréal, once each; one explicit public ticket-setup check per loaded planner',cases:[]};let browser;
 try{
 browser=await chromium.launch({executablePath:'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 for(const target of targets)for(const width of[390,1440]){
  const context=await browser.newContext({viewport:{width,height:1000},serviceWorkers:'block'}),page=await context.newPage(),tasks=[],started=new Map(),item={kind:target.kind,width,event_id:target.id,errors:[],rpcs:[],assets:[],request_failures:[],non_read_requests:[],checks:[],status:'running'};report.cases.push(item);
  page.on('pageerror',e=>item.errors.push(e.message));page.on('request',r=>{started.set(r,Date.now());const u=new URL(r.url()),fn=u.pathname.includes('/rpc/')?u.pathname.split('/').pop():null;if(privateRPC.test(fn||''))item.non_read_requests.push({method:r.method(),url:safeURL(r.url()),rpc:fn,private:true});else if(!['GET','HEAD','OPTIONS'].includes(r.method())&&!(fn&&publicRead.has(fn)))item.non_read_requests.push({method:r.method(),url:safeURL(r.url()),rpc:fn});});
  page.on('requestfailed',r=>item.request_failures.push({url:safeURL(r.url()),error:r.failure()?.errorText}));
  page.on('response',r=>{const u=new URL(r.url()),fn=u.pathname.includes('/rpc/')?u.pathname.split('/').pop():null;if(fn||assets.has(u.pathname))tasks.push((async()=>{const entry={url:safeURL(r.url()),status:r.status(),latency_ms:Date.now()-(started.get(r.request())||Date.now())};if(fn){entry.name=fn;try{const d=await r.json();entry.code=d?.code||null;if(r.status()>=400)entry.message=typeof d?.message==='string'?d.message.slice(0,300):null;else if(fn==='home_entity'){entry.identity={id:d.id,type:d.entity_type,slug:d.canonical_slug||d.slug};}else if(fn==='table_inventory_map'){entry.inventory={event_id:d.event_id,configured:d.configured,table_count:Array.isArray(d.tables)?d.tables.length:null};}}catch{entry.body_unparsed=true;}item.rpcs.push(entry);}else{const b=await r.body(),expected=await fs.readFile(path.join(assetBase,u.pathname));entry.path=u.pathname;entry.bytes=b.length;entry.actual_sha256=hash(b);entry.expected_sha256=hash(expected);entry.matches=entry.actual_sha256===entry.expected_sha256;item.assets.push(entry);}})().catch(e=>item.errors.push('Response capture failed: '+e.message)));});
  try{
   const response=await page.goto(origin+target.url,{waitUntil:'domcontentloaded',timeout:60000});item.document={url:safeURL(page.url()),status:response.status(),bytes_sha256:hash(await response.body()),charset:await page.evaluate(()=>document.characterSet)};
   if(response.status()!==200){item.status='public_service_unavailable';item.dom=await page.locator('body').innerText();item.checks.push('canonical document did not load; no guest capability inferred');continue;}
   assert.equal(item.document.charset,'UTF-8');
   const loaded=await page.locator('[data-count]').first().waitFor({timeout:25000}).then(()=>true,()=>false);
   if(!loaded){item.status='guest_render_unavailable';item.dom=await page.locator('body').innerText();item.checks.push('document200 without usable guest planner is not acceptance');continue;}
   assert.equal(await page.evaluate(()=>window.ZoiCore?.auth?.load?.()?.user_id||null),null);
   item.title=await page.locator('h1').first().innerText();
   if(target.kind==='montreal'){const data=JSON.parse(await page.locator('#event-home-content').textContent());assert.equal(data.entity.id,target.id);assert.equal(data.entity.slug,target.slug);item.source={id:data.entity.id,name:data.entity.name,slug:data.entity.slug};assert(item.title.includes(data.entity.name),'Exact Unicode public event name');}
   await page.locator('[data-count]').fill('9');
   if(target.kind==='toronto'){await page.locator('#signature-room canvas').first().waitFor({timeout:35000});await page.locator('#signature-room [data-details-toggle]').click();await page.locator('#signature-room [data-find]').selectOption('9');await page.locator('#signature-room [data-request]').click();item.checks.push('actual source Table9 selection reaches guest planner');}
   await page.locator('[data-count]').fill('9');await page.locator('[data-next]').click();
   for(let i=0;i<3;i++){if(i)await page.locator('[data-add-recipient]').click();await page.locator('[data-recipient-name]').nth(i).fill(['Guest A','Guest B','Guest C'][i]);await page.locator('[data-ticket-quantity]').nth(i).fill(String([3,1,5][i]));}
   assert.match(await page.locator('[data-allocation-status]').innerText(),/9 of 9/);await page.locator('[data-next]').click();
   await page.locator('[data-event-setup]').waitFor();await page.waitForFunction(()=>document.querySelector('[data-event-setup]')?.getAttribute('aria-busy')!=='true',{},{timeout:15000});
   item.setup_before=await page.locator('[data-event-setup]').innerText();await page.locator('[data-check-ticket-setup]').click();await page.waitForFunction(()=>document.querySelector('[data-event-setup]')?.getAttribute('aria-busy')!=='true',{},{timeout:15000});item.setup_after=await page.locator('[data-event-setup]').innerText();
   await settle(tasks);const failed=item.rpcs.some(r=>['home_entity','table_inventory_map'].includes(r.name)&&r.status>=400),map=item.rpcs.filter(r=>r.name==='table_inventory_map'&&r.status===200).at(-1),identity=item.rpcs.filter(r=>r.name==='home_entity'&&r.status===200).at(-1);
   if(identity){assert.equal(identity.identity.id,target.id);assert.equal(identity.identity.slug,target.slug);}
   if(map){assert.equal(map.inventory.event_id,target.id);assert.equal(typeof map.inventory.configured,'boolean');}
   if(item.setup_after.includes('not configured'))assert(map&&map.inventory.configured===false,'Only actual successful configured:false may be called unconfigured');
   item.setup_classification=/temporarily unavailable/.test(item.setup_after)?'service_unavailable':map?.inventory.configured===false?'verified_unconfigured':map?.inventory.configured===true?'verified_configured':'unresolved';
   if(failed&&!map)assert.equal(item.setup_classification,'service_unavailable');
   item.checks.push('one deliberate public setup check; unavailable versus verified configured:false kept distinct');
   assert.equal(await page.locator('[data-message-review]:not([hidden])').count(),0);assert.equal(await page.locator('[data-person-channels] a').count(),0);
   await page.locator('[data-stage="1"]').first().click();assert.deepEqual(await page.locator('[data-recipient-name]').evaluateAll(nodes=>nodes.map(n=>n.value)),['Guest A','Guest B','Guest C']);assert.deepEqual(await page.locator('[data-ticket-quantity]').evaluateAll(nodes=>nodes.map(n=>Number(n.value))),[3,1,5]);item.checks.push('3/1/5 anonymous group preserved through public setup result; no contacts, composers or private save');
   item.render={overflow:await page.evaluate(()=>document.documentElement.scrollWidth),planner_text:await page.locator('.sig-a-work').innerText(),private_panel:await page.locator('.sig-a-private').evaluate(e=>({background:getComputedStyle(e).backgroundImage,text:getComputedStyle(e).color})),canvas_count:await page.locator('canvas').count()};assert.equal(item.render.overflow,width);await settle(tasks);assert.deepEqual(item.errors,[]);assert.deepEqual(item.non_read_requests,[]);for(const required of['/assets/events/guest-planning.mjs','/assets/events/signature/private-plan.mjs','/assets/events/signature/customer-a.mjs','/assets/events/signature/customer-a.css'])assert(item.assets.some(a=>a.path===required),required+' must actually load');assert(item.assets.every(a=>a.status===200&&a.matches),'Actual loaded module bytes must match exact release stage');item.status=['service_unavailable','unresolved'].includes(item.setup_classification)?'degraded_guest_usable':'public_guest_passed';
  }catch(e){item.status='failed';item.failure=e.message;}
  finally{await settle(tasks);item.elapsed_ms=Date.now()-(started.values().next().value||Date.now());await page.screenshot({path:path.join(out,target.kind+'-'+width+'.png'),fullPage:true}).catch(e=>item.screenshot_error=e.message);await context.close();}
 }
 report.status=report.cases.some(c=>c.status==='failed')?'failed':report.cases.every(c=>c.status==='public_guest_passed')?'passed':'partial';report.completed_at=new Date().toISOString();
 }finally{await browser?.close();const bytes=JSON.stringify(report,null,2)+'\n',{credentialFindings}=await import('../../../scripts/check-source-credentials.mjs');assert.equal(credentialFindings(bytes).length,0,'Do not retain credential-bearing evidence');await fs.writeFile(path.join(out,'report.json'),bytes);console.log(JSON.stringify({status:report.status,commit,cases:report.cases.map(c=>({kind:c.kind,width:c.width,status:c.status,setup:c.setup_classification}))}));if(report.status!=='passed')process.exitCode=report.status==='partial'?2:1;}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
