const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process'),{chromium}=require('playwright-core');
const commit=process.env.RELEASE_COMMIT,deployment=process.env.RELEASE_DEPLOYMENT,out=process.env.EVIDENCE_DIR;
if(!commit||!deployment||!out)throw Error('Exact deployment commit and evidence path required');
const origin='https://www.zoi.city',report={commit,deployment,actual_production:true,physical_device:false,room_heights_and_furniture:'illustrations, not surveyed or available inventory',cases:[],assets:[]};
const controls=room=>room.locator('.fc-controls,.rs-toolbar').evaluate(bar=>{const a=bar.getBoundingClientRect();return{width:bar.clientWidth,scroll:bar.scrollWidth,height:a.height,buttons:[...bar.querySelectorAll('button')].filter(b=>getComputedStyle(b).display!=='none').map(b=>{const r=b.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{text:b.textContent.trim(),fits:r.left>=a.left&&r.right<=a.right+1&&r.top>=a.top&&r.bottom<=a.bottom+1,height:r.height,hit:hit===b||b.contains(hit)};})};});
(async()=>{await fs.mkdir(out,{recursive:true});let browser;
try{
for(const file of ['/assets/events/signature/furnished-concert.mjs','/assets/events/room-scene.mjs','/assets/events/room-brand.css','/assets/events/room-scene.css']){
 const r=await fetch(origin+file),actual=Buffer.from(await r.arrayBuffer()),expected=cp.execFileSync('git',['show',commit+':'+file.slice(1)]),sha=b=>crypto.createHash('sha256').update(b).digest('hex');report.assets.push({path:file,status:r.status,served_sha256:sha(actual),expected_sha256:sha(expected)});assert.equal(r.status,200);assert.equal(sha(actual),sha(expected));
}
browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--enable-unsafe-swiftshader']});
for(const city of['toronto','montreal'])for(const width of[390,1440]){
 const context=await browser.newContext({viewport:{width,height:900},hasTouch:width===390,reducedMotion:'reduce',serviceWorkers:'block'}),page=await context.newPage(),c={city,width,errors:[],bad_rpc:[],blocked_mutations:[],image_failures:[]};report.cases.push(c);
 page.on('pageerror',e=>c.errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().includes('/rest/v1/rpc/'))c.bad_rpc.push({name:new URL(r.url()).pathname.split('/').pop(),status:r.status()});});page.on('requestfailed',r=>{if(r.resourceType()==='image')c.image_failures.push(new URL(r.url()).pathname);});
 await page.route('**/*',r=>{const u=new URL(r.request().url()),fn=u.pathname.includes('/rest/v1/rpc/')?u.pathname.split('/').pop():null;if(fn&&/(?:save|write|update|send|create|delete|reserve|publish|checkout|claim|commit|insert|configure)/i.test(fn)){c.blocked_mutations.push(fn);return r.abort();}return r.continue();});
 const url=origin+(city==='toronto'?'/events/giannis-ploutarchos-andromache-toronto-2027/':'/event/giannis-ploutarchos-andromache-montreal-2027')+'#room';const response=await page.goto(url,{waitUntil:'domcontentloaded'});assert.equal(response.status(),200);const room=page.locator('[data-room-skin=zoi]').first();await room.locator('canvas').first().waitFor({timeout:45000});await room.scrollIntoViewIfNeeded();await page.waitForTimeout(1600);await page.screenshot({path:path.join(out,city+'-'+width+'-embedded.png')});
 await room.getByRole('button',{name:'Full screen',exact:true}).click();await page.waitForTimeout(900);c.controls=await controls(room);assert.ok(c.controls.scroll<=c.controls.width+1);assert.ok(c.controls.buttons.every(b=>b.fits&&b.height>=44&&b.hit));if(width===390)assert.ok(c.controls.height<=110);await page.screenshot({path:path.join(out,city+'-'+width+'-fullscreen.png')});
 await room.getByRole('button',{name:'Find table',exact:true}).click();const search=room.getByRole('searchbox');await search.fill(city==='toronto'?'12':'10A');await room.locator(city==='toronto'?'[data-fc-table="12"]':'.rs-numbers [data-table="10A"]').last().click();await page.waitForTimeout(900);await page.screenshot({path:path.join(out,city+'-'+width+'-selected.png')});
 await room.getByRole('button',{name:'View from table',exact:true}).click();await page.waitForTimeout(900);await page.screenshot({path:path.join(out,city+'-'+width+'-seated.png')});await room.getByRole('button',{name:'Whole room',exact:true}).click();await page.waitForTimeout(900);await page.screenshot({path:path.join(out,city+'-'+width+'-overview.png')});
 c.final=await controls(room);assert.ok(c.final.buttons.every(b=>b.fits&&b.hit));await room.getByRole('button',{name:'Exit full screen',exact:true}).click();assert.equal(await page.evaluate(()=>!!document.fullscreenElement),false);assert.deepEqual(c.errors,[]);assert.deepEqual(c.bad_rpc,[]);assert.deepEqual(c.blocked_mutations,[]);c.passed=true;console.log(city,width,'actual production room passed');await context.close();
}
report.passed=report.cases.length===4&&report.cases.every(c=>c.passed);assert.equal(report.passed,true);
}catch(e){report.passed=false;report.failure=e.message;throw e;}finally{await browser?.close();await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));}})().catch(e=>{console.error(e.message);process.exitCode=1;});
