begin;
set local lock_timeout='5s';
create table zoi.football_seasons(id uuid primary key,workspace_id uuid not null references zoi.workspaces(id),host_id uuid not null references zoi.listings(id),host_kind text not null check(host_kind in('club','league')),name text not null,timezone text not null,starts_on date not null,ends_on date not null,published boolean not null default false,version integer not null default 1,initial_data jsonb not null,created_by uuid not null references zoi.user_profiles(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp());
create index football_season_host on zoi.football_seasons(host_id,published);
create index football_season_workspace on zoi.football_seasons(workspace_id,updated_at desc);
create table zoi.football_teams(id uuid primary key,season_id uuid not null references zoi.football_seasons(id),club_id uuid not null references zoi.listings(id),club_workspace uuid not null references zoi.workspaces(id),name text not null,contact_notes text not null default '',adult_confirmed boolean not null default false,invited boolean not null default false,status text not null check(status in('invited','applied','accepted','declined','withdrawn')),version integer not null default 1,initial_data jsonb not null,created_by uuid not null references zoi.user_profiles(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp());
create index football_team_season on zoi.football_teams(season_id,status);
create index football_team_workspace on zoi.football_teams(club_workspace,updated_at desc);
create table zoi.football_fixtures(id uuid primary key,season_id uuid not null references zoi.football_seasons(id),home_id uuid not null references zoi.football_teams(id),away_id uuid not null references zoi.football_teams(id),starts_at timestamptz not null,ends_at timestamptz not null,timezone text not null,venue text not null,published boolean not null default false,status text not null default 'scheduled' check(status in('scheduled','proposed','disputed','confirmed','cancelled')),home_score integer,away_score integer,proposed_by uuid references zoi.user_profiles(id),proposed_workspace uuid references zoi.workspaces(id),confirmed_by uuid references zoi.user_profiles(id),decision_reason text,version integer not null default 1,initial_data jsonb not null,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp());
create index football_fixture_season on zoi.football_fixtures(season_id,starts_at);
create index football_fixture_home on zoi.football_fixtures(home_id,starts_at);
create index football_fixture_away on zoi.football_fixtures(away_id,starts_at);
create table zoi.football_audit(id bigint generated always as identity primary key,season_id uuid not null references zoi.football_seasons(id),team_id uuid references zoi.football_teams(id),fixture_id uuid references zoi.football_fixtures(id),actor_id uuid not null references zoi.user_profiles(id),action text not null,before_state jsonb,after_state jsonb not null,created_at timestamptz not null default clock_timestamp());
create index football_audit_season on zoi.football_audit(season_id,id desc);
alter table zoi.football_seasons enable row level security;alter table zoi.football_teams enable row level security;alter table zoi.football_fixtures enable row level security;alter table zoi.football_audit enable row level security;
revoke all on zoi.football_seasons,zoi.football_teams,zoi.football_fixtures,zoi.football_audit from public,anon,authenticated;
create function zoi.football_actor(p_workspace uuid) returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid;begin if auth.uid() is null or coalesce(zoi.ops_role(p_workspace),'') not in('owner','admin') then raise exception 'football_permission_denied' using errcode='42501';end if;select id into actor from zoi.user_profiles where auth_user_id=auth.uid();if actor is null then raise exception 'football_permission_denied';end if;return actor;end $$;
create function zoi.football_host(p_listing uuid,p_workspace uuid) returns void language plpgsql security definer set search_path='' as $$begin perform 1 from zoi.listings where id=p_listing and owner_workspace_id=p_workspace and publish_status='published' and coalesce(marketplace_status,'')<>'hidden' and entity_type in('sports','organization','business') for share;if not found then raise exception 'football_host_unavailable';end if;end $$;
create function zoi.football_current(p_season uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from zoi.football_seasons s join zoi.listings l on l.id=s.host_id where s.id=p_season and l.owner_workspace_id=s.workspace_id and l.publish_status='published' and coalesce(l.marketplace_status,'')<>'hidden')$$;
create function zoi.football_team_current(p_team uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from zoi.football_teams t join zoi.listings l on l.id=t.club_id where t.id=p_team and l.owner_workspace_id=t.club_workspace and l.publish_status='published' and coalesce(l.marketplace_status,'')<>'hidden')$$;
revoke all on function zoi.football_actor(uuid),zoi.football_host(uuid,uuid),zoi.football_current(uuid),zoi.football_team_current(uuid) from public,anon,authenticated;
create function public.football_season_save(p_workspace uuid,p_id uuid,p_expected_version integer,p_data jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;s zoi.football_seasons;prior zoi.football_seasons;begin
 actor:=zoi.football_actor(p_workspace);perform 1 from zoi.workspaces where id=p_workspace for update;select * into prior from zoi.football_seasons where id=p_id for update;
 if prior.id is not null and prior.workspace_id is distinct from p_workspace then raise exception 'football_permission_denied';end if;
 if p_expected_version=0 and prior.id is not null then if prior.initial_data is distinct from p_data then raise exception 'football_request_conflict';end if;return jsonb_build_object('ok',true,'season',to_jsonb(prior));end if;
 if p_id is null or jsonb_typeof(p_data) is distinct from 'object' or octet_length(p_data::text)>5000 or length(btrim(coalesce(p_data->>'name',''))) not between 1 and 160 or coalesce(p_data->>'host_kind','') not in('club','league') or jsonb_typeof(p_data->'published') is distinct from 'boolean' or not exists(select 1 from pg_catalog.pg_timezone_names where name=p_data->>'timezone') or coalesce(p_data->>'starts_on','') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' or coalesce(p_data->>'ends_on','') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' or (p_data->>'ends_on')::date<(p_data->>'starts_on')::date or (p_data->>'ends_on')::date-(p_data->>'starts_on')::date>730 then raise exception 'invalid_football_season';end if;
 perform zoi.football_host((p_data->>'host_id')::uuid,p_workspace);
 if prior.id is null then
  if p_expected_version is distinct from 0 then raise exception 'football_version_conflict';end if;if (select count(*) from zoi.football_seasons where workspace_id=p_workspace)>=30 then raise exception 'football_season_limit';end if;
  insert into zoi.football_seasons(id,workspace_id,host_id,host_kind,name,timezone,starts_on,ends_on,published,initial_data,created_by) values(p_id,p_workspace,(p_data->>'host_id')::uuid,p_data->>'host_kind',btrim(p_data->>'name'),p_data->>'timezone',(p_data->>'starts_on')::date,(p_data->>'ends_on')::date,(p_data->>'published')::boolean,p_data,actor) returning * into s;
 else
  if prior.version is distinct from p_expected_version then raise exception 'football_version_conflict';end if;
  if exists(select 1 from zoi.football_teams where season_id=p_id) and (prior.host_id is distinct from (p_data->>'host_id')::uuid or prior.host_kind is distinct from p_data->>'host_kind' or prior.timezone is distinct from p_data->>'timezone') then raise exception 'football_season_identity_locked';end if;
  if exists(select 1 from zoi.football_fixtures where season_id=p_id and status<>'cancelled' and ((starts_at at time zone timezone)::date<(p_data->>'starts_on')::date or (ends_at at time zone timezone)::date>(p_data->>'ends_on')::date)) then raise exception 'football_season_dates_conflict';end if;
  update zoi.football_seasons set host_id=(p_data->>'host_id')::uuid,host_kind=p_data->>'host_kind',name=btrim(p_data->>'name'),timezone=p_data->>'timezone',starts_on=(p_data->>'starts_on')::date,ends_on=(p_data->>'ends_on')::date,published=(p_data->>'published')::boolean,version=version+1,updated_at=clock_timestamp() where id=p_id returning * into s;
 end if;
 insert into zoi.football_audit(season_id,actor_id,action,before_state,after_state) values(s.id,actor,'season_saved',case when prior.id is null then null else to_jsonb(prior) end,to_jsonb(s));return jsonb_build_object('ok',true,'season',to_jsonb(s));end $$;
create function public.football_team_submit(p_workspace uuid,p_season uuid,p_id uuid,p_data jsonb,p_invite boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;s zoi.football_seasons;t zoi.football_teams;l zoi.listings;begin
 actor:=zoi.football_actor(p_workspace);select * into s from zoi.football_seasons where id=p_season for update;if s.id is null or not zoi.football_current(s.id) then raise exception 'football_season_unavailable';end if;
 select * into t from zoi.football_teams where id=p_id;if t.id is not null then if t.created_by is distinct from actor or t.season_id is distinct from p_season or t.initial_data is distinct from p_data or t.invited is distinct from p_invite then raise exception 'football_request_conflict';end if;return jsonb_build_object('ok',true,'team',to_jsonb(t));end if;
 if p_id is null or p_invite is null or jsonb_typeof(p_data) is distinct from 'object' or octet_length(p_data::text)>12000 or length(btrim(coalesce(p_data->>'name',''))) not between 1 and 120 or length(coalesce(p_data->>'contact_notes',''))>2500 then raise exception 'invalid_football_team';end if;
 select * into l from zoi.listings where id=(p_data->>'club_id')::uuid for share;if l.id is null or l.owner_workspace_id is null then raise exception 'football_host_unavailable';end if;perform zoi.football_host(l.id,l.owner_workspace_id);
 if p_invite then if s.workspace_id is distinct from p_workspace then raise exception 'football_permission_denied';end if;
 else if not s.published or l.owner_workspace_id is distinct from p_workspace or (p_data->>'adult_confirmed')::boolean is distinct from true then raise exception 'football_adult_club_authorization_required';end if;end if;
 if (select count(*) from zoi.football_teams where season_id=p_season)>=64 then raise exception 'football_team_limit';end if;
 insert into zoi.football_teams(id,season_id,club_id,club_workspace,name,contact_notes,adult_confirmed,invited,status,initial_data,created_by) values(p_id,p_season,l.id,l.owner_workspace_id,btrim(p_data->>'name'),coalesce(p_data->>'contact_notes',''),not p_invite,p_invite,case when p_invite then 'invited' else 'applied' end,p_data,actor) returning * into t;
 insert into zoi.football_audit(season_id,team_id,actor_id,action,after_state) values(s.id,t.id,actor,case when p_invite then 'team_invited' else 'team_applied' end,to_jsonb(t));return jsonb_build_object('ok',true,'team',to_jsonb(t));end $$;
create function public.football_team_decide(p_workspace uuid,p_team uuid,p_expected_version integer,p_action text) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;s zoi.football_seasons;t zoi.football_teams;prior zoi.football_teams;next_status text;begin
 actor:=zoi.football_actor(p_workspace);select * into prior from zoi.football_teams where id=p_team;select * into s from zoi.football_seasons where id=prior.season_id for update;if s.id is null then raise exception 'football_team_unavailable';end if;
 select * into prior from zoi.football_teams where id=p_team for update;if prior.version is distinct from p_expected_version then raise exception 'football_version_conflict';end if;
 if p_action='accept_adult_invitation' and prior.status='invited' and prior.club_workspace=p_workspace and zoi.football_team_current(prior.id) then next_status:='applied';
 elsif p_action='approve' and prior.status='applied' and s.workspace_id=p_workspace and zoi.football_current(s.id) and zoi.football_team_current(prior.id) then next_status:='accepted';
 elsif p_action='decline' and prior.status in('applied','invited') and s.workspace_id=p_workspace then next_status:='declined';
 elsif p_action='withdraw' and prior.status in('invited','applied','accepted') and prior.club_workspace=p_workspace then next_status:='withdrawn';
 else raise exception 'football_transition_denied';end if;
 if next_status='withdrawn' and exists(select 1 from zoi.football_fixtures where season_id=s.id and status<>'cancelled' and (home_id=p_team or away_id=p_team)) then raise exception 'football_cancel_fixtures_before_withdrawal';end if;
 update zoi.football_teams set status=next_status,adult_confirmed=adult_confirmed or p_action='accept_adult_invitation',version=version+1,updated_at=clock_timestamp() where id=p_team returning * into t;
 insert into zoi.football_audit(season_id,team_id,actor_id,action,before_state,after_state) values(s.id,t.id,actor,'team_'||next_status,to_jsonb(prior),to_jsonb(t));return jsonb_build_object('ok',true,'team',to_jsonb(t));end $$;
create function public.football_fixture_save(p_workspace uuid,p_season uuid,p_id uuid,p_expected_version integer,p_data jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;s zoi.football_seasons;f zoi.football_fixtures;prior zoi.football_fixtures;win tstzrange;home uuid;away uuid;begin
 actor:=zoi.football_actor(p_workspace);select * into s from zoi.football_seasons where id=p_season and workspace_id=p_workspace for update;if s.id is null or not zoi.football_current(s.id) then raise exception 'football_season_unavailable';end if;
 select * into prior from zoi.football_fixtures where id=p_id for update;if prior.id is not null and prior.season_id is distinct from p_season then raise exception 'football_permission_denied';end if;
 if p_expected_version=0 and prior.id is not null then if prior.initial_data is distinct from p_data then raise exception 'football_request_conflict';end if;return jsonb_build_object('ok',true,'fixture',to_jsonb(prior));end if;
 if p_id is null or jsonb_typeof(p_data) is distinct from 'object' or octet_length(p_data::text)>10000 or length(btrim(coalesce(p_data->>'venue',''))) not between 1 and 500 or jsonb_typeof(p_data->'published') is distinct from 'boolean' or p_data->>'timezone' is distinct from s.timezone then raise exception 'invalid_football_fixture';end if;
 if prior.id is not null and prior.version is distinct from p_expected_version then raise exception 'football_version_conflict';end if;
 if prior.id is not null and p_data->>'cancelled'='true' then
  if length(btrim(coalesce(p_data->>'reason',''))) not between 1 and 1000 then raise exception 'football_reason_required';end if;
  update zoi.football_fixtures set status='cancelled',decision_reason=p_data->>'reason',version=version+1,updated_at=clock_timestamp() where id=p_id returning * into f;
 else
  if prior.id is not null and prior.status<>'scheduled' then raise exception 'football_fixture_locked';end if;
  home:=(p_data->>'home_id')::uuid;away:=(p_data->>'away_id')::uuid;if home is null or away is null or home=away or (select count(*) from zoi.football_teams where season_id=p_season and id in(home,away) and status='accepted' and adult_confirmed and zoi.football_team_current(id))<>2 then raise exception 'football_teams_not_approved';end if;
  win:=zoi.trip_window(p_data->>'starts_at',p_data->>'ends_at',p_data->>'timezone');if upper(win)-lower(win)>interval '8 hours' or (lower(win) at time zone s.timezone)::date<s.starts_on or (upper(win) at time zone s.timezone)::date>s.ends_on then raise exception 'football_fixture_outside_season';end if;
  if exists(select 1 from zoi.football_fixtures x where x.season_id=p_season and x.id<>p_id and x.status<>'cancelled' and (x.home_id in(home,away) or x.away_id in(home,away)) and tstzrange(x.starts_at,x.ends_at,'[)') && win) then raise exception 'football_team_time_conflict';end if;
  if prior.id is null then
   if p_expected_version is distinct from 0 then raise exception 'football_version_conflict';end if;if (select count(*) from zoi.football_fixtures where season_id=p_season)>=1000 then raise exception 'football_fixture_limit';end if;
   insert into zoi.football_fixtures(id,season_id,home_id,away_id,starts_at,ends_at,timezone,venue,published,initial_data) values(p_id,p_season,home,away,lower(win),upper(win),s.timezone,btrim(p_data->>'venue'),(p_data->>'published')::boolean,p_data) returning * into f;
  else update zoi.football_fixtures set home_id=home,away_id=away,starts_at=lower(win),ends_at=upper(win),venue=btrim(p_data->>'venue'),published=(p_data->>'published')::boolean,version=version+1,updated_at=clock_timestamp() where id=p_id returning * into f;end if;
 end if;
 insert into zoi.football_audit(season_id,fixture_id,actor_id,action,before_state,after_state) values(s.id,f.id,actor,case when f.status='cancelled' then 'fixture_cancelled' else 'fixture_saved' end,case when prior.id is null then null else to_jsonb(prior) end,to_jsonb(f));return jsonb_build_object('ok',true,'fixture',to_jsonb(f));end $$;
create function public.football_score_submit(p_workspace uuid,p_fixture uuid,p_expected_version integer,p_home integer,p_away integer) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;s zoi.football_seasons;f zoi.football_fixtures;prior zoi.football_fixtures;home zoi.football_teams;away zoi.football_teams;begin
 actor:=zoi.football_actor(p_workspace);select * into prior from zoi.football_fixtures where id=p_fixture;select * into s from zoi.football_seasons where id=prior.season_id for update;
 select * into prior from zoi.football_fixtures where id=p_fixture for update;
 select * into home from zoi.football_teams where id=prior.home_id;select * into away from zoi.football_teams where id=prior.away_id;
 if s.id is null or p_workspace not in(s.workspace_id,home.club_workspace,away.club_workspace) then raise exception 'football_permission_denied';end if;
 if not zoi.football_current(s.id) or not zoi.football_team_current(home.id) or not zoi.football_team_current(away.id) then raise exception 'football_host_unavailable';end if;
 select * into prior from zoi.football_fixtures where id=p_fixture for update;if prior.version is distinct from p_expected_version then raise exception 'football_version_conflict';end if;
 if prior.status not in('scheduled','disputed') or prior.ends_at>clock_timestamp() then raise exception 'football_score_not_ready';end if;if p_home is null or p_away is null or p_home not between 0 and 99 or p_away not between 0 and 99 then raise exception 'invalid_football_score';end if;
 update zoi.football_fixtures set status='proposed',home_score=p_home,away_score=p_away,proposed_by=actor,proposed_workspace=p_workspace,confirmed_by=null,decision_reason=null,version=version+1,updated_at=clock_timestamp() where id=p_fixture returning * into f;
 insert into zoi.football_audit(season_id,fixture_id,actor_id,action,before_state,after_state) values(s.id,f.id,actor,'score_proposed',to_jsonb(prior),to_jsonb(f));return jsonb_build_object('ok',true,'fixture',to_jsonb(f));end $$;
create function public.football_score_decide(p_workspace uuid,p_fixture uuid,p_expected_version integer,p_action text,p_reason text default '') returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;s zoi.football_seasons;f zoi.football_fixtures;prior zoi.football_fixtures;home zoi.football_teams;away zoi.football_teams;begin
 actor:=zoi.football_actor(p_workspace);select * into prior from zoi.football_fixtures where id=p_fixture;select * into s from zoi.football_seasons where id=prior.season_id for update;select * into prior from zoi.football_fixtures where id=p_fixture for update;select * into home from zoi.football_teams where id=prior.home_id;select * into away from zoi.football_teams where id=prior.away_id;
 if s.id is null or p_workspace not in(s.workspace_id,home.club_workspace,away.club_workspace) then raise exception 'football_permission_denied';end if;
 if not zoi.football_current(s.id) or not zoi.football_team_current(home.id) or not zoi.football_team_current(away.id) then raise exception 'football_host_unavailable';end if;
 select * into prior from zoi.football_fixtures where id=p_fixture for update;if prior.version is distinct from p_expected_version then raise exception 'football_version_conflict';end if;
 if prior.status<>'proposed' or actor=prior.proposed_by or p_workspace=prior.proposed_workspace or p_action is null or p_action not in('confirm','dispute') then raise exception 'football_independent_confirmation_required';end if;
 if length(coalesce(p_reason,''))>1000 or (p_action='dispute' and btrim(coalesce(p_reason,''))='') then raise exception 'football_reason_required';end if;
 update zoi.football_fixtures set status=case when p_action='confirm' then 'confirmed' else 'disputed' end,confirmed_by=case when p_action='confirm' then actor end,decision_reason=coalesce(p_reason,''),version=version+1,updated_at=clock_timestamp() where id=p_fixture returning * into f;
 insert into zoi.football_audit(season_id,fixture_id,actor_id,action,before_state,after_state) values(s.id,f.id,actor,'score_'||f.status,to_jsonb(prior),to_jsonb(f));return jsonb_build_object('ok',true,'fixture',to_jsonb(f));end $$;
create function public.football_public(p_host uuid default null,p_season uuid default null) returns jsonb language plpgsql stable security definer set search_path='' as $$declare seasons jsonb;teams jsonb;fixtures jsonb;s zoi.football_seasons;begin
 select coalesce(jsonb_agg(jsonb_build_object('id',q.id,'host_id',q.host_id,'host_kind',q.host_kind,'name',q.name,'timezone',q.timezone,'starts_on',q.starts_on,'ends_on',q.ends_on,'host_name',q.host_name,'host_slug',q.host_slug)),'[]') into seasons from(select ss.*,l.name host_name,l.slug host_slug from zoi.football_seasons ss join zoi.listings l on l.id=ss.host_id where ss.published and (p_host is null or ss.host_id=p_host) and zoi.football_current(ss.id) order by ss.starts_on desc,ss.id limit 30)q;
 select * into s from zoi.football_seasons where id=p_season and published and zoi.football_current(id) and (p_host is null or host_id=p_host);
 if s.id is null then return jsonb_build_object('ok',true,'seasons',seasons,'season',null,'teams','[]'::jsonb,'fixtures','[]'::jsonb);end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'club_id',t.club_id,'name',t.name,'club_name',l.name,'club_slug',l.slug) order by t.name,t.id),'[]') into teams from zoi.football_teams t join zoi.listings l on l.id=t.club_id where t.season_id=s.id and t.status='accepted' and zoi.football_team_current(t.id);
 select coalesce(jsonb_agg(jsonb_build_object('id',f.id,'home_id',f.home_id,'away_id',f.away_id,'starts_at',f.starts_at,'ends_at',f.ends_at,'timezone',f.timezone,'venue',f.venue,'status',f.status,'home_score',case when f.status='confirmed' then f.home_score end,'away_score',case when f.status='confirmed' then f.away_score end) order by f.starts_at,f.id),'[]') into fixtures from zoi.football_fixtures f where f.season_id=s.id and f.published and zoi.football_team_current(f.home_id) and zoi.football_team_current(f.away_id);
 return jsonb_build_object('ok',true,'seasons',seasons,'season',jsonb_build_object('id',s.id,'name',s.name,'host_id',s.host_id,'host_kind',s.host_kind,'timezone',s.timezone,'starts_on',s.starts_on,'ends_on',s.ends_on),'teams',teams,'fixtures',fixtures,'rules',jsonb_build_object('win',3,'draw',1,'loss',0,'tie_break',jsonb_build_array('points','goal_difference','goals_for'),'tied_rank',true));end $$;
create function public.football_operator(p_workspace uuid,p_season uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;s zoi.football_seasons;seasons jsonb;teams jsonb;fixtures jsonb;audit jsonb;owned jsonb;begin
 actor:=zoi.football_actor(p_workspace);
 select coalesce(jsonb_agg(to_jsonb(q)),'[]') into seasons from(select distinct ss.* from zoi.football_seasons ss left join zoi.football_teams t on t.season_id=ss.id where ss.workspace_id=p_workspace or t.club_workspace=p_workspace order by ss.updated_at desc limit 100)q;
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'entity_type',entity_type)),'[]') into owned from zoi.listings where owner_workspace_id=p_workspace and publish_status='published' and coalesce(marketplace_status,'')<>'hidden' and entity_type in('sports','organization','business');
 select * into s from zoi.football_seasons where id=p_season and (workspace_id=p_workspace or exists(select 1 from zoi.football_teams where season_id=p_season and club_workspace=p_workspace));
 if s.id is null then return jsonb_build_object('ok',true,'seasons',seasons,'owned',owned,'season',null,'teams','[]'::jsonb,'fixtures','[]'::jsonb,'audit','[]'::jsonb);end if;
 select coalesce(jsonb_agg(case when s.workspace_id=p_workspace or t.club_workspace=p_workspace then to_jsonb(t) else jsonb_build_object('id',t.id,'season_id',t.season_id,'club_id',t.club_id,'name',t.name,'status',t.status,'club_workspace',t.club_workspace) end order by t.name,t.id),'[]') into teams from zoi.football_teams t where t.season_id=s.id and (s.workspace_id=p_workspace or t.club_workspace=p_workspace or (t.status='accepted' and zoi.football_team_current(t.id))); 
 select coalesce(jsonb_agg(to_jsonb(f) order by f.starts_at,f.id),'[]') into fixtures from zoi.football_fixtures f where f.season_id=s.id and (s.workspace_id=p_workspace or exists(select 1 from zoi.football_teams where id in(f.home_id,f.away_id) and club_workspace=p_workspace));
 select coalesce(jsonb_agg(to_jsonb(q)),'[]') into audit from(select a.* from zoi.football_audit a where a.season_id=s.id and s.workspace_id=p_workspace order by id desc limit 100)q;
 return jsonb_build_object('ok',true,'seasons',seasons,'owned',owned,'season',to_jsonb(s),'teams',teams,'fixtures',fixtures,'audit',audit,'can_organize',s.workspace_id=p_workspace);end $$;
create function public.football_clubs(p_query text default '') returns jsonb language plpgsql stable security definer set search_path='' as $$declare rows jsonb;begin
 if length(coalesce(p_query,''))>100 then raise exception 'invalid_football_search';end if;
 select coalesce(jsonb_agg(to_jsonb(q)),'[]') into rows from(select id,name,slug,city,country,entity_type from zoi.listings where entity_type in('sports','organization','business') and owner_workspace_id is not null and publish_status='published' and coalesce(marketplace_status,'')<>'hidden' and (coalesce(p_query,'')='' or position(lower(p_query) in lower(name))>0) order by name,id limit 30)q;return jsonb_build_object('ok',true,'clubs',rows);end $$;
revoke all on function public.football_clubs(text) from public,anon;grant execute on function public.football_clubs(text) to anon,authenticated;
revoke all on function public.football_season_save(uuid,uuid,integer,jsonb),public.football_team_submit(uuid,uuid,uuid,jsonb,boolean),public.football_team_decide(uuid,uuid,integer,text),public.football_fixture_save(uuid,uuid,uuid,integer,jsonb),public.football_score_submit(uuid,uuid,integer,integer,integer),public.football_score_decide(uuid,uuid,integer,text,text),public.football_public(uuid,uuid),public.football_operator(uuid,uuid) from public,anon,authenticated;
grant execute on function public.football_public(uuid,uuid) to anon,authenticated;
grant execute on function public.football_season_save(uuid,uuid,integer,jsonb),public.football_team_submit(uuid,uuid,uuid,jsonb,boolean),public.football_team_decide(uuid,uuid,integer,text),public.football_fixture_save(uuid,uuid,uuid,integer,jsonb),public.football_score_submit(uuid,uuid,integer,integer,integer),public.football_score_decide(uuid,uuid,integer,text,text),public.football_operator(uuid,uuid) to authenticated;
commit;
