begin;
set local lock_timeout='5s';
create table zoi.artist_appearances(id uuid primary key,artist_id uuid not null references zoi.listings(id),event_id uuid not null references zoi.listings(id),artist_workspace uuid not null references zoi.workspaces(id),event_workspace uuid not null references zoi.workspaces(id),starts_at timestamptz not null,ends_at timestamptz not null,timezone text not null,source_url text not null,event_confirmed_by uuid references zoi.user_profiles(id),artist_confirmed_by uuid references zoi.user_profiles(id),status text not null default 'pending' check(status in('pending','confirmed','withdrawn')),version integer not null default 1,created_by uuid not null references zoi.user_profiles(id),initial_data jsonb not null,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp());
create unique index appearance_one_active_slot on zoi.artist_appearances(artist_id,event_id,starts_at) where status<>'withdrawn';
create index artist_appearances_artist on zoi.artist_appearances(artist_id,starts_at);
create index artist_appearances_workspaces on zoi.artist_appearances(event_workspace,artist_workspace);
create table zoi.appearance_audit(id bigint generated always as identity primary key,appearance_id uuid not null references zoi.artist_appearances(id),actor_id uuid not null references zoi.user_profiles(id),action text not null,before_state jsonb,after_state jsonb not null,created_at timestamptz not null default clock_timestamp());
create index appearance_audit_parent on zoi.appearance_audit(appearance_id,id desc);
create table zoi.private_trips(id uuid primary key,profile_id uuid not null references zoi.user_profiles(id),name text not null,timezone text not null,notes text not null default '',version integer not null default 1,initial_data jsonb not null,archived boolean not null default false,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp());
create index private_trips_profile on zoi.private_trips(profile_id,updated_at desc);
create table zoi.trip_items(id uuid primary key,trip_id uuid not null references zoi.private_trips(id),listing_id uuid not null references zoi.listings(id),appearance_id uuid references zoi.artist_appearances(id),starts_at timestamptz not null,ends_at timestamptz not null,timezone text not null,notes text not null default '',version integer not null default 1,initial_data jsonb not null,removed boolean not null default false,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp());
create index trip_items_parent on zoi.trip_items(trip_id,starts_at);
create table zoi.trip_audit(id bigint generated always as identity primary key,trip_id uuid not null references zoi.private_trips(id),item_id uuid references zoi.trip_items(id),actor_id uuid not null references zoi.user_profiles(id),action text not null,before_state jsonb,after_state jsonb not null,created_at timestamptz not null default clock_timestamp());
create index trip_audit_parent on zoi.trip_audit(trip_id,id desc);
alter table zoi.artist_appearances enable row level security;alter table zoi.appearance_audit enable row level security;alter table zoi.private_trips enable row level security;alter table zoi.trip_items enable row level security;alter table zoi.trip_audit enable row level security;
revoke all on zoi.artist_appearances,zoi.appearance_audit,zoi.private_trips,zoi.trip_items,zoi.trip_audit from public,anon,authenticated;
create function zoi.trip_actor() returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid;begin if auth.uid() is null then raise exception 'sign_in_required' using errcode='42501';end if;actor:=zoi.ensure_profile();if actor is null then raise exception 'trip_profile_required';end if;return actor;end $$;
create function zoi.trip_window(p_start text,p_end text,p_timezone text) returns tstzrange language plpgsql stable set search_path='' as $$declare a timestamptz;b timestamptz;begin
 if coalesce(p_start,'') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$' or coalesce(p_end,'') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$' or not exists(select 1 from pg_catalog.pg_timezone_names where name=p_timezone) then raise exception 'trip_timezone_required';end if;
 begin a:=p_start::timestamptz;b:=p_end::timestamptz;exception when others then raise exception 'invalid_trip_window';end;if not isfinite(a) or not isfinite(b) or b<=a or b-a>interval '7 days' then raise exception 'invalid_trip_window';end if;return tstzrange(a,b,'[)');end $$;
create function zoi.appearance_current(p zoi.artist_appearances) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from zoi.listings a join zoi.listings e on e.id=p.event_id where a.id=p.artist_id and a.owner_workspace_id=p.artist_workspace and e.owner_workspace_id=p.event_workspace and a.publish_status='published' and e.publish_status='published' and coalesce(a.marketplace_status,'')<>'hidden' and coalesce(e.marketplace_status,'')<>'hidden')$$;
revoke all on function zoi.trip_actor(),zoi.trip_window(text,text,text),zoi.appearance_current(zoi.artist_appearances) from public,anon,authenticated;
create function public.appearance_propose(p_id uuid,p_data jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid;artist zoi.listings;ev zoi.listings;p zoi.artist_appearances;win tstzrange;ar boolean;er boolean;
begin
 actor:=zoi.trip_actor();perform 1 from zoi.user_profiles where id=actor for update;
 select * into p from zoi.artist_appearances where id=p_id;
 if p.id is not null then if p.created_by is distinct from actor or p.initial_data is distinct from p_data then raise exception 'appearance_request_conflict';end if;return jsonb_build_object('ok',true,'appearance',to_jsonb(p));end if;
 if p_id is null or jsonb_typeof(p_data) is distinct from 'object' or octet_length(p_data::text)>8000 or length(coalesce(p_data->>'source_url',''))>2000 or coalesce(p_data->>'source_url','') !~ '^https://[A-Za-z0-9][A-Za-z0-9.-]*(:[0-9]+)?(/[^[:space:]<>]*)?$' then raise exception 'invalid_appearance';end if;
 -- Lock both listing rows in deterministic order before reading ownership snapshots.
 perform 1 from zoi.listings where id in((p_data->>'artist_id')::uuid,(p_data->>'event_id')::uuid) order by id for share;
 select * into artist from zoi.listings where id=(p_data->>'artist_id')::uuid;select * into ev from zoi.listings where id=(p_data->>'event_id')::uuid;
 if artist.id is null or ev.id is null or coalesce(artist.entity_type,'') not in('artist','creator') or coalesce(ev.entity_type,'')<>'event' or artist.owner_workspace_id is null or ev.owner_workspace_id is null or artist.publish_status<>'published' or ev.publish_status<>'published' or coalesce(artist.marketplace_status,'')='hidden' or coalesce(ev.marketplace_status,'')='hidden' then raise exception 'appearance_listing_unavailable';end if;
 ar:=coalesce(zoi.ops_role(artist.owner_workspace_id),'') in('owner','admin');er:=coalesce(zoi.ops_role(ev.owner_workspace_id),'') in('owner','admin');if not ar and not er then raise exception 'appearance_permission_denied' using errcode='42501';end if;
 if (select count(*) from zoi.artist_appearances where created_by=actor and created_at>clock_timestamp()-interval '1 day')>=30 then raise exception 'appearance_daily_limit';end if;
 win:=zoi.trip_window(p_data->>'starts_at',p_data->>'ends_at',p_data->>'timezone');
 insert into zoi.artist_appearances(id,artist_id,event_id,artist_workspace,event_workspace,starts_at,ends_at,timezone,source_url,artist_confirmed_by,event_confirmed_by,status,created_by,initial_data) values(p_id,artist.id,ev.id,artist.owner_workspace_id,ev.owner_workspace_id,lower(win),upper(win),p_data->>'timezone',p_data->>'source_url',case when ar then actor end,case when er then actor end,case when ar and er then 'confirmed' else 'pending' end,actor,p_data) returning * into p;
 insert into zoi.appearance_audit(appearance_id,actor_id,action,after_state) values(p.id,actor,'proposed',to_jsonb(p));return jsonb_build_object('ok',true,'appearance',to_jsonb(p));
end $$;
create function public.appearance_decide(p_id uuid,p_expected_version integer,p_action text) returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid;p zoi.artist_appearances;prior zoi.artist_appearances;ar boolean;er boolean;
begin actor:=zoi.trip_actor();select * into prior from zoi.artist_appearances where id=p_id;if prior.id is null then raise exception 'appearance_unavailable';end if;
 perform 1 from zoi.listings where id in(prior.artist_id,prior.event_id) order by id for share;
 ar:=coalesce(zoi.ops_role(prior.artist_workspace),'') in('owner','admin');er:=coalesce(zoi.ops_role(prior.event_workspace),'') in('owner','admin');if not ar and not er then raise exception 'appearance_permission_denied' using errcode='42501';end if;
 select * into prior from zoi.artist_appearances where id=p_id for update;if prior.version is distinct from p_expected_version then raise exception 'appearance_version_conflict';end if;
 if prior.status='withdrawn' or p_action not in('confirm','withdraw') or p_action is null then raise exception 'appearance_transition_invalid';end if;
 if p_action='confirm' and not zoi.appearance_current(prior) then raise exception 'appearance_listing_unavailable';end if;
 update zoi.artist_appearances set artist_confirmed_by=case when p_action='confirm' and ar then actor else artist_confirmed_by end,event_confirmed_by=case when p_action='confirm' and er then actor else event_confirmed_by end,status=case when p_action='withdraw' then 'withdrawn' when (ar or artist_confirmed_by is not null) and (er or event_confirmed_by is not null) then 'confirmed' else 'pending' end,version=version+1,updated_at=clock_timestamp() where id=p_id returning * into p;
 insert into zoi.appearance_audit(appearance_id,actor_id,action,before_state,after_state) values(p.id,actor,p_action,to_jsonb(prior),to_jsonb(p));return jsonb_build_object('ok',true,'appearance',to_jsonb(p));end $$;
create function public.appearance_operator(p_workspace uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare items jsonb;owned jsonb;audit jsonb;begin
 if auth.uid() is null or coalesce(zoi.ops_role(p_workspace),'') not in('owner','admin') then raise exception 'appearance_permission_denied' using errcode='42501';end if;
 select coalesce(jsonb_agg(to_jsonb(q)),'[]') into items from(select p.*,a.name artist_name,e.name event_name,zoi.appearance_current(p) currently_visible from zoi.artist_appearances p join zoi.listings a on a.id=p.artist_id join zoi.listings e on e.id=p.event_id where p.artist_workspace=p_workspace or p.event_workspace=p_workspace order by p.updated_at desc limit 100)q;
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'entity_type',entity_type)),'[]') into owned from zoi.listings where owner_workspace_id=p_workspace and entity_type in('artist','creator','event') and publish_status='published' and coalesce(marketplace_status,'')<>'hidden';
 select coalesce(jsonb_agg(to_jsonb(q)),'[]') into audit from(select a.* from zoi.appearance_audit a join zoi.artist_appearances p on p.id=a.appearance_id where p.artist_workspace=p_workspace or p.event_workspace=p_workspace order by a.id desc limit 100)q;
 return jsonb_build_object('ok',true,'appearances',items,'owned',owned,'audit',audit);end $$;
create function public.trip_discover(p_query text default '',p_country text default null,p_type text default null) returns jsonb language plpgsql stable security definer set search_path='' as $$declare rows jsonb;begin
 if length(coalesce(p_query,''))>100 or length(coalesce(p_country,''))>100 or (p_type is not null and p_type not in('event','artist','creator','business','organization','travel_place')) then raise exception 'invalid_trip_search';end if;
 select coalesce(jsonb_agg(to_jsonb(q)),'[]') into rows from(select id,name,slug,entity_type,city,country from zoi.listings where publish_status='published' and coalesce(marketplace_status,'')<>'hidden' and nullif(slug,'') is not null and (p_type is null or entity_type=p_type) and (p_country is null or country=p_country) and (coalesce(p_query,'')='' or name ilike '%'||replace(replace(replace(p_query,'\','\\'),'%','\%'),'_','\_')||'%') order by name,id limit 30)q;return jsonb_build_object('ok',true,'listings',rows);end $$;
create function public.artist_shows(p_artist uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare rows jsonb;begin
 select coalesce(jsonb_agg(to_jsonb(q)),'[]') into rows from(select p.id,p.artist_id,p.event_id,p.starts_at,p.ends_at,p.timezone,p.source_url,p.updated_at,a.name artist_name,e.name event_name,e.slug,e.city,e.country from zoi.artist_appearances p join zoi.listings a on a.id=p.artist_id join zoi.listings e on e.id=p.event_id where p.artist_id=p_artist and nullif(e.slug,'') is not null and p.status='confirmed' and p.ends_at>=clock_timestamp() and zoi.appearance_current(p) order by p.starts_at,p.id limit 100)q;
 return jsonb_build_object('ok',true,'shows',rows,'confirmation','event_and_artist_workspace');end $$;
create function public.trip_save(p_id uuid,p_expected_version integer,p_data jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;t zoi.private_trips;prior zoi.private_trips;begin
 actor:=zoi.trip_actor();perform 1 from zoi.user_profiles where id=actor for update;select * into prior from zoi.private_trips where id=p_id for update;
 if prior.id is not null and prior.profile_id is distinct from actor then raise exception 'trip_permission_denied' using errcode='42501';end if;
 if p_expected_version=0 and prior.id is not null then if prior.initial_data is distinct from p_data then raise exception 'trip_request_conflict';end if;return jsonb_build_object('ok',true,'trip',to_jsonb(prior));end if;
 if p_id is null or jsonb_typeof(p_data) is distinct from 'object' or octet_length(p_data::text)>15000 or length(btrim(coalesce(p_data->>'name',''))) not between 1 and 160 or length(coalesce(p_data->>'notes',''))>4000 or not exists(select 1 from pg_catalog.pg_timezone_names where name=p_data->>'timezone') then raise exception 'invalid_trip';end if;
 if prior.id is null then
  if p_expected_version is distinct from 0 then raise exception 'trip_version_conflict';end if;if (select count(*) from zoi.private_trips where profile_id=actor and not archived)>=30 then raise exception 'trip_limit';end if;
  insert into zoi.private_trips(id,profile_id,name,timezone,notes,initial_data) values(p_id,actor,btrim(p_data->>'name'),p_data->>'timezone',coalesce(p_data->>'notes',''),p_data) returning * into t;
 else
  if prior.version is distinct from p_expected_version then raise exception 'trip_version_conflict';end if;if prior.archived then raise exception 'trip_archived';end if;
  update zoi.private_trips set name=btrim(p_data->>'name'),timezone=p_data->>'timezone',notes=coalesce(p_data->>'notes',''),version=version+1,updated_at=clock_timestamp() where id=p_id returning * into t;
 end if;
 insert into zoi.trip_audit(trip_id,actor_id,action,before_state,after_state) values(t.id,actor,'trip_saved',case when prior.id is null then null else to_jsonb(prior) end,to_jsonb(t));return jsonb_build_object('ok',true,'trip',to_jsonb(t));end $$;
create function public.trip_item_save(p_trip uuid,p_id uuid,p_expected_version integer,p_data jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;t zoi.private_trips;i zoi.trip_items;prior zoi.trip_items;l zoi.listings;ap zoi.artist_appearances;win tstzrange;begin
 actor:=zoi.trip_actor();select * into t from zoi.private_trips where id=p_trip for update;if t.id is null or t.profile_id is distinct from actor then raise exception 'trip_permission_denied' using errcode='42501';end if;
 select * into prior from zoi.trip_items where id=p_id for update;if prior.id is not null and prior.trip_id is distinct from p_trip then raise exception 'trip_permission_denied' using errcode='42501';end if;
 if p_expected_version=0 and prior.id is not null then if prior.initial_data is distinct from p_data then raise exception 'trip_request_conflict';end if;return jsonb_build_object('ok',true,'item',to_jsonb(prior));end if;
 if t.archived then raise exception 'trip_archived';end if;
 if p_id is null or jsonb_typeof(p_data) is distinct from 'object' or octet_length(p_data::text)>12000 or length(coalesce(p_data->>'notes',''))>2500 then raise exception 'invalid_trip_item';end if;
 select * into l from zoi.listings where id=(p_data->>'listing_id')::uuid and publish_status='published' and coalesce(marketplace_status,'')<>'hidden' for share;if l.id is null or l.entity_type in('artist','creator') then raise exception 'trip_listing_unavailable';end if;
 if nullif(p_data->>'appearance_id','') is not null then
  select * into ap from zoi.artist_appearances where id=(p_data->>'appearance_id')::uuid for share;
  if ap.id is null or ap.event_id is distinct from l.id or ap.status<>'confirmed' or not zoi.appearance_current(ap) then raise exception 'appearance_unavailable';end if;
  win:=tstzrange(ap.starts_at,ap.ends_at,'[)');
 else win:=zoi.trip_window(p_data->>'starts_at',p_data->>'ends_at',p_data->>'timezone');end if;
 if prior.id is null then
  if p_expected_version is distinct from 0 then raise exception 'trip_version_conflict';end if;if (select count(*) from zoi.trip_items where trip_id=p_trip and not removed)>=100 then raise exception 'trip_item_limit';end if;
  insert into zoi.trip_items(id,trip_id,listing_id,appearance_id,starts_at,ends_at,timezone,notes,initial_data) values(p_id,p_trip,l.id,ap.id,lower(win),upper(win),coalesce(ap.timezone,p_data->>'timezone'),coalesce(p_data->>'notes',''),p_data) returning * into i;
 else
  if prior.version is distinct from p_expected_version then raise exception 'trip_version_conflict';end if;if prior.removed then raise exception 'trip_item_removed';end if;
  update zoi.trip_items set listing_id=l.id,appearance_id=ap.id,starts_at=lower(win),ends_at=upper(win),timezone=coalesce(ap.timezone,p_data->>'timezone'),notes=coalesce(p_data->>'notes',''),version=version+1,updated_at=clock_timestamp() where id=p_id returning * into i;
 end if;
 insert into zoi.trip_audit(trip_id,item_id,actor_id,action,before_state,after_state) values(p_trip,i.id,actor,'item_saved',case when prior.id is null then null else to_jsonb(prior) end,to_jsonb(i));return jsonb_build_object('ok',true,'item',to_jsonb(i));end $$;
create function public.trip_remove(p_trip uuid,p_item uuid,p_expected_version integer) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;t zoi.private_trips;i zoi.trip_items;prior jsonb;result jsonb;begin
 actor:=zoi.trip_actor();select * into t from zoi.private_trips where id=p_trip for update;if t.id is null or t.profile_id is distinct from actor then raise exception 'trip_permission_denied' using errcode='42501';end if;
 if p_item is null then
  if t.version is distinct from p_expected_version then raise exception 'trip_version_conflict';end if;prior:=to_jsonb(t);update zoi.private_trips set archived=true,version=version+1,updated_at=clock_timestamp() where id=p_trip returning * into t;result:=to_jsonb(t);
 else
  select * into i from zoi.trip_items where id=p_item and trip_id=p_trip for update;if i.id is null then raise exception 'trip_item_unavailable';end if;if i.version is distinct from p_expected_version then raise exception 'trip_version_conflict';end if;prior:=to_jsonb(i);update zoi.trip_items set removed=true,version=version+1,updated_at=clock_timestamp() where id=p_item returning * into i;result:=to_jsonb(i);
 end if;
 insert into zoi.trip_audit(trip_id,item_id,actor_id,action,before_state,after_state) values(p_trip,p_item,actor,case when p_item is null then 'trip_archived' else 'item_removed' end,prior,result);return jsonb_build_object('ok',true,'record',result);end $$;
create function public.trips_mine() returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;rows jsonb;begin actor:=zoi.trip_actor();select coalesce(jsonb_agg(to_jsonb(q)),'[]') into rows from(select t.*,(select count(*) from zoi.trip_items i where i.trip_id=t.id and not i.removed) item_count from zoi.private_trips t where profile_id=actor and not archived order by updated_at desc limit 30)q;return jsonb_build_object('ok',true,'trips',rows);end $$;
create function public.trip_get(p_trip uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;t zoi.private_trips;items jsonb;audit jsonb;begin
 actor:=zoi.trip_actor();select * into t from zoi.private_trips where id=p_trip;if t.id is null or t.profile_id is distinct from actor then raise exception 'trip_permission_denied' using errcode='42501';end if;
 select coalesce(jsonb_agg(to_jsonb(q)),'[]') into items from(select i.*,case when l.publish_status='published' and coalesce(l.marketplace_status,'')<>'hidden' then l.name end listing_name,case when l.publish_status='published' and coalesce(l.marketplace_status,'')<>'hidden' then l.slug end slug,case when l.publish_status='published' and coalesce(l.marketplace_status,'')<>'hidden' then l.entity_type end entity_type,(l.publish_status='published' and coalesce(l.marketplace_status,'')<>'hidden') listing_available,case when i.appearance_id is null then null else coalesce(ap.status='confirmed' and zoi.appearance_current(ap),false) end appearance_confirmed,exists(select 1 from zoi.trip_items x where x.trip_id=i.trip_id and x.id<>i.id and not x.removed and tstzrange(x.starts_at,x.ends_at,'[)') && tstzrange(i.starts_at,i.ends_at,'[)')) time_conflict from zoi.trip_items i join zoi.listings l on l.id=i.listing_id left join zoi.artist_appearances ap on ap.id=i.appearance_id where i.trip_id=p_trip and not i.removed order by i.starts_at,i.id)q;
 select coalesce(jsonb_agg(to_jsonb(q)),'[]') into audit from(select * from zoi.trip_audit where trip_id=p_trip order by id desc limit 100)q;
 return jsonb_build_object('ok',true,'trip',to_jsonb(t),'items',items,'audit',audit,'server_now',clock_timestamp());end $$;
revoke all on function public.appearance_propose(uuid,jsonb),public.appearance_decide(uuid,integer,text),public.appearance_operator(uuid),public.trip_discover(text,text,text),public.artist_shows(uuid),public.trip_save(uuid,integer,jsonb),public.trip_item_save(uuid,uuid,integer,jsonb),public.trip_remove(uuid,uuid,integer),public.trips_mine(),public.trip_get(uuid) from public,anon,authenticated;
grant execute on function public.trip_discover(text,text,text),public.artist_shows(uuid) to anon,authenticated;
grant execute on function public.appearance_propose(uuid,jsonb),public.appearance_decide(uuid,integer,text),public.appearance_operator(uuid),public.trip_save(uuid,integer,jsonb),public.trip_item_save(uuid,uuid,integer,jsonb),public.trip_remove(uuid,uuid,integer),public.trips_mine(),public.trip_get(uuid) to authenticated;
commit;
