begin;
set local lock_timeout='5s';
create table zoi.community_profiles(profile_id uuid primary key references zoi.user_profiles(id),handle text not null unique,display_name text not null,bio text not null default '',city text,country text,interests text[] not null default '{}',avatar_media_id uuid,avatar_url text,version integer not null default 1,initial_data jsonb not null,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp());
delete from zoi.feed_follows f where f.follower=f.followee or not exists(select 1 from zoi.user_profiles u where u.id=f.follower) or not exists(select 1 from zoi.user_profiles u where u.id=f.followee) or exists(select 1 from zoi.feed_blocks b where (b.blocker=f.follower and b.blocked=f.followee) or (b.blocker=f.followee and b.blocked=f.follower));
create index community_followee on zoi.feed_follows(followee,follower);
create table zoi.community_saved(profile_id uuid not null references zoi.user_profiles(id),post_id uuid not null references zoi.feed_posts(id) on delete cascade,created_at timestamptz not null default clock_timestamp(),primary key(profile_id,post_id));
create index community_saved_created on zoi.community_saved(profile_id,created_at desc);
create table zoi.community_mutes(profile_id uuid not null references zoi.user_profiles(id),muted uuid not null references zoi.user_profiles(id),created_at timestamptz not null default clock_timestamp(),primary key(profile_id,muted),check(profile_id<>muted));
create table zoi.community_preferences(profile_id uuid primary key references zoi.user_profiles(id),topics text[] not null default '{}',city text,country text,locality_enabled boolean not null default false,version integer not null default 1,initial_data jsonb not null,updated_at timestamptz not null default clock_timestamp());
create table zoi.community_post_context(post_id uuid primary key references zoi.feed_posts(id) on delete cascade,intent text not null default 'moment' check(intent in('question','recommendation','moment','event')),topics text[] not null default '{}',city text,country text,accepted_comment_id uuid references zoi.feed_comments(id) on delete set null,version integer not null default 1);
create table zoi.community_comment_requests(profile_id uuid not null references zoi.user_profiles(id),request_id uuid not null,post_id uuid not null references zoi.feed_posts(id) on delete cascade,comment_id uuid not null references zoi.feed_comments(id) on delete cascade,body text not null,primary key(profile_id,request_id));
create table zoi.community_notifications(id uuid primary key default gen_random_uuid(),recipient uuid not null references zoi.user_profiles(id),actor uuid not null references zoi.user_profiles(id),kind text not null check(kind in('follow','like','comment','accepted_answer')),post_id uuid references zoi.feed_posts(id) on delete cascade,comment_id uuid references zoi.feed_comments(id) on delete cascade,event_key text not null unique,created_at timestamptz not null default clock_timestamp(),read_at timestamptz);
create index community_notifications_recipient on zoi.community_notifications(recipient,created_at desc);
create table zoi.community_reports(id uuid primary key default gen_random_uuid(),reporter uuid not null references zoi.user_profiles(id),post_id uuid references zoi.feed_posts(id) on delete set null,request_id uuid not null,reason text not null,details text not null,content_snapshot jsonb not null,status text not null default 'pending' check(status in('pending','dismissed','hidden')),reviewed_by uuid references zoi.user_profiles(id),review_note text,created_at timestamptz not null default clock_timestamp(),reviewed_at timestamptz,unique(reporter,request_id));
create index community_reports_status on zoi.community_reports(status,created_at);
-- New private graph/control tables are only reachable through scoped RPCs.
do $$declare t text;begin foreach t in array array['community_profiles','feed_follows','community_saved','community_mutes','community_preferences','community_post_context','community_comment_requests','community_notifications','community_reports'] loop execute format('alter table zoi.%I enable row level security',t);execute format('revoke all on zoi.%I from public,anon,authenticated',t);end loop;end $$;
-- Existing direct table access must not bypass block/status or private profile projection.
alter table zoi.feed_posts enable row level security;alter table zoi.feed_comments enable row level security;alter table zoi.feed_likes enable row level security;
revoke all on zoi.feed_posts,zoi.feed_comments,zoi.feed_likes from public,anon,authenticated;
create function zoi.community_viewer() returns uuid language sql stable security definer set search_path='' as $$select id from zoi.user_profiles where auth_user_id=auth.uid() limit 1$$;
create function zoi.community_actor() returns uuid language plpgsql security definer set search_path='' as $$declare actor uuid;begin if auth.uid() is null then raise exception 'community_sign_in_required' using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended('community_auth:'||auth.uid()::text,0));actor:=zoi.ensure_profile();return actor;end $$;
create function zoi.community_topics() returns text[] language sql immutable as $$select array['food','travel','business','careers','culture','language','music','faith','sport','family','local','community']::text[]$$;
create function zoi.community_topic_array(p_data jsonb,p_limit integer) returns text[] language plpgsql immutable set search_path='' as $$declare result text[];begin
 if jsonb_typeof(p_data) is distinct from 'array' then raise exception 'community_invalid_topics';end if;if jsonb_array_length(p_data)>p_limit or exists(select 1 from jsonb_array_elements(p_data) x where jsonb_typeof(x)<>'string' or not ((x#>>'{}')=any(zoi.community_topics()))) then raise exception 'community_invalid_topics';end if;select coalesce(array_agg(distinct x order by x),'{}') into result from jsonb_array_elements_text(p_data)x;return result;end $$;
create function zoi.community_blocked(p_viewer uuid,p_author uuid) returns boolean language sql stable security definer set search_path='' as $$select p_viewer is not null and exists(select 1 from zoi.feed_blocks b where (b.blocker=p_viewer and b.blocked=p_author) or (b.blocked=p_viewer and b.blocker=p_author))$$;
create function zoi.community_post_visible(p_post uuid,p_viewer uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from zoi.feed_posts p where p.id=p_post and p.status='visible' and not zoi.community_blocked(p_viewer,p.profile_id))$$;
-- Media specialist replaces these internal adapters with verified-owned asset projections.
create function zoi.community_avatar_url(p_actor uuid,p_asset uuid) returns text language plpgsql security definer set search_path='' as $$begin if p_asset is not null then return zoi.community_media_avatar(p_actor,p_asset);end if;return null;end $$;
create function zoi.community_media_for_post(p_post uuid) returns jsonb language sql stable security definer set search_path='' as $$select coalesce(jsonb_agg(jsonb_build_object('id',null,'type','image','url',x#>>'{}','poster_url',null,'mime_type',null,'width',null,'height',null,'duration_seconds',null,'alt','')),'[]') from zoi.feed_posts p cross join lateral jsonb_array_elements(case when jsonb_typeof(p.media)='array' then p.media else '[]' end)x where p.id=p_post and jsonb_typeof(x)='string' and (x#>>'{}') like 'https://csebihpaychdkanjjsmz.supabase.co/storage/v1/object/public/media/%'$$;
create function zoi.community_context_set(p_actor uuid,p_post uuid,p_data jsonb) returns void language plpgsql security definer set search_path='' as $$declare topics text[];begin
 if not exists(select 1 from zoi.feed_posts where id=p_post and profile_id=p_actor) then raise exception 'community_post_not_owned';end if;
 if jsonb_typeof(p_data) is distinct from 'object' or coalesce(p_data->>'intent','moment') not in('question','recommendation','moment','event') or length(coalesce(p_data->>'city',''))>120 or length(coalesce(p_data->>'country',''))>120 then raise exception 'community_invalid_context';end if;topics:=zoi.community_topic_array(coalesce(p_data->'topics','[]'),5);
 insert into zoi.community_post_context(post_id,intent,topics,city,country) values(p_post,coalesce(p_data->>'intent','moment'),topics,nullif(btrim(p_data->>'city'),''),nullif(btrim(p_data->>'country'),''));end $$;
create function zoi.community_author(p_profile uuid) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('id',u.id,'handle',p.handle,'display_name',coalesce(p.display_name,'Community member'),'avatar_url',p.avatar_url,'city',p.city,'country',p.country) from zoi.user_profiles u left join zoi.community_profiles p on p.profile_id=u.id where u.id=p_profile$$;
create function zoi.community_profile(p_profile uuid,p_viewer uuid) returns jsonb language sql stable security definer set search_path='' as $$select zoi.community_author(u.id)||jsonb_build_object('bio',coalesce(p.bio,''),'interests',coalesce(to_jsonb(p.interests),'[]'::jsonb),'version',coalesce(p.version,0),'following_count',(select count(*) from zoi.feed_follows where follower=u.id),'follower_count',(select count(*) from zoi.feed_follows where followee=u.id),'post_count',(select count(*) from zoi.feed_posts where profile_id=u.id and status='visible'),'followed',exists(select 1 from zoi.feed_follows where follower=p_viewer and followee=u.id),'mine',coalesce(u.id=p_viewer,false)) from zoi.user_profiles u left join zoi.community_profiles p on p.profile_id=u.id where u.id=p_profile and not zoi.community_blocked(p_viewer,u.id)$$;
create function zoi.community_notify(p_recipient uuid,p_actor uuid,p_kind text,p_post uuid,p_comment uuid,p_key text) returns void language plpgsql security definer set search_path='' as $$begin if p_recipient is null or p_recipient=p_actor or zoi.community_blocked(p_recipient,p_actor) or exists(select 1 from zoi.community_mutes where profile_id=p_recipient and muted=p_actor) then return;end if;insert into zoi.community_notifications(recipient,actor,kind,post_id,comment_id,event_key) values(p_recipient,p_actor,p_kind,p_post,p_comment,p_key) on conflict(event_key) do nothing;end $$;
-- Private helpers cannot be invoked to impersonate another member.
revoke all on function zoi.community_viewer(),zoi.community_actor(),zoi.community_topics(),zoi.community_topic_array(jsonb,integer),zoi.community_blocked(uuid,uuid),zoi.community_post_visible(uuid,uuid),zoi.community_avatar_url(uuid,uuid),zoi.community_media_for_post(uuid),zoi.community_context_set(uuid,uuid,jsonb),zoi.community_author(uuid),zoi.community_profile(uuid,uuid),zoi.community_notify(uuid,uuid,text,uuid,uuid,text) from public,anon,authenticated;
create function public.community_profile_get(p_handle text default null,p_profile uuid default null) returns jsonb language plpgsql stable security definer set search_path='' as $$declare target uuid;viewer uuid:=zoi.community_viewer();begin if (p_handle is null)=(p_profile is null) then raise exception 'community_profile_reference_required';end if;if p_handle is not null then select profile_id into target from zoi.community_profiles where handle=lower(p_handle);else select u.id into target from zoi.user_profiles u where u.id=p_profile and (exists(select 1 from zoi.community_profiles c where c.profile_id=u.id) or exists(select 1 from zoi.feed_posts f where f.profile_id=u.id and f.status='visible'));end if;return jsonb_build_object('ok',true,'profile',zoi.community_profile(target,viewer));end $$;
create function public.community_profile_save(p_expected_version integer,p_data jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;p zoi.community_profiles;prior zoi.community_profiles;topics text[];avatar uuid;v_url text;v_handle text;begin
 actor:=zoi.community_actor();perform 1 from zoi.user_profiles where id=actor for update;select * into prior from zoi.community_profiles where profile_id=actor for update;
 if prior.profile_id is not null and p_expected_version=0 then if prior.initial_data is distinct from p_data then raise exception 'community_version_conflict';end if;return jsonb_build_object('ok',true,'profile',zoi.community_profile(actor,actor)||jsonb_build_object('avatar_media_id',prior.avatar_media_id));end if;
 v_handle:=lower(btrim(p_data->>'handle'));if jsonb_typeof(p_data) is distinct from 'object' or octet_length(p_data::text)>12000 or coalesce(v_handle,'') !~ '^[a-z0-9_]{3,30}$' or v_handle in('admin','administrator','support','zoi','buygreek','moderator','official') or length(btrim(coalesce(p_data->>'display_name',''))) not between 1 and 80 or length(coalesce(p_data->>'bio',''))>400 or length(coalesce(p_data->>'city',''))>120 or length(coalesce(p_data->>'country',''))>120 then raise exception 'community_invalid_profile';end if;
 topics:=zoi.community_topic_array(coalesce(p_data->'interests','[]'),8);avatar:=nullif(p_data->>'avatar_media_id','')::uuid;v_url:=zoi.community_avatar_url(actor,avatar);
 if exists(select 1 from zoi.community_profiles where community_profiles.handle=v_handle and profile_id<>actor) then raise exception 'community_handle_taken';end if;
 if prior.profile_id is null then if p_expected_version is distinct from 0 then raise exception 'community_version_conflict';end if;
 insert into zoi.community_profiles(profile_id,handle,display_name,bio,city,country,interests,avatar_media_id,avatar_url,initial_data) values(actor,v_handle,btrim(p_data->>'display_name'),coalesce(p_data->>'bio',''),nullif(btrim(p_data->>'city'),''),nullif(btrim(p_data->>'country'),''),topics,avatar,v_url,p_data) returning * into p;
 else if prior.version is distinct from p_expected_version then raise exception 'community_version_conflict';end if;
 update zoi.community_profiles set handle=v_handle,display_name=btrim(p_data->>'display_name'),bio=coalesce(p_data->>'bio',''),city=nullif(btrim(p_data->>'city'),''),country=nullif(btrim(p_data->>'country'),''),interests=topics,avatar_media_id=avatar,avatar_url=v_url,version=version+1,updated_at=clock_timestamp() where profile_id=actor returning * into p;end if;
 return jsonb_build_object('ok',true,'profile',zoi.community_profile(actor,actor)||jsonb_build_object('avatar_media_id',p.avatar_media_id));end $$;
create function public.community_preferences_save(p_expected_version integer,p_data jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;p zoi.community_preferences;v_topics text[];begin
 actor:=zoi.community_actor();perform 1 from zoi.user_profiles where id=actor for update;select * into p from zoi.community_preferences where profile_id=actor for update;
 if p.profile_id is not null and p_expected_version=0 then if p.initial_data is distinct from p_data then raise exception 'community_version_conflict';end if;return jsonb_build_object('ok',true,'preferences',to_jsonb(p)-'profile_id'-'initial_data'-'updated_at');end if;
 if jsonb_typeof(p_data) is distinct from 'object' or jsonb_typeof(p_data->'locality_enabled') is distinct from 'boolean' or length(coalesce(p_data->>'city',''))>120 or length(coalesce(p_data->>'country',''))>120 or ((p_data->>'locality_enabled')::boolean and btrim(coalesce(p_data->>'city',''))='' and btrim(coalesce(p_data->>'country',''))='') then raise exception 'community_invalid_preferences';end if;v_topics:=zoi.community_topic_array(coalesce(p_data->'topics','[]'),8);
 if p.profile_id is null then if p_expected_version is distinct from 0 then raise exception 'community_version_conflict';end if;insert into zoi.community_preferences(profile_id,topics,city,country,locality_enabled,initial_data) values(actor,v_topics,nullif(btrim(p_data->>'city'),''),nullif(btrim(p_data->>'country'),''),(p_data->>'locality_enabled')::boolean,p_data) returning * into p;
 else if p.version is distinct from p_expected_version then raise exception 'community_version_conflict';end if;update zoi.community_preferences set topics=v_topics,city=nullif(btrim(p_data->>'city'),''),country=nullif(btrim(p_data->>'country'),''),locality_enabled=(p_data->>'locality_enabled')::boolean,version=version+1,updated_at=clock_timestamp() where profile_id=actor returning * into p;end if;
 return jsonb_build_object('ok',true,'preferences',to_jsonb(p)-'profile_id'-'initial_data'-'updated_at');end $$;
create function public.community_follow_set(p_profile uuid,p_follow boolean) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;added boolean;begin actor:=zoi.community_actor();perform 1 from zoi.user_profiles where id in(actor,p_profile) order by id for update;
 if p_profile is null or p_profile=actor or p_follow is null or not exists(select 1 from zoi.user_profiles u where u.id=p_profile and (exists(select 1 from zoi.community_profiles c where c.profile_id=u.id) or exists(select 1 from zoi.feed_posts f where f.profile_id=u.id and f.status='visible'))) or zoi.community_blocked(actor,p_profile) then raise exception 'community_relationship_unavailable';end if;
 if p_follow then insert into zoi.feed_follows(follower,followee) values(actor,p_profile) on conflict do nothing;added:=found;if added then perform zoi.community_notify(p_profile,actor,'follow',null,null,'follow:'||actor||':'||p_profile);end if;
 else delete from zoi.feed_follows where follower=actor and followee=p_profile;delete from zoi.community_notifications where event_key='follow:'||actor||':'||p_profile;end if;
 return jsonb_build_object('ok',true,'profile_id',p_profile,'following',p_follow,'follower_count',(select count(*) from zoi.feed_follows where followee=p_profile));end $$;
create function public.community_saved_set(p_post uuid,p_saved boolean) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;begin actor:=zoi.community_actor();if p_saved is null or not zoi.community_post_visible(p_post,actor) then raise exception 'community_post_unavailable';end if;
 if p_saved then insert into zoi.community_saved(profile_id,post_id) values(actor,p_post) on conflict do nothing;else delete from zoi.community_saved where profile_id=actor and post_id=p_post;end if;return jsonb_build_object('ok',true,'post_id',p_post,'saved',p_saved);end $$;
create function public.community_block_set(p_profile uuid,p_blocked boolean) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid;begin v_actor:=zoi.community_actor();perform 1 from zoi.user_profiles where id in(v_actor,p_profile) order by id for update;if p_profile is null or p_profile=v_actor or p_blocked is null or not exists(select 1 from zoi.user_profiles where id=p_profile) then raise exception 'community_relationship_unavailable';end if;
 if p_blocked then insert into zoi.feed_blocks(blocker,blocked) values(v_actor,p_profile) on conflict do nothing;delete from zoi.feed_follows where (follower=v_actor and followee=p_profile) or (follower=p_profile and followee=v_actor);delete from zoi.community_notifications where (recipient=v_actor and community_notifications.actor=p_profile) or (recipient=p_profile and community_notifications.actor=v_actor);
 else delete from zoi.feed_blocks where blocker=v_actor and blocked=p_profile;end if;return jsonb_build_object('ok',true,'profile_id',p_profile,'blocked',p_blocked);end $$;
create function public.community_mute_set(p_profile uuid,p_muted boolean) returns jsonb language plpgsql security definer set search_path='' as $$declare actor uuid;begin actor:=zoi.community_actor();if p_profile is null or p_profile=actor or p_muted is null or not exists(select 1 from zoi.user_profiles where id=p_profile) then raise exception 'community_relationship_unavailable';end if;
 if p_muted then insert into zoi.community_mutes(profile_id,muted) values(actor,p_profile) on conflict do nothing;else delete from zoi.community_mutes where profile_id=actor and muted=p_profile;end if;return jsonb_build_object('ok',true,'profile_id',p_profile,'muted',p_muted);end $$;
create function zoi.community_comment_json(p_id uuid,p_viewer uuid) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('id',c.id,'post_id',c.post_id,'body',c.body,'created_at',c.created_at,'author',zoi.community_author(c.profile_id),'mine',coalesce(c.profile_id=p_viewer,false),'accepted',coalesce(x.accepted_comment_id=c.id,false)) from zoi.feed_comments c left join zoi.community_post_context x on x.post_id=c.post_id where c.id=p_id and c.status='visible' and zoi.community_post_visible(c.post_id,p_viewer) and not zoi.community_blocked(p_viewer,c.profile_id)$$;
create function zoi.community_post_json(p_id uuid,p_viewer uuid,p_reasons jsonb default '["Recent post"]') returns jsonb language sql stable security definer set search_path='' as $$
 select jsonb_build_object('id',p.id,'body',p.body,'created_at',p.created_at,'author',zoi.community_author(p.profile_id),'listing',(select jsonb_build_object('id',l.id,'name',l.name,'slug',l.slug,'entity_type',l.entity_type) from zoi.listings l where l.id=p.listing_id and l.publish_status='published' and coalesce(l.marketplace_status,'')<>'hidden'),'intent',coalesce(x.intent,'moment'),'topics',coalesce(to_jsonb(x.topics),'[]'::jsonb),'city',x.city,'country',x.country,'media',zoi.community_media_for_post(p.id),'likes',(select count(*) from zoi.feed_likes k where k.post_id=p.id and not zoi.community_blocked(p_viewer,k.profile_id)),'comments',(select count(*) from zoi.feed_comments c where c.post_id=p.id and c.status='visible' and not zoi.community_blocked(p_viewer,c.profile_id)),'liked',exists(select 1 from zoi.feed_likes k where k.post_id=p.id and k.profile_id=p_viewer),'saved',exists(select 1 from zoi.community_saved s where s.post_id=p.id and s.profile_id=p_viewer),'mine',coalesce(p.profile_id=p_viewer,false),'accepted_comment_id',case when zoi.community_comment_json(x.accepted_comment_id,p_viewer) is not null then x.accepted_comment_id end,'context_version',coalesce(x.version,1),'ranking_reasons',p_reasons) from zoi.feed_posts p left join zoi.community_post_context x on x.post_id=p.id where p.id=p_id and zoi.community_post_visible(p.id,p_viewer)$$;
create function public.community_post_get(p_post uuid) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('ok',true,'post',zoi.community_post_json(p_post,zoi.community_viewer()))$$;
create function zoi.community_interaction_lock(p_post uuid,p_actor uuid) returns void language plpgsql security definer set search_path='' as $$declare v_owner uuid;begin select profile_id into v_owner from zoi.feed_posts where id=p_post;perform 1 from zoi.user_profiles where id in(p_actor,v_owner) order by id for update;end $$;
revoke all on function zoi.community_interaction_lock(uuid,uuid) from public,anon,authenticated;
create function public.community_like_set(p_post uuid,p_liked boolean) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();v_owner uuid;begin
 perform zoi.community_interaction_lock(p_post,v_actor);select profile_id into v_owner from zoi.feed_posts where id=p_post for update;if p_liked is null or not zoi.community_post_visible(p_post,v_actor) then raise exception 'community_post_unavailable';end if;
 if p_liked then insert into zoi.feed_likes(post_id,profile_id) values(p_post,v_actor) on conflict do nothing;if found then perform zoi.community_notify(v_owner,v_actor,'like',p_post,null,'like:'||p_post||':'||v_actor);end if;else delete from zoi.feed_likes where post_id=p_post and profile_id=v_actor;delete from zoi.community_notifications where event_key='like:'||p_post||':'||v_actor;end if;
 update zoi.feed_posts set likes=(select count(*) from zoi.feed_likes where post_id=p_post) where id=p_post;return jsonb_build_object('ok',true,'post_id',p_post,'liked',p_liked,'likes',(select count(*) from zoi.feed_likes k where post_id=p_post and not zoi.community_blocked(v_actor,k.profile_id)));end $$;
create function public.community_comments(p_post uuid,p_limit integer default 30,p_offset integer default 0) returns jsonb language plpgsql stable security definer set search_path='' as $$declare v_actor uuid:=zoi.community_viewer();v_rows jsonb;v_count integer;begin
 if p_limit is null or p_limit not between 1 and 50 or p_offset is null or p_offset not between 0 and 1000 then raise exception 'community_invalid_page';end if;if not zoi.community_post_visible(p_post,v_actor) then raise exception 'community_post_unavailable';end if;
 select coalesce(jsonb_agg(j order by created_at,id),'[]'),count(*) into v_rows,v_count from(select c.id,c.created_at,zoi.community_comment_json(c.id,v_actor) j from zoi.feed_comments c where c.post_id=p_post and c.status='visible' and not zoi.community_blocked(v_actor,c.profile_id) order by c.created_at,c.id limit p_limit+1 offset p_offset)s;
 return jsonb_build_object('ok',true,'comments',case when v_count>p_limit then v_rows-p_limit else v_rows end,'next_offset',case when v_count>p_limit and p_offset+p_limit<=1000 then p_offset+p_limit end);end $$;
create function public.community_comment(p_post uuid,p_request uuid,p_body text) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();v_prior zoi.community_comment_requests;v_id uuid;v_owner uuid;v_body text:=btrim(p_body);begin
 if p_request is null or length(coalesce(v_body,'')) not between 1 and 500 then raise exception 'community_invalid_comment';end if;
 select * into v_prior from zoi.community_comment_requests where profile_id=v_actor and request_id=p_request;if found then if v_prior.post_id is distinct from p_post or v_prior.body is distinct from v_body then raise exception 'community_request_conflict';end if;if not zoi.community_post_visible(p_post,v_actor) then raise exception 'community_post_unavailable';end if;return jsonb_build_object('ok',true,'comment',zoi.community_comment_json(v_prior.comment_id,v_actor));end if;
 perform zoi.community_interaction_lock(p_post,v_actor);select profile_id into v_owner from zoi.feed_posts where id=p_post for update;if not zoi.community_post_visible(p_post,v_actor) then raise exception 'community_post_unavailable';end if;
 if (select count(*) from zoi.feed_comments where profile_id=v_actor and created_at>clock_timestamp()-interval '1 minute')>=15 then raise exception 'community_comment_rate_limit';end if;
 insert into zoi.feed_comments(post_id,profile_id,body,status) values(p_post,v_actor,v_body,'visible') returning id into v_id;insert into zoi.community_comment_requests values(v_actor,p_request,p_post,v_id,v_body);
 update zoi.feed_posts set comments=(select count(*) from zoi.feed_comments where post_id=p_post and status='visible') where id=p_post;perform zoi.community_notify(v_owner,v_actor,'comment',p_post,v_id,'comment:'||v_id);return jsonb_build_object('ok',true,'comment',zoi.community_comment_json(v_id,v_actor));end $$;
create function public.community_accept_answer(p_post uuid,p_comment uuid,p_expected_version integer) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();v_context zoi.community_post_context;v_target uuid;begin
 select profile_id into v_target from zoi.feed_comments where id=p_comment and post_id=p_post;perform 1 from zoi.user_profiles where id in(v_actor,v_target) order by id for update;
 perform 1 from zoi.feed_posts where id=p_post and profile_id=v_actor for update;if not found or not zoi.community_post_visible(p_post,v_actor) then raise exception 'community_post_unavailable';end if;select * into v_context from zoi.community_post_context where post_id=p_post for update;
 if v_context.intent is distinct from 'question' or v_context.version is distinct from p_expected_version then raise exception 'community_version_conflict';end if;
 if p_comment is not null then select profile_id into v_target from zoi.feed_comments where id=p_comment and post_id=p_post and status='visible';if v_target is null or v_target=v_actor or zoi.community_blocked(v_actor,v_target) then raise exception 'community_answer_unavailable';end if;end if;
 update zoi.community_post_context set accepted_comment_id=p_comment,version=version+1 where post_id=p_post returning * into v_context;delete from zoi.community_notifications where post_id=p_post and kind='accepted_answer';if p_comment is not null then perform zoi.community_notify(v_target,v_actor,'accepted_answer',p_post,p_comment,'answer:'||p_post||':'||p_comment);end if;
 return jsonb_build_object('ok',true,'post_id',p_post,'accepted_comment_id',p_comment,'context_version',v_context.version);end $$;
create function zoi.community_notification_visible(p_id uuid,p_actor uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from zoi.community_notifications n where n.id=p_id and n.recipient=p_actor and not zoi.community_blocked(p_actor,n.actor) and not exists(select 1 from zoi.community_mutes m where m.profile_id=p_actor and m.muted=n.actor) and (n.post_id is null or zoi.community_post_visible(n.post_id,p_actor)) and (n.comment_id is null or zoi.community_comment_json(n.comment_id,p_actor) is not null))$$;
create function public.community_notifications(p_limit integer default 30,p_offset integer default 0) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();v_rows jsonb;v_count integer;begin
 if p_limit is null or p_limit not between 1 and 50 or p_offset is null or p_offset not between 0 and 1000 then raise exception 'community_invalid_page';end if;
 select coalesce(jsonb_agg(j order by created_at desc,id),'[]'),count(*) into v_rows,v_count from(select n.id,n.created_at,jsonb_build_object('id',n.id,'kind',n.kind,'actor',zoi.community_author(n.actor),'post_id',n.post_id,'comment_id',n.comment_id,'created_at',n.created_at,'read_at',n.read_at) j from zoi.community_notifications n where n.recipient=v_actor and zoi.community_notification_visible(n.id,v_actor) order by n.created_at desc,n.id limit p_limit+1 offset p_offset)s;
 return jsonb_build_object('ok',true,'notifications',case when v_count>p_limit then v_rows-p_limit else v_rows end,'next_offset',case when v_count>p_limit and p_offset+p_limit<=1000 then p_offset+p_limit end,'unread_count',(select count(*) from zoi.community_notifications n where n.recipient=v_actor and n.read_at is null and zoi.community_notification_visible(n.id,v_actor)));end $$;
create function public.community_notifications_read(p_ids uuid[]) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();v_count integer;begin if p_ids is null or cardinality(p_ids)>100 then raise exception 'community_invalid_notification_ids';end if;update zoi.community_notifications set read_at=clock_timestamp() where recipient=v_actor and id=any(p_ids) and read_at is null;get diagnostics v_count=row_count;return jsonb_build_object('ok',true,'updated',v_count,'unread_count',(select count(*) from zoi.community_notifications n where n.recipient=v_actor and n.read_at is null and zoi.community_notification_visible(n.id,v_actor)));end $$;
create function public.community_me() returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();v_preferences jsonb;begin
 select to_jsonb(p)-'profile_id'-'initial_data'-'updated_at' into v_preferences from zoi.community_preferences p where profile_id=v_actor;
 return jsonb_build_object('ok',true,'profile',zoi.community_profile(v_actor,v_actor)||jsonb_build_object('avatar_media_id',(select avatar_media_id from zoi.community_profiles where profile_id=v_actor)),'preferences',coalesce(v_preferences,'{"topics":[],"city":null,"country":null,"locality_enabled":false,"version":0}'::jsonb),'counts',jsonb_build_object('following',(select count(*) from zoi.feed_follows where follower=v_actor),'saved',(select count(*) from zoi.community_saved s where profile_id=v_actor and zoi.community_post_visible(s.post_id,v_actor)),'unread_notifications',(select count(*) from zoi.community_notifications n where n.recipient=v_actor and n.read_at is null and zoi.community_notification_visible(n.id,v_actor))),'blocked',(select coalesce(jsonb_agg(zoi.community_author(b.blocked) order by b.created_at),'[]') from zoi.feed_blocks b where b.blocker=v_actor),'muted',(select coalesce(jsonb_agg(zoi.community_author(m.muted) order by m.created_at),'[]') from zoi.community_mutes m where m.profile_id=v_actor),'topics',to_jsonb(zoi.community_topics()));end $$;
create function public.community_feed(p_mode text default 'for_you',p_limit integer default 20,p_offset integer default 0,p_as_of timestamptz default null,p_profile uuid default null,p_topic text default null,p_query text default '') returns jsonb language plpgsql stable security definer set search_path='' as $$declare v_actor uuid:=zoi.community_viewer();v_asof timestamptz:=coalesce(p_as_of,statement_timestamp());v_pref zoi.community_preferences;v_rows jsonb;v_count integer;begin
 if p_mode is null or p_mode not in('for_you','latest','following','saved','questions','profile','watch','near_me') or p_limit is null or p_limit not between 1 and 50 or p_offset is null or p_offset not between 0 and 1000 or not isfinite(v_asof) or v_asof>statement_timestamp()+interval '1 minute' or length(coalesce(p_query,''))>100 or (p_topic is not null and not p_topic=any(zoi.community_topics())) or (p_mode='profile' and p_profile is null) then raise exception 'community_invalid_feed';end if;
 if p_mode in('following','saved','near_me') and v_actor is null then raise exception 'community_sign_in_required' using errcode='42501';end if;select * into v_pref from zoi.community_preferences where profile_id=v_actor;
 with candidates as(select p.id,p.profile_id,p.created_at,coalesce(x.topics,'{}') topics,x.city,x.country,exists(select 1 from zoi.feed_follows f where f.follower=v_actor and f.followee=p.profile_id) follows,
 coalesce(x.topics && v_pref.topics,false) interests,coalesce(v_pref.locality_enabled and ((v_pref.city is not null and lower(x.city)=lower(v_pref.city) and (v_pref.country is null or lower(x.country)=lower(v_pref.country))) or (v_pref.city is null and v_pref.country is not null and lower(x.country)=lower(v_pref.country))),false) local
 from zoi.feed_posts p left join zoi.community_post_context x on x.post_id=p.id
 where p.created_at<=v_asof and zoi.community_post_visible(p.id,v_actor) and not exists(select 1 from zoi.community_mutes m where m.profile_id=v_actor and m.muted=p.profile_id)
 and (p_mode<>'following' or exists(select 1 from zoi.feed_follows f where f.follower=v_actor and f.followee=p.profile_id))
 and (p_mode<>'saved' or exists(select 1 from zoi.community_saved s where s.profile_id=v_actor and s.post_id=p.id))
 and (p_mode<>'profile' or p.profile_id=p_profile) and (p_mode<>'questions' or x.intent='question')
 and (p_mode<>'watch' or exists(select 1 from jsonb_array_elements(zoi.community_media_for_post(p.id)) m where m->>'type'='video'))
 and (p_topic is null or p_topic=any(x.topics)) and (coalesce(p_query,'')='' or position(lower(p_query) in lower(p.body))>0)
 order by p.created_at desc,p.id limit 1500), eligible as(select *,case when follows then 4 else 0 end+case when interests then 3 else 0 end+case when local then 2 else 0 end+1.0/(1+extract(epoch from(v_asof-created_at))/86400) score from candidates where p_mode<>'near_me' or local),ranked as(select *,row_number() over(partition by profile_id order by score desc,created_at desc,id) author_round from eligible),page as(select *,case when p_mode in('for_you','questions','watch','near_me') then to_jsonb(array_remove(array[case when follows then 'You follow this author' end,case when interests then 'Matches your interests' end,case when local then 'Matches your chosen locality' end,'Recent post'],null)) else jsonb_build_array(case p_mode when 'following' then 'You follow this author' when 'saved' then 'Saved by you' when 'questions' then 'Ask the diaspora' when 'watch' then 'Video post' when 'near_me' then 'Matches your chosen locality' when 'profile' then 'Posts by this member' else 'Recent post' end) end reasons from ranked order by case when p_mode in('for_you','questions','watch','near_me') then author_round else 0 end,case when p_mode in('for_you','questions','watch','near_me') then score else 0 end desc,created_at desc,id limit p_limit+1 offset p_offset)
 select coalesce(jsonb_agg(zoi.community_post_json(id,v_actor,reasons) order by case when p_mode in('for_you','questions','watch','near_me') then author_round else 0 end,case when p_mode in('for_you','questions','watch','near_me') then score else 0 end desc,created_at desc,id),'[]'),count(*) into v_rows,v_count from page;
 return jsonb_build_object('ok',true,'mode',p_mode,'as_of',v_asof,'posts',case when v_count>p_limit then v_rows-p_limit else v_rows end,'next_offset',case when v_count>p_limit and p_offset+p_limit<=1000 then p_offset+p_limit end,'ranking_rules',jsonb_build_array('Only visible posts; blocked and muted authors excluded','For you: follows, chosen interests and locality, recency, then author diversity','No paid placement or invented engagement'));end $$;
create function public.community_report(p_post uuid,p_reason text,p_details text,p_request uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();v_prior zoi.community_reports;v_snapshot jsonb;begin
 if p_request is null or p_reason is null or p_reason not in('spam','scam','harassment','hate','privacy','other') or length(coalesce(p_details,''))>1000 then raise exception 'community_invalid_report';end if;
 select * into v_prior from zoi.community_reports where reporter=v_actor and request_id=p_request;if found then if v_prior.content_snapshot->>'id' is distinct from p_post::text or v_prior.reason is distinct from p_reason or v_prior.details is distinct from coalesce(p_details,'') then raise exception 'community_request_conflict';end if;return jsonb_build_object('ok',true,'report_id',v_prior.id,'status',v_prior.status);end if;
 v_snapshot:=zoi.community_post_json(p_post,v_actor);if v_snapshot is null then raise exception 'community_post_unavailable';end if;if (select count(*) from zoi.community_reports where reporter=v_actor and created_at>clock_timestamp()-interval '1 day')>=10 then raise exception 'community_report_rate_limit';end if;
 insert into zoi.community_reports(reporter,post_id,request_id,reason,details,content_snapshot) values(v_actor,p_post,p_request,p_reason,coalesce(p_details,''),v_snapshot) returning * into v_prior;return jsonb_build_object('ok',true,'report_id',v_prior.id,'status',v_prior.status);end $$;
create function public.community_reports_review(p_report uuid,p_action text,p_note text) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();v_report zoi.community_reports;begin
 if not coalesce(zoi.is_admin(),false) then raise exception 'community_moderator_required' using errcode='42501';end if;if p_action is null or p_action not in('dismiss','hide') or length(btrim(coalesce(p_note,''))) not between 1 and 1000 then raise exception 'community_invalid_review';end if;
 select * into v_report from zoi.community_reports where id=p_report for update;if not found then raise exception 'community_report_unavailable';end if;if v_report.status<>'pending' then if v_report.status=(case p_action when 'hide' then 'hidden' else 'dismissed' end) and v_report.review_note=p_note then return jsonb_build_object('ok',true,'report_id',v_report.id,'status',v_report.status);end if;raise exception 'community_review_already_completed';end if;
 if p_action='hide' then update zoi.feed_posts set status='hidden' where id=v_report.post_id;end if;update zoi.community_reports set status=case p_action when 'hide' then 'hidden' else 'dismissed' end,reviewed_by=v_actor,review_note=p_note,reviewed_at=clock_timestamp() where id=p_report returning * into v_report;return jsonb_build_object('ok',true,'report_id',v_report.id,'status',v_report.status);end $$;
create function public.community_reports_queue(p_limit integer default 30,p_offset integer default 0) returns jsonb language plpgsql security definer set search_path='' as $$declare v_rows jsonb;begin
 if not coalesce(zoi.is_admin(),false) then raise exception 'community_moderator_required' using errcode='42501';end if;if p_limit is null or p_limit not between 1 and 50 or p_offset is null or p_offset not between 0 and 1000 then raise exception 'community_invalid_page';end if;
 select coalesce(jsonb_agg(to_jsonb(q) order by created_at,id),'[]') into v_rows from(select * from zoi.community_reports where status='pending' order by created_at,id limit p_limit offset p_offset)q;return jsonb_build_object('ok',true,'reports',v_rows);end $$;
-- Legacy mutation/read wrappers are completed after the exact live signatures are verified.
create function zoi.community_legacy_post(p_id uuid,p_viewer uuid) returns jsonb language sql stable security definer set search_path='' as $$select j||jsonb_build_object('author_id',j#>'{author,id}','author',j#>'{author,display_name}','author_city',j#>'{author,city}','listing_id',j#>'{listing,id}','listing_name',j#>'{listing,name}','listing_slug',j#>'{listing,slug}','nameday_ref',p.nameday_ref) from zoi.feed_posts p cross join lateral(select zoi.community_post_json(p.id,p_viewer) j)x where p.id=p_id and j is not null$$;
create or replace function public.feed_list(p_limit integer default 30,p_offset integer default 0,p_sort text default 'new',p_place uuid default null) returns jsonb language plpgsql stable security definer set search_path='' as $$declare v_feed jsonb;v_actor uuid:=zoi.community_viewer();begin
 v_feed:=public.community_feed(case when p_sort='top' then 'for_you' else 'latest' end,least(greatest(coalesce(p_limit,30),1),50),least(greatest(coalesce(p_offset,0),0),1000));return(select coalesce(jsonb_agg(zoi.community_legacy_post((p->>'id')::uuid,v_actor) order by ord),'[]') from jsonb_array_elements(v_feed->'posts') with ordinality x(p,ord));end $$;
create or replace function public.feed_comments_list(p_post uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare v_actor uuid:=zoi.community_viewer();begin if not zoi.community_post_visible(p_post,v_actor) then return '[]';end if;return(select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'body',c.body,'created_at',c.created_at,'author_id',c.profile_id,'author',zoi.community_author(c.profile_id)->>'display_name','mine',coalesce(c.profile_id=v_actor,false)) order by c.created_at,c.id),'[]') from(select * from zoi.feed_comments where post_id=p_post and status='visible' and not zoi.community_blocked(v_actor,profile_id) order by created_at,id limit 100)c);end $$;
create or replace function public.feed_like(p_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();begin perform zoi.community_interaction_lock(p_id,v_actor);perform 1 from zoi.feed_posts where id=p_id for update;return public.community_like_set(p_id,not exists(select 1 from zoi.feed_likes where post_id=p_id and profile_id=v_actor));end $$;
create or replace function public.feed_comment(p_post uuid,p_body text) returns jsonb language plpgsql security definer set search_path='' as $$declare v_result jsonb;begin v_result:=public.community_comment(p_post,gen_random_uuid(),p_body);return jsonb_build_object('ok',true,'comments',(public.community_post_get(p_post)#>'{post,comments}'));end $$;
create or replace function public.feed_delete(p_id uuid) returns boolean language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();begin delete from zoi.feed_posts where id=p_id and profile_id=v_actor;return found;end $$;


create or replace function public.feed_get(p_id uuid) returns jsonb language sql stable security definer set search_path='' as $$select coalesce(zoi.community_legacy_post(p_id,zoi.community_viewer()),'null'::jsonb)$$;
create or replace function public.feed_follow(p_profile uuid) returns jsonb language sql security definer set search_path='' as $$select public.community_follow_set(p_profile,true)$$;
create or replace function public.feed_unfollow(p_profile uuid) returns jsonb language sql security definer set search_path='' as $$select public.community_follow_set(p_profile,false)$$;
create or replace function public.feed_block(p_profile uuid) returns jsonb language sql security definer set search_path='' as $$select public.community_block_set(p_profile,true)$$;
create or replace function public.feed_unblock(p_profile uuid) returns jsonb language sql security definer set search_path='' as $$select public.community_block_set(p_profile,false)$$;
create or replace function public.feed_follow_counts(p_profile uuid) returns jsonb language sql stable security definer set search_path='' as $$select case when zoi.community_blocked(zoi.community_viewer(),p_profile) then 'null'::jsonb else jsonb_build_object('followers',(select count(*) from zoi.feed_follows where followee=p_profile),'following',(select count(*) from zoi.feed_follows where follower=p_profile),'i_follow',exists(select 1 from zoi.feed_follows where follower=zoi.community_viewer() and followee=p_profile)) end$$;
create or replace function public.feed_report(p_id uuid,p_reason text default null) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=zoi.community_actor();v_id uuid;begin select request_id into v_id from zoi.community_reports where reporter=v_actor and post_id=p_id order by created_at limit 1;if v_id is not null then return jsonb_build_object('ok',true);end if;perform public.community_report(p_id,'other',left(coalesce(p_reason,''),200),gen_random_uuid());return jsonb_build_object('ok',true);end $$;
create or replace function public.community_stats() returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('posts',count(*),'members',count(distinct p.profile_id),'places',count(distinct case when l.publish_status='published' and coalesce(l.marketplace_status,'')<>'hidden' then l.id end)) from zoi.feed_posts p left join zoi.listings l on l.id=p.listing_id where zoi.community_post_visible(p.id,zoi.community_viewer())$$;
create or replace function public.community_trending(p_limit integer default 6) returns jsonb language sql stable security definer set search_path='' as $$select coalesce(jsonb_agg(to_jsonb(q) order by n desc,last_post desc),'[]') from(select l.id,l.name,l.slug,coalesce(l.canonical_path,'/p/'||l.slug) path,l.city,count(*) n,max(p.created_at) last_post from zoi.feed_posts p join zoi.listings l on l.id=p.listing_id where p.created_at>statement_timestamp()-interval '30 days' and zoi.community_post_visible(p.id,zoi.community_viewer()) and l.publish_status='published' and coalesce(l.marketplace_status,'')<>'hidden' group by l.id,l.name,l.slug,l.canonical_path,l.city order by n desc,last_post desc limit least(greatest(coalesce(p_limit,6),1),12))q$$;
-- Preserve old reports in their existing restricted archive; legacy new submissions use the audited queue.
alter table zoi.feed_reports enable row level security;revoke all on zoi.feed_reports from public,anon,authenticated;

alter table zoi.feed_blocks enable row level security;revoke all on zoi.feed_blocks from public,anon,authenticated;
create index if not exists community_visible_posts_created on zoi.feed_posts(created_at desc,id) where status='visible';
create index if not exists community_visible_comments_post on zoi.feed_comments(post_id,created_at,id) where status='visible';
create index if not exists community_posts_author_created on zoi.feed_posts(profile_id,created_at desc);
do $$declare f record;begin for f in select p.oid::regprocedure sig,n.nspname,p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='zoi' and p.proname in('community_actor','community_author','community_avatar_url','community_blocked','community_comment_json','community_context_set','community_interaction_lock','community_legacy_post','community_media_for_post','community_notification_visible','community_notify','community_post_json','community_post_visible','community_profile','community_topic_array','community_topics','community_viewer')) or (n.nspname='public' and p.proname in('community_accept_answer','community_block_set','community_comment','community_comments','community_feed','community_follow_set','community_like_set','community_me','community_mute_set','community_notifications','community_notifications_read','community_post_get','community_preferences_save','community_profile_get','community_profile_save','community_report','community_reports_queue','community_reports_review','community_saved_set','community_stats','community_trending','feed_block','feed_comment','feed_comments_list','feed_delete','feed_follow','feed_follow_counts','feed_get','feed_like','feed_list','feed_report','feed_unblock','feed_unfollow')) loop execute 'revoke all on function '||f.sig||' from public,anon,authenticated';if f.nspname='public' then execute 'grant execute on function '||f.sig||' to authenticated';if f.proname in('community_feed','community_post_get','community_profile_get','community_comments','feed_list','feed_comments_list','feed_get','feed_follow_counts','community_stats','community_trending') then execute 'grant execute on function '||f.sig||' to anon';end if;end if;end loop;end $$;
commit;
