const {chromium}=require('playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs/promises');
const origin=process.env.ZOI_ORIGIN||'https://www.zoi.city';
const slug='giannis-ploutarchos-andromache-toronto-2027',canonical='/events/'+slug+'/',expectedID=process.env.TORONTO_EVENT_ID;
const readRPC=new Set(['explore_search','dir_counts','explore_cities','explore_fresh','home_entity','home_stats','zoi_me','event_plan_get','event_plan_list']);
(async()=>{const results={origin,at:new Date().toISOString(),expectedID:expectedID||null,checks:[],limitations:['Anonymous public browser; no customer writes, invitations, payment, reservations or native acceptance.']};let browser;try{
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox','--enable-unsafe-swiftshader']});
 for(const width of [390,1440]){const context=await browser.newContext({viewport:{width,height:900}});const page=await context.newPage();const errors=[],blocked=[],searchRows=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const req=route.request(),url=new URL(req.url()),rpc=url.pathname.match(/\/rest\/v1\/rpc\/([^/]+)$/)?.[1];if(['GET','HEAD','OPTIONS'].includes(req.method())||(req.method()==='POST'&&readRPC.has(rpc)))return route.continue();blocked.push({method:req.method(),path:url.pathname});return route.abort();});
 page.on('response',async response=>{if(new URL(response.url()).pathname.endsWith('/rpc/explore_search')){try{const rows=await response.json();if(Array.isArray(rows))searchRows.push(...rows);}catch{}}});
 async function check(name,fn){try{const details=await fn();results.checks.push({width,name,pass:true,details});console.log('PASS',width,name);}catch(e){results.checks.push({width,name,pass:false,error:e.message});console.error('FAIL',width,name,e.message);}}
 await check('singular redirect query and valid fragment',async()=>{for(const suffix of ['', '/']){const response=await page.goto(origin+'/event/'+slug+suffix+'?qa_catalogue=read-only#signature-room',{waitUntil:'domcontentloaded',timeout:60000});const url=new URL(page.url());assert.equal(url.pathname,canonical);assert.equal(url.searchParams.get('qa_catalogue'),'read-only');assert.equal(url.hash,'#signature-room');assert.equal(await page.locator('#signature-room').count(),1);assert.equal(await page.locator('link[rel=canonical]').getAttribute('href'),origin+canonical);assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'noindex,follow');assert(response.ok());}return{url:page.url()};});
 await check('interactive room table 10 to group',async()=>{await page.goto(origin+canonical+'#signature-room',{waitUntil:'domcontentloaded',timeout:60000});const room=page.locator('#signature-room');await room.locator('canvas').first().waitFor({timeout:45000});await room.locator('[data-selection-title]').waitFor();const toggle=room.locator('[data-details-toggle]');if(await toggle.isVisible()&&await toggle.getAttribute('aria-expanded')!=='true')await toggle.click();await room.locator('[data-find]').selectOption('10');assert.match(await room.locator('[data-selection-title]').textContent(),/10/);await page.screenshot({path:'/tmp/toronto-catalogue-room-'+width+'.png',fullPage:false});await room.locator('[data-request]').click();await page.locator('[data-content] [data-count]').waitFor();assert.match(await page.locator('[data-content]').textContent(),/Sponsor booth 10/);await page.locator('[data-content] [data-next]').click();await page.locator('[data-ticket-quantity]').first().waitFor();assert.match(await page.locator('[data-content]').textContent(),/private drafts/);await page.screenshot({path:'/tmp/toronto-catalogue-group-'+width+'.png',fullPage:false});return{table:'10',groupInputs:await page.locator('[data-ticket-quantity]').count()};});
 await check('public catalogue search exact event and same room',async()=>{await page.goto(origin+'/explore/?q='+encodeURIComponent('Ploutarchos Toronto')+'&type=event',{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(s=>Array.from(document.querySelectorAll('a[href]')).some(a=>a.getAttribute('href').includes(s)),slug,{timeout:30000}).catch(()=>{throw Error('Exact Toronto catalogue result is absent from rendered search; matching RPC rows: '+searchRows.filter(r=>r.slug===slug).length);});const row=searchRows.find(r=>r.slug===slug);assert(row,'Exact catalogue row absent from actual explore_search response');assert.equal(row.entity_type||row.type,'event');if(expectedID)assert.equal(row.id,expectedID);const link=page.locator('a[href*="'+slug+'"]').first();await link.click();await page.waitForURL(url=>url.pathname===canonical,{timeout:30000});await page.locator('#signature-room canvas').first().waitFor({timeout:45000});return{id:row.id,slug:row.slug,finalURL:page.url()};});
 results.checks.push({width,name:'page exceptions',pass:errors.length===0,errors});results.checks.push({width,name:'write guard',pass:true,blocked});await context.close();}
 }finally{await browser?.close();const output=process.env.QA_REPORT||'/tmp/toronto-catalogue-journey.json';await fs.writeFile(output,JSON.stringify(results,null,2));console.log('Report',output);if(results.checks.some(c=>!c.pass))process.exitCode=1;}})().catch(e=>{console.error(e);process.exitCode=1;});
