import {chromium} from 'playwright-core';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
import {renderRestaurantHome} from '../../../api/_restaurant-home.js';import {renderBakeryHome} from '../../../api/_bakery-home.js';import {renderHospitalityHome} from '../../../api/_hospitality-home.js';import {renderCreatorCanonicalHome} from '../../../api/_creator-home.js';import {renderMusicHome} from '../../../api/_music-home.js';import {renderChurchHome} from '../../../api/_church-home.js';import {renderEventCanonicalHome} from '../../../api/_event-home.js';import {CREATOR} from '../../../assets/homes/templates/creator/data.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),out=process.env.OUTPUT_DIR||'/tmp/listing-photo-gallery';await fs.mkdir(out,{recursive:true});
const defs=[['restaurant',renderRestaurantHome,'business','greek-restaurants','[data-gallery]'],['bakery',renderBakeryHome,'vendor','bakeries','[data-gallery]'],['hotel',renderHospitalityHome,'travel_place','hotels','[data-photo]'],['creator',renderCreatorCanonicalHome,'creator','creators','[data-photo]'],['artist',renderMusicHome,'artist','musicians','[data-gallery]'],['church',renderChurchHome,'church','orthodox-churches','[data-photo]'],['event',renderEventCanonicalHome,'venue','event-venues','[data-generic-photo]']];
const browser=await chromium.launch({executablePath:'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});let report=[];
try{for(const [family,render,type,category,selector] of defs)for(const width of [390,1440])for(const size of [0,1,3]){
 const images=Array.from({length:size},(_,i)=>'https://images.example/photo-'+i+'.jpg');const entity={id:'10000000-0000-4000-8000-000000000001',slug:'gallery-fixture',name:'Gallery fixture '+family,entity_type:type,category_slug:category,website:'https://official.example/',profile:{photos:images,photo_url:images[0]||null,hero_url:images[0]||null},...(family==='creator'&&size?{id:CREATOR.id,name:CREATOR.name,website:CREATOR.website}:{} )};const html=render(entity);assert.ok(html,family+' renderer');const p=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));let fail=size===3;
 await p.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin==='https://fixture.invalid'&&u.pathname==='/')return route.fulfill({contentType:'text/html',body:html});if(u.origin==='https://fixture.invalid'&&(u.pathname.startsWith('/assets/')||u.pathname.startsWith('/supabase/functions/'))){try{return route.fulfill({body:await fs.readFile(path.join(root,u.pathname)),contentType:u.pathname.endsWith('.css')?'text/css':u.pathname.endsWith('.png')?'image/png':'text/javascript'})}catch{return route.abort()}}if(route.request().resourceType()==='image'){if(fail)return route.abort();return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="700"><rect width="1000" height="700" fill="#164561"/><text x="60" y="340" fill="white" font-size="40">Controlled gallery image fixture</text></svg>'})}return route.abort()});
 await p.goto('https://fixture.invalid/');await p.waitForTimeout(350);const buttons=p.locator(selector);const count=await buttons.count();if(!size){assert.equal(count,0,family+' sparse controls');assert.equal(await p.locator('.zpg[open]').count(),0)}else{assert.ok(count>0,family+' photo controls');await buttons.first().click();await p.locator('.zpg[open]').waitFor();if(fail){await p.locator('[data-zpg-retry]').waitFor({state:'visible'});fail=false;await p.locator('[data-zpg-retry]').click();}await p.waitForFunction(()=>document.querySelector('.zpg-stage img')?.naturalWidth>0);const total=Number((await p.locator('[data-zpg-count]').textContent()).split('/')[1]);assert.ok(total>=1);if(total>1){await p.keyboard.press('ArrowRight');assert.equal(await p.locator('[data-zpg-count]').textContent(),'2 / '+total);await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('[data-zpg-count]').textContent(),'1 / '+total)}else assert.equal(await p.locator('[data-zpg-next]').isDisabled(),true);assert.equal(await p.locator('.zpg').evaluate(d=>d.scrollWidth>d.clientWidth),false);await p.waitForFunction(()=>document.querySelector('[data-zpg-status]')?.textContent==='');if(size===3)await p.screenshot({path:path.join(out,`${family}-${width}.png`)});await p.keyboard.press('Escape');assert.equal(await p.locator('.zpg[open]').count(),0);assert.equal(await buttons.first().evaluate(b=>document.activeElement===b),true)}assert.deepEqual(errors,[],family);report.push({family,width,size,count,passed:true});await p.close();}
}finally{await browser.close();await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2))}console.log('Passed '+report.length+' actual-renderer journeys');
