import test from 'node:test';import assert from 'node:assert/strict';
import{QA,qaUser,qaMe,withQaSession,permittedRequest}from'../../scripts/auth-qa/session.mjs';
const user={id:QA.user,email:'zoi-qa@example.invalid'};const me={authenticated:true,profile:{id:QA.profile},workspaces:[{id:QA.workspace,role:'owner'}]};
const listing='11111111-1111-4111-8111-111111111111';
function fixture({wrongUser=false,wrongWorkspace=false,owned=false}={}){const calls=[];const fetchImpl=async(url,options)=>{const path=new URL(url).pathname+new URL(url).search;const body=options.body?JSON.parse(options.body):null;calls.push({path,body,options});let result;
 if(path==='/auth/v1/admin/users/'+QA.user)result=wrongUser?{...user,id:'someone-else'}:user;
 else if(path==='/auth/v1/admin/generate_link')result={...user,hashed_token:'one-use-hash',verification_type:'magiclink'};
 else if(path==='/auth/v1/verify')result={user,access_token:'test-access',refresh_token:'test-refresh',expires_in:3600};
 else if(path==='/rest/v1/rpc/zoi_me')result=wrongWorkspace?{...me,workspaces:[]}:me;
 else if(path==='/rest/v1/rpc/bizpage_status')result={owned:owned?[{id:listing}]:[],claims:[]};
 else if(path==='/rest/v1/rpc/home_content_get')result={ok:true,workspace_id:QA.workspace,listing_id:listing,version:'a'.repeat(32)};
 else if(path==='/auth/v1/logout?scope=local')return new Response(null,{status:204});
 else throw Error('Unexpected request');return Response.json(result);};return{fetchImpl,calls};}
test('identity pins exact user plus QA address and profile/workspace owner membership',()=>{assert.equal(qaUser(user),user);assert.throws(()=>qaUser({...user,email:'actual-owner@example.invalid'}));assert.throws(()=>qaUser({...user,id:'other'}));assert.equal(qaMe(me),true);assert.throws(()=>qaMe({...me,profile:{id:QA.user}}));assert.throws(()=>qaMe({...me,workspaces:[{id:QA.workspace,role:'viewer'}]}));});
test('generates no email, verifies nonce, reads only QA scope and logs out locally',async()=>{const f=fixture({owned:true});const result=await withQaSession('sb_secret_test',async({session,listing:id})=>{assert.equal(session.access_token,'test-access');assert.equal(id,listing);return{passed:true};},f);assert.deepEqual(result,{passed:true});assert.deepEqual(f.calls.map(c=>c.path),['/auth/v1/admin/users/'+QA.user,'/auth/v1/admin/generate_link','/auth/v1/verify','/rest/v1/rpc/zoi_me','/rest/v1/rpc/bizpage_status','/rest/v1/rpc/home_content_get','/auth/v1/logout?scope=local']);assert.deepEqual(f.calls[1].body,{type:'magiclink',email:user.email});assert.deepEqual(f.calls[2].body,{type:'magiclink',token_hash:'one-use-hash'});assert.equal(f.calls[0].options.headers.Authorization,undefined);assert.equal(f.calls.at(-1).options.headers.Authorization,'Bearer test-access');});
test('wrong admin identity fails before generate; workspace and browser failures revoke local session',async()=>{let f=fixture({wrongUser:true});await assert.rejects(withQaSession('secret',()=>assert.fail(),f),/qa_identity_guard/);assert.equal(f.calls.length,1);f=fixture({wrongWorkspace:true});await assert.rejects(withQaSession('secret',()=>assert.fail(),f),/qa_workspace_guard/);assert.equal(f.calls.at(-1).path,'/auth/v1/logout?scope=local');f=fixture();await assert.rejects(withQaSession('secret',()=>{throw Error('browser failure');},f),/browser failure/);assert.equal(f.calls.at(-1).path,'/auth/v1/logout?scope=local');});
test('no owned QA listing is an explicit unexercised home journey',async()=>{const f=fixture();await withQaSession('secret',async x=>assert.equal(x.listing,null),f);assert.equal(f.calls.some(c=>c.path.includes('home_content_get')),false);});
test('browser guard denies writes, outside scopes, other hosts and arbitrary listing reads',()=>{const rpc=(fn,body)=>({url:QA.base+'/rest/v1/rpc/'+fn,method:'POST',postData:JSON.stringify(body)});assert.equal(permittedRequest(rpc('zoi_me',{}),listing),true);assert.equal(permittedRequest(rpc('home_content_get',{p_workspace:QA.workspace,p_listing:listing}),listing),true);for(const fn of['home_content_save','tickets_reserve_once','booking_create','social_save_post','zoi_create_workspace'])assert.equal(permittedRequest(rpc(fn,{p_workspace:QA.workspace}),listing),false);assert.equal(permittedRequest(rpc('home_content_get',{p_workspace:'other',p_listing:listing}),listing),false);assert.equal(permittedRequest(rpc('home_content_get',{p_workspace:QA.workspace,p_listing:'other'}),listing),false);assert.equal(permittedRequest({url:QA.base+'/auth/v1/otp',method:'POST',postData:'{}'},listing),false);assert.equal(permittedRequest({url:'https://other.example/assets/test',method:'GET'},listing),false);});

import{closeBrowser}from'../../scripts/auth-qa/browser.mjs';
test('browser cleanup failure prevents a successful result and hides process errors',async()=>{await closeBrowser(async args=>assert.deepEqual(args,['close']));await assert.rejects(closeBrowser(async()=>{throw Error('private process failure detail');}),error=>error.message==='qa_browser_cleanup_failed');});
