import test from'node:test';import assert from'node:assert/strict';import{churchSourceScope}from'../../supabase/functions/zoi-enrich/_scope.js';
const row={name:'Holy Trinity Parish',entity_type:'church',website:'https://example.org/'};
test('institution root title/meta rejects parish generic extraction across language variants',()=>{for(const branding of ['Greek Orthodox Archdiocese','Sacra Arcidiocesi Ortodossa Italia','Ιερά Μητρόπολις Αθηνών','Hellenic Orthodox Society']){const r=churchSourceScope(row,'<head><meta content="'+branding+'" property="og:description"></head>');assert.equal(r.handled,true);assert.equal(r.profile.blocked,'true');assert.equal(r.profile.scope_review_required,true);assert.equal(r.skipSupplementary,true);assert.equal(Object.hasOwn(r.profile,'phone'),false);}});
test('actual parish website with institution mentioned only in footer is not rejected',()=>{assert.equal(churchSourceScope(row,'<head><title>Holy Trinity Parish</title></head><h1>Holy Trinity</h1><footer>Part of the Greek Orthodox Archdiocese</footer>').handled,false);assert.equal(churchSourceScope({...row,entity_type:'organization'},'<h1>Archdiocese</h1>').handled,false);assert.equal(churchSourceScope({...row,name:'Greek Orthodox Archdiocese'},'<h1>Archdiocese</h1>').handled,false);});
test('known source is blocked before metadata extraction and after redirects to its homepage',()=>{assert.equal(churchSourceScope({...row,website:'http://www.ortodossia.it'}).handled,true);assert.equal(churchSourceScope(row,'','https://ortodossia.it/it/').handled,true);assert.equal(churchSourceScope(row,'<h1>Archdiocese</h1>','https://example.org/parishes/holy-trinity').handled,false);});

test('a matching parish title can mention its parent in the description without adopting its identity',()=>{assert.equal(churchSourceScope(row,'<head><title>Holy Trinity Parish</title><meta name="description" content="Part of the Orthodox Archdiocese"></head>').handled,false);assert.equal(churchSourceScope({...row,name:'Holy Trinity Parish of the Archdiocese'},'<head><title>Orthodox Archdiocese</title></head>').handled,true);});

test('complete parish primary heading accepts separated city/site suffixes',()=>{for(const title of ['Holy Trinity Parish | Toronto','Holy Trinity Parish|Toronto','Holy Trinity Parish – Toronto','Holy Trinity Parish — Official website','Holy Trinity Parish - Toronto','Holy Trinity Parish · Toronto']){const html='<head><title>'+title+'</title><meta name="description" content="Part of the Orthodox Archdiocese"></head>';assert.equal(churchSourceScope(row,html).handled,false,title);}assert.equal(churchSourceScope(row,'<head><title>Archdiocese</title></head><h1>Holy Trinity Parish | Toronto</h1>').handled,false);});
test('missing or different parish identity cannot bypass institution scope',()=>{for(const title of ['', 'St George Parish | Toronto','Holy Trinity Parishioners | Toronto','Holy Trinity | Toronto','Parish | Toronto','Archdiocese | Holy Trinity Parish','Holy Trinity Parish | St George Parish']){assert.equal(churchSourceScope(row,'<head><title>'+title+'</title><meta name="description" content="Part of the Orthodox Archdiocese"></head>').handled,true,title);}assert.equal(churchSourceScope({...row,website:'https://ortodossia.it'},'<head><title>Holy Trinity Parish | Toronto</title></head>').handled,true);});
