import test from 'node:test';import assert from 'node:assert/strict';import {churchHomeContent,renderChurchHome} from '../../api/_church-home.js';import {PARISH} from '../../assets/homes/templates/church/data.mjs';
const entity={id:PARISH.id,entity_type:'church',name:PARISH.fullName,slug:PARISH.slug,website:PARISH.site,city:'Washington',phone:'(202) 333-4730',address:PARISH.address};
test('canonical church defaults to real Concierge SSR and correct canonical route',()=>{const html=renderChurchHome(entity);assert.match(html,/<body data-template="concierge">/);assert.ok(html.includes('There is a place'));assert.ok(html.includes('https://www.zoi.city/church/'+PARISH.slug));assert.ok(html.includes('application/ld+json'));assert.ok(!html.includes('Design preview'));assert.match(html,/id="church-home-content"/);});
test('published design controls actual SSR template, order, visibility and escaped copy',()=>{const html=renderChurchHome(entity,{template:'parea',section_order:['contact','intro'],hidden_sections:['gallery'],copy:{headline:'My parish <welcome>'}});assert.match(html,/<body data-template="parea">/);assert.ok(html.indexOf('id="contact"')<html.indexOf('id="intro"'));assert.ok(!html.includes('id="gallery"'));assert.ok(html.includes('My parish &lt;welcome&gt;'));});
test('no identity, source or visibility mismatch receives Saint Sophia content',()=>{for(const delta of [{id:'00000000-0000-0000-0000-000000000000'},{entity_type:'business'},{marketplace_status:'hidden'},{publish_status:'draft'}])assert.equal(renderChurchHome({...entity,...delta}),null);});
test('hydration and schema cannot break out of JSON script tags',()=>{const html=renderChurchHome({...entity,name:'</script><script>alert(1)</script>'},{copy:{intro:'</script><img src=x onerror=alert(1)>'}});assert.ok(!html.includes('</script><script>alert'));assert.ok(html.includes('\\u003c/script\\u003e'));assert.equal(churchHomeContent(entity).phone,'+12023334730');});
test('canonical content omits private fields and honors safe owner-authored giving links',()=>{const html=renderChurchHome({...entity,profile:{private_client_notes:'never public',give_url:'https://bad.test'},access_token:'never exposed'});assert.ok(!html.includes('never public'));assert.ok(!html.includes('never exposed'));assert.ok(html.includes('https://bad.test/'));assert.ok(!renderChurchHome({...entity,profile:{give_url:'javascript:alert(1)'}}).includes('href="javascript:')); });

test('unmatched source church remains usable but never receives Sophia source material',()=>{for(const website of ['https://other-church.test','javascript:alert(1)']){const d=churchHomeContent({...entity,website});assert.equal(d.photos.length,0);assert.equal(d.ministries.length,0);assert.equal(d.giving,'');assert.ok(!renderChurchHome({...entity,website}).includes('saintsophiadc.org'));}});
