import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {inspectMedia,mediaMetadata,mediaDigest} from '../../assets/community/media-rules.mjs';
import {uploadCommunityMedia,validMediaAsset} from '../../assets/community/media-client.mjs';
const png=new Uint8Array(readFileSync(new URL('../../assets/icons/icon-512.png',import.meta.url)));
test('real PNG dimensions and content hash are read from bytes',async()=>{assert.deepEqual(inspectMedia(png,'image/png'),{type:'image',mime_type:'image/png',width:512,height:512,duration_seconds:null});assert.equal((await mediaDigest(png)).length,64);});
test('renamed HTML, unsupported types, oversized and avatar video rejected',()=>{assert.throws(()=>inspectMedia(new TextEncoder().encode('<html><script>alert(1)</script></html>'),'image/png'));assert.throws(()=>mediaMetadata('image/svg+xml',100),/unsupported/);assert.throws(()=>mediaMetadata('image/png',9000000),/size/);assert.throws(()=>mediaMetadata('video/mp4',100,'avatar'),/unsupported/);});
test('MP4 requires actual movie/video track rather than filename or ftyp magic only',()=>{const b=new Uint8Array(24);new DataView(b.buffer).setUint32(0,24);b.set(new TextEncoder().encode('ftypisom'),4);assert.throws(()=>inspectMedia(b,'video/mp4'));});
test('short binary headers never produce valid media metadata',()=>{for(let n=16;n<24;n++){let b=png.slice(0,n);assert.throws(()=>inspectMedia(b,'image/png'));}});
test('upload validates exact asset URL and preserves request metadata',async()=>{const id='12345678-1234-4123-8123-123456789012';let sent;const asset={id,type:'image',url:'https://csebihpaychdkanjjsmz.supabase.co/functions/v1/community-media?asset='+id,width:512,height:512};const result=await uploadCommunityMedia({base:'https://example.com',apikey:'public',token:'session',requestId:id,file:new File([png],'x.png',{type:'image/png'}),fetcher:async(u,o)=>{sent=o.body;return Response.json({ok:true,asset});}});assert.equal(result.id,id);assert.equal(sent.get('request_id'),id);assert.equal(sent.get('purpose'),'post');assert.equal(validMediaAsset({...asset,url:'https://evil.example/a.png'}),false);});

test('actual generated H264 MP4 parses and unsupported codec/long duration rejects',()=>{const b=new Uint8Array(readFileSync(new URL('../fixtures/community/codec-h264.mp4',import.meta.url)));assert.deepEqual(inspectMedia(b,'video/mp4'),{type:'video',mime_type:'video/mp4',width:64,height:48,duration_seconds:0.2});const bad=b.slice();let at=Buffer.from(b).indexOf('avc1',40);assert.ok(at>0);bad.set(new TextEncoder().encode('hvc1'),at);assert.throws(()=>inspectMedia(bad,'video/mp4'),/codec/);const long=b.slice(),mv=Buffer.from(b).indexOf('mvhd');new DataView(long.buffer).setUint32(mv+20,121000);assert.throws(()=>inspectMedia(long,'video/mp4'),/duration/);});
