import test from'node:test';import assert from'node:assert/strict';
import{ACTION_PLANS,actionPlanDraft,actionPlanContext,validateActionPlan,actionPlanArgs}from'../../assets/operations/company-action-plan-model.mjs';
import{createCompanyActionPlan}from'../../assets/operations/company-action-plan-controller.mjs';
import{createOperationsRecovery}from'../../assets/operations/recovery.mjs';
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),workspace=id(1),actor=id(99),company={id:id(2),workspace_id:workspace,version:1,title:'Olive Studios',kind:'company',status:'open',data:{}},member=id(98);
function fixture(){let current=true,role='owner',reads=0,writes=0,calls=0,nonce=1,marker=null,rows=[company],receipts={},loseAt=null,hold=null;const read=async()=>{reads++;if(hold)await hold;if(!current)throw Error('changed');return{ok:true,role,records:structuredClone(rows),members:[{profile_id:member,display_name:'Eleni'}]}};const recovery=createOperationsRecovery({actor,workspace,current:()=>current,nonce:()=>id(500+nonce++),storage:{load:async()=>marker,save:async m=>{marker=m},clear:async()=>{marker=null}},call:async(name,a)=>{if(name==='ops_request_status')return receipts[a.p_request]||{ok:true,state:a.p_cancel_if_missing?'cancelled':'missing',workspace_id:workspace,request_id:a.p_request};calls++;if(receipts[a.p_request])return receipts[a.p_request];writes++;const p=a.p_args,data=p.p_data,row={...data,id:id(100+writes),workspace_id:workspace,kind:p.p_kind,version:1,data:{notes:data.notes},company_id:company.id};rows.push(row);const receipt={ok:true,state:'saved',workspace_id:workspace,request_id:a.p_request,action:'save',record_id:row.id,kind:row.kind,version:1};receipts[a.p_request]=receipt;if(loseAt===writes)throw Error('lost');return receipt;}});let cleared=false;const controller=createCompanyActionPlan({workspace,companyId:company.id,current:()=>current,read,recovery,refused:()=>cleared=true});return{controller,recovery,init:()=>recovery.load(),read,state:()=>({rows,writes,calls,reads,marker,cleared}),lose:n=>loseAt=n,role:r=>role=r,account:()=>current=false,hold:p=>hold=p,alter:fn=>fn(rows)};}
test('all four templates produce editable ordinary project/task payloads, no legal dates or providers',()=>{const c=actionPlanContext({ok:true,role:'editor',records:[company],members:[{profile_id:member}]},workspace,company.id);for(const t of ACTION_PLANS){const d=validateActionPlan(actionPlanDraft(t.id),c);assert(d.tasks.every(x=>x.due_at===null));assert.equal(actionPlanArgs(d,company.id,null,0).p_kind,'project');assert.equal(actionPlanArgs(d,company.id,id(7),1).p_kind,'task');}});
test('validation rejects foreign contacts/member, excessive/empty actions, bad dates and cross-workspace responses',()=>{const c=actionPlanContext({ok:true,role:'owner',records:[company],members:[]},workspace,company.id);for(const alter of [d=>d.contact_id=id(999),d=>d.tasks[0].assignee_profile_id=member,d=>d.tasks=[],d=>d.tasks=Array(13).fill({title:'X'}),d=>d.tasks[0].due_at='not date',d=>d.tasks[0].title='']){const d=actionPlanDraft('records');alter(d);assert.throws(()=>validateActionPlan(d,c));}assert.throws(()=>actionPlanContext({ok:true,role:'owner',records:[{...company,workspace_id:id(88)}],members:[]},workspace,company.id));});
test('review has no mutation; save confirms five actual linked records with fresh authority per step',async()=>{const f=fixture();await f.init();await f.controller.prepare(actionPlanDraft('employee'));assert.equal(f.state().writes,0);await f.controller.advance();assert.equal(f.state().writes,5);assert(f.controller.state().complete);const tasks=f.state().rows.filter(r=>r.kind==='task');assert(tasks.every(t=>t.project_id===f.controller.state().projectId));assert(f.state().reads>=11);});
test('committed but lost project response checks receipt and resumes without duplicate',async()=>{const f=fixture();await f.init();await f.controller.prepare(actionPlanDraft('records'));f.lose(1);await assert.rejects(f.controller.advance(),/lost/);assert.equal(f.state().writes,1);assert(f.recovery.state().blocked);await f.controller.acceptRecovery(await f.recovery.recover('check'));await f.controller.advance();assert.equal(f.state().writes,5);assert.equal(f.state().calls,5);assert(f.controller.state().complete);});
test('committed but lost middle action retains preceding steps and resumes exact remaining work',async()=>{const f=fixture();await f.init();await f.controller.prepare(actionPlanDraft('contractor'));f.lose(3);await assert.rejects(f.controller.advance(),/lost/);assert.equal(f.controller.state().index,2);await f.controller.acceptRecovery(await f.recovery.recover('retry'));assert.equal(f.state().writes,3);await f.controller.advance();assert.equal(f.state().writes,5);assert.equal(new Set(f.state().rows.map(r=>r.id)).size,6);});
test('role downgrade before save clears private plan and emits zero writes',async()=>{const f=fixture();await f.init();await f.controller.prepare(actionPlanDraft('records'));f.role('viewer');await assert.rejects(f.controller.advance());assert(f.state().cleared);assert.equal(f.controller.state().plan,null);assert.equal(f.state().writes,0);});
test('account switch while fresh-read awaits discards private draft, publishes no response',async()=>{const f=fixture();await f.init();let release;f.hold(new Promise(r=>release=r));const pending=f.controller.prepare(actionPlanDraft('employee'));f.account();release();await assert.rejects(pending);assert.equal(f.state().writes,0);assert.equal(f.controller.state().plan,null);});
test('saved receipt followed by refresh failure never resends the already saved step',async()=>{const f=fixture();await f.init();await f.controller.prepare(actionPlanDraft('custom'));// Force the saved project to disappear from a fresh authorized snapshot.
 const c=f.controller;f.lose(1);await assert.rejects(c.advance());f.alter(rows=>rows.splice(1));await assert.rejects(c.acceptRecovery(await f.recovery.recover('check')),/could not be verified/);assert.equal(c.state().index,1);assert.equal(f.state().writes,1);await assert.rejects(c.advance(),/could not be verified/);assert.equal(f.state().writes,1);
});
test('nonce-only marker never contains plan titles, contact payloads or deadlines',async()=>{const f=fixture();await f.init();const d=actionPlanDraft('records');d.title='Private new hire';d.notes='Private notes';await f.controller.prepare(d);f.lose(1);await assert.rejects(f.controller.advance());const stored=JSON.stringify(f.state().marker);assert(!stored.includes('Private'));assert.deepEqual(Object.keys(f.state().marker).sort(),['actor','workspace','action','request'].sort());});
