import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import*as mod from'node:module';import vm from'node:vm';
const compile=file=>mod.stripTypeScriptTypes?.(readFileSync(new URL('../../supabase/functions/'+file,import.meta.url),'utf8').replace(/^import .*;$/gm,'').replace(/export /g,''));
const helper=compile('_shared/delivery-auth.ts');const id='00000000-0000-0000-0000-000000000001';
async function invoke(name,{enabled=true,authorized=true,token=true,receipt=true,margin=1,returnUrl='https://zoi.city/social'}={}){let handler;const calls=[];const sql=async(parts)=>{const q=parts.join(' ');calls.push(q);if(q.includes('SELECT 1'))return authorized?[{allowed:1}]:[];if(q.includes('from zoi.delivery_orders'))return[{id,listing_id:id,fees:{customer_fee:10,zoi_margin:margin,currency:'eur'},stripe_ref:null,stripe_account_id:'acct_test'}];if(q.includes('select stripe_account_id'))return[{stripe_account_id:'acct_test'}];if(q.includes('returning'))return receipt?[{id}]:[];throw Error(q);};sql.end=async()=>{};
 const fetch=async(url)=>{calls.push(url);if(url.endsWith('/auth/v1/user'))return token?Response.json({id}):Response.json({}, {status:401});if(url.endsWith('/payment_intents'))return Response.json({id:'pi_test',status:'requires_payment_method'});if(url.endsWith('/account_links'))return Response.json({url:'https://connect.stripe.com/setup/test',expires_at:1});throw Error(url);};
 const context={Response,Request,URL,URLSearchParams,AbortSignal,fetch,postgres:()=>sql,Deno:{env:{get:k=>({STRIPE_SECRET_KEY:'mock-only',DELIVERY_PAYMENTS_ENABLED:enabled?'on':'off',SUPABASE_URL:'https://db.test',SUPABASE_ANON_KEY:'anon',SUPABASE_DB_URL:'mock'})[k]},serve:f=>handler=f}};
 vm.runInNewContext(helper+'\n'+compile(name+'/index.ts'),context);const res=await handler(new Request('https://worker.test',{method:'POST',headers:{Authorization:'Bearer fixture'},body:JSON.stringify({order_id:id,listing_id:id,return_url:returnUrl,refresh_url:returnUrl})}));return{status:res.status,body:await res.json(),calls};}
for(const name of ['delivery-charge','delivery-connect-onboard']){
 test(name+' denies disabled, invalid-session and unauthorized calls before Stripe',{skip:!helper},async()=>{for(const opts of [{enabled:false},{token:false},{authorized:false}]){const r=await invoke(name,opts);assert.equal(r.body.ok,false);assert.ok(!r.calls.some(c=>c.includes('api.stripe.com')));}});
}
test('intent creation never claims payment completed and requires persisted receipt',{skip:!helper},async()=>{const r=await invoke('delivery-charge');assert.equal(r.body.payment_confirmed,false);assert.equal(r.body.payment_intent_status,'requires_payment_method');const failed=await invoke('delivery-charge',{receipt:false});assert.equal(failed.status,503);assert.equal(failed.body.ok,false);});
test('invalid fee split blocks Stripe and onboarding URLs cannot redirect externally',{skip:!helper},async()=>{const fee=await invoke('delivery-charge',{margin:20});assert.equal(fee.status,422);assert.ok(!fee.calls.some(c=>c.includes('api.stripe.com')));const onboarding=await invoke('delivery-connect-onboard',{returnUrl:'https://evil.test'});assert.equal(onboarding.status,400);assert.ok(!onboarding.calls.some(c=>c.includes('api.stripe.com')));});
