import test from 'node:test';import assert from 'node:assert/strict';
let handler;globalThis.Deno={env:{get:name=>({SUPABASE_URL:'https://unit.invalid',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'sb_secret_unit'})[name]},serve:fn=>handler=fn};
await import('../../supabase/functions/ops-documents/index.ts');
const originalFetch=globalThis.fetch;let calls=[];
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
function mock(){calls=[];globalThis.fetch=async(url,opts={})=>{const path=new URL(url).pathname;calls.push({path,opts});if(path==='/auth/v1/user')return json({id:'user'});if(path.endsWith('/document_download_authorize'))return json({ok:true,object_path:'ws/doc/version.pdf',filename:'Client file.pdf',expires_in:60});if(path.startsWith('/storage/v1/object/sign/'))return json({signedURL:'/object/sign/workspace-documents/ws/doc/version.pdf?token=short'});if(path.endsWith('/document_upload_begin'))return json({ok:true,document:{id:'doc'},upload:{id:'version',state:'pending',object_path:'ws/doc/version.pdf'}});if(path.endsWith('/document_upload_finish'))return json({ok:true,document:{id:'doc'},version:{id:'version',version:1,state:'ready'}});if(path==='/storage/v1/object/authenticated/workspace-documents/ws/doc/version.pdf')return new Response('%PDF-1.7\n',{headers:{'Content-Type':'application/pdf','Content-Length':'9'}});if(path==='/storage/v1/object/workspace-documents/ws/doc/version.pdf')return json({Key:'safe'});throw Error('unexpected_mock_request');};}
const headers={Authorization:'Bearer caller'};
test('download uses caller authorization, fixed60sec signing, attachment and no-store',async()=>{mock();try{const r=await handler(new Request('https://edge.invalid/?action=download',{method:'POST',headers,body:JSON.stringify({workspace:'ws',version_id:'version',expires_in:999999})}));const d=await r.json();assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal(d.expires_in,60);assert.equal(new URL(d.url).searchParams.get('download'),'Client file.pdf');const auth=calls.find(c=>c.path.endsWith('/document_download_authorize'));assert.equal(auth.opts.headers.Authorization,'Bearer caller');const sign=calls.find(c=>c.path.includes('/object/sign/'));assert.deepEqual(JSON.parse(sign.opts.body),{expiresIn:60});assert.equal(sign.opts.headers.Authorization,undefined);assert.equal(sign.opts.headers.apikey,'sb_secret_unit');}finally{globalThis.fetch=originalFetch;}});
test('upload calculates hash from bytes and stores immutable private object before finalizing',async()=>{mock();try{const form=new FormData();for(const [k,v] of Object.entries({workspace:'ws',project:'matter',document:'',expected_version:'0',title:'Client PDF',request_id:'stable'}))form.set(k,v);form.set('file',new File(['%PDF-1.7\n'],'file.pdf',{type:'application/pdf'}));const r=await handler(new Request('https://edge.invalid/?action=upload',{method:'POST',headers,body:form}));assert.equal(r.status,200);const begin=calls.find(c=>c.path.endsWith('/document_upload_begin'));assert.match(JSON.parse(begin.opts.body).p_sha256,/^[a-f0-9]{64}$/);assert.equal(JSON.parse(begin.opts.body).p_size,9);const upload=calls.find(c=>c.path==='/storage/v1/object/workspace-documents/ws/doc/version.pdf');assert.equal(upload.opts.headers['x-upsert'],'false');assert.equal(upload.opts.headers['Cache-Control'],'private, max-age=0, no-store');assert.equal(upload.opts.headers.Authorization,undefined);assert.equal(upload.opts.headers.apikey,'sb_secret_unit');assert.ok(calls.findIndex(c=>c.path.endsWith('/document_upload_finish'))>calls.indexOf(upload));}finally{globalThis.fetch=originalFetch;}});
test('fake PDF rejected before any metadata reservation or object upload',async()=>{mock();try{const form=new FormData();form.set('expected_version','0');form.set('file',new File(['<html>bad</html>'],'file.pdf',{type:'application/pdf'}));const r=await handler(new Request('https://edge.invalid/?action=upload',{method:'POST',headers,body:form}));assert.equal(r.status,409);assert.equal((await r.json()).error,'document_signature_mismatch');assert.deepEqual(calls.map(c=>c.path),['/auth/v1/user']);}finally{globalThis.fetch=originalFetch;}});
test('authenticated file proxy forces attachment, no-store and nosniff without issuing signed URL',async()=>{mock();try{const r=await handler(new Request('https://edge.invalid/?action=file',{method:'POST',headers,body:JSON.stringify({workspace:'ws',version_id:'version',path:'attacker-controlled'})}));assert.equal(r.status,200);assert.equal(await r.text(),'%PDF-1.7\n');assert.equal(r.headers.get('Cache-Control'),'private, no-store, max-age=0');assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');assert.match(r.headers.get('Content-Disposition'),/^attachment;/);assert.equal(calls.some(c=>c.path.includes('/object/sign/')),false);assert.equal(calls.at(-1).path,'/storage/v1/object/authenticated/workspace-documents/ws/doc/version.pdf');}finally{globalThis.fetch=originalFetch;}});
