import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';
// Reproduce pinned CLI2.115.0's source walker, not Deno's more permissive parser.
// https://github.com/supabase/cli/blob/v2.115.0/apps/cli/src/shared/functions/deploy.ts
const pattern=/(?:import|export)\s+(?:type\s+)?(?:{[^{}]+}|.*?)\s*(?:from)?\s*['"](.*?)['"]|import\(\s*['"](.*?)['"]\)/gi;
const root=path.resolve(new URL('../..',import.meta.url).pathname);
function graph(read=filename=>fs.readFileSync(path.join(root,filename),'utf8')){const queue=['supabase/functions/zoi-enrich/index.ts'],seen=new Set();while(queue.length){const current=queue.shift();if(seen.has(current))continue;seen.add(current);const text=read(current);for(const m of text.matchAll(new RegExp(pattern))){const raw=(m[1]??m[2]??'').trim();if(!raw.startsWith('./')&&!raw.startsWith('../'))continue;if(!raw.split('/').at(-1).includes('.'))continue;const next=path.posix.normalize(path.posix.join(path.posix.dirname(current),raw));assert(!next.startsWith('../'),'Import must stay inside repository');queue.push(next);}}return [...seen].sort();}
const expected=['supabase/functions/zoi-enrich/_phone.js','supabase/functions/zoi-enrich/_hospitality.js','supabase/functions/zoi-enrich/_document-quality.js','supabase/functions/zoi-enrich/index.ts','supabase/functions/zoi-enrich/_ssrf.ts','supabase/functions/zoi-enrich/_social.js','supabase/functions/zoi-enrich/_media.js','supabase/functions/zoi-enrich/_member.js','supabase/functions/zoi-enrich/_menus.js','supabase/functions/zoi-enrich/_images.js','supabase/functions/zoi-enrich/_image-context.js','supabase/functions/zoi-enrich/_scope.js','supabase/functions/zoi-enrich/_receipts.js','assets/enrichment/member-source.mjs','assets/enrichment/association-cards.mjs'].sort();
test('pinned API packaging reaches every worker and external shared source dependency',()=>{assert.deepEqual(graph(),expected);});
test('regression demonstrates compact import was skipped despite valid JavaScript',()=>{const files=graph(filename=>{const text=fs.readFileSync(path.join(root,filename),'utf8');return filename.endsWith('/_images.js')?text.replace("import { auxiliaryImage } from './_image-context.js';","import{auxiliaryImage}from'./_image-context.js';"):text;});assert.equal(files.includes('supabase/functions/zoi-enrich/_image-context.js'),false);assert.equal(files.includes('supabase/functions/zoi-enrich/_scope.js'),true);});
