import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
import {memberLeaseGuard} from '../../supabase/functions/zoi-enrich/_member.js';
import {confirmedEnrichmentReceipts,enrichmentSample} from '../../supabase/functions/zoi-enrich/_receipts.js';
const source=fs.readFileSync(new URL('../../supabase/functions/zoi-enrich/index.ts',import.meta.url),'utf8');
const memberURL='https://www.hellenicmedical.ca/profile/atzakis/';
const row={slug:'ageliki-tzakis',website:memberURL,lease_id:'lease',name:'Ageliki Tzakis',entity_type:'professional',existing_enrich:{member:{name:'Ageliki Tzakis',profession:'Registered Nurse'}}};
const doc='<h1>Ageliki (Angie) Tzakis, RN</h1><p>Associate</p><p>Profession: Registered Nurse</p><p>City: East York / Scarborough</p><footer>Practice Phone:9055812440</footer>';
async function run(item,got){let handler,batch,generic=0,supplements=0;const deps={Deno:{serve:fn=>handler=fn},authorised:()=>true,ENABLED:true,BATCH:1,enrichmentSample,memberLeaseGuard,confirmedEnrichmentReceipts,Response,Date,URL,dnsState:()=>true,vet:async url=>({url:new URL(url)}),robotsAllows:async()=>true,fetchDoc:async()=>got,sbRpc:async(fn,args)=>{if(fn.endsWith('_lease'))return[item];batch=args.p_batch;return batch.map(x=>({slug:x.slug,applied:true}))},extract:()=>{generic++;return{profile:{menu:[{section:'Actual generic extraction delegated'}]},provenance:{},aggregator:false}},supplementaryPages:()=>{supplements++;return[]},imageIdentity:x=>x};new Function(...Object.keys(deps),stripTypeScriptTypes(source.slice(source.indexOf('Deno.serve('))))(...Object.values(deps));const response=await handler(new Request('https://worker.test',{method:'POST',body:'{}'}));assert.equal(response.status,200);return{batch,generic,supplements,result:await response.json()}}
test('actual worker handler takes member branch before generic metadata and supplementary fetches',async()=>{const r=await run(row,{doc,finalUrl:memberURL});assert.equal(r.generic,0);assert.equal(r.supplements,0);assert.equal(r.batch[0].profile.member.profession,'Registered Nurse');assert.equal(r.batch[0].profile.phone,null);assert.deepEqual(r.batch[0].profile.social,{});assert.equal(r.result.stats['member-identity-matched'],1)});
test('challenge and HTTP refusal select database preservation branch',async()=>{for(const got of [{doc:'One moment, please. Request being verified.',finalUrl:memberURL},{error:'http403'}]){const r=await run(row,got);assert.equal(r.generic,0);assert.equal(r.supplements,0);assert.equal(r.batch[0].profile.crawl_status,'error');assert(!('member' in r.batch[0].profile));assert(!('photo_url' in r.batch[0].profile));assert.equal({...row.existing_enrich,...r.batch[0].profile}.member.profession,'Registered Nurse')}});
test('missing lease identity and redirect to unrelated organization fail closed',async()=>{for(const item of [{slug:'old-lease',website:memberURL,lease_id:'lease'},row]){const r=await run(item,{doc:'<h1>Association</h1><img src="banner.jpg">',finalUrl:'https://other-association.example/'});assert.equal(r.generic,0);assert.equal(r.supplements,0);assert.equal(r.batch[0].profile.crawl_status,'error')}});
test('known legal association roots protected but actual organization and ordinary practice proceed',async()=>{const protectedRow={...row,website:'https://hellenicbar.org/',name:'Real Person'};assert.equal((await run(protectedRow,{doc:'Association header',finalUrl:protectedRow.website})).generic,0);for(const item of [{...row,entity_type:'organization'}, {...row,website:'https://real-practice.example/'}]){const r=await run(item,{doc:'Real business',finalUrl:item.website});assert.equal(r.generic,1);assert.equal(r.supplements,1)}});
test('association subdomains and legacy HTTP sources cannot leak organization branding',()=>{for(const website of ['https://members.hellenicbar.org/','http://hcla.ca/']){const g=memberLeaseGuard({...row,website},'<h1>Organization</h1>',website);assert.equal(g.handled,true);assert.equal(g.skipSupplementary,true);assert.equal(g.profile.crawl_status,'error')}});
