import test from 'node:test';import assert from 'node:assert/strict';import handler from '../../api/entity.js';
const response=value=>new Response(JSON.stringify(value));
async function controlled(fn,run){const original=globalThis.fetch;const calls=[];globalThis.fetch=async(url,options)=>{const name=String(url).split('/').pop(),args=JSON.parse(options.body);calls.push({name,args,headers:options.headers});await new Promise(r=>setTimeout(r,5));return fn(name,args,calls);};try{return await run(calls);}finally{globalThis.fetch=original;}}
async function page(slug,headers={}){const result={headers:{},body:''};await handler({query:{slug},headers},{setHeader(k,v){result.headers[k]=v},end(body){result.status=this.statusCode;result.body=body}});return result;}
const record=slug=>({slug,name:'Public '+slug,entity_type:'business',profile:{}});
test('12 actual same-slug canonical requests share primary and optional public reads',()=>controlled((name,args)=>response(name==='home_entity'?record(args.p_slug):name==='seo_related'?[]:null),async calls=>{const pages=await Promise.all(Array.from({length:12},(_,i)=>page('burst-same',{authorization:'Bearer customer-'+i,cookie:'private='+i})));assert.equal(calls.length,3);assert.deepEqual(calls.map(x=>x.name),['home_entity','seo_related','listing_completeness']);assert.ok(pages.every(p=>p.status===200&&p.headers['Cache-Control']==='public, max-age=0, s-maxage=60'));assert.ok(calls.every(c=>c.headers.Authorization===calls[0].headers.Authorization&&!Object.keys(c.headers).some(k=>k.toLowerCase()==='cookie')));assert.doesNotMatch(calls[0].headers.Authorization,/customer/);}));
test('distinct slugs never share projection or optional scope',()=>controlled((name,args)=>response(name==='home_entity'?record(args.p_slug):null),async calls=>{const[a,b]=await Promise.all([page('scope-alpha'),page('scope-beta')]);assert.match(a.body,/Public scope-alpha/);assert.doesNotMatch(a.body,/Public scope-beta/);assert.match(b.body,/Public scope-beta/);assert.equal(calls.length,6);}));
test('a failed burst is evicted; later request observes success without error cache',()=>{let failed=true;return controlled((name,args)=>name==='home_entity'?(failed?new Response('unavailable',{status:503}):response(record(args.p_slug))):response(null),async calls=>{const pages=await Promise.all(Array.from({length:8},()=>page('failed-burst')));assert.equal(calls.length,1);assert.ok(pages.every(p=>p.status===503&&p.headers['Cache-Control']==='no-store'));failed=false;assert.equal((await page('failed-burst')).status,200);assert.equal(calls.filter(c=>c.name==='home_entity').length,2);});});
test('same burst shares one whole recovery sequence, not independent retries',()=>{let attempts=0;return controlled((name,args)=>name==='home_entity'&&++attempts===1?new Response('gateway',{status:502}):response(name==='home_entity'?record(args.p_slug):null),async calls=>{const pages=await Promise.all(Array.from({length:12},()=>page('recovery-burst')));assert.ok(pages.every(p=>p.status===200));assert.equal(calls.filter(c=>c.name==='home_entity').length,2);});});
test('next request immediately observes explicit owner clear and later not-found',()=>{let state='published';return controlled((name,args)=>response(name==='home_entity'?(state==='hidden'?null:{...record(args.p_slug),entity_type:'organization',website:'https://example.org',profile:{_enrich:{social:{youtube:'https://www.youtube.com/@source'}}},...(state==='cleared'?{owner_content:{social_links:{}}}:{})}):null),async()=>{const before=await page('owner-fresh');assert.match(before.body,/youtube.com/);state='cleared';const after=await page('owner-fresh');assert.doesNotMatch(after.body,/youtube.com/);state='hidden';assert.equal((await page('owner-fresh')).status,404);state='published';assert.equal((await page('owner-fresh')).status,200);});});
