import test from 'node:test';import assert from 'node:assert/strict';
import {eventOwnerSnapshot,eventAnnouncementPayload,createEventAnnouncementClient} from '../../assets/events/host-controls.mjs';
import {publicPublicity} from '../../assets/events/publicity.mjs';import {eventHomeContent} from '../../api/_event-home.js';import {renderGenericEvent} from '../../assets/homes/templates/events/generic.mjs';
const workspace='22222222-2222-4222-8222-222222222222',event='44444444-4444-4444-8444-444444444444',request='55555555-5555-4555-8555-555555555555';
const raw=()=>({ok:true,workspace_id:workspace,listing_id:event,version:'a'.repeat(32),base:{website:'https://official.example/show',description:'Existing source description'},entity_type:'event',profile:{tickets_url:'https://tickets.example/show',starts:'2027-03-26',lineup:['Original artist'],_enrich:{blocked_reason:'source_scope_mismatch'}}});
const snapshot=()=>eventOwnerSnapshot(raw(),workspace,event,{id:event,name:'Montréal – Ελληνική βραδιά',slug:'current-event'});
const publicity=()=>({event_url:snapshot().event_url,sales:{enabled:true,count:317,as_of:new Date(Date.now()-3600000).toISOString(),expires_at:new Date(Date.now()+3600000).toISOString(),source_url:'https://official.example/current-report',label:'Tickets sold'},highlights:[{id:'prior',title:'Owner highlight',url:'https://youtu.be/abcdefghijk'}],posts:[]});
function storage(){const s=new Map();return{getItem:k=>s.get(k)||null,setItem:(k,v)=>s.set(k,v),removeItem:k=>s.delete(k),s};}
test('event identity, editorial scope and scalar version must all match',()=>{assert.equal(snapshot().identity.name,'Montréal – Ελληνική βραδιά');for(const p of[{workspace_id:event},{listing_id:workspace},{entity_type:'business'},{version:'0'},{profile:null}])assert.throws(()=>eventOwnerSnapshot({...raw(),...p},workspace,event,{id:event,name:'Name',slug:'slug'}));assert.throws(()=>eventOwnerSnapshot(raw(),workspace,event,{id:workspace,name:'Other',slug:'other'}));});
test('narrow dated publicity patch preserves all source and booking fields; explicit removal',()=>{const s=snapshot(),before=structuredClone(s),payload=eventAnnouncementPayload(s,publicity(),request);assert.deepEqual(payload.p_base,{});assert.deepEqual(Object.keys(payload.p_profile),['event_publicity']);assert.equal(payload.p_profile.event_publicity.highlights[0].url,'https://www.youtube.com/watch?v=abcdefghijk');assert.deepEqual(s,before);assert.equal(eventAnnouncementPayload(s,null,request).p_profile.event_publicity,null);assert.throws(()=>eventAnnouncementPayload(s,{...publicity(),event_url:'https://www.zoi.city/event/different'},request));for(const count of[-1,2.5,Infinity])assert.throws(()=>eventAnnouncementPayload(s,{...publicity(),sales:{...publicity().sales,count}},request));});
test('uncertain save reloads exact immutable request and response; account isolates it',async()=>{const store=storage(),calls=[];let actor=event,fail=true;const call=async(fn,p)=>{calls.push(structuredClone(p));if(fail){fail=false;throw Error('response lost');}return{ok:true,workspace_id:workspace,listing_id:event,request_id:request,version:'b'.repeat(32)};};let c=createEventAnnouncementClient({call,getActor:()=>actor,workspace,event,storage:store});const p=eventAnnouncementPayload(snapshot(),publicity(),request);await assert.rejects(c.save(p));p.p_profile.event_publicity.sales.count=888;assert.equal(c.state().pending.p_profile.event_publicity.sales.count,317);c=createEventAnnouncementClient({call,getActor:()=>actor,workspace,event,storage:store});await assert.rejects(c.save(p));await c.retry();assert.deepEqual(calls[0],calls[1]);assert.equal(c.state().pending,null);fail=true;await assert.rejects(c.save(eventAnnouncementPayload(snapshot(),null,request)));actor=workspace;await assert.rejects(c.retry());c.sync();assert.equal(c.state().pending,null);assert.equal(calls.length,3);});
test('wrong receipt stays pending; refusal/CAS clears request; malformed reference blocks replacement',async()=>{for(const mode of['wrong','conflict','denied']){const store=storage();const c=createEventAnnouncementClient({getActor:()=>event,workspace,event,storage:store,call:async()=>{if(mode==='wrong')return{ok:true,workspace_id:workspace,listing_id:workspace,request_id:request,version:'b'.repeat(32)};throw Error(mode==='conflict'?'version_conflict':'not_authorized');}});await assert.rejects(c.save(eventAnnouncementPayload(snapshot(),publicity(),request)));assert.equal(!!c.state().pending,mode==='wrong');}const store=storage();store.setItem(`zoi.event-announcement:${event}:${workspace}:${event}`,'broken');let count=0;const c=createEventAnnouncementClient({getActor:()=>event,workspace,event,storage:store,call:async()=>{count++;}});assert(c.state().invalid);await assert.rejects(c.save(eventAnnouncementPayload(snapshot(),null,request)));assert.equal(count,0);});
test('adapter refuses broad patches and source inventory mutation before sending',async()=>{let count=0;const c=createEventAnnouncementClient({getActor:()=>event,workspace,event,storage:storage(),call:async()=>{count++;}});const p=eventAnnouncementPayload(snapshot(),publicity(),request);for(const changed of[{p_base:{website:'https://new.example/'}},{p_profile:{event_publicity:publicity(),starts:'wrong'}},{p_listing:workspace}])await assert.rejects(c.save({...p,...changed}));assert.equal(count,0);});
test('same public reader renders saved report, explicit clear, future/expired and wrong event for generic families',()=>{const raw={id:event,entity_type:'event',name:'Montréal – Ελληνική βραδιά',slug:'current-event',profile:{},owner_content:{profile:{event_publicity:publicity()}}};const rendered=()=>renderGenericEvent(eventHomeContent(raw),'concierge');assert.match(rendered(),/317 tickets sold/);raw.owner_content.profile.event_publicity=null;assert.doesNotMatch(rendered(),/317 tickets sold/);raw.owner_content.profile.event_publicity=publicity();raw.owner_content.profile.event_publicity.sales.expires_at=new Date(Date.now()-1).toISOString();assert.equal(publicPublicity(raw).sales,null);assert.match(rendered(),/Owner highlight/);assert.doesNotMatch(rendered(),/317 tickets sold/);raw.owner_content.profile.event_publicity=publicity();raw.slug="different";assert.doesNotMatch(rendered(),/317 tickets sold/);});
test('current-session authority refusals clear the exact pending request while transient transport keeps it',async()=>{for(const [status,message,clear]of[[400,'invitation_unavailable',true],[400,'suite_session_unavailable',true],[400,'bad_session',true],[400,'bad-session',true],[401,'JWT expired',true],[403,'Permission denied',true],[undefined,'Your session changed. Reload this view to check the result.',true],[503,'Service temporarily unavailable',false],[400,'Unexpected upstream response',false]]){const store=storage(),c=createEventAnnouncementClient({call:async()=>{throw Object.assign(Error(message),{status});},getActor:()=>event,workspace,event,storage:store});await assert.rejects(c.save(eventAnnouncementPayload(snapshot(),publicity(),request)));assert.equal(!!c.state().pending,!clear,message);assert.equal(store.s.size,clear?0:1,message);}});
