import test from 'node:test';
import assert from 'node:assert/strict';
import {confirmedEventArtists,artistPageMedia,artistPageMediaFromHTML,eventArtistMedia,eventArtistsHTML,mountEventArtists} from '../../assets/trips/event-artists.mjs';
const event='11111111-1111-4111-8111-111111111111',artist='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333';
const row={id,artist_id:artist,event_id:event,artist_name:'Artist <script>',entity_type:'artist',slug:'τραγούδι',city:'Athens',country:'Greece',starts_at:'2030-03-20T20:00:00Z',ends_at:'2030-03-21T00:00:00Z',timezone:'Europe/Athens',source_url:'https://artist.example/show'};
const result=rows=>({ok:true,event_id:event,confirmation:'event_and_artist_workspace',artists:rows});
const spotify='https://open.spotify.com/artist/152y903Cqyk9GVl6amOtuD';
test('only exact event, dual confirmation and safe future identity rows',()=>{const rows=confirmedEventArtists(result([row,{...row,id:'44444444-4444-4444-8444-444444444444',slug:'../bad'}]),event);assert.equal(rows.length,1);assert.equal(rows[0].url,'/artist/'+encodeURIComponent('τραγούδι'));assert.throws(()=>confirmedEventArtists({...result([]),confirmation:'source_announced'},event));assert.equal(confirmedEventArtists(result([{...row,timezone:'bad/time'}]),event).length,0);assert.equal(confirmedEventArtists(result([row]),event,Date.parse('2031-01-01')).length,0);});
test('current authoritative owner clear wins over reviewed artist defaults',()=>{const p={artist:{id:artist,name:'Artist',spotify}};assert.equal(artistPageMedia(p,null,artist).provider,'spotify');assert.equal(artistPageMedia(p,{listing:artist,authoritative:true,items:[]},artist),null);assert.equal(artistPageMedia(p,{listing:artist,authoritative:true,items:[{url:'https://www.instagram.com/artist'}]},artist),null);assert.throws(()=>artistPageMedia(p,{listing:event,authoritative:true,items:[]},artist));assert.throws(()=>artistPageMedia(p,null,event));});
test('owner supported selection validated, unsafe URL does not create player',()=>{const p={artist:{id:artist,name:'Artist',spotify}};assert.equal(artistPageMedia(p,{listing:artist,authoritative:true,items:[{url:'https://www.youtube.com/watch?v=Toth_4OkO5U',label:'Video'}]},artist).provider,'youtube');assert.equal(artistPageMedia({artist:{id:artist,spotify:'javascript:alert(1)'}},null,artist),null);assert.equal(eventArtistMedia(artist,{artist_id:event,reviewed:true}),null);});
test('render escapes author content and does not promise playback or insert iframe',()=>{const html=eventArtistsHTML(confirmedEventArtists(result([row]),event));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('Music'));assert.ok(!html.includes('<iframe'));assert.ok(!html.includes('▶ Listen'));});
test('hidden owner section never queries or renders',async()=>{let calls=0,clears=0;const api=mountEventArtists({replaceChildren(){clears++;}},{eventId:event,visible:false,core:{api:{rpc(){calls++;}}}});await api.refresh();api.destroy();assert.equal(calls,0);assert.equal(clears,1);});

test('JSON extraction does not parse image elements and honors hidden playback sections',()=>{const p={artist:{id:artist,spotify},design:{hidden_sections:['offerings','media']}};const html='<img src="https://tracking.example/pixel"><script type="application/json" id="music-home-content">'+JSON.stringify(p)+'</script>';assert.equal(artistPageMediaFromHTML(html,artist),null);assert.equal(artistPageMedia(p,{listing:artist,authoritative:true,items:[{url:spotify}]},artist),null);assert.throws(()=>artistPageMediaFromHTML(html+html,artist));});
