import test from 'node:test';import assert from 'node:assert/strict';
import {reservationActor,reservationMap,createEventReservationRpc} from '../../assets/tickets/event-reservations.mjs';
const actor='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',other='cccccccc-cccc-4ccc-8ccc-cccccccccccc',event='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',table='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const session=id=>({user_id:id,access_token:'header.'+btoa(JSON.stringify({sub:id}))+'.signature'});
const row={id:table,label:'Configured table',capacity:10,min_party_size:5,per_guest_cents:12500,currency:'CAD',pricing_version:1,fees_included:true,state:'available'};
test('identity is account UUID, never profile or inconsistent token identity',()=>{assert.equal(reservationActor(session(actor)),actor);assert.equal(reservationActor({...session(actor),user_id:other}),null);assert.equal(reservationActor({user_id:actor,access_token:'not-a-token'}),null);assert.equal(reservationActor(null),null);});
test('only exact event UUID inventory with explicit pricing and fee approval is renderable',()=>{const good={event_id:event,configured:true,tables:[row]};assert.equal(reservationMap(good,event),good);for(const delta of[{event_id:other},{tables:[{...row,id:'30'}]},{tables:[{...row,fees_included:false}]},{tables:[{...row,currency:null}]},{tables:[row,row]},{configured:false}])assert.throws(()=>reservationMap({...good,...delta},event));assert.equal(reservationMap({event_id:event,configured:false,tables:[]},event).configured,false);});
test('public read uses no account token and authenticated transport captures exact actor',async()=>{let s=session(actor);const calls=[],core={BASE:'https://example.test',KEY:'publishable',auth:{load:()=>s,ensureFresh:async()=>true}};const rpc=createEventReservationRpc(core,{fetchImpl:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({ok:true})};}});await rpc('table_inventory_map',{p_event:event},true);assert.equal(calls[0].options.headers.Authorization,'Bearer publishable');await rpc('table_hold_status',{p_event:event});assert.equal(calls[1].options.headers.Authorization,'Bearer '+s.access_token);assert.ok(calls[1].options.signal);await assert.rejects(rpc('unexpected',{}));});
test('account changes during refresh prevent writes, and after send suppress stale replies',async()=>{let s=session(actor),sent=0;const core={BASE:'https://example.test',KEY:'public',auth:{load:()=>s,ensureFresh:async()=>{s=session(other);}}};const rpc=createEventReservationRpc(core,{fetchImpl:async()=>{sent++;return {ok:true,json:async()=>({ok:true})};}});await assert.rejects(rpc('table_hold_create',{}),/account changed/);assert.equal(sent,0);s=session(actor);core.auth.ensureFresh=async()=>true;const after=createEventReservationRpc(core,{fetchImpl:async()=>({ok:true,json:async()=>{s=session(other);return {ok:true};}})});await assert.rejects(after('table_hold_create',{}),/account changed/);});
test('transport preserves only database error code needed for exact first-refusal handling',async()=>{const core={BASE:'https://example.test',KEY:'public',auth:{load:()=>session(actor),ensureFresh:async()=>true}};const rpc=createEventReservationRpc(core,{fetchImpl:async()=>({ok:false,status:400,json:async()=>({code:'P0001',message:'table_unavailable',details:'not exposed'})})});await assert.rejects(rpc('table_hold_create',{}),e=>e.status===400&&e.code==='P0001'&&e.message==='table_unavailable'&&!('details'in e));});

test('failed session refresh sends no private request and clears expired identity',async()=>{let s={...session(actor),expires_at:1},sent=0,cleared=0;const core={BASE:'https://example.test',KEY:'public',auth:{load:()=>s,ensureFresh:async()=>false,clear:()=>{cleared++;s=null;}}};const rpc=createEventReservationRpc(core,{fetchImpl:async()=>{sent++;}});await assert.rejects(rpc('table_hold_create',{}),e=>e.definitive===true);assert.equal(sent,0);assert.equal(cleared,1);});
