import test from 'node:test';import assert from 'node:assert/strict';
import{renderSalesMilestone,facebookTimelineURL,renderPublicityPosts}from'../../assets/events/publicity-view.mjs';
import{signatureHighlights}from'../../assets/events/signature-highlights.mjs';
const event='https://example.org/concert',sales={enabled:true,count:300,as_of:new Date(Date.now()-1000).toISOString(),expires_at:new Date(Date.now()+86400000).toISOString(),source_url:'https://example.org/announcement'};
test('milestones never transfer a count from a different event or expired report',()=>{assert.equal(renderSalesMilestone({event_url:event,sales},['https://example.org/festival']),'');assert.match(renderSalesMilestone({event_url:event,sales},[event]),/300 tickets sold/);assert.match(renderSalesMilestone({event_url:event,sales},[event]),/Organiser update/);assert.equal(renderSalesMilestone({event_url:event,sales:{...sales,expires_at:'2000-01-01T00:00:00Z'}},[event]),'');});
test('timeline embeds accept official page identity only and encode query input',()=>{assert.equal(facebookTimelineURL('https://facebook.com.evil.example/Signature'),'');assert.equal(facebookTimelineURL('https://user:pass@facebook.com/Signature'),'');assert.equal(facebookTimelineURL('https://facebook.com/plugins/page.php'),'');const u=new URL(facebookTimelineURL('https://www.facebook.com/SignatureProductionsToronto/'));assert.equal(u.hostname,'www.facebook.com');assert.equal(u.searchParams.get('tabs'),'timeline');});
test('curated posts escape content and unsafe links never render',()=>{assert.equal(renderPublicityPosts({posts:[{url:'javascript:alert(1)',title:'x'}]}),'');const h=renderPublicityPosts({posts:[{url:'https://example.org/p',title:'<script>x</script>',provider:'<img>'}]});assert.doesNotMatch(h,/<script>|<img>/);assert.match(h,/&lt;script&gt;/);});
test('owner photo clears and explicit publicity do not inherit official video fallback',()=>{assert.deepEqual(signatureHighlights({owner_gallery:true,signature_gallery:[]}),[]);const items=signatureHighlights({signature_gallery:[],publicity:{highlights:[{provider:'Facebook',url:'https://www.facebook.com/Page/videos/2405487242896499/',title:'Owner film'}]}});assert.equal(items.length,1);assert.equal(items[0].caption,'Owner film');});

test('future sales updates do not render before their report date',()=>{assert.equal(renderSalesMilestone({event_url:event,sales:{...sales,as_of:new Date(Date.now()+86400000).toISOString()}},[event]),'');});
