import test from'node:test';import assert from'node:assert/strict';import vm from'node:vm';import fs from'node:fs';
const html=fs.readFileSync(new URL('../../explore/app/index.html',import.meta.url),'utf8');
const source=html.slice(html.indexOf('var followed={},followAccount='),html.indexOf('/* the persisted profile id'))+html.slice(html.indexOf('function relationFor(t)'),html.indexOf('function relationLabel'))+html.slice(html.indexOf('function toggleFollow('),html.indexOf('/* When a profile id first appears'));
function fixture(){const storage=new Map(),calls=[],messages=[],callbacks={},auth={access_token:'test-token',user_id:'user-a',expires_at:Date.now()/1000+3600};storage.set('zoi_auth',JSON.stringify(auth));let reply=null,signin=0;
const ctx={auth,account:null,lang:'en',Date,JSON,Error,Promise,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},window:{addEventListener:(n,f)=>callbacks[n]=f},ZT:s=>messages.push(s),openAuth:()=>signin++,authRPC:async(n,args)=>{calls.push({n,args});if(reply)return reply(n,args);return n==='zoi_me'?{authenticated:true,profile:{id:'profile-a'}}:{ok:true,slug:args.p_slug,relation:args.p_relation};}};vm.createContext(ctx);vm.runInContext(source,ctx);return{ctx,calls,messages,storage,callbacks,get signin(){return signin;},reply:f=>reply=f,setActor:id=>storage.set('zoi_auth',JSON.stringify({...auth,user_id:id,access_token:'token-'+id}))};}
test('follow uses authenticated actual profile and only commits matching success; unfollow is generic',async()=>{const f=fixture(),updates=[];await f.ctx.toggleFollow('parish','church','Parish',x=>updates.push(x));assert.equal(f.calls[0].n,'zoi_me');assert.equal(f.calls[1].args.p_profile,'profile-a');assert.equal(f.calls[1].args.p_relation,'follow');assert.deepEqual(updates,[true]);assert.equal(f.ctx.followed.parish.confirmed,true);assert.equal(f.ctx.followVerb('church'),'Follow');await f.ctx.toggleFollow('parish','church','Parish',x=>updates.push(x));assert.equal(f.calls[3].n,'zoi_unfollow_place');assert.deepEqual(updates,[true,false]);});
test('refusal and unknown transport outcome never claim success or update confirmed cache',async()=>{for(const result of[null,{ok:false,error:'not_found'},{ok:true,slug:'foreign',relation:'follow'}]){const f=fixture();f.reply(async n=>n==='zoi_me'?{authenticated:true,profile:{id:'actual'}}:result);await f.ctx.toggleFollow('place','business','Name',()=>assert.fail('optimistic callback'));assert.equal(Object.keys(f.ctx.followed).length,0);assert.match(f.messages.at(-1),/Could not confirm/);}});
test('account switch discards stale successful response and never imports global optimistic follows',async()=>{const f=fixture();f.storage.set('zoi_followed',JSON.stringify({bad:{relation:'my_church'}}));let complete;f.reply(n=>n==='zoi_me'?{authenticated:true,profile:{id:'actual'}}:new Promise(r=>complete=r));const pending=f.ctx.toggleFollow('place','business','Name',()=>assert.fail('stale callback'));await new Promise(r=>setImmediate(r));f.setActor('user-b');f.callbacks.storage({key:'zoi_auth'});complete({ok:true,slug:'place',relation:'follow'});await pending;assert.equal(f.ctx.followAccount,'user-b');assert.equal(Object.keys(f.ctx.followed).length,0);assert.equal(f.storage.has('zoi_followed:user-b'),false);});
test('signed-out action requires sign-in without a write or local success',async()=>{const f=fixture();f.storage.delete('zoi_auth');await f.ctx.toggleFollow('place','church','Name');assert.equal(f.signin,1);assert.equal(f.calls.length,0);assert.equal(Object.keys(f.ctx.followed).length,0);});
test('review read sends exact RPC parameter and all inline scripts remain syntactically valid',()=>{assert.match(html,/sbRPC\('zoi_listing_reviews',\{p_slug:ent.slug\}\)/);for(const script of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){if(script[1].trim())new vm.Script(script[1]);}});

test('event follow labels do not claim attendance or fabricate local going state',()=>{const card=html.slice(html.indexOf('function eventCardEl('),html.indexOf('function scrEvents'));assert.match(card,/followedVerb\('event'\)/);assert.doesNotMatch(card,/zoi_going_|I’m going|See you there/);assert.match(card,/btn.disabled=true/);});

test('account change immediately repaints connected controls and prunes detached views',async()=>{const f=fixture(),button={isConnected:true,textContent:''},removed={isConnected:false};f.ctx.bindFollowControl(button,()=>button.textContent=f.ctx.followed.place?'Following':'Follow');let removedPaints=0;f.ctx.bindFollowControl(removed,()=>removedPaints++);await f.ctx.toggleFollow('place','church','Name');assert.equal(button.textContent,'Following');const before=removedPaints;f.setActor('user-b');f.callbacks.storage({key:'zoi_auth'});assert.equal(button.textContent,'Follow');assert.equal(removedPaints,before);assert.equal(f.ctx.followControls.length,1);});
