import test from'node:test';import assert from'node:assert/strict';import{createParishSearch,parishPath}from'../../assets/faith/parish-search.mjs';
const id='e3676dad-957e-42b4-9881-65453e2856aa';
function setup(){let job=null;const calls=[],states=[],pending=[];const search=createParishSearch({rpc:p=>{calls.push(p);return new Promise((resolve,reject)=>pending.push({resolve,reject}));},onState:s=>states.push(s),setTimer:f=>(job=f,1),clearTimer:()=>job=null});return{search,calls,states,pending,fire:()=>{const f=job;job=null;f?.();},flush:()=>new Promise(r=>setImmediate(r))};}
test('suggestions require three letters and debounce qualifier changes into one bounded call',async()=>{const t=setup();for(const name of ['St','---','123']){t.search.update({name});t.fire();}assert.equal(t.calls.length,0);t.search.update({name:'St George'});t.search.update({name:'St George',city:'Toronto',country:'Canada'});t.fire();assert.equal(t.calls.length,1);assert.deepEqual(t.calls[0],{p_q:'St George',p_type:'church',p_city:'Toronto',p_country:'Canada',p_limit:8,p_offset:0});t.pending[0].resolve([{id,name:'St George',city:'Toronto'}]);await t.flush();assert.equal(t.states.at(-1).state,'ready');});
test('clearing input and changing qualifiers fence late successful and failed responses',async()=>{const t=setup();t.search.update({name:'Saint George'});t.fire();t.search.update({name:''});t.pending[0].resolve([{id}]);await t.flush();assert.equal(t.states.at(-1).state,'idle');t.search.update({name:'Saint Nicholas'});t.fire();t.search.update({name:'Saint Nicholas',city:'Toronto'});t.fire();t.pending[2].resolve([{id}]);await t.flush();t.pending[1].reject(Error('old failure'));await t.flush();assert.equal(t.states.at(-1).state,'ready');assert.equal(t.states.at(-1).rows.length,1);});
test('IME never requests unfinished text; explicit city search remains available',async()=>{const t=setup();t.search.composition(true);t.search.update({name:'Αγιος'});t.fire();await t.search.submit();assert.equal(t.calls.length,0);t.search.composition(false);t.search.update({name:'Άγιος'});t.fire();assert.equal(t.calls.length,1);t.search.update({name:'',city:'Toronto'});t.fire();assert.equal(t.calls.length,1);void t.search.submit();assert.equal(t.calls.length,2);});
test('invalid receipts show errors and results stay capped with valid identifiers',async()=>{const t=setup();t.search.update({name:'Saint'});t.fire();t.pending[0].resolve({ok:true});await t.flush();assert.equal(t.states.at(-1).state,'error');t.search.update({name:'Saint'});t.fire();t.pending[1].resolve([{id:'bad'},...Array.from({length:20},()=>({id}))]);await t.flush();assert.equal(t.states.at(-1).rows.length,8);});

test('parish paths preserve current Unicode identity and reject traversal or external URLs',()=>{
 const slug='άγιος-γεώργιος-αθήνα';assert.equal(parishPath({slug,path:'/church/stale'}),'/church/'+encodeURIComponent(slug));assert.equal(parishPath({canonical_slug:slug,slug:'old'}),'/church/'+encodeURIComponent(slug));assert.equal(parishPath({path:'/church/'+encodeURIComponent(slug)}),'/church/'+encodeURIComponent(slug));assert.equal(parishPath({slug:'α\u0301γιος'}),'/church/'+encodeURIComponent('α\u0301γιος'));
 for(const bad of ['../secret','a/b','a\\b','a?x=1','a#x','javascript:alert(1)','%2fsecret','%252fsecret','a\n','https://evil.test']){assert.equal(parishPath({slug:bad}),'',bad);assert.equal(parishPath({path:'/church/'+bad}),'',bad);}
 assert.equal(parishPath({path:'https://evil.test/church/good'}),'');assert.equal(parishPath({path:'/church/%E0%A4%A'}),'');
});
