import test from 'node:test';import assert from 'node:assert/strict';import{furnishedPositions}from'../../assets/events/signature/furnished-concert.mjs';import{TABLES}from'../../assets/events/signature/venue-experience.mjs';
test('all118 source identities retained; only known sponsor footprints furnished',()=>{const a=furnishedPositions(TABLES);assert.equal(a.length,118);assert.deepEqual(a.map(r=>r.id),TABLES.map(r=>r.id));assert.ok(a.some(r=>r.furnished));for(const r of a){assert.equal(r.furnished,r.tier==='magenta');assert.ok([r.cx,r.cz,r.width,r.depth].every(Number.isFinite));const t=TABLES.find(t=>t.id===r.id);assert.ok(Math.abs(r.cz-(41.1875-(t.ny+t.nh/2)*82.375)*.3)<1e-9);}});
test('invalid or duplicate source geometry fails before scene',()=>{assert.throws(()=>furnishedPositions([TABLES[0],TABLES[0]]));assert.throws(()=>furnishedPositions([{...TABLES[0],nw:NaN}]));});
import{tableViewCamera}from'../../assets/events/signature/furnished-concert.mjs';
test('table view uses selected source location facing actual source stage',()=>{for(const r of furnishedPositions(TABLES)){const c=tableViewCamera(r);assert.equal(c.position.x,r.cx);assert.ok(c.position.z>r.cz);assert.equal(c.lookAt.z,-10.88);assert.equal(c.lookAt.x,-1.35);}assert.throws(()=>tableViewCamera({cx:0,cz:NaN,depth:1}));});
import{loungeConfiguration}from'../../assets/events/signature/lounge-scene.mjs';
test('couches never face away from stage: front side-on, U opening toward stage',()=>{for(const kind of ['front','side'])for(const couch of loungeConfiguration(kind)){const forwardZ=Math.cos(couch.angle);assert.ok(-forwardZ>=-1e-10);}const front=loungeConfiguration('front');assert.ok(front.every(x=>x.z===0));const side=loungeConfiguration('side');assert.ok(side.some(x=>x.z===2.7&&x.angle===Math.PI));assert.ok(!side.some(x=>x.z===-2.7));});
import{boothAssembly}from'../../assets/events/signature/furnished-concert.mjs';
test('rendered sponsor assembly stays within exact source footprint after90degree rotation',()=>{for(const r of furnishedPositions(TABLES).filter(r=>r.furnished)){const a=boothAssembly(r);assert.equal(a.rotation,Math.PI/2);assert.ok(a.bounds.width<=r.width);assert.ok(a.bounds.depth<=r.depth);assert.ok(a.length>a.cross*.5);for(const facing of a.seatFacing){assert.equal(facing.z,0);assert.ok(Math.abs(facing.x)===1);}}});
test('only confirmed side boothIDs1and23 useU; front17 stays side-onpair',()=>{const rows=furnishedPositions(TABLES);for(const r of rows.filter(r=>r.furnished))assert.equal(boothAssembly(r).kind,['1','23'].includes(r.id)?'side-u':'paired');});
import {roomFurnishings,cameraLimits} from '../../assets/events/signature/furnished-concert.mjs';
test('side lounges span illustrated stage depth and preserve original source position separately',()=>{const original=furnishedPositions(TABLES),rows=roomFurnishings(original);for(const id of ['1','23']){const a=rows.find(r=>r.id===id),b=original.find(r=>r.id===id);assert.ok(a.depth>b.depth*2);assert.equal(a.sourcePosition.cz,b.cz);assert.equal(a.cz-a.depth/2,-11.73);assert.equal(a.sideOpening,id==='1'?-1:1);}assert.equal(rows.find(r=>r.id==='17').cz,original.find(r=>r.id==='17').cz);});
test('camera cannot orbit behind stage or below floor',()=>{assert.deepEqual(cameraLimits(100,100),{theta:1.15,phi:1.22});assert.deepEqual(cameraLimits(-100,-100),{theta:-1.15,phi:.12});});

import {standardChairPositions} from '../../assets/events/signature/furnished-concert.mjs';
test('standard seating is visible on both long sides and never replaces VIP couches',()=>{for(const row of furnishedPositions(TABLES)){const chairs=standardChairPositions(row);if(row.furnished){assert.deepEqual(chairs,[]);continue;}assert.equal(chairs.length,10);assert.equal(chairs.filter(c=>c.side===1).length,5);assert.ok(chairs.every(c=>Number.isFinite(c.x)&&Number.isFinite(c.z)&&c.seatDepth>0&&Math.abs(c.z)<row.depth/2));}});
import {initialRoomView} from '../../assets/events/signature/furnished-concert.mjs';
test('phone starts at a readable stage-facing lounge view and desktop retains whole-room overview',()=>{const mobile=initialRoomView(390),desktop=initialRoomView(1440);assert.deepEqual(mobile.target,{x:-1.35,z:-6});assert.equal(mobile.distance,9);assert.deepEqual(desktop.target,{x:0,z:0});assert.equal(desktop.distance,25);assert.ok(mobile.phi>.12&&mobile.phi<1.22);});

import {selectionRoomView,cameraBlend} from '../../assets/events/signature/furnished-concert.mjs';
test('selection framing retains stage backdrop and exact table in portrait and landscape',()=>{for(const aspect of [.55,1.8])for(const row of roomFurnishings(furnishedPositions(TABLES))){const v=selectionRoomView(row,aspect),d=v.distance*Math.max(1,1.35/aspect),tan=Math.tan(42*Math.PI/360);for(const[x,y,z]of [[-6.5,4.2,-12],[3.8,4.2,-12],[row.cx,1,row.cz]]){const dx=x-v.target.x,dz=z-v.target.z,depth=d-y*Math.cos(v.phi)-dz*Math.sin(v.phi);assert.ok(depth>0);assert.ok(Math.abs(dx)/(depth*tan*aspect)<.9);assert.ok(Math.abs(y*Math.sin(v.phi)-dz*Math.cos(v.phi))/(depth*tan)<.9);}}});
test('camera easing is time-based and bounds resumed-frame motion',()=>{const a=cameraBlend(16);assert.ok(a>0&&a<1);assert.ok(Math.abs((1-a)**2-(1-cameraBlend(32)))<1e-10);assert.equal(cameraBlend(1000),cameraBlend(64));assert.equal(cameraBlend(-5),0);});

import {publishedCategory} from '../../assets/events/signature/furnished-concert.mjs';
test('all 118 room surfaces retain published category colours and per-guest prices',()=>{const expected={red:['#f21827',100,8],blue:['#22a9d7',125,26],white:['#ffffff',150,32],green:['#8cc53e',175,20],yellow:['#ffeb28',200,14],magenta:['#ef0094',275,18]},counts={};for(const r of roomFurnishings(furnishedPositions(TABLES))){const [color,price]=expected[r.tier];assert.deepEqual(publishedCategory(r.tier),{color,price});counts[r.tier]=(counts[r.tier]||0)+1;}for(const [tier,[,,count]]of Object.entries(expected))assert.equal(counts[tier],count);assert.throws(()=>publishedCategory('available'));});

import {mobileStageShift} from '../../assets/events/signature/furnished-concert.mjs';
test('mobile fullscreen stage fits below controls without altering desktop or table sightlines',()=>{const frame={width:390,height:780,fullscreen:true,tableView:false,stageTop:218,controlsBottom:139,canvasTop:64};assert.equal(mobileStageShift(frame),123);assert.equal(frame.stageTop-mobileStageShift(frame)+frame.canvasTop,159);assert.equal(mobileStageShift({...frame,width:1440}),0);assert.equal(mobileStageShift({...frame,tableView:true}),0);assert.equal(mobileStageShift({...frame,fullscreen:false}),0);assert.equal(mobileStageShift({...frame,stageTop:30}),0);assert.equal(mobileStageShift({...frame,stageTop:1000}),234);assert.equal(mobileStageShift({...frame,stageTop:NaN}),0);});
import {validatedPreviewPlacement} from '../../assets/events/signature/furnished-concert.mjs';
import {TORONTO_PREVIEW_BUSINESSES} from '../../assets/events/signature/sponsor-preview-model.mjs';
test('test placement only accepts source tables and reviewed matching businesses',()=>{const ids=TABLES.map(r=>r.id),business=TORONTO_PREVIEW_BUSINESSES[0];assert.deepEqual(validatedPreviewPlacement({tableId:'17',business},ids),{tableId:'17',business});assert.equal(validatedPreviewPlacement(null,ids),null);for(const value of [{tableId:'999',business},{tableId:'17',business:{...business,image:'https://evil.test/image.png'}},{tableId:'17',business:{...business,url:'javascript:alert(1)'}},{tableId:'17',business:{...business,name:'Pretend sponsor'}}])assert.throws(()=>validatedPreviewPlacement(value,ids));});

import{placementRoomView}from'../../assets/events/signature/furnished-concert.mjs';
test('preview camera keeps phone branding readable and desktop placement in room context',()=>{assert.deepEqual(placementRoomView(390),{distance:3.5,phi:.7});assert.deepEqual(placementRoomView(1440),{distance:5.8,phi:.7});assert.ok(placementRoomView(1440).distance>placementRoomView(390).distance);});
