import test from 'node:test';import assert from 'node:assert/strict';import{furnishedPositions}from'../../assets/events/signature/furnished-concert.mjs';import{TABLES}from'../../assets/events/signature/venue-experience.mjs';
test('all118 source identities retained; only known sponsor footprints furnished',()=>{const a=furnishedPositions(TABLES);assert.equal(a.length,118);assert.deepEqual(a.map(r=>r.id),TABLES.map(r=>r.id));assert.ok(a.some(r=>r.furnished));for(const r of a){assert.equal(r.furnished,r.tier==='magenta');assert.ok([r.cx,r.cz,r.width,r.depth].every(Number.isFinite));const t=TABLES.find(t=>t.id===r.id);assert.ok(Math.abs(r.cz-(41.1875-(t.ny+t.nh/2)*82.375)*.3)<1e-9);}});
test('invalid or duplicate source geometry fails before scene',()=>{assert.throws(()=>furnishedPositions([TABLES[0],TABLES[0]]));assert.throws(()=>furnishedPositions([{...TABLES[0],nw:NaN}]));});
import{tableViewCamera}from'../../assets/events/signature/furnished-concert.mjs';
test('table view uses selected source location facing actual source stage',()=>{for(const r of furnishedPositions(TABLES)){const c=tableViewCamera(r);assert.equal(c.position.x,r.cx);assert.ok(c.position.z>r.cz);assert.equal(c.lookAt.z,-10.88);assert.equal(c.lookAt.x,-1.35);}assert.throws(()=>tableViewCamera({cx:0,cz:NaN,depth:1}));});
import{loungeConfiguration}from'../../assets/events/signature/lounge-scene.mjs';
test('couches never face away from stage: front side-on, U opening toward stage',()=>{for(const kind of ['front','side'])for(const couch of loungeConfiguration(kind)){const forwardZ=Math.cos(couch.angle);assert.ok(-forwardZ>=-1e-10);}const front=loungeConfiguration('front');assert.ok(front.every(x=>x.z===0));const side=loungeConfiguration('side');assert.ok(side.some(x=>x.z===2.7&&x.angle===Math.PI));assert.ok(!side.some(x=>x.z===-2.7));});
import{boothAssembly}from'../../assets/events/signature/furnished-concert.mjs';
test('rendered sponsor assembly stays within exact source footprint after90degree rotation',()=>{for(const r of furnishedPositions(TABLES).filter(r=>r.furnished)){const a=boothAssembly(r);assert.equal(a.rotation,Math.PI/2);assert.ok(a.bounds.width<=r.width);assert.ok(a.bounds.depth<=r.depth);assert.ok(a.length>a.cross*.5);for(const facing of a.seatFacing){assert.equal(facing.z,0);assert.ok(Math.abs(facing.x)===1);}}});
test('only confirmed side boothIDs1and23 useU; front17 stays side-onpair',()=>{const rows=furnishedPositions(TABLES);for(const r of rows.filter(r=>r.furnished))assert.equal(boothAssembly(r).kind,['1','23'].includes(r.id)?'side-u':'paired');});
import {roomFurnishings,cameraLimits} from '../../assets/events/signature/furnished-concert.mjs';
test('side lounges span illustrated stage depth and preserve original source position separately',()=>{const original=furnishedPositions(TABLES),rows=roomFurnishings(original);for(const id of ['1','23']){const a=rows.find(r=>r.id===id),b=original.find(r=>r.id===id);assert.ok(a.depth>b.depth*2);assert.equal(a.sourcePosition.cz,b.cz);assert.equal(a.cz-a.depth/2,-11.73);assert.equal(a.sideOpening,id==='1'?-1:1);}assert.equal(rows.find(r=>r.id==='17').cz,original.find(r=>r.id==='17').cz);});
test('camera cannot orbit behind stage or below floor',()=>{assert.deepEqual(cameraLimits(100,100),{theta:1.15,phi:1.22});assert.deepEqual(cameraLimits(-100,-100),{theta:-1.15,phi:.12});});

import {standardChairPositions} from '../../assets/events/signature/furnished-concert.mjs';
test('standard seating is visible on both long sides and never replaces VIP couches',()=>{for(const row of furnishedPositions(TABLES)){const chairs=standardChairPositions(row);if(row.furnished){assert.deepEqual(chairs,[]);continue;}assert.equal(chairs.length,10);assert.equal(chairs.filter(c=>c.side===1).length,5);assert.ok(chairs.every(c=>Number.isFinite(c.x)&&Number.isFinite(c.z)&&c.seatDepth>0&&Math.abs(c.z)<row.depth/2));}});
import {initialRoomView} from '../../assets/events/signature/furnished-concert.mjs';
test('phone starts at a readable stage-facing lounge view and desktop retains whole-room overview',()=>{const mobile=initialRoomView(390),desktop=initialRoomView(1440);assert.deepEqual(mobile.target,{x:-1.35,z:-6});assert.equal(mobile.distance,9);assert.deepEqual(desktop.target,{x:0,z:0});assert.equal(desktop.distance,25);assert.ok(mobile.phi>.12&&mobile.phi<1.22);});
