import test from'node:test';import assert from'node:assert/strict';import{createGeneralReservations,validateGeneralRecovery}from'../../assets/tickets/general-reservation.js';
const event='11111111-1111-4111-8111-111111111111',nonce='22222222-2222-4222-8222-222222222222';
function fixture(){const memory=new Map(),calls=[];let actor='guest',result=null;const storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};const service=createGeneralReservations({storage,identity:()=>({actor,token:actor+'-token'}),random:()=>nonce,now:()=>new Date(0).toISOString(),locks:null,call:async(fn,args,token)=>{calls.push({fn,args,token});if(fn==='tickets_reserve_once'){result={ok:true,code:'REAL',qty:args.p_qty,amount_cents:0,currency:'EUR',paid:false,request_id:args.p_request,event_id:args.p_event,ticket_type_id:args.p_type};return result;}return result?{ok:true,found:true,receipt:result,current_status:'cancelled',checked_in:false,event_available:false}:{ok:true,found:false};}});return{service,storage,calls,memory,setActor:v=>actor=v};}
test('saved request precedes mutation, has no contact PII and recovers current cancellation after immutable reply',async()=>{const f=fixture(),a=await f.service.prepare(event,'19',2);assert.equal(f.calls.length,0);assert.equal(a.id,nonce);assert.equal(f.memory.size,1);assert.doesNotMatch([...f.memory.values()][0],/email|name/);const r=await f.service.submit(a,' Guest ',' guest@example.com ');assert.equal(r.status,'cancelled');assert.equal(r.eventAvailable,false);assert.deepEqual(f.calls.map(x=>x.fn),['tickets_reserve_once','tickets_reserve_receipt']);assert.equal(f.calls[0].args.p_request,f.calls[1].args.p_request);f.service.complete(a,r);assert.equal(f.service.read(event),null);});
test('missing receipt does not clear nonce or permit replacement tier/quantity',async()=>{const f=fixture(),a=await f.service.prepare(event,'19',2);assert.equal(await f.service.recover(a),null);assert.equal((await f.service.prepare(event,'19',2)).id,a.id);await assert.rejects(f.service.prepare(event,'20',2));await assert.rejects(f.service.prepare(event,'19',3));assert.equal(f.service.read(event).id,nonce);});
test('scope changes and legacy latches fail closed without rebinding or request',async()=>{const f=fixture(),a=await f.service.prepare(event,'19',2);f.setActor('other-account');await assert.rejects(f.service.submit(a,'Guest','guest@example.com'));assert.equal(f.calls.length,0);f.setActor('guest');const k=[...f.memory.keys()][0];const legacy={...a};delete legacy.protocol;delete legacy.qty;f.storage.setItem(k,JSON.stringify(legacy));await assert.rejects(f.service.prepare(event,'19',2));await assert.rejects(f.service.recover(legacy));assert.equal(f.calls.length,0);});
test('mismatched receipt/current state cannot clear warning and storage denial prevents mutation',async()=>{const f=fixture(),a=await f.service.prepare(event,'19',2);for(const x of[{}, {ok:true,found:true,receipt:{}},{ok:true,found:'false'}])assert.throws(()=>validateGeneralRecovery(x,a));f.storage.setItem=()=>{throw Error('denied')};f.setActor('new');await assert.rejects(f.service.prepare(event,'19',2));assert.equal(f.calls.length,0);});
test('late response after account change cannot expose receipt or clear original nonce',async()=>{const f=fixture(),a=await f.service.prepare(event,'19',2);let actor='guest';const guard=createGeneralReservations({storage:f.storage,identity:()=>({actor,token:'token'}),call:async()=>{actor='other';return{ok:true,code:'REAL',qty:2,amount_cents:0,currency:'EUR',paid:false,request_id:a.id,event_id:a.event,ticket_type_id:a.tier};},locks:null});await assert.rejects(guard.submit(a,'Guest','guest@example.com'),/account changed/);actor='guest';assert.equal(guard.read(event).id,a.id);});
test('sign-in cannot bypass an unresolved guest latch or send its nonce under another actor',async()=>{const f=fixture(),a=await f.service.prepare(event,'19',2);f.setActor('signed-in');assert.throws(()=>f.service.read(event),/unresolved guest request/);await assert.rejects(f.service.prepare(event,'19',2),/unresolved guest request/);await assert.rejects(f.service.recover(a),/account changed/);assert.equal(f.memory.size,1);assert.equal(f.calls.length,0);f.setActor('guest');assert.equal(f.service.read(event).id,a.id);assert.equal(await f.service.recover(a),null);assert.equal(f.calls[0].token,'guest-token');assert.equal(f.calls[0].args.p_request,a.id);});
test('malformed or legacy guest latch still blocks new signed-in reservations; another event does not',async()=>{const f=fixture();await f.service.prepare(event,'19',2);const k=[...f.memory.keys()][0];f.storage.setItem(k,'{corrupt');f.setActor('signed-in');await assert.rejects(f.service.prepare(event,'19',2),/unresolved guest request/);const other='44444444-4444-4444-8444-444444444444';assert.equal((await f.service.prepare(other,'19',1)).event,other);assert.equal(f.calls.length,0);});
