import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{extractHospitality,hospitalitySourceMatches,hospitalityPages,hospitalitySupplements,validHospitalityFields}from'../../supabase/functions/zoi-enrich/_hospitality.js';
import{extractRenderedSource}from'../../scripts/enrichment/extractor.mjs';import{captureSourceHTML}from'../../scripts/enrichment/source-html.mjs';import{reviewedEnrichmentBatch}from'../../scripts/enrichment/reviewed-batch.mjs';import{canonical,sha256}from'../../scripts/quality/evidence.mjs';import{hospitalityHomeContent,renderHospitalityHome}from'../../api/_hospitality-home.js';import{OLYMPIA}from'../../assets/homes/templates/hospitality/sources.mjs';
const source='https://www.amarahotel.com/',html=readFileSync(new URL('../fixtures/hospitality/amara-rooms.source.txt',import.meta.url),'utf8'),names=['Deluxe Sea View Room','Deluxe Grand Sea View Room'];
const ld=value=>`<script type="application/ld+json">${JSON.stringify(value)}</script>`;
const hotel=extra=>ld({'@type':'Hotel',name:'Example Hotel',url:'https://hotel.test/',...extra});
const row={listing_id:'361c983b-29aa-4b4a-8bfa-ca4a17993e40',name:'AMARA Hotel',entity_type:'travel_place',slug:'amara-hotel-limassol',website:source,source_fingerprint:'fixture-source-v1'};
export function catalogEntity(){return{id:row.listing_id,name:row.name,slug:row.slug,entity_type:row.entity_type,category_slug:'hotels',website:source,profile:{_enrich:{...extractHospitality(html,source+'rooms/'),source_url:source+'rooms/'}}};}
test('source-derived AMARA named room links deduplicate empty links without inventing stock',()=>{const p=extractHospitality(html,source+'rooms/');assert.deepEqual(p.rooms.map(x=>x.name),names);assert.equal(p.amenities,undefined);assert.equal(p.rooms[0].price,undefined);assert.equal(p.rooms[0].image,undefined);assert.deepEqual(extractRenderedSource(html,source+'rooms/').profile.rooms,p.rooms);});
test('homepage catalogue discovery follows actual same-origin links only and preserves two-fetch contact/menu priority',()=>{const home='<title>AMARA Hotel</title><a href="/rooms/">Rooms</a><a href="https://other.test/dining/">Dining</a>';assert.deepEqual(extractHospitality(home,source),{});assert.deepEqual(hospitalityPages(home,source),[{url:source+'rooms/',purpose:'hospitality'}]);const contact={url:source+'contact/',purpose:'contact'},menu={url:source+'menu/',purpose:'menu'},gallery={url:source+'gallery/',purpose:'gallery'};assert.deepEqual(hospitalitySupplements([gallery,contact],home,source),[contact,{url:source+'rooms/',purpose:'hospitality'}]);assert.deepEqual(hospitalitySupplements([menu,contact],home,source),[menu,contact]);});
test('generic navigation, absent href, off-origin, credentials, fragments, scripts and unrelated pages are not offerings',()=>{const bad='<a>Missing</a><a href="/rooms/">Rooms</a><a href="/room/anything/">Learn more</a><a href="https://evil.test/room/a/">Alien suite</a><a href="https://u:p@hotel.test/room/a/">Secret suite</a><a href="/room/a/#x">Fragment suite</a><script><a href="/room/b/">Script suite</a></script><div hidden><a href="/room/c/">Hidden suite</a></div>';assert.deepEqual(extractHospitality('<title>Example Hotel</title>'+bad,'https://hotel.test/'),{});assert.deepEqual(extractHospitality('<title>Community directory</title><a href="/room/a/">Blue room</a>','https://hotel.test/'),{});});
test('structured true amenities and named contained offerings only; conflicts fail closed',()=>{const p=extractHospitality(hotel({amenityFeature:[{'@type':'LocationFeatureSpecification',name:'Wi-Fi',value:true},{'@type':'LocationFeatureSpecification',name:'Pool',value:true},{'@type':'LocationFeatureSpecification',name:'Pool',value:false},{'@type':'LocationFeatureSpecification',name:'Gym',value:'true'}],containsPlace:[{'@type':'Restaurant',name:'Named Dining Room',url:'/restaurants/named/',description:'Published description'},{'@type':'HotelRoom',name:'Blue Suite',url:'/room/blue/'}]}),'https://hotel.test/');assert.deepEqual(p.amenities,['Wi-Fi']);assert.equal(p.dining[0].name,'Named Dining Room');assert.equal(p.rooms[0].name,'Blue Suite');assert.deepEqual(extractHospitality(hotel({})+hotel({name:'Other Hotel'})+'<a href="/room/a/">Suite A</a>','https://hotel.test/'),{});assert.deepEqual(extractHospitality(hotel({url:'https://other.test/'})+'<a href="/room/a/">Suite A</a>','https://hotel.test/'),{});assert.deepEqual(extractHospitality('<script type="application/ld+json">{bad</script>','https://hotel.test/'),{});assert.deepEqual(extractHospitality(hotel({})+'<a href="/room/a/">Suite A</a><a href="/room/a/">Suite B</a>','https://hotel.test/'),{});});
test('review field contract rejects overflow, unsafe URLs, prices, duplicates and malformed arrays',()=>{const p=extractHospitality(html,source);assert(validHospitalityFields(p,source));for(const rooms of [null,[],[...p.rooms,p.rooms[0]],Array(31).fill(p.rooms[0]),[{...p.rooms[0],price:200}],[{...p.rooms[0],source:'https://other.test/room/a/'}],[{...p.rooms[0],name:'<b>Suite</b>'}],[{...p.rooms[0],source:undefined}]])assert.equal(validHospitalityFields({rooms},source),false);});
test('single-page capture -> reviewed lease payload -> canonical public model -> all four layouts',async()=>{const directory=mkdtempSync(join(tmpdir(),'hotel-catalog-'));try{let requests=0;const report=await captureSourceHTML(row,{directory,session:{stats:{},sourceFetch:async()=>{requests++;return{status:200,text:html,url:source+'rooms/'};}}});assert.equal(requests,1);assert.equal(report.source.sha256,sha256(html));assert.equal(report.render,null);assert.deepEqual(report.profile.rooms.map(x=>x.name),names);const lease={...row,lease_id:'test-lease',existing_enrich:{}},review={listing_id:row.listing_id,source_fingerprint:row.source_fingerprint,report_sha256:sha256(canonical(report)),identity_confirmed:true,images_confirmed:true,reviewer:'isolated-test',reviewed_at:'2026-10-01T00:00:00Z',approved_image_hashes:[],prior_machine_sha256:sha256(canonical({}))};const batch=reviewedEnrichmentBatch(report,review,lease)[0],e={...catalogEntity(),profile:{_enrich:{...batch.profile,source_url:report.source.url}}};assert.deepEqual(hospitalityHomeContent(e).rooms.map(x=>x.name),names);for(const template of['atelier','concierge','table','parea']){const rendered=renderHospitalityHome(e,{template});for(const name of names)assert(rendered.includes(name));assert(rendered.includes('data-detail="rooms-0"'));assert(!rendered.includes('Book now'));}report.profile.rooms[0].source='https://other.test/a';review.report_sha256=sha256(canonical(report));assert.throws(()=>reviewedEnrichmentBatch(report,review,lease),/source_hospitality_invalid/);}finally{rmSync(directory,{recursive:true,force:true});}});
test('owner partial clears win across designs, including curated amenities; mismatched/quarantined machine facts disappear',()=>{const e=catalogEntity();for(const clear of[[],null])for(const template of['atelier','concierge','table','parea']){const own={...e,owner_content:{profile:{rooms:clear,dining:[{name:'Owner dining',source:source}]}}};assert.equal(hospitalityHomeContent(own).rooms.length,0);const rendered=renderHospitalityHome(own,{template});assert(!rendered.includes(names[0]));assert(rendered.includes('Owner dining'));const curated={id:OLYMPIA.id,website:OLYMPIA.source,profile:{},owner_content:{profile:{amenities:clear,rooms:clear}}};assert.deepEqual(hospitalityHomeContent({...curated,entity_type:'travel_place',category_slug:'hotels',name:'The Olympia',slug:OLYMPIA.slug}).amenities,[]);}for(const change of[{source_url:'https://other.test/'},{source_scope_mismatch:true},{scope_review_required:true},{last_error:'source_scope_mismatch'}])assert.deepEqual(hospitalityHomeContent({...e,profile:{_enrich:{...e.profile._enrich,...change}}}).rooms,[]);assert.deepEqual(hospitalityHomeContent({...e,owner_content:{website:null}}).rooms,[]);});

test('sibling properties on a shared domain cannot donate rooms or amenities',()=>{const source='https://chain.test/hotel-a/',other=ld({'@type':'Hotel',name:'Hotel B',url:'https://chain.test/hotel-b/',containsPlace:{'@type':'HotelRoom',name:'Hotel B Penthouse',url:'/hotel-b/rooms/penthouse/'},amenityFeature:{'@type':'LocationFeatureSpecification',name:'Hotel B rooftop pool',value:true}});assert.deepEqual(extractHospitality(other,source),{});assert.deepEqual(extractHospitality('<title>Hotel A</title><a href="/hotel-b/rooms/penthouse/">Hotel B Penthouse</a>',source),{});const rooms=[{name:'Wrong hotel',source:'https://chain.test/hotel-b/rooms/penthouse/',detail:''}];assert.equal(validHospitalityFields({rooms},source),false);const e={...catalogEntity(),website:source,profile:{_enrich:{source_url:source,rooms}}};assert.deepEqual(hospitalityHomeContent(e).rooms,[]);assert.equal(extractHospitality('<title>Hotel A</title><a href="/hotel-a/rooms/blue/">Blue Suite</a>',source+'rooms/').rooms[0].name,'Blue Suite');});

test('same-origin supplementary redirect cannot cross the current hotel property scope',()=>{assert.equal(hospitalitySourceMatches('https://chain.test/hotel-b/rooms/','https://chain.test/hotel-a/'),false);assert.equal(hospitalitySourceMatches('https://chain.test/hotel-a/rooms/','https://chain.test/hotel-a/'),true);});

test('worker initial and supplementary catalogue acceptance are bound to the original lease website',()=>{const worker=readFileSync(new URL('../../supabase/functions/zoi-enrich/index.ts',import.meta.url),'utf8');assert.match(worker,/if \(!hospitalitySourceMatches\(got.finalUrl!, row.website\)\) \{[\s\S]*?delete profile\[key\]; delete provenance\[key\]/);assert.match(worker,/hospitalitySourceMatches\(got.finalUrl!, row.website\) && hospitalitySourceMatches\(extra.finalUrl, row.website\) && validHospitalityFields\(next.profile, row.website\)/);});
