import test from 'node:test';import assert from 'node:assert/strict';import {message,subject,confirmed,requestTracker,esc,errorText} from '../../assets/inquiries/model.mjs';
test('message and subject enforce nonempty bounded trimmed text',()=>{assert.equal(message(' hello '),'hello');assert.throws(()=>message(' '));assert.throws(()=>message('x'.repeat(4001)));assert.throws(()=>subject('x'.repeat(121)));assert.equal(subject(' Topic '),'Topic');});
test('unchanged sends reuse stable request UUID; distinct payload starts new request',()=>{const tracker=requestTracker(),first=tracker.get(['thread','text']);assert.equal(tracker.get(['thread','text']),first);assert.notEqual(tracker.get(['thread','different']),first);tracker.clear();assert.notEqual(tracker.get(['thread','text']),first);});
test('unconfirmed response cannot be presented as success and untrusted text is escaped',()=>{assert.throws(()=>confirmed({ok:false,message:{id:'fake'}},'message'));assert.throws(()=>confirmed({ok:true},'thread'));assert.equal(esc('<img src=x onerror="run()">'),'&lt;img src=x onerror=&quot;run()&quot;&gt;');assert.doesNotMatch(errorText(Error('private SQL data')),/private SQL/);});

import{inquiryLifetime}from'../../assets/inquiries/lifecycle.mjs';
test('late private response after account switch is discarded',async()=>{let actor='A',resolve;const life=inquiryLifetime({getActor:()=>actor});const read=life.read(()=>new Promise(r=>resolve=r));actor='B';resolve({private:'A conversation'});await assert.rejects(read,/inquiry_stale_session/);assert.equal(life.active(),false);});
test('unmounted private response is discarded and cannot restart',async()=>{let resolve;const life=inquiryLifetime({getActor:()=> 'A'});const read=life.read(()=>new Promise(r=>resolve=r));life.dispose();resolve({private:'data'});await assert.rejects(read,/inquiry_stale_session/);await assert.rejects(life.read(()=>Promise.resolve('new')),/inquiry_stale_session/);});
test('guest cannot issue private enquiry read',async()=>{let called=false;const life=inquiryLifetime({getActor:()=>null});await assert.rejects(life.read(()=>{called=true}),/inquiry_stale_session/);assert.equal(called,false);});
import{inquiryPending}from'../../assets/inquiries/pending.mjs';
test('pending send persists nonce only and fences changed payload until receipt',()=>{const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};const p=inquiryPending({actor:'A',scope:'customer',storage});const args=p.begin('start',{p_listing:'d70c858b-d906-41b0-855e-623e605e3257',p_body:'PRIVATE MESSAGE'});assert.ok(args.p_request);assert.ok(![...values.values()][0].includes('PRIVATE'));assert.throws(()=>p.begin('start',{p_body:'different'}),/Resolve/);const restored=inquiryPending({actor:'A',scope:'customer',storage});assert.equal(restored.record.request,args.p_request);assert.equal(restored.payload,null);assert.equal(restored.matches({request_id:'wrong',kind:'start'}),false);assert.equal(inquiryPending({actor:'B',scope:'customer',storage}).record,null);restored.clear();assert.equal(values.size,0);});
test('storage failure stops send before any pending payload can be used',()=>{const p=inquiryPending({actor:'A',scope:'customer',storage:{getItem(){throw Error()}}});assert.throws(()=>p.begin('reply',{}),/storage is unavailable/);assert.equal(p.payload,null);});

test('corrupt non-null pending markers block replacement sends',()=>{for(const value of [{},false,{actor:'A',kind:'start',request:'bad'}]){const p=inquiryPending({actor:'A',scope:'customer',storage:{getItem:()=>JSON.stringify(value)}});assert.throws(()=>p.begin('start',{}),/storage is unavailable/);}});
import{sendReceipt,settingsReceipt,updateReceipt}from'../../assets/inquiries/model.mjs';
test('write receipts must match the exact submitted semantic payload',()=>{const id='d70c858b-d906-41b0-855e-623e605e3257',a={p_request:id,p_listing:id,p_subject:'subject',p_body:'message'};const thread={id,request_id:id,listing_id:id,subject:'subject',initial_body:'message'};assert.equal(sendReceipt({ok:true,thread},'start',a).id,id);for(const field of ['request_id','listing_id','subject','initial_body'])assert.throws(()=>sendReceipt({ok:true,thread:{...thread,[field]:'wrong'}},'start',a));assert.throws(()=>sendReceipt({ok:true,message:{id,request_id:id,thread_id:id,body:'different'}},'reply',{p_request:id,p_thread:id,p_body:'message'}));const args={p_workspace:id,p_listing:id,p_enabled:true,p_expected_version:3};assert.throws(()=>settingsReceipt({ok:true,settings:{listing_id:id,workspace_id:id,enabled:true,version:3}},args));assert.equal(settingsReceipt({ok:true,settings:{listing_id:id,workspace_id:id,enabled:true,version:4}},args).version,4);assert.throws(()=>updateReceipt({ok:true,thread:{id,workspace_id:id,status:'open',assignee_id:null,version:5}},{p_workspace:id,p_thread:id,p_status:'resolved',p_assignee:null,p_expected_version:4}));});
