import test from'node:test';import assert from'node:assert/strict';import{privateLocality,resolveLocality,homeDestination,createLocalityReader}from'../../assets/personalization/locality.mjs';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
const receipt=(city='Toronto',enabled=true)=>({ok:true,profile:{id:A,private_email:'not exported'},preferences:{city,country:'Canada',locality_enabled:enabled,topics:['food','private_invalid'],version:2},blocked:[{id:B}]});
function core(){let who=A;return{auth:{load:()=>who?{user_id:who}:null,token:()=>who?'token-'+who:null,ensureFresh:async()=>!!who},switch:id=>who=id,keys:{auth:'zoi_auth'},BASE:'https://example.invalid',KEY:'public-key'};}
test('minimal own projection requires confirmed receipt and explicit locality opt-in',()=>{assert.deepEqual(privateLocality(receipt()),{home:{city:'Toronto',country:'Canada'},topics:['food'],version:2});assert.equal(privateLocality(receipt('Toronto',false)).home,null);assert.throws(()=>privateLocality({ok:true}),/unconfirmed/);assert.ok(!JSON.stringify(privateLocality(receipt())).includes('private_email'));});
test('explicit destination and global choice win; category browsing may use saved home',()=>{const home={city:'Toronto',country:'Canada'};assert.equal(resolveLocality('/explore?type=business',home).source,'home');for(const url of ['/explore?city=Athens','/explore?q=Signature','/explore?country=Greece','/explore/map?place=paradosi','/explore/map#5/40/20','/explore?city='])assert.equal(resolveLocality(url,home).source,'explicit',url);assert.equal(resolveLocality('/explore?scope=global',home).source,'global');assert.equal(resolveLocality('/explore',null).source,'global');assert.equal(homeDestination('/explore?type=business&q=Athens#5/40/20',home),'/explore?type=business');});
test('account switch aborts prior read and late response cannot expose previous home',async()=>{const c=core(),pending=[],states=[];const r=createLocalityReader({core:c,pollMs:0,onChange:s=>states.push(s),read:signal=>new Promise(resolve=>pending.push({signal,resolve}))});const first=r.refresh();c.switch(B);r.checkAccount();assert.equal(pending[0].signal.aborted,true);pending[0].resolve(receipt('Old home'));await first;assert.equal(r.snapshot().home,null);pending[1].resolve(receipt('New home'));await new Promise(resolve=>setTimeout(resolve,0));assert.equal(r.snapshot().home.city,'New home');c.switch(null);r.checkAccount();assert.deepEqual(r.snapshot(),{status:'guest',home:null,topics:[],version:0});r.destroy();});
test('guest makes no private request and failure leaves no stale preferences',async()=>{const c=core();c.switch(null);let calls=0;const r=createLocalityReader({core:c,pollMs:0,read:async()=>{calls++;throw Error('offline');}});await r.refresh();assert.equal(calls,0);c.switch(A);await r.refresh();assert.equal(calls,1);assert.equal(r.snapshot().status,'error');assert.equal(r.snapshot().home,null);r.destroy();});
test('private read calls only existing own RPC, no-store and abort signal; never a preference writer',async()=>{const c=core(),calls=[];const r=createLocalityReader({core:c,pollMs:0,fetchImpl:async(url,options)=>{calls.push({url,options});return{ok:true,json:async()=>receipt()};}});await r.refresh();assert.equal(calls.length,1);assert.equal(calls[0].url,'https://example.invalid/rest/v1/rpc/community_me');assert.equal(calls[0].options.cache,'no-store');assert.equal(calls[0].options.body,'{}');assert.ok(calls[0].options.signal instanceof AbortSignal);r.destroy();});

import {mapHistoryIntent} from '../../assets/personalization/locality.mjs';
test('map Back/Forward restores browse intent without leaking saved home into history',()=>{const home={city:'Toronto',country:'Canada'},base='https://zoi.city/explore/map/';const generated=base+'#7/43.65/-79.38/0/0';const initial=mapHistoryIntent(generated,{zoiMapIntent:base});assert.equal(resolveLocality(initial,home).source,'home');assert.equal(resolveLocality(mapHistoryIntent(base+'?scope=global#3/40/20',{zoiMapIntent:base+'?scope=global'}),home).source,'global');assert.equal(resolveLocality(mapHistoryIntent(base+'?city=Athens#7/38/23',{zoiMapIntent:base+'?city=Athens'}),home).city,'Athens');assert.equal(mapHistoryIntent(generated,{zoiMapIntent:'https://other.test/explore/map/'}),generated);assert.equal(mapHistoryIntent(generated,{zoiMapIntent:'https://zoi.city/account/'}),generated);assert.equal(mapHistoryIntent(generated,null),generated);});

test('returning from preferences refreshes the same account without flashing global, but direct account changes clear home',async()=>{const c=core(),events=new EventTarget(),pending=[];const r=createLocalityReader({core:c,events,pollMs:0,read:()=>new Promise(resolve=>pending.push(resolve))});const first=r.refresh();pending.shift()(receipt());await first;events.dispatchEvent(new Event('focus'));assert.equal(r.snapshot().home.city,'Toronto');pending.shift()(receipt('Athens'));await new Promise(resolve=>setTimeout(resolve,0));assert.equal(r.snapshot().home.city,'Athens');c.switch(B);const second=r.refresh();assert.equal(r.snapshot().home,null);pending.shift()(receipt('Melbourne'));await second;assert.equal(r.snapshot().home.city,'Melbourne');r.destroy();events.dispatchEvent(new Event('focus'));assert.equal(pending.length,0);});
