import{test}from'node:test';import assert from'node:assert/strict';import{loadMapPages,focusOptions,isMappableRow}from'../../assets/map-data/loader.mjs';
test('map loader bounds concurrency at four and stops after the first short page',async()=>{let inFlight=0,peak=0;const offsets=[];const r=await loadMapPages(async(offset,size)=>{offsets.push(offset);peak=Math.max(peak,++inFlight);await new Promise(resolve=>setTimeout(resolve,2));inFlight--;return Array.from({length:offset===4000?25:offset<4000?size:0},(_,i)=>({id:offset+i}));});assert.equal(peak,4);assert.equal(r.rows.length,4025);assert.equal(r.requests,8);assert.equal(r.complete,true);assert.equal(r.truncated,false);assert.ok(!offsets.includes(8000));});
test('an outage stops after one bounded batch and never becomes an empty success',async()=>{let calls=0;await assert.rejects(loadMapPages(async()=>{calls++;throw Error('outage');}),/unavailable/);assert.equal(calls,4);});
test('failed or malformed pages remain explicit holes in partial results',async()=>{const result=await loadMapPages(async(offset,size)=>offset===1000?null:Array.from({length:offset===2000?4:offset<2000?size:0},()=>({})));assert.deepEqual(result.failedOffsets,[1000]);assert.equal(result.complete,false);assert.equal(result.endDetected,true);assert.equal(result.rows.length,1004);});
test('a full configured cap is marked truncated and not complete',async()=>{const r=await loadMapPages(async(_,size)=>Array(size).fill({}),{pageSize:10,maxRows:40});assert.equal(r.requests,4);assert.equal(r.truncated,true);assert.equal(r.complete,false);});
test('known empty first page is a real empty dataset; out-of-range failures do not invent holes',async()=>{const r=await loadMapPages(async(offset)=>{if(offset===0)return[];throw Error('irrelevant beyond end');});assert.equal(r.complete,true);assert.deepEqual(r.rows,[]);assert.deepEqual(r.failedOffsets,[]);});
test('selection focus respects precision, viewport occlusion and reduced motion',()=>{const exact=focusOptions({lng:23,lat:38,precision:'rooftop'}),city=focusOptions({lng:23,lat:38,precision:'city'}),unknown=focusOptions({lng:23,lat:38,precision:'none'},{width:390,height:500,top:200,bottom:300,reducedMotion:true});assert.ok(exact.zoom>city.zoom);assert.ok(city.zoom>unknown.zoom);assert.equal(unknown.duration,0);assert.equal(unknown.essential,false);assert.ok(unknown.padding.top+unknown.padding.bottom<=400);assert.equal(exact.retainPadding,false);});

test('invalid coordinates never enter MapLibre while valid zero coordinates remain valid',()=>{for(const row of [{slug:'a',lat:null,lng:5},{slug:'a',lat:NaN,lng:5},{slug:'a',lat:91,lng:5},{slug:'a',lat:5,lng:-181},{slug:'a',lat:'Infinity',lng:5},{lat:5,lng:5}])assert.equal(isMappableRow(row),false);assert.equal(isMappableRow({slug:'zero',lat:0,lng:0}),true);});

test('search bounds use only finite street-level coordinates, keep zero and never invent an empty destination',async()=>{const {matchBounds}=await import('../../assets/map-data/loader.mjs');assert.equal(matchBounds([]),null);assert.equal(matchBounds([{lat:null,lng:12},{lat:91,lng:2}]),null);assert.deepEqual(matchBounds([{lat:0,lng:0,precision:'street'},{lat:43.6,lng:-79.4,precision:'address'},{lat:Infinity,lng:2,precision:'street'}]),[[-79.4,0],[0,43.6]]);assert.deepEqual(matchBounds([{lat:38,lng:23,precision:'rooftop'}]),[[23,38],[23,38]]);});

test('selecting a city-positioned place preserves a closer manual zoom instead of jumping back out',()=>{const p={lng:-79.4,lat:43.7,precision:'city'};assert.equal(focusOptions(p,{currentZoom:16}).zoom,16);assert.equal(focusOptions(p,{currentZoom:4}).zoom,10);assert.equal(focusOptions(p,{currentZoom:NaN}).zoom,10);assert.equal(focusOptions(p,{currentZoom:'16'}).zoom,10);assert.equal(focusOptions(p,{currentZoom:25}).zoom,18.5);assert.equal(focusOptions(p,{currentZoom:16,reducedMotion:true}).duration,0);});

test('transient page failures retry at most twice inside the four worker slots',async()=>{
 const calls=new Map();let active=0,peak=0;
 const result=await loadMapPages(async(offset,size)=>{calls.set(offset,(calls.get(offset)||0)+1);peak=Math.max(peak,++active);try{await Promise.resolve();if(offset===0&&calls.get(offset)<3)throw Object.assign(Error('canceling statement due to statement timeout'),{status:500});return offset===0?Array(size).fill({id:'a'}):[];}finally{active--; }},{pageSize:2,maxRows:8,wait:async()=>{}});
 assert.equal(calls.get(0),3);assert.ok(peak<=4);assert.equal(result.complete,true);assert.equal(result.requests,6);assert.deepEqual(result.failedOffsets,[]);
});
test('exhausted network retries remain explicit partial coverage and invalid responses are not retried',async()=>{
 let count=0;const result=await loadMapPages(async(offset,size)=>{if(offset===0)return Array(size).fill({});if(offset===2){count++;throw new TypeError('Failed to fetch');}return[];},{pageSize:2,maxRows:8,wait:async()=>{}});
 assert.equal(count,3);assert.equal(result.complete,false);assert.deepEqual(result.failedOffsets,[2]);
 const {retryMapRead}=await import('../../assets/map-data/loader.mjs');let auth=0;await assert.rejects(retryMapRead(async()=>{auth++;throw Object.assign(Error('Forbidden'),{status:403});},{wait:async()=>{}}));assert.equal(auth,1);
});
test('unmapped deep links preserve exact identity without inventing any coordinates',async()=>{
 const {unmappedPlace}=await import('../../assets/map-data/loader.mjs');const entity={id:'84bdafb9-966b-489a-a4d3-0dc3dc92acf9',slug:'yamas-nairobi',name:'Yamas',city:'Nairobi',country:'Kenya',entity_type:'business',lat:-1,lng:36};
 const p=unmappedPlace(entity,'yamas-nairobi');assert.equal(p.s,'yamas-nairobi');assert.equal(p.city,'Nairobi');assert.equal(p.lat,null);assert.equal(p.lng,null);assert.equal(p.unmapped,true);assert.equal(isMappableRow(p),false);
 assert.equal(unmappedPlace({...entity,slug:'yamas-cardiff'},'yamas-nairobi'),null);assert.equal(unmappedPlace({...entity,marketplace_status:'hidden'},'yamas-nairobi'),null);assert.equal(unmappedPlace({...entity,publish_status:'draft'},'yamas-nairobi'),null);assert.equal(unmappedPlace(null,'yamas-nairobi'),null);
});

test('unmapped identity survives resize moveend and late response cannot replace a new selection',async()=>{
 const fs=await import('node:fs'),vm=await import('node:vm');const html=fs.readFileSync(new URL('../../explore/map/index.html',import.meta.url),'utf8');
 const fn=html.match(/async function openUnmappedPlace\(slug\) \{[\s\S]*?\n  \}\n\n  function closeSelection/)?.[0].replace(/\n\n  function closeSelection$/,'');assert.ok(fn);
 const elements=new Map(),node=()=>({classList:{add(){}},innerHTML:'',textContent:'',appendChild(){}});let resolve;
 const context={selectionVersion:0,pendingPlace:null,selected:null,listState:{mode:'all'},mapTools:{retryMapRead:()=>new Promise(r=>{resolve=r}),unmappedPlace:(e,s)=>e.slug===s?{s,n:e.name,city:'Nairobi',country:'Kenya'}:null},C:{},$:id=>{if(!elements.has(id))elements.set(id,node());return elements.get(id)},setSheet(){if(context.listState.mode==='all'){context.selectionVersion++;context.pendingPlace=null;}},showList(){context.listState.mode='group'},writeUrl(){},nice:()=>'',document:{createElement:node}};
 vm.createContext(context);vm.runInContext(fn,context);const first=context.openUnmappedPlace('nairobi');assert.equal(context.pendingPlace,'nairobi');resolve({slug:'nairobi',name:'Yamas'});await first;assert.equal(context.selected.s,'nairobi');
 const late=context.openUnmappedPlace('nairobi');context.selectionVersion++;context.selected={s:'another-place'};resolve({slug:'nairobi',name:'Yamas'});await late;assert.equal(context.selected.s,'another-place');
});

test('coarse and unknown coordinates never become premises or move search bounds',async()=>{const {hasStreetPosition,matchBounds}=await import('../../assets/map-data/loader.mjs');for(const precision of ['city','approx','approximate','region','neighbourhood','none','unknown',''])assert.equal(hasStreetPosition({lat:37.97,lng:23.73,precision}),false);assert.equal(matchBounds([{lat:37.97,lng:23.73,precision:'city'}]),null);assert.equal(hasStreetPosition({lat:43.6,lng:-79.4,geo_precision:'street'}),true);});

test('false street labels reused across cities or many addresses remain unplotted',async()=>{const {validatePositionCohorts,hasStreetPosition}=await import('../../assets/map-data/loader.mjs');const source=[{lat:43.6532,lng:-79.3832,precision:'street',city:'Toronto',country:'Canada',addr:'One'},{lat:43.6532,lng:-79.3832,precision:'street',city:'Brantford',country:'Canada',addr:'Two'}];const projected=validatePositionCohorts(source);assert.ok(projected.every(p=>!hasStreetPosition(p)));assert.ok(source.every(p=>!Object.hasOwn(p,'position_conflict')));const shared=validatePositionCohorts([{...source[0]},{...source[0],addr:'One'}]);assert.ok(shared.every(hasStreetPosition));const mixed=validatePositionCohorts(Array.from({length:9},(_,i)=>({...source[0],addr:String(i)})));assert.ok(mixed.every(p=>!hasStreetPosition(p)));});
