import{test}from'node:test';import assert from'node:assert/strict';import{loadMapPages,focusOptions,isMappableRow}from'../../assets/map-data/loader.mjs';
test('map loader bounds concurrency at four and stops after the first short page',async()=>{let inFlight=0,peak=0;const offsets=[];const r=await loadMapPages(async(offset,size)=>{offsets.push(offset);peak=Math.max(peak,++inFlight);await new Promise(resolve=>setTimeout(resolve,2));inFlight--;return Array.from({length:offset===4000?25:offset<4000?size:0},(_,i)=>({id:offset+i}));});assert.equal(peak,4);assert.equal(r.rows.length,4025);assert.equal(r.requests,5);assert.equal(r.complete,true);assert.equal(r.truncated,false);assert.ok(!offsets.includes(8000));});
test('an outage stops after the first page probe and never becomes an empty success',async()=>{let calls=0;await assert.rejects(loadMapPages(async()=>{calls++;throw Error('outage');}),/unavailable/);assert.equal(calls,1);});
test('failed or malformed pages remain explicit holes in partial results',async()=>{const result=await loadMapPages(async(offset,size)=>offset===1000?null:Array.from({length:offset===2000?4:offset<2000?size:0},()=>({})));assert.deepEqual(result.failedOffsets,[1000]);assert.equal(result.complete,false);assert.equal(result.endDetected,true);assert.equal(result.rows.length,1004);});
test('a full configured cap is marked truncated and not complete',async()=>{const r=await loadMapPages(async(_,size)=>Array(size).fill({}),{pageSize:10,maxRows:40});assert.equal(r.requests,4);assert.equal(r.truncated,true);assert.equal(r.complete,false);});
test('known empty first page is a real empty dataset; out-of-range failures do not invent holes',async()=>{const r=await loadMapPages(async(offset)=>{if(offset===0)return[];throw Error('irrelevant beyond end');});assert.equal(r.complete,true);assert.deepEqual(r.rows,[]);assert.deepEqual(r.failedOffsets,[]);});
test('selection focus respects precision, viewport occlusion and reduced motion',()=>{const exact=focusOptions({lng:23,lat:38,precision:'rooftop'}),city=focusOptions({lng:23,lat:38,precision:'city'}),unknown=focusOptions({lng:23,lat:38,precision:'none'},{width:390,height:500,top:200,bottom:300,reducedMotion:true});assert.ok(exact.zoom>city.zoom);assert.ok(city.zoom>unknown.zoom);assert.equal(unknown.duration,0);assert.equal(unknown.essential,false);assert.ok(unknown.padding.top+unknown.padding.bottom<=400);assert.equal(exact.retainPadding,false);});

test('invalid coordinates never enter MapLibre while valid zero coordinates remain valid',()=>{for(const row of [{slug:'a',lat:null,lng:5},{slug:'a',lat:NaN,lng:5},{slug:'a',lat:91,lng:5},{slug:'a',lat:5,lng:-181},{slug:'a',lat:'Infinity',lng:5},{lat:5,lng:5}])assert.equal(isMappableRow(row),false);assert.equal(isMappableRow({slug:'zero',lat:0,lng:0}),false);});

test('search bounds use only finite street-level coordinates, keep zero and never invent an empty destination',async()=>{const {matchBounds}=await import('../../assets/map-data/loader.mjs');assert.equal(matchBounds([]),null);assert.equal(matchBounds([{lat:null,lng:12},{lat:91,lng:2}]),null);assert.deepEqual(matchBounds([{lat:0,lng:1,precision:'street'},{lat:43.6,lng:-79.4,precision:'address'},{lat:Infinity,lng:2,precision:'street'}]),[[-79.4,0],[1,43.6]]);assert.deepEqual(matchBounds([{lat:38,lng:23,precision:'rooftop'}]),[[23,38],[23,38]]);});

test('selecting a city-positioned place preserves a closer manual zoom instead of jumping back out',()=>{const p={lng:-79.4,lat:43.7,precision:'city'};assert.equal(focusOptions(p,{currentZoom:16}).zoom,16);assert.equal(focusOptions(p,{currentZoom:4}).zoom,10);assert.equal(focusOptions(p,{currentZoom:NaN}).zoom,10);assert.equal(focusOptions(p,{currentZoom:'16'}).zoom,10);assert.equal(focusOptions(p,{currentZoom:25}).zoom,18.5);assert.equal(focusOptions(p,{currentZoom:16,reducedMotion:true}).duration,0);});

test('transient page failures retry at most twice inside the four worker slots',async()=>{
 const calls=new Map();let active=0,peak=0;
 const result=await loadMapPages(async(offset,size)=>{calls.set(offset,(calls.get(offset)||0)+1);peak=Math.max(peak,++active);try{await Promise.resolve();if(offset===0&&calls.get(offset)<3)throw Object.assign(Error('canceling statement due to statement timeout'),{status:500});return offset===0?Array(size).fill({id:'a'}):[];}finally{active--; }},{pageSize:2,maxRows:8,wait:async()=>{}});
 assert.equal(calls.get(0),3);assert.ok(peak<=4);assert.equal(result.complete,true);assert.equal(result.requests,6);assert.deepEqual(result.failedOffsets,[]);
});
test('exhausted network retries remain explicit partial coverage and invalid responses are not retried',async()=>{
 let count=0;const result=await loadMapPages(async(offset,size)=>{if(offset===0)return Array(size).fill({});if(offset===2){count++;throw new TypeError('Failed to fetch');}return[];},{pageSize:2,maxRows:8,wait:async()=>{}});
 assert.equal(count,3);assert.equal(result.complete,false);assert.deepEqual(result.failedOffsets,[2]);
 const {retryMapRead}=await import('../../assets/map-data/loader.mjs');let auth=0;await assert.rejects(retryMapRead(async()=>{auth++;throw Object.assign(Error('Forbidden'),{status:403});},{wait:async()=>{}}));assert.equal(auth,1);
});
test('unmapped deep links preserve exact identity without inventing any coordinates',async()=>{
 const {unmappedPlace}=await import('../../assets/map-data/loader.mjs');const entity={id:'84bdafb9-966b-489a-a4d3-0dc3dc92acf9',slug:'yamas-nairobi',name:'Yamas',city:'Nairobi',country:'Kenya',entity_type:'business',lat:-1,lng:36};
 const p=unmappedPlace(entity,'yamas-nairobi');assert.equal(p.s,'yamas-nairobi');assert.equal(p.city,'Nairobi');assert.equal(p.lat,null);assert.equal(p.lng,null);assert.equal(p.unmapped,true);assert.equal(isMappableRow(p),false);
 assert.equal(unmappedPlace({...entity,slug:'yamas-cardiff'},'yamas-nairobi'),null);assert.equal(unmappedPlace({...entity,marketplace_status:'hidden'},'yamas-nairobi'),null);assert.equal(unmappedPlace({...entity,publish_status:'draft'},'yamas-nairobi'),null);assert.equal(unmappedPlace(null,'yamas-nairobi'),null);
});

test('unmapped identity survives resize moveend and late response cannot replace a new selection',async()=>{
 const fs=await import('node:fs'),vm=await import('node:vm');const html=fs.readFileSync(new URL('../../explore/map/index.html',import.meta.url),'utf8');
 const fn=html.match(/async function openUnmappedPlace\(slug\) \{[\s\S]*?\n  \}/)?.[0];assert.ok(fn);
 const elements=new Map(),node=()=>({classList:{add(){}},innerHTML:'',textContent:'',appendChild(){}});let resolve;
 const context={selectionVersion:0,pendingPlace:null,selected:null,listState:{mode:'all'},mapTools:{retryMapRead:()=>new Promise(r=>{resolve=r}),unmappedPlace:(e,s)=>e.slug===s?{s,n:e.name,city:'Nairobi',country:'Kenya'}:null},C:{},$:id=>{if(!elements.has(id))elements.set(id,node());return elements.get(id)},setSheet(){if(context.listState.mode==='all'){context.selectionVersion++;context.pendingPlace=null;}},showList(){context.listState.mode='group'},writeUrl(){},nice:()=>'',document:{createElement:node},selectedPositionStatus(){}};
 vm.createContext(context);vm.runInContext(fn,context);const first=context.openUnmappedPlace('nairobi');assert.equal(context.pendingPlace,'nairobi');resolve({slug:'nairobi',name:'Yamas'});await first;assert.equal(context.selected.s,'nairobi');
 const late=context.openUnmappedPlace('nairobi');context.selectionVersion++;context.selected={s:'another-place'};resolve({slug:'nairobi',name:'Yamas'});await late;assert.equal(context.selected.s,'another-place');
});

test('coarse and unknown coordinates never become premises or move search bounds',async()=>{const {hasStreetPosition,matchBounds}=await import('../../assets/map-data/loader.mjs');for(const precision of ['city','approx','approximate','region','neighbourhood','none','unknown',''])assert.equal(hasStreetPosition({lat:37.97,lng:23.73,precision}),false);assert.equal(matchBounds([{lat:37.97,lng:23.73,precision:'city'}]),null);assert.equal(hasStreetPosition({lat:43.6,lng:-79.4,geo_precision:'street'}),true);});

test('false street labels reused across cities or many addresses remain unplotted',async()=>{const {validatePositionCohorts,hasStreetPosition}=await import('../../assets/map-data/loader.mjs');const source=[{lat:43.6532,lng:-79.3832,precision:'street',city:'Toronto',country:'Canada',addr:'One'},{lat:43.6532,lng:-79.3832,precision:'street',city:'Brantford',country:'Canada',addr:'Two'}];const projected=validatePositionCohorts(source);assert.ok(projected.every(p=>!hasStreetPosition(p)));assert.ok(source.every(p=>!Object.hasOwn(p,'position_conflict')));const shared=validatePositionCohorts([{...source[0]},{...source[0],addr:'One'}]);assert.ok(shared.every(hasStreetPosition));const mixed=validatePositionCohorts(Array.from({length:9},(_,i)=>({...source[0],addr:String(i)})));assert.ok(mixed.every(p=>!hasStreetPosition(p)));});

test('coordinate guards reject coercion values and dual-zero while retaining real zero-axis locations',async()=>{const {validCoordinates,hasStreetPosition}=await import('../../assets/map-data/loader.mjs');for(const lat of ['', ' ',false,true,[],{},null,'0x10']){assert.equal(validCoordinates({lat,lng:12}),false);assert.equal(hasStreetPosition({lat,lng:12,precision:'street'}),false);}for(const p of [{lat:0,lng:12},{lat:12,lng:0},{lat:'-0.5',lng:' 12.25 '}])assert.equal(hasStreetPosition({...p,precision:'street'}),true);assert.equal(hasStreetPosition({lat:0,lng:0,precision:'street'}),false);});
test('area search retains scoped unmapped results, paginates truthfully and never supplies coordinates',async()=>{const {createMapAreaSearch,areaResultPlace}=await import('../../assets/map-data/loader.mjs');const args=[],search=createMapAreaSearch(async p=>{args.push(p);return p.p_offset===0?Array.from({length:24},(_,i)=>({id:String(i),slug:'s'+i,name:'Place',city:'Nairobi',country:'Kenya',lat:1,lng:2})):[];});search.setScope({city:'Nairobi',country:'Kenya'});await search.more();assert.equal(search.state().rows.length,24);assert.equal(search.state().done,false);const place=areaResultPlace(search.state().rows[0]);assert.equal(place.lat,null);assert.equal(place.lng,null);await search.more();assert.equal(args[1].p_offset,24);assert.equal(search.state().done,true);});
test('area responses cannot overwrite changed account/location, and failure stays retryable',async()=>{const {createMapAreaSearch}=await import('../../assets/map-data/loader.mjs');let resolve,fail=false;const search=createMapAreaSearch(()=>fail?Promise.reject(Error('offline')):new Promise(r=>resolve=r));search.setScope({city:'Nairobi',actor:'a'});const first=search.more();search.setScope({city:'Athens',actor:'b'});resolve([{id:'1',slug:'old',name:'Old',city:'Nairobi'}]);await first;assert.equal(search.state().rows.length,0);fail=true;await search.more();assert.match(search.state().error,/Retry/);assert.equal(search.state().done,false);assert.equal(search.state().offset,0);search.clear();assert.equal(search.state().active,false);});
test('scoped area response rejects wrong country and private rows without promoting returned coordinates',async()=>{const {createMapAreaSearch}=await import('../../assets/map-data/loader.mjs');const common={id:'1',slug:'one',name:'One',city:'Athens',country:'Greece'};const search=createMapAreaSearch(async()=>[common,{...common,slug:'wrong-country',country:'USA'},{...common,slug:'private',publish_status:'draft'}]);search.setScope({city:'Athens',country:'Greece'});await search.more();assert.deepEqual(search.state().rows.map(x=>x.slug),['one']);assert.equal(search.state().done,true);});

test('service outage retries only the health probe, never starts parallel directory reads',async()=>{const offsets=[],waits=[];await assert.rejects(loadMapPages(async offset=>{offsets.push(offset);throw Object.assign(Error('Service unavailable'),{status:503});},{wait:async ms=>waits.push(ms)}),/unavailable/);assert.deepEqual(offsets,[0,0,0]);assert.deepEqual(waits,[350,700]);});

import {publishedAddressLookup,areaResultPlace,hasStreetPosition} from '../../assets/map-data/loader.mjs';
test('unlocated published address search keeps exact place identity and never routes by coordinates',()=>{const row={id:'real-id',slug:'actual-place',name:'Actual place',city:'Montréal',country:'Canada',address:'5777 Avenue Wilderton',latitude:45.5,longitude:-73.5};const place=areaResultPlace(row),before=JSON.stringify(place),action=publishedAddressLookup(place);const u=new URL(action.href);assert.equal(u.origin,'https://www.google.com');assert.equal(u.pathname,'/maps/search/');assert.equal(u.searchParams.get('api'),'1');assert.equal(u.searchParams.get('query'),'Actual place, 5777 Avenue Wilderton, Montréal, Canada');assert.equal(action.basis,'published-address');assert.equal(u.searchParams.has('destination'),false);assert.equal(u.searchParams.has('query_place_id'),false);assert.equal(hasStreetPosition(place),false);assert.equal(JSON.stringify(place),before);});
test('address lookup refuses city-only, country-only, absent, non-text and oversized addresses',()=>{const place={s:'actual',n:'Actual',addr:'Street',city:'London',country:'United Kingdom'};for(const address of[null,'','  ','London','United Kingdom','London, United Kingdom',false,{},'x'.repeat(501)])assert.equal(publishedAddressLookup(place,{address}),null);assert.equal(publishedAddressLookup({...place,country:''}),null);assert.equal(publishedAddressLookup({...place,s:''}),null);assert.equal(publishedAddressLookup(place,{address:'<b>20 Main Street</b>'}).address,'20 Main Street');});
test('fresh explicit address edit and clear override earlier place without using map scope as locality',()=>{const place={s:'actual',n:'Actual',addr:'Old Address',city:'Nairobi',country:'Kenya',lat:123,lng:456};const fresh=publishedAddressLookup(place,{address:'New Published Address',city:'Nairobi',country:'Kenya'});assert.match(new URL(fresh.href).searchParams.get('query'),/New Published Address, Nairobi, Kenya/);assert.doesNotMatch(fresh.href,/Old|123|456/);assert.equal(publishedAddressLookup(place,{address:null}),null);assert.equal(place.addr,'Old Address');});

async function actualDirectionPolicy(){const fs=await import('node:fs'),vm=await import('node:vm'),mapTools=await import('../../assets/map-data/loader.mjs');const html=fs.readFileSync(process.env.MAP_DIRECTION_HTML||new URL('../../explore/map/index.html',import.meta.url),'utf8'),source=html.match(/function directionsUrl\(p\)[\s\S]*?(?=\n  function [a-zA-Z])/)[0],context={mapTools};vm.createContext(context);vm.runInContext(source,context);return{directions:context.directionsUrl,mapTools};}
test('actual map directions refuse unreviewed numeric points and recover published address search',async()=>{const {directions}=await actualDirectionPolicy(),point={s:'actual',n:'Actual place',city:'Nairobi',country:'Kenya',precision:'street',lat:-1.28,lng:36.8};assert.equal(directions(point),null);const lookup=new URL(directions({...point,addr:'20 Published Street'}));assert.equal(lookup.pathname,'/maps/search/');assert(!lookup.searchParams.has('destination'));assert.equal(directions({...point,reviewedPosition:true,precision:'unknown'}),null);assert.equal(directions({...point,reviewedPosition:true,position_conflict:true}),null);});
test('actual map numeric directions require exact identity and coordinate receipt, and fresh clear cannot retain old action',async()=>{const {directions,mapTools}=await actualDirectionPolicy(),point={s:'actual',n:'Actual',addr:'Old address',city:'Sydney',country:'Australia',precision:'street',lat:-33.8818077,lng:151.2192239},entity={id:'actual-id',slug:'actual',geo_precision:'street',latitude:point.lat,longitude:point.lng,reviewed_destination:{listing_id:'actual-id',request_id:'review-proof',precision:'street',latitude:point.lat,longitude:point.lng}};assert.equal(mapTools.hasReviewedPosition(point,entity),true);assert.equal(new URL(directions({...point,reviewedPosition:mapTools.hasReviewedPosition(point,entity)})).searchParams.get('destination'),'-33.8818077,151.2192239');for(const bad of[{...entity,reviewed_destination:null},{...entity,reviewed_destination:{...entity.reviewed_destination,listing_id:'other'}},{...entity,reviewed_destination:{...entity.reviewed_destination,longitude:151.2}},{...entity,latitude:-33.8}]){assert.equal(mapTools.hasReviewedPosition(point,bad),false);const current={...point,addr:'',reviewedPosition:mapTools.hasReviewedPosition(point,bad)};assert.equal(directions(current),null);assert.equal(point.addr,'Old address');}});

test('global startup reader is explicit opt-in and retains bounded public pagination without coordinates',async()=>{const {createMapAreaSearch}=await import('../../assets/map-data/loader.mjs');let disabled=0;const off=createMapAreaSearch(async()=>{disabled++;return[]});off.setScope({actor:'a'});await off.more();assert.equal(disabled,0);assert.equal(off.state().active,false);const calls=[],search=createMapAreaSearch(async p=>{calls.push(p);return Array.from({length:p.p_offset===0?24:1},(_,i)=>({id:String(p.p_offset+i),slug:'global-'+(p.p_offset+i),name:'Published',country:'Kenya',latitude:99,longitude:999}))},{allowGlobal:true});search.setScope({actor:'a'});await search.more();assert.equal(search.state().done,false);await search.more();assert.equal(search.state().rows.length,25);assert.equal(search.state().done,true);assert(calls.every(p=>p.p_city===null&&p.p_country===null&&p.p_q===null&&p.p_limit===24));assert.deepEqual(calls.map(p=>p.p_offset),[0,24]);assert(search.state().rows.map(areaResultPlace).every(p=>p.lat===null&&p.lng===null));});
test('global startup account invalidation drops a pending result and failure remains retryable',async()=>{const {createMapAreaSearch}=await import('../../assets/map-data/loader.mjs');let release,fail=false,calls=0;const search=createMapAreaSearch(()=>{calls++;if(fail)return Promise.reject(Error('offline'));return new Promise(r=>release=r)},{allowGlobal:true});search.setScope({actor:'first'});const old=search.more();search.setScope({actor:'second'});release([{id:'old',slug:'old',name:'Old'}]);await old;assert.equal(search.state().rows.length,0);fail=true;await search.more();assert.match(search.state().error,/Retry/);assert.equal(search.state().offset,0);assert.equal(search.state().done,false);fail=false;const retry=search.more();release([{id:'new',slug:'new',name:'New',publish_status:'published'},{id:'private',slug:'private',name:'Private',marketplace_status:'hidden'}]);await retry;assert.deepEqual(search.state().rows.map(r=>r.slug),['new']);assert.equal(calls,3);});
