import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{extractMemberSource,identityMatches,classifyMemberSource,organizationContamination,memberTextFromHTML}from'../../api/_member-source.js';
const text=fs.readFileSync('tests/fixtures/member-source/atzakis-indexed.txt','utf8'),args={url:'https://www.hellenicmedical.ca/profile/atzakis/',text,expectedName:'Ageliki Tzakis',checkedAt:'2026-09-30',images:['https://www.hellenicmedical.ca/wp-content/uploads/pp-avatar/8fa09195a4bee0a72380b3ab7dc789ff.png']};
test('identity-scoped member facts preserveprofession notsociety orclinic',()=>{const m=extractMemberSource(args);assert.equal(m.name,'Ageliki (Angie) Tzakis');assert.equal(m.profession,'Registered Nurse');assert.equal(m.credentials,'RN');assert.equal(m.city,'East York / Scarborough');assert.equal(m.phone,'+14166699865');assert.equal(m.email,'at.rnconsulting@gmail.com');assert.deepEqual(m.languages,['Greek']);assert.equal(m.education[0].graduation_year,2007);assert.equal(m.specialties.length,4);assert.match(m.portrait_url,/pp-avatar/);assert.equal(m.provenance.licence_verified,false)});
test('mismatchedname rootorganization unsupportedhost andchallenge yieldno member',()=>{assert.equal(extractMemberSource({...args,expectedName:'Other Person'}),null);assert.equal(extractMemberSource({...args,url:'https://www.hellenicmedical.ca/'}),null);assert.equal(extractMemberSource({...args,url:'https://evil.example/profile/atzakis/'}),null);assert.equal(extractMemberSource({...args,text:'One moment, please. Request being verified.'}),null);assert(identityMatches('Dr Ageliki Tzakis','Ageliki (Angie) Tzakis, RN'))});
test('missingpracticefields neverfallback to footercontacts or organizationOGimage',()=>{const m=extractMemberSource({...args,text:text.replace(/Practice Phone:.*\n|Practice E-mail:.*\n/g,''),images:['https://www.hellenicmedical.ca/wp-content/uploads/2025/07/chms-default.jpg']});assert.equal(m.phone,null);assert.equal(m.email,null);assert.equal(m.portrait_url,null)});
test('HTML normalization ignoreshead nav footer scripts and preserveslabels',()=>{const html='<head><meta property="og:image" content="org.jpg"></head><nav>Ageliki Tzakis</nav><main><h1>Ageliki (Angie) Tzakis, RN</h1><p>Associate</p><p>Profession: Registered Nurse</p><p>Practice Phone: <a>4166699865</a></p><p>Speaks Greek: Yes</p></main><footer>Practice Phone:9055812440</footer><script>Profession:Doctor</script>';const m=extractMemberSource({...args,text:undefined,html});assert.equal(m.phone,'+14166699865');assert.equal(m.profession,'Registered Nurse');assert(!memberTextFromHTML(html).includes('9055812440'))});
test('onlyexactderivedcontamination flagged;explicitownerfields untouched',()=>{const p={entity_type:'professional',photo_url:'owner.jpg',social_links:{instagram:'owner'},profile:{_enrich:{source_url:args.url,photo_url:'https://www.hellenicmedical.ca/wp-content/uploads/2025/07/chms-default.jpg',tagline:'Canadian Hellenic Medical Society',social:{facebook:'https://www.facebook.com/hellenicmedical.ca/',linkedin:'https://www.linkedin.com/in/real-person'},email:'NotApplicable@NotApplicable.NotApplicable'}}};assert.deepEqual(organizationContamination(p).map(x=>x.field),['photo_url','tagline','social.facebook','email']);assert.equal(p.photo_url,'owner.jpg');assert.deepEqual(organizationContamination({...p,entity_type:'organization'}),[])});
test('genericthirdparty classificationneverallowsglobalpersonOGmetadata',()=>{assert.equal(classifyMemberSource({entity_type:'professional',website:'https://society.example/members/person'}).global_metadata_safe,false);assert.equal(classifyMemberSource({entity_type:'professional',website:'https://society.example/'}).kind,'person_on_shared_site_requires_review')});

test('futureworker guard suppressesglobalbranding and preservespriorreview onchallenge',async()=>{const{memberEnrichmentGuard}=await import('../../api/_member-source.js');const listing={name:'Ageliki Tzakis',entity_type:'professional',website:args.url,profile:{_enrich:{member:{profession:'Registered Nurse',portrait_url:'reviewed'}}}};let g=memberEnrichmentGuard({listing,html:'<html>One moment, please. Request being verified.</html>',url:args.url});assert.equal(g.handled,true);assert.equal(g.skipSupplementary,true);assert(!('member'in g.profile));assert(!('photo_url'in g.profile));assert.equal(listing.profile._enrich.member.portrait_url,'reviewed');g=memberEnrichmentGuard({listing,html:text.split('\n').map(x=>'<p>'+x+'</p>').join(''),url:args.url,images:args.images,checkedAt:'2026-09-30'});assert.equal(g.profile.member.profession,'Registered Nurse');assert.deepEqual(g.profile.social,{});assert.equal(g.profile.hero_url,null);assert.equal(memberEnrichmentGuard({listing:{...listing,entity_type:'organization'},url:args.url,html:''}).handled,false);assert.equal(memberEnrichmentGuard({listing:{...listing,website:'https://personal-practice.example/'},url:'https://personal-practice.example/',html:''}).handled,false)});

test('ambiguous portraits remain empty and a reviewed matching portrait survives a text-only refresh',async()=>{const{memberEnrichmentGuard}=await import('../../api/_member-source.js');const other='https://www.hellenicmedical.ca/wp-content/uploads/pp-avatar/another-person.png';assert.equal(extractMemberSource({...args,images:[...args.images,other]}).portrait_url,null);const previous=extractMemberSource(args);const listing={name:'Ageliki Tzakis',entity_type:'professional',website:args.url,profile:{_enrich:{member:previous}}};const result=memberEnrichmentGuard({listing,url:args.url,html:text.split('\n').map(x=>'<p>'+x+'</p>').join(''),checkedAt:'2026-09-30'});assert.equal(result.profile.member.portrait_url,args.images[0]);assert.equal(result.profile.member.provenance.portrait,'previous_reviewed_member_portrait');const wrong={...listing,profile:{_enrich:{member:{...previous,source_url:'https://www.hellenicmedical.ca/profile/other/'}}}};assert.equal(memberEnrichmentGuard({listing:wrong,url:args.url,html:text.split('\n').map(x=>'<p>'+x+'</p>').join('')}).profile.member.portrait_url,null)});
