import test from 'node:test';import assert from 'node:assert/strict';
import {musicHomeContent} from '../../api/_music-home.js';
import {machineImage,profileMedia} from '../../api/_profile-media.js';
const flag='https://yannis-ploutarchos.gr/wp-content/plugins/qtranslate-x/flags/gr.png';
const e={id:'98a3cc20-0369-469a-b885-9e1d6f070f92',name:'Giannis Ploutarhos',slug:'giannis-ploutarhos-athens',entity_type:'artist',website:'https://yannis-ploutarchos.gr',publish_status:'published',moderation_status:'clean',profile:{_enrich:{source_url:'https://yannis-ploutarchos.gr',photo_url:flag,photo_urls:[flag]}}};
test('translation flags are excluded from machine media without excluding real Greek-flag photos',()=>{assert.equal(machineImage(flag),null);assert.equal(machineImage('https://example.test/photos/greek-flag.jpg'),'https://example.test/photos/greek-flag.jpg');assert.equal(profileMedia({owner_content:{photo_url:flag}},{}).hero,flag);});
test('reviewed artist gets actual portrait and provider connection instead of translation flag',()=>{const d=musicHomeContent(e);assert.match(d.portrait,/spotifycdn/);assert.match(d.spotify,/152y903Cqyk9GVl6amOtuD/);assert.equal(d.gallery.length,0);assert.match(d.youtube,/Toth_4OkO5U/);});
test('reviewed defaults respect owner removals, changed identity and source quarantine',()=>{const d=musicHomeContent({...e,owner_content:{photo_url:null,social_links:null,profile:{photos:null,spotify_url:null,youtube_url:null}}});assert.equal(d.portrait,'');assert.equal(d.spotify,'');assert.equal(d.youtube,'');assert.deepEqual(d.gallery,[]);for(const x of[{...e,name:'Another person'},{...e,id:'11111111-1111-4111-8111-111111111111'},{...e,profile:{_enrich:{...e.profile._enrich,identity_scope:'organization'}}}]){const xdata=musicHomeContent(x);assert.equal(xdata.spotify,'');assert.equal(xdata.portrait,'');}});

test('reviewed portrait wins over unreviewed crawler photo while explicit owner still wins',()=>{const d=musicHomeContent({...e,profile:{_enrich:{...e.profile._enrich,photo_url:'https://yannis-ploutarchos.gr/arx4.jpg'}}});assert.match(d.portrait,/spotifycdn/);const own=musicHomeContent({...e,owner_content:{photo_url:'https://owner.example/portrait.jpg'}});assert.equal(own.portrait,'https://owner.example/portrait.jpg');});
