import test from'node:test';import assert from'node:assert/strict';import{musicHomeContent,renderMusicHome}from'../../api/_music-home.js';
const e={id:'48162031-673e-491d-ba63-3e502dabf3fd',entity_type:'artist',name:'Anna Vissi',slug:'anna-vissi-athens-481620',website:'https://www.annavissilive.com/',profile:{}};
const profile={merch:'https://shop.annavissilive.com/',releases:[{title:'A recording',date:'2026-10-02',url:'https://listen.example/release'}],tour:[{title:'A show at the venue',date:'2099-03-20',url:'https://tickets.example/show'}]};
test('actual persisted owner fields project source-neutral rows without invented metadata',()=>{for(const owner of[false,true]){const row={...e,profile,...(owner?{owner_content:{profile}}:{})},a=musicHomeContent(row);assert.equal(a.shop_url,profile.merch);assert.deepEqual(a.owner_releases,profile.releases);assert.deepEqual(a.owner_shows,profile.tour);assert.deepEqual(a.releases,[]);assert.deepEqual(a.shows,[]);for(const template of['atelier','concierge','table','parea']){const h=renderMusicHome(row,{template});assert.match(h,/A recording/);assert.match(h,/A show at the venue/);assert.match(h,/Listen on provider/);assert.doesNotMatch(h,/Keep the date/);}}});
test('actual merch field clears imported store; legacy shop_url remains supported',()=>{const row={...e,profile:{_enrich:{source_url:e.website,shop_url:profile.merch}}};for(const value of[null,'','javascript:alert(1)'])assert.equal(musicHomeContent({...row,owner_content:{profile:{merch:value}}}).shop_url,'');assert.equal(musicHomeContent({...row,profile:{shop_url:profile.merch}}).shop_url,profile.merch);});
test('explicit empty/null/invalid owner collection suppresses curated source defaults',()=>{const row={...e,id:'a558f28d-6c8f-4079-9730-838f483867fc',website:'https://www.georgedalaras.com/'};for(const value of[[],null,{},'bad']){const a=musicHomeContent({...row,owner_content:{profile:{releases:value,tour:value}}});assert.deepEqual(a.owner_releases,[]);assert.deepEqual(a.owner_shows,[]);assert.deepEqual(a.releases,[]);assert.deepEqual(a.shows,[]);assert.equal(a.programme,'');}});
test('unsafe/blank rows rejected, dates not repaired and past/invalid shows absent',()=>{const row={...e,owner_content:{profile:{releases:[{title:'unsafe',url:'javascript:alert(1)'},{title:'',url:'https://safe.example/'}],tour:[{title:'Past show',date:'2020-01-01',url:'https://safe.example/'},{title:'Invalid day',date:'2099-02-31',url:'https://safe.example/'}]}}};const h=renderMusicHome(row);assert.equal(musicHomeContent(row).owner_releases.length,0);assert.doesNotMatch(h,/<h3>Past show|<h3>Invalid day/);assert.match(h,/No upcoming dated shows/);});

test('concierge horizon agrees with published owner dates and sparse clear',()=>{const h=renderMusicHome({...e,owner_content:{profile}},{template:'concierge'});assert.doesNotMatch(h,/No upcoming dates verified/);assert.match(h,/class="hero-date"[^]*A show at the venue/);const cleared=renderMusicHome({...e,owner_content:{profile:{tour:null}}},{template:'concierge'});assert.match(cleared,/No upcoming dates verified/);});

test('owner catalogue never overrides explicitly hidden design section',()=>{const h=renderMusicHome({...e,owner_content:{profile}},{template:'concierge',hidden_sections:['offerings']});assert.doesNotMatch(h,/id="offerings"/);assert.doesNotMatch(h,/href="#offerings"/);assert.match(h,/id="calendar"/);});
