import test from 'node:test';
import assert from 'node:assert/strict';
import {musicHomeContent,renderMusicHome} from '../../api/_music-home.js';
const entity={id:'11111111-1111-4111-8111-111111111111',name:'Test Artist',slug:'test-artist',entity_type:'artist',website:'https://label.example/artists/test/',profile:{_enrich:{source_url:'https://label.example/artists/test/',source_kind:'label_artist_profile',description:'Source-reviewed artist biography.',email:'office@label.example',phone:'+302100000000'}}};
test('bound label artist source is attributed as label and cannot become artist booking office',()=>{const d=musicHomeContent({...entity,email:'office@label.example',phone:'+302100000000'});assert.equal(d.source_label,'Record label artist page');assert.equal(d.email,'');assert.equal(d.phone,'');const html=renderMusicHome(entity);assert.match(html,/Record label artist page/);assert.doesNotMatch(html,/mailto:office@label.example/);assert.match(html,/booking contact has not been verified/);});
test('release attribution requires matching source path and never trusts arbitrary crawler label',()=>{const release=musicHomeContent({...entity,profile:{_enrich:{...entity.profile._enrich,source_kind:'label_release_article',source_label:'Verified official owner'}}});assert.equal(release.source_label,'Record label release page');const mismatch=musicHomeContent({...entity,profile:{_enrich:{...entity.profile._enrich,source_url:'https://label.example/other-artist/'}}});assert.equal(mismatch.source_label,'Artist website');assert.doesNotMatch(renderMusicHome({...entity,profile:{_enrich:{...entity.profile._enrich,source_url:'https://label.example/other-artist/'}}}),/Source-reviewed artist biography/);});
test('published artist email produces coherent enquiry copy without an unsupported verification promise',()=>{const e={...entity,website:'https://artist.example/',profile:{_enrich:{source_url:'https://artist.example/',email:'booking@artist.example'}}};const html=renderMusicHome(e);assert.match(html,/mailto:booking@artist.example/);assert.match(html,/email the artist’s team using the published contact/);assert.doesNotMatch(html,/booking contact has not been verified/);});
test('owner booking email, explicit clears and owner website precedence survive label source protections',()=>{const own={...entity,owner_content:{email:'manager@artist.example',website:entity.website}};assert.equal(musicHomeContent(own).email,'manager@artist.example');assert.equal(musicHomeContent(own).source_label,'Artist website');assert.equal(musicHomeContent({...entity,owner_content:{profile:{booking_email:'book@artist.example'}}}).email,'book@artist.example');const clear={...entity,owner_content:{email:null,profile:{booking_email:null}}};assert.equal(musicHomeContent(clear).email,'');assert.doesNotMatch(renderMusicHome(clear),/mailto:/);assert.match(renderMusicHome(clear),/booking contact has not been verified/);});
test('sparse artist keeps honest no-contact state without source-label invention',()=>{const e={...entity,website:null,profile:{}};assert.equal(musicHomeContent(e).email,'');assert.match(renderMusicHome(e),/booking contact has not been verified/);assert.doesNotMatch(renderMusicHome(e),/Record label artist page/);});
