import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import vm from'node:vm';import{verticalFor,profileForVertical}from'../../api/_verticals.js';
const context={};vm.runInNewContext(readFileSync(new URL('../../assets/suite/_vertical-forms.js',import.meta.url),'utf8'),context);const F=context.ZoiVerticalForms;
const artist={entity_type:'artist',category_slug:'media-creators',name:'QA Hellenic Quartet'};
test('artist editor and public renderer select music and publish actual profile fields',()=>{
 assert.equal(F.fieldsFor(artist.entity_type,artist.category_slug).key,'music');
 const v=verticalFor(artist).v;assert.equal(v.key,'music');
 const profile={spotify_url:'https://open.spotify.com/artist/abc123',booking_email:'book@example.test',booking_name:'Agent',press_kit_url:'https://example.test/press.pdf',merch:'https://example.test/shop',releases:[{title:'New Album',date:'2026-10-01',url:'https://open.spotify.com/album/abc123'}],tour:[{title:'Athens show',date:'2026-10-10',url:'https://example.test/tickets'}],embeds:[{title:'Album player',url:'https://open.spotify.com/album/abc123'}]};
 const saved=F.clean(profile);const p=profileForVertical(v,saved);const html=v.sections(artist,p);
 for(const text of ['New Album','Athens show','book@example.test','https://example.test/press.pdf','https://open.spotify.com/embed/album/abc123'])assert.ok(html.includes(text));assert.equal(v.actions(artist,p).find(a=>a.label==='Merch').href,'https://example.test/shop');
});
test('Spotify playlist and locale links embed; untrusted origins and executable URLs do not',()=>{const v=verticalFor(artist).v;const html=v.sections(artist,{embeds:[{url:'https://open.spotify.com/intl-el/playlist/abc123'},{url:'https://open.spotify.com.evil.test/track/abc'},{url:'javascript:alert(1)'},{url:'https://user:password@open.spotify.com/track/abc'}]});assert.match(html,/embed\/playlist\/abc123/);assert.equal((html.match(/<iframe/g)||[]).length,1);assert.ok(!html.includes('evil.test'));});
test('explicit owner clear suppresses enrichment and nested legacy music values prefill',()=>{const fields=F.fieldsFor('artist','').fields;const p=F.partition({spotify_url:null,booking:{email:'agent@example.test'},_enrich:{spotify_url:'https://open.spotify.com/artist/old'}},fields);assert.equal(p.own.spotify_url,null);assert.equal(p.own.booking_email,'agent@example.test');assert.ok(!p.fromWebsite.includes('spotify_url'));const v=verticalFor(artist).v;const normalized=profileForVertical(v,{booking:{email:'old@example.test'},booking_email:null});assert.equal(normalized.booking.email,'');});
test('cleared owned profile values are sent as null rather than omitted from merge patches',()=>{const src=readFileSync(new URL('../../assets/suite/_vertical-ui.js',import.meta.url),'utf8');const start=src.indexOf('      read: function () {');const end=src.indexOf('\n      }\n    };',start);const read=vm.runInNewContext('('+src.slice(start,end+8).replace('      read: ','').trim()+')',{F,part:{own:{booking_email:'old@example.test'}},opts:{profile:{booking_email:'old@example.test'}},controls:[{f:{k:'booking_email'},ctl:{value:''},isAccepted:()=>true}]});assert.equal(read().booking_email,null);});
