import test from 'node:test';import assert from 'node:assert/strict';import{createOperationsRecovery,operationsDenied}from'../../assets/operations/recovery.mjs';
const actor='11111111-1111-4111-8111-111111111111',workspace='22222222-2222-4222-8222-222222222222',request='33333333-3333-4333-8333-333333333333',record='44444444-4444-4444-8444-444444444444';
function fixture(){let value=null,current=true,handler=async()=>{throw Error('lost')};const calls=[],storage={load:async()=>structuredClone(value),save:async v=>value=structuredClone(v),clear:async()=>value=null};const make=()=>createOperationsRecovery({actor,workspace,storage,current:()=>current,nonce:()=>request,call:async(n,p)=>{calls.push([n,structuredClone(p)]);return handler(n,p);}});return{make,storage,calls,get value(){return value},set value(v){value=v},set current(v){current=v},set handler(v){handler=v}};}
const receipt=(action='save')=>({ok:true,state:'saved',workspace_id:workspace,request_id:request,action,record_id:record,kind:'company',version:1});
test('lost new save blocks replacement, retries immutable payload, persists no private form',async()=>{const f=fixture(),r=f.make();await r.load();const args={p_kind:'company',p_data:{title:'PRIVATE'},p_expected_version:0};await assert.rejects(r.send('save',args));args.p_data.title='changed';assert.equal(JSON.stringify(f.value).includes('PRIVATE'),false);await assert.rejects(r.send('save',args));f.handler=async()=>receipt();await r.recover('retry');assert.deepEqual(f.calls[0],f.calls[1]);assert.equal(f.value,null);});
test('reload checks nonce without payload; missing does not unlock; matching cancelled proof does',async()=>{const f=fixture(),r=f.make();await r.load();await assert.rejects(r.send('save',{p_expected_version:0}));const next=f.make();await next.load();assert.equal(next.state().payload,false);await assert.rejects(next.recover('retry'));f.handler=async()=>({...receipt(),state:'missing'});await next.recover('check');assert.ok(next.state().marker);f.handler=async()=>({...receipt(),state:'cancelled',request_id:record});await assert.rejects(next.recover('cancel'));assert.ok(next.state().marker);f.handler=async()=>({...receipt(),state:'cancelled'});await next.recover('cancel');assert.equal(f.value,null);});
test('wrong scope/action/entity/version receipts retain recovery',async()=>{for(const patch of [{workspace_id:actor},{request_id:record},{action:'archive'},{record_id:actor},{version:2},{kind:'task'}]){const f=fixture(),r=f.make();await r.load();f.handler=async()=>({...receipt(),...patch});await assert.rejects(r.send('save',{p_id:record,p_kind:'company',p_expected_version:0}));assert.ok(f.value);}});
test('save success followed by readback failure blocks dispatch and next replacement',async()=>{const f=fixture(),r=f.make();await r.load();f.storage.load=async()=>{throw Error('unavailable')};await assert.rejects(r.send('save',{}));await assert.rejects(r.send('save',{}));assert.equal(f.calls.length,0);assert.equal(r.state().ready,false);assert.ok(f.value);});
test('scope change during readback cannot dispatch or acknowledge',async()=>{const f=fixture(),r=f.make();await r.load();const original=f.storage.load;f.storage.load=async()=>{const v=await original();f.current=false;return v;};await assert.rejects(r.send('save',{}));assert.equal(f.calls.length,0);assert.ok(f.value);});
test('corrupt marker cannot be silently replaced and payload drops retain nonce',async()=>{const f=fixture();f.value={actor,workspace,request,action:'save',title:'PRIVATE'};const r=f.make();await assert.rejects(r.load());await assert.rejects(r.send('save',{}));const g=fixture(),p=g.make();await p.load();await assert.rejects(p.send('archive',{p_id:record,p_expected_version:0}));p.dropPayload();assert.ok(g.value);assert.equal(p.state().payload,false);});
test('authoritative access denial distinct from transient failure and domain conflict',()=>{for(const e of[Error('not_authorized'),Error('insufficient_permission'),Error('ops_permission_denied'),{status:403},{code:'42501'}])assert.equal(operationsDenied(e),true);for(const e of[Error('version_conflict'),{status:502},Error('network')])assert.equal(operationsDenied(e),false);});
