import test from 'node:test';
import assert from 'node:assert/strict';
import {privateScope} from '../../assets/organizations/private-scope.mjs';
const actor='10000000-0000-4000-8000-000000000001',ws='20000000-0000-4000-8000-000000000001';
function fixture(){let release;const pending=new Promise(r=>release=r),calls=[];const root={childNodes:[],replaceChildren(){this.textContent="";},isConnected:true,textContent:'private roster'},ctx={ws},win=new EventTarget(),doc=new EventTarget();doc.body={};const C={auth:{load:()=>({user_id:actor}),ensureFresh:()=>pending},api:{rpc:async(name,args,options)=>{if(options.auth==='require')await pending;calls.push({name,args,options});return{ok:true};}}};const scope=privateScope(root,C,ctx,{win,doc,Observer:class{observe(){}disconnect(){}takeRecords(){return[];}},every:()=>1,stop:()=>{}});return{root,ctx,scope,release,calls};}
for(const operation of ['youth_family','youth_program_save','organization_groups_list'])test(`${operation} does not send after workspace changes during refresh`,async()=>{const f=fixture(),promise=f.scope.rpc(operation,{p_workspace:ws});f.ctx.ws='20000000-0000-4000-8000-000000000002';f.release(true);await assert.rejects(promise,/changed/);assert.equal(f.calls.length,0);});
test('detached surface cannot send its queued request',async()=>{const f=fixture(),p=f.scope.rpc('youth_family',{});f.root.isConnected=false;f.release(true);await assert.rejects(p,/changed/);assert.equal(f.calls.length,0);});
test('unchanged scope preserves exact request and does not requeue authentication',async()=>{const f=fixture(),args={p_workspace:ws,p_request:'request'},p=f.scope.rpc('youth_program_save',args);f.release(true);assert.deepEqual(await p,{ok:true});assert.deepEqual(f.calls,[{name:'youth_program_save',args,options:{auth:'prefer'}}]);});
test('failed refresh clears private state and sends nothing',async()=>{const f=fixture(),p=f.scope.rpc('youth_family',{});f.release(false);await assert.rejects(p,/sign in/i);assert.equal(f.calls.length,0);assert.doesNotMatch(f.root.textContent,/private roster/);});
