import test from'node:test';import assert from'node:assert/strict';import{organizationActor,privateScope,youthPendingGuard}from'../../assets/organizations/private-scope.mjs';
const actor='10000000-0000-4000-8000-000000000001',other='10000000-0000-4000-8000-000000000002',ws='20000000-0000-4000-8000-000000000001',request='30000000-0000-4000-8000-000000000001';
function setup(){let account=actor,respond=async()=>({ok:true}),calls=0;const root={isConnected:true,textContent:'PRIVATE CHILD',__organizationScope:null},win=new EventTarget(),doc=new EventTarget();doc.body={};const ctx={ws},C={auth:{load:()=>({user_id:account}),ensureFresh:async()=>true},api:{rpc:async(...args)=>{calls++;return respond(...args)}}};let interval;const scope=privateScope(root,C,ctx,{win,doc,Observer:class{observe(){}disconnect(){}},every:fn=>(interval=fn,1),stop:()=>{}});return{scope,root,win,ctx,change:x=>account=x,response:fn=>respond=fn,calls:()=>calls,tick:()=>interval()};}
test('real auth event immediately clears private DOM and permanently fences old callbacks',async()=>{const f=setup();f.change(other);f.win.dispatchEvent(new Event('zoi:auth-change'));assert.doesNotMatch(f.root.textContent,/PRIVATE CHILD/);await assert.rejects(f.scope.rpc('youth_child_save',{}),/changed/);assert.equal(f.calls(),0);f.change(actor);assert.equal(f.scope.current(),false);});
test('workspace is checked before writes even before polling',async()=>{const f=setup();f.ctx.ws='different';await assert.rejects(f.scope.rpc('youth_program_save',{}),/changed/);assert.equal(f.calls(),0);assert.doesNotMatch(f.root.textContent,/PRIVATE CHILD/);});
test('late read cannot return old records after account change; role denial clears old UI',async()=>{const f=setup();f.response(async()=>{f.change(other);return{secret:'OLD FAMILY'}});await assert.rejects(f.scope.rpc('youth_family',{}),/changed/);const g=setup();g.response(async()=>{throw Error('not_authorized')});await assert.rejects(g.scope.rpc('youth_operator',{}),/not_authorized/);assert.doesNotMatch(g.root.textContent,/PRIVATE CHILD/);});
function pending(){const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},guard=youthPendingGuard(storage,{actor,workspace:null});return{guard,storage,map};}
const spec={name:'youth_child_save',args:{p_request:request,p_id:null,p_name:'PRIVATE CHILD NAME',p_expected_version:0,p_archived:false},guardian:actor};
test('pending marker persists scope/nonce without sensitive fields and blocks a new nonce after remount',()=>{const f=pending();f.guard.begin(spec);const raw=[...f.map.values()][0];assert.doesNotMatch(raw,/PRIVATE CHILD NAME|p_name|guardian|contact|email/);const remount=youthPendingGuard(f.storage,{actor});assert.equal(remount.read().request,request);assert.throws(()=>remount.begin({...spec,args:{...spec.args,p_request:'30000000-0000-4000-8000-000000000002'}}),/Resolve/);assert.deepEqual(remount.begin(spec),f.guard.read());assert.equal(youthPendingGuard(f.storage,{actor:other}).read(),null);});
test('wrong workspace and unavailable persistence prevent writes; only matching receipt clears marker',()=>{const f=pending();assert.throws(()=>f.guard.begin({...spec,args:{...spec.args,p_workspace:ws}}),/workspace/);f.guard.begin(spec);assert.throws(()=>f.guard.confirmed({...spec,args:{...spec.args,p_request:other}}),/changed/);assert.ok(f.guard.read());f.guard.confirmed(spec);assert.equal(f.guard.read(),null);f.storage.setItem=()=>{};assert.throws(()=>f.guard.begin(spec),/Nothing was sent/);});
test('only a recognized complete server refusal resolves a marker; network text or unknown HTTP stays uncertain',()=>{const f=pending();f.guard.begin(spec);assert.equal(f.guard.refused(spec,Error('version_conflict')),false);assert.ok(f.guard.read());assert.equal(f.guard.refused(spec,Object.assign(Error('upstream unknown'),{status:409})),false);assert.ok(f.guard.read());assert.equal(f.guard.refused(spec,Object.assign(Error('not_authorized'),{status:403})),false);assert.ok(f.guard.read());assert.equal(f.guard.refused(spec,Object.assign(Error('version_conflict'),{status:400}),true),true);assert.equal(f.guard.read(),null);});

const jwt=(sub,revision=1)=>'header.'+Buffer.from(JSON.stringify({sub,revision})).toString('base64url')+'.signature';
test('JWT-only identity works; contradictory or malformed token identity fails closed',()=>{let session={access_token:jwt(actor)};const C={auth:{load:()=>session}};assert.equal(organizationActor(C),actor);session={user_id:actor,access_token:jwt(other)};assert.equal(organizationActor(C),'');session={user_id:actor,access_token:'malformed'};assert.equal(organizationActor(C),'');session={user_id:actor,access_token:jwt('not-a-profile')};assert.equal(organizationActor(C),'');});
test('same-actor token refresh preserves private scope; contradictory JWT clears it before writes',async()=>{let session={user_id:actor,access_token:jwt(actor)},calls=0;const root={isConnected:true,textContent:'PRIVATE CHILD'},win=new EventTarget(),doc=new EventTarget();doc.body={};const C={auth:{load:()=>session},api:{rpc:async()=>{calls++;return{ok:true}}}};const scope=privateScope(root,C,{ws},{win,doc,Observer:class{observe(){}disconnect(){}},every:()=>1,stop:()=>{}});session={user_id:actor,access_token:jwt(actor,2)};win.dispatchEvent(new Event('zoi:auth-change'));assert.equal(scope.current(),true);assert.equal(root.textContent,'PRIVATE CHILD');session={user_id:actor,access_token:jwt(other)};win.dispatchEvent(new Event('zoi:auth-change'));assert.equal(scope.current(),false);assert.doesNotMatch(root.textContent,/PRIVATE CHILD/);await assert.rejects(scope.rpc('youth_family',{}),/changed/);assert.equal(calls,0);});
