import test from'node:test';import assert from'node:assert/strict';import{ownerHomeContent}from'../../api/_owner-home-content.js';import{musicHomeContent}from'../../api/_music-home.js';import{creatorHomeContent,renderCreatorCanonicalHome}from'../../api/_creator-home.js';import{eventHomeContent,renderEventCanonicalHome}from'../../api/_event-home.js';import{CREATOR}from'../../assets/homes/templates/creator/data.mjs';import{PARKVIEW}from'../../assets/homes/templates/events/data.mjs';import{ARTIST_SOURCES}from'../../assets/homes/templates/music/sources.mjs';import{proposal}from'../../assets/homes/templates/creator/model.mjs';
const entity=(base,type,owner_content)=>({id:base.id,name:base.name,slug:base.slug,website:base.website,entity_type:type,owner_content});
test('unproven base fields and contaminated enrichment cannot override reviewed identity',()=>{const e={...entity(CREATOR,'creator'),description:'Wrong organization',photo_url:'https://wrong.org/org.jpg',profile:{_enrich:{photo_url:'https://wrong.org/org.jpg',social:{instagram:'https://wrong.org'}}}};const actual=creatorHomeContent(e);assert.equal(actual.bio,CREATOR.bio);assert.equal(actual.portrait,CREATOR.portrait);assert.deepEqual(actual.socials,CREATOR.socials);assert.equal(creatorHomeContent({...e,id:'different'}),null)});
test('actual projected owner picture bio and social clear override source defaults in rendered output',()=>{const e=entity(CREATOR,'creator',{description:'Owner <bio>',photo_url:'https://images.example.org/new.jpg',social_links:{},email:null});const content=creatorHomeContent(e);assert.equal(content.bio,'Owner <bio>');assert.equal(content.portrait,'https://images.example.org/new.jpg');assert.deepEqual(content.socials,[]);const html=renderCreatorCanonicalHome(e);assert(html.includes('Owner &lt;bio&gt;'));assert(html.includes('https://images.example.org/new.jpg'));assert(!html.includes(CREATOR.portrait));assert(!html.includes('href="'+CREATOR.socials[0].url+'"'));const result=proposal({kind:'Content collaboration',idea:'A meaningful owner collaboration idea.'},content);assert.equal(result.email,null);assert(result.body.includes('collaboration'))});
test('explicit image phone bio clears stay clear without empty image/tel requests',()=>{const e=entity(PARKVIEW,'venue',{description:null,photo_url:null,phone:null,social_links:{}}),c=eventHomeContent(e),html=renderEventCanonicalHome(e);assert.equal(c.hero,'');assert.equal(c.intro,'');assert(!html.includes('src=""'));assert(!html.includes('href="tel:"'));assert(!html.includes(PARKVIEW.hero));const creator=renderCreatorCanonicalHome(entity(CREATOR,'creator',{photo_url:null}));assert(creator.includes('Portrait not provided'));assert(!creator.includes('src=""'))});
test('music owner fields use presence semantics and remove stale portrait srcsets',()=>{const base=Object.values(ARTIST_SOURCES)[0],c=musicHomeContent(entity(base,'artist',{description:'Owner biography',photo_url:'https://images.example.org/new.jpg',social_links:{},profile:{press:null,spotify_url:null,youtube_url:null,photos:[]}}));assert.equal(c.story,'');assert.equal(c.owner_description,true);assert.equal(c.spotify,'');assert.equal(c.youtube,'');assert.equal(c.video_playlist,'');assert.deepEqual(c.portrait_sources,[]);assert.deepEqual(c.gallery,[])});
test('unsafe owner URLs are suppressed and exact source identity guard remains required',()=>{const c=ownerHomeContent(CREATOR,{owner_content:{photo_url:'javascript:alert(1)',social_links:{instagram:'javascript:alert(1)'}}},'creator');assert.equal(c.portrait,'');assert.deepEqual(c.socials,[]);assert.equal(creatorHomeContent({...entity(CREATOR,'creator'),website:'https://wrong.org'}),null)});

import {profileMedia} from '../../api/_profile-media.js';
test('shared media projection preserves explicit owner hero/gallery clearing across families',()=>{const e={photo_url:'https://old.org/photo.jpg',owner_content:{photo_url:null,profile:{photos:[]}},profile:{_enrich:{}}};const p={photo_url:'https://source.org/photo.jpg',photos:['https://source.org/gallery.jpg']};assert.deepEqual(profileMedia(e,p),{hero:null,logo:null,gallery:[]});e.owner_content.photo_url='https://owner.org/new.jpg';assert.equal(profileMedia(e,p).hero,'https://owner.org/new.jpg');});
