import{test}from'node:test';import assert from'node:assert/strict';import{prioritize,VERSION}from'../../assets/priorities/engine.mjs';import{loadSources}from'../../assets/priorities/view.mjs';
const now=Date.parse('2026-10-01T12:00:00Z');const id=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');const workspace=id(1);const source=(records,other={})=>({ok:true,fetchedAt:new Date(now).toISOString(),records,...other});const empty=()=>({operations:source([]),publishing:source([]),bookings:source([],{slots:[]})});
test('priority ranking is deterministic, explainable and capped with known record evidence',()=>{const sources=empty();sources.operations.records=[{id:id(2),workspace_id:workspace,kind:'task',status:'blocked',title:'Prepare campaign',due_at:'2026-10-01T06:00:00Z'}];sources.publishing.records=[{id:id(3),workspace_id:workspace,status:'failed',body:'Real draft',scheduled_at:'2026-10-01T10:00:00Z'}];const a=prioritize({workspace,now,sources});const b=prioritize({workspace,now,sources});assert.deepEqual(a,b);assert.equal(a.version,VERSION);assert.equal(a.issues[0].score,61);for(const issue of a.issues){assert.equal(issue.score,Object.values(issue.components).reduce((x,y)=>x+y));assert.ok(issue.score<=100);assert.ok(issue.facts.length);assert.match(issue.href,/^\/social\//);}assert.ok(!JSON.stringify(a).includes('engagement_rate'));});
test('cross-workspace, stale and malformed sources do not become reassuring empty success',()=>{const sources=empty();sources.operations.records=[{id:id(2),workspace_id:id(99),kind:'task',status:'blocked'}];sources.publishing.fetchedAt=new Date(now-6*60000).toISOString();sources.bookings={ok:false,error:'workspace_permission_denied',records:[],fetchedAt:new Date(now).toISOString()};const report=prioritize({workspace,now,sources});assert.equal(report.complete,false);assert.equal(report.coverage.filter(c=>c.available).length,0);assert.equal(report.issues.length,0);});
test('completed and archived tasks, successful posts and future deadlines do not create issues',()=>{const sources=empty();sources.operations.records=[{id:id(2),workspace_id:workspace,kind:'task',status:'completed',due_at:'2020-01-01'},{id:id(3),workspace_id:workspace,kind:'task',status:'blocked',archived_at:'2026-10-01'},{id:id(4),workspace_id:workspace,kind:'task',status:'open',due_at:'2026-11-01'}];sources.publishing.records=[{id:id(5),workspace_id:workspace,status:'published',scheduled_at:'2020-01-01'}];assert.equal(prioritize({workspace,now,sources}).issues.length,0);});
test('booking actions aggregate by slot and never expose customer contact data or invent payment outcomes',()=>{const sources=empty();sources.bookings=source([{id:id(5),workspace_id:workspace,slot_id:id(4),status:'confirmed',party_size:2,customer_email:'private@example.test',customer_name:'Private Person'},{id:id(6),workspace_id:workspace,slot_id:id(4),status:'confirmed',party_size:1}],{slots:[{id:id(4),workspace_id:workspace,service_name:'Hair appointment',starts_at:'2026-10-01T09:00:00Z',ends_at:'2026-10-01T10:00:00Z'}]});const report=prioritize({workspace,now,sources});assert.equal(report.issues.length,1);assert.match(report.issues[0].action,/actual booking outcomes/);assert.ok(!JSON.stringify(report).includes('Private Person'));assert.ok(!JSON.stringify(report).includes('private@example'));assert.ok(!JSON.stringify(report).includes('paid'));});
test('duplicate records produce one action and delayed publishing has a 15 minute grace',()=>{const sources=empty();const task={id:id(2),workspace_id:workspace,kind:'task',status:'blocked'};sources.operations.records=[task,task];sources.publishing.records=[{id:id(3),workspace_id:workspace,status:'scheduled',scheduled_at:'2026-10-01T11:50:00Z'},{id:id(4),workspace_id:workspace,status:'scheduled',scheduled_at:'2026-10-01T11:00:00Z'}];const r=prioritize({workspace,now,sources});assert.equal(r.issues.length,2);});
test('source loader verifies receipts and retains explicit partial permission errors',async()=>{const calls=[];const C={api:{rpc:async(name,args,opts)=>{calls.push({name,args,opts});if(name==='ops_records_list')return{ok:true,records:[]};if(name==='social_list_posts')return[];throw Error('workspace_permission_denied');}}};const sources=await loadSources(C,workspace,now);assert.equal(sources.operations.ok,true);assert.equal(sources.bookings.ok,false);assert.match(sources.bookings.error,/permission/);assert.equal(calls.length,3);assert.ok(calls.every(c=>c.opts.auth==='require'));});

test('foreign booking slots invalidate coverage and repeated booking receipts do not inflate coordination',()=>{const sources=empty();sources.bookings.slots=[{id:id(8),workspace_id:id(99)}];assert.equal(prioritize({workspace,now,sources}).coverage.find(c=>c.name==='bookings').available,false);const b={id:id(7),workspace_id:workspace,slot_id:id(8),status:'confirmed',party_size:2};sources.bookings=source([b,b],{slots:[{id:id(8),workspace_id:workspace,starts_at:'2026-10-01T13:00:00Z',ends_at:'2026-10-01T14:00:00Z'}]});const result=prioritize({workspace,now,sources});assert.equal(result.issues[0].components.coordination,2);assert.match(result.issues[0].facts[0],/1 confirmed booking/);});
