import test from 'node:test';import assert from 'node:assert/strict';
import {validateOwnerRequest,OWNER_CODE_FILES,ownerQaErrorClass} from '../../scripts/auth-qa/private-owner-ci.mjs';
import {ownerRequestFence} from '../../scripts/auth-qa/private-owner-policy.mjs';
import {ownerSavePayload,OWNER_QA,OWNER_DESIGN} from '../../scripts/auth-qa/private-owner-flow.mjs';import {QA,permittedRequest} from '../../scripts/auth-qa/session.mjs';
const now=Date.now(),env={GITHUB_REPOSITORY:'pangaon/zoi-city',GITHUB_REF:'refs/heads/main',GITHUB_RUN_ATTEMPT:'1',GITHUB_EVENT_NAME:'push',GITHUB_SHA:'b'.repeat(40)};
const hashes=Object.fromEntries(OWNER_CODE_FILES.map(p=>[p,'c'.repeat(64)]));
const request={purpose:'private-owner-edit-read-preview',fixture_id:OWNER_QA.listing,request_id:OWNER_QA.request,user_id:QA.user,profile_id:QA.profile,workspace_id:QA.workspace,issued_at:new Date(now-1000).toISOString(),expires_at:new Date(now+60000).toISOString(),base_sha:'a'.repeat(40),code_sha256:hashes};
const evidence={parent:request.base_sha,head:env.GITHUB_SHA,diff:'A\tops/private-owner-qa-request.json',hashes,event:{before:request.base_sha,after:env.GITHUB_SHA,ref:env.GITHUB_REF,repository:{full_name:env.GITHUB_REPOSITORY},forced:false,created:false,deleted:false}};
const post=(path,body,origin=QA.base)=>({method:'POST',url:origin+path,postData:JSON.stringify(body)});
test('requires exact reviewed code, one request-only push, main and first attempt',()=>{validateOwnerRequest(env,request,evidence,now);for(const [e,r,v]of[[{...env,GITHUB_RUN_ATTEMPT:'2'},request,evidence],[{...env,GITHUB_EVENT_NAME:'workflow_dispatch'},request,evidence],[env,{...request,fixture_id:'other'},evidence],[env,request,{...evidence,diff:evidence.diff+'\nM\tproduct.js'}],[env,request,{...evidence,hashes:{}}]])assert.throws(()=>validateOwnerRequest(e,r,v,now));});
test('expiry refuses new work but gives cleanup only a bounded grace period',()=>{assert.throws(()=>validateOwnerRequest(env,request,evidence,now+61000));validateOwnerRequest(env,request,evidence,now+61000,true);assert.throws(()=>validateOwnerRequest(env,request,evidence,now+3660001,true));});
test('cannot save before version capture; rejects changed contacts, fixture, request and duplicate write',()=>{const f=ownerRequestFence(),p=ownerSavePayload('a'.repeat(32)),call=b=>post('/rest/v1/rpc/home_content_save',b);assert.equal(f.allow(call(p)),false);f.arm('a'.repeat(32));for(const wrong of[{...p,p_listing:'other'},{...p,p_request:'other'},{...p,p_base:{...p.p_base,email:'qa@example.invalid'}},{...p,p_profile:{menu:[]}}])assert.equal(f.allow(call(wrong)),false);assert.equal(f.allow(call(p)),true);assert.equal(f.allow(call(p)),false);assert.equal(f.counts().writes,1);});
test('never permits publication, intake, claim, provider calls or legacy writers',()=>{const f=ownerRequestFence();f.arm('a'.repeat(32));for(const fn of['home_design_change','bizpage_save','bizpage_save_profile','intake_submit','zoi_claim_entity'])assert.equal(f.allow(post('/rest/v1/rpc/'+fn,{p_workspace:QA.workspace,p_listing:OWNER_QA.listing})),false);assert.equal(f.allow(post('/send',{},'https://example.invalid')),false);});
test('preview only after exact save, correct design and once',()=>{const f=ownerRequestFence(),p={workspace:QA.workspace,listing:OWNER_QA.listing,design:OWNER_DESIGN},call=b=>post('/api/home-preview',b,QA.site);assert.equal(f.allow(call(p)),false);f.arm('a'.repeat(32));f.allow(post('/rest/v1/rpc/home_content_save',ownerSavePayload('a'.repeat(32))));assert.equal(f.allow(call({...p,listing:'other'})),false);assert.equal(f.allow(call(p)),true);assert.equal(f.allow(call(p)),false);});
test('existing readonly fence still rejects all content writes',()=>{assert.equal(permittedRequest(post('/rest/v1/rpc/home_content_save',ownerSavePayload('a'.repeat(32))),OWNER_QA.listing),false);});

test('diagnostics expose only fixed known error classes, never response bodies, tokens or causes',()=>{
 for(const key of ['qa_ci_scope_guard','qa_request_guard','qa_push_guard','qa_code_guard','qa_management_credential_missing','qa_sql_unconfirmed','qa_sql_receipt_unconfirmed','qa_stage','qa_attempt_guard'])assert.equal(ownerQaErrorClass(new Error(key)),key);
 for(const error of [new Error('Bearer secret-token'),new Error('qa_request_guard: private payload'),new Error('select * from private_table'),new Error('qa_code_guard\nsecret'),{message:'qa_request_guard'},'qa_request_guard',null])assert.equal(ownerQaErrorClass(error),'qa_unclassified_error');
 const hostile=new Error();Object.defineProperty(hostile,'message',{get(){throw Error('sensitive getter')}});assert.equal(ownerQaErrorClass(hostile),'qa_unclassified_error');assert.equal(ownerQaErrorClass(new Error('qa_request_guard',{cause:new Error('secret')})),'qa_request_guard');
});
test('exact 30-minute request passes and 30 minutes plus one millisecond remains rejected',()=>{const issued=new Date(now).toISOString();validateOwnerRequest(env,{...request,issued_at:issued,expires_at:new Date(now+1800000).toISOString()},evidence,now);assert.throws(()=>validateOwnerRequest(env,{...request,issued_at:issued,expires_at:new Date(now+1800001).toISOString()},evidence,now),/qa_request_guard/);});
