import {test} from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import vm from'node:vm';
function expose(file,names){const src=readFileSync(new URL('../../assets/suite/'+file,import.meta.url),'utf8');const context={URL};vm.runInNewContext(src.replace('  global.ZoiSuite =','  global.exposed={'+names+'};\n  global.ZoiSuite ='),context);return context.exposed;}
const bio=expose('bio.js','channelToLink,isHttpUrl');const biz=expose('bizpage.js','editableListings,normStatus,normContent');
test('connected bio links never manufacture handles from display names',()=>{assert.equal(bio.channelToLink({platform:'instagram',display_name:'Athens Cafe'}),null);assert.equal(bio.channelToLink({platform:'instagram',handle:'@athens'}).url,'https://instagram.com/athens');assert.equal(bio.channelToLink({platform:'linkedin',profile_url:'https://linkedin.com/company/cafe'}).url,'https://linkedin.com/company/cafe');});
test('bio URL validation rejects executable schemes and credential URLs',()=>{for(const s of ['javascript:alert(1)','https://','https://user:pass@site.test'])assert.equal(bio.isHttpUrl(s),false);assert.equal(bio.isHttpUrl('https://example.test/path'),true);});
test('business selection recognizes actual owned and approved claims response',()=>{const choices=biz.editableListings({owned:[{id:'a',name:'Owned'}],claims:[{listing_id:'b',status:'approved'},{listing_id:'c',status:'pending'},{listing_id:'a',status:'approved'}]});assert.deepEqual(Array.from(choices,x=>x.id),['a','b']);assert.equal(biz.normStatus(choices[0]).claimed,true);});
test('business socials retain enrichment while owner values override matching networks',()=>{const d=biz.normContent({profile:{_enrich:{social:{facebook:'https://facebook.com/real'}},social:{instagram:'https://instagram.com/old'}},social_links:{instagram:'https://instagram.com/owner'}});assert.equal(d.social.length,2);assert.equal(d.social.find(x=>x.platform==='instagram').url,'https://instagram.com/owner');});
const source=readFileSync(new URL('../../assets/suite/bizpage.js',import.meta.url),'utf8');
test('business save requires actual boolean receipt and captures detailed draft before first write',async()=>{
 const start=source.indexOf('    function doSave('),end=source.indexOf('    function finishSave',start);
 for(const response of [false,null,{},true]){let profileCalls=0;const notes={textContent:''};const state={status:{listingId:'id'},draft:{social:[]},vform:{read:()=>({notes:'snapshot'})}};const btn={setAttribute(){}};const save=vm.runInNewContext('('+source.slice(start,end).trim()+')',{state,scopeLive:()=>true,contentDirty:true,ws:'ws',ctx:{ws:'ws'},wrap:{querySelectorAll:()=>[]},firstStr:x=>x||'',assembleSocial:()=>({}),rpcWrite:async(fn)=>{if(fn==='bizpage_save_profile'){profileCalls++;return true;}return response;},finishSave(){},toast(){}});save(btn,notes);await new Promise(r=>setTimeout(r,0));assert.equal(profileCalls,response===true?1:0);assert.match(notes.textContent,response===true?/up to date/:/did not complete/);}
});

test('public bio filters unsafe URLs and distinguishes availability failures from missing pages',()=>{const html=readFileSync(new URL('../../b/index.html',import.meta.url),'utf8');const fn=html.slice(html.indexOf('function safeUrl('),html.indexOf('function slugFromPath'));const safe=vm.runInNewContext(fn+';safeUrl',{URL});assert.equal(safe('javascript:alert(1)'),null);assert.equal(safe('https://example.test'),'https://example.test/');assert.match(html,/Profile temporarily unavailable/);assert.match(html,/id=\"retryProfile\"/);assert.match(html,/links.filter\(l=>l&&l.label&&safeUrl\(l.url\)\)/);});
