import test from'node:test';import assert from'node:assert/strict';import{publicWidget,widgetHTML}from'../../api/_public-widget.js';
const id='98a3cc20-0369-469a-b885-9e1d6f070f92';const e={id,name:'Giannis Ploutarhos',slug:'giannis-ploutarhos-athens',entity_type:'artist',publish_status:'published',moderation_status:'clean',profile:{},website:'https://yannis-ploutarchos.gr'};
test('public exact identity only and whitelisted fields',()=>{const d=publicWidget({...e,secret:'private'},id);assert.equal(d.id,id);assert.ok(!('secret'in d));assert.equal(publicWidget({...e,marketplace_status:'hidden'},id),null);assert.equal(publicWidget({...e,moderation_status:'flagged'},id),null);assert.equal(publicWidget({...e,entity_type:'business'},id),null);assert.equal(publicWidget(e,'bad'),null);});
test('authoritative owner media clear suppresses reviewed playback',()=>{assert.ok(publicWidget(e,id).media);assert.equal(publicWidget({...e,profile:{owner_media:{version:1,items:[]}}},id).media,null);});
test('hidden media and offerings respected; markup safe',()=>{const d=publicWidget({...e,published_design:{ok:true,listing:id,version:1,design:{schema_version:1,template:'concierge',section_order:[],hidden_sections:['offerings','media'],copy:{},item_order:{offerings:[]}}}},id);assert.equal(d.media,null);const html=widgetHTML({...d,name:'<script>bad</script>',description:'"<img>'});assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>bad'));assert.ok(!html.includes('iframe'));});

import{widgetProfileURL,widgetEmbed}from'../../assets/widgets/model.mjs';
import handler from'../../api/widget.js';
import{readFileSync}from'node:fs';
test('public visibility must be affirmative',()=>{for(const change of[{publish_status:undefined},{moderation_status:undefined},{publish_status:'draft'},{id:'different'}])assert.equal(publicWidget({...e,...change},id),null);});
test('URL onboarding accepts canonical profiles only',()=>{assert.deepEqual(widgetProfileURL('https://www.zoi.city/event/concert?shared=1'),{type:'event',slug:'concert'});for(const url of['https://evil.com/event/concert','https://zoi.city/business/company','https://zoi.city/event/a%2Fb','https://user@zoi.city/event/concert','http://zoi.city/event/concert'])assert.throws(()=>widgetProfileURL(url));assert.ok(widgetEmbed({id,slug:'concert'}).code.includes('&amp;slug=concert'));assert.throws(()=>widgetEmbed({id:'bad',slug:'concert'}));});
test('widget endpoint resolver is public minimal and binds type and identity',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>({ok:true,json:async()=>({...e,secret:'never expose'})});const invoke=async query=>{const r={headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},send(v){this.body=v;return this}};await handler({method:'GET',query},r);return r};try{let r=await invoke({mode:'resolve',type:'artist',slug:e.slug});assert.equal(r.code,200);assert.deepEqual(Object.keys(JSON.parse(r.body)).sort(),['id','name','slug','type']);r=await invoke({mode:'resolve',type:'event',slug:e.slug});assert.equal(r.code,404);r=await invoke({id:'28a3cc20-0369-469a-b885-9e1d6f070f92',slug:e.slug});assert.equal(r.code,404);globalThis.fetch=async()=>{throw Error('private upstream details')};r=await invoke({id,slug:e.slug});assert.equal(r.code,503);assert.ok(!r.body.includes('private upstream'));assert.match(r.headers['Content-Security-Policy'],/frame-ancestors https:/);}finally{globalThis.fetch=original}});
test('frame exception applies only to the public widget endpoint',()=>{const config=JSON.parse(readFileSync(new URL('../../vercel.json',import.meta.url)));const frameRule=config.headers.find(x=>x.headers.some(h=>h.key.toLowerCase()==='x-frame-options'));const pattern=new RegExp('^'+frameRule.source+'$');for(const route of['/api/widget','/api/widget/'])assert.equal(pattern.test(route),false,route);for(const route of['/api/widget-other','/social','/tickets','/api/entity','/widgets/'])assert.equal(pattern.test(route),true,route);});
test('sparse public record still has canonical handoff; unavailability has no private payload',()=>{const sparse=publicWidget({...e,name:'Sparse artist',profile:{owner_media:{version:1,items:[]}},slug:'sparse-artist'},id);assert.match(widgetHTML(sparse),/Explore on Zoi/);assert.equal(sparse.media,null);assert.ok(!widgetHTML(null).includes('id="play"'));});
test('poster projection preserves the entire artwork and labels public handoff',()=>{const data=publicWidget({...e,entity_type:'event',slug:'test-event',profile:{hero_kind:'event_poster',hero_url:'https://www.zoi.city/assets/events/opa/montreal-2027-poster.jpg',starts_at:'2027-03-26'}},id);assert.equal(data.imageKind,'event_poster');assert.match(widgetHTML(data),/event-poster/);assert.match(data.url,/\/event\/test-event$/);});
