import test from 'node:test';import assert from 'node:assert/strict';
import{mkdtemp,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{automaticAuditRequest,auditPlan,ciMain,qualitySummary}from'../../scripts/quality/ci.mjs';
const now=Date.parse('2026-09-30T12:00:00Z'),request={enabled:true,starts_at:'2026-09-30T11:00:00Z',expires_at:'2026-10-01T10:59:00Z',max_listings_per_run:20,tasks:['classification','verification']};
test('automatic authorization fixes total cap and expires within24hours',()=>{const p=automaticAuditRequest(request,now);assert(p.enabled);assert.equal(p.limit*p.tasks.length,20);for(const change of [{max_listings_per_run:21},{tasks:['design']},{expires_at:'2026-10-02T00:00:00Z'},{starts_at:'invalid'}])assert.throws(()=>automaticAuditRequest({...request,...change},now));for(const time of [Date.parse(request.starts_at)-1,Date.parse(request.expires_at),Date.parse(request.expires_at)+1])assert.equal(automaticAuditRequest(request,time).enabled,false);assert.equal(automaticAuditRequest({...request,enabled:false},now).enabled,false)});
test('expired automatic request performs no credential or collector network',async()=>{let calls=0;await ciMain({QUALITY_AUTOMATIC:'true',SUPABASE_ACCESS_TOKEN:'fixture'},{read:async()=>JSON.stringify(request),now:Date.parse(request.expires_at),fetchImpl:()=>{calls++;throw Error()},collector:()=>{calls++;throw Error()}});assert.equal(calls,0)});
test('automatic ignores environment attempts to enlarge cap or execute arbitrary task',async()=>{let cfg;await ciMain({QUALITY_AUTOMATIC:'true',QUALITY_TASK:'verification',QUALITY_LIMIT:'999',SUPABASE_SERVICE_ROLE_KEY:'fixture'},{read:async()=>JSON.stringify(request),now,collector:async c=>{cfg=c},summarize:async()=>({observed:0,confirmed:0,pending:0,scope:'fixture'})});assert.equal(cfg.limit,10);assert(cfg.execute);await assert.rejects(ciMain({QUALITY_AUTOMATIC:'true',QUALITY_TASK:'design'},{read:async()=>JSON.stringify(request),now}),/invalid_automatic_task/)});
test('manual plan and exact receipt resume retain explicit bounded options',async()=>{const plan=await auditPlan({QUALITY_TASK:'verification',QUALITY_LIMIT:'3',QUALITY_EXECUTE:'false'});assert.equal(plan.execute,false);assert.deepEqual(plan.matrix.task,['verification']);const resume=await auditPlan({QUALITY_EXECUTE:'true',QUALITY_RESUME:'true',RESUME_RUN:'123',RESUME_ATTEMPT:'2'});assert(resume.resume);assert(resume.execute);await assert.rejects(auditPlan({QUALITY_LIMIT:'21'}));await assert.rejects(auditPlan({RESUME_RUN:'1;bad'}));});
test('summary separates confirmed receipts from pending and routes actionable repair',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'quality-summary-'));try{const hash='a'.repeat(64),report={task:'classification',listing:{id:'listing'},decision:{status:'retry',evidence:{reason:'javascript_render_required',repair:{specialist:'enrichment'}}}};await writeFile(path.join(dir,hash+'.json'),JSON.stringify(report));let s=await qualitySummary(dir,{task:'classification',limit:10});assert.equal(s.pending,1);assert.equal(s.confirmed,0);assert.equal(s.repairs[0].specialist,'enrichment');await writeFile(path.join(dir,hash+'.receipt.json'),JSON.stringify({ok:true,listing_id:'listing',task:'classification',status:'retry'}));s=await qualitySummary(dir,{task:'classification',limit:10});assert.equal(s.confirmed,1);assert.equal(s.statuses.retry,1);assert.match(s.scope,/not every journey/);}finally{await rm(dir,{recursive:true,force:true})}});
