import test from 'node:test';import assert from 'node:assert/strict';import {quickLookDetails} from '../../assets/discovery/profile-preview.mjs';
test('public detail actions preserve source identity and owner clears',()=>{const e={name:'Test',website:'https://test.example',profile:{_enrich:{source_url:'https://test.example',phone:'+14165550123',description:'Source description'}}};assert.equal(quickLookDetails(e).links.find(x=>x.label==='Call').href,'tel:+14165550123');const cleared=quickLookDetails({...e,owner_content:{website:null,phone:null,description:null,profile:{menu_url:null}}});assert.deepEqual(cleared.links,[]);assert.equal(cleared.description,'');});
test('untrusted URL actions and mismatched machine contacts never become links',()=>{const result=quickLookDetails({website:'https://real.example',profile:{menu_url:'javascript:alert(1)',_enrich:{source_url:'https://other.example',phone:'+14165550123'}}});assert.deepEqual(result.links,[{href:'https://real.example/',label:'Official website'}]);});
test('same-identity source imagery and menu hydrate while explicit media clears and quarantine suppress fallback',()=>{const e={website:'https://place.example',profile:{_enrich:{source_url:'https://place.example/',hero_url:'https://place.example/logo.png',photo_urls:['https://place.example/interior.jpg'],menu_url:'https://place.example/menu.pdf',address_parts:{street:'123 Main',postcode:'A1'}}}};const d=quickLookDetails(e);assert.equal(d.photo,'https://place.example/interior.jpg');assert.equal(d.address,'123 Main, A1');assert(d.links.some(x=>x.label==='View menu'));assert.equal(quickLookDetails({...e,owner_content:{profile:{photos:[],menu_url:null}}}).photo,null);assert(!quickLookDetails({...e,owner_content:{profile:{menu_url:null}}}).links.some(x=>x.label==='View menu'));assert.equal(quickLookDetails({...e,profile:{_enrich:{...e.profile._enrich,organization_identity_quarantine:true}}}).photo,null);});

import {publicText} from '../../assets/discovery/profile-preview.mjs';
test('public descriptions remove imported markup including unfinished source fragments',()=>{assert.equal(publicText('<span class='),'');assert.equal(publicText('Fresh <b>Greek</b> food &amp; company'),'Fresh Greek food & company');});

test('explicit poster role applies only to its current photo and respects owner replacement or clear',()=>{const url='https://example.com/art.jpg',e={photo_url:url,profile:{hero_url:url,hero_kind:'event_poster'}};assert.equal(quickLookDetails(e).imageKind,'event_poster');assert.equal(quickLookDetails({...e,photo_url:'https://example.com/room.jpg'}).imageKind,null);assert.equal(quickLookDetails({...e,owner_content:{profile:{hero_kind:''}}}).imageKind,null);assert.equal(quickLookDetails({...e,owner_content:{photo_url:null}}).imageKind,null);assert.equal(quickLookDetails({photo_url:'https://example.com/poster.jpg',profile:{}}).imageKind,null);});
