import{test}from'node:test';import assert from'node:assert/strict';import{mkdtemp,rm,readFile,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{allowedRenderRequest}from'../../scripts/enrichment/render-source.mjs';import{captureRows}from'../../scripts/enrichment/render-capture.mjs';import{extractRenderedSource}from'../../scripts/enrichment/extractor.mjs';
test('renderer refuses mutations and active media while allowing publicly guarded page resources',()=>{for(const type of ['document','script','stylesheet','xhr','fetch','image'])assert(allowedRenderRequest({method:()=> 'GET',resourceType:()=>type}));for(const type of ['media','font','websocket','other'])assert.equal(allowedRenderRequest({method:()=> 'GET',resourceType:()=>type}),false);assert.equal(allowedRenderRequest({method:()=> 'POST',resourceType:()=> 'xhr'}),false)});
test('rendered page uses exact worker extractor and never promotes a video to image',()=>{const x=extractRenderedSource('<video><source src="/hero.mp4"></video><img src="/dining.jpg"><a href="tel:+254742432358">Call</a>','https://restaurant.org/');assert.equal(x.profile.hero_url,'https://restaurant.org/dining.jpg');assert.equal(x.profile.phone,'+254742432358')});
test('batch captures each record and resumes immutable source evidence without recrawling',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'zoi-render-'));try{let calls=0;const rows=[{id:'84bdafb9-966b-489a-a4d3-0dc3dc92acf9',website:'https://restaurant.org/',source_fingerprint:'one'}],render=async row=>{calls++;return{listing_id:row.id,profile:{phone:'1234567'},review_required:true}};const first=await captureRows(rows,{directory,render});const second=await captureRows(rows,{directory,render});assert.equal(calls,1);assert.equal(second[0].resumed,true);assert.equal(first[0].status,'captured_pending_review');await writeFile(path.join(directory,first[0].hash+'.json'),'changed');await assert.rejects(captureRows(rows,{directory,render}),/capture_hash_mismatch/);}finally{await rm(directory,{recursive:true,force:true})}});
test('a blocked source becomes a specialist repair report, never synthetic content',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'zoi-render-'));try{const r=await captureRows([{id:'84bdafb9-966b-489a-a4d3-0dc3dc92acf9',website:'https://restaurant.org/'}],{directory,render:async()=>{throw Error('robots_disallow')}});const report=JSON.parse(await readFile(path.join(directory,r[0].hash+'.json'),'utf8'));assert.equal(report.reason,'robots_disallow');assert.equal(report.specialist,'enrichment');assert.equal(report.profile,undefined);}finally{await rm(directory,{recursive:true,force:true})}});

test('reviewed enrichment cannot bypass source identity or existing lease binding',async()=>{const{reviewedEnrichmentBatch}=await import('../../scripts/enrichment/reviewed-batch.mjs');const{canonical,sha256}=await import('../../scripts/quality/evidence.mjs');const report={listing_id:'id',website:'https://restaurant.org/',source_fingerprint:'fp',profile:{phone:'1234567'},source:{http_status:200,sha256:'source'},render:{url:'https://restaurant.org/',sha256:'render'}};const review={listing_id:'id',source_fingerprint:'fp',report_sha256:sha256(canonical(report)),identity_confirmed:true,images_confirmed:true,reviewer:'specialist',reviewed_at:'2026-09-30T00:00:00Z'};const lease={listing_id:'id',website:report.website,lease_id:'existing',slug:'restaurant'};assert.equal(reviewedEnrichmentBatch(report,review,lease)[0].profile.phone,'1234567');assert.throws(()=>reviewedEnrichmentBatch(report,{...review,identity_confirmed:false},lease),/source_review_required/);assert.throws(()=>reviewedEnrichmentBatch(report,review,{...lease,listing_id:'other'}),/review_lease_mismatch/);assert.throws(()=>reviewedEnrichmentBatch(report,{...review,approved_fields:{rating:5}},lease),/unapproved_review_field/);});


test('unattended source repair requires exact identity and preserves previous nonempty fields',async()=>{
 const {automaticRenderedPayload}=await import('../../scripts/enrichment/render-queue.mjs');
 const row={listing_id:'id',slug:'example',website:'https://restaurant.org/',name:'Example Restaurant',lease_id:'lease',existing_enrich:{hero_url:'https://restaurant.org/old.jpg',phone:'111',status:'error'}};
 const report={listing_id:'id',website:row.website,source:{http_status:200,sha256:'s'},render:{title:row.name,url:row.website,sha256:'r'},profile:{hero_url:null,phone:'222'}};
 const result=automaticRenderedPayload(row,report,'hash');assert.equal(result.profile.phone,'222');assert.equal(result.profile.hero_url,row.existing_enrich.hero_url);assert.equal(result.profile.status,undefined);assert.equal(result.profile.rendered_source_evidence.identity_verified,false);
 for(const changed of [{...report,render:{...report.render,title:'Other Restaurant'}},{...report,listing_id:'other'},{...report,source:{http_status:500}},{...report,render:{...report.render,url:'https://other.org/'}}])assert.equal(automaticRenderedPayload(row,changed,'hash').profile.crawl_status,'error');
 assert.equal(automaticRenderedPayload({...row,owner_managed:true},report,'hash').profile.last_error,'owner_managed_render_review');
});
