import test from 'node:test';import assert from 'node:assert/strict';
import {restaurantHomeContent,renderRestaurantHome} from '../../api/_restaurant-home.js';
const id='10000000-0000-4000-8000-000000000001';
// Exact seo_entity fields, simulated response data; no live authenticated writes.
const source={phone:'+14165550199',email:'old@source.example',description:'Old source biography',hours:'Old source hours',social:{instagram:'https://instagram.com/old_source'},photo_url:'https://source.example/old.jpg',menu:[{section:'Source section',items:[{name:'Source dish',price:'CAD 99'}]}],specials:[{name:'Source promotion'}]};
const base={id,entity_type:'business',slug:'owner-readback',name:'Owner Readback',category_slug:'restaurants',website:'https://source.example',profile:{_enrich:source}};
test('projected owner explicit base clears suppress all derived contact biography hours and socials',()=>{const entity={...base,description:null,phone:null,email:null,social_links:{},owner_content:{description:null,phone:null,email:null,hours:null,social_links:{},photo_url:null}};const data=restaurantHomeContent(entity);assert.equal(data.description,'');assert.equal(data.phone,'');assert.equal(data.phoneHref,null);assert.equal(data.emailHref,null);assert.equal(data.hero,null);assert.deepEqual(data.hours,[]);assert.deepEqual(data.socials,[]);for(const template of ['atelier','concierge','table','parea']){const html=renderRestaurantHome(entity,{template});for(const old of ['Old source biography','Old source hours','14165550199','old@source.example','instagram.com/old_source','source.example/old.jpg'])assert(!html.includes(old),`${template}: ${old}`);}});
test('owner saved values and profile explicit clears survive later source enrichment refresh',()=>{const owner_content={description:'Owner biography',phone:'+14165550222',email:'owner@example.org',hours:'Tuesday 12–20',social_links:{instagram:'https://instagram.com/owner_real'},profile:{menu:null,specials:null}};for(const refreshed of [source,{...source,description:'New imported biography',phone:'+14165550333',menu:[{section:'Imported',items:[{name:'New imported dish'}]}]}]){const entity={...base,owner_content,profile:{_enrich:refreshed}};const data=restaurantHomeContent(entity);assert.equal(data.description,'Owner biography');assert.equal(data.phone,'+14165550222');assert.equal(data.email,'owner@example.org');assert.equal(data.hours[0].time,'Tuesday 12–20');assert.equal(data.socials[0].url,'https://instagram.com/owner_real');assert.deepEqual(data.menuSections,[]);assert.deepEqual(data.specials,[]);for(const template of ['atelier','concierge','table','parea']){const html=renderRestaurantHome(entity,{template});assert(html.includes('Owner biography'));assert(!html.includes('Source dish'));assert(!html.includes('New imported dish'));}}});
test('unclaimed source content remains available when no authoritative owner marker exists',()=>{const data=restaurantHomeContent(base);assert.equal(data.description,source.description);assert.equal(data.phone,source.phone);assert.equal(data.socials[0].url,source.social.instagram);assert.equal(data.menuSections[0].items[0].name,'Source dish');});
import {TWELVE_ISLANDS} from '../../assets/homes/templates/restaurant/brands.mjs';
test('exact reviewed restaurant identity also respects owner base clears without replacing brand artwork',()=>{const entity={...base,id:TWELVE_ISLANDS.id,website:TWELVE_ISLANDS.website,owner_content:{phone:null,description:null,hours:null,photo_url:null,social_links:{}}};const data=restaurantHomeContent(entity);assert.equal(data.brand,'twelve-islands');assert.equal(data.brandArtwork,TWELVE_ISLANDS.artwork);assert.equal(data.description,'');assert.equal(data.phoneHref,null);assert.equal(data.hero,null);assert.deepEqual(data.hours,[]);for(const template of ['atelier','concierge','table','parea']){const html=renderRestaurantHome(entity,{template});assert(!html.includes('tel:+19086472193'));assert(!html.includes('4pm–9pm'));assert(!html.includes('Old source biography'));assert(!html.includes('source.example/old.jpg'));}});
