import test from'node:test';import assert from'node:assert/strict';import{restaurantData}from'../../assets/homes/templates/restaurant/model.mjs';import{renderRestaurant}from'../../assets/homes/templates/restaurant/render.mjs';import{TWELVE_ISLANDS as S,reviewedRestaurantBrand,brandPalette,brandStyle,contrast}from'../../assets/homes/templates/restaurant/brands.mjs';
const e={id:S.id,slug:'12-islands-greek-taverna-stirling',name:'12 Islands Greek Taverna',website:S.website,profile:{},address:'1255 Valley Road',city:'Stirling'};
test('exact identity source supplies photos menu hours contact and ordering',()=>{const d=restaurantData(e);assert.equal(d.photos.length,3);assert.equal(d.menuSections[0].items.length,6);assert.equal(d.hours.length,4);assert.equal(d.phoneHref,'tel:+19086472193');assert.equal(d.order[0].url,S.website+'order');assert.equal(d.logo,null);assert.match(d.photoCaptions[d.photos[0]],/salad/);assert.ok(d.privateEvents);assert.equal(reviewedRestaurantBrand({...e,id:'other'}),null);assert.equal(reviewedRestaurantBrand({...e,website:'https://evil.test/'}),null);});
test('owner clear and override reviewed defaults',()=>{const p={photos:[],menu:[],menu_url:null,hours:[],order:[],catering:'Owner event terms',tagline:'Owner words'};const d=restaurantData({...e,profile:p},p);assert.equal(d.photos.length,0);assert.equal(d.menuSections.length,0);assert.equal(d.menuLinks.length,0);assert.equal(d.hours.length,0);assert.equal(d.order.length,0);assert.equal(d.catering,p.catering);assert.equal(d.tagline,p.tagline);assert.equal(d.privateEvents,false);assert.match(renderRestaurant(d,{copy:{headline:'My headline',intro:'My intro'},hidden_sections:['offerings']}),/My intro/);});
test('palette validates owner values and contrast without arbitrary CSS',()=>{for(const fg of['ink','muted','accent'])for(const bg of['paper','cream'])assert.ok(contrast(S.palette[fg],S.palette[bg])>=4.5);assert.equal(brandPalette(S.palette,{ink:'#ffffff'}).ink,S.palette.ink);assert.equal(brandPalette(S.palette,{ink:'#112233'}).ink,'#112233');assert.ok(!brandStyle(brandPalette(S.palette,{ink:'red;display:none'})).includes('display'));});
test('branded photos do not pretend an island panorama or olive illustration is venue or logo',()=>{const h=renderRestaurant(restaurantData(e));assert.match(h,/data-restaurant-brand="twelve-islands"/);assert.match(h,/data-event-plan/);assert.match(h,/Takeout/);assert.match(h,/US\$17/);assert.ok(!h.includes('Santorini'));assert.ok(!h.includes('OliveBranch.png" alt="12 Islands Greek Taverna logo'));});

test('owner menu URL and order URL clear block related source fallback',()=>{for(const p of [{menu_url:null,order_url:null},{menu_url:'https://owner.example/menu'}]){const d=restaurantData({...e,profile:p},p);assert.equal(d.menuSections.length,0);assert.equal(d.sourceMenu,'');if(p.order_url===null)assert.equal(d.order.length,0);}});

test('all restaurant identities use a readable default and can inherit source brand without curated ID',()=>{
 const base={id:'11111111-1111-4111-8111-111111111111',slug:'independent-restaurant',name:'Independent',website:'https://example.test/',profile:{}};
 const palette={ink:'#16334f',paper:'#ffffff',cream:'#f0f6fc',accent:'#174b80',muted:'#455a70',gold:'#946d29'};
 const d=restaurantData(base,{brand_palette:palette});assert.deepEqual(d.brandPalette,palette);
 assert.equal(restaurantData(base).brandPalette.accent,'#075985');
 for(const fg of['ink','muted','accent'])for(const bg of['paper','cream'])assert.ok(contrast(d.brandPalette[fg],d.brandPalette[bg])>=4.5);
 assert.equal(restaurantData({...base,profile:{brand_palette:null}},{brand_palette:palette}).brandPalette.accent,'#075985');
 assert.equal(restaurantData({...base,owner_content:{profile:{brand_palette:{accent:'#003366'}}}},{brand_palette:palette}).brandPalette.accent,'#003366');
 assert.equal(brandPalette({ink:'#ffffff'},null).ink,'#133a5b');
});

test('light brand ink and action colours cannot erase fixed white hero and button text',()=>{const palette=brandPalette(null,{ink:'#ffffff',paper:'#000000',cream:'#101010',accent:'#ffffff',muted:'#eeeeee',gold:'#000000'});assert.ok(contrast(palette.ink,'#ffffff')>=4.5);assert.ok(contrast(palette.accent,'#ffffff')>=4.5);});

test('source menu scans are separate from gallery and respect owner menu removal',()=>{const base={id:'11111111-1111-4111-8111-111111111111',name:'Menu place',website:'https://example.test/',profile:{}};const source={menu_image_urls:['https://example.test/menu.jpg','javascript:alert(1)']};const d=restaurantData(base,source);assert.equal(d.menuLinks.length,1);assert.equal(d.menuLinks[0].kind,'image');assert.equal(d.photos.length,0);assert.equal(restaurantData({...base,profile:{menu:[]}},source).menuLinks.length,0);assert.equal(restaurantData({...base,profile:{menu_image_urls:[]}},source).menuLinks.length,0);});

test('reviewed logo content bounds are bound to the exact source image and constrained',async()=>{const{logoContentStyle}=await import('../../assets/homes/templates/restaurant/model.mjs');const b={source_url:'https://example.com/logo.png',x:264,y:181,width:264,height:250,image_width:792,image_height:612};assert.match(logoContentStyle(b,b.source_url),/--logo-width:300%/);for(const v of [{...b,width:Infinity},{...b,x:-1},{...b,height:999},{...b,width:1}])assert.equal(logoContentStyle(v,b.source_url),'');assert.equal(logoContentStyle(b,'https://example.com/new-logo.png'),'');});
