import test from 'node:test';
import assert from 'node:assert/strict';
import {reviewedEnrichmentBatch} from '../../scripts/enrichment/reviewed-batch.mjs';
import {automaticRenderedPayload} from '../../scripts/enrichment/render-queue.mjs';
import {canonical,sha256} from '../../scripts/quality/evidence.mjs';
const hash='a'.repeat(64),photo='https://hotel.test/real.jpg';
function fixture(){
 const report={schema:2,source_scope:'official_site',capture_kind:'source_html',review_required:true,render:null,listing_id:'id',website:'https://hotel.test/',source_fingerprint:'fp',source:{url:'https://hotel.test/',http_status:200,sha256:hash,source_state:'html_available',requires_rendering:false,visible_text_length:1000},extractor_sha256:hash,profile:{description:'This genuine hotel offers rooms overlooking the village.',phone:'123456789',site_lang:'en',photo_urls:[photo],hero_url:photo,social:{facebook:'https://facebook.com/hotel'}},images:[{url:photo,final_url:photo,sha256:hash,mime:'image/jpeg',bytes:10000,width:1200,height:800,role:'photo'}]};
 const existing={description:'Old description',photo_urls:['https://hotel.test/old.jpg'],hero_url:'https://hotel.test/old.jpg',menu_url:'https://hotel.test/menu.pdf',social:{instagram:'https://instagram.com/hotel'},provenance:{menu_url:'older-reviewed-source'},crawl_status:'error',last_error:'timeout'};
 const review={listing_id:'id',source_fingerprint:'fp',report_sha256:sha256(canonical(report)),identity_confirmed:true,images_confirmed:true,reviewer:'independent',reviewed_at:'2026-10-01T00:00:00Z',approved_image_hashes:[hash],prior_machine_sha256:sha256(canonical(existing))};
 const lease={listing_id:'id',website:report.website,slug:'hotel',lease_id:'genuine-test-lease',source_fingerprint:'fp',existing_enrich:existing};return {report,review,lease};
}
function batch(f){f.review.report_sha256=sha256(canonical(f.report));return reviewedEnrichmentBatch(f.report,f.review,f.lease)[0];}
test('truthful source HTML provenance preserves prior useful fields and reviewed images',()=>{const f=fixture(),row=batch(f);assert.equal(row.profile.menu_url,f.lease.existing_enrich.menu_url);assert.deepEqual(row.profile.photo_urls,[photo,'https://hotel.test/old.jpg']);assert.equal(row.profile.social.instagram,'https://instagram.com/hotel');assert.equal(row.profile.social.facebook,'https://facebook.com/hotel');assert.equal(row.profile.rendered_source_evidence,undefined);assert.equal(row.profile.source_html_evidence.method,'reviewed_official_source_html');assert.equal(row.profile.last_error,undefined);assert.equal(row.provenance.phone,'official-source-html:https://hotel.test/');assert.equal(row.provenance.menu_url,'older-reviewed-source');});
test('unapproved or unavailable new photo cannot remove existing imagery',()=>{const f=fixture();f.review.approved_image_hashes=[];const row=batch(f);assert.deepEqual(row.profile.photo_urls,['https://hotel.test/old.jpg']);assert.equal(row.profile.hero_url,'https://hotel.test/old.jpg');});
test('approval binds both source artifact and prior machine snapshot',()=>{const f=fixture();assert.throws(()=>reviewedEnrichmentBatch({...f.report,profile:{phone:'changed'}},f.review,f.lease),/review_artifact_mismatch/);assert.throws(()=>batch({...f,lease:{...f.lease,existing_enrich:{}}}),/prior_machine_review_mismatch/);assert.throws(()=>batch({...f,lease:{...f.lease,existing_enrich:undefined}}),/prior_machine_review_required/);assert.throws(()=>batch({...f,lease:{...f.lease,source_fingerprint:'changed'}}),/review_lease_fingerprint_mismatch/);});
test('unknown image, fake rendering, challenge, member mismatches and unsupported data fail closed',()=>{for(const alter of[f=>f.review.approved_image_hashes=['b'.repeat(64)],f=>f.report.render={sha256:hash},f=>f.report.source.source_state='source_challenge',f=>f.report.source.requires_rendering=true,f=>f.report.source.url='https://other.test/',f=>f.report.aggregator=true,f=>f.report.profile.rating=5,f=>f.report.images[0].mime='image/svg+xml',f=>f.report.images[0].width=999999,f=>f.review.approved_fields={phone:'invented'}]){const f=fixture();alter(f);assert.throws(()=>batch(f));}});
test('language-only extraction is not useful enrichment and automatic rendered path refuses source-only report',()=>{const f=fixture();f.report.profile={site_lang:'en'};f.review.approved_image_hashes=[];assert.throws(()=>batch(f),/source_html_no_useful_fields/);const good=fixture();const row=automaticRenderedPayload({...good.lease,name:'Hotel'},good.report,sha256(canonical(good.report)));assert.equal(row.profile.crawl_status,'error');assert.equal(row.profile.last_error,'rendered_source_incomplete');});
test('reviewed source conflict deliberately clears prior machine email while preserving unrelated data',()=>{const f=fixture();f.lease.existing_enrich.email='stale@hotel.test';f.review.prior_machine_sha256=sha256(canonical(f.lease.existing_enrich));f.report.profile.email=null;f.report.profile.email_conflict={structured:'stale@hotel.test',linked:['current@hotel.test'],source_url:f.report.source.url};const row=batch(f);assert.equal(row.profile.email,null);assert.deepEqual(row.profile.email_conflict,f.report.profile.email_conflict);assert.equal(row.profile.menu_url,f.lease.existing_enrich.menu_url);assert.equal(row.profile.owner_content,undefined);assert.equal(row.provenance.email,'official-source-html:https://hotel.test/');});
test('absence or bare null email cannot manufacture a clear; malformed conflict evidence refuses approval',()=>{for(const email of [undefined,null]){const f=fixture();f.lease.existing_enrich.email='prior@hotel.test';f.review.prior_machine_sha256=sha256(canonical(f.lease.existing_enrich));f.report.profile.email=email;assert.equal(batch(f).profile.email,'prior@hotel.test');}for(const conflict of [{structured:'same@hotel.test',linked:['SAME@hotel.test'],source_url:'https://hotel.test/'},{structured:null,linked:['one@hotel.test'],source_url:'https://hotel.test/'},{structured:'old@hotel.test',linked:['new@hotel.test'],source_url:'https://other.test/'},{structured:'old@hotel.test',linked:['invalid'],source_url:'https://hotel.test/'}]){const f=fixture();f.report.profile.email=null;f.report.profile.email_conflict=conflict;assert.throws(()=>batch(f),/source_email_conflict_invalid/);}});
test('machine conflict does not override explicit owner contact or owner clear in public model',async()=>{const {restaurantData}=await import('../../assets/homes/templates/restaurant/model.mjs');const f=fixture();f.report.profile.email=null;f.report.profile.email_conflict={structured:'old@hotel.test',linked:['new@hotel.test'],source_url:f.report.source.url};const profile=batch(f).profile;for(const email of ['owner@hotel.test',null]){const model=restaurantData({name:'Independent Restaurant',slug:'independent-restaurant',owner_content:{email}},profile);assert.equal(model.email,email||'');}});
test('new valid email resolves explicit conflict marker; missing or invalid email cannot erase prior evidence',()=>{for(const value of ['current@hotel.test',null,undefined,'not an email']){const f=fixture(),prior={structured:'old@hotel.test',linked:['other@hotel.test'],source_url:f.report.source.url};f.lease.existing_enrich.email_conflict=prior;f.review.prior_machine_sha256=sha256(canonical(f.lease.existing_enrich));f.report.profile.email=value;f.report.profile.email_conflict=null;const result=batch(f);assert.deepEqual(result.profile.email_conflict,value==='current@hotel.test'?null:prior);}});

test('record label artist capture requires independently confirmed exact identity and excludes corporate contacts',()=>{
 const f=fixture();f.report.source_scope='record_label';f.report.publisher_identity={listing_id:'id',name:'Artist Name',source_url:f.report.source.url,kind:'label_artist_profile'};f.report.profile={description:'A factual biography of this singer and composer from their record label.',source_kind:'label_artist_profile',listen:{spotify:'https://open.spotify.com/artist/4uyuai6Pqgz3kSx1Jme2PJ'},photo_urls:[photo],hero_url:photo};f.lease.name='Artist Name';f.lease.entity_type='artist';f.lease.existing_enrich={old_evidence:'preserved'};f.review.prior_machine_sha256=sha256(canonical(f.lease.existing_enrich));f.review.publisher_scope_confirmed=true;f.review.publisher_identity=f.report.publisher_identity;const result=batch(f);assert.equal(result.profile.source_kind,'label_artist_profile');assert.equal(result.profile.old_evidence,'preserved');assert.equal(result.profile.source_html_evidence.method,'reviewed_record_label_source_html');
 for(const alter of [x=>x.review.publisher_scope_confirmed=false,x=>x.lease.name='Other artist',x=>x.lease.entity_type='business',x=>{x.report.source.url='https://hotel.test/other-artist';x.report.publisher_identity.source_url=x.report.source.url;},x=>x.report.profile.phone='123',x=>x.report.profile.social={instagram:'https://instagram.com/label'},x=>x.report.profile.listen.spotify='https://open.spotify.com/artist/wrong',x=>{x.lease.existing_enrich.email='label@example.com';x.review.prior_machine_sha256=sha256(canonical(x.lease.existing_enrich));}]){const x=structuredClone(f);alter(x);assert.throws(()=>batch(x));}
});
