import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {prepareCoordinateRequest} from '../../scripts/geography/reviewed-coordinate-request.mjs';
function fixture(){const snapshot={id:'054dd95e-5253-4a86-9630-fe91c3f29c90',database_snapshot:'snapshot',source_fingerprint:'source',address:'177 Lonsdale Street',city:'Melbourne',country:'Australia'};const reportText=JSON.stringify({schema:1,kind:'official_coordinate_dry_run',listing_id:snapshot.id,source_fingerprint:'source',collector:'collector',status:'review_required',reason:'coordinate_plausibility_review_required',http_status:200,candidate:{evidence_kind:'jsonld',address:{street:snapshot.address,city:snapshot.city,country:snapshot.country},latitude:-37.8110808,longitude:144.9670491}},null,2)+'\n';return{requestId:'11111111-1111-4111-8111-111111111111',snapshot,reportText,review:{candidate_address:{street:snapshot.address,city:snapshot.city,country:snapshot.country},database_snapshot:'snapshot',report_sha256:createHash('sha256').update(reportText).digest('hex'),reviewer:'reviewer',specialist:'collector',reviewed_at:'2026-10-01T00:00:00Z',official_source_confirmed:true,exact_address_confirmed:true,not_area_centroid:true,stored_address:snapshot.address,stored_city:snapshot.city,stored_country:snapshot.country,locality_extent:{south:-37.82,north:-37.80,west:144.95,east:144.98}},now:Date.parse('2026-10-01T01:00:00Z')};}
test('preserves exact reviewed bytes and explicit request identity; prepares no write',()=>{const f=fixture(),r=prepareCoordinateRequest(f);assert.equal(r.arguments.p_report_text,f.reportText);assert.equal(r.arguments.p_request,f.requestId);assert.equal(r.coordinate_writes,0);assert.deepEqual(prepareCoordinateRequest(f),r);});
test('report whitespace changes require renewed exact hash',()=>{const f=fixture();f.reportText=f.reportText.trim();assert.throws(()=>prepareCoordinateRequest(f),/exact_report_hash/);});
test('stale identity, self-review, expired evidence and out-of-locality point refuse',()=>{for(const mutate of [f=>f.snapshot.database_snapshot='changed',f=>f.review.reviewer=' COLLECTOR ',f=>f.review.reviewed_at='2026-09-01',f=>f.review.locality_extent.north=-38,f=>f.review.stored_address='different',f=>f.review.specialist='somebody else']){const f=fixture();mutate(f);assert.throws(()=>prepareCoordinateRequest(f));}});

test('requires exact independently reviewed candidate address and supported writer evidence',()=>{for(const mutate of [f=>delete f.review.candidate_address,f=>f.review.candidate_address.street='Other street']){const f=fixture();mutate(f);assert.throws(()=>prepareCoordinateRequest(f),/candidate_identity/);}});
test('official destination requires explicit purpose and exact reviewed destination URL',()=>{const f=fixture(),report=JSON.parse(f.reportText);report.candidate.evidence_kind='official_destination';report.candidate.evidence_url='https://www.google.com/maps/dir//Actual+Place';f.reportText=JSON.stringify(report);f.review.report_sha256=createHash('sha256').update(f.reportText).digest('hex');assert.throws(()=>prepareCoordinateRequest(f),/destination_review/);f.review.destination_purpose='place_location';f.review.destination_url=report.candidate.evidence_url;assert.equal(prepareCoordinateRequest(f).coordinate_writes,0);f.review.destination_url+='wrong';assert.throws(()=>prepareCoordinateRequest(f),/destination_review/);});
