import test from'node:test';import assert from'node:assert/strict';import{SOURCE_ID,TABLES,LEGEND,nearestTable,sponsorMetadata,tablePreference,FLOORPLAN}from'../../assets/events/signature/venue-experience.mjs';
test('published image trace has each numbered position1to118 once, bounded and nonoverlapping',()=>{assert.equal(TABLES.length,118);assert.deepEqual([...TABLES.map(t=>Number(t.id))].sort((a,b)=>a-b),Array.from({length:118},(_,i)=>i+1));for(const t of TABLES){assert.ok(LEGEND[t.tier]);assert.ok(t.nx>=0&&t.ny>=0&&t.nx+t.nw<=1&&t.ny+t.nh<=1);assert.equal(t.x/800,t.nx);assert.equal(t.y/659,t.ny);}for(let i=0;i<TABLES.length;i++)for(let j=i+1;j<TABLES.length;j++){const a=TABLES[i],b=TABLES[j];assert.ok(!(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y),`${a.id}/${b.id} overlap`);}});
test('source anchor positions and categories agree with visually reviewed floorplan',()=>{const t=id=>TABLES.find(t=>t.id===String(id));assert.equal(t(1).tier,'magenta');assert.equal(t(23).tier,'magenta');assert.equal(t(24).tier,'green');assert.equal(t(118).tier,'red');assert.equal(t(30).tier,'magenta');assert.equal(t(60).tier,'yellow');assert.equal(t(66).tier,'white');assert.equal(t(105).y,166);assert.equal(t(1).y,568);assert.match(FLOORPLAN.url,/ffa879fd11b34257a44a377874e56254/);});
test('keyboard spatial moves follow the published rows instead of numerical seat order',()=>{assert.equal(nearestTable('104','ArrowRight'),'103');assert.equal(nearestTable('104','ArrowDown'),'65');assert.equal(nearestTable('65','ArrowUp'),'104');assert.equal(nearestTable('105','ArrowLeft'),'105');});
test('preferences carry only source plan identity and max3 verified table labels',()=>{const p=tablePreference(['1','23','118']);assert.deepEqual(p.table_ids,['1','23','118']);assert.deepEqual(Object.keys(p).sort(),['source_id','source_version','table_ids']);for(const ids of [['119'],['1','1'],['1','2','3','4'],[1]])assert.throws(()=>tablePreference(ids));});
test('sponsors require approval and exact table plus safe destination; no sponsor invented by default',()=>{assert.equal(sponsorMetadata(null,'1'),null);const good={approved:true,event_id:SOURCE_ID,startsAt:'2020-01-01T00:00:00Z',endsAt:'2100-01-01T00:00:00Z',table_id:'1',name:'QA-only sponsor fixture',destination:'/business/example'};assert.equal(sponsorMetadata(good,'1').destination,'/business/example');assert.equal(sponsorMetadata({...good,approved:false},'1'),null);assert.equal(sponsorMetadata(good,'23'),null);for(const destination of ['javascript:alert(1)','//evil.example','https://u:p@evil.example','/\\evil.example','data:text/html,x','http://example.com'])assert.equal(sponsorMetadata({...good,destination},'1'),null);assert.equal(sponsorMetadata({...good,destination:'https://example.com/sponsor'},'1').destination,'https://example.com/sponsor');});

test('sponsor schedule is explicit, current, exclusive at end and scoped to this event',()=>{const good={approved:true,event_id:SOURCE_ID,table_id:'1',name:'QA only',destination:'/business/example',startsAt:'2027-03-01T00:00:00Z',endsAt:'2027-03-21T00:00:00Z'};const now=Date.parse('2027-03-20T00:00:00Z');assert.ok(sponsorMetadata(good,'1',now));for(const patch of [{event_id:'other'},{startsAt:undefined},{endsAt:'invalid'},{endsAt:'2027-03-20T00:00:00Z'},{startsAt:'2027-03-21T00:00:00Z'}])assert.equal(sponsorMetadata({...good,...patch},'1',now),null);});

test('guest preference ordering is immutable, exact-ID bounded and never changes floor geometry',async()=>{const {reorderPreferences}=await import('../../assets/events/signature/venue-experience.mjs');const ids=['30','31','32'],before=JSON.stringify(TABLES);assert.deepEqual(reorderPreferences(ids,'32',0),['32','30','31']);assert.deepEqual(ids,['30','31','32']);assert.equal(JSON.stringify(TABLES),before);for(const [items,id,pos]of[[ids,'119',0],[ids,'30',3],[ids,'30',-1],[ids,'30',.5],[['30','30'],'30',0]])assert.throws(()=>reorderPreferences(items,id,pos));});
test('mixed or mismatched source table price bands cannot produce a selected-budget subtotal',async()=>{const{matchesTableBudget}=await import('../../assets/events/signature/customer-a.mjs');assert.equal(matchesTableBudget(['30'],'yellow'),false);assert.equal(matchesTableBudget(['30'],'magenta'),true);assert.equal(matchesTableBudget(['30','29'],'magenta'),false);assert.equal(matchesTableBudget([],'yellow'),true);assert.throws(()=>matchesTableBudget(['not-a-table'],'yellow'));});
