import test from 'node:test';import assert from 'node:assert/strict';
import{createWallSubmission,moderateWallSubmission,revokeWallSubmission,screenItem,wallMedia,wallSponsor}from'../../assets/events/signature/event-wall.mjs';
const now=Date.parse('2027-03-20T23:00:00Z');
const ctx={actorId:'guest-1',eventId:'event-1',policyVersion:'screen-v1',now,allowedMediaOrigins:['https://media.example.test'],startsAt:'2027-03-20T22:00:00Z',endsAt:'2027-03-21T04:00:00Z'};
const input=()=>({id:'photo-1',caption:'Our evening',credit:'Guest chosen name',hashtags:['#Toronto','#Παρέα'],consent:{publicScreen:true,ownRights:true,peoplePermission:true,policyVersion:'screen-v1',eventId:'event-1',expiresAt:'2027-03-21T04:00:00Z'},media:{id:'asset-1',eventId:'event-1',authorId:'guest-1',provider:'zoi_upload',state:'ready',mime:'image/jpeg',url:'https://media.example.test/event-wall/event-1/asset-1.jpg'}});
const op={...ctx,actorId:'operator-1',membershipCurrent:true,role:'moderator',decision:'approved',expectedVersion:1};
const approved=()=>moderateWallSubmission(createWallSubmission(input(),ctx),op);
test('explicit separate event-screen consent required; new uploads remain pending until current moderator approves',()=>{const pending=createWallSubmission(input(),ctx);assert.equal(screenItem(pending,ctx),null);for(const field of['publicScreen','ownRights','peoplePermission']){const i=input();i.consent[field]=false;assert.throws(()=>createWallSubmission(i,ctx),/explicit_consent/);}const a=approved(),display=screenItem(a,ctx);assert.equal(display.caption,'Our evening');assert.deepEqual(Object.keys(display).sort(),['caption','credit','eventId','hashtags','id','media']);assert.equal(JSON.stringify(display).includes('guest-1'),false);assert.equal(pending.version,1);});
test('cross-event, other author, social URLs, unready uploads, SVG, credentials and arbitrary providers are rejected',()=>{for(const patch of[{eventId:'other'},{authorId:'other'},{provider:'instagram'},{state:'uploading'},{mime:'image/svg+xml'},{url:'https://instagram.com/photo'},{url:'https://media.example.test.evil/event-wall/event-1/asset-1.jpg'},{url:'https://user@media.example.test/event-wall/event-1/asset-1.jpg'},{url:'https://media.example.test/event-wall/event-1/asset-1.jpg?x=1'},{url:'data:image/jpeg;base64,AAAA'},{url:'https://media.example.test/event-wall/other/asset-1.jpg'}])assert.equal(wallMedia({...input().media,...patch},{...ctx,authorId:'guest-1'}),null);assert.equal(wallMedia(input().media,{...ctx,authorId:'guest-1',allowedMediaOrigins:[]}),null);});
test('approval needs role, current membership, same event and exact revision; consent version changes hide old approval',()=>{const e=createWallSubmission(input(),ctx);for(const patch of[{role:'viewer'},{membershipCurrent:false},{eventId:'other'},{actorId:''}])assert.throws(()=>moderateWallSubmission(e,{...op,...patch}),/not_authorized/);assert.throws(()=>moderateWallSubmission(e,{...op,expectedVersion:0}),/version_conflict/);assert.equal(screenItem(approved(),{...ctx,policyVersion:'screen-v2'}),null);assert.equal(screenItem({...approved(),version:3},ctx),null);assert.equal(screenItem(approved(),{...ctx,eventId:'other'}),null);});
test('owner revocation is immediate and idempotent; operator removal cannot be republished',()=>{const e=approved();assert.throws(()=>revokeWallSubmission(e,{...ctx,actorId:'another',expectedVersion:2}),/not_authorized/);const revoked=revokeWallSubmission(e,{...ctx,expectedVersion:2});assert.equal(screenItem(revoked,ctx),null);assert.equal(revokeWallSubmission(revoked,{...ctx,expectedVersion:2}),revoked);assert.throws(()=>moderateWallSubmission(revoked,{...op,expectedVersion:3}),/invalid_transition/);const removed=moderateWallSubmission(e,{...op,decision:'removed',expectedVersion:2});assert.equal(screenItem(removed,ctx),null);assert.throws(()=>moderateWallSubmission(removed,{...op,expectedVersion:3}),/invalid_transition/);});
test('no photos before event, after screen expiry, malformed time, future consent or expired consent; tags are display only',()=>{const a=approved();for(const patch of[{now:Date.parse(ctx.endsAt)},{now:Date.parse(ctx.startsAt)-1},{now:NaN},{endsAt:'bad'},{startsAt:'2027-03-20'}])assert.equal(screenItem(a,{...ctx,...patch}),null);assert.equal(screenItem({...a,consent:{...a.consent,expiresAt:new Date(now).toISOString()}},ctx),null);assert.equal(screenItem({...a,consent:{...a.consent,grantedAt:new Date(now+1).toISOString()}},ctx),null);const i=input();i.hashtags=['#foo<script>'];assert.throws(()=>createWallSubmission(i,ctx),/invalid_hashtags/);});
test('sponsor must match event and placement, active dates and approval; no campaign fabricated when missing',()=>{const s={eventId:'event-1',approved:true,placementId:'screen-lower',name:'Synthetic QA sponsor',url:'https://example.test/offer',startsAt:ctx.startsAt,endsAt:ctx.endsAt};const c={...ctx,placementId:'screen-lower'};assert.equal(wallSponsor(s,c).label,'Sponsored');for(const patch of[{eventId:'other'},{approved:false},{placementId:'other'},{removedAt:ctx.startsAt},{revokedAt:ctx.startsAt},{url:'javascript:alert(1)'}])assert.equal(wallSponsor({...s,...patch},c),null);assert.equal(wallSponsor(null,c),null);});

test('approval and screen require positive revisions and chronological submission/consent/moderation',()=>{const pending=createWallSubmission(input(),ctx),a=approved();for(const version of[0,-1,1.5,'1',null]){assert.throws(()=>moderateWallSubmission({...pending,version},{...op,expectedVersion:version}),/invalid_revision/);assert.equal(screenItem({...a,version,moderation:{...a.moderation,version}},ctx),null);}assert.equal(screenItem({...a,submittedAt:'invalid'},ctx),null);assert.equal(screenItem({...a,submittedAt:new Date(now+1).toISOString()},ctx),null);assert.equal(screenItem({...a,moderation:{...a.moderation,at:new Date(now-1).toISOString()}},ctx),null);assert.throws(()=>moderateWallSubmission({...pending,consent:{...pending.consent,grantedAt:new Date(now+1).toISOString()}},op),/invalid_chronology/);for(const entry of[null,undefined,{}])assert.throws(()=>revokeWallSubmission(entry,{}),/not_authorized/);});
