import test from'node:test';import assert from'node:assert/strict';import{CSV_COLUMNS,createReorderProposal,validateCatalog,importServiceCsv,orderEligibility}from'../../assets/events/signature/service-catalog.mjs';
const id='10000000-0000-4000-8000-000000000001',menu='20000000-0000-4000-8000-000000000001';const base=()=>({id,version:1,status:'draft',currency:'CAD',categories:[{id:'drinks',name:'Drinks'}],service_zones:[{id:'floor',label:'Main floor'}],items:[{id:'water',category_id:'drinks',name:'Water',price_cents:350,currency:'CAD',stock:10,service_zones:['floor'],allergens:null,alcohol:false,available:true,menu_item_id:menu}]});const opts=()=>({categories:base().categories,serviceZones:base().service_zones,currency:'CAD'});const csv=line=>CSV_COLUMNS.join(',')+'\n'+line;
test('explicit price, unknown stock/allergens and draft status preserved without inference',()=>{const c=base();c.items[0].stock=null;assert.equal(validateCatalog(c).items[0].stock,null);assert.equal(orderEligibility(c,{expectedVersion:1,zone:'floor',lines:[{item_id:'water',quantity:1}]}).ok,false);for(const bad of[-1,1.2,NaN,null]){const d=base();d.items[0].price_cents=bad;assert.throws(()=>validateCatalog(d));}});
test('CSV quotes, BOM, errors and explicit booleans prevent silent zero/free defaults',()=>{const a=importServiceCsv('\uFEFF'+csv('water,drinks,"Water, still",350,CAD,unknown,floor,unknown,false,true,'),opts());assert.equal(a.items[0].name,'Water, still');assert.equal(a.items[0].stock,null);assert.equal(a.status,'draft');assert.equal(a.can_review,true);const bad=importServiceCsv(csv('water,drinks,Water,,CAD,10,floor,none,,true,'),opts());assert.equal(bad.items.length,0);assert(bad.errors.some(x=>x.field==='price_cents'&&x.row===2));assert(bad.errors.some(x=>x.field==='alcohol'));assert.throws(()=>importServiceCsv('name,price\nWater,3.50',opts()));assert.throws(()=>importServiceCsv(csv('"unterminated'),opts()));});
test('duplicate CSV IDs and unsupported currency produce review errors',()=>{const line='water,drinks,Water,350,CAD,10,floor,none,false,true,';const r=importServiceCsv(csv(line+'\n'+line),opts());assert.equal(r.can_review,false);assert(r.errors.some(x=>x.field==='id'&&x.row===3));assert.throws(()=>importServiceCsv(csv(line),{...opts(),currency:'JPY'}));});
test('eligibility binds exact version, zone, availability, stock, alcohol and real mapping',()=>{const c=base();c.status='approved';const request={expectedVersion:1,zone:'floor',lines:[{item_id:'water',quantity:2}]};assert.equal(orderEligibility(c,request).total_cents,700);assert.equal(orderEligibility(c,{...request,expectedVersion:0}).ok,false);assert.equal(orderEligibility(c,{...request,zone:'booth'}).ok,false);for(const edit of[i=>i.available=false,i=>i.stock=1,i=>i.alcohol=true,i=>i.menu_item_id=null]){const d=base();d.status='approved';edit(d.items[0]);assert.equal(orderEligibility(d,request).ok,false);}assert.equal(orderEligibility(c,{...request,lines:[...request.lines,...request.lines]}).ok,false);assert.equal(orderEligibility(c,request).payment_collected,false);assert.equal(orderEligibility(c,request).reservation_created,false);});

test('reorder proposal contains only exact IDs and version, never stale price or stock writes',()=>{const c=base();c.items.push({...c.items[0],id:'juice',name:'Juice',price_cents:600,menu_item_id:'20000000-0000-4000-8000-000000000002'});const before=JSON.stringify(c),p=createReorderProposal(c,{expectedVersion:1,itemIds:['juice','water']});assert.deepEqual(Object.keys(p).sort(),['catalog_id','expected_version','item_order']);assert.equal(JSON.stringify(c),before);assert.throws(()=>createReorderProposal(c,{expectedVersion:0,itemIds:['juice','water']}));assert.throws(()=>createReorderProposal(c,{expectedVersion:1,itemIds:['water','water']}));assert.throws(()=>createReorderProposal(c,{expectedVersion:1,itemIds:['foreign','water']}));});

test('string or numeric alcohol authorization cannot bypass the strict authorization flag',()=>{const c=base();c.status='approved';c.items[0].alcohol=true;const r={expectedVersion:1,zone:'floor',lines:[{item_id:'water',quantity:1}]};for(const flag of['false','true',1,{},null])assert.equal(orderEligibility(c,{...r,alcoholAuthorized:flag}).ok,false);assert.equal(orderEligibility(c,{...r,alcoholAuthorized:true}).ok,true);});
test('different draft identifiers cannot alias one server item and evade stock checks',()=>{const c=base();c.status='approved';c.items.push({...c.items[0],id:'water-alias',menu_item_id:menu.toUpperCase()});assert.throws(()=>validateCatalog(c),e=>e.errors.some(x=>x.field==='menu_item_id'));const line='water,drinks,Water,350,CAD,10,floor,none,false,true,'+menu;const result=importServiceCsv(csv(line+'\n'+line.replace(/^water,/,'alias,')),opts());assert.equal(result.can_review,false);assert(result.errors.some(x=>x.field==='menu_item_id'));});
test('CSV rejects formula cells, malformed quote tails and explicit invalid booleans without coercion',()=>{for(const name of['=1+1','+SUM(A1:A2)','@SUM(A1:A2)','-1+2']){const result=importServiceCsv(csv('water,drinks,"'+name+'",350,CAD,10,floor,none,false,true,'),opts());assert.equal(result.can_review,false);assert(result.errors.some(x=>x.field==='name'));}assert.throws(()=>importServiceCsv(csv('water,drinks,"Water"oops,350,CAD,10,floor,none,false,true,'),opts()));const quoted=importServiceCsv(csv('water,drinks,"Water ""still""",350,CAD,10,floor,none,false,true,'),opts());assert.equal(quoted.items[0].name,'Water "still"');for(const bool of['TRUE','1','yes',''])assert.equal(importServiceCsv(csv('water,drinks,Water,350,CAD,10,floor,none,'+bool+',true,'),opts()).can_review,false);});
test('undefined stock and imprecise cents fail rather than assuming unlimited or free',()=>{for(const patch of[{stock:undefined},{price_cents:undefined},{price_cents:9007199254740992},{price_cents:'350'},{stock:Infinity}]){const c=base();Object.assign(c.items[0],patch);assert.throws(()=>validateCatalog(c));}});
