import{test}from'node:test';import assert from'node:assert/strict';import{extractSiteImages,sourceImage,supplementaryPages}from'../../supabase/functions/zoi-enrich/_images.js';
const base='https://restaurant.example.org/';
test('JSONLD logo stays logo and real imagery becomes hero',()=>{const r=extractSiteImages('<meta property="og:image" content="/logo.jpg"><img src="/dining.jpg" width="1200">',base,{logo:'/logo.jpg'});assert.equal(r.logo.url,base+'logo.jpg');assert.equal(r.hero.url,base+'dining.jpg');assert.equal(r.photos.length,1);});
test('deduplicates responsive variants, recognizes CSS backgrounds, excludes badges and stock',()=>{const r=extractSiteImages('<img src="/dining-300x200.jpg" srcset="/dining-300x200.jpg 300w, /dining.jpg 1200w"><img src="/dining.jpg.webp"><img src="/app-store.png"><img src="/pexels-photo-123.jpg"><div style="background-image:url(/terrace.jpg)"></div>',base);assert.deepEqual(r.photos.map(x=>x.url),[base+'dining.jpg',base+'terrace.jpg']);});
test('relative image objects and alternate meta attribute order supported',()=>{const r=extractSiteImages('<meta content="/food.jpg" name="twitter:image">',base,{logo:{contentUrl:'/brand.webp'},image:[{url:'/inside.jpg'}]});assert.equal(r.logo.url,base+'brand.webp');assert.equal(r.hero.url,base+'inside.jpg');assert.equal(r.photos.length,2);});
test('rejects private addresses/credentials/data and ignores scripts',()=>{for(const u of ['http://example.org/x.jpg','https://127.0.0.1/x.jpg','https://user:pass@example.org/x','data:image/png,x','https://metadata.internal/x'])assert.equal(sourceImage(u,base),null);assert.equal(extractSiteImages('<script>"<img src=\"/fake.jpg\">"</script>',base).photos.length,0);});
test('supplements only two explicit same-origin contact/gallery pages, not forms or external links',()=>{const pages=supplementaryPages('<a href="/gallery/">Photos</a><a href="/contact/">Contact</a><a href="https://evil.example/contact">Contact</a><a href="/contact?delete=yes">Contact</a>',base);assert.deepEqual(pages,[{url:base+'gallery/',purpose:'gallery'},{url:base+'contact/',purpose:'contact'}]);});

test('small explicit header logos remain available without entering photo gallery',()=>{const r=extractSiteImages('<img src="/brand.png" class="site-logo" width="120" height="40">',base);assert.equal(r.logo.url,base+'brand.png');assert.equal(r.photos.length,0);});
test('empty or page logo values do not resolve into image URLs and logo directories are not photos',()=>{
 const result=extractSiteImages('<img src="https://cdn.example.com/logos/23131.png"><img src="/food_rating.png"><img src="/Melodia_Anzeige.jpeg"><img src="/gyro.jpeg">','https://example.com/',{logo:'',image:'https://example.com/'});
 assert.equal(result.logo.url,'https://cdn.example.com/logos/23131.png');assert.equal(result.hero.url,'https://example.com/gyro.jpeg');assert.equal(result.photos.length,1);
 assert.equal(extractSiteImages('','https://example.com/',{logo:'https://example.com/'}).logo,null);
});
