import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../../api/sitemap.js';
async function run(url,responses){const original=globalThis.fetch;const calls=[];globalThis.fetch=async(url,options)=>{const fn=String(url).split('/').pop();calls.push({fn,args:JSON.parse(options.body),signal:options.signal});const value=responses[fn];if(value instanceof Error)throw value;return new Response(JSON.stringify(value),{status:200})};const headers={};let body='';const res={statusCode:0,setHeader:(k,v)=>headers[k]=v,end:v=>body=v};try{await handler({url},res);return{status:res.statusCode,headers,body,calls}}finally{globalThis.fetch=original}}
test('sitemap index directly lists every bounded page without fabricated modification dates',async()=>{const r=await run('/api/sitemap',{seo_sitemap_stats:{count:2501,lastmod:'2026-01-01'}});assert.equal(r.status,200);assert.equal(r.calls.length,1);assert.match(r.body,/sitemap-listings-3.xml/);assert.doesNotMatch(r.body,/sitemap-listings-4.xml|<lastmod>/)});
test('one listing sitemap executes one bounded page query and escapes XML',async()=>{const r=await run('/api/sitemap?part=listings&page=3',{seo_index:[{slug:'greek & home',entity_type:'business',updated_at:'2026-09-01'}]});assert.equal(r.status,200);assert.deepEqual(r.calls[0].args,{p_limit:1000,p_offset:2000});assert.ok(r.calls[0].signal);assert.match(r.body,/greek%20%26%20home/);assert.match(r.body,/<lastmod>2026-09-01<\/lastmod>/)});
test('invalid pages cannot trigger large offset scans',async()=>{for(const page of ['-1','0','1.5','10001','abc']){const r=await run('/api/sitemap?part=listings&page='+page,{});assert.equal(r.status,400);assert.equal(r.calls.length,0)}});
test('upstream failure is retryable503 rather than empty success',async()=>{const r=await run('/api/sitemap?part=listings',{seo_index:new Error('offline')});assert.equal(r.status,503);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(r.headers['Retry-After'],'60');assert.doesNotMatch(r.body,/<urlset/)});
test('partial place queries never cache a partial sitemap',async()=>{const r=await run('/api/sitemap?part=places',{explore_countries:[],explore_regions:new Error('offline'),explore_region_cities:[],explore_categories:[],explore_region_categories:[]});assert.equal(r.status,503)});
test('malformed database response is not indexable content',async()=>{const r=await run('/api/sitemap',{seo_sitemap_stats:{count:'many'}});assert.equal(r.status,503)});
