import test from'node:test';import assert from'node:assert/strict';import{extractSourceCoordinates,reviewCoordinateCandidate,coordinateSnapshot,canonicalCountry}from'../../scripts/geography/source-coordinates.mjs';import{canonical,sha256}from'../../scripts/quality/evidence.mjs';
const row={id:'test',name:'Actual Restaurant',website:'https://official.example.org/',address:'10 Main Street',city:'Melbourne',country:'Australia',latitude:null,longitude:null,public_eligible:true,source_kind:'official_website',source_fingerprint:'source1',owner_hash:'owner1'};
const node={ '@type':'Restaurant',name:row.name,url:row.website,address:{'@type':'PostalAddress',streetAddress:row.address,addressLocality:row.city,addressCountry:row.country},geo:{'@type':'GeoCoordinates',latitude:-37.81,longitude:144.96}};
const html=n=>'<script type="application/ld+json">'+JSON.stringify(n)+'</script>';
const review=r=>({report_sha256:sha256(canonical(r)),reviewer:'independent-review',reviewed_at:'2026-09-30',exact_address_confirmed:true,not_area_centroid:true,locality_extent:{source_url:'https://official.example.org/location',south:-38,north:-37,west:144,east:146}});
test('exact official structured address coordinates remain a review candidate, never a write',()=>{const r=extractSourceCoordinates(html(node),row);assert.equal(r.candidate.latitude,-37.81);assert.equal(r.status,'review_required');assert.equal(r.coordinate_writes,0);assert.equal(reviewCoordinateCandidate(r,review(r),row).status,'reviewed_pending_guarded_writer')});
test('other city, country, branch street or organization cannot supply this place coordinates',()=>{for(const patch of[{addressLocality:'Sydney'},{addressCountry:'Canada'},{streetAddress:'11 Main Street'}])assert(!extractSourceCoordinates(html({...node,address:{...node.address,...patch}}),row).candidate);assert(!extractSourceCoordinates(html({...node,name:'Other Company'}),row).candidate)});
test('random HTML GPS, invalid range and swapped coordinates are never silently repaired',()=>{assert(!extractSourceCoordinates('latitude=-37.81 longitude=144.96',row).candidate);for(const geo of[{latitude:144.96,longitude:-37.81},{latitude:91,longitude:12},{latitude:null,longitude:12}])assert(!extractSourceCoordinates(html({...node,geo:{'@type':'GeoCoordinates',...geo}}),row).candidate);const r=extractSourceCoordinates(html({...node,geo:{'@type':'GeoCoordinates',latitude:20,longitude:30}}),row);assert.throws(()=>reviewCoordinateCandidate(r,review(r),row),/outside_reviewed_locality/)});
test('owner edits, changed source/address and centroid approval fail closed',()=>{const r=extractSourceCoordinates(html(node),row);for(const patch of[{owner_hash:'changed'},{address:'Moved'},{source_fingerprint:'changed'},{owner_managed:true}])assert.throws(()=>reviewCoordinateCandidate(r,review(r),{...row,...patch}),/snapshot_changed/);assert.throws(()=>reviewCoordinateCandidate(r,{...review(r),not_area_centroid:false},row),/review_required/);assert.equal(extractSourceCoordinates(html(node),{...row,owner_managed:true}).reason,'owner_managed')});
test('two conflicting structured locations require review and external redirects are refused',()=>{assert.equal(extractSourceCoordinates(html([node,{...node,geo:{...node.geo,latitude:-37.82}}]),row).reason,'conflicting_source_coordinates');assert.equal(extractSourceCoordinates(html(node),row,{sourceUrl:'https://other.example.org/'}).reason,'source_identity_mismatch')});
import{auditCoordinateSources}from'../../scripts/geography/source-coordinate-audit.mjs';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
test('dry-run batch caps records, never fetches owner-managed sources and writes reports only',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'zoi-geo-'));let calls=0;try{const fetcher=async()=>{calls++;return{status:200,url:row.website,text:html(node)}};const result=await auditCoordinateSources([row,{...row,id:'owned',owner_managed:true}],{directory:dir,sourceFetch:fetcher});assert.equal(calls,1);assert.equal(result.coordinate_writes,0);assert.equal(result.provider_calls,0);assert.equal(result.reports[1].reason,'owner_managed');await assert.rejects(()=>auditCoordinateSources([row,row],{directory:dir,sourceFetch:fetcher}),/canary_limit/);}finally{await rm(dir,{recursive:true,force:true})}});

test('composite postal addresses and pinned ISO country codes match without fuzzy street aliases',()=>{const n={...node,address:{...node.address,streetAddress:'177-183 Lonsdale Street',addressRegion:'VIC',postalCode:'3000',addressCountry:'AU'}};const current={...row,address:'177-183 Lonsdale Street, Melbourne VIC 3000'};assert(extractSourceCoordinates(html(n),current).candidate);assert.equal(canonicalCountry('AUS'),'AU');assert(!extractSourceCoordinates(html(n),{...current,address:'177-183 Other Street, Melbourne VIC 3000'}).candidate);assert(!extractSourceCoordinates(html(n),{...current,country:'Austria'}).candidate);});
const aliasFor=(text,current,address)=>({listing_id:current.id,snapshot_sha256:coordinateSnapshot(current),source_url:current.website,source_sha256:sha256(text),reviewer:'reviewer',reviewed_at:'2026-10-01',exact_address_confirmed:true,source_address:address});
test('explicit address reconciliation is tied to exact name/source snapshot and source bytes',()=>{const n={...node,address:{...node.address,addressLocality:'Reviewed suburb'}};const text=html(n),a={street:row.address,city:'Reviewed suburb',country:'Australia'},identity=aliasFor(text,row,a);assert(extractSourceCoordinates(text,row,{identityReview:identity}).candidate);for(const patch of[{name:'Other name'},{address:'Other street'},{owner_hash:'new'}])assert.equal(extractSourceCoordinates(text,{...row,...patch},{identityReview:identity}).reason,'identity_review_mismatch');assert.equal(extractSourceCoordinates(text+' ',row,{identityReview:identity}).reason,'identity_review_mismatch');assert(!extractSourceCoordinates(text,row).candidate);});
const destination='https://www.google.com/maps/dir//Actual+Restaurant,+10+Main+Street,+Melbourne,+Australia/@20,30,15z/data=!4m8!4m7!1m0!1m5!1m1!1s0x123:0x456!2m2!1d144.96!2d-37.81';
test('official destination uses reviewed named address and destination pair, not camera coordinates',()=>{const text='<footer><a href="'+destination+'">Find our restaurant</a></footer>',identity={...aliasFor(text,row,{street:row.address,city:row.city,country:row.country}),destination_url:destination,destination_purpose:'place_location'};const result=extractSourceCoordinates(text,row,{identityReview:identity});assert.equal(result.candidate.latitude,-37.81);assert.equal(result.candidate.longitude,144.96);assert.equal(result.candidate.evidence_kind,'official_destination');assert.equal(result.identity_review_sha256,sha256(canonical(identity)));assert(!extractSourceCoordinates(text,row).candidate);});
test('parking, shortlink, other destination, camera-only and multi-stop links never become place pins',()=>{for(const [url,label]of [[destination,'Parking garage directions'],[destination,'Nearby recommendation'],[destination.replace('Actual+Restaurant','Other+Restaurant'),'Directions'],['https://maps.app.goo.gl/example','Directions'],[destination.split('/data=')[0],'Directions'],[destination.replace('/dir//','/dir/First+Stop/'),'Directions']]){const text='<section><h2>'+label+'</h2><a href="'+url+'">Map</a></section>',identity={...aliasFor(text,row,{street:row.address,city:row.city,country:row.country}),destination_url:url,destination_purpose:'place_location'};assert(!extractSourceCoordinates(text,row,{identityReview:identity}).candidate);}});
import{readFileSync}from'node:fs';
test('retained real source fragments yield Melbourne schema and reviewed AMARA destination',()=>{const mel=readFileSync(new URL('../fixtures/geography/stalactites-coordinate.source.txt',import.meta.url),'utf8'),mrow={...row,name:'Stalactites Restaurant',website:'https://www.stalactites.com.au/',address:'177-183 Lonsdale Street, Melbourne VIC 3000'};assert.deepEqual([extractSourceCoordinates(mel,mrow).candidate.latitude,extractSourceCoordinates(mel,mrow).candidate.longitude],[-37.8110808,144.9670491]);const amara=readFileSync(new URL('../fixtures/geography/amara-destination.source.txt',import.meta.url),'utf8'),arow={...row,name:'Amara Hotel',website:'https://www.amarahotel.com/',address:'Amathountos, Limassol',city:'Limassol',country:'Cyprus'},url=amara.match(/href="([^"]+)/)[1],identity={...aliasFor(amara,arow,{street:'95 Amathus Avenue',city:'Agios Tychon',postal_code:'4533',country:'Cyprus'}),destination_url:url,destination_purpose:'place_location'},r=extractSourceCoordinates(amara,arow,{identityReview:identity});assert.deepEqual([r.candidate.latitude,r.candidate.longitude],[34.7136232,33.1552567]);assert.equal(r.status,'review_required');});

test('same-domain sibling branch redirects and schema identities fail closed',()=>{const branch={...row,website:'https://official.example.org/hotel-a/'};assert.equal(extractSourceCoordinates(html(node),branch,{sourceUrl:'https://official.example.org/hotel-b/'}).reason,'source_identity_mismatch');assert(!extractSourceCoordinates(html({...node,url:'https://official.example.org/hotel-b/'}),branch).candidate);});
test('batch audit carries the frozen identity review into the immutable source report',async()=>{const text='<a href="'+destination+'">Our location</a>',identity={...aliasFor(text,row,{street:row.address,city:row.city,country:row.country}),destination_url:destination,destination_purpose:'place_location'},dir=await mkdtemp(path.join(tmpdir(),'zoi-geo-review-'));try{const result=await auditCoordinateSources([row],{directory:dir,sourceFetch:async()=>({status:200,url:row.website,text}),identityReviews:{[row.id]:identity}});const report=JSON.parse(readFileSync(path.join(dir,result.reports[0].report_sha256+'.json'),'utf8'));assert.equal(report.candidate.evidence_kind,'official_destination');assert.equal(report.identity_review_sha256,sha256(canonical(identity)));assert.equal(result.coordinate_writes,0);}finally{await rm(dir,{recursive:true,force:true})}});

test('non-document anchor strings and malformed report approvals fail closed',()=>{for(const wrapper of [x=>'<!--'+x+'-->',x=>'<script>const sample='+JSON.stringify(x)+'</script>',x=>'<style>'+x+'</style>',x=>'<template>'+x+'</template>']){const text=wrapper('<a href="'+destination+'">Our location</a>'),identity={...aliasFor(text,row,{street:row.address,city:row.city,country:row.country}),destination_url:destination,destination_purpose:'place_location'};assert(!extractSourceCoordinates(text,row,{identityReview:identity}).candidate);}const r=extractSourceCoordinates(html(node),row);for(const patch of[{schema:2},{kind:'other'},{status:'applied'},{reason:'other'},{http_status:503}]){const bad={...r,...patch};assert.throws(()=>reviewCoordinateCandidate(bad,review(bad),row),/report_invalid/);}const own={...r,collector:' Independent-Review '};assert.throws(()=>reviewCoordinateCandidate(own,review(own),row),/independent_coordinate_review/);});
const agoraSource=readFileSync(new URL('../fixtures/geography/agora-location.source.txt',import.meta.url),'utf8'),agoraRow={...row,name:'Agora',website:'https://agora.london/',city:'London',country:'United Kingdom',address:'Bedale Street, Borough Market, London SE1 9AL'},agoraAddress={street:'2-4 Bedale Street',city:'London',region:'England',postal_code:'SE1 9AL',country:'United Kingdom'};
test('typed Squarespace site location requires exact reviewed postal identity and separate schema corroboration',()=>{assert(!extractSourceCoordinates(agoraSource,agoraRow).candidate);const r=extractSourceCoordinates(agoraSource,agoraRow,{identityReview:aliasFor(agoraSource,agoraRow,agoraAddress)});assert.equal(r.candidate.evidence_kind,'squarespace_website_location');assert.deepEqual([r.candidate.latitude,r.candidate.longitude],[51.505369,-0.08999159999999999]);assert.equal(r.status,'review_required');assert.equal(r.coordinate_writes,0);});
test('Squarespace extraction rejects arbitrary JS, sparse config, branches and identity mismatch',()=>{for(const text of [agoraSource.replace('Static.SQUARESPACE_CONTEXT =','other ='),agoraSource.replace('"website":','"gallery":'),agoraSource.replace('"mapLat": 51.505369','"mapLat": null'),agoraSource.replace('www.agora.london','other.london'),agoraSource.replace('"addressTitle": "AGORA "','"addressTitle": "OTHER"'),agoraSource.replace('application/ld+json','text/plain'),agoraSource.replace('"LocalBusiness"','"WebSite"'),agoraSource.replace(';</script>','; evil();</script>'),'<!--'+agoraSource+'-->','<template>'+agoraSource+'</template>',agoraSource+agoraSource]){assert(!extractSourceCoordinates(text,agoraRow,{identityReview:aliasFor(text,agoraRow,agoraAddress)}).candidate);}const branch={...agoraRow,website:'https://agora.london/other-branch/'};assert(!extractSourceCoordinates(agoraSource,branch,{identityReview:aliasFor(agoraSource,branch,agoraAddress)}).candidate);});
test('Squarespace coordinates conflict with a separately matching structured point rather than replacing it',()=>{const n={'@type':'Restaurant',name:agoraRow.name,url:agoraRow.website,address:{'@type':'PostalAddress',streetAddress:agoraAddress.street,addressLocality:agoraAddress.city,addressRegion:agoraAddress.region,postalCode:agoraAddress.postal_code,addressCountry:agoraAddress.country},geo:{'@type':'GeoCoordinates',latitude:51.51,longitude:-0.09}};const text=agoraSource+html(n);const result=extractSourceCoordinates(text,agoraRow,{identityReview:aliasFor(text,agoraRow,agoraAddress)});assert.equal(result.reason,'conflicting_source_coordinates');assert(!result.candidate);assert.equal(result.coordinate_writes,0);});

test('inert structured JSON-LD cannot supply coordinates or introduce conflicts',()=>{for(const wrap of [x=>'<!--'+x+'-->',x=>'<template>'+x+'</template>',x=>'<noscript>'+x+'</noscript>',x=>'<style>'+x+'</style>']){assert(!extractSourceCoordinates(wrap(html(node)),row).candidate);const other={...node,geo:{...node.geo,latitude:-37.82}};assert.equal(extractSourceCoordinates(html(node)+wrap(html(other)),row).candidate.latitude,-37.81);}});
test('explicit source name alias is exact and bound to current property snapshot, source bytes and address',()=>{
 const current={...row,name:'Parkview Manor Banquet Hall',website:'https://www.parkviewmanor.ca/',address:'55 Barber Greene Rd #1, North York',city:'North York',country:'Canada'};
 const sourceNode={'@type':'Restaurant',name:'Parkview Manor',url:current.website,address:{'@type':'PostalAddress',streetAddress:'55 Barber Greene Road',addressLocality:'Toronto',addressRegion:'ON',postalCode:'M3C2A1',addressCountry:'CA'},geo:{'@type':'GeoCoordinates',latitude:43.7273636,longitude:-79.3447087}};
 const source=html(sourceNode),address={street:'55 Barber Greene Road',city:'Toronto',region:'ON',postal_code:'M3C2A1',country:'Canada'},identity={...aliasFor(source,current,address),source_name:'Parkview Manor',exact_name_confirmed:true};
 assert(!extractSourceCoordinates(source,current,{identityReview:aliasFor(source,current,address)}).candidate);
 const r=extractSourceCoordinates(source,current,{identityReview:identity});assert.equal(r.status,'review_required');assert.equal(r.candidate.name,'Parkview Manor');assert.equal(r.candidate.stored_name,current.name);assert.equal(r.candidate.name_identity_review_sha256,r.identity_review_sha256);assert.equal(r.coordinate_writes,0);
 for(const patch of [{name:'Another venue'},{address:'Another address'},{website:'https://other.test/'},{owner_hash:'changed'}])assert.equal(extractSourceCoordinates(source,{...current,...patch},{identityReview:identity}).reason,'identity_review_mismatch');
 for(const patch of [{exact_name_confirmed:false},{source_name:'Other Parkview Manor'},{source_name:''},{source_name:42},{source_address:{...address,street:'55 Other Road'}}])assert(!extractSourceCoordinates(source,current,{identityReview:{...identity,...patch}}).candidate);
 const other=html({...sourceNode,url:'https://unrelated.test/'});assert(!extractSourceCoordinates(other,current,{identityReview:{...identity,source_sha256:sha256(other)}}).candidate);
 const branch={...current,website:'https://www.parkviewmanor.ca/property-a/'};const sibling=html({...sourceNode,url:'https://www.parkviewmanor.ca/property-b/'});assert(!extractSourceCoordinates(sibling,branch,{identityReview:{...aliasFor(sibling,branch,address),source_name:'Parkview Manor',exact_name_confirmed:true}}).candidate);
 assert.equal(extractSourceCoordinates(source+' ',current,{identityReview:identity}).reason,'identity_review_mismatch');
});
