import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,readFile,readdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{captureSourceHTML,rasterHeader}from'../../scripts/enrichment/source-html.mjs';import{captureRows}from'../../scripts/enrichment/render-capture.mjs';import{sha256}from'../../scripts/quality/evidence.mjs';import{automaticRenderedPayload}from'../../scripts/enrichment/render-queue.mjs';
const row={listing_id:'11111111-1111-4111-8111-111111111111',name:'Example Hotel',entity_type:'travel_place',slug:'example-hotel',website:'https://hotel.org/',source_fingerprint:'current-fingerprint'};
const prose='Example Hotel welcomes guests to its garden rooms and traditional guest house. Contact the hotel directly to discuss your stay and the published room types.';
const html=(extra='')=>`<html><head><title>Example Hotel</title></head><body><h1>Example Hotel</h1><p>${prose}</p><a href="tel:+302410123456">Contact</a>${extra}</body></html>`;
const png=(width=640,height=480)=>{const b=Buffer.alloc(40);Buffer.from('89504e470d0a1a0a','hex').copy(b);b.writeUInt32BE(13,8);b.write('IHDR',12);b.writeUInt32BE(width,16);b.writeUInt32BE(height,20);return b;};
function fixture(doc=html(),response={}){const calls=[];return{calls,stats:{requests:0,bytes:0},async sourceFetch(url){calls.push(url);return url===row.website?{status:200,text:doc,url}:{status:200,body:png(),headers:{'content-type':'image/png'},url,...response};}};}
async function temp(fn){const directory=await mkdtemp(path.join(tmpdir(),'source-html-'));try{return await fn(directory);}finally{await rm(directory,{recursive:true,force:true});}}
const decoderFactory=async()=>({decode:async()=>({width:640,height:480}),close:async()=>{}});
test('substantive SSR reuses extractor without browser or rendered evidence',()=>temp(async directory=>{const session=fixture();const report=await captureSourceHTML(row,{directory,session,decoderFactory:async()=>{throw Error('unexpected decoder');}});assert.equal(report.schema,2);assert.equal(report.capture_kind,'source_html');assert.equal(report.render,null);assert.equal(report.source.requires_rendering,false);assert.equal(report.profile.phone,'+302410123456');assert.equal(report.source_fingerprint,row.source_fingerprint);assert.equal(report.source.sha256,sha256(html()));assert.equal(report.review_required,true);assert.equal(session.calls.length,1);assert.equal(automaticRenderedPayload({...row,lease_id:'lease'},report,'hash').profile.last_error,'rendered_source_incomplete');}));
test('image bytes must pass signature, decoder and immutable receipt verification',()=>temp(async directory=>{const session=fixture(html('<img src="/garden.png" alt="Hotel garden">'));const report=await captureSourceHTML(row,{directory,session,decoderFactory});assert.equal(report.images.length,1);const image=report.images[0];assert.equal(image.sha256,sha256(png()));assert.deepEqual(image,{url:'https://hotel.org/garden.png',final_url:'https://hotel.org/garden.png',sha256:sha256(png()),mime:'image/png',bytes:40,width:640,height:480,role:'photo'});assert.deepEqual(await readFile(path.join(directory,image.sha256+'.image')),png());assert.deepEqual(report.profile.photo_urls,[image.url]);assert.equal(report.profile.hero_url,image.url);}));
test('raster header validates MIME signatures and bounded dimensions before decoder allocation',()=>{assert.deepEqual(rasterHeader(png(),'image/png'),{mime:'image/png',width:640,height:480});for(const[mime,bytes]of[['image/png',Buffer.from('<html>no</html>')],['image/jpeg',png()],['image/svg+xml',Buffer.from('<svg/>')],['image/png',png(12001,1)],['image/png',png(10000,10000)]])assert.throws(()=>rasterHeader(bytes,mime),/source_image_/);const jpg=Buffer.from([255,216,255,192,0,8,8,1,224,2,128,0,255,217]);assert.deepEqual(rasterHeader(jpg,'image/jpeg'),{mime:'image/jpeg',width:640,height:480});});
test('challenge, JS shell, sparse and missing fingerprint fail before image or browser access',()=>temp(async directory=>{for(const[doc,error]of[['<title>One moment, please...</title><body>Please wait while your request is being verified...</body>','source_challenge'],['<body><div id="root"></div><script src="/app.js"></script></body>','javascript_render_required'],['<title>Example Hotel</title><body>Hello</body>','source_html_sparse']]){const session=fixture(doc);await assert.rejects(captureSourceHTML(row,{directory,session,decoderFactory:async()=>{throw Error('unexpected');}}),new RegExp(error));assert.equal(session.calls.length,1);}const session=fixture();await assert.rejects(captureSourceHTML({...row,source_fingerprint:''},{directory,session}),/source_capture_fingerprint_missing/);assert.equal(session.calls.length,0);}));
test('substantive contact CAPTCHA is not a whole-page challenge',()=>temp(async directory=>{const report=await captureSourceHTML(row,{directory,session:fixture(html('<form>Verify you are human before sending your enquiry.</form>'))});assert.equal(report.profile.phone,'+302410123456');}));
test('identity conflicts, member scope and aggregators refuse source-only content',()=>temp(async directory=>{
 const missing=fixture();await assert.rejects(captureSourceHTML({...row,name:null},{directory,session:missing}),/source_identity_scope_review/);assert.equal(missing.calls.length,0);
 const member=fixture();await assert.rejects(captureSourceHTML({...row,name:'Ageliki Tzakis',entity_type:'professional',website:'https://www.hellenicmedical.ca/profile/atzakis/'},{directory,session:member}),/source_identity_scope_review/);assert.equal(member.calls.length,0);
 const conflict='<title>Casino Betting Jackpot Deposit</title><body>'+prose.replace('Example Hotel','Other brand')+' sports betting jackpot deposit bonus</body>';await assert.rejects(captureSourceHTML(row,{directory,session:fixture(conflict)}),/source_identity_scope_review/);
 await assert.rejects(captureSourceHTML({...row,website:'https://yelp.com/hotel'},{directory,session:{stats:{},sourceFetch:async()=>({status:200,text:html(),url:'https://yelp.com/hotel'})}}),/source_identity_scope_review/);
}));
test('invalid or unreviewable images cannot enter photo fields',()=>temp(async directory=>{for(const response of[{body:Buffer.from('<html>missing</html>')},{headers:{'content-type':'text/html'}},{body:png(40,30)},{status:404},{url:'https://different.org/garden.png'}]){let decoded=0;const report=await captureSourceHTML(row,{directory,session:fixture(html('<img src="/garden.png">'),response),decoderFactory:async()=>{decoded++;return decoderFactory();}});assert.equal(report.images.length,0);assert.equal(report.profile.hero_url,undefined);assert.equal(report.rejected_images.length,1);assert.equal(decoded,0);}}));
test('decoder corruption or dimension mismatch rejects image and closes decoder',()=>temp(async directory=>{for(const fail of[true,false]){let closed=0;const report=await captureSourceHTML(row,{directory,session:fixture(html('<img src="/garden.png">')),decoderFactory:async()=>({decode:async()=>{if(fail)throw Error('decode failed');return{width:1,height:1};},close:async()=>{closed++;}})});assert.equal(report.images.length,0);assert.equal(closed,1);}}));
test('four-image cap and cumulative deadline prevent an unbounded photo crawl',()=>temp(async directory=>{const session=fixture(html(Array.from({length:9},(_,i)=>`<img src="/garden${i}.png">`).join('')));const report=await captureSourceHTML(row,{directory,session,decoderFactory});assert.equal(report.images.length,4);assert.equal(session.calls.length,5);let calls=0;await assert.rejects(captureSourceHTML(row,{directory,timeoutMs:15,session:{stats:{},sourceFetch:async()=>{calls++;await new Promise(r=>setTimeout(r,40));return{status:200,text:html(),url:row.website};}}}),/source_time_budget/);assert.equal(calls,1);}));
test('source HTML capture resume namespace cannot reuse legacy rendered failure',()=>temp(async directory=>{let calls=0;const render=async()=>{calls++;return{schema:2,capture_kind:'source_html',render:null,profile:{phone:'123'},review_required:true};};await captureRows([row],{directory,render:async()=>{throw Error('source_render_timeout');}});const first=await captureRows([row],{directory,captureKind:'source_html',render});const second=await captureRows([row],{directory,captureKind:'source_html',render});assert.equal(calls,1);assert.equal(first[0].status,'captured_pending_review');assert.equal(second[0].resumed,true);assert.equal((await readdir(directory)).filter(x=>x.endsWith('.capture.json')).length,2);const report=JSON.parse(await readFile(path.join(directory,first[0].hash+'.json')));assert.equal(report.source_fingerprint,row.source_fingerprint);}));
test('protected decoder is offline and receives image bytes only, never source HTML',()=>temp(async directory=>{
 let launchOptions,contextOptions,routeRule,websocketRule,closed=0,received;
 const page={goto:async url=>assert.equal(url,'about:blank'),evaluate:async(fn,args)=>{received=args;assert.equal(typeof fn,'function');return{width:640,height:480};}};
 const context={route:async(pattern,handler)=>{assert.equal(pattern,'**/*');let aborted=false;await handler({abort:()=>{aborted=true;}});routeRule=aborted;},routeWebSocket:async(pattern,handler)=>{let stopped=false;handler({close:()=>{stopped=true;}});websocketRule=stopped;},newPage:async()=>page,close:async()=>{closed++;}};
 const report=await captureSourceHTML(row,{directory,session:fixture(html('<img src="/garden.png">')),launch:async opts=>{launchOptions=opts;return{newContext:async opts=>{contextOptions=opts;return context;},close:async()=>{closed++;}};}});
 assert.equal(launchOptions.chromiumSandbox,true);assert(!launchOptions.args.includes('--no-sandbox'));assert.equal(contextOptions.offline,true);assert.equal(contextOptions.serviceWorkers,'block');assert.equal(routeRule,true);assert.equal(websocketRule,true);assert.deepEqual(Buffer.from(received.base64,'base64'),png());assert.deepEqual(Object.keys(received).sort(),['base64','mime']);assert.equal(closed,2);assert.equal(report.images.length,1);
}));
test('robots/DNS refusals propagate and no alternate insecure source is attempted',()=>temp(async directory=>{for(const reason of['robots_disallow','unsafe_source_dns','source_byte_budget']){let calls=0;await assert.rejects(captureSourceHTML(row,{directory,session:{stats:{},sourceFetch:async()=>{calls++;throw Error(reason);}}}),new RegExp(reason));assert.equal(calls,1);}await assert.rejects(captureSourceHTML({...row,website:'http://hotel.org/'},{directory,session:fixture()}),/unsafe_source_url/);}));
test('source HTML failure receipt remains mode and fingerprint bound',()=>temp(async directory=>{const receipt=await captureRows([row],{directory,captureKind:'source_html',render:async()=>{throw Error('javascript_render_required');}});const report=JSON.parse(await readFile(path.join(directory,receipt[0].hash+'.json')));assert.equal(report.schema,2);assert.equal(report.capture_kind,'source_html');assert.equal(report.render,null);assert.equal(report.reason,'javascript_render_required');assert.equal(report.source_fingerprint,row.source_fingerprint);assert.equal(report.profile,undefined);}));
test('immutable review artifact includes sanitized source facts but excludes inline executable configuration',()=>temp(async directory=>{const doc=html('<script>window.CONFIG="private-value"</script><input value="form-secret"><p onclick="send()">Published room details</p>');const report=await captureSourceHTML(row,{directory,session:fixture(doc)});assert.ok(report.html.includes('Published room details'));assert.ok(!report.html.includes('private-value'));assert.ok(!report.html.includes('form-secret'));assert.ok(!report.html.includes('onclick'));assert.equal(report.source.sha256,sha256(doc));}));
test('source capture retains explicit email conflict and null machine value for reviewed quarantine',()=>temp(async directory=>{const doc=html('<script type="application/ld+json">{"@type":"Hotel","email":"stale@hotel.org"}</script><a href="mailto:current@hotel.org">Contact</a>');const report=await captureSourceHTML(row,{directory,session:fixture(doc)});assert.equal(report.profile.email,null);assert.deepEqual(report.profile.email_conflict,{structured:'stale@hotel.org',linked:['current@hotel.org'],source_url:row.website});assert.equal(report.provenance.email,'official-source-html:'+row.website);}));
test('source capture retains resolved conflict null only alongside valid extracted contact',()=>temp(async directory=>{const report=await captureSourceHTML(row,{directory,session:fixture(html('<a href="mailto:current@hotel.org">Contact</a>'))});assert.equal(report.profile.email,'current@hotel.org');assert.equal(report.profile.email_conflict,null);const absent=await captureSourceHTML(row,{directory,session:fixture(html())});assert.equal(Object.hasOwn(absent.profile,'email_conflict'),false);}));
