import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {inventoryDraft,priceCents,createInventoryEditor} from '../../assets/tickets/table-inventory-model.mjs';
const event='40000000-0000-4000-8000-000000000001',workspace='30000000-0000-4000-8000-000000000001',table='60000000-0000-4000-8000-000000000001',request='70000000-0000-4000-8000-000000000001';
const available=[{table_id:table,label:'Actual table',capacity:10}],draft=()=>({starts_at:new Date(Date.now()+86400000).toISOString(),enabled:false,tables:[{table_id:table,source_label:'Source 8',capacity:10,min_party_size:8,price_per_guest_cents:12500,currency:'CAD',fees_included:true}]}),snapshot={ok:true,event_id:event,version:0,enabled:false,starts_at:null,tables:[],available_tables:available,payment_enabled:false},receipt={ok:true,event_id:event,version:1,enabled:false,payment_enabled:false};
function setup(call){let actor='account-a';const values=new Map(),storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};const options={call,workspace,event,getActor:()=>actor,storage,randomUUID:()=>request};return {editor:createInventoryEditor(options),options,values,setActor:a=>actor=a};}
test('explicit money, actual table identity and capacities are mandatory',()=>{assert.equal(priceCents('125.05'),12505);for(const s of ['','1e2','-1','12.001'])assert.throws(()=>priceCents(s));assert.equal(inventoryDraft(draft(),available).tables[0].capacity,10);for(const field of [{currency:''},{fees_included:false},{capacity:11},{min_party_size:0},{table_id:request}]){const d=draft();Object.assign(d.tables[0],field);assert.throws(()=>inventoryDraft(d,available));}assert.throws(()=>inventoryDraft({...draft(),starts_at:'2027-03-20T20:00'},available));});
test('lost response preserves nonce only and exact reviewed payload on retry',async()=>{const calls=[];let fail=true;const x=setup(async(n,p)=>{if(n.endsWith('_operator'))return snapshot;calls.push(structuredClone(p));if(fail){fail=false;throw Error('connection lost');}return receipt;});await x.editor.load();const d=draft();await assert.rejects(x.editor.save(d));d.tables[0].price_per_guest_cents=1;assert.equal(x.values.size,1);assert.equal([...x.values.values()][0].includes('price'),false);await assert.rejects(x.editor.save(d),/previous save/);await x.editor.retry();assert.deepEqual(calls[0],calls[1]);assert.equal(x.values.size,0);});
test('reload recovers receipt without private draft and never retries a new payload',async()=>{let save=false;const x=setup(async n=>{if(n.endsWith('_operator'))return snapshot;if(n.endsWith('_receipt'))return {ok:true,found:true,receipt};save=true;throw Error('lost');});await x.editor.load();await assert.rejects(x.editor.save(draft()));const second=createInventoryEditor(x.options);assert.equal(second.state().canRetry,false);await assert.rejects(second.retry(),/not stored/);assert.deepEqual(await second.recover(),receipt);assert.equal(x.values.size,0);assert.equal(save,true);});
test('missing or malformed recovery stays blocked; an unknown response is not success',async()=>{const x=setup(async n=>n.endsWith('_operator')?snapshot:n.endsWith('_receipt')?{ok:true,found:false}:{});await x.editor.load();await assert.rejects(x.editor.save(draft()),/could not be verified/);assert.equal(await x.editor.recover(),null);assert(x.editor.state().pending);});
test('account change fences late save receipt and keeps original account marker',async()=>{let done;const x=setup(async n=>n.endsWith('_operator')?snapshot:new Promise(r=>done=r));await x.editor.load();const pending=x.editor.save(draft());x.setActor('account-b');x.editor.sync();done(receipt);await assert.rejects(pending,/account changed/);assert.equal(x.editor.state().pending,null);assert.equal(x.values.size,1);x.setActor('account-a');x.editor.sync();assert.equal(x.editor.state().pending.request,request);});
test('storage failure prevents sending configure request',async()=>{let writes=0;const x=setup(async n=>{if(n.endsWith('_operator'))return snapshot;writes++;return receipt;});x.options.storage.setItem=()=>{throw Error('storage unavailable');};await x.editor.load();await assert.rejects(x.editor.save(draft()),/storage unavailable/);assert.equal(writes,0);});
test('actual dashboard integrates scoped module, closes on workspace change, not legacy redirect',()=>{const html=readFileSync(new URL('../../tickets/index.html',import.meta.url),'utf8');assert.match(html,/data-act="tableinventory"/);assert.match(html,/function switchWs\(\)\{ organizerEpoch\+\+;resetOrganizerTools\(\)/);assert.match(html,/function resetOrganizerTools\(\)\{closeGen\(\);closeDrawer\(\)/);assert.match(html,/function signOut\(\)\{ closeGen\(\)/);assert.match(html,/DASH\.ws===workspace\?gaIdentity\(\)\.actor:null/);assert.match(html,/table-inventory-operator\.mjs/);});
test('definite version conflict releases nonce and requires current settings reload',async()=>{let conflict=true;const x=setup(async n=>{if(n.endsWith('_operator'))return snapshot;if(conflict){conflict=false;const error=Error('version_conflict');error.status=400;throw error;}return receipt;});await x.editor.load();await assert.rejects(x.editor.save(draft()),/version_conflict/);assert.equal(x.editor.state().pending,null);assert.equal(x.values.size,0);await assert.rejects(x.editor.save(draft()),/Load the current/);await x.editor.load();await x.editor.save(draft());});
test('owner editor listens to the actual shared Core auth event',()=>{const core=readFileSync(new URL('../../assets/zoi-core.js',import.meta.url),'utf8'),ui=readFileSync(new URL('../../assets/tickets/table-inventory-operator.mjs',import.meta.url),'utf8');assert.match(core,/CustomEvent\('zoi:auth-change'/);assert.match(ui,/'zoi:auth-change'/);});
test('a refusal after an uncertain attempt never discards its nonce',async()=>{let count=0;const x=setup(async n=>{if(n.endsWith('_operator'))return snapshot;if(count++===0)throw Error('Lost response');const error=Error('not_authorized');error.status=403;throw error;});await x.editor.load();await assert.rejects(x.editor.save(draft()));await assert.rejects(x.editor.retry(),/not_authorized/);assert.equal(x.editor.state().pending.request,request);assert.equal(x.values.size,1);});
test('corrupt saved references fail closed rather than enabling a duplicate save',async()=>{const x=setup(async()=>snapshot);x.values.set(`zoi_table_config:account-a:${workspace}:${event}`,'broken JSON');const editor=createInventoryEditor(x.options);await editor.load();assert.equal(editor.state().pending.unreadable,true);await assert.rejects(editor.save(draft()),/previous save/);await assert.rejects(editor.recover(),/could not be read/);});
