import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync(new URL('../../tickets/index.html',import.meta.url),'utf8');
const close=html.match(/^function closeConfirm\(\).*$/m)?.[0];
const show=html.slice(html.indexOf('function showConfirm('),html.indexOf('\nfunction closeConfirm('));
function fixture(){
 let active=null,fallback=0;const nodes=new Map(),buttons=[];
 const element=(id,visible=true)=>{const classes=new Set();const e={id,isConnected:true,disabled:false,hidden:false,style:{},textContent:'',innerHTML:'',dataset:{},classList:{contains:k=>classes.has(k),add:k=>classes.add(k),remove:k=>classes.delete(k)},getClientRects:()=>visible?[{}]:[],focus(){active=e;},replaceChildren(){}};nodes.set(id,e);return e;};
 const modal=element('confirmModal');element('cfDone');
 const document={get activeElement(){return active;},getElementById:id=>nodes.get(id)||null};
 const context={document,app:{querySelectorAll:()=>buttons},$:selector=>nodes.get(selector.slice(1))||element(selector.slice(1)),PUB:{qty:1,eventId:'event',ev:null},PUBLIC_BASE:'https://www.zoi.city/tickets/',qrSvg:()=>'',fmtMoney:()=>'',esc:String,ico:()=>'',restoreFocus(){fallback++;active='fallback';}};
 vm.createContext(context);vm.runInContext('let LAST_CONFIRM=null,CONFIRM_RETURN=null;'+show+'\n'+close,context);
 return{element,buttons,modal,active:()=>active,fallback:()=>fallback,show(target){context.target=target;vm.runInContext("showConfirm({code:'LOCAL-FIXTURE',qty:1,paid:false,amount_cents:0},null,{status:'reserved',eventAvailable:true},target)",context);},close(){vm.runInContext('closeConfirm()',context);}};
}
test('ordinary opener returns focus after Done; already-hidden close does not steal it',()=>{assert.ok(close&&show);const f=fixture(),opener=f.element('open');opener.focus();f.show();assert.equal(f.active().id,'cfDone');f.close();assert.equal(f.active(),opener);assert.equal(f.modal.classList.contains('open'),false);const elsewhere=f.element('search');elsewhere.focus();f.close();assert.equal(f.active(),elsewhere);assert.equal(f.fallback(),0);});
test('history receipt restores replacement button by stable request identity after list rerender',()=>{const f=fixture(),old=f.element('old');old.dataset.request='request-A';f.buttons.push(old);old.focus();f.show({request:'request-A'});old.isConnected=false;const wrong=f.element('wrong');wrong.dataset.request='request-B';const replacement=f.element('new');replacement.dataset.request='request-A';f.buttons.splice(0,1,wrong,replacement);f.close();assert.equal(f.active(),replacement);assert.equal(f.fallback(),0);});
test('missing, disconnected, disabled or hidden return target uses fallback without throwing',()=>{for(const kind of ['missing','disconnected','disabled','hidden']){const f=fixture(),opener=f.element('open',kind!=='hidden');if(kind==='disconnected')opener.isConnected=false;if(kind==='disabled')opener.disabled=true;opener.focus();f.show(kind==='missing'?{request:'missing'}:undefined);f.close();assert.equal(f.active(),'fallback',kind);assert.equal(f.fallback(),1,kind);}});
test('refreshing an already-open confirmation preserves original return target',()=>{const f=fixture(),opener=f.element('open');opener.focus();f.show();f.show({request:'unexpected-new-target'});f.close();assert.equal(f.active(),opener);});
test('actual history controller supplies stable descriptor before its finally rerenders buttons',()=>{const history=html.slice(html.indexOf('async function gaViewHistory('),html.indexOf('\n',html.indexOf('async function gaViewHistory(')));assert.match(history,/showConfirm\([^;]+,\{request:id\}\)/);assert.match(history,/finally\{gaBusy=false;if\(epoch===gaHistoryEpoch\)gaPaintHistory\(\);\}/);});
