import test from 'node:test';import assert from 'node:assert/strict';import{createWorkspaceController}from'../../assets/suite/workspace-creation.mjs';
const actor='11111111-1111-4111-8111-111111111111',request='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333';
function fixture(overrides={}){let value=null,active=true,writes=0,confirmed=null;const storage={load:async()=>value,save:async x=>{value=structuredClone(x);},clear:async()=>{value=null;}};const rpc=async(name,args)=>{if(name==='zoi_create_workspace'){writes++;return{ok:true,workspace_id:id,name:args.p_name,kind:args.p_kind};}return{authenticated:true,workspaces:[{id,name:'New company',kind:'business',role:'owner'}]};};const controller=createWorkspaceController({actor,current:()=>active,storage,rpc,nonce:()=>request,onConfirmed:x=>confirmed=x,...overrides});return{controller,storage,setActive:x=>active=x,get value(){return value;},get writes(){return writes;},get confirmed(){return confirmed;}};}
test('creation selects exact new workspace after authoritative membership, not saved old selection',async()=>{const f=fixture();await f.controller.load();assert.equal((await f.controller.create({name:'New company'})).status,'confirmed');assert.equal(f.confirmed.workspaceId,id);assert.equal(f.writes,1);assert.equal(f.value,null);});
test('lost reply survives remount without permitting duplicate creation or same-name inference',async()=>{let writes=0;const f=fixture({rpc:async name=>{if(name==='zoi_create_workspace'){writes++;throw Error('lost');}return{authenticated:true,workspaces:[{id,name:'New company',kind:'business',role:'owner'}]};}});await f.controller.load();await assert.rejects(f.controller.create({name:'New company'}),/lost/);assert.deepEqual(f.value,{actor,request,workspace:null});assert(!JSON.stringify(f.value).includes('New company'));await assert.rejects(f.controller.create({name:'New company'}));const next=fixture({storage:f.storage,rpc:async()=>({authenticated:true,workspaces:[{id,name:'New company',kind:'business',role:'owner'}]})});await next.controller.load();assert.equal((await next.controller.check()).status,'unconfirmed');assert.equal(next.confirmed,null);assert.equal(writes,1);});
test('storage failure and actor switch before dispatch do not create',async()=>{const f=fixture();f.storage.save=async x=>{f.setActive(false);};await f.controller.load();await assert.rejects(f.controller.create({name:'New company'}));assert.equal(f.writes,0);});
test('double submit cannot race a held creation',async()=>{let release;const f=fixture({rpc:async name=>name==='zoi_create_workspace'?new Promise(r=>release=r):({authenticated:true,workspaces:[]})});await f.controller.load();const pending=f.controller.create({name:'New company'});while(!release)await new Promise(r=>setTimeout(r,0));await assert.rejects(f.controller.create({name:'New company'}));release({ok:false});await assert.rejects(pending,/declined/);assert.equal(f.controller.state().pending,false);});
test('saved receipt with membership read failure can recover exact ID without another write',async()=>{let reads=0;const f=fixture({rpc:async(name,args)=>name==='zoi_create_workspace'?{ok:true,workspace_id:id,name:args.p_name,kind:args.p_kind}:++reads===1?Promise.reject(Error('temporary')):{authenticated:true,workspaces:[{id,name:'New company',kind:'business',role:'owner'}]}});await f.controller.load();await assert.rejects(f.controller.create({name:'New company'}),/temporary/);assert.equal(f.value.workspace,id);assert.equal((await f.controller.check()).status,'confirmed');});
test('malformed recovery marker cannot be overwritten',async()=>{const f=fixture({storage:{load:async()=>({actor,request,workspace:null,private:'bad'}),save:async()=>assert.fail(),clear:async()=>assert.fail()}});await assert.rejects(f.controller.load());await assert.rejects(f.controller.create({name:'New company'}));});
test('failed storage readback after persistence fails closed until original marker is loaded',async()=>{let stored=null,fail=false,writes=0;const f=fixture({storage:{load:async()=>{if(fail)throw Error('readback unavailable');return stored;},save:async value=>{stored=value;fail=true;},clear:async()=>{stored=null;}},rpc:async()=>{writes++;}});await f.controller.load();await assert.rejects(f.controller.create({name:'New company'}),/readback unavailable/);await assert.rejects(f.controller.create({name:'Another company'}));assert.equal(writes,0);fail=false;await f.controller.load();assert.equal(f.controller.state().pending,true);});
test('disposal during a held creation cannot publish late navigation',async()=>{let release;const f=fixture({rpc:async()=>new Promise(r=>release=r)});await f.controller.load();const pending=f.controller.create({name:'New company'});while(!release)await new Promise(r=>setTimeout(r,0));f.controller.dispose();release({ok:true,workspace_id:id,name:'New company',kind:'business'});await assert.rejects(pending,/account changed/);assert.equal(f.confirmed,null);assert.equal(f.value.workspace,null);});
test('public load cannot race an in-flight create and wipe its marker',async()=>{let release;const f=fixture({rpc:async()=>new Promise(r=>release=r)});await f.controller.load();const pending=f.controller.create({name:'New company'});while(!release)await new Promise(r=>setTimeout(r,0));await assert.rejects(f.controller.load(),/already checking/);release({ok:false});await assert.rejects(pending,/declined/);});
test('cleanup storage failure cannot turn authoritatively confirmed creation into an unknown retry',async()=>{let value=null,fail=false;const f=fixture({storage:{load:async()=>{if(fail)throw Error('cleanup read failed');return value;},save:async x=>{value=x;},clear:async()=>{value=null;fail=true;}}});await f.controller.load();const result=await f.controller.create({name:'New company'});assert.equal(result.status,'confirmed');assert.equal(result.cleanupPending,true);assert.equal(f.confirmed.workspaceId,id);assert.equal(f.controller.state().ready,false);});
test('held initial reload serializes every competing load and create before stale null can return',async()=>{let release,hold=false,value=null,writes=0;const f=fixture({storage:{load:async()=>hold?new Promise(r=>release=r):value,save:async x=>{value=x;},clear:async()=>{value=null;}},rpc:async()=>{writes++;throw Error('lost');}});await f.controller.load();hold=true;const loading=f.controller.load();while(!release)await new Promise(r=>setTimeout(r,0));await assert.rejects(f.controller.load(),/already checking/);await assert.rejects(f.controller.create({name:'New company'}));hold=false;release(null);await loading;await assert.rejects(f.controller.create({name:'New company'}),/lost/);await assert.rejects(f.controller.create({name:'New company'}));assert.equal(writes,1);assert.equal(f.controller.state().pending,true);});
