import test from'node:test';import assert from'node:assert/strict';import{createYouthRecovery,youthCapability,youthOperationScope}from'../../assets/organizations/youth-recovery.mjs';
const actor='11111111-1111-4111-8111-111111111111',profile='22222222-2222-4222-8222-222222222222',child='33333333-3333-4333-8333-333333333333',request='44444444-4444-4444-8444-444444444444';
function fixture({cap=true,fail=false}={}){let stored=null,calls=[],active=true,available=cap;const saved={ok:true,state:'saved',actor_id:actor,actor_profile_id:profile,operation:'youth_child_save',request_id:request,scope:{id:null},workspace_id:null,child:{id:child,version:1,guardian_id:profile,name:'Private child',archived:false}};const storage={load:async()=>stored,save:async x=>stored=structuredClone(x),clear:async()=>stored=null},call=async(name,args)=>{calls.push({name,args});if(fail)throw Error('Network interrupted');return saved;};const make=()=>createYouthRecovery({actor,storage,call,current:()=>active,available:()=>available,nonce:()=>request});return{make,storage,call,saved,calls,setStored:x=>stored=x,getStored:()=>stored,setActive:x=>active=x,setAvailable:x=>available=x};}
test('capability requires exact actor/internal guardian identity and numeric installed version',()=>{const v={ok:true,actor_id:actor,actor_profile_id:profile,guardian_id:profile,capabilities:{youth_recovery:1}};assert(youthCapability(v,actor));for(const patch of[{actor_id:profile},{guardian_id:actor},{capabilities:{youth_recovery:'1'}},{capabilities:{youth_recovery:2}},{capabilities:null}])assert(!youthCapability({...v,...patch},actor));});
test('lost child save retains only identifiers, survives remount and checks same request',async()=>{const f=fixture({fail:true}),r=f.make();await r.load();await assert.rejects(r.send('youth_child_save',{p_id:null,p_expected_version:0,p_name:'Private child',p_archived:false}));assert(!JSON.stringify(f.getStored()).includes('Private child'));assert.equal(f.getStored().expected_version,0);const remount=createYouthRecovery({actor,storage:f.storage,call:async(name,args)=>{assert.equal(name,'youth_operation_request');assert.equal(args.p_request,request);return{...f.saved,receipt:{ok:true,child:f.saved.child},historical:true};},current:()=>true,available:()=>true,nonce:()=>request});await remount.load();assert.equal(remount.state().payload,null);await remount.recover();assert.equal(f.getStored(),null);});
test('absent capability blocks mutation and startup recovery but preserves marker',async()=>{const f=fixture({cap:false}),r=f.make();await r.load();await assert.rejects(r.send('youth_child_save',{p_id:null,p_name:'Name',p_expected_version:0}));assert.equal(f.calls.length,0);f.setStored({actor,workspace:null,request,operation:'youth_child_save',created_at:new Date().toISOString()});await r.load();await assert.rejects(r.recover());assert.equal(f.calls.length,0);assert(f.getStored());});
test('known receipt clears before optional caller refresh and wrong nested child stays blocked',async()=>{const f=fixture(),r=f.make();await r.load();await r.send('youth_child_save',{p_id:null,p_expected_version:0,p_name:'Private child',p_archived:false});assert.equal(r.state().marker,null);const g=fixture();g.saved.child.guardian_id=actor;const bad=g.make();await bad.load();await assert.rejects(bad.send('youth_child_save',{p_id:null,p_expected_version:0,p_name:'Private child',p_archived:false}));assert(g.getStored());});
test('legacy marker can resolve scoped saved receipt without persisting private retry payload',async()=>{const f=fixture();f.setStored({actor,workspace:null,request,operation:'youth_child_save',listing:null,program:null,created_at:new Date().toISOString()});const r=f.make();await r.load();await r.recover();assert.equal(f.calls[0].args.p_scope,null);assert.equal(f.getStored(),null);});
test('scope mappings never include guardian consent details',()=>{assert.deepEqual(youthOperationScope('youth_enrol',{p_program:request,p_child:child,p_data:{guardian_name:'Private'}}),{program:request,child});assert.throws(()=>youthOperationScope('arbitrary',{}));});
