// Actual map renderer fed by the isolated PostgreSQL writer/public-reader output.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),{chromium}=require(path.join(root,'node_modules/playwright-core'));
const packet=JSON.parse(fs.readFileSync(process.env.QA_PROJECTED_POINT||'/tmp/named-place-geography-projection.json','utf8'));
assert.equal(packet.controlled,true);assert.equal(packet.proof.listing_id,packet.entity.id);
const out=process.env.QA_OUTPUT_DIR||'/tmp/named-place-geography-browser';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const report=[];try{for(const width of[390,1440])for(const sparse of[false,true]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const entity=sparse?{...packet.entity,id:'40000000-0000-4000-8000-000000000002',name:'QA sparse place',slug:'qa-sparse-place',canonical_slug:'qa-sparse-place',latitude:null,longitude:null,geo_precision:'none',profile:{}}:packet.entity;
 const geo={id:entity.id,slug:entity.slug,name:entity.name,entity_type:entity.entity_type,city:entity.city,country:entity.country,address:entity.address,lat:entity.latitude,lng:entity.longitude,geo_precision:entity.geo_precision,publish_status:'published'};
 await page.route('**/*',route=>{const req=route.request(),u=new URL(req.url());if(u.pathname.includes('/rpc/')){const fn=u.pathname.split('/').pop(),args=req.postDataJSON()||{};const data=fn==='explore_geo'?(sparse||args.p_offset?[]:[geo]):['explore_search','explore_search_types'].includes(fn)?[geo]:fn==='home_entity'?entity:fn==='geography_reviewed_point'?(sparse?null:packet.proof):fn==='home_stats'?{}:[];return route.fulfill({contentType:'application/json',body:JSON.stringify(data)});}if(!['GET','HEAD','OPTIONS'].includes(req.method()))return route.abort();if(u.origin==='https://www.zoi.city'){const file=path.join(root,u.pathname==='/explore/map/'?'explore/map/index.html':u.pathname);if(fs.existsSync(file)&&fs.statSync(file).isFile())return route.fulfill({contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':/\.m?js$/.test(file)?'text/javascript':undefined,body:fs.readFileSync(file)});return route.abort();}return route.continue();});
 await page.goto('https://www.zoi.city/explore/map/?place='+entity.slug,{waitUntil:'domcontentloaded'});
 if(!sparse){await page.waitForFunction(()=>window.zoiMap?.getSource('places'));await page.evaluate(([lng,lat])=>window.zoiMap.jumpTo({center:[lng,lat],zoom:17}),[entity.longitude,entity.latitude]);const pin=page.locator('.m-pin[data-slug="qa-exact-place"]');await pin.waitFor({state:'visible',timeout:30000});await pin.click();}
 const preview=page.locator('.m-place-preview');await preview.waitFor({timeout:30000});await page.waitForTimeout(500);
 const directions=preview.getByRole('link',{name:/Directions/});await directions.waitFor();const href=await directions.getAttribute('href');
 if(sparse){assert.equal(await page.locator('.m-pin').count(),0);assert.ok(!href.includes(String(packet.proof.latitude)));assert.match(await preview.innerText(),/QA sparse place/);}else{await page.waitForFunction(({lat,lng})=>[...document.querySelectorAll('.m-place-preview a')].some(a=>a.href.includes(encodeURIComponent(lat+','+lng))),{lat:entity.latitude,lng:entity.longitude});assert.match(await preview.innerText(),/QA exact place/);}
 assert.match(await preview.getByRole('link',{name:/Open home/}).getAttribute('href'),new RegExp('/business/'+entity.slug));assert.deepEqual(errors,[]);await page.screenshot({path:path.join(out,`${width}-${sparse?'sparse':'reviewed'}.png`)});report.push({width,sparse,directions:await directions.getAttribute('href'),errors});await page.close();console.log('PASS',width,sparse?'unmapped sparse':'receipt-backed reviewed pin');
 }}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
