const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const root=path.resolve(__dirname,'../../..'),out=process.env.QA_OUTPUT_DIR||path.join(root,'docs/audits/evidence/room-finishing-2026-10-03/candidate');
(async()=>{await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox','--enable-unsafe-swiftshader']});const report={actual_production:false,actual_api_reads:true,local_overlays:true,live_writes:false,cases:[]};
try{for(const city of ['toronto','montreal'])for(const width of [390,1440]){const page=await browser.newPage({viewport:{width,height:900},hasTouch:width===390,reducedMotion:'reduce'}),item={city,width,errors:[],steps:[],failed:[],status:'running'};report.cases.push(item);page.on('pageerror',e=>item.errors.push(e.message));page.on('requestfailed',r=>item.failed.push({path:new URL(r.url()).pathname,error:r.failure()?.errorText}));let releaseLogo;const logoGate=new Promise(resolve=>releaseLogo=resolve),overlays=['/assets/events/signature/sponsor-preview.mjs','/assets/events/signature/sponsor-preview.css','/assets/events/signature/furnished-concert.mjs'];
await page.route('**/*',async r=>{const u=new URL(r.request().url());
if(overlays.includes(u.pathname))return r.fulfill({body:await fs.readFile(path.join(root,u.pathname)),contentType:u.pathname.endsWith('.css')?'text/css':'text/javascript'});
if(u.hostname==='kolonakifinefoods.ca'&&u.pathname.includes('Kolonaki_WEB')){await logoGate;return r.continue();}
if(u.hostname==='theoeyecare.com'&&u.pathname.endsWith('TheoEyeCare-HP-SiteIdentity-Logo.png'))return r.abort('failed');if(u.pathname.includes('/rest/v1/rpc/')&&/(save|write|send|create|delete|reserve|publish|checkout|claim|configure)/i.test(u.pathname))return r.abort();return r.continue();});
try{await page.goto('https://www.zoi.city'+(city==='toronto'?'/events/giannis-ploutarchos-andromache-toronto-2027/#room':'/event/giannis-ploutarchos-andromache-montreal-2027#room'),{waitUntil:'domcontentloaded'});const room=page.locator('[data-room-skin=zoi]').first();await room.locator('canvas').waitFor();await room.scrollIntoViewIfNeeded();await room.getByRole('button',{name:'Full screen',exact:true}).click();await room.getByRole('button',{name:'Find table',exact:true}).click();await room.getByRole('searchbox').fill(city==='toronto'?'9':'10A');await room.locator(city==='toronto'?'.fc-number-tray [data-fc-table="9"]':'.rs-numbers [data-table="10A"]').click();
if(city==='toronto'){
 await room.locator('.sv-demo-tools>summary').click();await room.locator('[data-preview-sponsor]').click();const card=room.locator('.sp-demo-card');await card.waitFor();
await card.locator('.sp-demo-logo[data-logo-state=pending]').waitFor();assert.match(await card.locator('[data-logo-status]').innerText(),/Kolonaki.*Loading logo/);assert.equal(await card.locator('img').isVisible(),false);
await page.screenshot({path:path.join(out,`${city}-${width}-logo-pending.png`)});releaseLogo();
await card.locator('.sp-demo-logo[data-logo-state=loaded]').waitFor({timeout:20000});
await card.locator('img').evaluate(image=>window.oldSponsorLogo=image);
await card.locator('select').selectOption('2d6eb99c-aace-4bb7-af46-50aa566b7f25');
await card.locator('.sp-demo-logo[data-logo-state=unavailable]').waitFor();assert.match(await card.locator('[data-logo-status]').innerText(),/Theo Eye Care.*Logo unavailable/);assert.equal(await card.locator('img').isVisible(),false);
await page.evaluate(()=>window.oldSponsorLogo.dispatchEvent(new Event('load')));
assert.equal(await card.locator('.sp-demo-logo').getAttribute('data-logo-state'),'unavailable');
await page.screenshot({path:path.join(out,`${city}-${width}-logo-unavailable.png`)});
await card.locator('select').selectOption('c12e76e0-e020-4ede-bcf3-b9068f611ddd');await card.locator('.sp-demo-logo[data-logo-state=loaded]').waitFor({timeout:20000});
await card.locator('[data-placement-status]').filter({hasText:'TEST display on table 9'}).waitFor();item.drawers=await room.evaluate(n=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,scrollHeight:e.scrollHeight,clientHeight:e.clientHeight};};return{drawer:rect(n.querySelector('.sv-demo-tools')),card:rect(n.querySelector('.sp-demo-card')),selection:rect(n.closest('.signature-venue').querySelector('.sv-inspector')),controls:rect(n.querySelector('.fc-controls')),viewport:rect(n.querySelector('.fc-viewport'))};});assert.ok(item.drawers.drawer.y>=item.drawers.controls.y+item.drawers.controls.h+7,JSON.stringify(item.drawers));assert.ok(item.drawers.drawer.y+item.drawers.drawer.h<=item.drawers.viewport.y+item.drawers.viewport.h-10,JSON.stringify(item.drawers));
if(width===390)assert.ok(item.drawers.drawer.y+item.drawers.drawer.h<=item.drawers.selection.y-10,JSON.stringify(item.drawers));
assert.equal(await card.evaluate(n=>getComputedStyle(n).overflowY),'visible');
await card.locator('details>summary').click();await card.locator('[data-source]').scrollIntoViewIfNeeded();
const sourceHit=await card.locator('[data-source]').evaluate(n=>{const r=n.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{hit:hit===n||n.contains(hit),height:r.height,bottom:r.bottom};});assert.ok(sourceHit.hit);assert.ok(sourceHit.height>=44);if(width===390)assert.ok(sourceHit.bottom<item.drawers.selection.y);
item.sourceHit=sourceHit;
await page.setViewportSize({width,height:740});
await page.waitForFunction(()=>{const drawer=document.querySelector('.sv-demo-tools'),viewport=drawer.closest('.fc-viewport'),selection=document.querySelector('.sv-inspector'),a=drawer.getBoundingClientRect(),v=viewport.getBoundingClientRect(),s=selection.getBoundingClientRect();return a.top>=v.top&&a.bottom<=v.bottom-10&&(!(a.left<s.right&&a.right>s.left)||a.bottom<=s.top-10);});
await card.locator('[data-source]').scrollIntoViewIfNeeded();assert.equal(await card.locator('[data-source]').evaluate(n=>{const r=n.getBoundingClientRect();return n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),true);
await page.screenshot({path:path.join(out,`${city}-${width}-resized-drawer.png`)});await page.setViewportSize({width,height:900});
item.logo=await card.locator('img').evaluate(i=>({complete:i.complete,width:i.naturalWidth,height:i.naturalHeight,hidden:i.hidden,src:i.getAttribute('src')}));await page.screenshot({path:path.join(out,`${city}-${width}-sponsor-open.png`)});
 await card.locator('[data-inspect]').click();await room.locator('.sv-demo-tools').evaluate(n=>{if(n.open)throw Error('preview drawer did not close');});await room.locator('[data-preview-placement]').waitFor();await page.screenshot({path:path.join(out,`${city}-${width}-table-display.png`)});
 const preview=room.locator('[data-preview-placement]');item.previewHit=await preview.evaluate(n=>{const r=n.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{visible:!!n.getClientRects().length,hit:hit===n||n.contains(hit),occluder:hit?.className,width:r.width,height:r.height};});assert.ok(item.previewHit.height>=44);await preview.click();await card.waitFor();await card.locator('[data-remove]').click();assert.equal(await room.locator('[data-preview-placement]').count(),0);await card.locator('[data-close]').click();item.steps.push('controlled delayed/failed/stale logo, unclipped source action, selected table9 test placement/open/inspect/reopen/remove');
 await room.locator('.sv-demo-tools').evaluate(n=>n.open=false);await page.locator('#signature-room [data-request]').click();assert.notEqual(await page.locator('#signature-room').getAttribute('data-fullscreen'),'true');
}else{await room.locator('[data-continue]').click();assert.equal(await page.evaluate(()=>!!document.fullscreenElement),false);assert.equal(await room.evaluate(n=>n.classList.contains('rs-expanded')),false);}
await page.locator('[data-count]').waitFor();assert.match(await page.locator('.sig-a-selected-table').innerText(),city==='toronto'?/Table 9\b/:/Table 10A\b/);item.active=await page.evaluate(()=>({tag:document.activeElement?.tagName,class:document.activeElement?.className,aria:document.activeElement?.getAttribute('aria-label'),scrollY,overflow:document.body.style.overflow,inert:[...document.querySelectorAll('[inert]')].length}));await page.screenshot({path:path.join(out,`${city}-${width}-parea-handoff.png`)});item.steps.push('full screen room→same shared Parea with exact source table');assert.deepEqual(item.errors,[]);item.status='passed';
}catch(error){item.status='failed';item.failure=error.message;await page.screenshot({path:path.join(out,`${city}-${width}-failure.png`)});}finally{await page.close();}
}}finally{await browser.close();const text=JSON.stringify(report,null,2)+'\n';const {credentialFindings}=await import('../../../scripts/check-source-credentials.mjs');assert.equal(credentialFindings(text).length,0);await fs.writeFile(path.join(out,'report.json'),text);}console.log(JSON.stringify(report.cases.map(c=>({city:c.city,width:c.width,status:c.status,failure:c.failure}))));if(report.cases.some(c=>c.status!=='passed'))process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1;});
