import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {credentialFindings} from '../../../scripts/check-source-credentials.mjs';
const root=process.cwd(),folder='docs/audits/evidence/room-finishing-2026-10-03',snapshot=path.join(root,'.recovery/room-finishing-freeze-20261003');
const runtime=['assets/events/signature/sponsor-preview.mjs','assets/events/signature/sponsor-preview.css','assets/events/signature/furnished-concert.mjs'];
const seeds=[...runtime,'docs/audits/room-finishing-2026-10-03.md','docs/audits/evidence/paired-room-polish-producer-2026-10-03/source-images.json','tests/browser/paired-room-polish/verify.cjs','tests/unit/sponsor-preview.test.mjs','tests/unit/furnished-concert.test.mjs','tests/unit/room-navigation-model.test.mjs','tests/unit/paired-room-camera.test.mjs','tests/unit/sponsor-handoff.test.mjs','scripts/check-source-credentials.mjs','package.json','package-lock.json','events/giannis-ploutarchos-andromache-toronto-2027/index.html'];
async function walk(dir){const items=[];for(const e of await fs.readdir(path.join(root,dir),{withFileTypes:true})){const p=path.posix.join(dir,e.name);if(e.isDirectory())items.push(...await walk(p));else if(e.isFile())items.push(p);}return items;}
seeds.push(...await walk('assets/events'),...await walk('tests/browser/room-finishing-live'),...(await walk(folder)).filter(p=>!p.endsWith('/manifest.json')));
const queue=[...new Set(seeds)],files=new Map();
while(queue.length){const p=queue.shift();if(files.has(p))continue;const bytes=await fs.readFile(path.join(root,p));files.set(p,bytes);if(!/\.(?:mjs|js|cjs|html|css)$/.test(p))continue;const text=bytes.toString();for(const m of text.matchAll(/["'`]((?:\/assets\/|\.\.\/|\.\/)[^"'`\s<>]+\.(?:mjs|js|css|jpg|png|svg|webp)(?:\?[^"'`\s<>]*)?)["'`]/g)){const clean=m[1].split('?')[0],dep=clean.startsWith('/')?clean.slice(1):path.posix.normalize(path.posix.join(path.posix.dirname(p),clean));if(dep.startsWith('../'))throw Error('Unsafe dependency');try{if((await fs.stat(path.join(root,dep))).isFile())queue.push(dep);}catch{}}}
await fs.mkdir(snapshot,{recursive:true});const entries=[];for(const [p,b] of [...files].sort(([a],[b])=>a.localeCompare(b))){if(/\.(?:json|md|mjs|js|cjs|css|html|txt|log|sql)$/.test(p)&&credentialFindings(b.toString()).length)throw Error('Credential finding in '+p);const to=path.join(snapshot,p);await fs.mkdir(path.dirname(to),{recursive:true});await fs.writeFile(to,b);entries.push({path:p,sha256:crypto.createHash('sha256').update(b).digest('hex'),bytes:b.length});}
const manifest={base_head:'95d63fd15b18d3d73d91bb2a5e40ae54313e8a39',deployment:'dpl_AEtAAPx4k71afGdkRnw2o9TTCcbP',snapshot,runtime,credential_findings:0,source_plan_or_image_edits:false,production_writes:false,files:entries};
const text=JSON.stringify(manifest,null,2)+'\n';await fs.writeFile(path.join(root,folder,'manifest.json'),text);console.log(JSON.stringify({entries:entries.length,runtime,manifest_sha256:crypto.createHash('sha256').update(text).digest('hex'),snapshot}));
