const {chromium}=require('playwright-core'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),actor='11111111-1111-4111-8111-111111111111',ws='22222222-2222-4222-8222-222222222222',sid='33333333-3333-4333-8333-333333333333',record='44444444-4444-4444-8444-444444444444';
const cases=['write-workspace','write-detached','write-positive','write-refresh401','late-workspace','late-account','denial','cleanup','detach-reattach','held-import','missing','opaque','mismatch'];
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const report=[];
try{for(const width of[390,1440])for(const family of['properties','timekeeping'])for(const scenario of cases){
 const context=await browser.newContext({viewport:{width,height:900}}),page=await context.newPage();let release,deny=false,holdRead=false;const posts=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const token='e30.'+Buffer.from(JSON.stringify({sub:actor,session_id:sid})).toString('base64url')+'.fixture';
 const data=family==='properties'?{ok:true,offers:[],owned:[{id:record,name:'Owner business',entity_type:'business'}],requests:[{offer_snapshot:{data:{title:'Private source',price_on_request:true}},data:{kind:'information',message:'SECRET enquiry'},inquiry_id:record,created_at:new Date().toISOString()}],audit:[]}:{ok:true,actor_id:actor,role:'owner',entries:[],projects:[{id:record,title:'Private matter'}],tasks:[],totals:[],active_timer:{id:record,started_at:new Date().toISOString(),data:{description:'SECRET timer'}},server_now:new Date().toISOString()};
 await context.route('**/*',async route=>{const url=new URL(route.request().url());
  if(url.pathname==='/auth/v1/token'){release=()=>route.fulfill({status:scenario==='write-refresh401'?401:200,contentType:'application/json',body:JSON.stringify(scenario==='write-refresh401'?{error:'invalid_grant'}:{access_token:token,refresh_token:'fixture',expires_in:3600,user:{id:actor}})});return;}
  if(url.pathname.includes('/rest/v1/rpc/')){const name=url.pathname.split('/').at(-1),args=route.request().postDataJSON();posts.push({name,args});const respond=()=>route.fulfill({status:deny?403:200,contentType:'application/json',body:JSON.stringify(deny?{code:'42501',message:'permission denied'}:name==='property_offer_save'?{ok:true,offer:{id:args.p_id,published:false}}:name==='time_entry_save'?{ok:true,entry:{id:args.p_id}}:data)});if(holdRead){release=respond;return;}return respond();}
  if(url.origin!=='https://fixture.invalid')return route.abort();if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:'<main id="root"></main><script src="/assets/zoi-core.js"></script>'});const file=path.resolve(root,'.'+url.pathname);if(!file.startsWith(root+'/'))return route.abort();try{const serve=()=>route.fulfill({contentType:file.endsWith('.css')?'text/css':'text/javascript',body:require('node:fs').readFileSync(file)});if(scenario==='held-import'&&url.pathname===`/assets/${family}/operator.mjs`){release=serve;return;}return serve();}catch{return route.abort();}
 });await page.goto('https://fixture.invalid/');await page.evaluate(async({actor,ws,token,family,scenario})=>{ZoiCore.auth.save({user_id:scenario==='missing'?undefined:scenario==='opaque'?'opaque-secret':scenario==='mismatch'?'99999999-9999-4999-8999-999999999999':actor,access_token:token,refresh_token:'fixture',expires_at:Date.now()/1000+3600});window.ctx={C:ZoiCore,ws,role:'owner'};window.ZoiSuite={modules:[]};await import('/assets/suite/'+family+'.js');window.mounted=ZoiSuite.modules.find(m=>m.id===family).mount(document.querySelector('#root'),ctx).then(handle=>window.handle=handle);},{actor,ws,token,family,scenario});
 const waitRelease=async()=>{for(let i=0;!release&&i<100;i++)await page.waitForTimeout(10);assert(release,`${family} ${scenario}: no held request`);};
 if(scenario==='held-import'){await waitRelease();await page.evaluate(()=>document.querySelector('#root').innerHTML='<p>Replacement surface</p>');await release();await page.waitForTimeout(200);assert.equal(posts.length,0,'Late import must not read private data');assert.equal(await page.locator('#root').innerText(),'Replacement surface');}
 else if(['missing','opaque','mismatch'].includes(scenario)){await page.evaluate(()=>mounted);assert.equal(posts.length,0);assert.equal(await page.locator('form').count(),0);}
 else{await page.waitForFunction(()=>document.body.textContent.includes('SECRET'));if(scenario==='detach-reattach'){await page.evaluate(()=>{window.oldRoot=document.querySelector('#root');oldRoot.remove();});await page.waitForTimeout(600);await page.evaluate(()=>document.body.append(oldRoot));assert(!await page.locator('body').innerText().then(s=>s.includes('SECRET')),'Detached old private DOM must not return after reattachment');}else if(scenario==='cleanup'){await page.evaluate(async()=>{await mounted;handle.destroy();});assert.equal(await page.locator('form').count(),0);assert(!await page.locator('body').innerText().then(s=>s.includes('SECRET')));}
 else if(scenario.startsWith('write-')){
  if(family==='properties'){await page.locator('[name=host]').selectOption(record);await page.getByLabel('Property title',{exact:true}).fill('Private draft');await page.getByLabel('City / area',{exact:true}).fill('Athens');await page.getByLabel('Country',{exact:true}).fill('Greece');await page.getByLabel('Price on request',{exact:true}).check();}else await page.getByLabel('Private description',{exact:true}).fill('Private draft');
  posts.length=0;await page.evaluate(()=>ZoiCore.auth.save({...ZoiCore.auth.load(),expires_at:Date.now()/1000+20}));await page.getByRole('button',{name:family==='properties'?'Save property':'Save manual time',exact:true}).click();await waitRelease();if(scenario==='write-workspace')await page.evaluate(()=>ctx.ws='55555555-5555-4555-8555-555555555555');if(scenario==='write-detached')await page.evaluate(()=>document.querySelector('#root').remove());await release();await page.waitForTimeout(200);
  if(scenario==='write-positive'){assert.equal(posts.filter(p=>p.name.endsWith('_save')).length,1);await page.getByRole('status').filter({hasText:family==='properties'?'Private property draft saved.':'Time saved as a draft.'}).waitFor();}else{assert.equal(posts.length,0);assert.equal(await page.locator('form').count(),0);}
 }else{posts.length=0;holdRead=scenario.startsWith('late-');deny=scenario==='denial';await page.getByRole('button',{name:family==='properties'?'Refresh':'Show range',exact:true}).click();if(holdRead){await waitRelease();await page.evaluate(scenario=>{if(scenario==='late-workspace')ctx.ws='55555555-5555-4555-8555-555555555555';else ZoiCore.auth.clear();},scenario);await release();}await page.waitForTimeout(200);assert.equal(await page.locator('form').count(),0);assert(!await page.locator('body').innerText().then(s=>s.includes('SECRET')));}
 }
 assert.deepEqual(errors,[]);report.push({width,family,scenario,passed:true});await context.close();
}await fs.writeFile(process.env.QA_REPORT||'/tmp/private-operator-journeys.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
