import{BAKERY_TEMPLATES}from'../assets/homes/templates/bakery/layouts.mjs';
import{verticalFor,profileOf,profileForVertical}from'./_verticals.js';
import{profileMedia}from'./_profile-media.js';
import{bakeryData,esc,UUID}from'../assets/homes/templates/bakery/model.mjs';
import{renderBakery}from'../assets/homes/templates/bakery/render.mjs';
import{reviewedBakerySource}from'../assets/homes/templates/bakery/sources.mjs';
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
export function bakeryHomeContent(e){if(!e||!UUID.test(e.id||'')||e.marketplace_status==='hidden'||e.publish_status&&e.publish_status!=='published')return null;const {v}=verticalFor(e);if(v.key!=='bakery')return null;const p=profileForVertical(v,profileOf(e),e),media=profileMedia(e,p),source=reviewedBakerySource(e);if(source&&!['photos','photo_url','photo_urls','hero','hero_image','logo','logo_url','gallery'].some(k=>Object.hasOwn(e.profile||{},k))){if(!media.hero)media.hero=source.photos[0];if(!media.gallery?.length)media.gallery=source.photos;if(!media.logo)media.logo=source.logo;}const data=bakeryData(e,p,media);if(source&&data.photos.some(x=>source.photos.includes(x))){data.source=source.url;data.checked=source.checked;}return data;}
export function renderBakeryHome(e,publishedDesign=null){const bakery=bakeryHomeContent(e);if(!bakery)return null;const design=publishedDesign&&typeof publishedDesign==='object'&&!Array.isArray(publishedDesign)?publishedDesign:{},type=e.entity_type==='vendor'?'vendor':'business',canonical='https://www.zoi.city/'+type+'/'+encodeURIComponent(bakery.slug),title=bakery.name+(bakery.city?' in '+bakery.city:'')+' · Zoi';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#563128"><title>${esc(title)}</title><meta name="description" content="${esc(bakery.description||'Explore the bakery and prepare a request.')}"><link rel="canonical" href="${esc(canonical)}"><link rel="stylesheet" href="/assets/homes/templates/bakery/style.css?v=20260930"><script src="/assets/zoi-core.js?v=20260930" defer></script></head><body data-template="${BAKERY_TEMPLATES.includes(design.template)?design.template:'concierge'}"><div id="bakery-home">${renderBakery(bakery,design)}</div><script type="application/json" id="bakery-home-content">${json({bakery,design})}</script><script type="module" src="/assets/homes/templates/bakery/client.mjs?v=20260930"></script></body></html>`;}
export default renderBakeryHome;
