export const STORE='https://buygreek.shop';
export const ENDPOINT=STORE+'/api/2026-07/graphql.json';
const IMAGE_HOSTS=new Set(['cdn.shopify.com','buygreek.shop']);
export function imageURL(value){try{const u=new URL(value);return u.protocol==='https:'&&IMAGE_HOSTS.has(u.hostname)&&!u.port&&!u.username&&!u.password?u.href:null;}catch{return null;}}
export function variantID(value){const id=String(value||'');if(!/^\d{8,20}$/.test(id))throw Error('invalid_variant');return id;}
export function lines(value){if(!Array.isArray(value)||!value.length||value.length>30)throw Error('invalid_cart');const seen=new Set();return value.map(x=>{const id=variantID(x?.id),quantity=x?.quantity;if(!Number.isInteger(quantity)||quantity<1||quantity>20||seen.has(id))throw Error('invalid_cart');seen.add(id);return{id,quantity};});}
export function checkoutURL(value){return STORE+'/cart/'+lines(value).map(x=>`${x.id}:${x.quantity}`).join(',');}
export function amount(value){if(typeof value!=='string'||!/^\d{1,9}(?:\.\d{1,6})?$/.test(value))throw Error('invalid_price');return value;}
export function variant(v){if(!v||!/^gid:\/\/shopify\/ProductVariant\/\d{8,20}$/.test(v.id||'')||!/^[A-Z]{3}$/.test(v.price?.currencyCode||''))throw Error('invalid_product');return{id:variantID(v.id.split('/').at(-1)),title:String(v.title||'').slice(0,250),available:v.availableForSale===true,price:amount(v.price.amount),currency:v.price.currencyCode,image:imageURL(v.image?.url)};}
export function product(p){if(!p||!/^[-a-zA-Z0-9]{1,200}$/.test(p.handle||'')||!Array.isArray(p.variants?.nodes))throw Error('invalid_product');return{id:p.id,handle:p.handle,title:String(p.title||'').slice(0,300),description:String(p.description||'').slice(0,6000),vendor:String(p.vendor||'').slice(0,200),type:String(p.productType||'').slice(0,160),available:p.availableForSale===true,price_min:p.priceRange?.minVariantPrice&&/^[A-Z]{3}$/.test(p.priceRange.minVariantPrice.currencyCode)?{price:amount(p.priceRange.minVariantPrice.amount),currency:p.priceRange.minVariantPrice.currencyCode}:null,url:STORE+'/products/'+p.handle,image:imageURL(p.featuredImage?.url),image_alt:String(p.featuredImage?.altText||p.title||'').slice(0,300),images:(p.images?.nodes||[]).slice(0,8).map(i=>({url:imageURL(i.url),alt:String(i.altText||p.title||'').slice(0,300)})).filter(i=>i.url),variants:p.variants.nodes.map(variant),more_variants:p.variants.pageInfo?.hasNextPage===true};}
export const VARIANT='id title availableForSale price { amount currencyCode } image { url }';
export const PRODUCT=`id handle title description vendor productType availableForSale priceRange { minVariantPrice { amount currencyCode } } featuredImage { url altText } images(first:8) { nodes { url altText } } variants(first:100) { nodes { ${VARIANT} } pageInfo { hasNextPage } }`;
export async function graph(query,variables={},fetcher=fetch){const response=await fetcher(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,variables}),signal:AbortSignal.timeout(12000),redirect:'error'});if(!response.ok)throw Error('store_unavailable');const data=await response.json();if(data.errors?.length||!data.data)throw Error('store_unavailable');return data.data;}
export async function validateCheckout(input,fetcher=fetch){const requested=lines(input),data=await graph(`query($ids:[ID!]!){nodes(ids:$ids){... on ProductVariant{${VARIANT} product{handle title availableForSale}}}}`,{ids:requested.map(x=>'gid://shopify/ProductVariant/'+x.id)},fetcher);if(!Array.isArray(data.nodes)||data.nodes.length!==requested.length)throw Error('store_unavailable');const unavailable=[];const result=requested.map((line,i)=>{const raw=data.nodes[i];if(!raw){unavailable.push({id:line.id,quantity:line.quantity,handle:null});return null;}const v=variant(raw);if(v.id!==line.id)throw Error('store_unavailable');if(!/^[-a-zA-Z0-9]{1,200}$/.test(raw.product?.handle||''))throw Error('store_unavailable');if(!raw.product.availableForSale||!v.available){unavailable.push({id:line.id,quantity:line.quantity,handle:raw.product.handle});return null;}return{...v,quantity:line.quantity,product_title:String(raw.product.title||'').slice(0,300),handle:raw.product.handle};});if(unavailable.length){const error=Error('item_unavailable');error.unavailable=unavailable;throw error;}return{ok:true,lines:result,checkout_url:checkoutURL(requested),payment_collected:false,pricing_note:'Shipping, tax, discounts and final availability are confirmed at BuyGreek checkout.'};}
