import{personData,eligiblePerson,personURL}from'../assets/homes/person-data.mjs';
import{ownerHomeContent}from'./_owner-home-content.js';
import{CREATOR}from'../assets/homes/templates/creator/data.mjs';
import{renderCreatorHome}from'../assets/homes/templates/creator/render.mjs';
import{TEMPLATES}from'../assets/homes/templates/creator/model.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
function source(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&['cypriotsmurf.com','www.cypriotsmurf.com'].includes(u.hostname)}catch{return false}}
export function creatorHomeContent(entity,now=new Date()){if(!eligiblePerson(entity,'creator'))return null;if(entity.id!==CREATOR.id||(Object.hasOwn(entity.owner_content||{},'website')&&!source(entity.website))){const d=personData(entity),p=entity.profile||{};return ownerHomeContent({...d,alias:'',role:'Creator',bio:d.description,channels:[],shows:[],socials:d.socials.map(x=>({...x,label:x.id,description:'Published profile link'})),story_url:'',contact_url:personURL(p.contact_url),shows_url:'',source_checked_at:'',character_photo:'',wide_photo:''},entity,'creator');}if(!source(entity.website))return null;const today=new Date(now).toISOString().slice(0,10);return ownerHomeContent({...CREATOR,slug:String(entity.canonical_slug||entity.slug||CREATOR.slug),name:String(entity.name||CREATOR.name),shows:CREATOR.shows.filter(s=>s.date>=today)},entity,'creator')}
export function renderCreatorCanonicalHome(entity,publishedDesign=null,options={}){const content=creatorHomeContent(entity,options.now||new Date());if(!content)return null;const design=publishedDesign&&typeof publishedDesign==='object'&&!Array.isArray(publishedDesign)?publishedDesign:{};const template=TEMPLATES.includes(design.template)?design.template:'concierge';const canonical='https://www.zoi.city/creator/'+encodeURIComponent(content.slug);const title=[content.name,content.alias,'Zoi'].filter(Boolean).join(' · ');const payload={entity:content,template,design};const schema={'@context':'https://schema.org','@type':'Person',name:content.name,alternateName:content.alias,url:canonical,sameAs:[content.website,...content.socials.map(s=>s.url)],image:content.portrait};return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><meta name="description" content="'+esc(content.bio)+'"><link rel="canonical" href="'+esc(canonical)+'"><meta property="og:title" content="'+esc(title)+'"><meta property="og:url" content="'+esc(canonical)+'"><meta property="og:image" content="'+esc(content.portrait)+'"><link rel="stylesheet" href="/assets/homes/templates/creator/style.css?v=20260930-generic"><script type="application/ld+json">'+json(schema)+'</script></head><body data-template="'+template+'"><div id="creator-home">'+renderCreatorHome({entity:content,template,design,reviewMode:false})+'</div><script type="application/json" id="creator-home-content">'+json(payload)+'</script><script type="module" src="/assets/homes/templates/creator/canonical.mjs?v=20261006-gallery"></script></body></html>'}
export default renderCreatorCanonicalHome;
