import{publicPublicity}from'../assets/events/publicity.mjs';
import{genericEventData}from'./_generic-event-data.js';
import{ownerHomeContent}from'./_owner-home-content.js';
import{SIGNATURE,PARKVIEW}from'../assets/homes/templates/events/data.mjs';
import{renderEventHome}from'../assets/homes/templates/events/render.mjs';
import{templates}from'../assets/homes/templates/events/model.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
function source(value,domain){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&[domain,'www.'+domain].includes(u.hostname)}catch{return false}}
export function eventHomeContent(entity){if(!entity||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(entity.id||'')||entity.marketplace_status==='hidden'||entity.publish_status&&entity.publish_status!=='published'||entity.moderation_status&&!['clean','cleared'].includes(entity.moderation_status))return null;const base=entity.id===SIGNATURE.id&&entity.entity_type==='business'&&source(entity.website,'signatureproductions.ca')?SIGNATURE:entity.id===PARKVIEW.id&&entity.entity_type==='venue'&&source(entity.website,'parkviewmanor.ca')?PARKVIEW:null;if(!base)return (['event','venue'].includes(entity.entity_type)||(entity.entity_type==='business'&&(Object.hasOwn(entity.owner_content?.profile||{},'business_type')?entity.owner_content.profile.business_type:entity.profile?.business_type)==='concert_promoter'))&&![SIGNATURE.id,PARKVIEW.id].includes(entity.id)?{...genericEventData(entity),publicity:publicPublicity(entity)}:null;const content=ownerHomeContent({...base,id:entity.id,slug:String(entity.canonical_slug||entity.slug||base.slug),name:String(entity.name||base.name),address:String(entity.address||base.address||'')},entity,'events');content.owner_hero=Object.hasOwn(entity.owner_content||{},'photo_url');content.owner_email=Object.hasOwn(entity.owner_content||{},'email');content.owner_gallery=Object.hasOwn(entity.owner_content?.profile||{},'photos');const p=entity.owner_content?.profile;if(base===SIGNATURE&&p&&Object.hasOwn(p,'photos'))content.signature_gallery=(Array.isArray(p.photos)?p.photos:[]).slice(0,12).map(x=>({url:typeof x==='string'?x:x?.url,caption:typeof x==='object'&&typeof x?.caption==='string'?x.caption.slice(0,200):content.name+' · owner photograph'})).filter(x=>{try{const u=new URL(x.url);return u.protocol==='https:'&&!u.username&&!u.password}catch{return false}});content.publicity=publicPublicity(entity);return content}
export function renderEventCanonicalHome(entity,publishedDesign=null,options={}){const content=eventHomeContent(entity);if(!content)return null;const design=publishedDesign&&typeof publishedDesign==='object'&&!Array.isArray(publishedDesign)?publishedDesign:{};const template=templates.includes(design.template)?design.template:'concierge';const canonical='https://www.zoi.city/'+entity.entity_type+'/'+encodeURIComponent(content.slug);const title=content.name+' · Zoi';const payload={entity:content,template,design};const schema={'@context':'https://schema.org','@type':content.family==='venue'?'EventVenue':content.family==='event'?'Event':'Organization',name:content.name,url:canonical,description:content.intro,sameAs:content.website?[content.website]:undefined,image:content.hero||undefined,address:content.family==='venue'?content.address||undefined:undefined};return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><meta name="description" content="'+esc(content.intro)+'"><link rel="canonical" href="'+esc(canonical)+'"><meta property="og:title" content="'+esc(title)+'"><meta property="og:type" content="website"><meta property="og:description" content="'+esc(content.intro)+'"><meta property="og:url" content="'+esc(canonical)+'">'+(content.hero?'<meta property="og:image" content="'+esc(content.hero)+'">':'')+'<meta name="twitter:card" content="'+(content.hero?'summary_large_image':'summary')+'"><link rel="stylesheet" href="/assets/homes/templates/events/style.css?v=20260930-publicity-room"><script src="/assets/zoi-core.js?v=20260930" defer></script><script type="application/ld+json">'+json(schema)+'</script></head><body data-template="'+template+'"><div id="event-home">'+renderEventHome({entity:content,template,design,reviewMode:false})+'</div><script type="application/json" id="event-home-content">'+json(payload)+'</script><script type="module" src="/assets/homes/templates/events/canonical.mjs?v=20260930-room-art"></script></body></html>'}
export default renderEventCanonicalHome;
