import{ownerHomeContent}from'./_owner-home-content.js';
import{SIGNATURE,PARKVIEW}from'../assets/homes/templates/events/data.mjs';
import{renderEventHome}from'../assets/homes/templates/events/render.mjs';
import{templates}from'../assets/homes/templates/events/model.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
function source(value,domain){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&[domain,'www.'+domain].includes(u.hostname)}catch{return false}}
export function eventHomeContent(entity){if(!entity||entity.marketplace_status==='hidden'||entity.publish_status&&entity.publish_status!=='published')return null;const base=entity.id===SIGNATURE.id&&entity.entity_type==='business'&&source(entity.website,'signatureproductions.ca')?SIGNATURE:entity.id===PARKVIEW.id&&entity.entity_type==='venue'&&source(entity.website,'parkviewmanor.ca')?PARKVIEW:null;if(!base)return null;return ownerHomeContent({...base,id:entity.id,slug:String(entity.canonical_slug||entity.slug||base.slug),name:String(entity.name||base.name),address:String(entity.address||base.address||'')},entity,'events')}
export function renderEventCanonicalHome(entity,publishedDesign=null,options={}){const content=eventHomeContent(entity);if(!content)return null;const design=publishedDesign&&typeof publishedDesign==='object'&&!Array.isArray(publishedDesign)?publishedDesign:{};const template=templates.includes(design.template)?design.template:'concierge';const canonical='https://www.zoi.city/'+entity.entity_type+'/'+encodeURIComponent(content.slug);const title=content.name+' · Zoi';const payload={entity:content,template,design};const schema={'@context':'https://schema.org','@type':content.family==='venue'?'EventVenue':'Organization',name:content.name,url:canonical,sameAs:[content.website],image:content.hero,address:content.address||undefined};return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><meta name="description" content="'+esc(content.intro)+'"><link rel="canonical" href="'+esc(canonical)+'"><meta property="og:title" content="'+esc(title)+'"><meta property="og:url" content="'+esc(canonical)+'"><meta property="og:image" content="'+esc(content.hero)+'"><link rel="stylesheet" href="/assets/homes/templates/events/style.css?v=20260930"><script type="application/ld+json">'+json(schema)+'</script></head><body data-template="'+template+'"><div id="event-home">'+renderEventHome({entity:content,template,design,reviewMode:false})+'</div><script type="application/json" id="event-home-content">'+json(payload)+'</script><script type="module" src="/assets/homes/templates/events/canonical.mjs?v=20260930"></script></body></html>'}
export default renderEventCanonicalHome;
