import{musicHomeContent}from'./_music-home.js';
import{eventHomeContent}from'./_event-home.js';
import{publishedHomeDesign}from'./_home-design.js';
import{ownerMedia,parseMediaLink}from'../assets/homes/shared-media-model.mjs';
export const WIDGET_ID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const eventDate=v=>{const raw=String(v||'');if(!/^\d{4}-\d{2}-\d{2}(?:T|$)/.test(raw))return raw;const d=new Date(raw.slice(0,10)+'T12:00:00Z');return Number.isNaN(d.valueOf())?'':new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(d)};
const excerpt=v=>{const text=String(v||'').trim();return text.length>240?text.slice(0,237).replace(/\s+\S*$/,'')+'…':text};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function publicWidget(entity,id){if(!WIDGET_ID.test(id)||entity?.id!==id||!['artist','event'].includes(entity.entity_type)||entity.marketplace_status==='hidden'||entity.publish_status!=='published'||!['clean','cleared'].includes(entity.moderation_status))return null;const design=publishedHomeDesign(entity),hidden=new Set(design?.hidden_sections||[]),artist=entity.entity_type==='artist',data=artist?musicHomeContent(entity):eventHomeContent(entity);if(!data)return null;const slug=entity.canonical_slug||entity.slug;if(typeof slug!=='string'||!slug||/[\\/?#\u0000-\u0020]/.test(slug))return null;let media=null;const op=entity.owner_content?.profile||{};const owned=ownerMedia(Object.hasOwn(op,'owner_media')?op:entity.profile);const links=owned.present?(hidden.has('media')?[]:owned.items.map(x=>x.url)):[...(!hidden.has('offerings')?[data.spotify]:[]),...(!hidden.has('media')?[data.youtube]:[])];for(const url of links){try{const m=parseMediaLink(url);if(m.embed){media={url:m.url,embed:m.embed};break;}}catch{}}
return{id,type:entity.entity_type,name:String(entity.name||'').slice(0,180),url:'https://www.zoi.city/'+entity.entity_type+'/'+encodeURIComponent(slug),image:hidden.has('intro')?'':data.portrait||data.hero||'',imageKind:data.hero_kind==='event_poster'?'event_poster':null,description:hidden.has('intro')?'':excerpt(data.intro||data.story),starts:!artist&&!hidden.has('offerings')?eventDate(data.starts):'',media:artist?media:null};}
export function widgetHTML(data){const json=JSON.stringify(data).replace(/</g,'\\u003c');return'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>'+esc(data?.name||'Zoi widget')+'</title><link rel="stylesheet" href="/assets/widgets/public.css"></head><body><main>'+(!data?'<p>This profile is not available to share.</p>':`${data.image?'<img class="portrait'+(data.imageKind==='event_poster'?' event-poster':'')+'" src="'+esc(data.image)+'" alt="'+esc(data.name)+'">':''}<small>${data.type==='artist'?'ARTIST ON ZOI':'EVENT ON ZOI'}</small><h1>${esc(data.name)}</h1>${data.description?'<p>'+esc(data.description)+'</p>':''}${data.starts?'<p>'+esc(data.starts)+'</p>':''}<div class="actions">${data.media?'<button id="play">Open music player</button>':''}<a href="${esc(data.url)}" target="_blank" rel="noopener noreferrer">Explore on Zoi ↗</a></div><p id="status" role="status"></p><div id="player"></div>${data.media?'<p><a href="'+esc(data.media.url)+'" target="_blank" rel="noopener noreferrer">Open directly in '+(data.media.embed.includes('spotify.com')?'Spotify':'YouTube')+' ↗</a></p><small>Opening the player connects to '+(data.media.embed.includes('spotify.com')?'Spotify':'YouTube')+'.</small>':''}`)+'</main><script type="application/json" id="widget-data">'+json+'</script><script type="module" src="/assets/widgets/public.mjs"></script></body></html>';}
