const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const base=path.resolve(__dirname,'../../..'),out=process.env.QA_OUTPUT_DIR||path.join(base,'docs/audits/evidence/source-health-owner-2026-10-03');
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local'),file=path.resolve(base,'.'+url.pathname);if(!file.startsWith(base+path.sep)||!(url.pathname.startsWith('/assets/')||url.pathname.startsWith('/tests/browser/source-health-owner/')))throw Error();res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8');res.end(await fs.readFile(file));}catch{res.statusCode=404;res.end();}});
(async()=>{await fs.mkdir(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,report={controlled:true,production:false,no_live_writes:true,cases:[]};let browser;
try{browser=await chromium.launch({executablePath:'/home/codespace/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});for(const width of[390,1440])for(const family of['business','artist','event','church']){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
 await page.goto(origin+'/tests/browser/source-health-owner/fixture.html');await page.getByRole('region',{name:'Website and source review'}).waitFor();await page.evaluate(type=>{qa.type=type;return qa.mount();},family);
 const panel=page.getByRole('region',{name:'Website and source review'}),input=page.getByLabel('Official website address');await panel.waitFor();assert.equal(await panel.getAttribute('data-source-state'),'import-held');assert.equal(await panel.locator('a').count(),0);assert.equal(await page.evaluate(()=>qa.writes.length),0);
 await panel.getByRole('button',{name:'Review website address'}).click();assert(await input.evaluate(n=>n===document.activeElement));await input.fill('https://old.example/new-owner-path');await panel.getByText('Website change is in your draft. Save page to publish it.',{exact:true}).waitFor();await panel.screenshot({path:path.join(out,`${family}-${width}-draft.png`)});
 async function save(){await page.getByRole('button',{name:'Save page',exact:true}).click();await page.getByText('Saved. Your page details and menu are updated.',{exact:true}).waitFor();}
 await save();assert.equal(await panel.getAttribute('data-source-state'),'owner-url');assert.equal(await page.evaluate(()=>qa.owner_content.website),'https://old.example/new-owner-path');assert.equal(await page.evaluate(()=>qa.profile._enrich.blocked_reason),'source_scope_mismatch');
 await input.fill('https://unfinished.example/');await panel.getByRole('button',{name:'Use saved choice'}).focus();await page.keyboard.press('Enter');assert.equal(await input.inputValue(),'https://old.example/new-owner-path');assert.equal(await page.evaluate(()=>qa.writes.length),1);
 const publicURL=await page.evaluate(async()=>{const{selectedOfficialWebsite}=await import('/assets/enrichment/official-source-policy.mjs');return selectedOfficialWebsite({...qa.base,profile:qa.profile,owner_content:qa.owner_content});});assert.equal(publicURL,'https://old.example/new-owner-path');await panel.screenshot({path:path.join(out,`${family}-${width}-saved.png`)});
 await panel.getByRole('button',{name:'Remove website link'}).click();assert.equal(await input.inputValue(),'');await panel.getByText('Website removal is in your draft. Save page to publish it.',{exact:true}).waitFor();await save();assert.equal(await panel.getAttribute('data-source-state'),'owner-clear');assert.equal(await page.evaluate(()=>qa.owner_content.website),null);await page.evaluate(()=>qa.mount());await panel.waitFor();assert.equal(await panel.getAttribute('data-source-state'),'owner-clear');assert.equal(await input.inputValue(),'');
 assert.equal(await page.evaluate(async()=>{const{selectedOfficialWebsite}=await import('/assets/enrichment/official-source-policy.mjs');return selectedOfficialWebsite({...qa.base,website:'https://stale.example/',profile:qa.profile,owner_content:qa.owner_content});}),'');
 await input.fill('https://old.example/stale');await panel.getByRole('button',{name:'Use saved choice'}).click();assert.equal(await input.inputValue(),'');assert.equal(await page.evaluate(()=>qa.writes.length),2);
 await panel.screenshot({path:path.join(out,`${family}-${width}-cleared.png`)});if(family==='business'){await page.locator('.zp-grid').screenshot({path:path.join(out,`${family}-${width}-full-editor.png`)});await page.evaluate(()=>document.documentElement.dataset.theme='light');await panel.evaluate(async n=>{await document.fonts.ready;await Promise.allSettled(n.getAnimations({subtree:true}).filter(a=>a.effect.getComputedTiming().iterations!==Infinity).map(a=>a.finished));});await panel.screenshot({path:path.join(out,`${family}-${width}-light.png`)});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);assert.deepEqual(errors,[]);report.cases.push({width,family,owner_edit_same_domain:true,clear_reload:true,public_policy:true,keyboard_restore_saved_and_clear:true,errors});await page.close();
 }
 for(const width of[390,1440]){const page=await browser.newPage({viewport:{width,height:1000}});page.on('dialog',d=>d.accept());await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+'/tests/browser/source-health-owner/fixture.html');const panel=page.getByRole('region',{name:'Website and source review'}),input=page.getByLabel('Official website address');await panel.waitFor();
 await page.evaluate(()=>{qa.base.website=null;qa.profile={};return qa.mount();});await panel.waitFor();assert.equal(await panel.getAttribute('data-source-state'),'no-url');await panel.screenshot({path:path.join(out,`sparse-${width}.png`)});
 await input.fill('https://owner.example/new');await page.evaluate(()=>qa.mode='lost');await page.getByRole('button',{name:'Save page',exact:true}).click();await page.getByRole('button',{name:'Retry this save',exact:true}).waitFor();assert(await input.isDisabled());await page.getByRole('button',{name:'Retry this save',exact:true}).click();await page.getByText('Saved. Your page details and menu are updated.',{exact:true}).waitFor();assert.deepEqual(await page.evaluate(()=>qa.writes[0]),await page.evaluate(()=>qa.writes[1]));assert.equal(await panel.getAttribute('data-source-state'),'owner-url');
 await input.fill('https://other.example/');await page.evaluate(()=>qa.mode='conflict');await page.getByRole('button',{name:'Save page',exact:true}).click();await page.getByText('This page changed elsewhere. Reload the latest details before editing again. Your unsaved text is still here.',{exact:true}).waitFor();assert.equal(await input.inputValue(),'https://other.example/');assert.equal(await page.evaluate(()=>qa.owner_content.website),'https://owner.example/new');
 await page.evaluate(()=>{qa.actor='';});await page.getByText('Your account or workspace changed. Reopen Business home.',{exact:true}).waitFor();assert.equal(await panel.count(),0);report.cases.push({width,scenario:'sparse/lost-response/CAS/account-change',passed:true});await page.close();
 const denied=await browser.newPage({viewport:{width,height:1000}});await denied.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await denied.goto(origin+'/tests/browser/source-health-owner/fixture.html');await denied.getByRole('region',{name:'Website and source review'}).waitFor();await denied.evaluate(()=>{qa.mode='read-fail';return qa.mount();});await denied.getByText('Your current access could not be confirmed. Sign in and reopen Business home before editing.',{exact:true}).waitFor();assert.equal(await denied.getByRole('region',{name:'Website and source review'}).count(),0);assert.equal(await denied.evaluate(()=>qa.writes.length),0);report.cases.push({width,scenario:'authorization-refused-no-private-panel',passed:true});await denied.close();
 }
 for(const width of[390,1440]){const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let rejected=false;await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!==origin)return route.abort();if(url.pathname==='/assets/suite/source-health.mjs'&&!url.search&&!rejected){rejected=true;return route.fulfill({status:503,contentType:'text/javascript',body:''});}return route.continue();});await page.goto(origin+'/tests/browser/source-health-owner/fixture.html');await page.getByRole('button',{name:'Retry website review',exact:true}).waitFor();assert.equal(await page.getByLabel('Official website address').inputValue(),'https://old.example/business');assert.equal(await page.evaluate(()=>qa.writes.length),0);await page.getByRole('button',{name:'Retry website review',exact:true}).click();await page.getByRole('region',{name:'Website and source review'}).waitFor();assert.equal(await page.getByRole('region',{name:'Website and source review'}).getAttribute('data-source-state'),'import-held');assert.deepEqual(errors,[]);report.cases.push({width,scenario:'optional-tool-load-failure-and-real-module-retry',passed:true});await page.close();}
 report.status='passed';
}catch(error){report.status='failed';report.failure=error.message;throw error;}finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');await browser?.close();await new Promise(r=>server.close(r));}console.log(JSON.stringify({status:report.status,cases:report.cases.length}));})().catch(e=>{console.error(e);process.exitCode=1;});
